local _, ns = ...

-- Alliance Era leveling route for Duskwood, levels 28-29.
-- Forever quests from the Duskwood list are woven into the Darkshire and Raven Hill loop.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    DUSKWOOD = 1431,
    WESTFALL = 1436,
    STORMWIND = 1453,
    ELWYNN = 1429,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-28-29-duskwood",
    title = "28-29 Duskwood",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Alliance" },
            { level = { min = 28 } },
        },
    },
    goals = {
        {
            id = "accept-66-the-legend-of-stalvan",
            kind = "accept",
            priority = 20,
            text = "Accept The Legend of Stalvan from Madame Eva in Darkshire.",
            complete = QuestState(66, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7572, 0.4534, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "accept-101-the-totem-of-infliction",
            kind = "accept",
            priority = 30,
            text = "Accept The Totem of Infliction from Madame Eva in Darkshire.",
            complete = QuestState(101, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7572, 0.4534, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "note-56-darkshire",
            kind = "note",
            priority = 40,
            text = "Set your hearth in Darkshire with Innkeeper Trelayne.",
            route = {
                Point(MAP.DUSKWOOD, 0.7390, 0.4440, "Innkeeper Trelayne",
                    "Travel to Innkeeper Trelayne."),
            },
        },
        {
            id = "accept-56-the-night-watch",
            kind = "accept",
            priority = 50,
            text = "Accept The Night Watch from Commander Althea Ebonlocke in Darkshire.",
            complete = QuestState(56, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7360, 0.4685, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "turnin-66-the-legend-of-stalvan",
            kind = "turnin",
            priority = 60,
            text = "Turn in The Legend of Stalvan to Clerk Daltry in Darkshire.",
            dependsOn = { "accept-66-the-legend-of-stalvan" },
            complete = QuestState(66, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7264, 0.4684, "Clerk Daltry",
                    "Travel to Clerk Daltry."),
            },
        },
        {
            id = "accept-67-the-legend-of-stalvan",
            kind = "accept",
            priority = 70,
            text = "Accept The Legend of Stalvan from Clerk Daltry in Darkshire.",
            complete = QuestState(67, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7264, 0.4684, "Clerk Daltry",
                    "Travel to Clerk Daltry."),
            },
        },
        {
            id = "accept-173-worgen-in-the-woods",
            kind = "accept",
            priority = 80,
            text = "Accept Worgen in the Woods from Calor in Darkshire.",
            complete = QuestState(173, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7524, 0.4800, "Calor",
                    "Travel to Calor."),
            },
        },
        {
            id = "accept-165-the-hermit",
            kind = "accept",
            priority = 90,
            text = "Accept The Hermit from Elaine Carevin in Darkshire.",
            complete = QuestState(165, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7533, 0.4862, "Elaine Carevin",
                    "Travel to Elaine Carevin."),
            },
        },
        {
            id = "accept-164-deliveries-to-sven",
            kind = "accept",
            priority = 100,
            text = "Accept Deliveries to Sven from Elaine Carevin in Darkshire.",
            complete = QuestState(164, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7533, 0.4862, "Elaine Carevin",
                    "Travel to Elaine Carevin."),
            },
        },
        {
            id = "accept-163-raven-hill",
            kind = "accept",
            priority = 110,
            text = "Accept Raven Hill from Elaine Carevin in Darkshire.",
            complete = QuestState(163, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7531, 0.4851, "Elaine Carevin",
                    "Travel to Elaine Carevin."),
            },
        },
        {
            id = "accept-96139-the-valor-family",
            kind = "accept",
            priority = 111,
            conditions = { level = { min = 22 } },
            text = "Accept The Valor Family from Sirra Von'Indi in Darkshire.",
            complete = QuestState(96139, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "accept-96137-iras-dagger",
            kind = "accept",
            priority = 112,
            conditions = { level = { min = 24 } },
            text = "Accept Ira's Dagger from Sirra Von'Indi in Darkshire.",
            complete = QuestState(96137, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "accept-96138-merricks-bow",
            kind = "accept",
            priority = 113,
            conditions = { level = { min = 28 } },
            text = "Accept Merrick's Bow from Sirra Von'Indi in Darkshire.",
            complete = QuestState(96138, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "accept-174-look-to-the-stars",
            kind = "accept",
            priority = 120,
            text = "Accept Look To The Stars from Viktori Prism'Antras in Darkshire.",
            complete = QuestState(174, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7979, 0.4797, "Viktori Prism'Antras",
                    "Travel to Viktori Prism'Antras."),
            },
        },
        {
            id = "objective-174-look-to-the-stars",
            kind = "objective",
            priority = 130,
            text = "Buy a Bronze Tube from Herble Baubbletump in Darkshire He does only have a limited supply of these and you may have to wait for him to stock up. If he does not have any you can easily fly to Stormwind where you can buy these from Billibub Cogspinner in the Dwarven District or the Auction House.",
            dependsOn = { "accept-174-look-to-the-stars" },
            complete = QuestState(174, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.7800, 0.4800, "Herble Baubbletump",
                    "Travel to Herble Baubbletump."),
            },
        },
        {
            id = "turnin-174-look-to-the-stars",
            kind = "turnin",
            priority = 140,
            text = "Turn in Look To The Stars to Viktori Prism'Antras in Darkshire.",
            dependsOn = { "objective-174-look-to-the-stars" },
            complete = QuestState(174, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7979, 0.4797, "Viktori Prism'Antras",
                    "Travel to Viktori Prism'Antras."),
            },
        },
        {
            id = "accept-175-look-to-the-stars",
            kind = "accept",
            priority = 150,
            text = "Accept Look To The Stars from Viktori Prism'Antras in Darkshire.",
            complete = QuestState(175, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7979, 0.4797, "Viktori Prism'Antras",
                    "Travel to Viktori Prism'Antras."),
            },
        },
        {
            id = "turnin-175-look-to-the-stars",
            kind = "turnin",
            priority = 160,
            text = "Turn in Look To The Stars to Blind Mary in Tranquil Gardens Cemetery.",
            dependsOn = { "accept-175-look-to-the-stars" },
            complete = QuestState(175, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.8180, 0.5929, "Blind Mary",
                    "Travel to Blind Mary."),
            },
        },
        {
            id = "accept-177-look-to-the-stars",
            kind = "accept",
            priority = 170,
            text = "Accept Look To The Stars from Blind Mary in Tranquil Gardens Cemetery.",
            complete = QuestState(177, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.8180, 0.5929, "Blind Mary",
                    "Travel to Blind Mary."),
            },
        },
        {
            id = "objective-177-look-to-the-stars",
            kind = "objective",
            priority = 180,
            text = "Kill the Insane Ghoul which can be found patrolling the Tranquil Gardens Cemetary around and collect Mary's Looking Glass.",
            dependsOn = { "accept-177-look-to-the-stars" },
            complete = QuestState(177, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.7800, 0.7000, "Insane Ghoul",
                    "Travel to Insane Ghoul."),
            },
        },
        {
            id = "objective-96137-black-ravager",
            kind = "objective",
            priority = 185,
            conditions = { level = { min = 24 } },
            text = "Ira's Dagger: slay 7 Black Ravagers.",
            dependsOn = { "accept-96137-iras-dagger" },
            complete = QuestObjective(96137, 2),
            route = {
                Point(MAP.DUSKWOOD, 0.6940, 0.3580, "Black Ravager",
                    "Travel to Black Ravager."),
            },
        },
        {
            id = "objective-101-3-skeleton-finger",
            kind = "objective",
            priority = 190,
            text = "Collect 10 Skeleton Finger from skeletons in in Tranquil Gardens Cemetery.",
            dependsOn = { "accept-101-the-totem-of-infliction" },
            complete = QuestObjective(101, 3),
            route = {
                Point(MAP.DUSKWOOD, 0.7689, 0.7207, "Skeletal Warrior",
                    "Travel to Skeletal Warrior."),
            },
        },
        {
            id = "objective-56-the-night-watch",
            kind = "objective",
            priority = 200,
            text = "Kill 8 Skeletal Warrior and 6 Skeletal Mage in Tranquil Gardens Cemetery.",
            dependsOn = { "accept-56-the-night-watch" },
            complete = QuestState(56, "complete"),
        },
        {
            id = "objective-173-worgen-in-the-woods",
            kind = "objective",
            priority = 220,
            text = "Kill 6 Nightbane Shadow Weaver in the The Rotting Orchard Southwest of the town of Darkshire.",
            dependsOn = { "accept-173-worgen-in-the-woods" },
            complete = QuestState(173, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.6300, 0.7000, "Nightbane Shadow Weaver",
                    "Travel to Nightbane Shadow Weaver."),
            },
        },
        {
            id = "turnin-173-worgen-in-the-woods",
            kind = "turnin",
            priority = 240,
            text = "Turn in Worgen in the Woods to Calor in Darkshire.",
            dependsOn = { "objective-173-worgen-in-the-woods" },
            complete = QuestState(173, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7524, 0.4800, "Calor",
                    "Travel to Calor."),
            },
        },
        {
            id = "accept-221-worgen-in-the-woods",
            kind = "accept",
            priority = 250,
            text = "Accept Worgen in the Woods from Calor in Darkshire.",
            complete = QuestState(221, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7524, 0.4800, "Calor",
                    "Travel to Calor."),
            },
        },
        {
            id = "turnin-56-the-night-watch",
            kind = "turnin",
            priority = 260,
            text = "Turn in The Night Watch to Commander Althea Ebonlocke in Darkshire.",
            dependsOn = { "objective-56-the-night-watch" },
            complete = QuestState(56, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7360, 0.4685, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "accept-57-the-night-watch",
            kind = "accept",
            priority = 270,
            text = "Accept The Night Watch from Commander Althea Ebonlocke in Darkshire.",
            complete = QuestState(57, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7360, 0.4685, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "turnin-177-look-to-the-stars",
            kind = "turnin",
            priority = 280,
            text = "Turn in Look To The Stars to Viktori Prism'Antras in Darkshire.",
            dependsOn = { "objective-177-look-to-the-stars" },
            complete = QuestState(177, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7979, 0.4797, "Viktori Prism'Antras",
                    "Travel to Viktori Prism'Antras."),
            },
        },
        {
            id = "accept-181-look-to-the-stars",
            kind = "accept",
            priority = 290,
            text = "Accept Look To The Stars from Viktori Prism'Antras in Darkshire.",
            complete = QuestState(181, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7979, 0.4797, "Viktori Prism'Antras",
                    "Travel to Viktori Prism'Antras."),
            },
        },
        {
            id = "objective-221-worgen-in-the-woods",
            kind = "objective",
            priority = 310,
            text = "Kill 12 Nightbane Dark Runner found in The Rotting Orchard.",
            dependsOn = { "accept-221-worgen-in-the-woods" },
            complete = QuestState(221, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.6300, 0.7000, "Nightbane Dark Runner",
                    "Travel to Nightbane Dark Runner."),
            },
        },
        {
            id = "turnin-221-worgen-in-the-woods",
            kind = "turnin",
            priority = 330,
            text = "Turn in Worgen in the Woods to Calor in Darkshire.",
            dependsOn = { "objective-221-worgen-in-the-woods" },
            complete = QuestState(221, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7524, 0.4800, "Calor",
                    "Travel to Calor."),
            },
        },
        {
            id = "accept-222-worgen-in-the-woods",
            kind = "accept",
            priority = 340,
            text = "Accept Worgen in the Woods from Calor in Darkshire.",
            complete = QuestState(222, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7524, 0.4800, "Calor",
                    "Travel to Calor."),
            },
        },
        {
            id = "objective-222-worgen-in-the-woods",
            kind = "objective",
            priority = 360,
            text = "Kill 8 Nightbane Vile Fang and 8 Nightbane Tainted One around the Western edge of the Tranquil Gardens Cemetary. Tainted Ones are found further South of this area.",
            dependsOn = { "accept-222-worgen-in-the-woods" },
            complete = QuestState(222, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.7400, 0.6700, "Continue toward Worgen in the Woods",
                    "Continue toward Worgen in the Woods."),
                Point(MAP.DUSKWOOD, 0.7400, 0.7400, "Nightbane Vile Fang",
                    "Travel to Nightbane Vile Fang."),
            },
        },
        {
            id = "objective-181-look-to-the-stars",
            kind = "objective",
            priority = 380,
            text = "Find and kill Zzarc' Vul collect the Ogre's Monocle inside the Vul'Gol Ogre Mound cave.",
            dependsOn = { "accept-181-look-to-the-stars" },
            complete = QuestState(181, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.3600, 0.8300, "Zzarc' Vul",
                    "Travel to Zzarc' Vul."),
            },
        },
        {
            id = "objective-96137-young-black-ravager",
            kind = "objective",
            priority = 381,
            conditions = { level = { min = 24 } },
            text = "Ira's Dagger: slay 10 Young Black Ravagers.",
            dependsOn = { "accept-96137-iras-dagger" },
            complete = QuestObjective(96137, 1),
            route = {
                Point(MAP.DUSKWOOD, 0.2380, 0.7900, "Young Black Ravager",
                    "Travel to Young Black Ravager."),
            },
        },
        {
            id = "objective-96139-the-valor-family",
            kind = "objective",
            priority = 395,
            conditions = { level = { min = 22 } },
            useClientPin = true,
            text = "The Valor Family: search Raven Hill. No saved spot for this, so the guide follows the pin in your quest log.",
            dependsOn = { "accept-96139-the-valor-family" },
            complete = QuestState(96139, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.1833, 0.5625, "Raven Hill",
                    "Travel to Raven Hill."),
            },
        },
        {
            id = "turnin-163-raven-hill",
            kind = "turnin",
            priority = 400,
            text = "Turn in Raven Hill to Jitters in Raven Hill.",
            dependsOn = { "accept-163-raven-hill" },
            complete = QuestState(163, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.1833, 0.5625, "Jitters",
                    "Travel to Jitters."),
            },
        },
        {
            id = "accept-5-jitters-growling-gut",
            kind = "accept",
            priority = 410,
            text = "Accept Jitters' Growling Gut from Jitters in Raven Hill.",
            complete = QuestState(5, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.1838, 0.5643, "Jitters",
                    "Travel to Jitters."),
            },
        },
        {
            id = "objective-57-the-night-watch",
            kind = "objective",
            priority = 420,
            text = "Travel North of Raven Hill and kill 15 Skeletal Fiend and 15 Rotting Horror.",
            dependsOn = { "accept-57-the-night-watch" },
            complete = QuestState(57, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.2000, 0.4500, "Skeletal Fiend",
                    "Travel to Skeletal Fiend."),
            },
        },
        {
            id = "turnin-165-the-hermit",
            kind = "turnin",
            priority = 430,
            text = "Turn in The Hermit to Abercrombie in Raven Hill Cemetery.",
            dependsOn = { "accept-165-the-hermit" },
            complete = QuestState(165, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.2798, 0.3151, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "accept-148-supplies-from-darkshire",
            kind = "accept",
            priority = 440,
            text = "Accept Supplies from Darkshire from Abercrombie in Raven Hill Cemetery.",
            complete = QuestState(148, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.2798, 0.3151, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "objective-101-2-vial-of-spider-venom",
            kind = "objective",
            priority = 450,
            text = "Kill Black Widow Hatchling for 5 Vial of Spider Venom around the area, also collect 6 Gooey Spider Leg for a later quest.",
            dependsOn = { "accept-101-the-totem-of-infliction" },
            complete = QuestObjective(101, 2),
            route = {
                Point(MAP.DUSKWOOD, 0.2926, 0.5180, "Black Widow Hatchling",
                    "Travel to Black Widow Hatchling."),
            },
        },
        {
            id = "objective-93-gooey-spider-leg",
            kind = "objective",
            priority = 460,
            text = "Kill Black Widow Hatchling for 6 Gooey Spider Leg for a later quest.",
            dependsOn = { "accept-93-dusky-crab-cakes" },
            complete = QuestState(93, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.2926, 0.5180, "Black Widow Hatchling",
                    "Travel to Black Widow Hatchling."),
            },
        },
        {
            id = "objective-101-1-ghoul-fang",
            kind = "objective",
            priority = 470,
            text = "Kill ghouls and collect 10 Ghoul Fang in Raven Hill Cemetery.",
            dependsOn = { "accept-101-the-totem-of-infliction" },
            complete = QuestObjective(101, 1),
            route = {
                Point(MAP.DUSKWOOD, 0.2579, 0.3339, "Rotted One",
                    "Travel to Rotted One."),
            },
        },
        {
            id = "objective-96138-merricks-bow",
            kind = "objective",
            priority = 471,
            conditions = { level = { min = 28 } },
            text = "Merrick's Bow: slay 8 Splinter Fist Warriors and 4 Splinter Fist Taskmasters in Raven Hill Cemetery.",
            dependsOn = { "accept-96138-merricks-bow" },
            complete = QuestState(96138, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.3420, 0.7740, "Splinter Fist Warrior",
                    "Travel to Splinter Fist Warrior."),
                Point(MAP.DUSKWOOD, 0.3400, 0.7380, "Splinter Fist Taskmaster",
                    "Travel to Splinter Fist Taskmaster."),
            },
        },
        {
            id = "accept-225-the-weathered-grave",
            kind = "accept",
            priority = 490,
            text = "Accept The Weathered Grave in Forlorn Rowe.",
            complete = QuestState(225, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.1768, 0.2915, "Forlorn Rowe",
                    "Travel to Forlorn Rowe."),
            },
        },
        {
            id = "turnin-164-deliveries-to-sven",
            kind = "turnin",
            priority = 510,
            text = "Turn in Deliveries to Sven to Sven Yorgen in The Hushed Bank.",
            dependsOn = { "accept-164-deliveries-to-sven" },
            complete = QuestState(164, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.0782, 0.3406, "Sven Yorgen",
                    "Travel to Sven Yorgen."),
            },
        },
        {
            id = "accept-95-sven-s-revenge",
            kind = "accept",
            priority = 520,
            text = "Accept Sven's Revenge from Sven Yorgen in The Hushed Bank.",
            complete = QuestState(95, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.0782, 0.3406, "Sven Yorgen",
                    "Travel to Sven Yorgen."),
            },
        },
        {
            id = "turnin-96139-the-valor-family",
            kind = "turnin",
            priority = 535,
            conditions = { level = { min = 22 } },
            text = "Turn in The Valor Family to Sirra Von'Indi in Darkshire.",
            dependsOn = { "objective-96139-the-valor-family" },
            complete = QuestState(96139, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "turnin-96137-iras-dagger",
            kind = "turnin",
            priority = 536,
            conditions = { level = { min = 24 } },
            text = "Turn in Ira's Dagger to Sirra Von'Indi in Darkshire.",
            dependsOn = { "objective-96137-young-black-ravager", "objective-96137-black-ravager" },
            complete = QuestState(96137, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "turnin-96138-merricks-bow",
            kind = "turnin",
            priority = 537,
            conditions = { level = { min = 28 } },
            text = "Turn in Merrick's Bow to Sirra Von'Indi in Darkshire.",
            dependsOn = { "objective-96138-merricks-bow" },
            complete = QuestState(96138, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "accept-98447-the-valor-family",
            kind = "accept",
            priority = 538,
            conditions = { level = { min = 27 } },
            text = "Accept The Valor Family from Sirra Von'Indi in Darkshire.",
            dependsOn = { "turnin-96139-the-valor-family" },
            complete = QuestState(98447, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "turnin-5-jitters-growling-gut",
            kind = "turnin",
            priority = 540,
            text = "Turn in Jitters' Growling Gut to Chef Grual in Darkshire.",
            dependsOn = { "accept-5-jitters-growling-gut" },
            complete = QuestState(5, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7388, 0.4343, "Chef Grual",
                    "Travel to Chef Grual."),
            },
        },
        {
            id = "accept-93-dusky-crab-cakes",
            kind = "accept",
            priority = 550,
            text = "Accept Dusky Crab Cakes from Chef Grual in Darkshire.",
            complete = QuestState(93, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7388, 0.4343, "Chef Grual",
                    "Travel to Chef Grual."),
            },
        },
        {
            id = "turnin-93-dusky-crab-cakes",
            kind = "turnin",
            priority = 560,
            text = "Turn in Dusky Crab Cakes to Chef Grual in Darkshire.",
            dependsOn = { "objective-93-gooey-spider-leg" },
            complete = QuestState(93, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7388, 0.4343, "Chef Grual",
                    "Travel to Chef Grual."),
            },
        },
        {
            id = "accept-240-return-to-jitters",
            kind = "accept",
            priority = 570,
            text = "Accept Return to Jitters from Chef Grual in Darkshire.",
            complete = QuestState(240, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7386, 0.4349, "Chef Grual",
                    "Travel to Chef Grual."),
            },
        },
        {
            id = "turnin-57-the-night-watch",
            kind = "turnin",
            priority = 580,
            text = "Turn in The Night Watch to Commander Althea Ebonlocke in Darkshire.",
            dependsOn = { "objective-57-the-night-watch" },
            complete = QuestState(57, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7360, 0.4685, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "accept-58-the-night-watch",
            kind = "accept",
            priority = 590,
            text = "Accept The Night Watch from Commander Althea Ebonlocke in Darkshire.",
            complete = QuestState(58, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7360, 0.4685, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "turnin-225-the-weathered-grave",
            kind = "turnin",
            priority = 600,
            text = "Turn in The Weathered Grave to Sirra Von'Indi in Darkshire.",
            dependsOn = { "accept-225-the-weathered-grave" },
            complete = QuestState(225, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7258, 0.4757, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "accept-227-morgan-ladimore",
            kind = "accept",
            priority = 610,
            text = "Accept Morgan Ladimore from Sirra Von'Indi in Darkshire.",
            complete = QuestState(227, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7258, 0.4757, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "turnin-227-morgan-ladimore",
            kind = "turnin",
            priority = 620,
            text = "Turn in Morgan Ladimore to Commander Althea Ebonlocke in Darkshire.",
            dependsOn = { "accept-227-morgan-ladimore" },
            complete = QuestState(227, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7360, 0.4685, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "accept-228-mor-ladim",
            kind = "accept",
            priority = 630,
            text = "Accept Mor'Ladim from Commander Althea Ebonlocke in Darkshire.",
            complete = QuestState(228, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7360, 0.4685, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "turnin-101-the-totem-of-infliction",
            kind = "turnin",
            priority = 640,
            text = "Turn in The Totem of Infliction to Madame Eva in Darkshire.",
            dependsOn = { "objective-101-3-skeleton-finger", "objective-101-2-vial-of-spider-venom", "objective-101-1-ghoul-fang" },
            complete = QuestState(101, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7578, 0.4533, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "turnin-148-supplies-from-darkshire",
            kind = "turnin",
            priority = 650,
            text = "Turn in Supplies from Darkshire to Madame Eva in Darkshire.",
            dependsOn = { "accept-148-supplies-from-darkshire" },
            complete = QuestState(148, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7572, 0.4534, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "accept-149-ghost-hair-thread",
            kind = "accept",
            priority = 660,
            text = "Accept Ghost Hair Thread from Madame Eva in Darkshire.",
            complete = QuestState(149, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7572, 0.4534, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "turnin-222-worgen-in-the-woods",
            kind = "turnin",
            priority = 670,
            text = "Turn in Worgen in the Woods to Calor in Darkshire.",
            dependsOn = { "objective-222-worgen-in-the-woods" },
            complete = QuestState(222, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7524, 0.4800, "Calor",
                    "Travel to Calor."),
            },
        },
        {
            id = "accept-223-worgen-in-the-woods",
            kind = "accept",
            priority = 680,
            text = "Accept Worgen in the Woods from Calor in Darkshire.",
            complete = QuestState(223, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7524, 0.4800, "Calor",
                    "Travel to Calor."),
            },
        },
        {
            id = "turnin-223-worgen-in-the-woods",
            kind = "turnin",
            priority = 690,
            text = "Turn in Worgen in the Woods to Jonathan Carevin in Darkshire.",
            dependsOn = { "accept-223-worgen-in-the-woods" },
            complete = QuestState(223, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7533, 0.4903, "Jonathan Carevin",
                    "Travel to Jonathan Carevin."),
            },
        },
        {
            id = "turnin-181-look-to-the-stars",
            kind = "turnin",
            priority = 700,
            text = "Turn in Look To The Stars to Viktori Prism'Antras in Darkshire.",
            dependsOn = { "objective-181-look-to-the-stars" },
            complete = QuestState(181, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7979, 0.4797, "Viktori Prism'Antras",
                    "Travel to Viktori Prism'Antras."),
            },
        },
        {
            id = "turnin-149-ghost-hair-thread",
            kind = "turnin",
            priority = 710,
            text = "Turn in Ghost Hair Thread to Blind Mary in Darkshire.",
            dependsOn = { "accept-149-ghost-hair-thread" },
            complete = QuestState(149, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.8180, 0.5929, "Blind Mary",
                    "Travel to Blind Mary."),
            },
        },
        {
            id = "accept-154-return-the-comb",
            kind = "accept",
            priority = 720,
            text = "Accept Return the Comb from Blind Mary in Darkshire.",
            complete = QuestState(154, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.8180, 0.5929, "Blind Mary",
                    "Travel to Blind Mary."),
            },
        },
        {
            id = "turnin-154-return-the-comb",
            kind = "turnin",
            priority = 730,
            text = "Turn in Return the Comb to Madame Eva in Darkshire.",
            dependsOn = { "accept-154-return-the-comb" },
            complete = QuestState(154, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7572, 0.4534, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "accept-157-deliver-the-thread",
            kind = "accept",
            priority = 740,
            text = "Accept Deliver the Thread from Madame Eva in Darkshire.",
            complete = QuestState(157, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7572, 0.4534, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "turnin-95-sven-s-revenge",
            kind = "turnin",
            priority = 760,
            text = "Turn in Sven's Revenge in The Yorgen Farmstead.",
            dependsOn = { "accept-95-sven-s-revenge" },
            complete = QuestState(95, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.4979, 0.7786, "The Yorgen Farmstead",
                    "Travel to The Yorgen Farmstead."),
            },
        },
        {
            id = "accept-230-sven-s-camp",
            kind = "accept",
            priority = 770,
            text = "Accept Sven's Camp in The Yorgen Farmstead.",
            complete = QuestState(230, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.4979, 0.7786, "The Yorgen Farmstead",
                    "Travel to The Yorgen Farmstead."),
            },
        },
        {
            id = "objective-98447-the-valor-family",
            kind = "objective",
            priority = 781,
            conditions = { level = { min = 27 } },
            text = "The Valor Family: find the cause of the ghosts at Ol' Sandy in Raven Hill.",
            dependsOn = { "accept-98447-the-valor-family" },
            complete = QuestState(98447, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.1720, 0.5380, "Ol' Sandy",
                    "Travel to Ol' Sandy."),
            },
        },
        {
            id = "turnin-240-return-to-jitters",
            kind = "turnin",
            priority = 790,
            text = "Turn in Return to Jitters to Jitters in R Raven Hill.",
            dependsOn = { "accept-240-return-to-jitters" },
            complete = QuestState(240, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.1840, 0.5644, "Jitters",
                    "Travel to Jitters."),
            },
        },
        {
            id = "turnin-157-deliver-the-thread",
            kind = "turnin",
            priority = 800,
            text = "Turn in Deliver the Thread to Abercrombie in Raven Hill Cemetery.",
            dependsOn = { "accept-157-deliver-the-thread" },
            complete = QuestState(157, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.2798, 0.3151, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "accept-158-zombie-juice",
            kind = "accept",
            priority = 810,
            text = "Accept Zombie Juice from Abercrombie in Raven Hill Cemetery.",
            complete = QuestState(158, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.2798, 0.3151, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "objective-58-the-night-watch",
            kind = "objective",
            priority = 830,
            text = "Kill 20 Plague Spreader underground in Dawning Wood Catacombs.",
            dependsOn = { "accept-58-the-night-watch" },
            complete = QuestState(58, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.2370, 0.3523, "Continue toward The Night Watch",
                    "Continue toward The Night Watch."),
                Point(MAP.DUSKWOOD, 0.2566, 0.3432, "Plague Spreader",
                    "Travel to Plague Spreader."),
            },
        },
        {
            id = "objective-228-mor-ladim",
            kind = "objective",
            priority = 840,
            text = "Kill Mor'Ladim and collect Mor'Ladim's Skull in Forlorn Rowe This is a group quest and tough to solo, you can skip this safely.",
            dependsOn = { "accept-228-mor-ladim" },
            complete = QuestState(228, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.1668, 0.3737, "Mor'Ladim",
                    "Travel to Mor'Ladim."),
            },
        },
        {
            id = "turnin-230-sven-s-camp",
            kind = "turnin",
            priority = 860,
            text = "Turn in Sven's Camp to Sven Yorgen in The Hushed Bank.",
            dependsOn = { "accept-230-sven-s-camp" },
            complete = QuestState(230, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.0782, 0.3406, "Sven Yorgen",
                    "Travel to Sven Yorgen."),
            },
        },
        {
            id = "accept-262-the-shadowy-figure",
            kind = "accept",
            priority = 870,
            text = "Accept The Shadowy Figure from Sven Yorgen in The Hushed Bank.",
            complete = QuestState(262, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.0782, 0.3406, "Sven Yorgen",
                    "Travel to Sven Yorgen."),
            },
        },
        {
            id = "turnin-67-the-legend-of-stalvan",
            kind = "turnin",
            priority = 900,
            text = "Turn in The Legend of Stalvan in Moonbrook.",
            dependsOn = { "accept-67-the-legend-of-stalvan" },
            complete = QuestState(67, "completed"),
            route = {
                Point(MAP.WESTFALL, 0.4152, 0.6672, "Moonbrook",
                    "Travel to Moonbrook."),
            },
        },
        {
            id = "accept-68-the-legend-of-stalvan",
            kind = "accept",
            priority = 910,
            text = "Accept The Legend of Stalvan in Moonbrook.",
            complete = QuestState(68, "activeOrCompleted"),
            route = {
                Point(MAP.WESTFALL, 0.4152, 0.6674, "Moonbrook",
                    "Travel to Moonbrook."),
            },
        },
        {
            id = "turnin-98447-the-valor-family",
            kind = "turnin",
            priority = 921,
            conditions = { level = { min = 27 } },
            text = "Turn in The Valor Family to Sirra Von'Indi in Darkshire.",
            dependsOn = { "objective-98447-the-valor-family" },
            complete = QuestState(98447, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "turnin-158-zombie-juice",
            kind = "turnin",
            priority = 930,
            text = "Turn in Zombie Juice to Tavernkeep Smitts in Darkshire.",
            dependsOn = { "accept-158-zombie-juice" },
            complete = QuestState(158, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7380, 0.4440, "Tavernkeep Smitts",
                    "Travel to Tavernkeep Smitts."),
            },
        },
        {
            id = "accept-156-gather-rot-blossoms",
            kind = "accept",
            priority = 940,
            text = "Accept Gather Rot Blossoms from Tavernkeep Smitts in Darkshire.",
            complete = QuestState(156, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7380, 0.4440, "Tavernkeep Smitts",
                    "Travel to Tavernkeep Smitts."),
            },
        },
        {
            id = "turnin-58-the-night-watch",
            kind = "turnin",
            priority = 950,
            text = "Turn in The Night Watch to Commander Althea Ebonlocke in Darkshire.",
            dependsOn = { "objective-58-the-night-watch" },
            complete = QuestState(58, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7360, 0.4685, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "turnin-228-mor-ladim",
            kind = "turnin",
            priority = 960,
            text = "Turn in Mor'Ladim to Commander Althea Ebonlocke in Darkshire.",
            dependsOn = { "objective-228-mor-ladim" },
            complete = QuestState(228, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7357, 0.4691, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "accept-229-the-daughter-who-lived",
            kind = "accept",
            priority = 970,
            conditions = {
                all = {
                    { quest = { id = 228, state = "completed" } },
                },
            },
            text = "Accept The Daughter Who Lived from Commander Althea Ebonlocke in Darkshire.",
            complete = QuestState(229, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7357, 0.4691, "Commander Althea Ebonlocke",
                    "Travel to Commander Althea Ebonlocke."),
            },
        },
        {
            id = "turnin-229-the-daughter-who-lived",
            kind = "turnin",
            priority = 980,
            conditions = {
                all = {
                    { quest = { id = 228, state = "completed" } },
                },
            },
            text = "Turn in The Daughter Who Lived to Watcher Ladimore in Darkshire.",
            dependsOn = { "accept-229-the-daughter-who-lived" },
            complete = QuestState(229, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7450, 0.4616, "Watcher Ladimore",
                    "Travel to Watcher Ladimore."),
            },
        },
        {
            id = "accept-231-a-daughter-s-love",
            kind = "accept",
            priority = 990,
            conditions = {
                all = {
                    { quest = { id = 228, state = "completed" } },
                },
            },
            text = "Accept A Daughter's Love from Watcher Ladimore in Darkshire.",
            complete = QuestState(231, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7450, 0.4616, "Watcher Ladimore",
                    "Travel to Watcher Ladimore."),
            },
        },
        {
            id = "turnin-68-the-legend-of-stalvan",
            kind = "turnin",
            priority = 1000,
            text = "Turn in The Legend of Stalvan to Clerk Daltry in Darkshire.",
            dependsOn = { "accept-68-the-legend-of-stalvan" },
            complete = QuestState(68, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7256, 0.4683, "Clerk Daltry",
                    "Travel to Clerk Daltry."),
            },
        },
        {
            id = "accept-69-the-legend-of-stalvan",
            kind = "accept",
            priority = 1010,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Accept The Legend of Stalvan from Clerk Daltry in Darkshire.",
            complete = QuestState(69, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7256, 0.4683, "Clerk Daltry",
                    "Travel to Clerk Daltry."),
            },
        },
        {
            id = "turnin-262-the-shadowy-figure",
            kind = "turnin",
            priority = 1020,
            text = "Turn in The Shadowy Figure to Madame Eva in Darkshire.",
            dependsOn = { "accept-262-the-shadowy-figure" },
            complete = QuestState(262, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7572, 0.4534, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "accept-265-the-shadowy-search-continues",
            kind = "accept",
            priority = 1030,
            text = "Accept The Shadowy Search Continues from Madame Eva in Darkshire.",
            complete = QuestState(265, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7572, 0.4534, "Madame Eva",
                    "Travel to Madame Eva."),
            },
        },
        {
            id = "turnin-265-the-shadowy-search-continues",
            kind = "turnin",
            priority = 1040,
            text = "Turn in The Shadowy Search Continues to Clerk Daltry in Darkshire.",
            dependsOn = { "accept-265-the-shadowy-search-continues" },
            complete = QuestState(265, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7264, 0.4684, "Clerk Daltry",
                    "Travel to Clerk Daltry."),
            },
        },
        {
            id = "accept-266-inquire-at-the-inn",
            kind = "accept",
            priority = 1050,
            text = "Accept Inquire at the Inn from Clerk Daltry in Darkshire.",
            complete = QuestState(266, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7264, 0.4684, "Clerk Daltry",
                    "Travel to Clerk Daltry."),
            },
        },
        {
            id = "turnin-266-inquire-at-the-inn",
            kind = "turnin",
            priority = 1060,
            text = "Turn in Inquire at the Inn to Tavernkeep Smitts in Darkshire.",
            dependsOn = { "accept-266-inquire-at-the-inn" },
            complete = QuestState(266, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7380, 0.4440, "Tavernkeep Smitts",
                    "Travel to Tavernkeep Smitts."),
            },
        },
        {
            id = "accept-453-finding-the-shadowy-figure",
            kind = "accept",
            priority = 1070,
            text = "Accept Finding the Shadowy Figure from Tavernkeep Smitts in Darkshire.",
            complete = QuestState(453, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7380, 0.4440, "Tavernkeep Smitts",
                    "Travel to Tavernkeep Smitts."),
            },
        },
        {
            id = "turnin-453-finding-the-shadowy-figure",
            kind = "turnin",
            priority = 1090,
            text = "Turn in Finding the Shadowy Figure to Jitters in Raven Hill.",
            dependsOn = { "accept-453-finding-the-shadowy-figure" },
            complete = QuestState(453, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.1840, 0.5644, "Jitters",
                    "Travel to Jitters."),
            },
        },
        {
            id = "accept-268-return-to-sven",
            kind = "accept",
            priority = 1100,
            text = "Accept Return to Sven from Jitters in Raven Hill.",
            complete = QuestState(268, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.1840, 0.5644, "Jitters",
                    "Travel to Jitters."),
            },
        },
        {
            id = "turnin-268-return-to-sven",
            kind = "turnin",
            priority = 1120,
            text = "Turn in Return to Sven to Sven Yorgen in The Hushed Bank.",
            dependsOn = { "accept-268-return-to-sven" },
            complete = QuestState(268, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.0783, 0.3402, "Sven Yorgen",
                    "Travel to Sven Yorgen."),
            },
        },
        {
            id = "accept-323-proving-your-worth",
            kind = "accept",
            priority = 1130,
            text = "Accept Proving Your Worth in The Hushed Bank.",
            complete = QuestState(323, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.0783, 0.3402, "The Hushed Bank",
                    "Travel to The Hushed Bank."),
            },
        },
        {
            id = "turnin-231-a-daughter-s-love",
            kind = "turnin",
            priority = 1140,
            conditions = {
                all = {
                    { quest = { id = 228, state = "completed" } },
                },
            },
            text = "Turn in A Daughter's Love in Forlorn Rowe.",
            dependsOn = { "accept-231-a-daughter-s-love" },
            complete = QuestState(231, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.1774, 0.2909, "Forlorn Rowe",
                    "Travel to Forlorn Rowe."),
            },
        },
        {
            id = "objective-323-proving-your-worth",
            kind = "objective",
            priority = 1150,
            text = "Kill 3 Skeletal Healer, 15 Skeletal Raider, 3 Skeletal Warder and in Dawning Wood Catacombs The Skeletal Warder are only found inside the Catacombs underground.",
            dependsOn = { "accept-323-proving-your-worth" },
            complete = QuestState(323, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.1601, 0.3707, "Skeletal Healer",
                    "Travel to Skeletal Healer."),
            },
        },
        {
            id = "objective-156-gather-rot-blossoms",
            kind = "objective",
            priority = 1160,
            text = "Kill Rotting Horror and collect 8 Rot Blossom.",
            dependsOn = { "accept-156-gather-rot-blossoms" },
            complete = QuestState(156, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.8107, 0.5780, "Rotting Horror",
                    "Travel to Rotting Horror."),
            },
        },
        {
            id = "turnin-323-proving-your-worth",
            kind = "turnin",
            priority = 1170,
            text = "Turn in Proving Your Worth to Sven Yorgen in The Hushed Bank.",
            dependsOn = { "objective-323-proving-your-worth" },
            complete = QuestState(323, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.0781, 0.3402, "Sven Yorgen",
                    "Travel to Sven Yorgen."),
            },
        },
        {
            id = "accept-269-seeking-wisdom",
            kind = "accept",
            priority = 1180,
            text = "Accept Seeking Wisdom from Sven Yorgen in The Hushed Bank.",
            complete = QuestState(269, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.0781, 0.3402, "Sven Yorgen",
                    "Travel to Sven Yorgen."),
            },
        },
        {
            id = "turnin-156-gather-rot-blossoms",
            kind = "turnin",
            priority = 1200,
            text = "Turn in Gather Rot Blossoms to Tavernkeep Smitts in Darkshire.",
            dependsOn = { "objective-156-gather-rot-blossoms" },
            complete = QuestState(156, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7382, 0.4449, "Tavernkeep Smitts",
                    "Travel to Tavernkeep Smitts."),
            },
        },
        {
            id = "accept-159-juice-delivery",
            kind = "accept",
            priority = 1210,
            text = "Accept Juice Delivery from Tavernkeep Smitts in Darkshire.",
            complete = QuestState(159, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7382, 0.4449, "Tavernkeep Smitts",
                    "Travel to Tavernkeep Smitts."),
            },
        },
        {
            id = "turnin-159-juice-delivery",
            kind = "turnin",
            priority = 1230,
            text = "Turn in Juice Delivery to Abercrombie in Raven Hill Cemetery.",
            dependsOn = { "accept-159-juice-delivery" },
            complete = QuestState(159, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.2806, 0.3149, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "accept-133-ghoulish-effigy",
            kind = "accept",
            priority = 1240,
            text = "Accept Ghoulish Effigy from Abercrombie in Raven Hill Cemetery.",
            complete = QuestState(133, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.2806, 0.3149, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "objective-133-ghoulish-effigy",
            kind = "objective",
            priority = 1250,
            text = "Kill any ghouls and collect 7 Ghoul Rib in Raven Hill Cemetery.",
            dependsOn = { "accept-133-ghoulish-effigy" },
            complete = QuestState(133, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.2424, 0.3770, "Flesh Eater",
                    "Travel to Flesh Eater."),
            },
        },
        {
            id = "turnin-133-ghoulish-effigy",
            kind = "turnin",
            priority = 1260,
            text = "Turn in Ghoulish Effigy to Abercrombie in Raven Hill Cemetery.",
            dependsOn = { "objective-133-ghoulish-effigy" },
            complete = QuestState(133, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.2805, 0.3142, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "accept-134-ogre-thieves",
            kind = "accept",
            priority = 1270,
            text = "Accept Ogre Thieves from Abercrombie in Raven Hill Cemetery.",
            complete = QuestState(134, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.2805, 0.3142, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "objective-134-ogre-thieves",
            kind = "objective",
            priority = 1290,
            text = "Collect Abercrombie's Crate from the crate outside Vul'Gol Ogre Mound.",
            dependsOn = { "accept-134-ogre-thieves" },
            complete = QuestState(134, "complete"),
            route = {
                Point(MAP.DUSKWOOD, 0.3345, 0.7631, "Vul'Gol Ogre Mound",
                    "Travel to Vul'Gol Ogre Mound."),
            },
        },
        {
            id = "turnin-134-ogre-thieves",
            kind = "turnin",
            priority = 1310,
            text = "Turn in Ogre Thieves to Abercrombie in Raven Hill Cemetery.",
            dependsOn = { "objective-134-ogre-thieves" },
            complete = QuestState(134, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.2806, 0.3147, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "accept-160-note-to-the-mayor",
            kind = "accept",
            priority = 1320,
            text = "Accept Note to the Mayor from Abercrombie in Raven Hill Cemetery.",
            complete = QuestState(160, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.2806, 0.3147, "Abercrombie",
                    "Travel to Abercrombie."),
            },
        },
        {
            id = "turnin-160-note-to-the-mayor",
            kind = "turnin",
            priority = 1340,
            text = "Turn in Note to the Mayor to Lord Ello Ebonlocke in Darkshire.",
            dependsOn = { "accept-160-note-to-the-mayor" },
            complete = QuestState(160, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7195, 0.4642, "Lord Ello Ebonlocke",
                    "Travel to Lord Ello Ebonlocke."),
            },
        },
        {
            id = "accept-251-translate-abercrombie-s-note",
            kind = "accept",
            priority = 1350,
            text = "Accept Translate Abercrombie's Note from Lord Ello Ebonlocke in Darkshire.",
            complete = QuestState(251, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7195, 0.4642, "Lord Ello Ebonlocke",
                    "Travel to Lord Ello Ebonlocke."),
            },
        },
        {
            id = "turnin-251-translate-abercrombie-s-note",
            kind = "turnin",
            priority = 1360,
            text = "Turn in Translate Abercrombie's Note to Sirra Von'Indi in Darkshire.",
            dependsOn = { "accept-251-translate-abercrombie-s-note" },
            complete = QuestState(251, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7263, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "accept-401-wait-for-sirra-to-finish",
            kind = "accept",
            priority = 1370,
            text = "Accept Wait for Sirra to Finish from Sirra Von'Indi in Darkshire.",
            complete = QuestState(401, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7263, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "turnin-401-wait-for-sirra-to-finish",
            kind = "turnin",
            priority = 1380,
            text = "Turn in Wait for Sirra to Finish to Sirra Von'Indi in Darkshire.",
            dependsOn = { "accept-401-wait-for-sirra-to-finish" },
            complete = QuestState(401, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7263, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "accept-252-translation-to-ello",
            kind = "accept",
            priority = 1390,
            text = "Accept Translation to Ello from Sirra Von'Indi in Darkshire.",
            complete = QuestState(252, "activeOrCompleted"),
            route = {
                Point(MAP.DUSKWOOD, 0.7263, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "turnin-252-translation-to-ello",
            kind = "turnin",
            priority = 1400,
            text = "Turn in Translation to Ello to Lord Ello Ebonlocke in Darkshire.",
            dependsOn = { "accept-252-translation-to-ello" },
            complete = QuestState(252, "completed"),
            route = {
                Point(MAP.DUSKWOOD, 0.7196, 0.4643, "Lord Ello Ebonlocke",
                    "Travel to Lord Ello Ebonlocke."),
            },
        },
        {
            id = "accept-2923-tinkmaster-overspark",
            kind = "accept",
            priority = 1430,
            text = "Accept Tinkmaster Overspark from Brother Sarno in Cathedral of Light.",
            complete = QuestState(2923, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.4055, 0.3073, "Brother Sarno",
                    "Travel to Brother Sarno."),
            },
        },
        {
            id = "turnin-269-seeking-wisdom",
            kind = "turnin",
            priority = 1440,
            text = "Turn in Seeking Wisdom to Bishop Farthing in Cathedral of Light.",
            dependsOn = { "accept-269-seeking-wisdom" },
            complete = QuestState(269, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.3953, 0.2813, "Bishop Farthing",
                    "Travel to Bishop Farthing."),
            },
        },
        {
            id = "accept-270-the-doomed-fleet",
            kind = "accept",
            priority = 1450,
            text = "Accept The Doomed Fleet from Bishop Farthing in Cathedral of Light.",
            complete = QuestState(270, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.3953, 0.2813, "Bishop Farthing",
                    "Travel to Bishop Farthing."),
            },
        },
        {
            id = "accept-1274-the-missing-diplomat",
            kind = "accept",
            priority = 1460,
            text = "Accept The Missing Diplomat from Thomas in Cathedral of Light.",
            complete = QuestState(1274, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.3978, 0.2852, "Thomas",
                    "Travel to Thomas."),
            },
        },
        {
            id = "turnin-1274-the-missing-diplomat",
            kind = "turnin",
            priority = 1470,
            text = "Turn in The Missing Diplomat to Bishop DeLavey in Stormwind Keep.",
            dependsOn = { "accept-1274-the-missing-diplomat" },
            complete = QuestState(1274, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.7829, 0.2544, "Bishop DeLavey",
                    "Travel to Bishop DeLavey."),
            },
        },
        {
            id = "accept-1241-the-missing-diplomat",
            kind = "accept",
            priority = 1480,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Accept The Missing Diplomat from Bishop DeLavey in Stormwind Keep.",
            complete = QuestState(1241, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.7829, 0.2544, "Bishop DeLavey",
                    "Travel to Bishop DeLavey."),
            },
        },
        {
            id = "accept-538-southshore",
            kind = "accept",
            priority = 1490,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Accept Southshore from Milton Sheaf in Royal Library.",
            complete = QuestState(538, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.7414, 0.0746, "Milton Sheaf",
                    "Travel to Milton Sheaf."),
            },
        },
        {
            id = "turnin-1241-the-missing-diplomat",
            kind = "turnin",
            priority = 1500,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Turn in The Missing Diplomat to Jorgen in Valley of Heroes.",
            dependsOn = { "accept-1241-the-missing-diplomat" },
            complete = QuestState(1241, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.7314, 0.7839, "Jorgen",
                    "Travel to Jorgen."),
            },
        },
        {
            id = "accept-1242-the-missing-diplomat",
            kind = "accept",
            priority = 1510,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Accept The Missing Diplomat from Jorgen in Valley of Heroes.",
            complete = QuestState(1242, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.7314, 0.7839, "Jorgen",
                    "Travel to Jorgen."),
            },
        },
        {
            id = "turnin-69-the-legend-of-stalvan",
            kind = "turnin",
            priority = 1520,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Turn in The Legend of Stalvan to Innkeeper Farley in Lion's Pride Inn.",
            dependsOn = { "accept-69-the-legend-of-stalvan" },
            complete = QuestState(69, "completed"),
            route = {
                Point(MAP.ELWYNN, 0.4378, 0.6584, "Innkeeper Farley",
                    "Travel to Innkeeper Farley."),
            },
        },
        {
            id = "accept-70-the-legend-of-stalvan",
            kind = "accept",
            priority = 1530,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Accept The Legend of Stalvan from Innkeeper Farley in Lion's Pride Inn.",
            complete = QuestState(70, "activeOrCompleted"),
            route = {
                Point(MAP.ELWYNN, 0.4378, 0.6584, "Innkeeper Farley",
                    "Travel to Innkeeper Farley."),
            },
        },
        {
            id = "objective-70-the-legend-of-stalvan",
            kind = "objective",
            priority = 1540,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Retrieve Stalvan's Undelivered Letter from the chest upstairs in Lion's Pride Inn.",
            dependsOn = { "accept-70-the-legend-of-stalvan" },
            complete = QuestState(70, "complete"),
            route = {
                Point(MAP.ELWYNN, 0.4422, 0.6580, "Lion's Pride Inn",
                    "Travel to Lion's Pride Inn."),
            },
        },
        {
            id = "turnin-70-the-legend-of-stalvan",
            kind = "turnin",
            priority = 1550,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Turn in The Legend of Stalvan to Caretaker Folsom in The Canals.",
            dependsOn = { "objective-70-the-legend-of-stalvan" },
            complete = QuestState(70, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.2956, 0.6191, "Caretaker Folsom",
                    "Travel to Caretaker Folsom."),
            },
        },
        {
            id = "accept-72-the-legend-of-stalvan",
            kind = "accept",
            priority = 1560,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Accept The Legend of Stalvan from Caretaker Folsom in The Canals.",
            complete = QuestState(72, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.2956, 0.6191, "Caretaker Folsom",
                    "Travel to Caretaker Folsom."),
            },
        },
        {
            id = "turnin-72-the-legend-of-stalvan",
            kind = "turnin",
            priority = 1570,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Turn in The Legend of Stalvan in The Canals.",
            dependsOn = { "accept-72-the-legend-of-stalvan" },
            complete = QuestState(72, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.2951, 0.6163, "The Canals",
                    "Travel to The Canals."),
            },
        },
        {
            id = "accept-74-the-legend-of-stalvan",
            kind = "accept",
            priority = 1580,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Accept The Legend of Stalvan in The Canals.",
            complete = QuestState(74, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.2951, 0.6163, "The Canals",
                    "Travel to The Canals."),
            },
        },
        {
            id = "turnin-1242-the-missing-diplomat",
            kind = "turnin",
            priority = 1590,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Turn in The Missing Diplomat to Elling Trias in Trade District.",
            dependsOn = { "accept-1242-the-missing-diplomat" },
            complete = QuestState(1242, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.5992, 0.6415, "Elling Trias",
                    "Travel to Elling Trias."),
            },
        },
        {
            id = "accept-1243-the-missing-diplomat",
            kind = "accept",
            priority = 1600,
            conditions = {
                all = {
                    { quest = { id = 337, state = "completed" } },
                },
            },
            text = "Accept The Missing Diplomat from Elling Trias in Trade District.",
            complete = QuestState(1243, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.5992, 0.6415, "Elling Trias",
                    "Travel to Elling Trias."),
            },
        },
    },
})
