local _, ns = ...

-- Forever Casual spine: Duskwood & Redridge Mountains (25-27)
-- Hearth, grind/ding, trainer, vendor, and flight-learn steps omitted.
-- Forever weaves ported from prior Leveling chapters (quest id >= 90000).
-- Coordinates not yet validated in Forever.

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

local MAP = {
    ELWYNN_FOREST = 1429,
    DUSKWOOD = 1431,
    REDRIDGE_MOUNTAINS = 1433,
    WESTFALL = 1436,
    MOONGLADE = 1450,
    STORMWIND_CITY = 1453,
    IRONFORGE = 1455,
    DARNASSUS = 1457,
}

ns:RegisterGuide({
    id = "leveling-era-alliance-duskwood-and-redridge-mountains",
    title = "Duskwood & Redridge Mountains",
    category = "Leveling Quest Guides",
    revision = 1,
    casualSpine = true,
    conditions = {
        all = {
            { faction = "Alliance" },
            { level = { min = 25 } },
        },
    },
    goals = {
        {
            id = "accept-66-the-legend-of-stalvan",
            kind = "accept",
            priority = 10,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Legend of Stalvan.",
            complete = QuestState(66, "activeOrCompleted"),
            route = {
                Point(1431, 0.7582, 0.4529, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-101-the-totem-of-infliction",
            kind = "accept",
            priority = 20,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Totem of Infliction.",
            complete = QuestState(101, "activeOrCompleted"),
            route = {
                Point(1431, 0.7582, 0.4529, "The Totem of Infliction",
                    "Travel to The Totem of Infliction."),
            },
        },
        {
            id = "accept-56-the-night-watch",
            kind = "accept",
            priority = 30,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Night Watch.",
            complete = QuestState(56, "activeOrCompleted"),
            route = {
                Point(1431, 0.7360, 0.4690, "The Night Watch",
                    "Travel to The Night Watch."),
            },
        },
        {
            id = "turnin-66-the-legend-of-stalvan",
            kind = "turnin",
            priority = 40,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Legend of Stalvan.",
            complete = QuestState(66, "completed"),
            dependsOn = { "accept-66-the-legend-of-stalvan" },
            route = {
                Point(1431, 0.7252, 0.4685, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-67-the-legend-of-stalvan",
            kind = "accept",
            priority = 50,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Legend of Stalvan.",
            complete = QuestState(67, "activeOrCompleted"),
            route = {
                Point(1431, 0.7252, 0.4685, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-163-raven-hill",
            kind = "accept",
            priority = 60,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Raven Hill.",
            complete = QuestState(163, "activeOrCompleted"),
            route = {
                Point(1431, 0.7533, 0.4869, "Raven Hill",
                    "Travel to Raven Hill."),
            },
        },
        {
            id = "accept-165-the-hermit",
            kind = "accept",
            priority = 70,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Hermit.",
            complete = QuestState(165, "activeOrCompleted"),
            route = {
                Point(1431, 0.7533, 0.4869, "The Hermit",
                    "Travel to The Hermit."),
            },
        },
        {
            id = "accept-164-deliveries-to-sven",
            kind = "accept",
            priority = 80,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Deliveries to Sven.",
            complete = QuestState(164, "activeOrCompleted"),
            route = {
                Point(1431, 0.7533, 0.4869, "Deliveries to Sven",
                    "Travel to Deliveries to Sven."),
            },
        },
        {
            id = "accept-174-look-to-the-stars",
            kind = "accept",
            priority = 90,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Look To The Stars.",
            complete = QuestState(174, "activeOrCompleted"),
            route = {
                Point(1431, 0.7980, 0.4802, "Look To The Stars",
                    "Travel to Look To The Stars."),
            },
        },
        {
            id = "turnin-174-look-to-the-stars",
            kind = "turnin",
            priority = 100,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Look To The Stars.",
            complete = QuestState(174, "completed"),
            dependsOn = { "accept-174-look-to-the-stars" },
            route = {
                Point(1431, 0.7980, 0.4802, "Look To The Stars",
                    "Travel to Look To The Stars."),
            },
        },
        {
            id = "accept-175-look-to-the-stars",
            kind = "accept",
            priority = 110,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Look To The Stars.",
            complete = QuestState(175, "activeOrCompleted"),
            route = {
                Point(1431, 0.7980, 0.4802, "Look To The Stars",
                    "Travel to Look To The Stars."),
            },
        },
        {
            id = "turnin-175-look-to-the-stars",
            kind = "turnin",
            priority = 120,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Look To The Stars.",
            complete = QuestState(175, "completed"),
            dependsOn = { "accept-175-look-to-the-stars" },
            route = {
                Point(1431, 0.8199, 0.5909, "Look To The Stars",
                    "Travel to Look To The Stars."),
            },
        },
        {
            id = "accept-177-look-to-the-stars",
            kind = "accept",
            priority = 130,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Look To The Stars.",
            complete = QuestState(177, "activeOrCompleted"),
            route = {
                Point(1431, 0.8199, 0.5909, "Look To The Stars",
                    "Travel to Look To The Stars."),
            },
        },
        {
            id = "objective-177-1-insane-ghoul",
            kind = "objective",
            priority = 140,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Insane Ghoul.",
            complete = QuestObjective(177, 1, "Insane Ghoul"),
            dependsOn = { "accept-177-look-to-the-stars" },
            route = {
                Point(1431, 0.8094, 0.7140, "Insane Ghoul",
                    "Travel to Insane Ghoul."),
            },
        },
        {
            id = "turnin-163-raven-hill",
            kind = "turnin",
            priority = 150,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Raven Hill.",
            complete = QuestState(163, "completed"),
            dependsOn = { "accept-163-raven-hill" },
            route = {
                Point(1431, 0.1816, 0.5651, "Raven Hill",
                    "Travel to Raven Hill."),
            },
        },
        {
            id = "accept-5-jitters-growling-gut",
            kind = "accept",
            priority = 160,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Jitters' Growling Gut.",
            complete = QuestState(5, "activeOrCompleted"),
            route = {
                Point(1431, 0.1816, 0.5651, "Jitters' Growling Gut",
                    "Travel to Jitters' Growling Gut."),
            },
        },
        {
            id = "turnin-164-deliveries-to-sven",
            kind = "turnin",
            priority = 170,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Deliveries to Sven.",
            complete = QuestState(164, "completed"),
            dependsOn = { "accept-164-deliveries-to-sven" },
            route = {
                Point(1431, 0.0779, 0.3400, "Deliveries to Sven",
                    "Travel to Deliveries to Sven."),
            },
        },
        {
            id = "accept-95-sven-s-revenge",
            kind = "accept",
            priority = 180,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Sven's Revenge.",
            complete = QuestState(95, "activeOrCompleted"),
            route = {
                Point(1431, 0.0779, 0.3400, "Sven's Revenge",
                    "Travel to Sven's Revenge."),
            },
        },
        {
            id = "accept-226-wolves-at-our-heels",
            kind = "accept",
            priority = 190,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Wolves at Our Heels.",
            complete = QuestState(226, "activeOrCompleted"),
            route = {
                Point(1431, 0.0771, 0.3320, "Wolves at Our Heels",
                    "Travel to Wolves at Our Heels."),
            },
        },
        {
            id = "objective-226-2-rabid-dire-wolf",
            kind = "objective",
            priority = 200,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill 8 Rabid Dire Wolf.",
            complete = QuestObjective(226, 2, "Rabid Dire Wolf"),
            dependsOn = { "accept-226-wolves-at-our-heels" },
            route = {
                Point(1431, 0.1940, 0.2860, "Rabid Dire Wolf",
                    "Travel to Rabid Dire Wolf."),
            },
        },
        {
            id = "objective-226-1-starving-dire-wolf",
            kind = "objective",
            priority = 210,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill 12 Starving Dire Wolf.",
            complete = QuestObjective(226, 1, "Starving Dire Wolf"),
            dependsOn = { "accept-226-wolves-at-our-heels" },
            route = {
                Point(1431, 0.1940, 0.2860, "Starving Dire Wolf",
                    "Travel to Starving Dire Wolf."),
            },
        },
        {
            id = "turnin-165-the-hermit",
            kind = "turnin",
            priority = 220,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Hermit.",
            complete = QuestState(165, "completed"),
            dependsOn = { "accept-165-the-hermit" },
            route = {
                Point(1431, 0.2811, 0.3147, "The Hermit",
                    "Travel to The Hermit."),
            },
        },
        {
            id = "accept-148-supplies-from-darkshire",
            kind = "accept",
            priority = 230,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Supplies from Darkshire.",
            complete = QuestState(148, "activeOrCompleted"),
            route = {
                Point(1431, 0.2811, 0.3147, "Supplies from Darkshire",
                    "Travel to Supplies from Darkshire."),
            },
        },
        {
            id = "objective-101-1-flesh-eater",
            kind = "objective",
            priority = 240,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Flesh Eater.",
            complete = QuestObjective(101, 1, "Flesh Eater"),
            dependsOn = { "accept-101-the-totem-of-infliction" },
            route = {
                Point(1431, 0.2359, 0.3489, "Flesh Eater",
                    "Travel to Flesh Eater."),
            },
        },
        {
            id = "turnin-226-wolves-at-our-heels",
            kind = "turnin",
            priority = 250,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Wolves at Our Heels.",
            complete = QuestState(226, "completed"),
            dependsOn = { "accept-226-wolves-at-our-heels", "objective-226-2-rabid-dire-wolf", "objective-226-1-starving-dire-wolf" },
            route = {
                Point(1431, 0.2359, 0.3489, "Wolves at Our Heels",
                    "Travel to Wolves at Our Heels."),
            },
        },
        {
            id = "turnin-2360-mathias-and-the-defias",
            kind = "turnin",
            priority = 260,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 4 },
            } },
            text = "Turn in Mathias and the Defias.",
            complete = QuestState(2360, "completed"),
            route = {
                Point(1436, 0.6849, 0.7008, "Mathias and the Defias",
                    "Travel to Mathias and the Defias."),
            },
        },
        {
            id = "accept-2359-klaven-s-tower",
            kind = "accept",
            priority = 270,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 4 },
            } },
            text = "Accept Klaven's Tower.",
            complete = QuestState(2359, "activeOrCompleted"),
            route = {
                Point(1436, 0.6849, 0.7008, "Klaven's Tower",
                    "Travel to Klaven's Tower."),
            },
        },
        {
            id = "turnin-67-the-legend-of-stalvan",
            kind = "turnin",
            priority = 280,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Legend of Stalvan.",
            complete = QuestState(67, "completed"),
            dependsOn = { "accept-67-the-legend-of-stalvan" },
            route = {
                Point(1436, 0.4151, 0.6673, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-68-the-legend-of-stalvan",
            kind = "accept",
            priority = 290,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Legend of Stalvan.",
            complete = QuestState(68, "activeOrCompleted"),
            route = {
                Point(1436, 0.4151, 0.6673, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "turnin-1650-the-tome-of-valor",
            kind = "turnin",
            priority = 300,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 2 },
            } },
            text = "Turn in The Tome of Valor.",
            complete = QuestState(1650, "completed"),
            route = {
                Point(1436, 0.5264, 0.7227, "The Tome of Valor",
                    "Travel to The Tome of Valor."),
            },
        },
        {
            id = "accept-1651-the-tome-of-valor",
            kind = "accept",
            priority = 310,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 2 },
            } },
            text = "Accept The Tome of Valor.",
            complete = QuestState(1651, "activeOrCompleted"),
            route = {
                Point(1436, 0.5264, 0.7227, "The Tome of Valor",
                    "Travel to The Tome of Valor."),
            },
        },
        {
            id = "turnin-1651-the-tome-of-valor",
            kind = "turnin",
            priority = 320,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 2 },
            } },
            text = "Turn in The Tome of Valor.",
            complete = QuestState(1651, "completed"),
            dependsOn = { "accept-1651-the-tome-of-valor" },
            route = {
                Point(1436, 0.4168, 0.8909, "The Tome of Valor",
                    "Travel to The Tome of Valor."),
            },
        },
        {
            id = "accept-1652-the-tome-of-valor",
            kind = "accept",
            priority = 330,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 2 },
            } },
            text = "Accept The Tome of Valor.",
            complete = QuestState(1652, "activeOrCompleted"),
            route = {
                Point(1436, 0.4168, 0.8909, "The Tome of Valor",
                    "Travel to The Tome of Valor."),
            },
        },
        {
            id = "objective-272-1-half-pendant-of-aquatic-agility",
            kind = "objective",
            priority = 340,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 11 },
            } },
            text = "Use Half Pendant of Aquatic Agility.",
            complete = QuestObjective(272, 1, "Half Pendant of Aquatic Agility"),
            route = {
                Point(1450, 0.3592, 0.4142, "Half Pendant of Aquatic Agility",
                    "Travel to Half Pendant of Aquatic Agility."),
            },
        },
        {
            id = "turnin-272-trial-of-the-sea-lion",
            kind = "turnin",
            priority = 350,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 11 },
            } },
            text = "Turn in Trial of the Sea Lion.",
            complete = QuestState(272, "completed"),
            dependsOn = { "objective-272-1-half-pendant-of-aquatic-agility" },
            route = {
                Point(1450, 0.5621, 0.3064, "Trial of the Sea Lion",
                    "Travel to Trial of the Sea Lion."),
            },
        },
        {
            id = "accept-5061-aquatic-form",
            kind = "accept",
            priority = 360,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 11 },
            } },
            text = "Accept Aquatic Form.",
            complete = QuestState(5061, "activeOrCompleted"),
            route = {
                Point(1450, 0.5621, 0.3064, "Aquatic Form",
                    "Travel to Aquatic Form."),
            },
        },
        {
            id = "turnin-5061-aquatic-form",
            kind = "turnin",
            priority = 370,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 11 },
            } },
            text = "Turn in Aquatic Form.",
            complete = QuestState(5061, "completed"),
            dependsOn = { "accept-5061-aquatic-form" },
            route = {
                Point(1457, 0.3537, 0.0839, "Aquatic Form",
                    "Travel to Aquatic Form."),
            },
        },
        {
            id = "turnin-5-jitters-growling-gut",
            kind = "turnin",
            priority = 380,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Jitters' Growling Gut.",
            complete = QuestState(5, "completed"),
            dependsOn = { "accept-5-jitters-growling-gut" },
            route = {
                Point(1431, 0.7378, 0.4345, "Jitters' Growling Gut",
                    "Travel to Jitters' Growling Gut."),
            },
        },
        {
            id = "accept-93-dusky-crab-cakes",
            kind = "accept",
            priority = 390,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Dusky Crab Cakes.",
            complete = QuestState(93, "activeOrCompleted"),
            route = {
                Point(1431, 0.7378, 0.4345, "Dusky Crab Cakes",
                    "Travel to Dusky Crab Cakes."),
            },
        },
        {
            id = "turnin-93-dusky-crab-cakes",
            kind = "turnin",
            priority = 400,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Dusky Crab Cakes.",
            complete = QuestState(93, "completed"),
            dependsOn = { "accept-93-dusky-crab-cakes" },
            route = {
                Point(1431, 0.7378, 0.4345, "Dusky Crab Cakes",
                    "Travel to Dusky Crab Cakes."),
            },
        },
        {
            id = "accept-240-return-to-jitters",
            kind = "accept",
            priority = 410,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Return to Jitters.",
            complete = QuestState(240, "activeOrCompleted"),
            route = {
                Point(1431, 0.7378, 0.4345, "Return to Jitters",
                    "Travel to Jitters."),
            },
        },
        {
            id = "turnin-56-the-night-watch",
            kind = "turnin",
            priority = 420,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Night Watch.",
            complete = QuestState(56, "completed"),
            dependsOn = { "accept-56-the-night-watch" },
            route = {
                Point(1431, 0.7359, 0.4690, "The Night Watch",
                    "Travel to The Night Watch."),
            },
        },
        {
            id = "accept-57-the-night-watch",
            kind = "accept",
            priority = 430,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Night Watch.",
            complete = QuestState(57, "activeOrCompleted"),
            route = {
                Point(1431, 0.7359, 0.4690, "The Night Watch",
                    "Travel to The Night Watch."),
            },
        },
        {
            id = "turnin-68-the-legend-of-stalvan",
            kind = "turnin",
            priority = 440,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Legend of Stalvan.",
            complete = QuestState(68, "completed"),
            dependsOn = { "accept-68-the-legend-of-stalvan" },
            route = {
                Point(1431, 0.7252, 0.4685, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-69-the-legend-of-stalvan",
            kind = "accept",
            priority = 450,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Legend of Stalvan.",
            complete = QuestState(69, "activeOrCompleted"),
            route = {
                Point(1431, 0.7252, 0.4685, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "turnin-101-the-totem-of-infliction",
            kind = "turnin",
            priority = 460,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Totem of Infliction.",
            complete = QuestState(101, "completed"),
            dependsOn = { "accept-101-the-totem-of-infliction", "objective-101-1-flesh-eater" },
            route = {
                Point(1431, 0.7581, 0.4529, "The Totem of Infliction",
                    "Travel to The Totem of Infliction."),
            },
        },
        {
            id = "turnin-148-supplies-from-darkshire",
            kind = "turnin",
            priority = 470,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Supplies from Darkshire.",
            complete = QuestState(148, "completed"),
            dependsOn = { "accept-148-supplies-from-darkshire" },
            route = {
                Point(1431, 0.7581, 0.4529, "Supplies from Darkshire",
                    "Travel to Supplies from Darkshire."),
            },
        },
        {
            id = "accept-149-ghost-hair-thread",
            kind = "accept",
            priority = 480,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Ghost Hair Thread.",
            complete = QuestState(149, "activeOrCompleted"),
            route = {
                Point(1431, 0.7581, 0.4529, "Ghost Hair Thread",
                    "Travel to Ghost Hair Thread."),
            },
        },
        {
            id = "turnin-177-look-to-the-stars",
            kind = "turnin",
            priority = 490,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Look To The Stars.",
            complete = QuestState(177, "completed"),
            dependsOn = { "accept-177-look-to-the-stars", "objective-177-1-insane-ghoul" },
            route = {
                Point(1431, 0.7980, 0.4802, "Look To The Stars",
                    "Travel to Look To The Stars."),
            },
        },
        {
            id = "turnin-149-ghost-hair-thread",
            kind = "turnin",
            priority = 500,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Ghost Hair Thread.",
            complete = QuestState(149, "completed"),
            dependsOn = { "accept-149-ghost-hair-thread" },
            route = {
                Point(1431, 0.8198, 0.5909, "Ghost Hair Thread",
                    "Travel to Ghost Hair Thread."),
            },
        },
        {
            id = "accept-154-return-the-comb",
            kind = "accept",
            priority = 510,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Return the Comb.",
            complete = QuestState(154, "activeOrCompleted"),
            route = {
                Point(1431, 0.8198, 0.5909, "Return the Comb",
                    "Travel to Return the Comb."),
            },
        },
        {
            id = "turnin-154-return-the-comb",
            kind = "turnin",
            priority = 520,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Return the Comb.",
            complete = QuestState(154, "completed"),
            dependsOn = { "accept-154-return-the-comb" },
            route = {
                Point(1431, 0.7581, 0.4529, "Return the Comb",
                    "Travel to Return the Comb."),
            },
        },
        {
            id = "accept-157-deliver-the-thread",
            kind = "accept",
            priority = 530,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Deliver the Thread.",
            complete = QuestState(157, "activeOrCompleted"),
            route = {
                Point(1431, 0.7581, 0.4529, "Deliver the Thread",
                    "Travel to Deliver the Thread."),
            },
        },
        {
            id = "turnin-95-sven-s-revenge",
            kind = "turnin",
            priority = 540,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Sven's Revenge.",
            complete = QuestState(95, "completed"),
            dependsOn = { "accept-95-sven-s-revenge" },
            route = {
                Point(1431, 0.4986, 0.7770, "Sven's Revenge",
                    "Travel to Sven's Revenge."),
            },
        },
        {
            id = "accept-230-sven-s-camp",
            kind = "accept",
            priority = 550,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Sven's Camp.",
            complete = QuestState(230, "activeOrCompleted"),
            route = {
                Point(1431, 0.4986, 0.7770, "Sven's Camp",
                    "Travel to Sven's Camp."),
            },
        },
        {
            id = "turnin-157-deliver-the-thread",
            kind = "turnin",
            priority = 560,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Deliver the Thread.",
            complete = QuestState(157, "completed"),
            dependsOn = { "accept-157-deliver-the-thread" },
            route = {
                Point(1431, 0.2811, 0.3147, "Deliver the Thread",
                    "Travel to Deliver the Thread."),
            },
        },
        {
            id = "accept-158-zombie-juice",
            kind = "accept",
            priority = 570,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Zombie Juice.",
            complete = QuestState(158, "activeOrCompleted"),
            route = {
                Point(1431, 0.2811, 0.3147, "Zombie Juice",
                    "Travel to Zombie Juice."),
            },
        },
        {
            id = "turnin-230-sven-s-camp",
            kind = "turnin",
            priority = 580,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Sven's Camp.",
            complete = QuestState(230, "completed"),
            dependsOn = { "accept-230-sven-s-camp" },
            route = {
                Point(1431, 0.0779, 0.3400, "Sven's Camp",
                    "Travel to Sven's Camp."),
            },
        },
        {
            id = "accept-262-the-shadowy-figure",
            kind = "accept",
            priority = 590,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Shadowy Figure.",
            complete = QuestState(262, "activeOrCompleted"),
            route = {
                Point(1431, 0.0779, 0.3400, "The Shadowy Figure",
                    "Travel to The Shadowy Figure."),
            },
        },
        {
            id = "turnin-69-the-legend-of-stalvan",
            kind = "turnin",
            priority = 600,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Legend of Stalvan.",
            complete = QuestState(69, "completed"),
            dependsOn = { "accept-69-the-legend-of-stalvan" },
            route = {
                Point(1429, 0.4377, 0.6580, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-70-the-legend-of-stalvan",
            kind = "accept",
            priority = 610,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Legend of Stalvan.",
            complete = QuestState(70, "activeOrCompleted"),
            route = {
                Point(1429, 0.4377, 0.6580, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "turnin-1652-the-tome-of-valor",
            kind = "turnin",
            priority = 620,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 2 },
            } },
            text = "Turn in The Tome of Valor.",
            complete = QuestState(1652, "completed"),
            dependsOn = { "accept-1652-the-tome-of-valor" },
            route = {
                Point(1453, 0.4305, 0.3448, "The Tome of Valor",
                    "Travel to The Tome of Valor."),
            },
        },
        {
            id = "turnin-2359-klaven-s-tower",
            kind = "turnin",
            priority = 630,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 4 },
            } },
            text = "Turn in Klaven's Tower.",
            complete = QuestState(2359, "completed"),
            dependsOn = { "accept-2359-klaven-s-tower" },
            route = {
                Point(1453, 0.7578, 0.5985, "Klaven's Tower",
                    "Travel to Klaven's Tower."),
            },
        },
        {
            id = "accept-2607-the-touch-of-zanzil",
            kind = "accept",
            priority = 640,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 4 },
            } },
            text = "Accept The Touch of Zanzil.",
            complete = QuestState(2607, "activeOrCompleted"),
            route = {
                Point(1453, 0.7578, 0.5985, "The Touch of Zanzil",
                    "Travel to The Touch of Zanzil."),
            },
        },
        {
            id = "turnin-2607-the-touch-of-zanzil",
            kind = "turnin",
            priority = 650,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 4 },
            } },
            text = "Turn in The Touch of Zanzil.",
            complete = QuestState(2607, "completed"),
            dependsOn = { "accept-2607-the-touch-of-zanzil" },
            route = {
                Point(1453, 0.7804, 0.5877, "The Touch of Zanzil",
                    "Travel to The Touch of Zanzil."),
            },
        },
        {
            id = "accept-2608-the-touch-of-zanzil",
            kind = "accept",
            priority = 660,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 4 },
            } },
            text = "Accept The Touch of Zanzil.",
            complete = QuestState(2608, "activeOrCompleted"),
            route = {
                Point(1453, 0.7804, 0.5877, "The Touch of Zanzil",
                    "Travel to The Touch of Zanzil."),
            },
        },
        {
            id = "turnin-2608-the-touch-of-zanzil",
            kind = "turnin",
            priority = 670,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
                { class = 4 },
            } },
            text = "Turn in The Touch of Zanzil.",
            complete = QuestState(2608, "completed"),
            dependsOn = { "accept-2608-the-touch-of-zanzil" },
            route = {
                Point(1453, 0.7804, 0.5877, "The Touch of Zanzil",
                    "Travel to The Touch of Zanzil."),
            },
        },
        {
            id = "turnin-70-the-legend-of-stalvan",
            kind = "turnin",
            priority = 680,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Legend of Stalvan.",
            complete = QuestState(70, "completed"),
            dependsOn = { "accept-70-the-legend-of-stalvan" },
            route = {
                Point(1453, 0.2958, 0.6193, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-72-the-legend-of-stalvan",
            kind = "accept",
            priority = 690,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Legend of Stalvan.",
            complete = QuestState(72, "activeOrCompleted"),
            route = {
                Point(1453, 0.2958, 0.6193, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "turnin-72-the-legend-of-stalvan",
            kind = "turnin",
            priority = 700,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Legend of Stalvan.",
            complete = QuestState(72, "completed"),
            dependsOn = { "accept-72-the-legend-of-stalvan" },
            route = {
                Point(1453, 0.2946, 0.6158, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-74-the-legend-of-stalvan",
            kind = "accept",
            priority = 710,
            conditions = { all = {
                { level = { min = 30 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Legend of Stalvan.",
            complete = QuestState(74, "activeOrCompleted"),
            route = {
                Point(1453, 0.2946, 0.6158, "The Legend of Stalvan",
                    "Travel to The Legend of Stalvan."),
            },
        },
        {
            id = "accept-335-a-noble-brew",
            kind = "accept",
            priority = 720,
            conditions = { all = {
                { level = { min = 30 } },
                { faction = "Alliance" },
            } },
            text = "Accept A Noble Brew.",
            complete = QuestState(335, "activeOrCompleted"),
            route = {
                Point(1453, 0.2916, 0.7415, "A Noble Brew",
                    "Travel to A Noble Brew."),
            },
        },
        {
            id = "accept-20-blackrock-menace",
            kind = "accept",
            priority = 730,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Blackrock Menace.",
            complete = QuestState(20, "activeOrCompleted"),
            route = {
                Point(1433, 0.3351, 0.4897, "Blackrock Menace",
                    "Travel to Blackrock Menace."),
            },
        },
        {
            id = "accept-127-selling-fish",
            kind = "accept",
            priority = 740,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Selling Fish.",
            complete = QuestState(127, "activeOrCompleted"),
            route = {
                Point(1433, 0.2772, 0.4738, "Selling Fish",
                    "Travel to Selling Fish."),
            },
        },
        {
            id = "accept-150-murloc-poachers",
            kind = "accept",
            priority = 750,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Murloc Poachers.",
            complete = QuestState(150, "activeOrCompleted"),
            route = {
                Point(1433, 0.2772, 0.4738, "Murloc Poachers",
                    "Travel to Murloc Poachers."),
            },
        },
        {
            id = "accept-34-an-unwelcome-guest",
            kind = "accept",
            priority = 760,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept An Unwelcome Guest.",
            complete = QuestState(34, "activeOrCompleted"),
            route = {
                Point(1433, 0.2186, 0.4633, "An Unwelcome Guest",
                    "Travel to An Unwelcome Guest."),
            },
        },
        {
            id = "objective-34-1-bellygrub",
            kind = "objective",
            priority = 770,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Bellygrub.",
            complete = QuestObjective(34, 1, "Bellygrub"),
            dependsOn = { "accept-34-an-unwelcome-guest" },
            route = {
                Point(1433, 0.1568, 0.4932, "Bellygrub",
                    "Travel to Bellygrub."),
            },
        },
        {
            id = "turnin-34-an-unwelcome-guest",
            kind = "turnin",
            priority = 780,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in An Unwelcome Guest.",
            complete = QuestState(34, "completed"),
            dependsOn = { "accept-34-an-unwelcome-guest", "objective-34-1-bellygrub" },
            route = {
                Point(1433, 0.2186, 0.4633, "An Unwelcome Guest",
                    "Travel to An Unwelcome Guest."),
            },
        },
        {
            id = "objective-20-1-blackrock-grunt",
            kind = "objective",
            priority = 790,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Blackrock Grunt.",
            complete = QuestObjective(20, 1, "Blackrock Grunt"),
            dependsOn = { "accept-20-blackrock-menace" },
            route = {
                Point(1433, 0.6260, 0.4360, "Blackrock Grunt",
                    "Travel to Blackrock Grunt."),
            },
        },
        {
            id = "objective-150-1-murloc-flesheater",
            kind = "objective",
            priority = 800,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Murloc Flesheater.",
            complete = QuestObjective(150, 1, "Murloc Flesheater"),
            dependsOn = { "accept-150-murloc-poachers" },
            route = {
                Point(1433, 0.5593, 0.5301, "Murloc Flesheater",
                    "Travel to Murloc Flesheater."),
            },
        },
        {
            id = "objective-127-1-spotted-sunfish",
            kind = "objective",
            priority = 810,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Collect 10 Spotted Sunfish.",
            complete = QuestObjective(127, 1, "Spotted Sunfish"),
            dependsOn = { "accept-127-selling-fish" },
            route = {
                Point(1433, 0.5593, 0.5301, "Spotted Sunfish",
                    "Travel to Spotted Sunfish."),
            },
        },
        {
            id = "turnin-20-blackrock-menace",
            kind = "turnin",
            priority = 820,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Blackrock Menace.",
            complete = QuestState(20, "completed"),
            dependsOn = { "accept-20-blackrock-menace", "objective-20-1-blackrock-grunt" },
            route = {
                Point(1433, 0.3351, 0.4897, "Blackrock Menace",
                    "Travel to Blackrock Menace."),
            },
        },
        {
            id = "turnin-127-selling-fish",
            kind = "turnin",
            priority = 830,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Selling Fish.",
            complete = QuestState(127, "completed"),
            dependsOn = { "accept-127-selling-fish", "objective-127-1-spotted-sunfish" },
            route = {
                Point(1433, 0.2772, 0.4738, "Selling Fish",
                    "Travel to Selling Fish."),
            },
        },
        {
            id = "turnin-150-murloc-poachers",
            kind = "turnin",
            priority = 840,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Murloc Poachers.",
            complete = QuestState(150, "completed"),
            dependsOn = { "accept-150-murloc-poachers", "objective-150-1-murloc-flesheater" },
            route = {
                Point(1433, 0.2772, 0.4738, "Murloc Poachers",
                    "Travel to Murloc Poachers."),
            },
        },
        {
            id = "turnin-262-the-shadowy-figure",
            kind = "turnin",
            priority = 850,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Shadowy Figure.",
            complete = QuestState(262, "completed"),
            dependsOn = { "accept-262-the-shadowy-figure" },
            route = {
                Point(1431, 0.7581, 0.4529, "The Shadowy Figure",
                    "Travel to The Shadowy Figure."),
            },
        },
        {
            id = "accept-265-the-shadowy-search-continues",
            kind = "accept",
            priority = 860,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Shadowy Search Continues.",
            complete = QuestState(265, "activeOrCompleted"),
            route = {
                Point(1431, 0.7581, 0.4529, "The Shadowy Search Continues",
                    "Travel to The Shadowy Search Continues."),
            },
        },
        {
            id = "turnin-265-the-shadowy-search-continues",
            kind = "turnin",
            priority = 870,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Shadowy Search Continues.",
            complete = QuestState(265, "completed"),
            dependsOn = { "accept-265-the-shadowy-search-continues" },
            route = {
                Point(1431, 0.7253, 0.4685, "The Shadowy Search Continues",
                    "Travel to The Shadowy Search Continues."),
            },
        },
        {
            id = "accept-266-inquire-at-the-inn",
            kind = "accept",
            priority = 880,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Inquire at the Inn.",
            complete = QuestState(266, "activeOrCompleted"),
            route = {
                Point(1431, 0.7253, 0.4685, "Inquire at the Inn",
                    "Travel to Inquire at the Inn."),
            },
        },
        {
            id = "turnin-158-zombie-juice",
            kind = "turnin",
            priority = 890,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Zombie Juice.",
            complete = QuestState(158, "completed"),
            dependsOn = { "accept-158-zombie-juice" },
            route = {
                Point(1431, 0.7378, 0.4448, "Zombie Juice",
                    "Travel to Zombie Juice."),
            },
        },
        {
            id = "accept-156-gather-rot-blossoms",
            kind = "accept",
            priority = 900,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Gather Rot Blossoms.",
            complete = QuestState(156, "activeOrCompleted"),
            route = {
                Point(1431, 0.7378, 0.4448, "Gather Rot Blossoms",
                    "Travel to Gather Rot Blossoms."),
            },
        },
        {
            id = "turnin-266-inquire-at-the-inn",
            kind = "turnin",
            priority = 910,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Inquire at the Inn.",
            complete = QuestState(266, "completed"),
            dependsOn = { "accept-266-inquire-at-the-inn" },
            route = {
                Point(1431, 0.7378, 0.4448, "Inquire at the Inn",
                    "Travel to Inquire at the Inn."),
            },
        },
        {
            id = "accept-453-finding-the-shadowy-figure",
            kind = "accept",
            priority = 920,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Finding the Shadowy Figure.",
            complete = QuestState(453, "activeOrCompleted"),
            route = {
                Point(1431, 0.7378, 0.4448, "Finding the Shadowy Figure",
                    "Travel to Finding the Shadowy Figure."),
            },
        },
        {
            id = "turnin-240-return-to-jitters",
            kind = "turnin",
            priority = 930,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Return to Jitters.",
            complete = QuestState(240, "completed"),
            dependsOn = { "accept-240-return-to-jitters" },
            route = {
                Point(1431, 0.1814, 0.5652, "Return to Jitters",
                    "Travel to Jitters."),
            },
        },
        {
            id = "turnin-453-finding-the-shadowy-figure",
            kind = "turnin",
            priority = 940,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Finding the Shadowy Figure.",
            complete = QuestState(453, "completed"),
            dependsOn = { "accept-453-finding-the-shadowy-figure" },
            route = {
                Point(1431, 0.1814, 0.5652, "Finding the Shadowy Figure",
                    "Travel to Finding the Shadowy Figure."),
            },
        },
        {
            id = "accept-268-return-to-sven",
            kind = "accept",
            priority = 950,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Return to Sven.",
            complete = QuestState(268, "activeOrCompleted"),
            route = {
                Point(1431, 0.1814, 0.5652, "Return to Sven",
                    "Travel to Sven."),
            },
        },
        {
            id = "objective-156-1-skeletal-fiend",
            kind = "objective",
            priority = 960,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Skeletal Fiend.",
            complete = QuestObjective(156, 1, "Skeletal Fiend"),
            dependsOn = { "accept-156-gather-rot-blossoms" },
            route = {
                Point(1431, 0.1760, 0.4640, "Skeletal Fiend",
                    "Travel to Skeletal Fiend."),
            },
        },
        {
            id = "turnin-268-return-to-sven",
            kind = "turnin",
            priority = 970,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Return to Sven.",
            complete = QuestState(268, "completed"),
            dependsOn = { "accept-268-return-to-sven" },
            route = {
                Point(1431, 0.0779, 0.3400, "Return to Sven",
                    "Travel to Sven."),
            },
        },
        {
            id = "accept-323-proving-your-worth",
            kind = "accept",
            priority = 980,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Proving Your Worth.",
            complete = QuestState(323, "activeOrCompleted"),
            route = {
                Point(1431, 0.0779, 0.3400, "Proving Your Worth",
                    "Travel to Proving Your Worth."),
            },
        },
        {
            id = "objective-323-3-skeletal-warder",
            kind = "objective",
            priority = 990,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill 3 Skeletal Warder.",
            complete = QuestObjective(323, 3, "Skeletal Warder"),
            dependsOn = { "accept-323-proving-your-worth" },
            route = {
                Point(1431, 0.1588, 0.3872, "Skeletal Warder",
                    "Travel to Skeletal Warder."),
            },
        },
        {
            id = "objective-323-2-skeletal-healer",
            kind = "objective",
            priority = 1000,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill 3 Skeletal Healer.",
            complete = QuestObjective(323, 2, "Skeletal Healer"),
            dependsOn = { "accept-323-proving-your-worth" },
            route = {
                Point(1431, 0.1588, 0.3872, "Skeletal Healer",
                    "Travel to Skeletal Healer."),
            },
        },
        {
            id = "objective-323-1-skeletal-raider",
            kind = "objective",
            priority = 1010,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill 15 Skeletal Raider.",
            complete = QuestObjective(323, 1, "Skeletal Raider"),
            dependsOn = { "accept-323-proving-your-worth" },
            route = {
                Point(1431, 0.1588, 0.3872, "Skeletal Raider",
                    "Travel to Skeletal Raider."),
            },
        },
        {
            id = "turnin-323-proving-your-worth",
            kind = "turnin",
            priority = 1020,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Proving Your Worth.",
            complete = QuestState(323, "completed"),
            dependsOn = { "accept-323-proving-your-worth", "objective-323-3-skeletal-warder", "objective-323-2-skeletal-healer", "objective-323-1-skeletal-raider" },
            route = {
                Point(1431, 0.1588, 0.3872, "Proving Your Worth",
                    "Travel to Proving Your Worth."),
            },
        },
        {
            id = "accept-269-seeking-wisdom",
            kind = "accept",
            priority = 1030,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Seeking Wisdom.",
            complete = QuestState(269, "activeOrCompleted"),
            route = {
                Point(1431, 0.1588, 0.3872, "Seeking Wisdom",
                    "Travel to Seeking Wisdom."),
            },
        },
        {
            id = "turnin-156-gather-rot-blossoms",
            kind = "turnin",
            priority = 1040,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Gather Rot Blossoms.",
            complete = QuestState(156, "completed"),
            dependsOn = { "accept-156-gather-rot-blossoms", "objective-156-1-skeletal-fiend" },
            route = {
                Point(1431, 0.7378, 0.4448, "Gather Rot Blossoms",
                    "Travel to Gather Rot Blossoms."),
            },
        },
        {
            id = "accept-159-juice-delivery",
            kind = "accept",
            priority = 1050,
            conditions = { all = {
                { level = { min = 30 } },
                { faction = "Alliance" },
            } },
            text = "Accept Juice Delivery.",
            complete = QuestState(159, "activeOrCompleted"),
            route = {
                Point(1431, 0.7378, 0.4448, "Juice Delivery",
                    "Travel to Juice Delivery."),
            },
        },
        {
            id = "turnin-57-the-night-watch",
            kind = "turnin",
            priority = 1060,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Night Watch.",
            complete = QuestState(57, "completed"),
            dependsOn = { "accept-57-the-night-watch" },
            route = {
                Point(1431, 0.7360, 0.4690, "The Night Watch",
                    "Travel to The Night Watch."),
            },
        },
        {
            id = "accept-377-crime-and-punishment",
            kind = "accept",
            priority = 1070,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Crime and Punishment.",
            complete = QuestState(377, "activeOrCompleted"),
            route = {
                Point(1431, 0.7195, 0.4779, "Crime and Punishment",
                    "Travel to Crime and Punishment."),
            },
        },
        {
            id = "accept-128-blackrock-bounty",
            kind = "accept",
            priority = 1080,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Blackrock Bounty.",
            complete = QuestState(128, "activeOrCompleted"),
            route = {
                Point(1433, 0.3154, 0.5785, "Blackrock Bounty",
                    "Travel to Blackrock Bounty."),
            },
        },
        {
            id = "accept-126-howling-in-the-hills",
            kind = "accept",
            priority = 1090,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Howling in the Hills.",
            complete = QuestState(126, "activeOrCompleted"),
            route = {
                Point(1433, 0.3097, 0.4727, "Howling in the Hills",
                    "Travel to Howling in the Hills."),
            },
        },
        {
            id = "accept-91-solomon-s-law",
            kind = "accept",
            priority = 1100,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Solomon's Law.",
            complete = QuestState(91, "activeOrCompleted"),
            route = {
                Point(1433, 0.2972, 0.4426, "Solomon's Law",
                    "Travel to Solomon's Law."),
            },
        },
        {
            id = "accept-180-wanted-lieutenant-fangore",
            kind = "accept",
            priority = 1110,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Wanted: Lieutenant Fangore.",
            complete = QuestState(180, "activeOrCompleted"),
            route = {
                Point(1433, 0.2675, 0.4647, "Wanted: Lieutenant Fangore",
                    "Travel to Wanted: Lieutenant Fangore."),
            },
        },
        {
            id = "objective-126-1-yowler",
            kind = "objective",
            priority = 1120,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Yowler.",
            complete = QuestObjective(126, 1, "Yowler"),
            dependsOn = { "accept-126-howling-in-the-hills" },
            route = {
                Point(1433, 0.2765, 0.2138, "Yowler",
                    "Travel to Yowler."),
            },
        },
        {
            id = "objective-180-1-lieutenant-fangore",
            kind = "objective",
            priority = 1130,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Lieutenant Fangore.",
            complete = QuestObjective(180, 1, "Lieutenant Fangore"),
            dependsOn = { "accept-180-wanted-lieutenant-fangore" },
            route = {
                Point(1433, 0.7980, 0.3740, "Lieutenant Fangore",
                    "Travel to Lieutenant Fangore."),
            },
        },
        {
            id = "turnin-94-a-watchful-eye",
            kind = "turnin",
            priority = 1140,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in A Watchful Eye.",
            complete = QuestState(94, "completed"),
            route = {
                Point(1433, 0.8436, 0.4671, "A Watchful Eye",
                    "Travel to A Watchful Eye."),
            },
        },
        {
            id = "objective-128-1-blackrock-champion",
            kind = "objective",
            priority = 1150,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill 15 Blackrock Champion.",
            complete = QuestObjective(128, 1, "Blackrock Champion"),
            dependsOn = { "accept-128-blackrock-bounty" },
            route = {
                Point(1433, 0.3321, 0.0688, "Blackrock Champion",
                    "Travel to Blackrock Champion."),
            },
        },
        {
            id = "accept-219-missing-in-action",
            kind = "accept",
            priority = 1160,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Missing In Action.",
            complete = QuestState(219, "activeOrCompleted"),
            route = {
                Point(1433, 0.2839, 0.1255, "Missing In Action",
                    "Travel to Missing In Action."),
            },
        },
        {
            id = "turnin-219-missing-in-action",
            kind = "turnin",
            priority = 1170,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Missing In Action.",
            complete = QuestState(219, "completed"),
            dependsOn = { "accept-219-missing-in-action" },
            route = {
                Point(1433, 0.3351, 0.4897, "Missing In Action",
                    "Travel to Missing In Action."),
            },
        },
        {
            id = "turnin-126-howling-in-the-hills",
            kind = "turnin",
            priority = 1180,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Howling in the Hills.",
            complete = QuestState(126, "completed"),
            dependsOn = { "accept-126-howling-in-the-hills", "objective-126-1-yowler" },
            route = {
                Point(1433, 0.3097, 0.4727, "Howling in the Hills",
                    "Travel to Howling in the Hills."),
            },
        },
        {
            id = "turnin-91-solomon-s-law",
            kind = "turnin",
            priority = 1190,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Solomon's Law.",
            complete = QuestState(91, "completed"),
            dependsOn = { "accept-91-solomon-s-law" },
            route = {
                Point(1433, 0.2971, 0.4427, "Solomon's Law",
                    "Travel to Solomon's Law."),
            },
        },
        {
            id = "turnin-180-wanted-lieutenant-fangore",
            kind = "turnin",
            priority = 1200,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Wanted: Lieutenant Fangore.",
            complete = QuestState(180, "completed"),
            dependsOn = { "accept-180-wanted-lieutenant-fangore", "objective-180-1-lieutenant-fangore" },
            route = {
                Point(1433, 0.2999, 0.4446, "Wanted: Lieutenant Fangore",
                    "Travel to Wanted: Lieutenant Fangore."),
            },
        },
        {
            id = "turnin-128-blackrock-bounty",
            kind = "turnin",
            priority = 1210,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Blackrock Bounty.",
            complete = QuestState(128, "completed"),
            dependsOn = { "accept-128-blackrock-bounty", "objective-128-1-blackrock-champion" },
            route = {
                Point(1433, 0.3154, 0.5786, "Blackrock Bounty",
                    "Travel to Blackrock Bounty."),
            },
        },
        {
            id = "accept-2923-tinkmaster-overspark",
            kind = "accept",
            priority = 1220,
            conditions = { all = {
                { level = { min = 29 } },
                { faction = "Alliance" },
            } },
            text = "Accept Tinkmaster Overspark.",
            complete = QuestState(2923, "activeOrCompleted"),
            route = {
                Point(1453, 0.4305, 0.3448, "Tinkmaster Overspark",
                    "Travel to Tinkmaster Overspark."),
            },
        },
        {
            id = "turnin-269-seeking-wisdom",
            kind = "turnin",
            priority = 1230,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Seeking Wisdom.",
            complete = QuestState(269, "completed"),
            dependsOn = { "accept-269-seeking-wisdom" },
            route = {
                Point(1453, 0.3913, 0.2790, "Seeking Wisdom",
                    "Travel to Seeking Wisdom."),
            },
        },
        {
            id = "accept-270-the-doomed-fleet",
            kind = "accept",
            priority = 1240,
            conditions = { all = {
                { level = { min = 27 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Doomed Fleet.",
            complete = QuestState(270, "activeOrCompleted"),
            route = {
                Point(1453, 0.3913, 0.2790, "The Doomed Fleet",
                    "Travel to The Doomed Fleet."),
            },
        },
        {
            id = "accept-389-bazil-thredd",
            kind = "accept",
            priority = 1250,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Bazil Thredd.",
            complete = QuestState(389, "activeOrCompleted"),
            route = {
                Point(1453, 0.4919, 0.3028, "Bazil Thredd",
                    "Travel to Bazil Thredd."),
            },
        },
        {
            id = "accept-388-the-color-of-blood",
            kind = "accept",
            priority = 1260,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Color of Blood from Brother Kristoff in Stormwind Cathedral District.",
            complete = QuestState(388, "activeOrCompleted"),
            route = nil,
        },
        {
            id = "turnin-389-bazil-thredd",
            kind = "turnin",
            priority = 1270,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Bazil Thredd.",
            complete = QuestState(389, "completed"),
            dependsOn = { "accept-389-bazil-thredd" },
            route = {
                Point(1453, 0.4111, 0.5809, "Bazil Thredd",
                    "Travel to Bazil Thredd."),
            },
        },
        {
            id = "accept-391-the-stockade-riots",
            kind = "accept",
            priority = 1280,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept The Stockade Riots.",
            complete = QuestState(391, "activeOrCompleted"),
            route = {
                Point(1453, 0.4111, 0.5809, "The Stockade Riots",
                    "Travel to The Stockade Riots."),
            },
        },
        {
            id = "accept-387-quell-the-uprising",
            kind = "accept",
            priority = 1290,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Accept Quell The Uprising.",
            complete = QuestState(387, "activeOrCompleted"),
            route = {
                Point(1453, 0.4111, 0.5809, "Quell The Uprising",
                    "Travel to Quell The Uprising."),
            },
        },
        {
            id = "objective-386-1-targorr-the-dread",
            kind = "objective",
            priority = 1300,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Targorr the Dread.",
            complete = QuestObjective(386, 1, "Targorr the Dread"),
            useClientPin = true,
            route = nil,
        },
        {
            id = "objective-391-1-bazil-thredd",
            kind = "objective",
            priority = 1310,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Bazil Thredd.",
            complete = QuestObjective(391, 1, "Bazil Thredd"),
            dependsOn = { "accept-391-the-stockade-riots" },
            useClientPin = true,
            route = nil,
        },
        {
            id = "objective-377-1-dextren-ward",
            kind = "objective",
            priority = 1320,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Kill Dextren Ward.",
            complete = QuestObjective(377, 1, "Dextren Ward"),
            dependsOn = { "accept-377-crime-and-punishment" },
            useClientPin = true,
            route = nil,
        },
        {
            id = "turnin-387-quell-the-uprising",
            kind = "turnin",
            priority = 1330,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Quell The Uprising.",
            complete = QuestState(387, "completed"),
            dependsOn = { "accept-387-quell-the-uprising" },
            route = {
                Point(1453, 0.4111, 0.5809, "Quell The Uprising",
                    "Travel to Quell The Uprising."),
            },
        },
        {
            id = "turnin-391-the-stockade-riots",
            kind = "turnin",
            priority = 1340,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Stockade Riots.",
            complete = QuestState(391, "completed"),
            dependsOn = { "accept-391-the-stockade-riots", "objective-391-1-bazil-thredd" },
            route = {
                Point(1453, 0.4111, 0.5809, "The Stockade Riots",
                    "Travel to The Stockade Riots."),
            },
        },
        {
            id = "turnin-388-the-color-of-blood",
            kind = "turnin",
            priority = 1350,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in The Color of Blood.",
            complete = QuestState(388, "completed"),
            dependsOn = { "accept-388-the-color-of-blood" },
            useClientPin = true,
            route = nil,
        },
        {
            id = "turnin-386-what-comes-around",
            kind = "turnin",
            priority = 1360,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in What Comes Around...",
            complete = QuestState(386, "completed"),
            dependsOn = { "objective-386-1-targorr-the-dread" },
            route = {
                Point(1433, 0.2626, 0.4658, "What Comes Around..",
                    "Travel to What Comes Around...."),
            },
        },
        {
            id = "turnin-377-crime-and-punishment",
            kind = "turnin",
            priority = 1370,
            conditions = { all = {
                { level = { min = 25 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Crime and Punishment.",
            complete = QuestState(377, "completed"),
            dependsOn = { "accept-377-crime-and-punishment", "objective-377-1-dextren-ward" },
            route = {
                Point(1431, 0.7195, 0.4778, "Crime and Punishment",
                    "Travel to Crime and Punishment."),
            },
        },
        {
            id = "turnin-2923-tinkmaster-overspark",
            kind = "turnin",
            priority = 1380,
            conditions = { all = {
                { level = { min = 29 } },
                { faction = "Alliance" },
            } },
            text = "Turn in Tinkmaster Overspark.",
            complete = QuestState(2923, "completed"),
            dependsOn = { "accept-2923-tinkmaster-overspark" },
            route = {
                Point(1455, 0.6954, 0.5032, "Tinkmaster Overspark",
                    "Travel to Tinkmaster Overspark."),
            },
        },
        {
            id = "woven-accept-98387-blackrock-blockade",
            kind = "accept",
            priority = 1390,
            conditions = { level = { min = 21 } },
            text = "Accept Blackrock Blockade from Marshal Marris in Lakeshire.",
            complete = QuestState(98387, "activeOrCompleted"),
            route = {
                Point(1433, 0.3340, 0.4880, "Marshal Marris",
                    "Travel to Marshal Marris."),
            },
        },
        {
            id = "woven-accept-98386-althers-mill",
            kind = "accept",
            priority = 1400,
            conditions = { level = { min = 21 } },
            text = "Accept Alther's Mill from Foreman Oslow in Lakeshire.",
            complete = QuestState(98386, "activeOrCompleted"),
            route = {
                Point(1433, 0.3220, 0.4860, "Foreman Oslow",
                    "Travel to Foreman Oslow."),
            },
        },
        {
            id = "woven-objective-98387-blackrock-blockade",
            kind = "objective",
            priority = 1410,
            conditions = { level = { min = 21 } },
            useClientPin = true,
            text = "Blackrock Blockade: collect 10 Battleworn Axes from the Blackrock camp you are already clearing. No saved spot for this, so the guide follows the pin in your quest log.",
            complete = QuestState(98387, "complete"),
            route = {
                Point(1433, 0.2920, 0.1160, "Blackrock Grunt",
                    "Travel to Blackrock Grunt."),
            },
        },
        {
            id = "woven-turnin-98387-blackrock-blockade",
            kind = "turnin",
            priority = 1420,
            conditions = { level = { min = 21 } },
            text = "Turn in Blackrock Blockade to Marshal Marris in Lakeshire.",
            complete = QuestState(98387, "completed"),
            route = {
                Point(1433, 0.3340, 0.4880, "Marshal Marris",
                    "Travel to Marshal Marris."),
            },
        },
        {
            id = "woven-objective-98386-althers-mill",
            kind = "objective",
            priority = 1430,
            conditions = { level = { min = 21 } },
            text = "Alther's Mill: slay 12 Greater Tarantulas and destroy 6 Tarantula Eggs.",
            complete = QuestState(98386, "complete"),
            route = {
                Point(1433, 0.5200, 0.4520, "Greater Tarantula",
                    "Travel to Greater Tarantula."),
                Point(1433, 0.4720, 0.4080, "Greater Tarantula",
                    "Travel to Greater Tarantula."),
            },
        },
        {
            id = "woven-turnin-98386-althers-mill",
            kind = "turnin",
            priority = 1440,
            conditions = { level = { min = 21 } },
            text = "Turn in Alther's Mill to Foreman Oslow in Lakeshire.",
            complete = QuestState(98386, "completed"),
            route = {
                Point(1433, 0.3220, 0.4860, "Foreman Oslow",
                    "Travel to Foreman Oslow."),
            },
        },
        {
            id = "woven-accept-96139-the-valor-family",
            kind = "accept",
            priority = 1450,
            conditions = { level = { min = 22 } },
            text = "Accept The Valor Family from Sirra Von'Indi in Darkshire.",
            complete = QuestState(96139, "activeOrCompleted"),
            route = {
                Point(1431, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "woven-accept-96137-iras-dagger",
            kind = "accept",
            priority = 1460,
            conditions = { level = { min = 24 } },
            text = "Accept Ira's Dagger from Sirra Von'Indi in Darkshire.",
            complete = QuestState(96137, "activeOrCompleted"),
            route = {
                Point(1431, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "woven-accept-96138-merricks-bow",
            kind = "accept",
            priority = 1470,
            conditions = { level = { min = 28 } },
            text = "Accept Merrick's Bow from Sirra Von'Indi in Darkshire.",
            complete = QuestState(96138, "activeOrCompleted"),
            route = {
                Point(1431, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "woven-objective-96137-black-ravager",
            kind = "objective",
            priority = 1480,
            conditions = { level = { min = 24 } },
            text = "Ira's Dagger: slay 7 Black Ravagers.",
            complete = QuestObjective(96137, 2),
            route = {
                Point(1431, 0.6940, 0.3580, "Black Ravager",
                    "Travel to Black Ravager."),
            },
        },
        {
            id = "woven-objective-96137-young-black-ravager",
            kind = "objective",
            priority = 1490,
            conditions = { level = { min = 24 } },
            text = "Ira's Dagger: slay 10 Young Black Ravagers.",
            complete = QuestObjective(96137, 1),
            route = {
                Point(1431, 0.2380, 0.7900, "Young Black Ravager",
                    "Travel to Young Black Ravager."),
            },
        },
        {
            id = "woven-objective-96139-the-valor-family",
            kind = "objective",
            priority = 1500,
            conditions = { level = { min = 22 } },
            useClientPin = true,
            text = "The Valor Family: search Raven Hill. No saved spot for this, so the guide follows the pin in your quest log.",
            complete = QuestState(96139, "complete"),
            route = {
                Point(1431, 0.1833, 0.5625, "Raven Hill",
                    "Travel to Raven Hill."),
            },
        },
        {
            id = "woven-objective-96138-merricks-bow",
            kind = "objective",
            priority = 1510,
            conditions = { level = { min = 28 } },
            text = "Merrick's Bow: slay 8 Splinter Fist Warriors and 4 Splinter Fist Taskmasters in Raven Hill Cemetery.",
            complete = QuestState(96138, "complete"),
            route = {
                Point(1431, 0.3420, 0.7740, "Splinter Fist Warrior",
                    "Travel to Splinter Fist Warrior."),
                Point(1431, 0.3400, 0.7380, "Splinter Fist Taskmaster",
                    "Travel to Splinter Fist Taskmaster."),
            },
        },
        {
            id = "woven-turnin-96139-the-valor-family",
            kind = "turnin",
            priority = 1520,
            conditions = { level = { min = 22 } },
            text = "Turn in The Valor Family to Sirra Von'Indi in Darkshire.",
            complete = QuestState(96139, "completed"),
            route = {
                Point(1431, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "woven-turnin-96137-iras-dagger",
            kind = "turnin",
            priority = 1530,
            conditions = { level = { min = 24 } },
            text = "Turn in Ira's Dagger to Sirra Von'Indi in Darkshire.",
            complete = QuestState(96137, "completed"),
            route = {
                Point(1431, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "woven-turnin-96138-merricks-bow",
            kind = "turnin",
            priority = 1540,
            conditions = { level = { min = 28 } },
            text = "Turn in Merrick's Bow to Sirra Von'Indi in Darkshire.",
            complete = QuestState(96138, "completed"),
            route = {
                Point(1431, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "woven-accept-98447-the-valor-family",
            kind = "accept",
            priority = 1550,
            conditions = { level = { min = 27 } },
            text = "Accept The Valor Family from Sirra Von'Indi in Darkshire.",
            complete = QuestState(98447, "activeOrCompleted"),
            route = {
                Point(1431, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
        {
            id = "woven-objective-98447-the-valor-family",
            kind = "objective",
            priority = 1560,
            conditions = { level = { min = 27 } },
            text = "The Valor Family: find the cause of the ghosts at Ol' Sandy in Raven Hill.",
            complete = QuestState(98447, "complete"),
            route = {
                Point(1431, 0.1720, 0.5380, "Ol' Sandy",
                    "Travel to Ol' Sandy."),
            },
        },
        {
            id = "woven-turnin-98447-the-valor-family",
            kind = "turnin",
            priority = 1570,
            conditions = { level = { min = 27 } },
            text = "Turn in The Valor Family to Sirra Von'Indi in Darkshire.",
            complete = QuestState(98447, "completed"),
            route = {
                Point(1431, 0.7260, 0.4760, "Sirra Von'Indi",
                    "Travel to Sirra Von'Indi."),
            },
        },
    },
})
