local _, ns = ...

-- Forever Casual spine: Silverpine Forest (13-15)
-- Hearth, grind/ding, trainer, vendor, and flight-learn steps omitted.
-- Forever weaves ported from prior Leveling chapters (quest id >= 90000).
-- Coordinates not yet validated in Forever.

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

local MAP = {
    DUROTAR = 1411,
    SILVERPINE_FOREST = 1421,
    ORGRIMMAR = 1454,
    THUNDER_BLUFF = 1456,
    UNDERCITY = 1458,
}

ns:RegisterGuide({
    id = "leveling-era-horde-silverpine-forest",
    title = "Silverpine Forest",
    category = "Leveling Quest Guides",
    revision = 1,
    casualSpine = true,
    conditions = {
        all = {
            { faction = "Horde" },
            { race = 5 },
            { level = { min = 13 } },
        },
    },
    goals = {
        {
            id = "accept-435-escorting-erland",
            kind = "accept",
            priority = 10,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Escorting Erland.",
            complete = QuestState(435, "activeOrCompleted"),
            route = {
                Point(1421, 0.5619, 0.0918, "Escorting Erland",
                    "Travel to Escorting Erland."),
            },
        },
        {
            id = "turnin-435-escorting-erland",
            kind = "turnin",
            priority = 20,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Escorting Erland.",
            complete = QuestState(435, "completed"),
            dependsOn = { "accept-435-escorting-erland" },
            route = {
                Point(1421, 0.5346, 0.1343, "Escorting Erland",
                    "Travel to Escorting Erland."),
            },
        },
        {
            id = "accept-449-the-deathstalkers-report",
            kind = "accept",
            priority = 30,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept The Deathstalkers' Report.",
            complete = QuestState(449, "activeOrCompleted"),
            route = {
                Point(1421, 0.5346, 0.1343, "The Deathstalkers' Report",
                    "Travel to The Deathstalkers' Report."),
            },
        },
        {
            id = "accept-429-wild-hearts",
            kind = "accept",
            priority = 40,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Wild Hearts.",
            complete = QuestState(429, "activeOrCompleted"),
            route = {
                Point(1421, 0.5346, 0.1343, "Wild Hearts",
                    "Travel to Wild Hearts."),
            },
        },
        {
            id = "accept-421-prove-your-worth",
            kind = "accept",
            priority = 50,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Prove Your Worth.",
            complete = QuestState(421, "activeOrCompleted"),
            route = {
                Point(1421, 0.4420, 0.3978, "Prove Your Worth",
                    "Travel to Prove Your Worth."),
            },
        },
        {
            id = "accept-477-border-crossings",
            kind = "accept",
            priority = 60,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Border Crossings.",
            complete = QuestState(477, "activeOrCompleted"),
            route = {
                Point(1421, 0.4398, 0.4093, "Border Crossings",
                    "Travel to Border Crossings."),
            },
        },
        {
            id = "accept-6321-supplying-the-sepulcher",
            kind = "accept",
            priority = 70,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 5 },
            } },
            text = "Accept Supplying the Sepulcher.",
            complete = QuestState(6321, "activeOrCompleted"),
            route = {
                Point(1421, 0.4343, 0.4168, "Supplying the Sepulcher",
                    "Travel to Supplying the Sepulcher."),
            },
        },
        {
            id = "turnin-449-the-deathstalkers-report",
            kind = "turnin",
            priority = 80,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in The Deathstalkers' Report.",
            complete = QuestState(449, "completed"),
            dependsOn = { "accept-449-the-deathstalkers-report" },
            route = {
                Point(1421, 0.4309, 0.4139, "The Deathstalkers' Report",
                    "Travel to The Deathstalkers' Report."),
            },
        },
        {
            id = "accept-3221-speak-with-renferrel",
            kind = "accept",
            priority = 90,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Speak with Renferrel.",
            complete = QuestState(3221, "activeOrCompleted"),
            route = {
                Point(1421, 0.4309, 0.4139, "Speak with Renferrel",
                    "Travel to Speak with Renferrel."),
            },
        },
        {
            id = "accept-437-the-dead-fields",
            kind = "accept",
            priority = 100,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept The Dead Fields.",
            complete = QuestState(437, "activeOrCompleted"),
            route = {
                Point(1421, 0.4309, 0.4139, "The Dead Fields",
                    "Travel to The Dead Fields."),
            },
        },
        {
            id = "turnin-445-delivery-to-silverpine-forest",
            kind = "turnin",
            priority = 110,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Delivery to Silverpine Forest.",
            complete = QuestState(445, "completed"),
            route = {
                Point(1421, 0.4280, 0.4086, "Delivery to Silverpine Forest",
                    "Travel to Delivery to Silverpine Forest."),
            },
        },
        {
            id = "turnin-3221-speak-with-renferrel",
            kind = "turnin",
            priority = 120,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Speak with Renferrel.",
            complete = QuestState(3221, "completed"),
            dependsOn = { "accept-3221-speak-with-renferrel" },
            route = {
                Point(1421, 0.4280, 0.4086, "Speak with Renferrel",
                    "Travel to Speak with Renferrel."),
            },
        },
        {
            id = "accept-1359-zinge-s-delivery",
            kind = "accept",
            priority = 130,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Zinge's Delivery.",
            complete = QuestState(1359, "activeOrCompleted"),
            route = {
                Point(1421, 0.4280, 0.4086, "Zinge's Delivery",
                    "Travel to Zinge's Delivery."),
            },
        },
        {
            id = "turnin-429-wild-hearts",
            kind = "turnin",
            priority = 140,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Wild Hearts.",
            complete = QuestState(429, "completed"),
            dependsOn = { "accept-429-wild-hearts" },
            route = {
                Point(1421, 0.4280, 0.4086, "Wild Hearts",
                    "Travel to Wild Hearts."),
            },
        },
        {
            id = "accept-430-return-to-quinn",
            kind = "accept",
            priority = 150,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Return to Quinn.",
            complete = QuestState(430, "activeOrCompleted"),
            route = {
                Point(1421, 0.4280, 0.4086, "Return to Quinn",
                    "Travel to Quinn."),
            },
        },
        {
            id = "accept-447-a-recipe-for-death",
            kind = "accept",
            priority = 160,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept A Recipe For Death.",
            complete = QuestState(447, "activeOrCompleted"),
            route = {
                Point(1421, 0.4280, 0.4086, "A Recipe For Death",
                    "Travel to A Recipe For Death."),
            },
        },
        {
            id = "turnin-6321-supplying-the-sepulcher",
            kind = "turnin",
            priority = 170,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Supplying the Sepulcher.",
            complete = QuestState(6321, "completed"),
            dependsOn = { "accept-6321-supplying-the-sepulcher" },
            route = {
                Point(1421, 0.4562, 0.4260, "Supplying the Sepulcher",
                    "Travel to Supplying the Sepulcher."),
            },
        },
        {
            id = "accept-6323-ride-to-the-undercity",
            kind = "accept",
            priority = 180,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Ride to the Undercity.",
            complete = QuestState(6323, "activeOrCompleted"),
            route = {
                Point(1421, 0.4562, 0.4260, "Ride to the Undercity",
                    "Travel to Ride to the Undercity."),
            },
        },
        {
            id = "objective-421-1-moonrage-whitescalp",
            kind = "objective",
            priority = 190,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Kill 5 Moonrage Whitescalp.",
            complete = QuestObjective(421, 1, "Moonrage Whitescalp"),
            dependsOn = { "accept-421-prove-your-worth" },
            route = {
                Point(1421, 0.4900, 0.3680, "Moonrage Whitescalp",
                    "Travel to Moonrage Whitescalp."),
            },
        },
        {
            id = "turnin-421-prove-your-worth",
            kind = "turnin",
            priority = 200,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Prove Your Worth.",
            complete = QuestState(421, "completed"),
            dependsOn = { "accept-421-prove-your-worth", "objective-421-1-moonrage-whitescalp" },
            route = {
                Point(1421, 0.4420, 0.3978, "Prove Your Worth",
                    "Travel to Prove Your Worth."),
            },
        },
        {
            id = "accept-422-arugal-s-folly",
            kind = "accept",
            priority = 210,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Arugal's Folly.",
            complete = QuestState(422, "activeOrCompleted"),
            route = {
                Point(1421, 0.4420, 0.3978, "Arugal's Folly",
                    "Travel to Arugal's Folly."),
            },
        },
        {
            id = "turnin-430-return-to-quinn",
            kind = "turnin",
            priority = 220,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Return to Quinn.",
            complete = QuestState(430, "completed"),
            dependsOn = { "accept-430-return-to-quinn" },
            route = {
                Point(1421, 0.5343, 0.1259, "Return to Quinn",
                    "Travel to Quinn."),
            },
        },
        {
            id = "accept-425-ivar-the-foul",
            kind = "accept",
            priority = 230,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Ivar the Foul.",
            complete = QuestState(425, "activeOrCompleted"),
            route = {
                Point(1421, 0.5346, 0.1343, "Ivar the Foul",
                    "Travel to Ivar the Foul."),
            },
        },
        {
            id = "objective-425-1-ivar-the-foul",
            kind = "objective",
            priority = 240,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Kill Ivar the Foul.",
            complete = QuestObjective(425, 1, "Ivar the Foul"),
            dependsOn = { "accept-425-ivar-the-foul" },
            route = {
                Point(1421, 0.5153, 0.1391, "Ivar the Foul",
                    "Travel to Ivar the Foul."),
            },
        },
        {
            id = "turnin-425-ivar-the-foul",
            kind = "turnin",
            priority = 250,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Ivar the Foul.",
            complete = QuestState(425, "completed"),
            dependsOn = { "accept-425-ivar-the-foul", "objective-425-1-ivar-the-foul" },
            route = {
                Point(1421, 0.5346, 0.1343, "Ivar the Foul",
                    "Travel to Ivar the Foul."),
            },
        },
        {
            id = "turnin-422-arugal-s-folly",
            kind = "turnin",
            priority = 260,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Arugal's Folly.",
            complete = QuestState(422, "completed"),
            dependsOn = { "accept-422-arugal-s-folly" },
            route = {
                Point(1421, 0.4420, 0.3978, "Arugal's Folly",
                    "Travel to Arugal's Folly."),
            },
        },
        {
            id = "accept-423-arugal-s-folly",
            kind = "accept",
            priority = 270,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Arugal's Folly.",
            complete = QuestState(423, "activeOrCompleted"),
            route = {
                Point(1421, 0.4420, 0.3978, "Arugal's Folly",
                    "Travel to Arugal's Folly."),
            },
        },
        {
            id = "turnin-437-the-dead-fields",
            kind = "turnin",
            priority = 280,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in The Dead Fields.",
            complete = QuestState(437, "completed"),
            dependsOn = { "accept-437-the-dead-fields" },
            route = {
                Point(1421, 0.4309, 0.4139, "The Dead Fields",
                    "Travel to The Dead Fields."),
            },
        },
        {
            id = "accept-438-the-decrepit-ferry",
            kind = "accept",
            priority = 290,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept The Decrepit Ferry.",
            complete = QuestState(438, "activeOrCompleted"),
            route = {
                Point(1421, 0.4309, 0.4139, "The Decrepit Ferry",
                    "Travel to The Decrepit Ferry."),
            },
        },
        {
            id = "turnin-438-the-decrepit-ferry",
            kind = "turnin",
            priority = 300,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in The Decrepit Ferry.",
            complete = QuestState(438, "completed"),
            dependsOn = { "accept-438-the-decrepit-ferry" },
            route = {
                Point(1421, 0.5839, 0.3484, "The Decrepit Ferry",
                    "Travel to The Decrepit Ferry."),
            },
        },
        {
            id = "accept-439-rot-hide-clues",
            kind = "accept",
            priority = 310,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Rot Hide Clues.",
            complete = QuestState(439, "activeOrCompleted"),
            route = {
                Point(1421, 0.5839, 0.3484, "Rot Hide Clues",
                    "Travel to Rot Hide Clues."),
            },
        },
        {
            id = "objective-423-2-moonrage-darksoul",
            kind = "objective",
            priority = 320,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Kill Moonrage Darksoul.",
            complete = QuestObjective(423, 2, "Moonrage Darksoul"),
            dependsOn = { "accept-423-arugal-s-folly" },
            route = {
                Point(1421, 0.5654, 0.4602, "Moonrage Darksoul",
                    "Travel to Moonrage Darksoul."),
            },
        },
        {
            id = "turnin-477-border-crossings",
            kind = "turnin",
            priority = 330,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Border Crossings.",
            complete = QuestState(477, "completed"),
            dependsOn = { "accept-477-border-crossings" },
            route = {
                Point(1421, 0.5654, 0.4602, "Border Crossings",
                    "Travel to Border Crossings."),
            },
        },
        {
            id = "accept-478-maps-and-runes",
            kind = "accept",
            priority = 340,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Maps and Runes.",
            complete = QuestState(478, "activeOrCompleted"),
            route = {
                Point(1421, 0.5654, 0.4602, "Maps and Runes",
                    "Travel to Maps and Runes."),
            },
        },
        {
            id = "turnin-478-maps-and-runes",
            kind = "turnin",
            priority = 350,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Maps and Runes.",
            complete = QuestState(478, "completed"),
            dependsOn = { "accept-478-maps-and-runes" },
            route = {
                Point(1421, 0.4398, 0.4093, "Maps and Runes",
                    "Travel to Maps and Runes."),
            },
        },
        {
            id = "accept-481-dalar-s-analysis",
            kind = "accept",
            priority = 360,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Dalar's Analysis.",
            complete = QuestState(481, "activeOrCompleted"),
            route = {
                Point(1421, 0.4398, 0.4093, "Dalar's Analysis",
                    "Travel to Dalar's Analysis."),
            },
        },
        {
            id = "turnin-423-arugal-s-folly",
            kind = "turnin",
            priority = 370,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Arugal's Folly.",
            complete = QuestState(423, "completed"),
            dependsOn = { "accept-423-arugal-s-folly", "objective-423-2-moonrage-darksoul" },
            route = {
                Point(1421, 0.4419, 0.3978, "Arugal's Folly",
                    "Travel to Arugal's Folly."),
            },
        },
        {
            id = "accept-424-arugal-s-folly",
            kind = "accept",
            priority = 375,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Arugal's Folly from Dalar Dawnweaver.",
            complete = QuestState(424, "activeOrCompleted"),
            dependsOn = { "turnin-423-arugal-s-folly" },
            route = {
                Point(1421, 0.4419, 0.3978, "Dalar Dawnweaver",
                    "Travel to Dalar Dawnweaver."),
            },
        },
        {
            id = "turnin-481-dalar-s-analysis",
            kind = "turnin",
            priority = 380,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Dalar's Analysis.",
            complete = QuestState(481, "completed"),
            dependsOn = { "accept-481-dalar-s-analysis" },
            route = {
                Point(1421, 0.4419, 0.3978, "Dalar's Analysis",
                    "Travel to Dalar's Analysis."),
            },
        },
        {
            id = "accept-482-dalaran-s-intentions",
            kind = "accept",
            priority = 390,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Dalaran's Intentions.",
            complete = QuestState(482, "activeOrCompleted"),
            route = {
                Point(1421, 0.4419, 0.3978, "Dalaran's Intentions",
                    "Travel to Dalaran's Intentions."),
            },
        },
        {
            id = "turnin-482-dalaran-s-intentions",
            kind = "turnin",
            priority = 400,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Dalaran's Intentions.",
            complete = QuestState(482, "completed"),
            dependsOn = { "accept-482-dalaran-s-intentions" },
            route = {
                Point(1421, 0.4398, 0.4093, "Dalaran's Intentions",
                    "Travel to Dalaran's Intentions."),
            },
        },
        {
            id = "accept-479-ambermill-investigations",
            kind = "accept",
            priority = 405,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Ambermill Investigations from Shadow Priest Allister.",
            complete = QuestState(479, "activeOrCompleted"),
            dependsOn = { "turnin-482-dalaran-s-intentions" },
            route = {
                Point(1421, 0.4398, 0.4093, "Shadow Priest Allister",
                    "Travel to Shadow Priest Allister."),
            },
        },
        {
            id = "turnin-439-rot-hide-clues",
            kind = "turnin",
            priority = 410,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Rot Hide Clues.",
            complete = QuestState(439, "completed"),
            dependsOn = { "accept-439-rot-hide-clues" },
            route = {
                Point(1421, 0.4309, 0.4139, "Rot Hide Clues",
                    "Travel to Rot Hide Clues."),
            },
        },
        {
            id = "turnin-6323-ride-to-the-undercity",
            kind = "turnin",
            priority = 420,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 5 },
            } },
            text = "Turn in Ride to the Undercity.",
            complete = QuestState(6323, "completed"),
            dependsOn = { "accept-6323-ride-to-the-undercity" },
            route = {
                Point(1458, 0.6149, 0.4180, "Ride to the Undercity",
                    "Travel to Ride to the Undercity."),
            },
        },
        {
            id = "accept-6322-michael-garrett",
            kind = "accept",
            priority = 430,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 5 },
            } },
            text = "Accept Michael Garrett.",
            complete = QuestState(6322, "activeOrCompleted"),
            route = {
                Point(1458, 0.6149, 0.4180, "Michael Garrett",
                    "Travel to Michael Garrett."),
            },
        },
        {
            id = "turnin-6322-michael-garrett",
            kind = "turnin",
            priority = 440,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 5 },
            } },
            text = "Turn in Michael Garrett.",
            complete = QuestState(6322, "completed"),
            dependsOn = { "accept-6322-michael-garrett" },
            route = {
                Point(1458, 0.6326, 0.4856, "Michael Garrett",
                    "Travel to Michael Garrett."),
            },
        },
        {
            id = "accept-6324-return-to-podrig",
            kind = "accept",
            priority = 450,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 5 },
            } },
            text = "Accept Return to Podrig.",
            complete = QuestState(6324, "activeOrCompleted"),
            route = {
                Point(1458, 0.6326, 0.4856, "Return to Podrig",
                    "Travel to Podrig."),
            },
        },
        {
            id = "turnin-6324-return-to-podrig",
            kind = "turnin",
            priority = 460,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 5 },
            } },
            text = "Turn in Return to Podrig.",
            complete = QuestState(6324, "completed"),
            dependsOn = { "accept-6324-return-to-podrig" },
            route = {
                Point(1421, 0.4343, 0.4168, "Return to Podrig",
                    "Travel to Podrig."),
            },
        },
        {
            id = "turnin-447-a-recipe-for-death",
            kind = "turnin",
            priority = 470,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in A Recipe For Death.",
            complete = QuestState(447, "completed"),
            dependsOn = { "accept-447-a-recipe-for-death" },
            route = {
                Point(1458, 0.5284, 0.7762, "A Recipe For Death",
                    "Travel to A Recipe For Death."),
            },
        },
        {
            id = "turnin-1359-zinge-s-delivery",
            kind = "turnin",
            priority = 480,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Zinge's Delivery.",
            complete = QuestState(1359, "completed"),
            dependsOn = { "accept-1359-zinge-s-delivery" },
            route = {
                Point(1458, 0.5013, 0.6799, "Zinge's Delivery",
                    "Travel to Zinge's Delivery."),
            },
        },
        {
            id = "accept-1358-sample-for-helbrim",
            kind = "accept",
            priority = 490,
            conditions = { all = {
                { level = { min = 15 } },
                { faction = "Horde" },
            } },
            text = "Accept Sample for Helbrim.",
            complete = QuestState(1358, "activeOrCompleted"),
            route = {
                Point(1458, 0.5013, 0.6799, "Sample for Helbrim",
                    "Travel to Sample for Helbrim."),
            },
        },
        {
            id = "turnin-1886-the-deathstalkers",
            kind = "turnin",
            priority = 500,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { class = 4 },
            } },
            text = "Turn in The Deathstalkers.",
            complete = QuestState(1886, "completed"),
            route = {
                Point(1458, 0.8351, 0.6911, "The Deathstalkers",
                    "Travel to The Deathstalkers."),
            },
        },
        {
            id = "accept-1898-the-deathstalkers",
            kind = "accept",
            priority = 510,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { class = 4 },
            } },
            text = "Accept The Deathstalkers.",
            complete = QuestState(1898, "activeOrCompleted"),
            route = {
                Point(1458, 0.8351, 0.6911, "The Deathstalkers",
                    "Travel to The Deathstalkers."),
            },
        },
        {
            id = "turnin-1898-the-deathstalkers",
            kind = "turnin",
            priority = 520,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { class = 4 },
            } },
            text = "Turn in The Deathstalkers.",
            complete = QuestState(1898, "completed"),
            dependsOn = { "accept-1898-the-deathstalkers" },
            route = {
                Point(1458, 0.5482, 0.7630, "The Deathstalkers",
                    "Travel to The Deathstalkers."),
            },
        },
        {
            id = "accept-1899-the-deathstalkers",
            kind = "accept",
            priority = 530,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { class = 4 },
            } },
            text = "Accept The Deathstalkers.",
            complete = QuestState(1899, "activeOrCompleted"),
            route = {
                Point(1458, 0.5482, 0.7630, "The Deathstalkers",
                    "Travel to The Deathstalkers."),
            },
        },
        {
            id = "objective-1899-1-andron-s-bookshelf",
            kind = "objective",
            priority = 540,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { class = 4 },
            } },
            text = "Click Andron's Bookshelf.",
            complete = QuestObjective(1899, 1, "Andron's Bookshelf"),
            dependsOn = { "accept-1899-the-deathstalkers" },
            route = {
                Point(1458, 0.5542, 0.7705, "Andron's Bookshelf",
                    "Travel to Andron's Bookshelf."),
            },
        },
        {
            id = "turnin-1899-the-deathstalkers",
            kind = "turnin",
            priority = 550,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { class = 4 },
            } },
            text = "Turn in The Deathstalkers.",
            complete = QuestState(1899, "completed"),
            dependsOn = { "accept-1899-the-deathstalkers", "objective-1899-1-andron-s-bookshelf" },
            route = {
                Point(1458, 0.8351, 0.6911, "The Deathstalkers",
                    "Travel to The Deathstalkers."),
            },
        },
        {
            id = "accept-1978-the-deathstalkers",
            kind = "accept",
            priority = 560,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { class = 4 },
            } },
            text = "Accept The Deathstalkers.",
            complete = QuestState(1978, "activeOrCompleted"),
            route = {
                Point(1458, 0.8351, 0.6911, "The Deathstalkers",
                    "Travel to The Deathstalkers."),
            },
        },
        {
            id = "turnin-1978-the-deathstalkers",
            kind = "turnin",
            priority = 570,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { class = 4 },
            } },
            text = "Turn in The Deathstalkers.",
            complete = QuestState(1978, "completed"),
            dependsOn = { "accept-1978-the-deathstalkers" },
            route = {
                Point(1458, 0.5975, 0.8464, "The Deathstalkers",
                    "Travel to The Deathstalkers."),
            },
        },
        {
            id = "accept-5723-testing-an-enemy-s-strength",
            kind = "accept",
            priority = 580,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 6 },
            } },
            text = "Accept Testing an Enemy's Strength.",
            complete = QuestState(5723, "activeOrCompleted"),
            route = {
                Point(1456, 0.7050, 0.3182, "Testing an Enemy's Strength",
                    "Travel to Testing an Enemy's Strength."),
            },
        },
        {
            id = "accept-5722-searching-for-the-lost-satchel",
            kind = "accept",
            priority = 590,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 6 },
            } },
            text = "Accept Searching for the Lost Satchel.",
            complete = QuestState(5722, "activeOrCompleted"),
            route = {
                Point(1456, 0.7050, 0.3182, "Searching for the Lost Satchel",
                    "Travel to Searching for the Lost Satchel."),
            },
        },
        {
            id = "accept-5726-hidden-enemies",
            kind = "accept",
            priority = 600,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Hidden Enemies.",
            complete = QuestState(5726, "activeOrCompleted"),
            route = {
                Point(1454, 0.3173, 0.3782, "Hidden Enemies",
                    "Travel to Hidden Enemies."),
            },
        },
        {
            id = "objective-5726-1-burning-blade-apprentice",
            kind = "objective",
            priority = 610,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Kill Burning Blade Apprentice.",
            complete = QuestObjective(5726, 1, "Burning Blade Apprentice"),
            dependsOn = { "accept-5726-hidden-enemies" },
            route = {
                Point(1411, 0.5498, 0.0967, "Burning Blade Apprentice",
                    "Travel to Burning Blade Apprentice."),
            },
        },
        {
            id = "turnin-5726-hidden-enemies",
            kind = "turnin",
            priority = 620,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Hidden Enemies.",
            complete = QuestState(5726, "completed"),
            dependsOn = { "accept-5726-hidden-enemies", "objective-5726-1-burning-blade-apprentice" },
            route = {
                Point(1454, 0.3173, 0.3782, "Hidden Enemies",
                    "Travel to Hidden Enemies."),
            },
        },
        {
            id = "accept-5727-hidden-enemies",
            kind = "accept",
            priority = 630,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Hidden Enemies.",
            complete = QuestState(5727, "activeOrCompleted"),
            route = {
                Point(1454, 0.3173, 0.3782, "Hidden Enemies",
                    "Travel to Hidden Enemies."),
            },
        },
        {
            id = "turnin-5727-hidden-enemies",
            kind = "turnin",
            priority = 640,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Hidden Enemies.",
            complete = QuestState(5727, "completed"),
            dependsOn = { "accept-5727-hidden-enemies" },
            route = {
                Point(1454, 0.3174, 0.3783, "Hidden Enemies",
                    "Travel to Hidden Enemies."),
            },
        },
        {
            id = "accept-5728-hidden-enemies",
            kind = "accept",
            priority = 650,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Hidden Enemies.",
            complete = QuestState(5728, "activeOrCompleted"),
            route = {
                Point(1454, 0.3174, 0.3783, "Hidden Enemies",
                    "Travel to Hidden Enemies."),
            },
        },
        {
            id = "accept-5761-slaying-the-beast",
            kind = "accept",
            priority = 660,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Slaying the Beast.",
            complete = QuestState(5761, "activeOrCompleted"),
            route = {
                Point(1454, 0.4949, 0.5060, "Slaying the Beast",
                    "Travel to Slaying the Beast."),
            },
        },
        {
            id = "turnin-5722-searching-for-the-lost-satchel",
            kind = "turnin",
            priority = 670,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 6 },
            } },
            text = "Turn in Searching for the Lost Satchel.",
            complete = QuestState(5722, "completed"),
            dependsOn = { "accept-5722-searching-for-the-lost-satchel" },
            useClientPin = true,
            route = nil,
        },
        {
            id = "accept-5724-returning-the-lost-satchel",
            kind = "accept",
            priority = 680,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 6 },
            } },
            text = "Accept Returning the Lost Satchel after Maur Grimtotem's satchel drops in Ragefire Chasm.",
            complete = QuestState(5724, "activeOrCompleted"),
            route = nil,
        },
        {
            id = "objective-5761-2-taragaman-the-hungerer",
            kind = "objective",
            priority = 690,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Kill Taragaman the Hungerer.",
            complete = QuestObjective(5761, 2, "Taragaman the Hungerer"),
            dependsOn = { "accept-5761-slaying-the-beast" },
            useClientPin = true,
            route = nil,
        },
        {
            id = "objective-5728-2-jergosh-the-invoker",
            kind = "objective",
            priority = 700,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Kill Jergosh the Invoker.",
            complete = QuestObjective(5728, 2, "Jergosh the Invoker"),
            dependsOn = { "accept-5728-hidden-enemies" },
            useClientPin = true,
            route = nil,
        },
        {
            id = "objective-5728-1-bazzalan",
            kind = "objective",
            priority = 710,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Kill Bazzalan.",
            complete = QuestObjective(5728, 1, "Bazzalan"),
            dependsOn = { "accept-5728-hidden-enemies" },
            useClientPin = true,
            route = nil,
        },
        {
            id = "turnin-5761-slaying-the-beast",
            kind = "turnin",
            priority = 720,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Slaying the Beast.",
            complete = QuestState(5761, "completed"),
            dependsOn = { "accept-5761-slaying-the-beast", "objective-5761-2-taragaman-the-hungerer" },
            route = {
                Point(1454, 0.4949, 0.5060, "Slaying the Beast",
                    "Travel to Slaying the Beast."),
            },
        },
        {
            id = "turnin-5728-hidden-enemies",
            kind = "turnin",
            priority = 730,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Hidden Enemies.",
            complete = QuestState(5728, "completed"),
            dependsOn = { "accept-5728-hidden-enemies", "objective-5728-2-jergosh-the-invoker", "objective-5728-1-bazzalan" },
            route = {
                Point(1454, 0.3174, 0.3783, "Hidden Enemies",
                    "Travel to Hidden Enemies."),
            },
        },
        {
            id = "turnin-5723-testing-an-enemy-s-strength",
            kind = "turnin",
            priority = 740,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 6 },
            } },
            text = "Turn in Testing an Enemy's Strength.",
            complete = QuestState(5723, "completed"),
            dependsOn = { "accept-5723-testing-an-enemy-s-strength" },
            route = {
                Point(1456, 0.7050, 0.3182, "Testing an Enemy's Strength",
                    "Travel to Testing an Enemy's Strength."),
            },
        },
        {
            id = "turnin-5722-searching-for-the-lost-satchel-2",
            kind = "turnin",
            priority = 750,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
                { race = 6 },
            } },
            text = "Turn in Searching for the Lost Satchel.",
            complete = QuestState(5722, "completed"),
            dependsOn = { "accept-5722-searching-for-the-lost-satchel" },
            route = {
                Point(1456, 0.7050, 0.3182, "Searching for the Lost Satchel",
                    "Travel to Searching for the Lost Satchel."),
            },
        },
        {
            id = "woven-accept-91920-wild-eyes",
            kind = "accept",
            priority = 760,
            conditions = { level = { min = 11 } },
            text = "Accept Wild Eyes from Quinn Yorick at the Ivar Patch.",
            complete = QuestState(91920, "activeOrCompleted"),
            route = {
                Point(1421, 0.5340, 0.1260, "Quinn Yorick",
                    "Travel to Quinn Yorick."),
            },
        },
        {
            id = "woven-objective-91920-wild-eyes",
            kind = "objective",
            priority = 770,
            conditions = { level = { min = 11 } },
            text = "Wild Eyes: gather 3 Murloc Eyes from the Vile Fin murlocs around the lake.",
            complete = QuestState(91920, "complete"),
            route = {
                Point(1421, 0.5980, 0.1540, "Vile Fin Shredder",
                    "Travel to Vile Fin Shredder."),
            },
        },
        {
            id = "woven-turnin-91920-wild-eyes",
            kind = "turnin",
            priority = 780,
            conditions = { level = { min = 11 } },
            text = "Turn in Wild Eyes to Apothecary Renferrel in the Sepulcher.",
            complete = QuestState(91920, "completed"),
            route = {
                Point(1421, 0.4280, 0.4080, "Apothecary Renferrel",
                    "Travel to Apothecary Renferrel."),
            },
        },
        {
            id = "woven-accept-91921-return-to-quinn-again",
            kind = "accept",
            priority = 790,
            conditions = { level = { min = 11 } },
            text = "Accept Return to Quinn (Again) from Apothecary Renferrel in the Sepulcher.",
            complete = QuestState(91921, "activeOrCompleted"),
            route = {
                Point(1421, 0.4280, 0.4080, "Apothecary Renferrel",
                    "Travel to Apothecary Renferrel."),
            },
        },
        {
            id = "woven-turnin-91921-return-to-quinn-again",
            kind = "turnin",
            priority = 800,
            conditions = { level = { min = 11 } },
            text = "Return to Quinn (Again): bring Quinn's potion to Quinn Yorick at the Ivar Patch.",
            complete = QuestState(91921, "completed"),
            route = {
                Point(1421, 0.5340, 0.1260, "Quinn Yorick",
                    "Travel to Quinn Yorick."),
            },
        },
        {
            id = "objective-424-1-grimson-the-pale",
            kind = "objective",
            priority = 802,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Kill Grimson the Pale and collect the Head of Grimson in Deep Elem Mine.",
            complete = QuestObjective(424, 1, "Head of Grimson"),
            dependsOn = { "accept-424-arugal-s-folly" },
            route = {
                Point(1421, 0.5657, 0.4601, "Deep Elem Mine",
                    "Travel to Deep Elem Mine."),
                Point(1421, 0.5854, 0.4487, "Grimson the Pale",
                    "Travel to Grimson the Pale."),
            },
        },
        {
            id = "objective-479-1-dalaran-pendant",
            kind = "objective",
            priority = 803,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Collect 8 Dalaran Pendants from Dalaran humans in Ambermill.",
            complete = QuestObjective(479, 1, "Dalaran Pendant"),
            dependsOn = { "accept-479-ambermill-investigations" },
            route = {
                Point(1421, 0.5997, 0.6424, "Ambermill",
                    "Travel to Ambermill."),
            },
        },
        {
            id = "turnin-424-arugal-s-folly",
            kind = "turnin",
            priority = 804,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Arugal's Folly to Dalar Dawnweaver.",
            complete = QuestState(424, "completed"),
            dependsOn = { "accept-424-arugal-s-folly", "objective-424-1-grimson-the-pale" },
            route = {
                Point(1421, 0.4419, 0.3978, "Dalar Dawnweaver",
                    "Travel to Dalar Dawnweaver."),
            },
        },
        {
            id = "accept-99-arugal-s-folly",
            kind = "accept",
            priority = 805,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Accept Arugal's Folly from Dalar Dawnweaver.",
            complete = QuestState(99, "activeOrCompleted"),
            dependsOn = { "turnin-424-arugal-s-folly" },
            route = {
                Point(1421, 0.4419, 0.3978, "Dalar Dawnweaver",
                    "Travel to Dalar Dawnweaver."),
            },
        },
        {
            id = "turnin-479-ambermill-investigations",
            kind = "turnin",
            priority = 806,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Ambermill Investigations to Shadow Priest Allister.",
            complete = QuestState(479, "completed"),
            dependsOn = { "accept-479-ambermill-investigations", "objective-479-1-dalaran-pendant" },
            route = {
                Point(1421, 0.4398, 0.4093, "Shadow Priest Allister",
                    "Travel to Shadow Priest Allister."),
            },
        },
        {
            id = "objective-99-1-pyrewood-shackle",
            kind = "objective",
            priority = 807,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Collect 6 Pyrewood Shackles from Pyrewood villagers (or Moonrage forms at night).",
            complete = QuestObjective(99, 1, "Pyrewood Shackle"),
            dependsOn = { "accept-99-arugal-s-folly" },
            route = {
                Point(1421, 0.4697, 0.7246, "Pyrewood Village",
                    "Travel to Pyrewood Village."),
            },
        },
        {
            id = "turnin-99-arugal-s-folly",
            kind = "turnin",
            priority = 808,
            conditions = { all = {
                { level = { min = 13 } },
                { faction = "Horde" },
            } },
            text = "Turn in Arugal's Folly to Dalar Dawnweaver.",
            complete = QuestState(99, "completed"),
            dependsOn = { "accept-99-arugal-s-folly", "objective-99-1-pyrewood-shackle" },
            route = {
                Point(1421, 0.4419, 0.3978, "Dalar Dawnweaver",
                    "Travel to Dalar Dawnweaver."),
            },
        },
        {
            id = "woven-accept-95981-watching-the-roads",
            kind = "accept",
            priority = 810,
            conditions = { level = { min = 20 } },
            text = "Accept Watching the Roads from Shadow Priest Allister in the Sepulcher.",
            complete = QuestState(95981, "activeOrCompleted"),
            dependsOn = { "turnin-479-ambermill-investigations" },
            route = {
                Point(1421, 0.4400, 0.4100, "Shadow Priest Allister",
                    "Travel to Shadow Priest Allister."),
            },
        },
        {
            id = "woven-objective-95981-watching-the-roads",
            kind = "objective",
            priority = 820,
            conditions = { level = { min = 20 } },
            text = "Watching the Roads: slay 8 Dalaran Watchers and 8 Dalaran Wizards in Ambermill.",
            complete = QuestState(95981, "complete"),
            route = {
                Point(1421, 0.6040, 0.7460, "Dalaran Watcher",
                    "Travel to Dalaran Watcher."),
                Point(1421, 0.6320, 0.6520, "Dalaran Wizard",
                    "Travel to Dalaran Wizard."),
            },
        },
        {
            id = "woven-turnin-95981-watching-the-roads",
            kind = "turnin",
            priority = 830,
            conditions = { level = { min = 20 } },
            text = "Turn in Watching the Roads to Shadow Priest Allister in the Sepulcher.",
            complete = QuestState(95981, "completed"),
            route = {
                Point(1421, 0.4400, 0.4100, "Shadow Priest Allister",
                    "Travel to Shadow Priest Allister."),
            },
        },
        {
            id = "woven-accept-98298-arugals-folly",
            kind = "accept",
            priority = 840,
            conditions = { level = { min = 16 } },
            text = "Accept Arugal's Folly from Dalar Dawnweaver in the Sepulcher.",
            complete = QuestState(98298, "activeOrCompleted"),
            dependsOn = { "turnin-99-arugal-s-folly" },
            route = {
                Point(1421, 0.4420, 0.3980, "Dalar Dawnweaver",
                    "Travel to Dalar Dawnweaver."),
            },
        },
        {
            id = "woven-objective-98298-arugals-folly",
            kind = "objective",
            priority = 850,
            conditions = { level = { min = 16 } },
            text = "Arugal's Folly: bring 6 Worgen Bits from Moonrage Bloodhowlers.",
            complete = QuestState(98298, "complete"),
            route = {
                Point(1421, 0.5000, 0.7400, "Moonrage Bloodhowler",
                    "Travel to Moonrage Bloodhowler."),
            },
        },
        {
            id = "woven-turnin-98298-arugals-folly",
            kind = "turnin",
            priority = 860,
            conditions = { level = { min = 16 } },
            text = "Turn in Arugal's Folly to Dalar Dawnweaver in the Sepulcher.",
            complete = QuestState(98298, "completed"),
            route = {
                Point(1421, 0.4420, 0.3980, "Dalar Dawnweaver",
                    "Travel to Dalar Dawnweaver."),
            },
        },
        {
            id = "woven-accept-98299-stop-the-spread",
            kind = "accept",
            priority = 870,
            conditions = { level = { min = 20 } },
            text = "Accept Stop the Spread from Dalar Dawnweaver in the Sepulcher.",
            complete = QuestState(98299, "activeOrCompleted"),
            route = {
                Point(1421, 0.4420, 0.3980, "Dalar Dawnweaver",
                    "Travel to Dalar Dawnweaver."),
            },
        },
        {
            id = "woven-objective-98299-stop-the-spread",
            kind = "objective",
            priority = 880,
            conditions = { level = { min = 20 } },
            text = "Stop the Spread: slay 5 Sickly Refugees and 5 Haggard Refugees by the Greymane Wall.",
            complete = QuestState(98299, "complete"),
            route = {
                Point(1421, 0.4540, 0.8320, "Sickly Refugee",
                    "Travel to Sickly Refugee."),
                Point(1421, 0.4620, 0.8640, "Haggard Refugee",
                    "Travel to Haggard Refugee."),
            },
        },
        {
            id = "woven-turnin-98299-stop-the-spread",
            kind = "turnin",
            priority = 890,
            conditions = { level = { min = 20 } },
            text = "Turn in Stop the Spread to Dalar Dawnweaver in the Sepulcher.",
            complete = QuestState(98299, "completed"),
            route = {
                Point(1421, 0.4420, 0.3980, "Dalar Dawnweaver",
                    "Travel to Dalar Dawnweaver."),
            },
        },
    },
})
