local _, ns = ...

-- Alliance Era leveling route for Desolace, levels 34-35.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    DESOLACE = 1443,
    IRONFORGE = 1455,
    STONETALON = 1442,
    FERALAS = 1444,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-34-35-desolace",
    title = "34-35 Desolace (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Alliance" },
            { level = { min = 34 } },
        },
    },
    goals = {
        {
            id = "travel-1453-city-of-ironforge",
            kind = "travel",
            priority = 10,
            text = "Travel to City of Ironforge.",
            route = {
                Point(MAP.IRONFORGE, 0.6795, 0.1761, "City of Ironforge",
                    "Travel to City of Ironforge."),
            },
        },
        {
            id = "accept-1453-reclaimers-business-in-desolace",
            kind = "accept",
            priority = 20,
            text = "Accept Reclaimers' Business in Desolace from Roetten Stonehammer in Hall of Explorers.",
            complete = QuestState(1453, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.6795, 0.1761, "Roetten Stonehammer",
                    "Travel to Roetten Stonehammer."),
            },
        },
        {
            id = "accept-1179-the-brassbolts-brothers",
            kind = "accept",
            priority = 30,
            text = "Accept The Brassbolts Brothers from Pilot Longbeard in Hall of Arms.",
            complete = QuestState(1179, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.7270, 0.9397, "Pilot Longbeard",
                    "Travel to Pilot Longbeard."),
            },
        },
        {
            id = "travel-1437-desolace",
            kind = "travel",
            priority = 40,
            text = "Run South to Desolace.",
            route = {
                Point(MAP.STONETALON, 0.2700, 0.8590, "Desolace",
                    "Travel to Desolace."),
            },
        },
        {
            id = "travel-1437-nijel-s-point",
            kind = "travel",
            priority = 50,
            text = "Nijel's Point is along the northern edge of Desolace.",
            route = {
                Point(MAP.DESOLACE, 0.6400, 0.1000, "Nijel's Point",
                    "Travel to Nijel's Point."),
            },
        },
        {
            id = "accept-1382-strange-alliance",
            kind = "accept",
            priority = 60,
            text = "Accept Strange Alliance from Captain Pentigast in Nijel's Point.",
            complete = QuestState(1382, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6667, 0.1092, "Captain Pentigast",
                    "Travel to Captain Pentigast."),
            },
        },
        {
            id = "accept-1387-centaur-bounty",
            kind = "accept",
            priority = 70,
            text = "Accept Centaur Bounty from Corporal Melkins in Nijel's Point.",
            complete = QuestState(1387, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6674, 0.1090, "Corporal Melkins",
                    "Travel to Corporal Melkins."),
            },
        },
        {
            id = "accept-1437-vahlarriel-s-search",
            kind = "accept",
            priority = 80,
            text = "Accept Vahlarriel's Search from Vahlarriel Demonslayer in Nijel's Point.",
            complete = QuestState(1437, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6644, 0.1181, "Vahlarriel Demonslayer",
                    "Travel to Vahlarriel Demonslayer."),
            },
        },
        {
            id = "turnin-1453-reclaimers-business-in-desolace",
            kind = "turnin",
            priority = 90,
            text = "Turn in Reclaimers' Business in Desolace to Kreldig Ungor in Nijel's Point.",
            dependsOn = { "accept-1453-reclaimers-business-in-desolace" },
            complete = QuestState(1453, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6623, 0.0964, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "accept-1458-reagents-for-reclaimers-inc",
            kind = "accept",
            priority = 100,
            text = "Accept Reagents for Reclaimers Inc. from Kreldig Ungor in Nijel's Point.",
            complete = QuestState(1458, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6623, 0.0964, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "accept-1454-the-karnitol-shipwreck",
            kind = "accept",
            priority = 110,
            text = "Accept The Karnitol Shipwreck from Kreldig Ungor in Nijel's Point.",
            complete = QuestState(1454, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6623, 0.0964, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "note-1465-nijel-s-point",
            kind = "note",
            priority = 120,
            text = "Set your hearth in Nijel's Point with Innkeeper Lyshaerya.",
            route = {
                Point(MAP.DESOLACE, 0.6628, 0.0655, "Continue toward Nijel's Point",
                    "Continue toward Nijel's Point."),
                Point(MAP.DESOLACE, 0.6630, 0.0670, "Innkeeper Lyshaerya",
                    "Travel to Innkeeper Lyshaerya."),
            },
        },
        {
            id = "accept-261-down-the-scarlet-path",
            kind = "accept",
            priority = 130,
            text = "Accept Down the Scarlet Path from Brother Anton in Nijel's Point.",
            complete = QuestState(261, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6649, 0.0788, "Brother Anton",
                    "Travel to Brother Anton."),
            },
        },
        {
            id = "turnin-1437-vahlarriel-s-search",
            kind = "turnin",
            priority = 140,
            text = "Turn in Vahlarriel's Search in Desolace.",
            dependsOn = { "accept-1437-vahlarriel-s-search" },
            complete = QuestState(1437, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.5660, 0.1780, "Desolace",
                    "Travel to Desolace."),
            },
        },
        {
            id = "accept-1465-vahlarriel-s-search",
            kind = "accept",
            priority = 150,
            text = "Accept Vahlarriel's Search in Desolace.",
            complete = QuestState(1465, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.5660, 0.1780, "Desolace",
                    "Travel to Desolace."),
            },
        },
        {
            id = "travel-1458-sargeron",
            kind = "travel",
            priority = 160,
            text = "Travel to Sargeron.",
            route = {
                Point(MAP.DESOLACE, 0.7092, 0.1677, "Sargeron",
                    "Travel to Sargeron."),
            },
        },
        {
            id = "objective-1458-reagents-for-reclaimers-inc",
            kind = "objective",
            priority = 170,
            text = "Kill Hatefury satyrs and collect 10 Hatefury Claw and 10 Hatefury Horn in Sargeron.",
            dependsOn = { "accept-1458-reagents-for-reclaimers-inc" },
            complete = QuestState(1458, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.7092, 0.1677, "Hatefury Rogue",
                    "Travel to Hatefury Rogue."),
            },
        },
        {
            id = "travel-1438-nijel-s-point",
            kind = "travel",
            priority = 180,
            text = "Travel to Nijel's Point.",
            route = {
                Point(MAP.DESOLACE, 0.6750, 0.1553, "Nijel's Point",
                    "Travel to Nijel's Point."),
            },
        },
        {
            id = "turnin-1465-vahlarriel-s-search",
            kind = "turnin",
            priority = 190,
            text = "Turn in Vahlarriel's Search to Vahlarriel Demonslayer in Nijel's Point.",
            dependsOn = { "accept-1465-vahlarriel-s-search" },
            complete = QuestState(1465, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6644, 0.1181, "Vahlarriel Demonslayer",
                    "Travel to Vahlarriel Demonslayer."),
            },
        },
        {
            id = "accept-1438-vahlarriel-s-search",
            kind = "accept",
            priority = 200,
            text = "Accept Vahlarriel's Search from Vahlarriel Demonslayer in Nijel's Point.",
            complete = QuestState(1438, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6644, 0.1181, "Vahlarriel Demonslayer",
                    "Travel to Vahlarriel Demonslayer."),
            },
        },
        {
            id = "turnin-1458-reagents-for-reclaimers-inc",
            kind = "turnin",
            priority = 210,
            text = "Turn in Reagents for Reclaimers Inc. to Kreldig Ungor in Nijel's Point.",
            dependsOn = { "objective-1458-reagents-for-reclaimers-inc" },
            complete = QuestState(1458, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6623, 0.0964, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "accept-1459-reagents-for-reclaimers-inc",
            kind = "accept",
            priority = 220,
            text = "Accept Reagents for Reclaimers Inc. from Kreldig Ungor in Nijel's Point.",
            complete = QuestState(1459, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6623, 0.0964, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "accept-5501-bone-collector",
            kind = "accept",
            priority = 230,
            text = "Accept Bone Collector from Bibbly F'utzbuckle in Kormek's Hut.",
            complete = QuestState(5501, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6232, 0.3898, "Bibbly F'utzbuckle",
                    "Travel to Bibbly F'utzbuckle."),
            },
        },
        {
            id = "travel-1382-kolkar-village",
            kind = "travel",
            priority = 240,
            text = "Travel to Kolkar Village.",
            route = {
                Point(MAP.DESOLACE, 0.7200, 0.4500, "Kolkar Village",
                    "Travel to Kolkar Village."),
            },
        },
        {
            id = "objective-1387-centaur-bounty",
            kind = "objective",
            priority = 250,
            text = "Kill Kolkar centaurs to collect 15 Centaur Ear in Kolkar Village.",
            dependsOn = { "accept-1387-centaur-bounty" },
            complete = QuestState(1387, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.7200, 0.4500, "Magram Mauler",
                    "Travel to Magram Mauler."),
            },
        },
        {
            id = "objective-1382-strange-alliance",
            kind = "objective",
            priority = 260,
            text = "Keep killing Magram Centaurs until you reach Friendly reputation status with Gelkis in Magram Village You will need to kill around 40 Magram Centaurs.",
            dependsOn = { "accept-1382-strange-alliance" },
            complete = QuestState(1382, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.6983, 0.7713, "Magram Mauler",
                    "Travel to Magram Mauler."),
            },
        },
        {
            id = "travel-5561-scrabblescrew-s-camp",
            kind = "travel",
            priority = 270,
            text = "Travel to Scrabblescrew's Camp.",
            route = {
                Point(MAP.DESOLACE, 0.6089, 0.6189, "Scrabblescrew's Camp",
                    "Travel to Scrabblescrew's Camp."),
            },
        },
        {
            id = "accept-5561-kodo-roundup",
            kind = "accept",
            priority = 280,
            text = "Accept Kodo Roundup from Smeed Scrabblescrew in Scrabblescrew's Camp.",
            complete = QuestState(5561, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6089, 0.6189, "Smeed Scrabblescrew",
                    "Travel to Smeed Scrabblescrew."),
            },
        },
        {
            id = "objective-5561-kodo-roundup",
            kind = "objective",
            priority = 290,
            text = "Use the Kodo Kombobulator to tame 5 Ancient Kodo, Aged Kodo or Dying Kodo in the graveyard . Once tamed, you must bring it back to Scrabblescrew. Only one kodo can be tamed at a time.",
            dependsOn = { "accept-5561-kodo-roundup" },
            complete = QuestState(5561, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.5100, 0.5900, "Ancient Kodo",
                    "Travel to Ancient Kodo."),
            },
        },
        {
            id = "turnin-5561-kodo-roundup",
            kind = "turnin",
            priority = 300,
            text = "Turn in Kodo Roundup to Smeed Scrabblescrew in Scrabblescrew's Camp.",
            dependsOn = { "objective-5561-kodo-roundup" },
            complete = QuestState(5561, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6089, 0.6189, "Smeed Scrabblescrew",
                    "Travel to Smeed Scrabblescrew."),
            },
        },
        {
            id = "objective-1459-2-aged-kodo",
            kind = "objective",
            priority = 310,
            text = "Kill Aged Kodo and collect 3 Aged Kodo Hide in Desolace.",
            dependsOn = { "accept-1459-reagents-for-reclaimers-inc" },
            complete = QuestObjective(1459, 2),
            route = {
                Point(MAP.DESOLACE, 0.5837, 0.3452, "Continue toward Aged Kodo",
                    "Continue toward Aged Kodo."),
                Point(MAP.DESOLACE, 0.4940, 0.4020, "Continue toward Aged Kodo",
                    "Continue toward Aged Kodo."),
                Point(MAP.DESOLACE, 0.5050, 0.5660, "Aged Kodo",
                    "Travel to Aged Kodo."),
            },
        },
        {
            id = "travel-1459-2-kodo-graveyard",
            kind = "travel",
            priority = 320,
            text = "Travel to Kodo Graveyard.",
            complete = QuestObjective(1459, 2),
            route = {
                Point(MAP.DESOLACE, 0.5100, 0.5900, "Kodo Graveyard",
                    "Travel to Kodo Graveyard."),
            },
        },
        {
            id = "objective-5501-bone-collector",
            kind = "objective",
            priority = 330,
            text = "Collect 10 Kodo Bone lying around in Kodo Graveyard.",
            dependsOn = { "accept-5501-bone-collector" },
            complete = QuestState(5501, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.5100, 0.5900, "Kodo Graveyard",
                    "Travel to Kodo Graveyard."),
            },
        },
        {
            id = "turnin-5501-bone-collector",
            kind = "turnin",
            priority = 340,
            text = "Turn in Bone Collector to Bibbly F'utzbuckle in Kormek's Hut.",
            dependsOn = { "objective-5501-bone-collector" },
            complete = QuestState(5501, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6232, 0.3898, "Bibbly F'utzbuckle",
                    "Travel to Bibbly F'utzbuckle."),
            },
        },
        {
            id = "travel-1384-gelkis-village",
            kind = "travel",
            priority = 350,
            text = "Travel to Gelkis Village.",
            route = {
                Point(MAP.DESOLACE, 0.3619, 0.7928, "Gelkis Village",
                    "Travel to Gelkis Village."),
            },
        },
        {
            id = "turnin-1382-strange-alliance",
            kind = "turnin",
            priority = 360,
            text = "Turn in Strange Alliance to Uthek the Wise in Gelkis Village.",
            dependsOn = { "objective-1382-strange-alliance" },
            complete = QuestState(1382, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.3619, 0.7928, "Uthek the Wise",
                    "Travel to Uthek the Wise."),
            },
        },
        {
            id = "accept-1384-raid-on-the-kolkar",
            kind = "accept",
            priority = 370,
            text = "Accept Raid on the Kolkar from Uthek the Wise in Gelkis Village.",
            complete = QuestState(1384, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.3619, 0.7928, "Uthek the Wise",
                    "Travel to Uthek the Wise."),
            },
        },
        {
            id = "travel-6161-ethel-rethor",
            kind = "travel",
            priority = 380,
            text = "Travel to Ethel Rethor.",
            route = {
                Point(MAP.DESOLACE, 0.3611, 0.3044, "Ethel Rethor",
                    "Travel to Ethel Rethor."),
            },
        },
        {
            id = "turnin-1454-the-karnitol-shipwreck",
            kind = "turnin",
            priority = 390,
            text = "Turn in The Karnitol Shipwreck in Ethel Rethor.",
            dependsOn = { "accept-1454-the-karnitol-shipwreck" },
            complete = QuestState(1454, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.3611, 0.3044, "Ethel Rethor",
                    "Travel to Ethel Rethor."),
            },
        },
        {
            id = "accept-1455-the-karnitol-shipwreck",
            kind = "accept",
            priority = 400,
            text = "Accept The Karnitol Shipwreck in Ethel Rethor.",
            complete = QuestState(1455, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.3611, 0.3044, "Ethel Rethor",
                    "Travel to Ethel Rethor."),
            },
        },
        {
            id = "accept-6161-claim-rackmore-s-treasure",
            kind = "accept",
            priority = 410,
            text = "Accept Claim Rackmore's Treasure! in Ethel Rethor.",
            complete = QuestState(6161, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.3611, 0.3044, "Ethel Rethor",
                    "Travel to Ethel Rethor."),
            },
        },
        {
            id = "objective-6161-1-drysnap-pincer",
            kind = "objective",
            priority = 420,
            text = "Kill Drysnaps until you find Rackmore's Silver Key in Sar'theris Strand.",
            dependsOn = { "accept-6161-claim-rackmore-s-treasure" },
            complete = QuestObjective(6161, 1),
            route = {
                Point(MAP.DESOLACE, 0.3370, 0.2900, "Drysnap Pincer",
                    "Travel to Drysnap Pincer."),
            },
        },
        {
            id = "travel-5741-ethel-rethor",
            kind = "travel",
            priority = 430,
            text = "Travel to Ethel Rethor.",
            route = {
                Point(MAP.DESOLACE, 0.3889, 0.2717, "Ethel Rethor",
                    "Travel to Ethel Rethor."),
            },
        },
        {
            id = "accept-5741-sceptre-of-light",
            kind = "accept",
            priority = 440,
            text = "Accept Sceptre of Light from Azore Aldamort in Ethel Rethor.",
            complete = QuestState(5741, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.4107, 0.2895, "Continue toward Sceptre of Light",
                    "Continue toward Sceptre of Light."),
                Point(MAP.DESOLACE, 0.3889, 0.2717, "Azore Aldamort",
                    "Travel to Azore Aldamort."),
            },
        },
        {
            id = "travel-1439-thunder-axe-fortress",
            kind = "travel",
            priority = 450,
            text = "Travel to Thunder Axe Fortress.",
            route = {
                Point(MAP.DESOLACE, 0.5487, 0.2619, "Thunder Axe Fortress",
                    "Travel to Thunder Axe Fortress."),
            },
        },
        {
            id = "turnin-1438-vahlarriel-s-search",
            kind = "turnin",
            priority = 460,
            text = "Turn in Vahlarriel's Search to Dalinda Malem in Thunder Axe Fortress.",
            dependsOn = { "accept-1438-vahlarriel-s-search" },
            complete = QuestState(1438, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.5487, 0.2619, "Dalinda Malem",
                    "Travel to Dalinda Malem."),
            },
        },
        {
            id = "accept-1439-search-for-tyranis",
            kind = "accept",
            priority = 470,
            text = "Accept Search for Tyranis from Dalinda Malem in Thunder Axe Fortress.",
            complete = QuestState(1439, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.5487, 0.2619, "Dalinda Malem",
                    "Travel to Dalinda Malem."),
            },
        },
        {
            id = "objective-5741-sceptre-of-light",
            kind = "objective",
            priority = 480,
            text = "Kill the Burning Blade Seer at the top of the watch tower to collect the Sceptre of Light in Thunder Axe Fortress.",
            dependsOn = { "accept-5741-sceptre-of-light" },
            complete = QuestState(5741, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.5523, 0.3013, "Burning Blade Seer",
                    "Travel to Burning Blade Seer."),
            },
        },
        {
            id = "objective-1439-search-for-tyranis",
            kind = "objective",
            priority = 490,
            text = "Kill Tyranis Malem inside a small building to collect Tyranis' Pendant in Thunder Axe Fortress.",
            dependsOn = { "accept-1439-search-for-tyranis" },
            complete = QuestState(1439, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.5300, 0.2900, "Tyranis Malem",
                    "Travel to Tyranis Malem."),
            },
        },
        {
            id = "turnin-1439-search-for-tyranis",
            kind = "turnin",
            priority = 500,
            text = "Turn in Search for Tyranis to Dalinda Malem in Thunder Axe Fortress.",
            dependsOn = { "objective-1439-search-for-tyranis" },
            complete = QuestState(1439, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.5487, 0.2619, "Dalinda Malem",
                    "Travel to Dalinda Malem."),
            },
        },
        {
            id = "accept-1440-return-to-vahlarriel",
            kind = "accept",
            priority = 510,
            text = "Accept Return to Vahlarriel from Dalinda Malem in Thunder Axe Fortress.",
            complete = QuestState(1440, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.5487, 0.2619, "Dalinda Malem",
                    "Travel to Dalinda Malem."),
            },
        },
        {
            id = "objective-1440-return-to-vahlarriel",
            kind = "objective",
            priority = 520,
            text = "Escort Dalinda Malem. She may ignore mobs, so don't attack anything unless she attacks or is attacked.",
            dependsOn = { "accept-1440-return-to-vahlarriel" },
            complete = QuestState(1440, "complete"),
        },
        {
            id = "travel-nijel-s-point",
            kind = "travel",
            priority = 530,
            text = "Travel to Nijel's Point.",
            route = {
                Point(MAP.DESOLACE, 0.6620, 0.0964, "Nijel's Point",
                    "Travel to Nijel's Point."),
            },
        },
        {
            id = "turnin-1455-the-karnitol-shipwreck",
            kind = "turnin",
            priority = 540,
            text = "Turn in The Karnitol Shipwreck to Kreldig Ungor in Nijel's Point.",
            dependsOn = { "accept-1455-the-karnitol-shipwreck" },
            complete = QuestState(1455, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6620, 0.0964, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "accept-1456-the-karnitol-shipwreck",
            kind = "accept",
            priority = 550,
            text = "Accept The Karnitol Shipwreck from Kreldig Ungor in Nijel's Point.",
            complete = QuestState(1456, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6620, 0.0964, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "turnin-1440-return-to-vahlarriel",
            kind = "turnin",
            priority = 560,
            text = "Turn in Return to Vahlarriel to Vahlarriel Demonslayer in Nijel's Point.",
            dependsOn = { "objective-1440-return-to-vahlarriel" },
            complete = QuestState(1440, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6644, 0.1181, "Vahlarriel Demonslayer",
                    "Travel to Vahlarriel Demonslayer."),
            },
        },
        {
            id = "travel-6027-ethel-rethor",
            kind = "travel",
            priority = 570,
            text = "Travel to Ethel Rethor.",
            route = {
                Point(MAP.DESOLACE, 0.5676, 0.3113, "Continue toward Ethel Rethor",
                    "Continue toward Ethel Rethor."),
                Point(MAP.DESOLACE, 0.4105, 0.2894, "Continue toward Ethel Rethor",
                    "Continue toward Ethel Rethor."),
                Point(MAP.DESOLACE, 0.4107, 0.2895, "Ethel Rethor",
                    "Travel to Ethel Rethor."),
            },
        },
        {
            id = "turnin-5741-sceptre-of-light",
            kind = "turnin",
            priority = 580,
            text = "Turn in Sceptre of Light to Azore Aldamort in Ethel Rethor.",
            dependsOn = { "objective-5741-sceptre-of-light" },
            complete = QuestState(5741, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.4107, 0.2895, "Continue toward Sceptre of Light",
                    "Continue toward Sceptre of Light."),
                Point(MAP.DESOLACE, 0.3889, 0.2717, "Azore Aldamort",
                    "Travel to Azore Aldamort."),
            },
        },
        {
            id = "accept-6027-book-of-the-ancients",
            kind = "accept",
            priority = 590,
            text = "Accept Book of the Ancients from Azore Aldamort in Ethel Rethor.",
            complete = QuestState(6027, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.3889, 0.2717, "Azore Aldamort",
                    "Travel to Azore Aldamort."),
            },
        },
        {
            id = "travel-6027-ranazjar-isle",
            kind = "travel",
            priority = 600,
            text = "Travel to Ranazjar Isle.",
            route = {
                Point(MAP.DESOLACE, 0.3002, 0.0869, "Ranazjar Isle",
                    "Travel to Ranazjar Isle."),
            },
        },
        {
            id = "objective-6027-book-of-the-ancients",
            kind = "objective",
            priority = 610,
            text = "Clear the area around the statue then click on the statue. Kill Lord Kragaru when he spawns to collect Book of the Ancients.",
            dependsOn = { "accept-6027-book-of-the-ancients" },
            complete = QuestState(6027, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.2800, 0.0700, "Lord Kragaru",
                    "Travel to Lord Kragaru."),
            },
        },
        {
            id = "objective-6161-2-rackmore-s-golden-key",
            kind = "objective",
            priority = 620,
            text = "Kill Slitherblade enemies until you find Rackmore's Golden Key in Sar'theris Strand.",
            dependsOn = { "accept-6161-claim-rackmore-s-treasure" },
            complete = QuestObjective(6161, 2),
            route = {
                Point(MAP.DESOLACE, 0.3286, 0.2312, "Slitherblade Warrior",
                    "Travel to Slitherblade Warrior."),
            },
        },
        {
            id = "objective-1456-the-karnitol-shipwreck",
            kind = "objective",
            priority = 630,
            text = "Kill Slitherblade Tidehunter or Slitherblade Sea Witch until you find Karnitol's Satchel in Ranazjar Isle.",
            dependsOn = { "accept-1456-the-karnitol-shipwreck" },
            complete = QuestState(1456, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.2760, 0.0895, "Slitherblade Tidehunter",
                    "Travel to Slitherblade Tidehunter."),
            },
        },
        {
            id = "turnin-6161-claim-rackmore-s-treasure",
            kind = "turnin",
            priority = 640,
            text = "Turn in Claim Rackmore's Treasure! in Ranazjar Isle.",
            dependsOn = { "objective-6161-1-drysnap-pincer", "objective-6161-2-rackmore-s-golden-key" },
            complete = QuestState(6161, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.3002, 0.0869, "Ranazjar Isle",
                    "Travel to Ranazjar Isle."),
            },
        },
        {
            id = "travel-6027-ethel-rethor-2",
            kind = "travel",
            priority = 650,
            text = "Travel to Ethel Rethor.",
            route = {
                Point(MAP.DESOLACE, 0.4107, 0.2895, "Ethel Rethor",
                    "Travel to Ethel Rethor."),
            },
        },
        {
            id = "turnin-6027-book-of-the-ancients",
            kind = "turnin",
            priority = 660,
            text = "Turn in Book of the Ancients to Azore Aldamort in Ethel Rethor.",
            dependsOn = { "objective-6027-book-of-the-ancients" },
            complete = QuestState(6027, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.4107, 0.2895, "Continue toward Book of the Ancients",
                    "Continue toward Book of the Ancients."),
                Point(MAP.DESOLACE, 0.3889, 0.2717, "Azore Aldamort",
                    "Travel to Azore Aldamort."),
            },
        },
        {
            id = "objective-1459-reagents-for-reclaimers-inc",
            kind = "objective",
            priority = 670,
            text = "Finish collecting 7 Scorpashi Venom and 3 Aged Kodo Hide from Scorpashi creatures if you haven't already got them.",
            dependsOn = { "accept-1459-reagents-for-reclaimers-inc" },
            complete = QuestState(1459, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.6980, 0.2570, "Continue toward Reagents for Reclaimers Inc.",
                    "Continue toward Reagents for Reclaimers Inc.."),
                Point(MAP.DESOLACE, 0.7350, 0.3010, "Scorpashi Snapper",
                    "Travel to Scorpashi Snapper."),
            },
        },
        {
            id = "objective-1384-raid-on-the-kolkar",
            kind = "objective",
            priority = 680,
            text = "Collect 10 (tem:6079) from Kolkars in Kolkar Village.",
            dependsOn = { "accept-1384-raid-on-the-kolkar" },
            complete = QuestState(1384, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.7167, 0.4156, "Magram Mauler",
                    "Travel to Magram Mauler."),
            },
        },
        {
            id = "travel-nijel-s-point-2",
            kind = "travel",
            priority = 690,
            text = "Travel or Hearthstone to Nijel's Point.",
            route = {
                Point(MAP.DESOLACE, 0.6620, 0.0964, "Nijel's Point",
                    "Travel to Nijel's Point."),
            },
        },
        {
            id = "turnin-1387-centaur-bounty",
            kind = "turnin",
            priority = 700,
            text = "Turn in Centaur Bounty to Corporal Melkins in Nijel's Point.",
            dependsOn = { "objective-1387-centaur-bounty" },
            complete = QuestState(1387, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6674, 0.1090, "Corporal Melkins",
                    "Travel to Corporal Melkins."),
            },
        },
        {
            id = "turnin-1459-reagents-for-reclaimers-inc",
            kind = "turnin",
            priority = 710,
            text = "Turn in Reagents for Reclaimers Inc. to Kreldig Ungor in Nijel's Point.",
            dependsOn = { "objective-1459-2-aged-kodo", "objective-1459-reagents-for-reclaimers-inc" },
            complete = QuestState(1459, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6620, 0.0964, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "turnin-1456-the-karnitol-shipwreck",
            kind = "turnin",
            priority = 720,
            text = "Turn in The Karnitol Shipwreck to Kreldig Ungor in Nijel's Point.",
            dependsOn = { "objective-1456-the-karnitol-shipwreck" },
            complete = QuestState(1456, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.6619, 0.0962, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "accept-1457-the-karnitol-shipwreck",
            kind = "accept",
            priority = 730,
            text = "Accept The Karnitol Shipwreck from Kreldig Ungor in Nijel's Point.",
            complete = QuestState(1457, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.6619, 0.0962, "Kreldig Ungor",
                    "Travel to Kreldig Ungor."),
            },
        },
        {
            id = "travel-1370-gelkis-village",
            kind = "travel",
            priority = 740,
            text = "Travel to Gelkis Village.",
            route = {
                Point(MAP.DESOLACE, 0.3628, 0.7926, "Gelkis Village",
                    "Travel to Gelkis Village."),
            },
        },
        {
            id = "turnin-1384-raid-on-the-kolkar",
            kind = "turnin",
            priority = 750,
            text = "Turn in Raid on the Kolkar to Uthek the Wise in Gelkis Village.",
            dependsOn = { "objective-1384-raid-on-the-kolkar" },
            complete = QuestState(1384, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.3628, 0.7926, "Uthek the Wise",
                    "Travel to Uthek the Wise."),
            },
        },
        {
            id = "accept-1370-stealing-supplies",
            kind = "accept",
            priority = 760,
            text = "Accept Stealing Supplies from Uthek the Wise in Gelkis Village.",
            complete = QuestState(1370, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.3628, 0.7926, "Uthek the Wise",
                    "Travel to Uthek the Wise."),
            },
        },
        {
            id = "travel-1370-magram-village",
            kind = "travel",
            priority = 770,
            text = "Travel to Magram Village.",
            route = {
                Point(MAP.DESOLACE, 0.4861, 0.7582, "Continue toward Magram Village",
                    "Continue toward Magram Village."),
                Point(MAP.DESOLACE, 0.7361, 0.7435, "Magram Village",
                    "Travel to Magram Village."),
            },
        },
        {
            id = "objective-1370-stealing-supplies",
            kind = "objective",
            priority = 780,
            text = "Click on the Sack of Meat on the ground to collect Crudely Dried Meat in Magram Village.",
            dependsOn = { "accept-1370-stealing-supplies" },
            complete = QuestState(1370, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.7361, 0.7435, "Magram Village",
                    "Travel to Magram Village."),
            },
        },
        {
            id = "turnin-1370-stealing-supplies",
            kind = "turnin",
            priority = 790,
            text = "Turn in Stealing Supplies to Uthek the Wise in Gelkis Village.",
            dependsOn = { "objective-1370-stealing-supplies" },
            complete = QuestState(1370, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.3621, 0.7924, "Uthek the Wise",
                    "Travel to Uthek the Wise."),
            },
        },
        {
            id = "accept-1373-ongeku",
            kind = "accept",
            priority = 800,
            text = "Accept Ongeku from Uthek the Wise in Gelkis Village.",
            complete = QuestState(1373, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.3621, 0.7924, "Uthek the Wise",
                    "Travel to Uthek the Wise."),
            },
        },
        {
            id = "travel-feathermoon-stronghold",
            kind = "travel",
            priority = 810,
            text = "Travel to Feathermoon Stronghold.",
            route = {
                Point(MAP.DESOLACE, 0.4086, 0.9019, "Continue toward Feathermoon Stronghold",
                    "Continue toward Feathermoon Stronghold."),
                Point(MAP.DESOLACE, 0.4174, 0.9544, "Feathermoon Stronghold",
                    "Travel to Feathermoon Stronghold."),
            },
        },
        {
            id = "travel-feathermoon-stronghold-2",
            kind = "travel",
            priority = 820,
            text = "Travel to Feathermoon Stronghold. Take the boat if it is there, or swim if it just left.",
            route = {
                Point(MAP.FERALAS, 0.4640, 0.1495, "Continue toward Feathermoon Stronghold",
                    "Continue toward Feathermoon Stronghold."),
                Point(MAP.FERALAS, 0.4820, 0.2325, "Continue toward Feathermoon Stronghold",
                    "Continue toward Feathermoon Stronghold."),
                Point(MAP.FERALAS, 0.4696, 0.2830, "Continue toward Feathermoon Stronghold",
                    "Continue toward Feathermoon Stronghold."),
                Point(MAP.FERALAS, 0.4788, 0.3700, "Continue toward Feathermoon Stronghold",
                    "Continue toward Feathermoon Stronghold."),
                Point(MAP.FERALAS, 0.4483, 0.4235, "Continue toward Feathermoon Stronghold",
                    "Continue toward Feathermoon Stronghold."),
                Point(MAP.FERALAS, 0.3024, 0.4325, "Feathermoon Stronghold",
                    "Travel to Feathermoon Stronghold."),
            },
        },
    },
})
