local _, ns = ...

-- Alliance Era leveling route for Feralas, levels 44-46.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    FERALAS = 1444,
    DARNASSUS = 1457,
    TELDRASSIL = 1438,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-44-46-feralas",
    title = "44-46 Feralas (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Alliance" },
            { level = { min = 44 } },
        },
    },
    goals = {
        {
            id = "travel-2821-feathermoon-stronghold",
            kind = "travel",
            priority = 10,
            text = "Travel to Feathermoon Stronghold.",
            route = {
                Point(MAP.FERALAS, 0.3063, 0.4272, "Feathermoon Stronghold",
                    "Travel to Feathermoon Stronghold."),
            },
        },
        {
            id = "accept-2821-the-mark-of-quality",
            kind = "accept",
            priority = 20,
            text = "Accept The Mark of Quality from Pratt McGrubben in Feathermoon Stronghold.",
            complete = QuestState(2821, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3063, 0.4272, "Pratt McGrubben",
                    "Travel to Pratt McGrubben."),
            },
        },
        {
            id = "note-2821-feathermoon-stronghold",
            kind = "note",
            priority = 30,
            text = "Set your hearth in Feathermoon Stronghold with Innkeeper Shyria.",
            route = {
                Point(MAP.FERALAS, 0.3097, 0.4350, "Innkeeper Shyria",
                    "Travel to Innkeeper Shyria."),
            },
        },
        {
            id = "accept-2982-the-high-wilderness",
            kind = "accept",
            priority = 40,
            text = "Accept The High Wilderness from Angelas Moonbreeze in Feathermoon Stronghold.",
            complete = QuestState(2982, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3181, 0.4552, "Angelas Moonbreeze",
                    "Travel to Angelas Moonbreeze."),
            },
        },
        {
            id = "accept-2939-in-search-of-knowledge",
            kind = "accept",
            priority = 50,
            text = "Accept In Search of Knowledge from Troyas Moonbreeze in Feathermoon Stronghold.",
            complete = QuestState(2939, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3183, 0.4526, "Troyas Moonbreeze",
                    "Travel to Troyas Moonbreeze."),
            },
        },
        {
            id = "accept-4124-the-missing-courier",
            kind = "accept",
            priority = 60,
            text = "Accept The Missing Courier from Latronicus Moonspear in Feathermoon Stronghold.",
            complete = QuestState(4124, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3028, 0.4621, "Latronicus Moonspear",
                    "Travel to Latronicus Moonspear."),
            },
        },
        {
            id = "accept-2866-the-ruins-of-solarsal",
            kind = "accept",
            priority = 70,
            text = "Accept The Ruins of Solarsal from Shandris Feathermoon in Feathermoon Stronghold.",
            complete = QuestState(2866, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3028, 0.4616, "Shandris Feathermoon",
                    "Travel to Shandris Feathermoon."),
            },
        },
        {
            id = "turnin-4124-the-missing-courier",
            kind = "turnin",
            priority = 80,
            text = "Turn in The Missing Courier to Ginro Hearthkindle in Feathermoon Stronghold.",
            dependsOn = { "accept-4124-the-missing-courier" },
            complete = QuestState(4124, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3186, 0.4514, "Ginro Hearthkindle",
                    "Travel to Ginro Hearthkindle."),
            },
        },
        {
            id = "accept-4125-the-missing-courier",
            kind = "accept",
            priority = 90,
            text = "Accept The Missing Courier from Ginro Hearthkindle in Feathermoon Stronghold.",
            complete = QuestState(4125, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3186, 0.4514, "Ginro Hearthkindle",
                    "Travel to Ginro Hearthkindle."),
            },
        },
        {
            id = "travel-2867-ruins-of-solarsal",
            kind = "travel",
            priority = 100,
            text = "Travel to Ruins of Solarsal.",
            route = {
                Point(MAP.FERALAS, 0.2640, 0.5220, "Ruins of Solarsal",
                    "Travel to Ruins of Solarsal."),
            },
        },
        {
            id = "turnin-2866-the-ruins-of-solarsal",
            kind = "turnin",
            priority = 110,
            text = "Turn in The Ruins of Solarsal in Ruins of Solarsal.",
            dependsOn = { "accept-2866-the-ruins-of-solarsal" },
            complete = QuestState(2866, "completed"),
            route = {
                Point(MAP.FERALAS, 0.2640, 0.5220, "Ruins of Solarsal",
                    "Travel to Ruins of Solarsal."),
            },
        },
        {
            id = "accept-2867-return-to-feathermoon-stronghold",
            kind = "accept",
            priority = 120,
            text = "Accept Return to Feathermoon Stronghold in Ruins of Solarsal.",
            complete = QuestState(2867, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.2640, 0.5220, "Ruins of Solarsal",
                    "Travel to Ruins of Solarsal."),
            },
        },
        {
            id = "travel-3130-feathermoon-stronghold",
            kind = "travel",
            priority = 130,
            text = "Travel to Feathermoon Stronghold.",
            route = {
                Point(MAP.FERALAS, 0.3027, 0.4616, "Feathermoon Stronghold",
                    "Travel to Feathermoon Stronghold."),
            },
        },
        {
            id = "turnin-2867-return-to-feathermoon-stronghold",
            kind = "turnin",
            priority = 140,
            text = "Turn in Return to Feathermoon Stronghold to Shandris Feathermoon in Feathermoon Stronghold.",
            dependsOn = { "accept-2867-return-to-feathermoon-stronghold" },
            complete = QuestState(2867, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3027, 0.4616, "Shandris Feathermoon",
                    "Travel to Shandris Feathermoon."),
            },
        },
        {
            id = "accept-3130-against-the-hatecrest",
            kind = "accept",
            priority = 150,
            text = "Accept Against the Hatecrest from Shandris Feathermoon in Feathermoon Stronghold.",
            complete = QuestState(3130, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3027, 0.4616, "Shandris Feathermoon",
                    "Travel to Shandris Feathermoon."),
            },
        },
        {
            id = "turnin-3130-against-the-hatecrest",
            kind = "turnin",
            priority = 160,
            text = "Turn in Against the Hatecrest to Latronicus Moonspear in Feathermoon Stronghold.",
            dependsOn = { "accept-3130-against-the-hatecrest" },
            complete = QuestState(3130, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3038, 0.4617, "Latronicus Moonspear",
                    "Travel to Latronicus Moonspear."),
            },
        },
        {
            id = "accept-2869-against-the-hatecrest",
            kind = "accept",
            priority = 170,
            text = "Accept Against the Hatecrest from Latronicus Moonspear in Feathermoon Stronghold.",
            complete = QuestState(2869, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3038, 0.4617, "Latronicus Moonspear",
                    "Travel to Latronicus Moonspear."),
            },
        },
        {
            id = "objective-2869-against-the-hatecrest",
            kind = "objective",
            priority = 180,
            text = "Kill Nagas and collect 10 Hatecrest Naga Scale in Ruins of Solarsal.",
            dependsOn = { "accept-2869-against-the-hatecrest" },
            complete = QuestState(2869, "complete"),
            route = {
                Point(MAP.FERALAS, 0.2888, 0.5097, "Hatecrest Warrior",
                    "Travel to Hatecrest Warrior."),
            },
        },
        {
            id = "turnin-2869-against-the-hatecrest",
            kind = "turnin",
            priority = 190,
            text = "Turn in Against the Hatecrest to Latronicus Moonspear in Feathermoon Stronghold.",
            dependsOn = { "objective-2869-against-the-hatecrest" },
            complete = QuestState(2869, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3039, 0.4617, "Latronicus Moonspear",
                    "Travel to Latronicus Moonspear."),
            },
        },
        {
            id = "accept-2870-against-lord-shalzaru",
            kind = "accept",
            priority = 200,
            text = "Accept Against Lord Shalzaru from Latronicus Moonspear in Feathermoon Stronghold.",
            complete = QuestState(2870, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3039, 0.4617, "Latronicus Moonspear",
                    "Travel to Latronicus Moonspear."),
            },
        },
        {
            id = "travel-2870-shalzaru-s-lair",
            kind = "travel",
            priority = 210,
            text = "Travel to Shalzaru's Lair.",
            route = {
                Point(MAP.FERALAS, 0.2590, 0.6713, "Shalzaru's Lair",
                    "Travel to Shalzaru's Lair."),
            },
        },
        {
            id = "objective-2870-against-lord-shalzaru",
            kind = "objective",
            priority = 220,
            text = "Kill Lord Shalzaru and collect Mysterious Relic in Shalzaru's Lair.",
            dependsOn = { "accept-2870-against-lord-shalzaru" },
            complete = QuestState(2870, "complete"),
            route = {
                Point(MAP.FERALAS, 0.2740, 0.6976, "Continue toward Against Lord Shalzaru",
                    "Continue toward Against Lord Shalzaru."),
                Point(MAP.FERALAS, 0.2847, 0.7044, "Lord Shalzaru",
                    "Travel to Lord Shalzaru."),
            },
        },
        {
            id = "travel-2871-feathermoon-stronghold",
            kind = "travel",
            priority = 230,
            text = "Travel or Hearthstone to Feathermoon Stronghold, or die and ressurect.",
            route = {
                Point(MAP.FERALAS, 0.2590, 0.6713, "Continue toward Feathermoon Stronghold",
                    "Continue toward Feathermoon Stronghold."),
                Point(MAP.FERALAS, 0.3039, 0.4618, "Feathermoon Stronghold",
                    "Travel to Feathermoon Stronghold."),
            },
        },
        {
            id = "turnin-2870-against-lord-shalzaru",
            kind = "turnin",
            priority = 240,
            text = "Turn in Against Lord Shalzaru to Latronicus Moonspear in Feathermoon Stronghold.",
            dependsOn = { "objective-2870-against-lord-shalzaru" },
            complete = QuestState(2870, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3039, 0.4618, "Latronicus Moonspear",
                    "Travel to Latronicus Moonspear."),
            },
        },
        {
            id = "accept-2871-delivering-the-relic",
            kind = "accept",
            priority = 250,
            text = "Accept Delivering the Relic from Latronicus Moonspear in Feathermoon Stronghold.",
            complete = QuestState(2871, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3039, 0.4618, "Latronicus Moonspear",
                    "Travel to Latronicus Moonspear."),
            },
        },
        {
            id = "turnin-2871-delivering-the-relic",
            kind = "turnin",
            priority = 260,
            text = "Turn in Delivering the Relic to Vestia Moonspear in Feathermoon Stronghold.",
            dependsOn = { "accept-2871-delivering-the-relic" },
            complete = QuestState(2871, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3008, 0.4507, "Vestia Moonspear",
                    "Travel to Vestia Moonspear."),
            },
        },
        {
            id = "travel-3520-the-forgotten-coast",
            kind = "travel",
            priority = 270,
            text = "Travel to The Forgotten Coast.",
            route = {
                Point(MAP.FERALAS, 0.4400, 0.3637, "The Forgotten Coast",
                    "Travel to The Forgotten Coast."),
            },
        },
        {
            id = "objective-3520-screecher-spirits",
            kind = "objective",
            priority = 280,
            text = "Kill Rogue Vale Screecher and use Yeh'kinya's Bramble, then interact with the spirit in The Forgotten Coast.",
            complete = QuestState(3520, "complete"),
            route = {
                Point(MAP.FERALAS, 0.4632, 0.4978, "Continue toward Screecher Spirits",
                    "Continue toward Screecher Spirits."),
                Point(MAP.FERALAS, 0.4643, 0.4908, "Rogue Vale Screecher",
                    "Travel to Rogue Vale Screecher."),
            },
        },
        {
            id = "turnin-4125-the-missing-courier",
            kind = "turnin",
            priority = 290,
            text = "Turn in The Missing Courier in The Forgotten Coast.",
            dependsOn = { "accept-4125-the-missing-courier" },
            complete = QuestState(4125, "completed"),
            route = {
                Point(MAP.FERALAS, 0.4547, 0.6503, "The Forgotten Coast",
                    "Travel to The Forgotten Coast."),
            },
        },
        {
            id = "accept-4127-boat-wreckage",
            kind = "accept",
            priority = 300,
            text = "Accept Boat Wreckage in The Forgotten Coast.",
            complete = QuestState(4127, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.4547, 0.6503, "The Forgotten Coast",
                    "Travel to The Forgotten Coast."),
            },
        },
        {
            id = "turnin-4127-boat-wreckage",
            kind = "turnin",
            priority = 310,
            text = "Turn in Boat Wreckage to Ginro Hearthkindle in Feathermoon Stronghold.",
            dependsOn = { "accept-4127-boat-wreckage" },
            complete = QuestState(4127, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3187, 0.4515, "Ginro Hearthkindle",
                    "Travel to Ginro Hearthkindle."),
            },
        },
        {
            id = "accept-4129-the-knife-revealed",
            kind = "accept",
            priority = 320,
            text = "Accept The Knife Revealed from Ginro Hearthkindle in Feathermoon Stronghold.",
            complete = QuestState(4129, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3187, 0.4515, "Ginro Hearthkindle",
                    "Travel to Ginro Hearthkindle."),
            },
        },
        {
            id = "turnin-4129-the-knife-revealed",
            kind = "turnin",
            priority = 330,
            text = "Turn in The Knife Revealed to Quintis Jonespyre in Feathermoon Stronghold.",
            dependsOn = { "accept-4129-the-knife-revealed" },
            complete = QuestState(4129, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3246, 0.4381, "Quintis Jonespyre",
                    "Travel to Quintis Jonespyre."),
            },
        },
        {
            id = "accept-4130-psychometric-reading",
            kind = "accept",
            priority = 340,
            text = "Accept Psychometric Reading from Quintis Jonespyre in Feathermoon Stronghold.",
            complete = QuestState(4130, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3246, 0.4381, "Quintis Jonespyre",
                    "Travel to Quintis Jonespyre."),
            },
        },
        {
            id = "turnin-4130-psychometric-reading",
            kind = "turnin",
            priority = 350,
            text = "Turn in Psychometric Reading to Ginro Hearthkindle in Feathermoon Stronghold.",
            dependsOn = { "accept-4130-psychometric-reading" },
            complete = QuestState(4130, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3188, 0.4512, "Ginro Hearthkindle",
                    "Travel to Ginro Hearthkindle."),
            },
        },
        {
            id = "accept-4131-the-woodpaw-gnolls",
            kind = "accept",
            priority = 360,
            text = "Accept The Woodpaw Gnolls from Ginro Hearthkindle in Feathermoon Stronghold.",
            complete = QuestState(4131, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3188, 0.4512, "Ginro Hearthkindle",
                    "Travel to Ginro Hearthkindle."),
            },
        },
        {
            id = "travel-2821-feral-scar-vale",
            kind = "travel",
            priority = 370,
            text = "Travel to Feral Scar Vale.",
            route = {
                Point(MAP.FERALAS, 0.4721, 0.4463, "Continue toward Feral Scar Vale",
                    "Continue toward Feral Scar Vale."),
                Point(MAP.FERALAS, 0.4882, 0.4562, "Continue toward Feral Scar Vale",
                    "Continue toward Feral Scar Vale."),
                Point(MAP.FERALAS, 0.5471, 0.5276, "Continue toward Feral Scar Vale",
                    "Continue toward Feral Scar Vale."),
                Point(MAP.FERALAS, 0.5554, 0.5712, "Feral Scar Vale",
                    "Travel to Feral Scar Vale."),
            },
        },
        {
            id = "objective-2821-the-mark-of-quality",
            kind = "objective",
            priority = 380,
            text = "Kill Feral Scar Yeti and collect 10 Thick Yeti Hide in Feral Scar Vale.",
            dependsOn = { "accept-2821-the-mark-of-quality" },
            complete = QuestState(2821, "complete"),
            route = {
                Point(MAP.FERALAS, 0.5540, 0.5636, "Feral Scar Yeti",
                    "Travel to Feral Scar Yeti."),
            },
        },
        {
            id = "travel-2982-ruins-of-isildien",
            kind = "travel",
            priority = 390,
            text = "Travel to Ruins of Isildien.",
            route = {
                Point(MAP.FERALAS, 0.6141, 0.5541, "Ruins of Isildien",
                    "Travel to Ruins of Isildien."),
            },
        },
        {
            id = "objective-2982-the-high-wilderness",
            kind = "objective",
            priority = 400,
            text = "Kill Gordunni Ogres in Ruins of Isildien, focus on Gordunni Warlock first Gordunni Brute is North side Gordunni Shaman is South Side Gordunni Warlock is scatttered.",
            dependsOn = { "accept-2982-the-high-wilderness" },
            complete = QuestState(2982, "complete"),
            route = {
                Point(MAP.FERALAS, 0.6108, 0.5565, "Continue toward The High Wilderness",
                    "Continue toward The High Wilderness."),
                Point(MAP.FERALAS, 0.5891, 0.6477, "Continue toward The High Wilderness",
                    "Continue toward The High Wilderness."),
                Point(MAP.FERALAS, 0.6017, 0.6691, "Gordunni Warlock",
                    "Travel to Gordunni Warlock."),
            },
        },
        {
            id = "accept-2969-freedom-for-all-creatures",
            kind = "accept",
            priority = 410,
            text = "Accept Freedom for All Creatures from Kindal Moonweaver in Feralas.",
            complete = QuestState(2969, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.6561, 0.4675, "Continue toward Freedom for All Creatures",
                    "Continue toward Freedom for All Creatures."),
                Point(MAP.FERALAS, 0.6582, 0.4621, "Continue toward Freedom for All Creatures",
                    "Continue toward Freedom for All Creatures."),
                Point(MAP.FERALAS, 0.6596, 0.4566, "Kindal Moonweaver",
                    "Travel to Kindal Moonweaver."),
            },
        },
        {
            id = "objective-2969-freedom-for-all-creatures",
            kind = "objective",
            priority = 420,
            text = "Clear the area and click on the cage door to release 6 Captured Sprite Darter.",
            dependsOn = { "accept-2969-freedom-for-all-creatures" },
            complete = QuestState(2969, "complete"),
            route = {
                Point(MAP.FERALAS, 0.6667, 0.4670, "Captured Sprite Darter",
                    "Travel to Captured Sprite Darter."),
            },
        },
        {
            id = "turnin-2969-freedom-for-all-creatures",
            kind = "turnin",
            priority = 430,
            text = "Turn in Freedom for All Creatures to Homing Robot OOX-22/FE in Feralas.",
            dependsOn = { "objective-2969-freedom-for-all-creatures" },
            complete = QuestState(2969, "completed"),
            route = {
                Point(MAP.FERALAS, 0.6561, 0.4675, "Continue toward Freedom for All Creatures",
                    "Continue toward Freedom for All Creatures."),
                Point(MAP.FERALAS, 0.6582, 0.4621, "Continue toward Freedom for All Creatures",
                    "Continue toward Freedom for All Creatures."),
                Point(MAP.FERALAS, 0.6595, 0.4569, "Homing Robot OOX-22/FE",
                    "Travel to Homing Robot OOX-22/FE."),
            },
        },
        {
            id = "accept-2970-doling-justice",
            kind = "accept",
            priority = 440,
            text = "Accept Doling Justice from Jer'kai Moonweaver in Feralas.",
            complete = QuestState(2970, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.6595, 0.4562, "Jer'kai Moonweaver",
                    "Travel to Jer'kai Moonweaver."),
            },
        },
        {
            id = "objective-2970-doling-justice",
            kind = "objective",
            priority = 450,
            text = "Kill 10 Grimtotem Raider, 6 Grimtotem Shaman and 12 Grimtotem Shaman in Feralas.",
            dependsOn = { "accept-2970-doling-justice" },
            complete = QuestState(2970, "complete"),
            route = {
                Point(MAP.FERALAS, 0.6594, 0.4766, "Continue toward Doling Justice",
                    "Continue toward Doling Justice."),
                Point(MAP.FERALAS, 0.6672, 0.4632, "Continue toward Doling Justice",
                    "Continue toward Doling Justice."),
                Point(MAP.FERALAS, 0.6792, 0.4637, "Grimtotem Raider",
                    "Travel to Grimtotem Raider."),
            },
        },
        {
            id = "turnin-2970-doling-justice",
            kind = "turnin",
            priority = 460,
            text = "Turn in Doling Justice to Jer'kai Moonweaver in Feralas.",
            dependsOn = { "objective-2970-doling-justice" },
            complete = QuestState(2970, "completed"),
            route = {
                Point(MAP.FERALAS, 0.6561, 0.4675, "Continue toward Doling Justice",
                    "Continue toward Doling Justice."),
                Point(MAP.FERALAS, 0.6582, 0.4621, "Continue toward Doling Justice",
                    "Continue toward Doling Justice."),
                Point(MAP.FERALAS, 0.6593, 0.4560, "Jer'kai Moonweaver",
                    "Travel to Jer'kai Moonweaver."),
            },
        },
        {
            id = "accept-2972-doling-justice",
            kind = "accept",
            priority = 470,
            text = "Accept Doling Justice from Jer'kai Moonweaver in Feralas.",
            complete = QuestState(2972, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.6593, 0.4560, "Jer'kai Moonweaver",
                    "Travel to Jer'kai Moonweaver."),
            },
        },
        {
            id = "travel-4135-woodpaw-hills",
            kind = "travel",
            priority = 480,
            text = "Travel to Woodpaw Hills.",
            route = {
                Point(MAP.FERALAS, 0.7330, 0.5631, "Woodpaw Hills",
                    "Travel to Woodpaw Hills."),
            },
        },
        {
            id = "turnin-4131-the-woodpaw-gnolls",
            kind = "turnin",
            priority = 490,
            text = "Turn in The Woodpaw Gnolls in Woodpaw Hills.",
            dependsOn = { "accept-4131-the-woodpaw-gnolls" },
            complete = QuestState(4131, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7330, 0.5631, "Woodpaw Hills",
                    "Travel to Woodpaw Hills."),
            },
        },
        {
            id = "accept-4135-the-writhing-deep",
            kind = "accept",
            priority = 500,
            text = "Accept The Writhing Deep in Woodpaw Hills.",
            complete = QuestState(4135, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7330, 0.5631, "Woodpaw Hills",
                    "Travel to Woodpaw Hills."),
            },
        },
        {
            id = "accept-4281-thalanaar-delivery",
            kind = "accept",
            priority = 510,
            text = "Use the Undelivered Parcel to accept Thalanaar Delivery.",
            complete = QuestState(4281, "activeOrCompleted"),
        },
        {
            id = "travel-4265-the-writhing-deep",
            kind = "travel",
            priority = 520,
            text = "Travel to The Writhing Deep.",
            route = {
                Point(MAP.FERALAS, 0.7307, 0.6397, "The Writhing Deep",
                    "Travel to The Writhing Deep."),
            },
        },
        {
            id = "turnin-4135-the-writhing-deep",
            kind = "turnin",
            priority = 530,
            text = "Turn in The Writhing Deep in The Writhing Deep.",
            dependsOn = { "accept-4135-the-writhing-deep" },
            complete = QuestState(4135, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7307, 0.6397, "Continue toward The Writhing Deep",
                    "Continue toward The Writhing Deep."),
                Point(MAP.FERALAS, 0.7209, 0.6370, "The Writhing Deep",
                    "Travel to The Writhing Deep."),
            },
        },
        {
            id = "accept-4265-freed-from-the-hive",
            kind = "accept",
            priority = 540,
            text = "Accept Freed from the Hive in The Writhing Deep.",
            complete = QuestState(4265, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7209, 0.6370, "The Writhing Deep",
                    "Travel to The Writhing Deep."),
            },
        },
        {
            id = "objective-4265-freed-from-the-hive",
            kind = "objective",
            priority = 550,
            text = "Free Raschal the Courier in The Writhing Deep, just wait until the quest is complete.",
            dependsOn = { "accept-4265-freed-from-the-hive" },
            complete = QuestState(4265, "complete"),
            route = {
                Point(MAP.FERALAS, 0.7206, 0.6365, "Raschal the Courier",
                    "Travel to Raschal the Courier."),
            },
        },
        {
            id = "travel-thalanaar",
            kind = "travel",
            priority = 560,
            text = "Travel to Thalanaar.",
            route = {
                Point(MAP.FERALAS, 0.8965, 0.4658, "Thalanaar",
                    "Travel to Thalanaar."),
            },
        },
        {
            id = "turnin-4281-thalanaar-delivery",
            kind = "turnin",
            priority = 570,
            text = "Turn in Thalanaar Delivery to Falfindel Waywarder in Thalanaar.",
            dependsOn = { "accept-4281-thalanaar-delivery" },
            complete = QuestState(4281, "completed"),
            route = {
                Point(MAP.FERALAS, 0.8965, 0.4658, "Falfindel Waywarder",
                    "Travel to Falfindel Waywarder."),
            },
        },
        {
            id = "travel-4266-feathermoon-stronghold",
            kind = "travel",
            priority = 580,
            text = "Travel or Hearthstone to Feathermoon Stronghold.",
            route = {
                Point(MAP.FERALAS, 0.3062, 0.4272, "Feathermoon Stronghold",
                    "Travel to Feathermoon Stronghold."),
            },
        },
        {
            id = "turnin-2821-the-mark-of-quality",
            kind = "turnin",
            priority = 590,
            text = "Turn in The Mark of Quality to Pratt McGrubben in Feathermoon Stronghold.",
            dependsOn = { "objective-2821-the-mark-of-quality" },
            complete = QuestState(2821, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3062, 0.4272, "Pratt McGrubben",
                    "Travel to Pratt McGrubben."),
            },
        },
        {
            id = "turnin-2982-the-high-wilderness",
            kind = "turnin",
            priority = 600,
            text = "Turn in The High Wilderness to Angelas Moonbreeze in Feathermoon Stronghold.",
            dependsOn = { "objective-2982-the-high-wilderness" },
            complete = QuestState(2982, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3182, 0.4562, "Angelas Moonbreeze",
                    "Travel to Angelas Moonbreeze."),
            },
        },
        {
            id = "turnin-4265-freed-from-the-hive",
            kind = "turnin",
            priority = 610,
            text = "Turn in Freed from the Hive to Ginro Hearthkindle in Feathermoon Stronghold.",
            dependsOn = { "objective-4265-freed-from-the-hive" },
            complete = QuestState(4265, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3187, 0.4515, "Ginro Hearthkindle",
                    "Travel to Ginro Hearthkindle."),
            },
        },
        {
            id = "accept-4266-a-hero-s-welcome",
            kind = "accept",
            priority = 620,
            text = "Accept A Hero's Welcome from Ginro Hearthkindle in Feathermoon Stronghold.",
            complete = QuestState(4266, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3187, 0.4515, "Ginro Hearthkindle",
                    "Travel to Ginro Hearthkindle."),
            },
        },
        {
            id = "turnin-4266-a-hero-s-welcome",
            kind = "turnin",
            priority = 630,
            text = "Turn in A Hero's Welcome to Shandris Feathermoon in Feathermoon Stronghold.",
            dependsOn = { "accept-4266-a-hero-s-welcome" },
            complete = QuestState(4266, "completed"),
            route = {
                Point(MAP.FERALAS, 0.3028, 0.4618, "Shandris Feathermoon",
                    "Travel to Shandris Feathermoon."),
            },
        },
        {
            id = "accept-4267-rise-of-the-silithid",
            kind = "accept",
            priority = 640,
            text = "Accept Rise of the Silithid from Shandris Feathermoon in Feathermoon Stronghold.",
            complete = QuestState(4267, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.3028, 0.4618, "Shandris Feathermoon",
                    "Travel to Shandris Feathermoon."),
            },
        },
        {
            id = "travel-3022-darnassus",
            kind = "travel",
            priority = 650,
            text = "Travel to Darnassus.",
            route = {
                Point(MAP.DARNASSUS, 0.3988, 0.4221, "Darnassus",
                    "Travel to Darnassus."),
            },
        },
        {
            id = "travel-temple-of-the-moon",
            kind = "travel",
            priority = 660,
            text = "Travel to Temple of the Moon.",
            route = {
                Point(MAP.DARNASSUS, 0.4176, 0.8552, "Temple of the Moon",
                    "Travel to Temple of the Moon."),
            },
        },
        {
            id = "turnin-4267-rise-of-the-silithid",
            kind = "turnin",
            priority = 670,
            text = "Turn in Rise of the Silithid to Gracina Spiritmight in Temple of the Moon.",
            dependsOn = { "accept-4267-rise-of-the-silithid" },
            complete = QuestState(4267, "completed"),
            route = {
                Point(MAP.DARNASSUS, 0.4176, 0.8552, "Gracina Spiritmight",
                    "Travel to Gracina Spiritmight."),
            },
        },
        {
            id = "turnin-2972-doling-justice",
            kind = "turnin",
            priority = 680,
            text = "Turn in Doling Justice to Tyrande Whisperwind in Temple of the Moon.",
            dependsOn = { "accept-2972-doling-justice" },
            complete = QuestState(2972, "completed"),
            route = {
                Point(MAP.DARNASSUS, 0.3902, 0.8155, "Tyrande Whisperwind",
                    "Travel to Tyrande Whisperwind."),
            },
        },
        {
            id = "travel-3661-rut-theran-village",
            kind = "travel",
            priority = 690,
            text = "Travel to Rut'theran Village.",
            route = {
                Point(MAP.TELDRASSIL, 0.2935, 0.4142, "Continue toward Rut'theran Village",
                    "Continue toward Rut'theran Village."),
                Point(MAP.TELDRASSIL, 0.5550, 0.9205, "Rut'theran Village",
                    "Travel to Rut'theran Village."),
            },
        },
        {
            id = "turnin-3022-handle-with-care",
            kind = "turnin",
            priority = 700,
            text = "Turn in Handle With Care to Erelas Ambersky in Rut'theran Village.",
            complete = QuestState(3022, "completed"),
            route = {
                Point(MAP.TELDRASSIL, 0.5550, 0.9205, "Erelas Ambersky",
                    "Travel to Erelas Ambersky."),
            },
        },
        {
            id = "accept-3661-favored-of-elune",
            kind = "accept",
            priority = 710,
            text = "Accept Favored of Elune? from Erelas Ambersky in Rut'theran Village.",
            complete = QuestState(3661, "activeOrCompleted"),
            route = {
                Point(MAP.TELDRASSIL, 0.5550, 0.9215, "Erelas Ambersky",
                    "Travel to Erelas Ambersky."),
            },
        },
        {
            id = "turnin-2939-in-search-of-knowledge",
            kind = "turnin",
            priority = 720,
            text = "Turn in In Search of Knowledge to Daryn Lightwind in Rut'theran Village.",
            dependsOn = { "accept-2939-in-search-of-knowledge" },
            complete = QuestState(2939, "completed"),
            route = {
                Point(MAP.TELDRASSIL, 0.5543, 0.9224, "Daryn Lightwind",
                    "Travel to Daryn Lightwind."),
            },
        },
        {
            id = "accept-2940-feralas-a-history",
            kind = "accept",
            priority = 730,
            text = "Accept Feralas: A History in Rut'theran Village.",
            complete = QuestState(2940, "activeOrCompleted"),
            route = {
                Point(MAP.TELDRASSIL, 0.5523, 0.9146, "Rut'theran Village",
                    "Travel to Rut'theran Village."),
            },
        },
        {
            id = "turnin-2940-feralas-a-history",
            kind = "turnin",
            priority = 740,
            text = "Turn in Feralas: A History to Daryn Lightwind in Rut'theran Village.",
            dependsOn = { "accept-2940-feralas-a-history" },
            complete = QuestState(2940, "completed"),
            route = {
                Point(MAP.TELDRASSIL, 0.5542, 0.9219, "Daryn Lightwind",
                    "Travel to Daryn Lightwind."),
            },
        },
        {
            id = "accept-2941-the-borrower",
            kind = "accept",
            priority = 750,
            text = "Accept The Borrower from Daryn Lightwind in Rut'theran Village.",
            complete = QuestState(2941, "activeOrCompleted"),
            route = {
                Point(MAP.TELDRASSIL, 0.5542, 0.9219, "Daryn Lightwind",
                    "Travel to Daryn Lightwind."),
            },
        },
    },
})
