local _, ns = ...

-- Horde Era leveling route for Feralas, levels 45-46.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    FERALAS = 1444,
    ORGRIMMAR = 1454,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-45-46-feralas",
    title = "45-46 Feralas (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Horde" },
            { level = { min = 45 } },
        },
    },
    goals = {
        {
            id = "travel-2973-camp-mojache",
            kind = "travel",
            priority = 10,
            text = "Travel to Camp Mojache.",
            route = {
                Point(MAP.FERALAS, 0.7595, 0.4274, "Camp Mojache",
                    "Travel to Camp Mojache."),
            },
        },
        {
            id = "accept-2973-a-new-cloak-s-sheen",
            kind = "accept",
            priority = 20,
            text = "Accept A New Cloak's Sheen from Krueg Skullsplitter in Camp Mojache.",
            complete = QuestState(2973, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7595, 0.4274, "Krueg Skullsplitter",
                    "Travel to Krueg Skullsplitter."),
            },
        },
        {
            id = "accept-2975-the-ogres-of-feralas",
            kind = "accept",
            priority = 30,
            text = "Accept The Ogres of Feralas from Rok Orhan in Camp Mojache.",
            complete = QuestState(2975, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7550, 0.4370, "Continue toward The Ogres of Feralas",
                    "Continue toward The Ogres of Feralas."),
                Point(MAP.FERALAS, 0.7330, 0.4480, "Rok Orhan",
                    "Travel to Rok Orhan."),
            },
        },
        {
            id = "accept-2987-gordunni-cobalt",
            kind = "accept",
            priority = 40,
            text = "Accept Gordunni Cobalt from Orwin Gizzmick in Camp Mojache.",
            complete = QuestState(2987, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7566, 0.4420, "Orwin Gizzmick",
                    "Travel to Orwin Gizzmick."),
            },
        },
        {
            id = "accept-2862-war-on-the-woodpaw",
            kind = "accept",
            priority = 50,
            text = "Accept War on the Woodpaw from Hadoken Swiftstrider in Camp Mojache.",
            complete = QuestState(2862, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7487, 0.4272, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "accept-2822-the-mark-of-quality",
            kind = "accept",
            priority = 60,
            text = "Accept The Mark of Quality from Jangdor Swiftstrider in Camp Mojache.",
            complete = QuestState(2822, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7443, 0.4293, "Jangdor Swiftstrider",
                    "Travel to Jangdor Swiftstrider."),
            },
        },
        {
            id = "accept-3121-a-strange-request",
            kind = "accept",
            priority = 70,
            text = "Accept A Strange Request from Witch Doctor Uzer'i in Camp Mojache.",
            complete = QuestState(3121, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7443, 0.4337, "Witch Doctor Uzer'i",
                    "Travel to Witch Doctor Uzer'i."),
            },
        },
        {
            id = "note-2978-camp-mojache",
            kind = "note",
            priority = 80,
            text = "Set your hearth in Camp Mojache with Innkeeper Greul.",
            route = {
                Point(MAP.FERALAS, 0.7480, 0.4510, "Innkeeper Greul",
                    "Travel to Innkeeper Greul."),
            },
        },
        {
            id = "objective-2862-war-on-the-woodpaw",
            kind = "objective",
            priority = 90,
            text = "Kill the Woodpaw north of Camp Mojache and collect 10 Woodpaw Gnoll Mane.",
            dependsOn = { "accept-2862-war-on-the-woodpaw" },
            complete = QuestState(2862, "complete"),
            route = {
                Point(MAP.FERALAS, 0.7275, 0.3795, "Woodpaw Mongrel",
                    "Travel to Woodpaw Mongrel."),
            },
        },
        {
            id = "travel-2987-gordunni-outpost",
            kind = "travel",
            priority = 100,
            text = "Travel to Gordunni Outpost.",
            route = {
                Point(MAP.FERALAS, 0.7485, 0.3531, "Continue toward Gordunni Outpost",
                    "Continue toward Gordunni Outpost."),
                Point(MAP.FERALAS, 0.7555, 0.2975, "Gordunni Outpost",
                    "Travel to Gordunni Outpost."),
            },
        },
        {
            id = "objective-2987-gordunni-cobalt",
            kind = "objective",
            priority = 110,
            text = "Use Orwin's Shovel near the glowing purple mounds and collect 12 Gordunni Cobalt.",
            dependsOn = { "accept-2987-gordunni-cobalt" },
            complete = QuestState(2987, "complete"),
            route = {
                Point(MAP.FERALAS, 0.7527, 0.3364, "Continue toward Gordunni Cobalt",
                    "Continue toward Gordunni Cobalt."),
                Point(MAP.FERALAS, 0.7638, 0.3306, "Continue toward Gordunni Cobalt",
                    "Continue toward Gordunni Cobalt."),
                Point(MAP.FERALAS, 0.7553, 0.3041, "Continue toward Gordunni Cobalt",
                    "Continue toward Gordunni Cobalt."),
                Point(MAP.FERALAS, 0.7456, 0.3025, "Continue toward Gordunni Cobalt",
                    "Continue toward Gordunni Cobalt."),
                Point(MAP.FERALAS, 0.7426, 0.2898, "Continue toward Gordunni Cobalt",
                    "Continue toward Gordunni Cobalt."),
                Point(MAP.FERALAS, 0.7535, 0.2824, "Gordunni Cobalt",
                    "Travel to Gordunni Cobalt."),
            },
        },
        {
            id = "objective-2975-the-ogres-of-feralas",
            kind = "objective",
            priority = 120,
            text = "Kill 10 Gordunni Ogre, 10 Gordunni Ogre Mage and 5 Gordunni Brute in Gordunni Outpost.",
            dependsOn = { "accept-2975-the-ogres-of-feralas" },
            complete = QuestState(2975, "complete"),
            route = {
                Point(MAP.FERALAS, 0.7500, 0.3000, "Gordunni Ogre",
                    "Travel to Gordunni Ogre."),
            },
        },
        {
            id = "objective-2978-gordunni-scroll",
            kind = "objective",
            priority = 130,
            text = "Collect Gordunni Scroll found near a log on the floor in Gordunni Outpost.",
            dependsOn = { "accept-2978-the-gordunni-scroll" },
            complete = QuestState(2978, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7513, 0.2975, "Gordunni Outpost",
                    "Travel to Gordunni Outpost."),
            },
        },
        {
            id = "accept-2978-the-gordunni-scroll",
            kind = "accept",
            priority = 140,
            text = "Use the Gordunni Scroll to accept The Gordunni Scroll.",
            complete = QuestState(2978, "activeOrCompleted"),
        },
        {
            id = "travel-2980-camp-mojache",
            kind = "travel",
            priority = 150,
            text = "Travel to Camp Mojache.",
            route = {
                Point(MAP.FERALAS, 0.7614, 0.4348, "Camp Mojache",
                    "Travel to Camp Mojache."),
            },
        },
        {
            id = "turnin-2975-the-ogres-of-feralas",
            kind = "turnin",
            priority = 160,
            text = "Turn in The Ogres of Feralas to Rok Orhan in Camp Mojache.",
            dependsOn = { "objective-2975-the-ogres-of-feralas" },
            complete = QuestState(2975, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7550, 0.4370, "Continue toward The Ogres of Feralas",
                    "Continue toward The Ogres of Feralas."),
                Point(MAP.FERALAS, 0.7330, 0.4480, "Rok Orhan",
                    "Travel to Rok Orhan."),
            },
        },
        {
            id = "accept-2980-the-ogres-of-feralas",
            kind = "accept",
            priority = 170,
            text = "Accept The Ogres of Feralas from Rok Orhan in Camp Mojache.",
            complete = QuestState(2980, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7550, 0.4370, "Continue toward The Ogres of Feralas",
                    "Continue toward The Ogres of Feralas."),
                Point(MAP.FERALAS, 0.7330, 0.4480, "Rok Orhan",
                    "Travel to Rok Orhan."),
            },
        },
        {
            id = "turnin-2978-the-gordunni-scroll",
            kind = "turnin",
            priority = 180,
            text = "Turn in The Gordunni Scroll to Rok Orhan in Camp Mojache.",
            dependsOn = { "objective-2978-gordunni-scroll" },
            complete = QuestState(2978, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7550, 0.4370, "Continue toward The Gordunni Scroll",
                    "Continue toward The Gordunni Scroll."),
                Point(MAP.FERALAS, 0.7330, 0.4480, "Rok Orhan",
                    "Travel to Rok Orhan."),
            },
        },
        {
            id = "accept-2979-dark-ceremony",
            kind = "accept",
            priority = 190,
            text = "Accept Dark Ceremony from Rok Orhan in Camp Mojache.",
            complete = QuestState(2979, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7550, 0.4370, "Continue toward Dark Ceremony",
                    "Continue toward Dark Ceremony."),
                Point(MAP.FERALAS, 0.7330, 0.4480, "Rok Orhan",
                    "Travel to Rok Orhan."),
            },
        },
        {
            id = "turnin-2987-gordunni-cobalt",
            kind = "turnin",
            priority = 200,
            text = "Turn in Gordunni Cobalt to Orwin Gizzmick in Camp Mojache.",
            dependsOn = { "objective-2987-gordunni-cobalt" },
            complete = QuestState(2987, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7570, 0.4430, "Orwin Gizzmick",
                    "Travel to Orwin Gizzmick."),
            },
        },
        {
            id = "turnin-2862-war-on-the-woodpaw",
            kind = "turnin",
            priority = 210,
            text = "Turn in War on the Woodpaw to Hadoken Swiftstrider in Camp Mojache.",
            dependsOn = { "objective-2862-war-on-the-woodpaw" },
            complete = QuestState(2862, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7492, 0.4245, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "objective-2863-alpha-strike",
            kind = "objective",
            priority = 220,
            text = "Kill Woodpaw Alpha in Woodpaw Hills, you can only find one in each camp.",
            complete = QuestState(2863, "complete"),
            route = {
                Point(MAP.FERALAS, 0.7314, 0.5642, "Continue toward Alpha Strike",
                    "Continue toward Alpha Strike."),
                Point(MAP.FERALAS, 0.7224, 0.5670, "Continue toward Alpha Strike",
                    "Continue toward Alpha Strike."),
                Point(MAP.FERALAS, 0.7150, 0.5610, "Continue toward Alpha Strike",
                    "Continue toward Alpha Strike."),
                Point(MAP.FERALAS, 0.7158, 0.5412, "Continue toward Alpha Strike",
                    "Continue toward Alpha Strike."),
                Point(MAP.FERALAS, 0.6869, 0.5412, "Woodpaw Alpha",
                    "Travel to Woodpaw Alpha."),
            },
        },
        {
            id = "travel-2902-camp-mojache",
            kind = "travel",
            priority = 230,
            text = "Travel to Camp Mojache.",
            route = {
                Point(MAP.FERALAS, 0.7491, 0.4252, "Camp Mojache",
                    "Travel to Camp Mojache."),
            },
        },
        {
            id = "turnin-2863-alpha-strike",
            kind = "turnin",
            priority = 240,
            text = "Turn in Alpha Strike to Hadoken Swiftstrider in Camp Mojache.",
            dependsOn = { "objective-2863-alpha-strike" },
            complete = QuestState(2863, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7491, 0.4252, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "accept-2902-woodpaw-investigation",
            kind = "accept",
            priority = 250,
            text = "Accept Woodpaw Investigation from Hadoken Swiftstrider in Camp Mojache.",
            complete = QuestState(2902, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7498, 0.4268, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "objective-2973-a-new-cloak-s-sheen",
            kind = "objective",
            priority = 260,
            text = "Kill the Sprite Darter west of Camp Mojache for 10 Iridescent Sprite Darter Wing.",
            dependsOn = { "accept-2973-a-new-cloak-s-sheen" },
            complete = QuestState(2973, "complete"),
            route = {
                Point(MAP.FERALAS, 0.6952, 0.4723, "Sprite Darter",
                    "Travel to Sprite Darter."),
            },
        },
        {
            id = "travel-camp-mojache",
            kind = "travel",
            priority = 270,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 2974, state = "activeOrCompleted" } } },
                },
            },
            text = "Travel to Camp Mojache.",
            route = {
                Point(MAP.FERALAS, 0.7593, 0.4275, "Camp Mojache",
                    "Travel to Camp Mojache."),
            },
        },
        {
            id = "turnin-2973-a-new-cloak-s-sheen",
            kind = "turnin",
            priority = 280,
            text = "Turn in A New Cloak's Sheen to Krueg Skullsplitter in Camp Mojache.",
            dependsOn = { "objective-2973-a-new-cloak-s-sheen" },
            complete = QuestState(2973, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7593, 0.4275, "Krueg Skullsplitter",
                    "Travel to Krueg Skullsplitter."),
            },
        },
        {
            id = "accept-2974-a-grim-discovery",
            kind = "accept",
            priority = 290,
            text = "Accept A Grim Discovery from Krueg Skullsplitter in Camp Mojache.",
            complete = QuestState(2974, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7595, 0.4316, "Krueg Skullsplitter",
                    "Travel to Krueg Skullsplitter."),
            },
        },
        {
            id = "objective-2974-a-grim-discovery",
            kind = "objective",
            priority = 300,
            text = "Kill the Grimtotems Northwest of Camp Mojache for 20 Grimtotem Horn.",
            dependsOn = { "accept-2974-a-grim-discovery" },
            complete = QuestState(2974, "complete"),
            route = {
                Point(MAP.FERALAS, 0.6600, 0.3800, "Grimtotem Raider",
                    "Travel to Grimtotem Raider."),
            },
        },
        {
            id = "travel-2903-woodpaw-hills",
            kind = "travel",
            priority = 310,
            text = "Travel to Woodpaw Hills.",
            route = {
                Point(MAP.FERALAS, 0.7162, 0.5592, "Krueg Skullsplitter",
                    "Travel to Krueg Skullsplitter."),
            },
        },
        {
            id = "turnin-2902-woodpaw-investigation",
            kind = "turnin",
            priority = 320,
            text = "Turn in Woodpaw Investigation in Woodpaw Hills.",
            dependsOn = { "accept-2902-woodpaw-investigation" },
            complete = QuestState(2902, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7160, 0.5590, "Woodpaw Hills",
                    "Travel to Woodpaw Hills."),
            },
        },
        {
            id = "accept-2903-the-battle-plans",
            kind = "accept",
            priority = 330,
            text = "Accept The Battle Plans in Woodpaw Hills.",
            complete = QuestState(2903, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7160, 0.5590, "Woodpaw Hills",
                    "Travel to Woodpaw Hills."),
            },
        },
        {
            id = "travel-2976-camp-mojache",
            kind = "travel",
            priority = 340,
            text = "Travel or Hearthstone to Camp Mojache.",
            route = {
                Point(MAP.FERALAS, 0.7595, 0.4274, "Camp Mojache",
                    "Travel to Camp Mojache."),
            },
        },
        {
            id = "turnin-2974-a-grim-discovery",
            kind = "turnin",
            priority = 350,
            text = "Turn in A Grim Discovery to Krueg Skullsplitter in Camp Mojache.",
            dependsOn = { "objective-2974-a-grim-discovery" },
            complete = QuestState(2974, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7595, 0.4274, "Krueg Skullsplitter",
                    "Travel to Krueg Skullsplitter."),
            },
        },
        {
            id = "accept-2976-a-grim-discovery",
            kind = "accept",
            priority = 360,
            text = "Accept A Grim Discovery from Krueg Skullsplitter in Camp Mojache.",
            complete = QuestState(2976, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7595, 0.4274, "Krueg Skullsplitter",
                    "Travel to Krueg Skullsplitter."),
            },
        },
        {
            id = "turnin-2903-the-battle-plans",
            kind = "turnin",
            priority = 370,
            text = "Turn in The Battle Plans to Hadoken Swiftstrider in Camp Mojache.",
            dependsOn = { "accept-2903-the-battle-plans" },
            complete = QuestState(2903, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7491, 0.4249, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "accept-7730-zukk-ash-infestation",
            kind = "accept",
            priority = 380,
            text = "Accept Zukk'ash Infestation from Hadoken Swiftstrider in Camp Mojache.",
            complete = QuestState(7730, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7491, 0.4249, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "accept-7731-stinglasher",
            kind = "accept",
            priority = 390,
            text = "Accept Stinglasher from Hadoken Swiftstrider in Camp Mojache.",
            complete = QuestState(7731, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7491, 0.4249, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "travel-7731-the-writhing-deep",
            kind = "travel",
            priority = 400,
            text = "Travel to The Writhing Deep.",
            route = {
                Point(MAP.FERALAS, 0.7691, 0.6152, "The Writhing Deep",
                    "Travel to The Writhing Deep."),
            },
        },
        {
            id = "objective-7731-stinglasher",
            kind = "objective",
            priority = 410,
            text = "Kill Stinglasher in the Writhing Deep and loot Stinglasher's Glands, he usually spawn in front of a hive entrance.",
            dependsOn = { "accept-7731-stinglasher" },
            complete = QuestState(7731, "complete"),
            route = {
                Point(MAP.FERALAS, 0.7400, 0.6200, "Continue toward Stinglasher",
                    "Continue toward Stinglasher."),
                Point(MAP.FERALAS, 0.7359, 0.6402, "Stinglasher",
                    "Travel to Stinglasher."),
            },
        },
        {
            id = "objective-7730-zukk-ash-infestation",
            kind = "objective",
            priority = 420,
            text = "Kill the Zukk'ash Wasps at the Writhing Deep for 20 Zukk'ash Carapace.",
            dependsOn = { "accept-7730-zukk-ash-infestation" },
            complete = QuestState(7730, "complete"),
            route = {
                Point(MAP.FERALAS, 0.7400, 0.6200, "Zukk'ash Stinger",
                    "Travel to Zukk'ash Stinger."),
            },
        },
        {
            id = "travel-3520-verdantis-river",
            kind = "travel",
            priority = 430,
            text = "Travel to Verdantis River.",
            route = {
                Point(MAP.FERALAS, 0.6370, 0.5117, "Verdantis River",
                    "Travel to Verdantis River."),
            },
        },
        {
            id = "objective-3520-screecher-spirits",
            kind = "objective",
            priority = 440,
            text = "Kill the Rogue Vale Screecher south of Dire Maul and use the Yeh'kinya's Bramble on their corpses to collect 3 Rogue Vale Screecher.",
            complete = QuestState(3520, "complete"),
            route = {
                Point(MAP.FERALAS, 0.6095, 0.4965, "Continue toward Screecher Spirits",
                    "Continue toward Screecher Spirits."),
                Point(MAP.FERALAS, 0.5911, 0.5094, "Continue toward Screecher Spirits",
                    "Continue toward Screecher Spirits."),
                Point(MAP.FERALAS, 0.5690, 0.4784, "Rogue Vale Screecher",
                    "Travel to Rogue Vale Screecher."),
            },
        },
        {
            id = "travel-2980-ruins-of-isildien",
            kind = "travel",
            priority = 450,
            text = "Travel to Ruins of Isildien.",
            route = {
                Point(MAP.FERALAS, 0.6099, 0.5676, "Ruins of Isildien",
                    "Travel to Ruins of Isildien."),
            },
        },
        {
            id = "objective-2979-dark-ceremony",
            kind = "objective",
            priority = 460,
            text = "Kill Gordunni Mage-Lord for the Gordunni Orb.",
            dependsOn = { "accept-2979-dark-ceremony" },
            complete = QuestState(2979, "complete"),
            route = {
                Point(MAP.FERALAS, 0.5900, 0.6800, "Gordunni Mage-Lord",
                    "Travel to Gordunni Mage-Lord."),
            },
        },
        {
            id = "objective-2980-the-ogres-of-feralas",
            kind = "objective",
            priority = 470,
            text = "Kill 10 Gordunni Shaman, 10 Gordunni Warlock and 5 Gordunni Mauler south of Dire Maul.",
            dependsOn = { "accept-2980-the-ogres-of-feralas" },
            complete = QuestState(2980, "complete"),
            route = {
                Point(MAP.FERALAS, 0.5900, 0.6800, "Gordunni Shaman",
                    "Travel to Gordunni Shaman."),
            },
        },
        {
            id = "travel-2822-feral-scar-vale",
            kind = "travel",
            priority = 480,
            text = "Travel to Feral Scar Vale.",
            route = {
                Point(MAP.FERALAS, 0.5540, 0.5636, "Feral Scar Vale",
                    "Travel to Feral Scar Vale."),
            },
        },
        {
            id = "objective-2822-the-mark-of-quality",
            kind = "objective",
            priority = 490,
            text = "Kill Feral Scar Yeti and collect 10 Thick Yeti Hide in Feral Scar Vale.",
            dependsOn = { "accept-2822-the-mark-of-quality" },
            complete = QuestState(2822, "complete"),
            route = {
                Point(MAP.FERALAS, 0.5540, 0.5636, "Feral Scar Yeti",
                    "Travel to Feral Scar Yeti."),
            },
        },
        {
            id = "travel-2980-camp-mojache-2",
            kind = "travel",
            priority = 500,
            text = "Travel to Camp Mojache.",
            route = {
                Point(MAP.FERALAS, 0.7446, 0.4287, "Camp Mojache",
                    "Travel to Camp Mojache."),
            },
        },
        {
            id = "turnin-2822-the-mark-of-quality",
            kind = "turnin",
            priority = 510,
            text = "Turn in The Mark of Quality to Jangdor Swiftstrider in Camp Mojache.",
            dependsOn = { "objective-2822-the-mark-of-quality" },
            complete = QuestState(2822, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7446, 0.4287, "Jangdor Swiftstrider",
                    "Travel to Jangdor Swiftstrider."),
            },
        },
        {
            id = "turnin-7730-zukk-ash-infestation",
            kind = "turnin",
            priority = 520,
            text = "Turn in Zukk'ash Infestation to Hadoken Swiftstrider in Camp Mojache.",
            dependsOn = { "objective-7730-zukk-ash-infestation" },
            complete = QuestState(7730, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7491, 0.4248, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "turnin-7731-stinglasher",
            kind = "turnin",
            priority = 530,
            text = "Turn in Stinglasher to Hadoken Swiftstrider in Camp Mojache.",
            dependsOn = { "objective-7731-stinglasher" },
            complete = QuestState(7731, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7491, 0.4248, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "accept-7732-zukk-ash-report",
            kind = "accept",
            priority = 540,
            text = "Accept Zukk'ash Report from Hadoken Swiftstrider in Camp Mojache.",
            complete = QuestState(7732, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7484, 0.4272, "Hadoken Swiftstrider",
                    "Travel to Hadoken Swiftstrider."),
            },
        },
        {
            id = "turnin-2979-dark-ceremony",
            kind = "turnin",
            priority = 550,
            text = "Turn in Dark Ceremony to Rok Orhan in Camp Mojache.",
            dependsOn = { "objective-2979-dark-ceremony" },
            complete = QuestState(2979, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7657, 0.4320, "Rok Orhan",
                    "Travel to Rok Orhan."),
            },
        },
        {
            id = "turnin-2980-the-ogres-of-feralas",
            kind = "turnin",
            priority = 560,
            text = "Turn in The Ogres of Feralas to Rok Orhan in Camp Mojache.",
            dependsOn = { "objective-2980-the-ogres-of-feralas" },
            complete = QuestState(2980, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7666, 0.4328, "Rok Orhan",
                    "Travel to Rok Orhan."),
            },
        },
        {
            id = "accept-3002-the-gordunni-orb",
            kind = "accept",
            priority = 570,
            text = "Accept The Gordunni Orb from Rok Orhan in Camp Mojache.",
            complete = QuestState(3002, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7652, 0.4320, "Rok Orhan",
                    "Travel to Rok Orhan."),
            },
        },
        {
            id = "travel-649-orgrimmar",
            kind = "travel",
            priority = 580,
            text = "Travel to Orgrimmar.",
            route = {
                Point(MAP.ORGRIMMAR, 0.5636, 0.4660, "Orgrimmar",
                    "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-7732-zukk-ash-report",
            kind = "turnin",
            priority = 590,
            text = "Turn in Zukk'ash Report to Zilzibin Drumlore in The Drag.",
            dependsOn = { "accept-7732-zukk-ash-report" },
            complete = QuestState(7732, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.5636, 0.4660, "Zilzibin Drumlore",
                    "Travel to Zilzibin Drumlore."),
            },
        },
        {
            id = "accept-649-ripple-recovery",
            kind = "accept",
            priority = 600,
            text = "Accept Ripple Recovery from Dran Droffers in The Drag.",
            complete = QuestState(649, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.5976, 0.3700, "Dran Droffers",
                    "Travel to Dran Droffers."),
            },
        },
        {
            id = "turnin-649-ripple-recovery",
            kind = "turnin",
            priority = 610,
            text = "Turn in Ripple Recovery to Zilzibin Drumlore in The Drag.",
            dependsOn = { "accept-649-ripple-recovery" },
            complete = QuestState(649, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.5964, 0.3686, "Zilzibin Drumlore",
                    "Travel to Zilzibin Drumlore."),
            },
        },
        {
            id = "accept-650-ripple-recovery",
            kind = "accept",
            priority = 620,
            text = "Accept Ripple Recovery from Malton Droffers in The Drag.",
            complete = QuestState(650, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.5964, 0.3686, "Malton Droffers",
                    "Travel to Malton Droffers."),
            },
        },
        {
            id = "turnin-2976-a-grim-discovery",
            kind = "turnin",
            priority = 630,
            text = "Turn in A Grim Discovery to Belgrom Rockmaul in Valley of Honor.",
            dependsOn = { "accept-2976-a-grim-discovery" },
            complete = QuestState(2976, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.7515, 0.3430, "Belgrom Rockmaul",
                    "Travel to Belgrom Rockmaul."),
            },
        },
        {
            id = "accept-3504-betrayed",
            kind = "accept",
            priority = 640,
            text = "Accept Betrayed from Belgrom Rockmaul in Valley of Honor.",
            complete = QuestState(3504, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.7515, 0.3430, "Belgrom Rockmaul",
                    "Travel to Belgrom Rockmaul."),
            },
        },
        {
            id = "turnin-3121-a-strange-request",
            kind = "turnin",
            priority = 650,
            text = "Turn in A Strange Request to Arnak Fireblade in Cleft of Shadow.",
            dependsOn = { "accept-3121-a-strange-request" },
            complete = QuestState(3121, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.4964, 0.5053, "Arnak Fireblade",
                    "Travel to Arnak Fireblade."),
            },
        },
        {
            id = "accept-3122-return-to-witch-doctor-uzer-i",
            kind = "accept",
            priority = 660,
            text = "Accept Return to Witch Doctor Uzer'i from Arnak Fireblade in Cleft of Shadow.",
            complete = QuestState(3122, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.4964, 0.5053, "Arnak Fireblade",
                    "Travel to Arnak Fireblade."),
            },
        },
        {
            id = "turnin-7541-service-to-the-horde",
            kind = "turnin",
            priority = 670,
            conditions = {
                all = {
                    { quest = { id = 1262, state = "completed" } },
                },
            },
            text = "Turn in Service to the Horde to Zor Lonetree in Grommash Hold. This is an elite. Bring a group.",
            complete = QuestState(7541, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.3899, 0.3827, "Zor Lonetree",
                    "Travel to Zor Lonetree."),
            },
        },
        {
            id = "turnin-3002-the-gordunni-orb",
            kind = "turnin",
            priority = 680,
            text = "Turn in The Gordunni Orb to Uthel'nay in Valley of Spirits.",
            dependsOn = { "accept-3002-the-gordunni-orb" },
            complete = QuestState(3002, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.3907, 0.8621, "Uthel'nay",
                    "Travel to Uthel'nay."),
            },
        },
        {
            id = "travel-3122-camp-mojache",
            kind = "travel",
            priority = 690,
            text = "Travel or Hearthstone to Camp Mojache.",
            route = {
                Point(MAP.FERALAS, 0.7441, 0.4338, "Camp Mojache",
                    "Travel to Camp Mojache."),
            },
        },
        {
            id = "turnin-3122-return-to-witch-doctor-uzer-i",
            kind = "turnin",
            priority = 700,
            text = "Turn in Return to Witch Doctor Uzer'i to Witch Doctor Uzer'i in Camp Mojache.",
            dependsOn = { "accept-3122-return-to-witch-doctor-uzer-i" },
            complete = QuestState(3122, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7441, 0.4338, "Witch Doctor Uzer'i",
                    "Travel to Witch Doctor Uzer'i."),
            },
        },
        {
            id = "accept-3123-testing-the-vessel",
            kind = "accept",
            priority = 710,
            text = "Accept Testing the Vessel from Witch Doctor Uzer'i in Camp Mojache.",
            complete = QuestState(3123, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7441, 0.4338, "Witch Doctor Uzer'i",
                    "Travel to Witch Doctor Uzer'i."),
            },
        },
        {
            id = "accept-3128-natural-materials",
            kind = "accept",
            priority = 720,
            text = "Accept Natural Materials from Witch Doctor Uzer'i in Camp Mojache.",
            complete = QuestState(3128, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.7443, 0.4337, "Witch Doctor Uzer'i",
                    "Travel to Witch Doctor Uzer'i."),
            },
        },
        {
            id = "objective-3128-2-sprite-darter",
            kind = "objective",
            priority = 730,
            text = "Kill Sprite Darter and collect 6 Encrusted Minerals.",
            dependsOn = { "accept-3128-natural-materials" },
            complete = QuestObjective(3128, 2),
            route = {
                Point(MAP.FERALAS, 0.6952, 0.4723, "Sprite Darter",
                    "Travel to Sprite Darter."),
            },
        },
        {
            id = "travel-3128-high-wilderness",
            kind = "travel",
            priority = 740,
            text = "Travel to High Wilderness.",
            route = {
                Point(MAP.FERALAS, 0.6779, 0.4972, "Continue toward High Wilderness",
                    "Continue toward High Wilderness."),
                Point(MAP.FERALAS, 0.6481, 0.5010, "Continue toward High Wilderness",
                    "Continue toward High Wilderness."),
                Point(MAP.FERALAS, 0.5684, 0.6587, "High Wilderness",
                    "Travel to High Wilderness."),
            },
        },
        {
            id = "objective-3128-1-wandering-forest-walker",
            kind = "objective",
            priority = 750,
            text = "Kill Wandering Forest Walker and collect 2 Splintered Log in Feralas, Wandering Forest Walker only spawn in 4 possible locations with 5 mins respawn time, after you kill one and check again later.",
            dependsOn = { "accept-3128-natural-materials" },
            complete = QuestObjective(3128, 1),
            route = {
                Point(MAP.FERALAS, 0.5740, 0.7330, "Wandering Forest Walker",
                    "Travel to Wandering Forest Walker."),
            },
        },
        {
            id = "objective-2741-hippogryph-egg",
            kind = "objective",
            priority = 760,
            text = "Collect Hippogryph Egg from the bird nest in Ruins of Isildien.",
            complete = QuestState(2741, "complete"),
            route = {
                Point(MAP.FERALAS, 0.5779, 0.7464, "Continue toward Hippogryph Egg",
                    "Continue toward Hippogryph Egg."),
                Point(MAP.FERALAS, 0.5858, 0.7555, "Ruins of Isildien",
                    "Travel to Ruins of Isildien."),
            },
        },
        {
            id = "travel-3128-1-high-wilderness",
            kind = "travel",
            priority = 770,
            text = "Travel to High Wilderness.",
            complete = QuestObjective(3128, 1),
            route = {
                Point(MAP.FERALAS, 0.5450, 0.6838, "High Wilderness",
                    "Travel to High Wilderness."),
            },
        },
        {
            id = "objective-3128-3-natural-materials",
            kind = "objective",
            priority = 780,
            text = "Kill Frayfeather Stagwing or Frayfeather Hippogryph 20 Resilient Sinew and 40 Metallic Fragments in High Wilderness.",
            dependsOn = { "accept-3128-natural-materials" },
            complete = QuestObjective(3128, 3),
            route = {
                Point(MAP.FERALAS, 0.5450, 0.6838, "Frayfeather Stagwing",
                    "Travel to Frayfeather Stagwing."),
            },
        },
        {
            id = "objective-3128-4-natural-materials",
            kind = "objective",
            priority = 790,
            text = "Kill Frayfeather Stagwing or Frayfeather Hippogryph 20 Resilient Sinew and 40 Metallic Fragments in High Wilderness.",
            dependsOn = { "accept-3128-natural-materials" },
            complete = QuestObjective(3128, 4),
            route = {
                Point(MAP.FERALAS, 0.5450, 0.6838, "Frayfeather Stagwing",
                    "Travel to Frayfeather Stagwing."),
            },
        },
        {
            id = "objective-3128-1-wandering-forest-walker-2",
            kind = "objective",
            priority = 800,
            text = "Kill Wandering Forest Walker and collect 2 Splintered Log in Feralas, Wandering Forest Walker only spawn in 4 possible locations with 5 mins respawn time, after you kill one and check again later.",
            dependsOn = { "accept-3128-natural-materials" },
            complete = QuestObjective(3128, 1),
            route = {
                Point(MAP.FERALAS, 0.7390, 0.3880, "Continue toward Wandering Forest Walker",
                    "Continue toward Wandering Forest Walker."),
                Point(MAP.FERALAS, 0.7350, 0.5450, "Wandering Forest Walker",
                    "Travel to Wandering Forest Walker."),
            },
        },
        {
            id = "turnin-3128-natural-materials",
            kind = "turnin",
            priority = 810,
            text = "Turn in Natural Materials to Witch Doctor Uzer'i in Camp Mojache.",
            dependsOn = { "objective-3128-2-sprite-darter", "objective-3128-1-wandering-forest-walker", "objective-3128-3-natural-materials", "objective-3128-4-natural-materials", "objective-3128-1-wandering-forest-walker-2" },
            complete = QuestState(3128, "completed"),
            route = {
                Point(MAP.FERALAS, 0.7442, 0.4336, "Witch Doctor Uzer'i",
                    "Travel to Witch Doctor Uzer'i."),
            },
        },
    },
})
