local _, ns = ...

-- Alliance Era leveling route for the Western Plaguelands, levels 56-57.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    WESTERN_PLAGUELANDS = 1422,
    IRONFORGE = 1455,
    HILLSBRAD = 1424,
    STORMWIND = 1453,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-56-57-western-plaguelands",
    title = "56-57 Western Plaguelands (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Alliance" },
            { level = { min = 56 } },
        },
    },
    goals = {
        {
            id = "travel-ironforge",
            kind = "travel",
            priority = 10,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 5903, state = "activeOrCompleted" } } },
                },
            },
            text = "Travel to The High Seat in Ironforge.",
            route = {
                Point(MAP.IRONFORGE, 0.3834, 0.5533, "The High Seat",
                    "Travel to The High Seat."),
            },
        },
        {
            id = "accept-1019-the-new-frontier",
            kind = "accept",
            priority = 20,
            text = "Accept The New Frontier from Courier Hammerfall in Ironforge.",
            complete = QuestState(1019, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.4671, 0.6525, "Courier Hammerfall",
                    "Travel to Courier Hammerfall."),
            },
        },
        {
            id = "accept-5090-a-call-to-arms-the-plaguelands",
            kind = "accept",
            priority = 30,
            text = "Accept A Call to Arms: The Plaguelands! from Courier Hammerfall in Ironforge.",
            complete = QuestState(5090, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.4671, 0.6525, "Courier Hammerfall",
                    "Travel to Courier Hammerfall."),
            },
        },
        {
            id = "note-ironforge",
            kind = "note",
            priority = 40,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 5903, state = "activeOrCompleted" } } },
                },
            },
            text = "Set your hearth in Ironforge with Innkeeper Firebrew.",
            route = {
                Point(MAP.IRONFORGE, 0.1850, 0.5161, "Innkeeper Firebrew",
                    "Travel to Innkeeper Firebrew."),
            },
        },
        {
            id = "travel-chillwind-camp",
            kind = "travel",
            priority = 50,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 5903, state = "activeOrCompleted" } } },
                },
            },
            text = "Travel to Chillwind Camp.",
            route = {
                Point(MAP.HILLSBRAD, 0.6724, 0.3080, "Continue toward Chillwind Camp",
                    "Continue toward Chillwind Camp."),
                Point(MAP.HILLSBRAD, 0.6828, 0.1482, "Continue toward Chillwind Camp",
                    "Continue toward Chillwind Camp."),
                Point(MAP.HILLSBRAD, 0.7158, 0.0798, "Chillwind Camp",
                    "Travel to Chillwind Camp."),
            },
        },
        {
            id = "travel-chillwind-camp-2",
            kind = "travel",
            priority = 60,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 5903, state = "activeOrCompleted" } } },
                },
            },
            text = "Travel to Chillwind Camp.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4293, 0.8507, "Chillwind Camp",
                    "Travel to Chillwind Camp."),
            },
        },
        {
            id = "accept-5903-a-plague-upon-thee",
            kind = "accept",
            priority = 70,
            text = "Accept A Plague Upon Thee from Nathaniel Dumah in Chillwind Camp.",
            complete = QuestState(5903, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4350, 0.8480, "Nathaniel Dumah",
                    "Travel to Nathaniel Dumah."),
            },
        },
        {
            id = "accept-5092-clear-the-way",
            kind = "accept",
            priority = 80,
            text = "Accept Clear the Way from Commander Ashlam Valorfist in Chillwind Camp.",
            complete = QuestState(5092, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4270, 0.8402, "Commander Ashlam Valorfist",
                    "Travel to Commander Ashlam Valorfist."),
            },
        },
        {
            id = "turnin-5401-argent-dawn-commission",
            kind = "turnin",
            priority = 90,
            text = "Turn in Argent Dawn Commission to Argent Officer Pureheart in Chillwind Camp.",
            complete = QuestState(5401, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4297, 0.8357, "Argent Officer Pureheart",
                    "Travel to Argent Officer Pureheart."),
            },
        },
        {
            id = "objective-5092-clear-the-way",
            kind = "objective",
            priority = 100,
            text = "Kill 10 Skeletal Flayer and 10 Slavering Ghoul in Sorrow Hill.",
            dependsOn = { "accept-5092-clear-the-way" },
            complete = QuestState(5092, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.5043, 0.7868, "Skeletal Flayer",
                    "Travel to Skeletal Flayer."),
            },
        },
        {
            id = "travel-5097-chillwind-camp",
            kind = "travel",
            priority = 110,
            text = "Travel to Chillwind Camp.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4271, 0.8404, "Chillwind Camp",
                    "Travel to Chillwind Camp."),
            },
        },
        {
            id = "turnin-5092-clear-the-way",
            kind = "turnin",
            priority = 120,
            text = "Turn in Clear the Way to Commander Ashlam Valorfist in Chillwind Camp.",
            dependsOn = { "objective-5092-clear-the-way" },
            complete = QuestState(5092, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4271, 0.8404, "Commander Ashlam Valorfist",
                    "Travel to Commander Ashlam Valorfist."),
            },
        },
        {
            id = "accept-5097-all-along-the-watchtowers",
            kind = "accept",
            priority = 130,
            text = "Accept All Along the Watchtowers from Commander Ashlam Valorfist in Chillwind Camp.",
            complete = QuestState(5097, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4271, 0.8404, "Commander Ashlam Valorfist",
                    "Travel to Commander Ashlam Valorfist."),
            },
        },
        {
            id = "accept-5215-the-scourge-cauldrons",
            kind = "accept",
            priority = 140,
            text = "Accept The Scourge Cauldrons from Commander Ashlam Valorfist in Chillwind Camp.",
            complete = QuestState(5215, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4271, 0.8404, "Commander Ashlam Valorfist",
                    "Travel to Commander Ashlam Valorfist."),
            },
        },
        {
            id = "turnin-5215-the-scourge-cauldrons",
            kind = "turnin",
            priority = 150,
            text = "Turn in The Scourge Cauldrons to Commander Ashlam Valorfist in Chillwind Camp.",
            dependsOn = { "accept-5215-the-scourge-cauldrons" },
            complete = QuestState(5215, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4298, 0.8451, "Commander Ashlam Valorfist",
                    "Travel to Commander Ashlam Valorfist."),
            },
        },
        {
            id = "accept-5216-target-felstone-field",
            kind = "accept",
            priority = 160,
            text = "Accept Target: Felstone Field from High Priestess MacDonnell in Chillwind Camp.",
            complete = QuestState(5216, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4298, 0.8451, "High Priestess MacDonnell",
                    "Travel to High Priestess MacDonnell."),
            },
        },
        {
            id = "travel-5097-ruins-of-andorhal",
            kind = "travel",
            priority = 170,
            text = "Travel to Ruins of Andorhal.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4180, 0.8012, "Continue toward Ruins of Andorhal",
                    "Continue toward Ruins of Andorhal."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.3626, 0.7813, "Continue toward Ruins of Andorhal",
                    "Continue toward Ruins of Andorhal."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.3867, 0.7144, "Ruins of Andorhal",
                    "Travel to Ruins of Andorhal."),
            },
        },
        {
            id = "objective-5097-1-mark-tower-one",
            kind = "objective",
            priority = 180,
            text = "Use Beacon Torch between the door way of the Tower in Ruins of Andorhal.",
            dependsOn = { "accept-5097-all-along-the-watchtowers" },
            complete = QuestObjective(5097, 1),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4000, 0.7158, "Ruins of Andorhal",
                    "Travel to Ruins of Andorhal."),
            },
        },
        {
            id = "accept-4971-a-matter-of-time",
            kind = "accept",
            priority = 190,
            text = "Accept A Matter of Time from Chromie in Ruins of Andorhal.",
            complete = QuestState(4971, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3945, 0.6679, "Chromie",
                    "Travel to Chromie."),
            },
        },
        {
            id = "objective-5097-2-mark-tower-two",
            kind = "objective",
            priority = 200,
            text = "Use Beacon Torch between the door way of the Tower in Ruins of Andorhal.",
            dependsOn = { "accept-5097-all-along-the-watchtowers" },
            complete = QuestObjective(5097, 2),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4243, 0.6607, "Ruins of Andorhal",
                    "Travel to Ruins of Andorhal."),
            },
        },
        {
            id = "objective-5097-3-mark-tower-three",
            kind = "objective",
            priority = 210,
            text = "Use Beacon Torch between the door way of the Tower in Ruins of Andorhal.",
            dependsOn = { "accept-5097-all-along-the-watchtowers" },
            complete = QuestObjective(5097, 3),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4415, 0.6325, "Ruins of Andorhal",
                    "Travel to Ruins of Andorhal."),
            },
        },
        {
            id = "objective-4971-a-matter-of-time",
            kind = "objective",
            priority = 220,
            text = "Use Temporal Displacer near the glowing silo to spawn and kill 15 Temporal Parasite in Ruins of Andorhal.",
            dependsOn = { "accept-4971-a-matter-of-time" },
            complete = QuestState(4971, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4539, 0.6290, "Continue toward A Matter of Time",
                    "Continue toward A Matter of Time."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.4634, 0.6258, "Continue toward A Matter of Time",
                    "Continue toward A Matter of Time."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.4796, 0.6244, "Continue toward A Matter of Time",
                    "Continue toward A Matter of Time."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.4797, 0.6416, "Continue toward A Matter of Time",
                    "Continue toward A Matter of Time."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.4999, 0.6695, "Temporal Parasite",
                    "Travel to Temporal Parasite."),
            },
        },
        {
            id = "objective-5097-4-mark-tower-four",
            kind = "objective",
            priority = 230,
            text = "Use Beacon Torch between the door way of the Tower in Ruins of Andorhal.",
            dependsOn = { "accept-5097-all-along-the-watchtowers" },
            complete = QuestObjective(5097, 4),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4663, 0.7126, "Ruins of Andorhal",
                    "Travel to Ruins of Andorhal."),
            },
        },
        {
            id = "turnin-4971-a-matter-of-time",
            kind = "turnin",
            priority = 240,
            text = "Turn in A Matter of Time to Chromie in Ruins of Andorhal.",
            dependsOn = { "objective-4971-a-matter-of-time" },
            complete = QuestState(4971, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3945, 0.6678, "Chromie",
                    "Travel to Chromie."),
            },
        },
        {
            id = "accept-4972-counting-out-time",
            kind = "accept",
            priority = 250,
            text = "Accept Counting Out Time from Chromie in Ruins of Andorhal.",
            complete = QuestState(4972, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3945, 0.6678, "Chromie",
                    "Travel to Chromie."),
            },
        },
        {
            id = "objective-4972-counting-out-time",
            kind = "objective",
            priority = 260,
            text = "Collect Andorhal Watch from small lockbox in Ruins of Andorhal.",
            dependsOn = { "accept-4972-counting-out-time" },
            complete = QuestState(4972, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3888, 0.6809, "Continue toward Counting Out Time",
                    "Continue toward Counting Out Time."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.4027, 0.6822, "Continue toward Counting Out Time",
                    "Continue toward Counting Out Time."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.4086, 0.6717, "Continue toward Counting Out Time",
                    "Continue toward Counting Out Time."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.4036, 0.6646, "Continue toward Counting Out Time",
                    "Continue toward Counting Out Time."),
                Point(MAP.WESTERN_PLAGUELANDS, 0.4231, 0.6873, "Ruins of Andorhal",
                    "Travel to Ruins of Andorhal."),
            },
        },
        {
            id = "turnin-4972-counting-out-time",
            kind = "turnin",
            priority = 270,
            text = "Turn in Counting Out Time to Chromie in Ruins of Andorhal.",
            dependsOn = { "objective-4972-counting-out-time" },
            complete = QuestState(4972, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3945, 0.6677, "Chromie",
                    "Travel to Chromie."),
            },
        },
        {
            id = "travel-5216-felstone-field",
            kind = "travel",
            priority = 280,
            text = "Travel to Felstone Field.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3714, 0.5735, "Felstone Field",
                    "Travel to Felstone Field."),
            },
        },
        {
            id = "objective-5216-target-felstone-field",
            kind = "objective",
            priority = 290,
            text = "Kill Cauldron Lord Bilemaw and collect Felstone Field Cauldron Key in Felstone Field.",
            dependsOn = { "accept-5216-target-felstone-field" },
            complete = QuestState(5216, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3714, 0.5735, "Cauldron Lord Bilemaw",
                    "Travel to Cauldron Lord Bilemaw."),
            },
        },
        {
            id = "turnin-5216-target-felstone-field",
            kind = "turnin",
            priority = 300,
            text = "Turn in Target: Felstone Field in Felstone Field.",
            dependsOn = { "objective-5216-target-felstone-field" },
            complete = QuestState(5216, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3723, 0.5689, "Felstone Field",
                    "Travel to Felstone Field."),
            },
        },
        {
            id = "accept-5217-return-to-chillwind-camp",
            kind = "accept",
            priority = 310,
            text = "Accept Return to Chillwind Camp in Felstone Field.",
            complete = QuestState(5217, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3723, 0.5689, "Felstone Field",
                    "Travel to Felstone Field."),
            },
        },
        {
            id = "accept-5021-better-late-than-never",
            kind = "accept",
            priority = 320,
            text = "Accept Better Late Than Never from Janice Felstone in Felstone Field.",
            complete = QuestState(5021, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3839, 0.5405, "Janice Felstone",
                    "Travel to Janice Felstone."),
            },
        },
        {
            id = "turnin-5021-better-late-than-never",
            kind = "turnin",
            priority = 330,
            text = "Turn in Better Late Than Never in Felstone Field.",
            dependsOn = { "accept-5021-better-late-than-never" },
            complete = QuestState(5021, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3873, 0.5525, "Felstone Field",
                    "Travel to Felstone Field."),
            },
        },
        {
            id = "accept-5022-better-late-than-never",
            kind = "accept",
            priority = 340,
            text = "Accept Better Late Than Never in Felstone Field.",
            complete = QuestState(5022, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3873, 0.5525, "Felstone Field",
                    "Travel to Felstone Field."),
            },
        },
        {
            id = "travel-stormwind-city",
            kind = "travel",
            priority = 350,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 6184, state = "activeOrCompleted" } } },
                },
            },
            text = "Use Hearthstone and fly to Stormwind City.",
            route = {
                Point(MAP.STORMWIND, 0.4848, 0.3050, "Stormwind City",
                    "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-5022-better-late-than-never",
            kind = "turnin",
            priority = 360,
            text = "Turn in Better Late Than Never to Royal Factor Bathrilor in Cathedral Square.",
            dependsOn = { "accept-5022-better-late-than-never" },
            complete = QuestState(5022, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.4848, 0.3050, "Royal Factor Bathrilor",
                    "Travel to Royal Factor Bathrilor."),
            },
        },
        {
            id = "accept-5048-good-natured-emma",
            kind = "accept",
            priority = 370,
            text = "Accept Good Natured Emma from Royal Factor Bathrilor in Cathedral Square.",
            complete = QuestState(5048, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.4848, 0.3050, "Royal Factor Bathrilor",
                    "Travel to Royal Factor Bathrilor."),
            },
        },
        {
            id = "turnin-5048-good-natured-emma",
            kind = "turnin",
            priority = 380,
            text = "Turn in Good Natured Emma to Ol' Emma in The Canals.",
            dependsOn = { "accept-5048-good-natured-emma" },
            complete = QuestState(5048, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.5133, 0.4447, "Continue toward Good Natured Emma",
                    "Continue toward Good Natured Emma."),
                Point(MAP.STORMWIND, 0.5460, 0.5390, "Continue toward Good Natured Emma",
                    "Continue toward Good Natured Emma."),
                Point(MAP.STORMWIND, 0.5970, 0.5150, "Ol' Emma",
                    "Travel to Ol' Emma."),
            },
        },
        {
            id = "accept-5050-good-luck-charm",
            kind = "accept",
            priority = 390,
            text = "Accept Good Luck Charm from Ol' Emma in The Canals.",
            complete = QuestState(5050, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.5133, 0.4447, "Ol' Emma",
                    "Travel to Ol' Emma."),
            },
        },
        {
            id = "accept-6182-the-first-and-the-last",
            kind = "accept",
            priority = 400,
            text = "Accept The First and the Last from Highlord Bolvar Fordragon in Stormwind Keep.",
            complete = QuestState(6182, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.7815, 0.1814, "Highlord Bolvar Fordragon",
                    "Travel to Highlord Bolvar Fordragon."),
            },
        },
        {
            id = "turnin-6182-the-first-and-the-last",
            kind = "turnin",
            priority = 410,
            text = "Turn in The First and the Last to Master Mathias Shaw in SI:7.",
            dependsOn = { "accept-6182-the-first-and-the-last" },
            complete = QuestState(6182, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.7579, 0.5983, "Master Mathias Shaw",
                    "Travel to Master Mathias Shaw."),
            },
        },
        {
            id = "accept-6183-honor-the-dead",
            kind = "accept",
            priority = 420,
            text = "Accept Honor the Dead from Master Mathias Shaw in SI:7.",
            complete = QuestState(6183, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.7579, 0.5983, "Master Mathias Shaw",
                    "Travel to Master Mathias Shaw."),
            },
        },
        {
            id = "turnin-6183-honor-the-dead",
            kind = "turnin",
            priority = 430,
            text = "Turn in Honor the Dead to Master Mathias Shaw in SI:7.",
            dependsOn = { "accept-6183-honor-the-dead" },
            complete = QuestState(6183, "completed"),
            route = {
                Point(MAP.STORMWIND, 0.7579, 0.5983, "Master Mathias Shaw",
                    "Travel to Master Mathias Shaw."),
            },
        },
        {
            id = "accept-6184-flint-shadowmore",
            kind = "accept",
            priority = 440,
            text = "Accept Flint Shadowmore from Master Mathias Shaw in SI:7.",
            complete = QuestState(6184, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.7579, 0.5983, "Master Mathias Shaw",
                    "Travel to Master Mathias Shaw."),
            },
        },
        {
            id = "travel-6185-chillwind-camp",
            kind = "travel",
            priority = 450,
            text = "Travel to Chillwind Camp.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4362, 0.8451, "Chillwind Camp",
                    "Travel to Chillwind Camp."),
            },
        },
        {
            id = "turnin-6184-flint-shadowmore",
            kind = "turnin",
            priority = 460,
            text = "Turn in Flint Shadowmore to Ol' Emma in Chillwind Camp.",
            dependsOn = { "accept-6184-flint-shadowmore" },
            complete = QuestState(6184, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4362, 0.8451, "Ol' Emma",
                    "Travel to Ol' Emma."),
            },
        },
        {
            id = "accept-6185-the-eastern-plagues",
            kind = "accept",
            priority = 470,
            text = "Accept The Eastern Plagues from Flint Shadowmore in Chillwind Camp.",
            complete = QuestState(6185, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4362, 0.8451, "Flint Shadowmore",
                    "Travel to Flint Shadowmore."),
            },
        },
        {
            id = "turnin-5097-all-along-the-watchtowers",
            kind = "turnin",
            priority = 480,
            text = "Turn in All Along the Watchtowers to Commander Ashlam Valorfist in Chillwind Camp.",
            dependsOn = { "objective-5097-1-mark-tower-one", "objective-5097-2-mark-tower-two", "objective-5097-3-mark-tower-three", "objective-5097-4-mark-tower-four" },
            complete = QuestState(5097, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4271, 0.8403, "Commander Ashlam Valorfist",
                    "Travel to Commander Ashlam Valorfist."),
            },
        },
        {
            id = "accept-5533-scholomance",
            kind = "accept",
            priority = 490,
            text = "Accept Scholomance from Commander Ashlam Valorfist in Chillwind Camp.",
            complete = QuestState(5533, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4270, 0.8406, "Commander Ashlam Valorfist",
                    "Travel to Commander Ashlam Valorfist."),
            },
        },
        {
            id = "turnin-5533-scholomance",
            kind = "turnin",
            priority = 500,
            text = "Turn in Scholomance to Alchemist Arbington in Chillwind Camp.",
            dependsOn = { "accept-5533-scholomance" },
            complete = QuestState(5533, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4267, 0.8377, "Alchemist Arbington",
                    "Travel to Alchemist Arbington."),
            },
        },
        {
            id = "accept-5537-skeletal-fragments",
            kind = "accept",
            priority = 510,
            text = "Accept Skeletal Fragments from Alchemist Arbington in Chillwind Camp.",
            complete = QuestState(5537, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4267, 0.8377, "Alchemist Arbington",
                    "Travel to Alchemist Arbington."),
            },
        },
        {
            id = "turnin-5217-return-to-chillwind-camp",
            kind = "turnin",
            priority = 520,
            text = "Turn in Return to Chillwind Camp to High Priestess MacDonnell in Chillwind Camp.",
            dependsOn = { "accept-5217-return-to-chillwind-camp" },
            complete = QuestState(5217, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4296, 0.8446, "High Priestess MacDonnell",
                    "Travel to High Priestess MacDonnell."),
            },
        },
        {
            id = "accept-5219-target-dalson-s-tears",
            kind = "accept",
            priority = 530,
            text = "Accept Target: Dalson's Tears from High Priestess MacDonnell in Chillwind Camp.",
            complete = QuestState(5219, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4296, 0.8446, "High Priestess MacDonnell",
                    "Travel to High Priestess MacDonnell."),
            },
        },
        {
            id = "travel-5021-felstone-field",
            kind = "travel",
            priority = 540,
            text = "Travel to Felstone Field.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3839, 0.5405, "Felstone Field",
                    "Travel to Felstone Field."),
            },
        },
        {
            id = "turnin-5050-good-luck-charm",
            kind = "turnin",
            priority = 550,
            text = "Turn in Good Luck Charm to Janice Felstone in Felstone Field.",
            dependsOn = { "accept-5050-good-luck-charm" },
            complete = QuestState(5050, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3839, 0.5406, "Janice Felstone",
                    "Travel to Janice Felstone."),
            },
        },
        {
            id = "accept-5051-two-halves-become-one",
            kind = "accept",
            priority = 560,
            text = "Accept Two Halves Become One from Janice Felstone in Felstone Field.",
            complete = QuestState(5051, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3839, 0.5406, "Janice Felstone",
                    "Travel to Janice Felstone."),
            },
        },
        {
            id = "objective-5051-1-jabbering-ghoul",
            kind = "objective",
            priority = 570,
            text = "Kill Jabbering Ghoul and collect Good Luck Other-Half-Charm in Felstone Field.",
            dependsOn = { "accept-5051-two-halves-become-one" },
            complete = QuestObjective(5051, 1),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3681, 0.5832, "Jabbering Ghoul",
                    "Travel to Jabbering Ghoul."),
            },
        },
        {
            id = "objective-5051-two-halves-become-one",
            kind = "objective",
            priority = 580,
            text = "Use Good Luck Other-Half-Charm to create Good Luck Charm in Felstone Field.",
            dependsOn = { "accept-5051-two-halves-become-one" },
            complete = QuestState(5051, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3681, 0.5832, "Felstone Field",
                    "Travel to Felstone Field."),
            },
        },
        {
            id = "turnin-5051-two-halves-become-one",
            kind = "turnin",
            priority = 590,
            text = "Turn in Two Halves Become One to Janice Felstone in Felstone Field.",
            dependsOn = { "objective-5051-1-jabbering-ghoul", "objective-5051-two-halves-become-one" },
            complete = QuestState(5051, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.3840, 0.5404, "Janice Felstone",
                    "Travel to Janice Felstone."),
            },
        },
        {
            id = "travel-5219-dalson-s-tears",
            kind = "travel",
            priority = 600,
            text = "Travel to Dalson's Tears.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4780, 0.5070, "Dalson's Tears",
                    "Travel to Dalson's Tears."),
            },
        },
        {
            id = "turnin-5058-mrs-dalson-s-diary",
            kind = "turnin",
            priority = 610,
            text = "Turn in Mrs. Dalson's Diary in Dalson's Tears. This is an elite. Bring a group.",
            complete = QuestState(5058, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4780, 0.5070, "Dalson's Tears",
                    "Travel to Dalson's Tears."),
            },
        },
        {
            id = "objective-5060-wandering-skeleton",
            kind = "objective",
            priority = 620,
            text = "Kill Wandering Skeleton, it should spawn outside the barn after you turn in 'Mrs. Dalson's Diary' and collect the Dalson Outhouse Key.",
            complete = QuestState(5060, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4766, 0.5008, "Wandering Skeleton",
                    "Travel to Wandering Skeleton."),
            },
        },
        {
            id = "turnin-5059-locked-away",
            kind = "turnin",
            priority = 630,
            text = "Turn in Locked Away in Dalson's Tears. This is an elite. Bring a group.",
            complete = QuestState(5059, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4811, 0.4966, "Dalson's Tears",
                    "Travel to Dalson's Tears."),
            },
        },
        {
            id = "objective-5060-farmer-dalson",
            kind = "objective",
            priority = 640,
            text = "Kill Farmer Dalson, he should spawn after turn in 'Locked Away' from the outhouse and. This is an elite. Bring a group.",
            complete = QuestState(5060, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4811, 0.4966, "Farmer Dalson",
                    "Travel to Farmer Dalson."),
            },
        },
        {
            id = "turnin-5060-locked-away",
            kind = "turnin",
            priority = 650,
            text = "Turn in Locked Away in Dalson's Tears. This is an elite. Bring a group.",
            dependsOn = { "objective-5060-wandering-skeleton", "objective-5060-farmer-dalson" },
            complete = QuestState(5060, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4739, 0.4962, "Dalson's Tears",
                    "Travel to Dalson's Tears."),
            },
        },
        {
            id = "objective-5219-target-dalson-s-tears",
            kind = "objective",
            priority = 660,
            text = "Kill Cauldron Lord Malvinious and collect Dalson's Tears Cauldron Key in Dalson's Tears.",
            dependsOn = { "accept-5219-target-dalson-s-tears" },
            complete = QuestState(5219, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4603, 0.5249, "Cauldron Lord Malvinious",
                    "Travel to Cauldron Lord Malvinious."),
            },
        },
        {
            id = "objective-5537-skeletal-fragments",
            kind = "objective",
            priority = 670,
            text = "Kill Skeletal Terror, Skeletal Executioner and collect 15 Skeletal Fragments in Chillwind Camp.",
            dependsOn = { "accept-5537-skeletal-fragments" },
            complete = QuestState(5537, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4267, 0.8377, "Skeletal Terror",
                    "Travel to Skeletal Terror."),
            },
        },
        {
            id = "turnin-5219-target-dalson-s-tears",
            kind = "turnin",
            priority = 680,
            text = "Turn in Target: Dalson's Tears in Dalson's Tears.",
            dependsOn = { "objective-5219-target-dalson-s-tears" },
            complete = QuestState(5219, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4621, 0.5206, "Dalson's Tears",
                    "Travel to Dalson's Tears."),
            },
        },
        {
            id = "accept-5220-return-to-chillwind-camp",
            kind = "accept",
            priority = 690,
            text = "Accept Return to Chillwind Camp in Dalson's Tears.",
            complete = QuestState(5220, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4621, 0.5206, "Dalson's Tears",
                    "Travel to Dalson's Tears."),
            },
        },
        {
            id = "travel-5222-chillwind-camp",
            kind = "travel",
            priority = 700,
            text = "Travel to Chillwind Camp.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4296, 0.8448, "Chillwind Camp",
                    "Travel to Chillwind Camp."),
            },
        },
        {
            id = "turnin-5220-return-to-chillwind-camp",
            kind = "turnin",
            priority = 710,
            text = "Turn in Return to Chillwind Camp to High Priestess MacDonnell in Chillwind Camp.",
            dependsOn = { "accept-5220-return-to-chillwind-camp" },
            complete = QuestState(5220, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4296, 0.8448, "High Priestess MacDonnell",
                    "Travel to High Priestess MacDonnell."),
            },
        },
        {
            id = "accept-5222-target-writhing-haunt",
            kind = "accept",
            priority = 720,
            text = "Accept Target: Writhing Haunt from High Priestess MacDonnell in Chillwind Camp.",
            complete = QuestState(5222, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4296, 0.8448, "High Priestess MacDonnell",
                    "Travel to High Priestess MacDonnell."),
            },
        },
        {
            id = "turnin-5537-skeletal-fragments",
            kind = "turnin",
            priority = 730,
            text = "Turn in Skeletal Fragments to Alchemist Arbington in Chillwind Camp.",
            dependsOn = { "objective-5537-skeletal-fragments" },
            complete = QuestState(5537, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4267, 0.8377, "Alchemist Arbington",
                    "Travel to Alchemist Arbington."),
            },
        },
        {
            id = "travel-5222-the-writhing-haunt",
            kind = "travel",
            priority = 740,
            text = "Travel to The Writhing Haunt.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.5301, 0.6605, "The Writhing Haunt",
                    "Travel to The Writhing Haunt."),
            },
        },
        {
            id = "objective-5222-target-writhing-haunt",
            kind = "objective",
            priority = 750,
            text = "Kill Cauldron Lord Razarch and collect Writhing Haunt Cauldron Key in The Writhing Haunt.",
            dependsOn = { "accept-5222-target-writhing-haunt" },
            complete = QuestState(5222, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.5301, 0.6605, "Cauldron Lord Razarch",
                    "Travel to Cauldron Lord Razarch."),
            },
        },
        {
            id = "turnin-5222-target-writhing-haunt",
            kind = "turnin",
            priority = 760,
            text = "Turn in Target: Writhing Haunt in The Writhing Haunt.",
            dependsOn = { "objective-5222-target-writhing-haunt" },
            complete = QuestState(5222, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.5301, 0.6579, "The Writhing Haunt",
                    "Travel to The Writhing Haunt."),
            },
        },
        {
            id = "accept-5223-return-to-chillwind-camp",
            kind = "accept",
            priority = 770,
            text = "Accept Return to Chillwind Camp in The Writhing Haunt.",
            complete = QuestState(5223, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.5301, 0.6579, "The Writhing Haunt",
                    "Travel to The Writhing Haunt."),
            },
        },
        {
            id = "turnin-5223-return-to-chillwind-camp",
            kind = "turnin",
            priority = 780,
            text = "Turn in Return to Chillwind Camp to High Priestess MacDonnell in Chillwind Camp.",
            dependsOn = { "accept-5223-return-to-chillwind-camp" },
            complete = QuestState(5223, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4297, 0.8448, "High Priestess MacDonnell",
                    "Travel to High Priestess MacDonnell."),
            },
        },
        {
            id = "accept-5225-target-gahrron-s-withering",
            kind = "accept",
            priority = 790,
            text = "Accept Target: Gahrron's Withering from High Priestess MacDonnell in Chillwind Camp.",
            complete = QuestState(5225, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4297, 0.8448, "High Priestess MacDonnell",
                    "Travel to High Priestess MacDonnell."),
            },
        },
        {
            id = "travel-5225-gahrron-s-withering",
            kind = "travel",
            priority = 800,
            text = "Travel to Gahrron's Withering.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.6269, 0.5887, "Gahrron's Withering",
                    "Travel to Gahrron's Withering."),
            },
        },
        {
            id = "objective-5225-target-gahrron-s-withering",
            kind = "objective",
            priority = 810,
            text = "Kill Cauldron Lord Soulwrath and collect Gahrron's Withering Cauldron Key in Gahrron's Withering.",
            dependsOn = { "accept-5225-target-gahrron-s-withering" },
            complete = QuestState(5225, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.6269, 0.5887, "Cauldron Lord Soulwrath",
                    "Travel to Cauldron Lord Soulwrath."),
            },
        },
        {
            id = "turnin-5225-target-gahrron-s-withering",
            kind = "turnin",
            priority = 820,
            text = "Turn in Target: Gahrron's Withering in Gahrron's Withering.",
            dependsOn = { "objective-5225-target-gahrron-s-withering" },
            complete = QuestState(5225, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.6258, 0.5857, "Gahrron's Withering",
                    "Travel to Gahrron's Withering."),
            },
        },
        {
            id = "accept-5226-return-to-chillwind-camp",
            kind = "accept",
            priority = 830,
            text = "Accept Return to Chillwind Camp in Gahrron's Withering.",
            complete = QuestState(5226, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.6258, 0.5857, "Gahrron's Withering",
                    "Travel to Gahrron's Withering."),
            },
        },
        {
            id = "travel-5533-chillwind-camp",
            kind = "travel",
            priority = 840,
            text = "Travel to Chillwind Camp.",
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4296, 0.8447, "Chillwind Camp",
                    "Travel to Chillwind Camp."),
            },
        },
        {
            id = "turnin-5226-return-to-chillwind-camp",
            kind = "turnin",
            priority = 850,
            text = "Turn in Return to Chillwind Camp to High Priestess MacDonnell in Chillwind Camp.",
            dependsOn = { "accept-5226-return-to-chillwind-camp" },
            complete = QuestState(5226, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4296, 0.8447, "High Priestess MacDonnell",
                    "Travel to High Priestess MacDonnell."),
            },
        },
        {
            id = "turnin-5238-mission-accomplished",
            kind = "turnin",
            priority = 860,
            text = "Turn in Mission Accomplished! to Commander Ashlam Valorfist in Chillwind Camp. This is an elite. Bring a group.",
            complete = QuestState(5238, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.4270, 0.8406, "Commander Ashlam Valorfist",
                    "Travel to Commander Ashlam Valorfist."),
            },
        },
    },
})
