local _, ns = ...

-- Library book collection for all classes in WoW Forever.
-- Turn books in to Garion Wendell in Stormwind or Owen Thadd in Undercity.
-- Rumi of Gnomeregan exists in Westfall and Loch Modan but counts once.
-- Deleting a book from your bags may prevent re-looting it.
-- Milestone quests: 78150 (10 books), 79536 (20 books), 82208 (25 books, level 30+).
-- The first 25 loot steps are both-faction books in turn-in order for milestone gating; extra books follow.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    ELWYNN = 1429,
    WESTFALL = 1436,
    DUSKWOOD = 1431,
    LOCH_MODAN = 1432,
    WETLANDS = 1437,
    IRONFORGE = 1455,
    TIRISFAL = 1420,
    SILVERPINE = 1421,
    BARRENS = 1413,
    DARKSHORE = 1439,
    STONETALON = 1442,
    ORGRIMMAR = 1454,
    STV = 1434,
    THOUSAND_NEEDLES = 1441,
    ALTERAC = 1416,
    DUSTWALLOW = 1445,
    ARATHI = 1417,
    DESOLACE = 1443,
    BADLANDS = 1418,
    WPL = 1422,
    EPL = 1423,
    SWAMP_OF_SORROWS = 1435,
    HINTERLANDS = 1425,
    FELWOOD = 1448,
    FERALAS = 1444,
    WINTER_SPRING = 1449,
    BURNING_STEPPES = 1428,
    SEARING_GORGE = 1427,
    AZSHARA = 1447,
    TANARIS = 1446,
    BLASTED_LANDS = 1419,
    STORMWIND = 1453,
    UNDERCITY = 1458,
}

local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "misc-library-books",
    title = "Library Books",
    category = "Miscellaneous Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 1 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "book-theocritus-journal",
            kind = "note",
            priority = 10,
            text = "Loot Archmage Theocritus's Research Journal from the Tower of Azora in Elwynn Forest.",
            complete = QuestState(79092, "completed"),
            route = {
                Point(MAP.ELWYNN, 0.6540, 0.7010, "Archmage Theocritus's Research Journal",
                    "Travel to the Tower of Azora."),
            },
        },
        {
            id = "book-bewitchments-glamours",
            kind = "note",
            priority = 20,
            text = "Loot Bewitchments and Glamours from Moonbrook in Westfall.",
            dependsOn = { "book-theocritus-journal" },
            complete = QuestState(78142, "completed"),
            route = {
                Point(MAP.WESTFALL, 0.4540, 0.7050, "Bewitchments and Glamours",
                    "Travel to Moonbrook."),
            },
        },
        {
            id = "book-rumi-collected-works",
            kind = "note",
            priority = 30,
            text = "Loot Rumi of Gnomeregan: The Collected Works from Sentinel Hill in Westfall or Thelsamar in Loch Modan (counts once).",
            dependsOn = { "book-bewitchments-glamours" },
            complete = QuestState(79093, "completed"),
            route = {
                Point(MAP.WESTFALL, 0.5270, 0.5380, "Rumi of Gnomeregan: The Collected Works",
                    "Travel to Sentinel Hill."),
                Point(MAP.LOCH_MODAN, 0.3560, 0.4890, "Rumi of Gnomeregan: The Collected Works",
                    "Travel to Thelsamar."),
            },
        },
        {
            id = "book-goaz-scrolls",
            kind = "note",
            priority = 40,
            text = "Loot Goaz Scrolls from Whelgar's Excavation Site in the Wetlands.",
            dependsOn = { "book-rumi-collected-works" },
            route = {
                Point(MAP.WETLANDS, 0.3360, 0.4790, "Goaz Scrolls",
                    "Travel to Whelgar's Excavation Site."),
            },
        },
        {
            id = "book-crimes-against-anatomy",
            kind = "note",
            priority = 50,
            text = "Loot Crimes Against Anatomy from Raven Hill Crypt in Duskwood.",
            dependsOn = { "book-goaz-scrolls" },
            route = {
                Point(MAP.DUSKWOOD, 0.1670, 0.2850, "Crimes Against Anatomy",
                    "Travel to Raven Hill Crypt."),
            },
        },
        {
            id = "book-runes-sorcerer-kings",
            kind = "note",
            priority = 60,
            text = "Loot Runes of the Sorcerer-Kings from the ogre cave at Mo'grosh Stronghold in Loch Modan.",
            dependsOn = { "book-crimes-against-anatomy" },
            complete = QuestState(78148, "completed"),
            route = {
                Point(MAP.LOCH_MODAN, 0.7750, 0.1410, "Runes of the Sorcerer-Kings",
                    "Travel to Mo'grosh Stronghold."),
            },
        },
        {
            id = "book-dalaran-digest",
            kind = "note",
            priority = 70,
            text = "Loot The Dalaran Digest, Vol. 23 from Amber Mill in Silverpine Forest.",
            dependsOn = { "book-runes-sorcerer-kings" },
            complete = QuestState(78127, "completed"),
            route = {
                Point(MAP.SILVERPINE, 0.6350, 0.6310, "The Dalaran Digest, Vol. 23",
                    "Travel to Amber Mill."),
            },
        },
        {
            id = "book-arcanic-systems-manual",
            kind = "note",
            priority = 80,
            text = "Loot Arcanic Systems Manual from the Sludge Fen oil rig in the Barrens.",
            dependsOn = { "book-dalaran-digest" },
            complete = QuestState(78145, "completed"),
            route = {
                Point(MAP.BARRENS, 0.5630, 0.0880, "Arcanic Systems Manual",
                    "Travel to the Sludge Fen oil rig."),
            },
        },
        {
            id = "book-secrets-dreamers",
            kind = "note",
            priority = 90,
            text = "Loot Secrets of the Dreamers from the Cavern of Mists near Wailing Caverns (not inside the dungeon).",
            dependsOn = { "book-arcanic-systems-manual" },
            complete = QuestState(78143, "completed"),
            route = {
                Point(MAP.BARRENS, 0.4600, 0.3650, "Cavern of Mists entrance",
                    "Travel to Lushwater Oasis."),
                Point(MAP.BARRENS, 0.5283, 0.5470, "Secrets of the Dreamers",
                    "Enter the cave toward the Cavern of Mists."),
            },
        },
        {
            id = "book-baxtan-destructive-magics",
            kind = "note",
            priority = 100,
            text = "Loot Baxtan: On Destructive Magics from Ratchet in the Barrens.",
            dependsOn = { "book-secrets-dreamers" },
            complete = QuestState(79097, "completed"),
            route = {
                Point(MAP.BARRENS, 0.6270, 0.3630, "Baxtan: On Destructive Magics",
                    "Travel to Ratchet."),
            },
        },
        {
            id = "accept-78150-friend-of-the-library",
            kind = "accept",
            priority = 110,
            text = "Accept Friend of the Library from your faction librarian after enough book turn-ins.",
            dependsOn = { "book-baxtan-destructive-magics" },
            complete = QuestState(78150, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.4900, 0.8630, "Garion Wendell",
                    "Travel to Garion Wendell in Stormwind City."),
                Point(MAP.UNDERCITY, 0.7400, 0.3250, "Owen Thadd",
                    "Travel to Owen Thadd in Undercity."),
            },
        },
        {
            id = "turnin-78150-friend-of-the-library",
            kind = "turnin",
            priority = 111,
            text = "Turn in Friend of the Library to Garion Wendell or Owen Thadd and choose your reward.",
            dependsOn = { "accept-78150-friend-of-the-library" },
            complete = QuestState(78150, "completed"),
            useClientPin = true,
            route = {
                Point(MAP.STORMWIND, 0.3780, 0.8020, "Garion Wendell",
                    "Travel to Garion Wendell in Stormwind City."),
                Point(MAP.UNDERCITY, 0.7360, 0.3250, "Owen Thadd",
                    "Travel to Owen Thadd in Undercity."),
            },
        },
        {
            id = "book-narthalas-almanac",
            kind = "note",
            priority = 130,
            text = "Loot Nar'thalas Almanac, Vol. 74 from the Ruins of Mathystra in Darkshore.",
            dependsOn = { "turnin-78150-friend-of-the-library" },
            complete = QuestState(78124, "completed"),
            route = {
                Point(MAP.DARKSHORE, 0.5960, 0.2220, "Nar'thalas Almanac, Vol. 74",
                    "Travel to the Ruins of Mathystra."),
            },
        },
        {
            id = "book-fury-of-the-land",
            kind = "note",
            priority = 140,
            text = "Loot Fury of the Land from the Grimtotem camp in Stonetalon Mountains.",
            dependsOn = { "book-narthalas-almanac" },
            complete = QuestState(78149, "completed"),
            route = {
                Point(MAP.STONETALON, 0.7440, 0.8570, "Fury of the Land",
                    "Travel to the Grimtotem camp."),
            },
        },
        {
            id = "book-defensive-magics-101",
            kind = "note",
            priority = 150,
            text = "Loot Defensive Magics 101 from the first ogre tower at Gallows' Corner in Alterac Mountains.",
            dependsOn = { "book-fury-of-the-land" },
            complete = QuestState(79948, "completed"),
            route = {
                Point(MAP.ALTERAC, 0.4840, 0.5750, "Defensive Magics 101",
                    "Travel to Gallows' Corner."),
            },
        },
        {
            id = "book-geomancy-stone-cold-truth",
            kind = "note",
            priority = 160,
            text = "Loot Geomancy: The Stone-Cold Truth from Darkcloud Pinnacle in Thousand Needles.",
            dependsOn = { "book-defensive-magics-101" },
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.3190, 0.3850, "Path up Darkcloud Pinnacle",
                    "Travel to the Grimtotem mound."),
                Point(MAP.THOUSAND_NEEDLES, 0.3440, 0.4000, "Geomancy: The Stone-Cold Truth",
                    "Follow the ramps to the main hut."),
            },
        },
        {
            id = "book-basilisks-petrification",
            kind = "note",
            priority = 170,
            text = "Loot Basilisks: Should Petrification be Feared? outside Crystalvein Mine in Stranglethorn Vale.",
            dependsOn = { "book-geomancy-stone-cold-truth" },
            route = {
                Point(MAP.STV, 0.3710, 0.4880, "Path toward Crystalvein Mine",
                    "Travel toward the mine."),
                Point(MAP.STV, 0.4130, 0.5090, "Basilisks: Should Petrification be Feared?",
                    "Follow the path to the platform."),
            },
        },
        {
            id = "book-rwlrwl",
            kind = "note",
            priority = 180,
            text = "Loot RwlRwlRwlRwl! from the murloc camp furnace in Dustwallow Marsh.",
            dependsOn = { "book-basilisks-petrification" },
            route = {
                Point(MAP.DUSTWALLOW, 0.5710, 0.2080, "RwlRwlRwlRwl!",
                    "Travel to Witch Hill."),
            },
        },
        {
            id = "book-web-of-lies",
            kind = "note",
            priority = 190,
            text = "Loot A Web of Lies: Debunking Myths and Legends from Witherbark Village in Arathi Highlands.",
            dependsOn = { "book-rwlrwl" },
            route = {
                Point(MAP.ARATHI, 0.7360, 0.6520, "A Web of Lies: Debunking Myths and Legends",
                    "Travel to Witherbark Village."),
            },
        },
        {
            id = "book-demons-and-you",
            kind = "note",
            priority = 200,
            text = "Loot Demons and You from Thunder Axe Fortress in Desolace.",
            dependsOn = { "book-web-of-lies" },
            route = {
                Point(MAP.DESOLACE, 0.5510, 0.2620, "Demons and You",
                    "Travel to Thunder Axe Fortress."),
            },
        },
        {
            id = "book-mummies-unsavory-undead",
            kind = "note",
            priority = 210,
            text = "Loot Mummies: A Guide to the Unsavory Undead from the crypt south of the Badlands butte.",
            dependsOn = { "book-demons-and-you" },
            route = {
                Point(MAP.BADLANDS, 0.5600, 0.4500, "Path toward the crypt",
                    "Travel toward the southern foothills."),
                Point(MAP.BADLANDS, 0.5670, 0.3970, "Mummies: A Guide to the Unsavory Undead",
                    "Climb to the crypt entrance."),
            },
        },
        {
            id = "book-conjurers-codex",
            kind = "note",
            priority = 220,
            text = "Loot Conjurer's Codex in the Blasted Lands.",
            dependsOn = { "book-mummies-unsavory-undead" },
            route = {
                Point(MAP.BLASTED_LANDS, 0.5540, 0.3220, "Conjurer's Codex",
                    "Travel to the Blasted Lands."),
            },
        },
        {
            id = "accept-79536-greater-friend-ring",
            kind = "accept",
            priority = 230,
            text = "Accept Greater Friend of the Library from your faction librarian after enough book turn-ins.",
            dependsOn = { "book-conjurers-codex" },
            complete = QuestState(79536, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.4900, 0.8630, "Garion Wendell",
                    "Travel to Garion Wendell in Stormwind City."),
                Point(MAP.UNDERCITY, 0.7400, 0.3250, "Owen Thadd",
                    "Travel to Owen Thadd in Undercity."),
            },
        },
        {
            id = "turnin-79536-greater-friend-ring",
            kind = "turnin",
            priority = 231,
            text = "Turn in Greater Friend of the Library to Garion Wendell or Owen Thadd and choose your reward.",
            dependsOn = { "accept-79536-greater-friend-ring" },
            complete = QuestState(79536, "completed"),
            useClientPin = true,
            route = {
                Point(MAP.STORMWIND, 0.3780, 0.8020, "Garion Wendell",
                    "Travel to Garion Wendell in Stormwind City."),
                Point(MAP.UNDERCITY, 0.7360, 0.3250, "Owen Thadd",
                    "Travel to Owen Thadd in Undercity."),
            },
        },
        {
            id = "book-sanguine-sorcery",
            kind = "note",
            priority = 250,
            text = "Loot Sanguine Sorcery from the Temple of Atal'Hakkar ledge in the Swamp of Sorrows (outside the dungeon).",
            dependsOn = { "turnin-79536-greater-friend-ring" },
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.7020, 0.5190, "Sanguine Sorcery",
                    "Travel to the Temple of Atal'Hakkar."),
            },
        },
        {
            id = "book-luddite-demonic-pet",
            kind = "note",
            priority = 260,
            text = "Loot A Luddite's Guide to Caring for Your Demonic Pet from the cage in the Fallow Sanctuary.",
            dependsOn = { "book-sanguine-sorcery" },
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.6100, 0.2200, "A Luddite's Guide to Caring for Your Demonic Pet",
                    "Travel to the Fallow Sanctuary."),
            },
        },
        {
            id = "book-study-of-the-light",
            kind = "note",
            priority = 270,
            text = "Loot A Study of the Light inside Light's Hope Chapel in Eastern Plaguelands.",
            dependsOn = { "book-luddite-demonic-pet" },
            route = {
                Point(MAP.EPL, 0.7180, 0.4820, "A Study of the Light",
                    "Travel to Light's Hope Chapel."),
            },
        },
        {
            id = "book-knight-and-the-lady",
            kind = "note",
            priority = 280,
            text = "Loot The Knight and the Lady from the burnt house by the lake in Eastern Plaguelands.",
            dependsOn = { "book-study-of-the-light" },
            route = {
                Point(MAP.EPL, 0.4730, 0.4230, "The Knight and the Lady",
                    "Travel to the lake house."),
            },
        },
        {
            id = "book-scourge-misunderstood",
            kind = "note",
            priority = 290,
            text = "Loot Scourge: Undead Menace or Misunderstood? from the table before the Stratholme bridge.",
            dependsOn = { "book-knight-and-the-lady" },
            route = {
                Point(MAP.EPL, 0.2660, 0.1450, "Scourge: Undead Menace or Misunderstood?",
                    "Travel to the Stratholme approach."),
            },
        },
        {
            id = "accept-82208-greater-friend-bow",
            kind = "accept",
            priority = 300,
            conditions = { level = { min = 30 } },
            text = "Accept Greater Friend of the Library from your faction librarian after enough book turn-ins.",
            dependsOn = { "book-scourge-misunderstood" },
            complete = QuestState(82208, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND, 0.4900, 0.8630, "Garion Wendell",
                    "Travel to Garion Wendell in Stormwind City."),
                Point(MAP.UNDERCITY, 0.7400, 0.3250, "Owen Thadd",
                    "Travel to Owen Thadd in Undercity."),
            },
        },
        {
            id = "turnin-82208-greater-friend-bow",
            kind = "turnin",
            priority = 301,
            conditions = { level = { min = 30 } },
            text = "Turn in Greater Friend of the Library to Garion Wendell or Owen Thadd and choose your reward.",
            dependsOn = { "accept-82208-greater-friend-bow" },
            complete = QuestState(82208, "completed"),
            useClientPin = true,
            route = {
                Point(MAP.STORMWIND, 0.3780, 0.8020, "Garion Wendell",
                    "Travel to Garion Wendell in Stormwind City."),
                Point(MAP.UNDERCITY, 0.7360, 0.3250, "Owen Thadd",
                    "Travel to Owen Thadd in Undercity."),
            },
        },
        {
            id = "book-antonidas-autobiography",
            kind = "note",
            priority = 320,
            conditions = { faction = "Alliance" },
            text = "Loot Archmage Antonidas: The Unabridged Autobiography from the Hall of Explorers in Ironforge.",
            dependsOn = { "turnin-82208-greater-friend-bow" },
            complete = QuestState(79091, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.7570, 0.1050, "Archmage Antonidas: The Unabridged Autobiography",
                    "Travel to the Hall of Explorers."),
            },
        },
        {
            id = "book-apothecary-primer",
            kind = "note",
            priority = 330,
            conditions = { faction = "Horde" },
            text = "Loot The Apothecary's Metaphysical Primer from the alchemy shop in Brill, Tirisfal Glades.",
            dependsOn = { "book-antonidas-autobiography" },
            complete = QuestState(79095, "completed"),
            route = {
                Point(MAP.TIRISFAL, 0.5940, 0.5230, "The Apothecary's Metaphysical Primer",
                    "Travel to Brill."),
            },
        },
        {
            id = "book-lessons-tazo",
            kind = "note",
            priority = 340,
            conditions = { faction = "Horde" },
            text = "Loot The Lessons of Ta'zo from the tablet at Darkbriar Lodge in Orgrimmar.",
            dependsOn = { "book-apothecary-primer" },
            complete = QuestState(79094, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.3860, 0.7840, "The Lessons of Ta'zo",
                    "Travel to the Valley of Spirits."),
            },
        },
        {
            id = "book-ataeric-arcane-curiosities",
            kind = "note",
            priority = 350,
            conditions = { faction = "Horde" },
            text = "Loot Ataeric: On Arcane Curiosities from the tomb near Sebastian Meloche in Silverpine Forest.",
            dependsOn = { "book-lessons-tazo" },
            route = {
                Point(MAP.SILVERPINE, 0.4340, 0.4120, "Ataeric: On Arcane Curiosities",
                    "Travel to the Sepulcher area."),
            },
        },
        {
            id = "book-liminal-arcane",
            kind = "note",
            priority = 360,
            text = "Loot The Liminal and the Arcane in Feralas.",
            dependsOn = { "book-ataeric-arcane-curiosities" },
            route = {
                Point(MAP.FERALAS, 0.5060, 0.1570, "The Liminal and the Arcane",
                    "Travel to northern Feralas."),
            },
        },
        {
            id = "book-necromancy-101",
            kind = "note",
            priority = 370,
            text = "Loot Necromancy 101 from the top floor near Scholomance in Western Plaguelands (outside the instance).",
            dependsOn = { "book-liminal-arcane" },
            route = {
                Point(MAP.WPL, 0.6918, 0.7227, "Necromancy 101",
                    "Travel to Caer Darrow."),
            },
        },
        {
            id = "book-undead-potatoes",
            kind = "note",
            priority = 380,
            text = "Loot Undead Potatoes from Janice Felstone's farmhouse in Western Plaguelands.",
            dependsOn = { "book-necromancy-101" },
            route = {
                Point(MAP.WPL, 0.3826, 0.5462, "Undead Potatoes",
                    "Travel to Felstone Field."),
            },
        },
        {
            id = "book-venomous-journeys",
            kind = "note",
            priority = 390,
            text = "Loot Venomous Journeys from the pyramid wall in the Hinterlands.",
            dependsOn = { "book-undead-potatoes" },
            complete = QuestState(81954, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.3580, 0.7250, "Venomous Journeys",
                    "Travel to the temple ruins."),
            },
        },
        {
            id = "book-northern-kalimdor-guide",
            kind = "note",
            priority = 400,
            text = "Loot Northern Kalimdor - A Comprehensive Guide inside Timbermaw Hold in Felwood.",
            dependsOn = { "book-venomous-journeys" },
            route = {
                Point(MAP.FELWOOD, 0.6510, 0.0320, "Northern Kalimdor - A Comprehensive Guide",
                    "Travel to Timbermaw Hold."),
            },
        },
        {
            id = "book-ka-boom",
            kind = "note",
            priority = 410,
            text = "Loot Ka-Boom! from Everlook in Winterspring.",
            dependsOn = { "book-northern-kalimdor-guide" },
            route = {
                Point(MAP.WINTER_SPRING, 0.6040, 0.3740, "Ka-Boom!",
                    "Travel to Everlook."),
            },
        },
        {
            id = "book-stonewrought-design",
            kind = "note",
            priority = 420,
            text = "Loot Stonewrought Design from Franclorn Forgewright's chamber in Blackrock Mountain (no dungeon entry).",
            dependsOn = { "book-ka-boom" },
            complete = QuestState(81953, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.3110, 0.3010, "Stonewrought Design",
                    "Travel to Blackrock Mountain."),
            },
        },
        {
            id = "book-magma-or-lava",
            kind = "note",
            priority = 430,
            text = "Loot Magma or Lava? on the platform before the Blackrock Depths entrance in Blackrock Mountain.",
            dependsOn = { "book-stonewrought-design" },
            complete = QuestState(84396, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.3110, 0.3010, "Magma or Lava?",
                    "Travel past the summoning stone toward Lothos Riftwaker."),
            },
        },
        {
            id = "book-mind-of-metal",
            kind = "note",
            priority = 440,
            text = "Loot A Mind of Metal from the tent in Searing Gorge.",
            dependsOn = { "book-magma-or-lava" },
            complete = QuestState(81955, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.3810, 0.4980, "A Mind of Metal",
                    "Travel to the Dark Iron camp."),
            },
        },
        {
            id = "book-everyday-etiquette",
            kind = "note",
            priority = 450,
            text = "Loot Everyday Etiquette north of the Azshara flight path.",
            dependsOn = { "book-mind-of-metal" },
            route = {
                Point(MAP.AZSHARA, 0.2040, 0.6230, "Everyday Etiquette",
                    "Travel north from the flight path."),
            },
        },
        {
            id = "book-legends-tidesages",
            kind = "note",
            priority = 460,
            text = "Loot Legends of the Tidesages from Lost Rigger Cove in Tanaris.",
            dependsOn = { "book-everyday-etiquette" },
            route = {
                Point(MAP.TANARIS, 0.7260, 0.4780, "Legends of the Tidesages",
                    "Travel to Lost Rigger Cove."),
            },
        },
    },
})
