local _, ns = ...

-- Horde Era leveling route for the Arathi Highlands, levels 37-38.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    ARATHI = 1417,
    UNDERCITY = 1458,
    STRANGLETHORN = 1434,
    HILLSBRAD = 1424,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-37-38-arathi-highlands",
    title = "37-38 Arathi Highlands (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Horde" },
            { level = { min = 37 } },
        },
    },
    goals = {
        {
            id = "accept-1164-to-steal-from-thieves",
            kind = "accept",
            priority = 20,
            text = "Accept To Steal From Thieves from Genavie Callow in Trade Quarter.",
            complete = QuestState(1164, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.6376, 0.4917, "Genavie Callow",
                    "Travel to Genavie Callow."),
            },
        },
        {
            id = "accept-638-trollbane",
            kind = "accept",
            priority = 40,
            text = "Accept Trollbane from Nimboya in Grom'gol Base Camp.",
            complete = QuestState(638, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3217, 0.2771, "Nimboya",
                    "Travel to Nimboya."),
            },
        },
        {
            id = "accept-676-the-hammer-may-fall",
            kind = "accept",
            priority = 60,
            text = "Accept The Hammer May Fall from Tallow in Tarren Mill.",
            complete = QuestState(676, "activeOrCompleted"),
            route = {
                Point(MAP.HILLSBRAD, 0.6190, 0.1970, "Tallow",
                    "Travel to Tallow."),
            },
        },
        {
            id = "accept-655-hammerfall",
            kind = "accept",
            priority = 80,
            text = "Accept Hammerfall from Gor'mul in Hammerfall.",
            complete = QuestState(655, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7268, 0.3404, "Gor'mul",
                    "Travel to Gor'mul."),
            },
        },
        {
            id = "turnin-655-hammerfall",
            kind = "turnin",
            priority = 90,
            text = "Turn in Hammerfall to Tor'gan in Hammerfall.",
            dependsOn = { "accept-655-hammerfall" },
            complete = QuestState(655, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7465, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "accept-672-raising-spirits",
            kind = "accept",
            priority = 100,
            text = "Accept Raising Spirits from Tor'gan in Hammerfall.",
            complete = QuestState(672, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7465, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "note-671-hammerfall",
            kind = "note",
            priority = 110,
            text = "Set your hearth in Hammerfall with Innkeeper Adegwa.",
            route = {
                Point(MAP.ARATHI, 0.7380, 0.3260, "Innkeeper Adegwa",
                    "Travel to Innkeeper Adegwa."),
            },
        },
        {
            id = "objective-672-raising-spirits",
            kind = "objective",
            priority = 120,
            text = "Kill Highland Strider and collect 10 Highland Raptor Eye west of Hammerfall.",
            dependsOn = { "accept-672-raising-spirits" },
            complete = QuestState(672, "complete"),
            route = {
                Point(MAP.ARATHI, 0.6400, 0.3700, "Highland Strider",
                    "Travel to Highland Strider."),
            },
        },
        {
            id = "turnin-672-raising-spirits",
            kind = "turnin",
            priority = 130,
            text = "Turn in Raising Spirits to Tor'gan in Hammerfall.",
            dependsOn = { "objective-672-raising-spirits" },
            complete = QuestState(672, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7465, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "accept-674-raising-spirits",
            kind = "accept",
            priority = 140,
            text = "Accept Raising Spirits from Tor'gan in Hammerfall.",
            complete = QuestState(674, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7465, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "turnin-674-raising-spirits",
            kind = "turnin",
            priority = 150,
            text = "Turn in Raising Spirits to Gor'mul in Hammerfall.",
            dependsOn = { "accept-674-raising-spirits" },
            complete = QuestState(674, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7268, 0.3404, "Gor'mul",
                    "Travel to Gor'mul."),
            },
        },
        {
            id = "accept-675-raising-spirits",
            kind = "accept",
            priority = 160,
            text = "Accept Raising Spirits from Gor'mul in Hammerfall.",
            complete = QuestState(675, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7268, 0.3404, "Gor'mul",
                    "Travel to Gor'mul."),
            },
        },
        {
            id = "turnin-675-raising-spirits",
            kind = "turnin",
            priority = 170,
            text = "Turn in Raising Spirits to Tor'gan in Hammerfall.",
            dependsOn = { "accept-675-raising-spirits" },
            complete = QuestState(675, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7465, 0.3634, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "accept-639-sigil-of-strom",
            kind = "accept",
            priority = 180,
            conditions = {
                all = {
                    { quest = { id = 638, state = "completed" } },
                },
            },
            text = "Accept Sigil of Strom from Zengu in Hammerfall.",
            complete = QuestState(639, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7381, 0.3387, "Zengu",
                    "Travel to Zengu."),
            },
        },
        {
            id = "accept-671-foul-magics",
            kind = "accept",
            priority = 190,
            text = "Accept Foul Magics from Tor'gan in Hammerfall.",
            complete = QuestState(671, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7461, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "accept-701-guile-of-the-raptor",
            kind = "accept",
            priority = 200,
            text = "Accept Guile of the Raptor from Tor'gan in Hammerfall.",
            complete = QuestState(701, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7461, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "accept-642-the-princess-trapped",
            kind = "accept",
            priority = 210,
            text = "Accept The Princess Trapped in Hammerfall.",
            complete = QuestState(642, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.6250, 0.3380, "Hammerfall",
                    "Travel to Hammerfall."),
            },
        },
        {
            id = "objective-642-the-princess-trapped",
            kind = "objective",
            priority = 220,
            text = "Kill Drywhisker and collect 12 Mote of Myzrael in the cave southeast of Hammerfall.",
            dependsOn = { "accept-642-the-princess-trapped" },
            complete = QuestState(642, "complete"),
            route = {
                Point(MAP.ARATHI, 0.7800, 0.3700, "Drywhisker Kobold",
                    "Travel to Drywhisker Kobold."),
            },
        },
        {
            id = "turnin-642-the-princess-trapped",
            kind = "turnin",
            priority = 230,
            text = "Turn in The Princess Trapped in Drywhisker Gorge.",
            dependsOn = { "objective-642-the-princess-trapped" },
            complete = QuestState(642, "completed"),
            route = {
                Point(MAP.ARATHI, 0.8430, 0.3090, "Drywhisker Gorge",
                    "Travel to Drywhisker Gorge."),
            },
        },
        {
            id = "accept-651-stones-of-binding",
            kind = "accept",
            priority = 240,
            text = "Accept Stones of Binding in Drywhisker Gorge.",
            complete = QuestState(651, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.8430, 0.3090, "Drywhisker Gorge",
                    "Travel to Drywhisker Gorge."),
            },
        },
        {
            id = "objective-651-3-cresting-key",
            kind = "objective",
            priority = 260,
            text = "Get the Cresting Key in Circle of Outer Binding.",
            dependsOn = { "accept-651-stones-of-binding" },
            complete = QuestObjective(651, 3),
            route = {
                Point(MAP.ARATHI, 0.6680, 0.2970, "Circle of Outer Binding",
                    "Travel to Circle of Outer Binding."),
            },
        },
        {
            id = "objective-651-2-thundering-key",
            kind = "objective",
            priority = 280,
            text = "Get the Thundering Key in Circle of East Binding.",
            dependsOn = { "accept-651-stones-of-binding" },
            complete = QuestObjective(651, 2),
            route = {
                Point(MAP.ARATHI, 0.5210, 0.5070, "Circle of East Binding",
                    "Travel to Circle of East Binding."),
            },
        },
        {
            id = "objective-701-guile-of-the-raptor",
            kind = "objective",
            priority = 290,
            text = "Kill Highland Fleshstalker for 12 Raptor Heart in Arathi Highlands.",
            dependsOn = { "accept-701-guile-of-the-raptor" },
            complete = QuestState(701, "complete"),
            route = {
                Point(MAP.ARATHI, 0.5300, 0.7000, "Highland Fleshstalker",
                    "Travel to Highland Fleshstalker."),
            },
        },
        {
            id = "objective-676-the-hammer-may-fall",
            kind = "objective",
            priority = 300,
            text = "Kill 8 Boulderfist Ogre and 10 Boulderfist Enforcer in Arathi Highlands.",
            dependsOn = { "accept-676-the-hammer-may-fall" },
            complete = QuestState(676, "complete"),
            route = {
                Point(MAP.ARATHI, 0.3400, 0.4500, "Boulderfist Ogre",
                    "Travel to Boulderfist Ogre."),
            },
        },
        {
            id = "objective-671-foul-magics",
            kind = "objective",
            priority = 320,
            text = "Kill Syndicate Pathstalker, Syndicate Mercenary and Syndicate Highwayman at Northfold Manor for 10 Bloodstone Amulet.",
            dependsOn = { "accept-671-foul-magics" },
            complete = QuestState(671, "complete"),
            route = {
                Point(MAP.ARATHI, 0.3100, 0.2800, "Syndicate Pathstalker",
                    "Travel to Syndicate Pathstalker."),
            },
        },
        {
            id = "objective-651-1-burning-key",
            kind = "objective",
            priority = 340,
            text = "Get the Burning Key in Circle of West Binding.",
            dependsOn = { "accept-651-stones-of-binding" },
            complete = QuestObjective(651, 1),
            route = {
                Point(MAP.ARATHI, 0.2540, 0.3030, "Circle of West Binding",
                    "Travel to Circle of West Binding."),
            },
        },
        {
            id = "objective-639-sigil-of-strom",
            kind = "objective",
            priority = 360,
            conditions = {
                all = {
                    { quest = { id = 638, state = "completed" } },
                },
            },
            text = "Kill Syndicate Prowler or Syndicate Conjuror until you find Sigil of Strom in Stromgarde Keep This is a group quest only and safe to skip.",
            dependsOn = { "accept-639-sigil-of-strom" },
            complete = QuestState(639, "complete"),
            route = {
                Point(MAP.ARATHI, 0.2628, 0.6259, "Syndicate Prowler",
                    "Travel to Syndicate Prowler."),
            },
        },
        {
            id = "turnin-651-stones-of-binding",
            kind = "turnin",
            priority = 380,
            text = "Turn in Stones of Binding in Circle of Inner Binding.",
            dependsOn = { "objective-651-3-cresting-key", "objective-651-2-thundering-key", "objective-651-1-burning-key" },
            complete = QuestState(651, "completed"),
            route = {
                Point(MAP.ARATHI, 0.3620, 0.5750, "Circle of Inner Binding",
                    "Travel to Circle of Inner Binding."),
            },
        },
        {
            id = "accept-652-breaking-the-keystone",
            kind = "accept",
            priority = 390,
            text = "Accept Breaking the Keystone in Circle of Inner Binding.",
            complete = QuestState(652, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.3613, 0.5742, "Circle of Inner Binding",
                    "Travel to Circle of Inner Binding."),
            },
        },
        {
            id = "objective-652-breaking-the-keystone",
            kind = "objective",
            priority = 400,
            text = "Find and kill Fozruk in Refuge Pointe This is a group quest and not possible to solo. Safe to skip.",
            dependsOn = { "accept-652-breaking-the-keystone" },
            complete = QuestState(652, "complete"),
            route = {
                Point(MAP.ARATHI, 0.4281, 0.5359, "Fozruk",
                    "Travel to Fozruk."),
            },
        },
        {
            id = "turnin-652-breaking-the-keystone",
            kind = "turnin",
            priority = 410,
            text = "Turn in Breaking the Keystone in Circle of Inner Binding.",
            dependsOn = { "objective-652-breaking-the-keystone" },
            complete = QuestState(652, "completed"),
            route = {
                Point(MAP.ARATHI, 0.3611, 0.5793, "Circle of Inner Binding",
                    "Travel to Circle of Inner Binding."),
            },
        },
        {
            id = "turnin-671-foul-magics",
            kind = "turnin",
            priority = 430,
            text = "Turn in Foul Magics to Tor'gan in Hammerfall.",
            dependsOn = { "objective-671-foul-magics" },
            complete = QuestState(671, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7461, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "turnin-676-the-hammer-may-fall",
            kind = "turnin",
            priority = 440,
            text = "Turn in The Hammer May Fall to Drum Fel in Hammerfall.",
            dependsOn = { "objective-676-the-hammer-may-fall" },
            complete = QuestState(676, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7427, 0.3382, "Drum Fel",
                    "Travel to Drum Fel."),
            },
        },
        {
            id = "accept-677-call-to-arms",
            kind = "accept",
            priority = 450,
            text = "Accept Call to Arms from Drum Fel in Hammerfall.",
            complete = QuestState(677, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7427, 0.3382, "Drum Fel",
                    "Travel to Drum Fel."),
            },
        },
        {
            id = "turnin-701-guile-of-the-raptor",
            kind = "turnin",
            priority = 460,
            text = "Turn in Guile of the Raptor to Tor'gan in Hammerfall.",
            dependsOn = { "objective-701-guile-of-the-raptor" },
            complete = QuestState(701, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7461, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "accept-702-guile-of-the-raptor",
            kind = "accept",
            priority = 470,
            text = "Accept Guile of the Raptor from Tor'gan in Hammerfall.",
            complete = QuestState(702, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7461, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "turnin-702-guile-of-the-raptor",
            kind = "turnin",
            priority = 480,
            text = "Turn in Guile of the Raptor to Gor'mul in Hammerfall.",
            dependsOn = { "accept-702-guile-of-the-raptor" },
            complete = QuestState(702, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7267, 0.3400, "Gor'mul",
                    "Travel to Gor'mul."),
            },
        },
        {
            id = "accept-847-guile-of-the-raptor",
            kind = "accept",
            priority = 490,
            text = "Accept Guile of the Raptor from Gor'mul in Hammerfall.",
            complete = QuestState(847, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7267, 0.3400, "Gor'mul",
                    "Travel to Gor'mul."),
            },
        },
        {
            id = "turnin-847-guile-of-the-raptor",
            kind = "turnin",
            priority = 500,
            text = "Turn in Guile of the Raptor to Tor'gan in Hammerfall.",
            dependsOn = { "accept-847-guile-of-the-raptor" },
            complete = QuestState(847, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7461, 0.3632, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "objective-677-call-to-arms",
            kind = "objective",
            priority = 510,
            text = "Kill 10 Witherbark Axe Thrower, 10 Witherbark Headhunter and 8 Witherbark Witch Doctor in Witherbark Village.",
            dependsOn = { "accept-677-call-to-arms" },
            complete = QuestState(677, "complete"),
            route = {
                Point(MAP.ARATHI, 0.7210, 0.6438, "Witherbark Axe Thrower",
                    "Travel to Witherbark Axe Thrower."),
            },
        },
        {
            id = "turnin-677-call-to-arms",
            kind = "turnin",
            priority = 530,
            text = "Turn in Call to Arms to Drum Fel in Hammerfall.",
            dependsOn = { "objective-677-call-to-arms" },
            complete = QuestState(677, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7420, 0.3386, "Drum Fel",
                    "Travel to Drum Fel."),
            },
        },
        {
            id = "accept-678-call-to-arms",
            kind = "accept",
            priority = 540,
            text = "Accept Call to Arms from Drum Fel in Hammerfall.",
            complete = QuestState(678, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7420, 0.3386, "Drum Fel",
                    "Travel to Drum Fel."),
            },
        },
        {
            id = "objective-678-call-to-arms",
            kind = "objective",
            priority = 560,
            text = "Kill 10 Boulderfist Brute and 4 Boulderfist Magus in Boulderfist Hall.",
            dependsOn = { "accept-678-call-to-arms" },
            complete = QuestState(678, "complete"),
            route = {
                Point(MAP.ARATHI, 0.5396, 0.7213, "Boulderfist Brute",
                    "Travel to Boulderfist Brute."),
            },
        },
        {
            id = "turnin-678-call-to-arms",
            kind = "turnin",
            priority = 580,
            text = "Turn in Call to Arms to Drum Fel in Hammerfall.",
            dependsOn = { "objective-678-call-to-arms" },
            complete = QuestState(678, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7422, 0.3377, "Drum Fel",
                    "Travel to Drum Fel."),
            },
        },
        {
            id = "accept-663-land-ho",
            kind = "accept",
            priority = 600,
            text = "Accept Land Ho! from Lolo the Lookout in Faldir's Cove.",
            complete = QuestState(663, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.3172, 0.8267, "Lolo the Lookout",
                    "Travel to Lolo the Lookout."),
            },
        },
        {
            id = "turnin-663-land-ho",
            kind = "turnin",
            priority = 610,
            text = "Turn in Land Ho! to Shakes O'Breen in Faldir's Cove.",
            dependsOn = { "accept-663-land-ho" },
            complete = QuestState(663, "completed"),
            route = {
                Point(MAP.ARATHI, 0.3222, 0.8145, "Shakes O'Breen",
                    "Travel to Shakes O'Breen."),
            },
        },
        {
            id = "accept-662-deep-sea-salvage",
            kind = "accept",
            priority = 620,
            text = "Accept Deep Sea Salvage from First Mate Nilzlix in Faldir's Cove.",
            complete = QuestState(662, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.3265, 0.8153, "First Mate Nilzlix",
                    "Travel to First Mate Nilzlix."),
            },
        },
        {
            id = "accept-664-drowned-sorrows",
            kind = "accept",
            priority = 630,
            text = "Accept Drowned Sorrows from Captain Steelgut in Faldir's Cove.",
            complete = QuestState(664, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.3395, 0.8073, "Captain Steelgut",
                    "Travel to Captain Steelgut."),
            },
        },
        {
            id = "accept-665-sunken-treasure",
            kind = "accept",
            priority = 640,
            text = "Accept Sunken Treasure from Professor Phizzlethorpe in Faldir's Cove.",
            complete = QuestState(665, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.3395, 0.8073, "Professor Phizzlethorpe",
                    "Travel to Professor Phizzlethorpe."),
            },
        },
        {
            id = "objective-665-sunken-treasure",
            kind = "objective",
            priority = 650,
            text = "Escort Professor Phizzlethorpe to the cave and back in Faldir's Cove, this is a difficult quest, stay outside the cave and kill 2 level 40 Vengeful Surge Kill one Vengeful Surge at a time and let Professor Phizzlethorpe tank the other, he can take a decent amount of damage.",
            dependsOn = { "accept-665-sunken-treasure" },
            complete = QuestState(665, "complete"),
            route = {
                Point(MAP.ARATHI, 0.3500, 0.8076, "Professor Phizzlethorpe",
                    "Travel to Professor Phizzlethorpe."),
            },
        },
        {
            id = "turnin-665-sunken-treasure",
            kind = "turnin",
            priority = 660,
            text = "Turn in Sunken Treasure to Doctor Draxlegauge in Faldir's Cove.",
            dependsOn = { "objective-665-sunken-treasure" },
            complete = QuestState(665, "completed"),
            route = {
                Point(MAP.ARATHI, 0.3383, 0.8056, "Doctor Draxlegauge",
                    "Travel to Doctor Draxlegauge."),
            },
        },
        {
            id = "accept-666-sunken-treasure",
            kind = "accept",
            priority = 670,
            text = "Accept Sunken Treasure from Doctor Draxlegauge in Faldir's Cove.",
            complete = QuestState(666, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.3383, 0.8056, "Doctor Draxlegauge",
                    "Travel to Doctor Draxlegauge."),
            },
        },
        {
            id = "objective-662-goggles-of-gem-hunting",
            kind = "objective",
            priority = 680,
            text = "Equip Goggles of Gem Hunting to help you collect Elven Gem.",
            dependsOn = { "accept-662-deep-sea-salvage" },
            complete = QuestState(662, "complete"),
        },
        {
            id = "objective-662-2-maiden-s-folly-log",
            kind = "objective",
            priority = 690,
            text = "Collect Maiden's Folly Log in The Drowned Reef, Head down the stairs from the deck, the log is a large brown book sitting in a cauldron Use Elixir of Water Breathing if you have it.",
            dependsOn = { "accept-662-deep-sea-salvage" },
            complete = QuestObjective(662, 2),
            route = {
                Point(MAP.ARATHI, 0.2342, 0.8516, "The Drowned Reef",
                    "Travel to The Drowned Reef."),
            },
        },
        {
            id = "objective-662-1-maiden-s-folly-charts",
            kind = "objective",
            priority = 700,
            text = "Collect Maiden's Folly Charts in the centre of the ship, looks like a square parchment, in The Drowned Reef.",
            dependsOn = { "accept-662-deep-sea-salvage" },
            complete = QuestObjective(662, 1),
            route = {
                Point(MAP.ARATHI, 0.2301, 0.8447, "The Drowned Reef",
                    "Travel to The Drowned Reef."),
            },
        },
        {
            id = "objective-662-4-spirit-of-silverpine-log",
            kind = "objective",
            priority = 710,
            text = "Collect Spirit of Silverpine Log in The Drowned Reef, head down the stairs from the deck, looks like a square parchment.",
            dependsOn = { "accept-662-deep-sea-salvage" },
            complete = QuestObjective(662, 4),
            route = {
                Point(MAP.ARATHI, 0.2063, 0.8507, "The Drowned Reef",
                    "Travel to The Drowned Reef."),
            },
        },
        {
            id = "objective-662-3-spirit-of-silverpine-charts",
            kind = "objective",
            priority = 720,
            text = "Collect Spirit of Silverpine Charts in The Drowned Reef, It lies on the seabed within the bottom floor of the ship. Looks like an open blue book.",
            dependsOn = { "accept-662-deep-sea-salvage" },
            complete = QuestObjective(662, 3),
            route = {
                Point(MAP.ARATHI, 0.2038, 0.8556, "The Drowned Reef",
                    "Travel to The Drowned Reef."),
            },
        },
        {
            id = "objective-666-sunken-treasure",
            kind = "objective",
            priority = 730,
            text = "Use Goggles of Gem Hunting and collect 10 Elven Gem in The Drowned Reef.",
            dependsOn = { "accept-666-sunken-treasure" },
            complete = QuestState(666, "complete"),
            route = {
                Point(MAP.ARATHI, 0.2244, 0.8371, "The Drowned Reef",
                    "Travel to The Drowned Reef."),
            },
        },
        {
            id = "objective-664-drowned-sorrows",
            kind = "objective",
            priority = 740,
            text = "Kill 10 Daggerspine Raider and 3 Daggerspine Sorceress in The Drowned Reef.",
            dependsOn = { "accept-664-drowned-sorrows" },
            complete = QuestState(664, "complete"),
            route = {
                Point(MAP.ARATHI, 0.2205, 0.8505, "Daggerspine Raider",
                    "Travel to Daggerspine Raider."),
            },
        },
        {
            id = "turnin-662-deep-sea-salvage",
            kind = "turnin",
            priority = 760,
            text = "Turn in Deep Sea Salvage to First Mate Nilzlix in Faldir's Cove.",
            dependsOn = { "objective-662-goggles-of-gem-hunting", "objective-662-2-maiden-s-folly-log", "objective-662-1-maiden-s-folly-charts", "objective-662-4-spirit-of-silverpine-log", "objective-662-3-spirit-of-silverpine-charts" },
            complete = QuestState(662, "completed"),
            route = {
                Point(MAP.ARATHI, 0.3260, 0.8154, "First Mate Nilzlix",
                    "Travel to First Mate Nilzlix."),
            },
        },
        {
            id = "turnin-664-drowned-sorrows",
            kind = "turnin",
            priority = 770,
            text = "Turn in Drowned Sorrows to Captain Steelgut in Faldir's Cove.",
            dependsOn = { "objective-664-drowned-sorrows" },
            complete = QuestState(664, "completed"),
            route = {
                Point(MAP.ARATHI, 0.3394, 0.8080, "Captain Steelgut",
                    "Travel to Captain Steelgut."),
            },
        },
        {
            id = "turnin-666-sunken-treasure",
            kind = "turnin",
            priority = 780,
            text = "Turn in Sunken Treasure to Doctor Draxlegauge in Faldir's Cove.",
            dependsOn = { "objective-666-sunken-treasure" },
            complete = QuestState(666, "completed"),
            route = {
                Point(MAP.ARATHI, 0.3383, 0.8050, "Doctor Draxlegauge",
                    "Travel to Doctor Draxlegauge."),
            },
        },
        {
            id = "accept-668-sunken-treasure",
            kind = "accept",
            priority = 790,
            text = "Accept Sunken Treasure from Doctor Draxlegauge in Faldir's Cove.",
            complete = QuestState(668, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.3383, 0.8050, "Doctor Draxlegauge",
                    "Travel to Doctor Draxlegauge."),
            },
        },
        {
            id = "turnin-668-sunken-treasure",
            kind = "turnin",
            priority = 800,
            text = "Turn in Sunken Treasure to Shakes O'Breen in Faldir's Cove.",
            dependsOn = { "accept-668-sunken-treasure" },
            complete = QuestState(668, "completed"),
            route = {
                Point(MAP.ARATHI, 0.3231, 0.8152, "Shakes O'Breen",
                    "Travel to Shakes O'Breen."),
            },
        },
        {
            id = "accept-669-sunken-treasure",
            kind = "accept",
            priority = 810,
            text = "Accept Sunken Treasure from Shakes O'Breen in Faldir's Cove.",
            complete = QuestState(669, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.3231, 0.8152, "Shakes O'Breen",
                    "Travel to Shakes O'Breen."),
            },
        },
        {
            id = "accept-679-call-to-arms",
            kind = "accept",
            priority = 820,
            text = "Accept Call to Arms from Drum Fel in Hammerfall.",
            complete = QuestState(679, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7422, 0.3377, "Drum Fel",
                    "Travel to Drum Fel."),
            },
        },
        {
            id = "accept-640-the-broken-sigil",
            kind = "accept",
            priority = 830,
            text = "Accept The Broken Sigil from Zengu in Hammerfall.",
            complete = QuestState(640, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7384, 0.3395, "Zengu",
                    "Travel to Zengu."),
            },
        },
        {
            id = "accept-680-the-real-threat",
            kind = "accept",
            priority = 840,
            text = "Accept The Real Threat from Korin Fel in Hammerfall.",
            complete = QuestState(680, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7403, 0.3316, "Korin Fel",
                    "Travel to Korin Fel."),
            },
        },
        {
            id = "accept-673-foul-magics",
            kind = "accept",
            priority = 850,
            text = "Accept Foul Magics from Tor'gan in Hammerfall.",
            complete = QuestState(673, "activeOrCompleted"),
            route = {
                Point(MAP.ARATHI, 0.7465, 0.3627, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "objective-640-the-broken-sigil",
            kind = "objective",
            priority = 860,
            text = "Collect 11 Sigil Fragment from the defenders in Stromgarde Keep.",
            dependsOn = { "accept-640-the-broken-sigil" },
            complete = QuestState(640, "complete"),
            route = {
                Point(MAP.ARATHI, 0.2370, 0.5912, "Stromgarde Troll Hunter",
                    "Travel to Stromgarde Troll Hunter."),
            },
        },
        {
            id = "objective-673-foul-magics",
            kind = "objective",
            priority = 870,
            text = "Kill Marez Cowl and collect Befouled Bloodstone Orb in Stromgarde Keep.",
            dependsOn = { "accept-673-foul-magics" },
            complete = QuestState(673, "complete"),
            route = {
                Point(MAP.ARATHI, 0.2895, 0.6109, "Marez Cowl",
                    "Travel to Marez Cowl."),
            },
        },
        {
            id = "objective-680-the-real-threat",
            kind = "objective",
            priority = 880,
            text = "Kill Or'Kalar and collect Or'Kalar's Head in Stromgarde Keep.",
            dependsOn = { "accept-680-the-real-threat" },
            complete = QuestState(680, "complete"),
            route = {
                Point(MAP.ARATHI, 0.2085, 0.6493, "Or'Kalar",
                    "Travel to Or'Kalar."),
            },
        },
        {
            id = "objective-679-1-call-to-arms",
            kind = "objective",
            priority = 890,
            text = "Kill 15 Boulderfist Shaman and 10 Boulderfist Lord in Stromgarde Keep.",
            dependsOn = { "accept-679-call-to-arms" },
            complete = QuestObjective(679, 1),
            route = {
                Point(MAP.ARATHI, 0.1890, 0.6750, "Boulderfist Shaman",
                    "Travel to Boulderfist Shaman."),
            },
        },
        {
            id = "turnin-679-call-to-arms",
            kind = "turnin",
            priority = 910,
            text = "Turn in Call to Arms to Drum Fel in Hammerfall.",
            dependsOn = { "objective-679-1-call-to-arms" },
            complete = QuestState(679, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7416, 0.3382, "Drum Fel",
                    "Travel to Drum Fel."),
            },
        },
        {
            id = "turnin-680-the-real-threat",
            kind = "turnin",
            priority = 920,
            text = "Turn in The Real Threat to Korin Fel in Hammerfall.",
            dependsOn = { "objective-680-the-real-threat" },
            complete = QuestState(680, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7405, 0.3322, "Korin Fel",
                    "Travel to Korin Fel."),
            },
        },
        {
            id = "turnin-640-the-broken-sigil",
            kind = "turnin",
            priority = 930,
            text = "Turn in The Broken Sigil to Tor'gan in Hammerfall.",
            dependsOn = { "objective-640-the-broken-sigil" },
            complete = QuestState(640, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7469, 0.3646, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
        {
            id = "turnin-673-foul-magics",
            kind = "turnin",
            priority = 940,
            text = "Turn in Foul Magics to Tor'gan in Hammerfall.",
            dependsOn = { "objective-673-foul-magics" },
            complete = QuestState(673, "completed"),
            route = {
                Point(MAP.ARATHI, 0.7469, 0.3646, "Tor'gan",
                    "Travel to Tor'gan."),
            },
        },
    },
})
