local _, ns = ...

-- Horde Era leveling route for Stranglethorn Vale, levels 38-40.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    STRANGLETHORN = 1434,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-38-40-stranglethorn-vale",
    title = "38-40 Stranglethorn Vale (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Horde" },
            { level = { min = 38 } },
        },
    },
    goals = {
        {
            id = "accept-583-welcome-to-the-jungle",
            kind = "accept",
            priority = 30,
            text = "Accept Welcome to the Jungle from Barnil Stonepot in Nesingwary's Expedition.",
            complete = QuestState(583, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3568, 0.1052, "Barnil Stonepot",
                    "Travel to Barnil Stonepot."),
            },
        },
        {
            id = "turnin-583-welcome-to-the-jungle",
            kind = "turnin",
            priority = 40,
            text = "Turn in Welcome to the Jungle to Hemet Nesingwary Jr. in Nesingwary's Expedition.",
            dependsOn = { "accept-583-welcome-to-the-jungle" },
            complete = QuestState(583, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1075, "Hemet Nesingwary Jr.",
                    "Travel to Hemet Nesingwary Jr.."),
            },
        },
        {
            id = "accept-185-tiger-mastery",
            kind = "accept",
            priority = 50,
            text = "Accept Tiger Mastery from Ajeck Rouack in Nesingwary's Expedition.",
            complete = QuestState(185, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3559, 0.1064, "Ajeck Rouack",
                    "Travel to Ajeck Rouack."),
            },
        },
        {
            id = "accept-190-panther-mastery",
            kind = "accept",
            priority = 60,
            text = "Accept Panther Mastery from Sir S. J. Erlgadin in Nesingwary's Expedition.",
            complete = QuestState(190, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3556, 0.1057, "Sir S. J. Erlgadin",
                    "Travel to Sir S. J. Erlgadin."),
            },
        },
        {
            id = "accept-194-raptor-mastery",
            kind = "accept",
            priority = 70,
            text = "Accept Raptor Mastery from Hemet Nesingwary Jr. in Nesingwary's Expedition.",
            complete = QuestState(194, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1075, "Hemet Nesingwary Jr.",
                    "Travel to Hemet Nesingwary Jr.."),
            },
        },
        {
            id = "objective-185-tiger-mastery",
            kind = "objective",
            priority = 80,
            text = "Kill 10 Young Stranglethorn Tiger slightly to the east in Stranglethorn Vale.",
            dependsOn = { "accept-185-tiger-mastery" },
            complete = QuestState(185, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3500, 0.1400, "Young Stranglethorn Tiger",
                    "Travel to Young Stranglethorn Tiger."),
            },
        },
        {
            id = "turnin-185-tiger-mastery",
            kind = "turnin",
            priority = 90,
            text = "Turn in Tiger Mastery to Ajeck Rouack in Nesingwary's Expedition.",
            dependsOn = { "objective-185-tiger-mastery" },
            complete = QuestState(185, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3559, 0.1064, "Ajeck Rouack",
                    "Travel to Ajeck Rouack."),
            },
        },
        {
            id = "accept-186-tiger-mastery",
            kind = "accept",
            priority = 100,
            text = "Accept Tiger Mastery from Ajeck Rouack in Nesingwary's Expedition.",
            complete = QuestState(186, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3559, 0.1064, "Ajeck Rouack",
                    "Travel to Ajeck Rouack."),
            },
        },
        {
            id = "objective-190-panther-mastery",
            kind = "objective",
            priority = 110,
            text = "Kill 10 Young Panther to the north in Stranglethorn Vale.",
            dependsOn = { "accept-190-panther-mastery" },
            complete = QuestState(190, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.4100, 0.0900, "Young Panther",
                    "Travel to Young Panther."),
            },
        },
        {
            id = "objective-186-tiger-mastery",
            kind = "objective",
            priority = 120,
            text = "Kill 10 Stranglethorn Tiger east of the camp in Stranglethorn Vale.",
            dependsOn = { "accept-186-tiger-mastery" },
            complete = QuestState(186, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3000, 0.1500, "Stranglethorn Tiger",
                    "Travel to Stranglethorn Tiger."),
            },
        },
        {
            id = "turnin-190-panther-mastery",
            kind = "turnin",
            priority = 130,
            text = "Turn in Panther Mastery to Sir S. J. Erlgadin in Nesingwary's Expedition.",
            dependsOn = { "objective-190-panther-mastery" },
            complete = QuestState(190, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3556, 0.1057, "Sir S. J. Erlgadin",
                    "Travel to Sir S. J. Erlgadin."),
            },
        },
        {
            id = "accept-191-panther-mastery",
            kind = "accept",
            priority = 140,
            text = "Accept Panther Mastery from Sir S. J. Erlgadin in Nesingwary's Expedition.",
            complete = QuestState(191, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3556, 0.1057, "Sir S. J. Erlgadin",
                    "Travel to Sir S. J. Erlgadin."),
            },
        },
        {
            id = "turnin-186-tiger-mastery",
            kind = "turnin",
            priority = 150,
            text = "Turn in Tiger Mastery to Ajeck Rouack in Nesingwary's Expedition.",
            dependsOn = { "objective-186-tiger-mastery" },
            complete = QuestState(186, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3559, 0.1064, "Ajeck Rouack",
                    "Travel to Ajeck Rouack."),
            },
        },
        {
            id = "accept-187-tiger-mastery",
            kind = "accept",
            priority = 160,
            text = "Accept Tiger Mastery from Ajeck Rouack in Nesingwary's Expedition.",
            complete = QuestState(187, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3559, 0.1064, "Ajeck Rouack",
                    "Travel to Ajeck Rouack."),
            },
        },
        {
            id = "objective-191-panther-mastery",
            kind = "objective",
            priority = 170,
            text = "Kill 10 Panther east of the camp in Stranglethorn Vale.",
            dependsOn = { "accept-191-panther-mastery" },
            complete = QuestState(191, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2900, 0.1100, "Panther",
                    "Travel to Panther."),
            },
        },
        {
            id = "objective-194-raptor-mastery",
            kind = "objective",
            priority = 180,
            text = "Kill 10 Stranglethorn Raptor east near the ruins in Stranglethorn Vale.",
            dependsOn = { "accept-194-raptor-mastery" },
            complete = QuestState(194, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2800, 0.1400, "Stranglethorn Raptor",
                    "Travel to Stranglethorn Raptor."),
            },
        },
        {
            id = "turnin-194-raptor-mastery",
            kind = "turnin",
            priority = 190,
            text = "Turn in Raptor Mastery to Hemet Nesingwary Jr. in Nesingwary's Expedition.",
            dependsOn = { "objective-194-raptor-mastery" },
            complete = QuestState(194, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1075, "Hemet Nesingwary Jr.",
                    "Travel to Hemet Nesingwary Jr.."),
            },
        },
        {
            id = "accept-195-raptor-mastery",
            kind = "accept",
            priority = 200,
            text = "Accept Raptor Mastery from Hemet Nesingwary Jr. in Nesingwary's Expedition.",
            complete = QuestState(195, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1075, "Hemet Nesingwary Jr.",
                    "Travel to Hemet Nesingwary Jr.."),
            },
        },
        {
            id = "turnin-191-panther-mastery",
            kind = "turnin",
            priority = 210,
            text = "Turn in Panther Mastery to Sir S. J. Erlgadin in Nesingwary's Expedition.",
            dependsOn = { "objective-191-panther-mastery" },
            complete = QuestState(191, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3556, 0.1057, "Sir S. J. Erlgadin",
                    "Travel to Sir S. J. Erlgadin."),
            },
        },
        {
            id = "accept-1181-goblin-sponsorship",
            kind = "accept",
            priority = 230,
            conditions = {
                all = {
                    { quest = { id = 1180, state = "completed" } },
                },
            },
            text = "Accept Goblin Sponsorship from Wharfmaster Lozgil in Booty Bay.",
            complete = QuestState(1181, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2633, 0.7349, "Wharfmaster Lozgil",
                    "Travel to Wharfmaster Lozgil."),
            },
        },
        {
            id = "note-605-booty-bay",
            kind = "note",
            priority = 240,
            text = "Set your hearth in Booty Bay with Innkeeper Skindle.",
            route = {
                Point(MAP.STRANGLETHORN, 0.2710, 0.7730, "Innkeeper Skindle",
                    "Travel to Innkeeper Skindle."),
            },
        },
        {
            id = "accept-605-singing-blue-shards",
            kind = "accept",
            priority = 250,
            text = "Accept Singing Blue Shards from Crank Fizzlebub in The Salty Sailor Tavern.",
            complete = QuestState(605, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2710, 0.7729, "Crank Fizzlebub",
                    "Travel to Crank Fizzlebub."),
            },
        },
        {
            id = "accept-189-bloodscalp-ears",
            kind = "accept",
            priority = 260,
            text = "Accept Bloodscalp Ears from Kebok in The Salty Sailor Tavern.",
            complete = QuestState(189, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2701, 0.7718, "Kebok",
                    "Travel to Kebok."),
            },
        },
        {
            id = "accept-213-hostile-takeover",
            kind = "accept",
            priority = 270,
            text = "Accept Hostile Takeover from Kebok in The Salty Sailor Tavern.",
            complete = QuestState(213, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2701, 0.7718, "Kebok",
                    "Travel to Kebok."),
            },
        },
        {
            id = "accept-201-investigate-the-camp",
            kind = "accept",
            priority = 280,
            text = "Accept Investigate the Camp from Krazek in The Salty Sailor Tavern.",
            complete = QuestState(201, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2699, 0.7723, "Krazek",
                    "Travel to Krazek."),
            },
        },
        {
            id = "accept-575-supply-and-demand",
            kind = "accept",
            priority = 290,
            text = "Accept Supply and Demand from Drizzlik in Booty Bay.",
            complete = QuestState(575, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2825, 0.7757, "Drizzlik",
                    "Travel to Drizzlik."),
            },
        },
        {
            id = "turnin-1181-goblin-sponsorship",
            kind = "turnin",
            priority = 300,
            conditions = {
                all = {
                    { quest = { id = 1180, state = "completed" } },
                },
            },
            text = "Turn in Goblin Sponsorship to Baron Revilgaz in Booty Bay.",
            dependsOn = { "accept-1181-goblin-sponsorship" },
            complete = QuestState(1181, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2720, 0.7690, "Baron Revilgaz",
                    "Travel to Baron Revilgaz."),
            },
        },
        {
            id = "accept-1182-goblin-sponsorship",
            kind = "accept",
            priority = 310,
            conditions = {
                all = {
                    { quest = { id = 1180, state = "completed" } },
                },
            },
            text = "Accept Goblin Sponsorship from Baron Revilgaz in Booty Bay.",
            complete = QuestState(1182, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2721, 0.7690, "Baron Revilgaz",
                    "Travel to Baron Revilgaz."),
            },
        },
        {
            id = "accept-568-the-defense-of-grom-gol",
            kind = "accept",
            priority = 320,
            text = "Accept The Defense of Grom'gol from Commander Aggro'gosh in Grom'gol Base Camp.",
            complete = QuestState(568, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3222, 0.2891, "Commander Aggro'gosh",
                    "Travel to Commander Aggro'gosh."),
            },
        },
        {
            id = "accept-570-mok-thardin-s-enchantment",
            kind = "accept",
            priority = 330,
            text = "Accept Mok'thardin's Enchantment from Far Seer Mok'thardin in Grom'gol Base Camp.",
            complete = QuestState(570, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3214, 0.2916, "Far Seer Mok'thardin",
                    "Travel to Far Seer Mok'thardin."),
            },
        },
        {
            id = "accept-581-hunt-for-yenniku",
            kind = "accept",
            priority = 340,
            text = "Accept Hunt for Yenniku from Nimboya in Grom'gol Base Camp.",
            complete = QuestState(581, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2778, "Nimboya",
                    "Travel to Nimboya."),
            },
        },
        {
            id = "accept-638-trollbane",
            kind = "accept",
            priority = 350,
            text = "Accept Trollbane from Nimboya in Grom'gol Base Camp.",
            complete = QuestState(638, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2778, "Nimboya",
                    "Travel to Nimboya."),
            },
        },
        {
            id = "accept-596-bloody-bone-necklaces",
            kind = "accept",
            priority = 360,
            text = "Accept Bloody Bone Necklaces from Kin'weelay in Grom'gol Base Camp.",
            complete = QuestState(596, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3223, 0.2777, "Kin'weelay",
                    "Travel to Kin'weelay."),
            },
        },
        {
            id = "accept-629-the-vile-reef",
            kind = "accept",
            priority = 370,
            text = "Accept The Vile Reef from Kin'weelay in Grom'gol Base Camp.",
            complete = QuestState(629, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3223, 0.2777, "Kin'weelay",
                    "Travel to Kin'weelay."),
            },
        },
        {
            id = "objective-605-singing-blue-shards",
            kind = "objective",
            priority = 380,
            text = "Find Stone Maw Basilisk and collect some Singing Crystal Shard, you can complete this later, if you can't find crocs The Savage Coast.",
            dependsOn = { "accept-605-singing-blue-shards" },
            complete = QuestState(605, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3700, 0.0800, "Stone Maw Basilisk",
                    "Travel to Stone Maw Basilisk."),
            },
        },
        {
            id = "objective-189-bloodscalp-ears",
            kind = "objective",
            priority = 400,
            text = "Kill the Bloodscalp trolls and collect 15 Bloodscalp Ear in Bal'lal Ruins.",
            dependsOn = { "accept-189-bloodscalp-ears" },
            complete = QuestState(189, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2952, 0.2087, "Bloodscalp Warrior",
                    "Travel to Bloodscalp Warrior."),
            },
        },
        {
            id = "objective-581-hunt-for-yenniku",
            kind = "objective",
            priority = 410,
            text = "Kill Bloodscalp trolls and collect 9 Bloodscalp Tusk in Bal'lal Ruins.",
            dependsOn = { "accept-581-hunt-for-yenniku" },
            complete = QuestState(581, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2900, 0.1961, "Bloodscalp Warrior",
                    "Travel to Bloodscalp Warrior."),
            },
        },
        {
            id = "objective-187-tiger-mastery",
            kind = "objective",
            priority = 430,
            text = "Kill 10 Elder Stranglethorn Tiger between the troll ruins and Nessingwary's camp.",
            dependsOn = { "accept-187-tiger-mastery" },
            complete = QuestState(187, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3400, 0.1900, "Elder Stranglethorn Tiger",
                    "Travel to Elder Stranglethorn Tiger."),
            },
        },
        {
            id = "objective-195-raptor-mastery",
            kind = "objective",
            priority = 440,
            text = "Kill 10 Lashtail Raptor near Grom'gol Base Camp.",
            dependsOn = { "accept-195-raptor-mastery" },
            complete = QuestState(195, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3800, 0.2300, "Lashtail Raptor",
                    "Travel to Lashtail Raptor."),
            },
        },
        {
            id = "objective-568-the-defense-of-grom-gol",
            kind = "objective",
            priority = 450,
            text = "Kill 15 Lashtail Raptor in Stranglethorn Vale.",
            dependsOn = { "accept-568-the-defense-of-grom-gol" },
            complete = QuestState(568, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3800, 0.2300, "Lashtail Raptor",
                    "Travel to Lashtail Raptor."),
            },
        },
        {
            id = "turnin-581-hunt-for-yenniku",
            kind = "turnin",
            priority = 470,
            text = "Turn in Hunt for Yenniku to Nimboya in Grom'gol Base Camp.",
            dependsOn = { "objective-581-hunt-for-yenniku" },
            complete = QuestState(581, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2778, "Nimboya",
                    "Travel to Nimboya."),
            },
        },
        {
            id = "accept-582-headhunting",
            kind = "accept",
            priority = 480,
            text = "Accept Headhunting from Nimboya in Grom'gol Base Camp.",
            complete = QuestState(582, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2778, "Nimboya",
                    "Travel to Nimboya."),
            },
        },
        {
            id = "turnin-568-the-defense-of-grom-gol",
            kind = "turnin",
            priority = 490,
            text = "Turn in The Defense of Grom'gol to Commander Aggro'gosh in Grom'gol Base Camp.",
            dependsOn = { "objective-568-the-defense-of-grom-gol" },
            complete = QuestState(568, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3222, 0.2891, "Commander Aggro'gosh",
                    "Travel to Commander Aggro'gosh."),
            },
        },
        {
            id = "accept-569-the-defense-of-grom-gol",
            kind = "accept",
            priority = 500,
            text = "Accept The Defense of Grom'gol from Commander Aggro'gosh in Grom'gol Base Camp.",
            complete = QuestState(569, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3222, 0.2891, "Commander Aggro'gosh",
                    "Travel to Commander Aggro'gosh."),
            },
        },
        {
            id = "objective-582-headhunting",
            kind = "objective",
            priority = 510,
            text = "Follow the path and kill Bloodscalp Headhunter in Ruins of Zul'Kunda 20 Shrunken Head Note: only Bloodscalp Headhunter will drop the item.",
            dependsOn = { "accept-582-headhunting" },
            complete = QuestState(582, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2465, 0.0995, "Continue toward Headhunting",
                    "Continue toward Headhunting."),
                Point(MAP.STRANGLETHORN, 0.2752, 0.0958, "Continue toward Headhunting",
                    "Continue toward Headhunting."),
                Point(MAP.STRANGLETHORN, 0.2752, 0.0958, "Continue toward Headhunting",
                    "Continue toward Headhunting."),
                Point(MAP.STRANGLETHORN, 0.2724, 0.1024, "Continue toward Headhunting",
                    "Continue toward Headhunting."),
                Point(MAP.STRANGLETHORN, 0.2656, 0.0831, "Continue toward Headhunting",
                    "Continue toward Headhunting."),
                Point(MAP.STRANGLETHORN, 0.2628, 0.0795, "Continue toward Headhunting",
                    "Continue toward Headhunting."),
                Point(MAP.STRANGLETHORN, 0.2475, 0.0803, "Bloodscalp Headhunter",
                    "Travel to Bloodscalp Headhunter."),
            },
        },
        {
            id = "objective-596-bloody-bone-necklaces",
            kind = "objective",
            priority = 520,
            text = "Kill Trolls in the Zuuldaia Ruins to collect 25 Bloody Bone Necklace.",
            dependsOn = { "accept-596-bloody-bone-necklaces" },
            complete = QuestState(596, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.1900, 0.1400, "Bloodscalp Axe Thrower",
                    "Travel to Bloodscalp Axe Thrower."),
            },
        },
        {
            id = "objective-201-investigate-the-camp",
            kind = "objective",
            priority = 540,
            text = "In Nesingwary's Expedition.",
            dependsOn = { "accept-201-investigate-the-camp" },
            complete = QuestState(201, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3526, 0.1112, "Nesingwary's Expedition",
                    "Travel to Nesingwary's Expedition."),
            },
        },
        {
            id = "turnin-195-raptor-mastery",
            kind = "turnin",
            priority = 550,
            text = "Turn in Raptor Mastery to Hemet Nesingwary Jr. in Nesingwary's Expedition.",
            dependsOn = { "objective-195-raptor-mastery" },
            complete = QuestState(195, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3562, 0.1079, "Hemet Nesingwary Jr.",
                    "Travel to Hemet Nesingwary Jr.."),
            },
        },
        {
            id = "accept-196-raptor-mastery",
            kind = "accept",
            priority = 560,
            text = "Accept Raptor Mastery from Hemet Nesingwary Jr. in Nesingwary's Expedition.",
            complete = QuestState(196, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3562, 0.1079, "Hemet Nesingwary Jr.",
                    "Travel to Hemet Nesingwary Jr.."),
            },
        },
        {
            id = "accept-192-panther-mastery",
            kind = "accept",
            priority = 570,
            text = "Accept Panther Mastery from Sir S. J. Erlgadin in Nesingwary's Expedition.",
            complete = QuestState(192, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3559, 0.1058, "Sir S. J. Erlgadin",
                    "Travel to Sir S. J. Erlgadin."),
            },
        },
        {
            id = "objective-605-singing-blue-shards-2",
            kind = "objective",
            priority = 580,
            text = "Find Crystal Spine Basilisk and collect some Singing Crystal Shard in The Savage Coast, if you can't find anymore crocs.",
            dependsOn = { "accept-605-singing-blue-shards" },
            complete = QuestState(605, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2422, 0.1765, "Crystal Spine Basilisk",
                    "Travel to Crystal Spine Basilisk."),
            },
        },
        {
            id = "objective-188-tiger-mastery",
            kind = "objective",
            priority = 590,
            text = "Kill Sin'Dall who is on top of a nearby hill and collect Paw of Sin'Dall.",
            dependsOn = { "accept-188-tiger-mastery" },
            complete = QuestState(188, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3186, 0.1732, "Sin'Dall",
                    "Travel to Sin'Dall."),
            },
        },
        {
            id = "turnin-188-tiger-mastery",
            kind = "turnin",
            priority = 600,
            text = "Turn in Tiger Mastery to Ajeck Rouack in Nesingwary's Expedition.",
            dependsOn = { "objective-188-tiger-mastery" },
            complete = QuestState(188, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3561, 0.1066, "Ajeck Rouack",
                    "Travel to Ajeck Rouack."),
            },
        },
        {
            id = "objective-575-supply-and-demand",
            kind = "objective",
            priority = 610,
            text = "Kill River Crocolisk and collect 2 Large River Crocolisk Skin in Nesingwary's Expedition.",
            dependsOn = { "accept-575-supply-and-demand" },
            complete = QuestState(575, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3482, 0.1040, "River Crocolisk",
                    "Travel to River Crocolisk."),
            },
        },
        {
            id = "objective-1182-foreman-cozzle",
            kind = "objective",
            priority = 630,
            conditions = {
                all = {
                    { quest = { id = 1180, state = "completed" } },
                },
            },
            text = "Kill Foreman Cozzle to collect Cozzle's Key in Venture Co. Operations Center.",
            dependsOn = { "accept-1182-goblin-sponsorship" },
            complete = QuestState(1182, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.4248, 0.1847, "Foreman Cozzle",
                    "Travel to Foreman Cozzle."),
            },
        },
        {
            id = "objective-1182-goblin-sponsorship",
            kind = "objective",
            priority = 640,
            conditions = {
                all = {
                    { quest = { id = 1180, state = "completed" } },
                },
            },
            text = "Use Cozzle's Key to open Cozzle's Footlocker and get Fuel Regulator Blueprints.",
            dependsOn = { "accept-1182-goblin-sponsorship" },
            complete = QuestState(1182, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.4300, 0.2000, "Foreman Cozzle",
                    "Travel to Foreman Cozzle."),
            },
        },
        {
            id = "objective-213-hostile-takeover",
            kind = "objective",
            priority = 660,
            text = "Kill Venture Co. Geologist and collect 8 Tumbled Crystal from in Venture Co. Base Camp.",
            dependsOn = { "accept-213-hostile-takeover" },
            complete = QuestState(213, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.4457, 0.2058, "Venture Co. Geologist",
                    "Travel to Venture Co. Geologist."),
            },
        },
        {
            id = "objective-570-mok-thardin-s-enchantment",
            kind = "objective",
            priority = 670,
            text = "Kill Shadowmaw Panther to collect 8 Shadowmaw Claw and kill Stranglethorn Tigress to collect a Pristine Tigress Fang.",
            dependsOn = { "accept-570-mok-thardin-s-enchantment" },
            complete = QuestState(570, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.4800, 0.2100, "Shadowmaw Panther",
                    "Travel to Shadowmaw Panther."),
            },
        },
        {
            id = "objective-192-panther-mastery",
            kind = "objective",
            priority = 690,
            text = "Kill 10 Shadowmaw Panther in Stranglethorn Vale.",
            dependsOn = { "accept-192-panther-mastery" },
            complete = QuestState(192, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.4800, 0.2100, "Continue toward Panther Mastery",
                    "Continue toward Panther Mastery."),
                Point(MAP.STRANGLETHORN, 0.3800, 0.3700, "Shadowmaw Panther",
                    "Travel to Shadowmaw Panther."),
            },
        },
        {
            id = "objective-605-singing-blue-shards-3",
            kind = "objective",
            priority = 700,
            text = "Find Crystal Spine Basilisk or Stone Maw Basilisk and collect 10 Singing Crystal Shard in The Savage Coast.",
            dependsOn = { "accept-605-singing-blue-shards" },
            complete = QuestState(605, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2422, 0.1765, "Continue toward Singing Blue Shards",
                    "Continue toward Singing Blue Shards."),
                Point(MAP.STRANGLETHORN, 0.3700, 0.0800, "Crystal Spine Basilisk",
                    "Travel to Crystal Spine Basilisk."),
            },
        },
        {
            id = "objective-569-the-defense-of-grom-gol",
            kind = "objective",
            priority = 720,
            text = "Kill 10 Mosh'Ogg Brute and 5 Mosh'Ogg Witch Doctor southeast of Grom'gol at the Mizjah Ruins.",
            dependsOn = { "accept-569-the-defense-of-grom-gol" },
            complete = QuestState(569, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3600, 0.3000, "Mosh'Ogg Brute",
                    "Travel to Mosh'Ogg Brute."),
            },
        },
        {
            id = "turnin-192-panther-mastery",
            kind = "turnin",
            priority = 740,
            text = "Turn in Panther Mastery to Sir S. J. Erlgadin in Nesingwary's Expedition.",
            dependsOn = { "objective-192-panther-mastery" },
            complete = QuestState(192, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3553, 0.1056, "Sir S. J. Erlgadin",
                    "Travel to Sir S. J. Erlgadin."),
            },
        },
        {
            id = "accept-193-panther-mastery",
            kind = "accept",
            priority = 750,
            text = "Accept Panther Mastery from Sir S. J. Erlgadin in Nesingwary's Expedition.",
            complete = QuestState(193, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3553, 0.1056, "Sir S. J. Erlgadin",
                    "Travel to Sir S. J. Erlgadin."),
            },
        },
        {
            id = "turnin-605-singing-blue-shards",
            kind = "turnin",
            priority = 770,
            text = "Turn in Singing Blue Shards to Crank Fizzlebub in The Salty Sailor Tavern.",
            dependsOn = { "objective-605-singing-blue-shards", "objective-605-singing-blue-shards-2", "objective-605-singing-blue-shards-3" },
            complete = QuestState(605, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2710, 0.7729, "Crank Fizzlebub",
                    "Travel to Crank Fizzlebub."),
            },
        },
        {
            id = "turnin-189-bloodscalp-ears",
            kind = "turnin",
            priority = 780,
            text = "Turn in Bloodscalp Ears to Kebok in The Salty Sailor Tavern.",
            dependsOn = { "objective-189-bloodscalp-ears" },
            complete = QuestState(189, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2701, 0.7718, "Kebok",
                    "Travel to Kebok."),
            },
        },
        {
            id = "accept-209-skullsplitter-tusks",
            kind = "accept",
            priority = 790,
            text = "Accept Skullsplitter Tusks from Kebok in The Salty Sailor Tavern.",
            complete = QuestState(209, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2699, 0.7713, "Kebok",
                    "Travel to Kebok."),
            },
        },
        {
            id = "turnin-213-hostile-takeover",
            kind = "turnin",
            priority = 800,
            text = "Turn in Hostile Takeover to Kebok in The Salty Sailor Tavern.",
            dependsOn = { "objective-213-hostile-takeover" },
            complete = QuestState(213, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2701, 0.7718, "Kebok",
                    "Travel to Kebok."),
            },
        },
        {
            id = "turnin-201-investigate-the-camp",
            kind = "turnin",
            priority = 810,
            text = "Turn in Investigate the Camp to Krazek in The Salty Sailor Tavern.",
            dependsOn = { "objective-201-investigate-the-camp" },
            complete = QuestState(201, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2699, 0.7723, "Krazek",
                    "Travel to Krazek."),
            },
        },
        {
            id = "turnin-575-supply-and-demand",
            kind = "turnin",
            priority = 820,
            text = "Turn in Supply and Demand to Drizzlik in Booty Bay.",
            dependsOn = { "objective-575-supply-and-demand" },
            complete = QuestState(575, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2827, 0.7755, "Drizzlik",
                    "Travel to Drizzlik."),
            },
        },
        {
            id = "turnin-1182-goblin-sponsorship",
            kind = "turnin",
            priority = 830,
            conditions = {
                all = {
                    { quest = { id = 1180, state = "completed" } },
                },
            },
            text = "Turn in Goblin Sponsorship.",
            dependsOn = { "objective-1182-foreman-cozzle", "objective-1182-goblin-sponsorship" },
            complete = QuestState(1182, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2720, 0.7690, "Goblin Sponsorship",
                    "Travel to Goblin Sponsorship."),
            },
        },
        {
            id = "accept-1183-goblin-sponsorship",
            kind = "accept",
            priority = 840,
            conditions = {
                all = {
                    { quest = { id = 1180, state = "completed" } },
                },
            },
            text = "Accept Goblin Sponsorship from Baron Revilgaz in Booty Bay.",
            complete = QuestState(1183, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2721, 0.7690, "Baron Revilgaz",
                    "Travel to Baron Revilgaz."),
            },
        },
        {
            id = "turnin-187-tiger-mastery",
            kind = "turnin",
            priority = 860,
            text = "Turn in Tiger Mastery to Ajeck Rouack in Nesingwary's Expedition.",
            dependsOn = { "objective-187-tiger-mastery" },
            complete = QuestState(187, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3561, 0.1066, "Ajeck Rouack",
                    "Travel to Ajeck Rouack."),
            },
        },
        {
            id = "accept-188-tiger-mastery",
            kind = "accept",
            priority = 870,
            text = "Accept Tiger Mastery from Ajeck Rouack in Nesingwary's Expedition.",
            complete = QuestState(188, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3561, 0.1066, "Ajeck Rouack",
                    "Travel to Ajeck Rouack."),
            },
        },
        {
            id = "turnin-569-the-defense-of-grom-gol",
            kind = "turnin",
            priority = 890,
            text = "Turn in The Defense of Grom'gol to Commander Aggro'gosh in Grom'gol Base Camp.",
            dependsOn = { "objective-569-the-defense-of-grom-gol" },
            complete = QuestState(569, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3218, 0.2882, "Commander Aggro'gosh",
                    "Travel to Commander Aggro'gosh."),
            },
        },
        {
            id = "turnin-570-mok-thardin-s-enchantment",
            kind = "turnin",
            priority = 900,
            text = "Turn in Mok'thardin's Enchantment to Far Seer Mok'thardin in Grom'gol Base Camp.",
            dependsOn = { "objective-570-mok-thardin-s-enchantment" },
            complete = QuestState(570, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3214, 0.2916, "Far Seer Mok'thardin",
                    "Travel to Far Seer Mok'thardin."),
            },
        },
        {
            id = "accept-572-mok-thardin-s-enchantment",
            kind = "accept",
            priority = 910,
            text = "Accept Mok'thardin's Enchantment from Far Seer Mok'thardin in Grom'gol Base Camp.",
            complete = QuestState(572, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3214, 0.2916, "Far Seer Mok'thardin",
                    "Travel to Far Seer Mok'thardin."),
            },
        },
        {
            id = "turnin-582-headhunting",
            kind = "turnin",
            priority = 920,
            text = "Turn in Headhunting to Nimboya in Grom'gol Base Camp.",
            dependsOn = { "objective-582-headhunting" },
            complete = QuestState(582, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2778, "Nimboya",
                    "Travel to Nimboya."),
            },
        },
        {
            id = "turnin-596-bloody-bone-necklaces",
            kind = "turnin",
            priority = 930,
            text = "Turn in Bloody Bone Necklaces to Kin'weelay in Grom'gol Base Camp.",
            dependsOn = { "objective-596-bloody-bone-necklaces" },
            complete = QuestState(596, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3223, 0.2777, "Kin'weelay",
                    "Travel to Kin'weelay."),
            },
        },
        {
            id = "accept-638-trollbane-2",
            kind = "accept",
            priority = 940,
            text = "Accept Trollbane from Nimboya in Grom'gol Base Camp.",
            complete = QuestState(638, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3217, 0.2771, "Nimboya",
                    "Travel to Nimboya."),
            },
        },
        {
            id = "accept-595-the-bloodsail-buccaneers",
            kind = "accept",
            priority = 960,
            text = "Accept The Bloodsail Buccaneers from First Mate Crazz in Booty Bay.",
            complete = QuestState(595, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2811, 0.7613, "First Mate Crazz",
                    "Travel to First Mate Crazz."),
            },
        },
        {
            id = "accept-606-scaring-shaky",
            kind = "accept",
            priority = 970,
            text = "Accept Scaring Shaky from \"Sea Wolf\" MacKinley in Booty Bay.",
            complete = QuestState(606, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2776, 0.7712, "'Sea Wolf' MacKinley",
                    "Travel to 'Sea Wolf' MacKinley."),
            },
        },
        {
            id = "note-1116-booty-bay",
            kind = "note",
            priority = 980,
            text = "Set your hearth in Booty Bay with Innkeeper Skindle.",
            route = {
                Point(MAP.STRANGLETHORN, 0.2710, 0.7730, "Innkeeper Skindle",
                    "Travel to Innkeeper Skindle."),
            },
        },
        {
            id = "accept-1116-dream-dust-in-the-swamp",
            kind = "accept",
            priority = 990,
            conditions = {
                all = {
                    { quest = { id = 1115, state = "completed" } },
                },
            },
            text = "Accept Dream Dust in the Swamp from Krazek in The Salty Sailor Tavern.",
            complete = QuestState(1116, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2698, 0.7723, "Krazek",
                    "Travel to Krazek."),
            },
        },
        {
            id = "accept-670-sunken-treasure",
            kind = "accept",
            priority = 1000,
            conditions = {
                all = {
                    { quest = { id = 669, state = "completed" } },
                },
            },
            text = "Accept Sunken Treasure from Fleet Master Seahorn in Booty Bay.",
            complete = QuestState(670, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2717, 0.7700, "Fleet Master Seahorn",
                    "Travel to Fleet Master Seahorn."),
            },
        },
        {
            id = "accept-1261-marg-speaks",
            kind = "accept",
            priority = 1010,
            conditions = {
                all = {
                    { quest = { id = 1240, state = "completed" } },
                },
            },
            text = "Accept Marg Speaks in Grom'gol Base Camp.",
            complete = QuestState(1261, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3220, 0.2770, "Grom'gol Base Camp",
                    "Travel to Grom'gol Base Camp."),
            },
        },
        {
            id = "objective-572-mok-thardin-s-enchantment",
            kind = "objective",
            priority = 1030,
            text = "Kill Jungle Stalker for 10 Jungle Stalker Feather in Gurubashi Arena.",
            dependsOn = { "accept-572-mok-thardin-s-enchantment" },
            complete = QuestState(572, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3100, 0.4100, "Jungle Stalker",
                    "Travel to Jungle Stalker."),
            },
        },
        {
            id = "objective-196-raptor-mastery",
            kind = "objective",
            priority = 1040,
            text = "Kill 10 Jungle Stalker in Gurubashi Arena.",
            dependsOn = { "accept-196-raptor-mastery" },
            complete = QuestState(196, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3151, 0.4233, "Jungle Stalker",
                    "Travel to Jungle Stalker."),
            },
        },
        {
            id = "turnin-572-mok-thardin-s-enchantment",
            kind = "turnin",
            priority = 1060,
            text = "Turn in Mok'thardin's Enchantment to Far Seer Mok'thardin in Grom'gol Base Camp.",
            dependsOn = { "objective-572-mok-thardin-s-enchantment" },
            complete = QuestState(572, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2918, "Far Seer Mok'thardin",
                    "Travel to Far Seer Mok'thardin."),
            },
        },
        {
            id = "accept-571-mok-thardin-s-enchantment",
            kind = "accept",
            priority = 1070,
            text = "Accept Mok'thardin's Enchantment from Far Seer Mok'thardin in Grom'gol Base Camp.",
            complete = QuestState(571, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2918, "Far Seer Mok'thardin",
                    "Travel to Far Seer Mok'thardin."),
            },
        },
        {
            id = "objective-209-skullsplitter-tusks",
            kind = "objective",
            priority = 1090,
            text = "Kill Trolls and collect 18 Skullsplitter Tusk in Ziata'jai Ruins and Ruins of Zul'Mamwe Stick to this area for the lower level trolls.",
            dependsOn = { "accept-209-skullsplitter-tusks" },
            complete = QuestState(209, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.4572, 0.4219, "Continue toward Skullsplitter Tusks",
                    "Continue toward Skullsplitter Tusks."),
                Point(MAP.STRANGLETHORN, 0.4486, 0.4070, "Skullsplitter Witch Doctor",
                    "Travel to Skullsplitter Witch Doctor."),
            },
        },
        {
            id = "turnin-193-panther-mastery",
            kind = "turnin",
            priority = 1110,
            text = "Turn in Panther Mastery to Sir S. J. Erlgadin in Nesingwary's Expedition.",
            dependsOn = { "accept-193-panther-mastery" },
            complete = QuestState(193, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3558, 0.1059, "Sir S. J. Erlgadin",
                    "Travel to Sir S. J. Erlgadin."),
            },
        },
        {
            id = "turnin-196-raptor-mastery",
            kind = "turnin",
            priority = 1120,
            text = "Turn in Raptor Mastery to Hemet Nesingwary Jr. in Nesingwary's Expedition.",
            dependsOn = { "objective-196-raptor-mastery" },
            complete = QuestState(196, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1075, "Hemet Nesingwary Jr.",
                    "Travel to Hemet Nesingwary Jr.."),
            },
        },
        {
            id = "accept-197-raptor-mastery",
            kind = "accept",
            priority = 1130,
            text = "Accept Raptor Mastery from Hemet Nesingwary Jr. in Nesingwary's Expedition.",
            complete = QuestState(197, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1075, "Hemet Nesingwary Jr.",
                    "Travel to Hemet Nesingwary Jr.."),
            },
        },
        {
            id = "turnin-595-the-bloodsail-buccaneers",
            kind = "turnin",
            priority = 1150,
            text = "Turn in The Bloodsail Buccaneers in Southern Savage Coast.",
            dependsOn = { "accept-595-the-bloodsail-buccaneers" },
            complete = QuestState(595, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2723, 0.6954, "Southern Savage Coast",
                    "Travel to Southern Savage Coast."),
            },
        },
        {
            id = "accept-597-the-bloodsail-buccaneers",
            kind = "accept",
            priority = 1160,
            text = "Accept The Bloodsail Buccaneers in Southern Savage Coast.",
            complete = QuestState(597, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2723, 0.6954, "Southern Savage Coast",
                    "Travel to Southern Savage Coast."),
            },
        },
        {
            id = "objective-606-scaring-shaky",
            kind = "objective",
            priority = 1180,
            text = "Kill the Elder Mistvale Gorilla for 5 Mistvale Giblets in the Mistvale Valley.",
            dependsOn = { "accept-606-scaring-shaky" },
            complete = QuestState(606, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3352, 0.6304, "Elder Mistvale Gorilla",
                    "Travel to Elder Mistvale Gorilla."),
            },
        },
        {
            id = "objective-571-mok-thardin-s-enchantment",
            kind = "objective",
            priority = 1190,
            text = "Kill Elder Mistvale Gorilla in the Mistvale Valley until you find the Aged Gorilla Sinew Note: Save all the Gorilla Fang you find for a later quest.",
            dependsOn = { "accept-571-mok-thardin-s-enchantment" },
            complete = QuestState(571, "complete"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3400, 0.6400, "Elder Mistvale Gorilla",
                    "Travel to Elder Mistvale Gorilla."),
            },
        },
        {
            id = "turnin-606-scaring-shaky",
            kind = "turnin",
            priority = 1210,
            text = "Turn in Scaring Shaky to \"Shaky\" Phillipe in Booty Bay.",
            dependsOn = { "objective-606-scaring-shaky" },
            complete = QuestState(606, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2690, 0.7362, "'Shaky' Phillipe",
                    "Travel to 'Shaky' Phillipe."),
            },
        },
        {
            id = "accept-607-return-to-mackinley",
            kind = "accept",
            priority = 1220,
            text = "Accept Return to MacKinley from \"Shaky\" Phillipe in Booty Bay.",
            complete = QuestState(607, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2690, 0.7362, "'Shaky' Phillipe",
                    "Travel to 'Shaky' Phillipe."),
            },
        },
        {
            id = "turnin-597-the-bloodsail-buccaneers",
            kind = "turnin",
            priority = 1230,
            text = "Turn in The Bloodsail Buccaneers to First Mate Crazz in Booty Bay.",
            dependsOn = { "accept-597-the-bloodsail-buccaneers" },
            complete = QuestState(597, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2811, 0.7613, "First Mate Crazz",
                    "Travel to First Mate Crazz."),
            },
        },
        {
            id = "accept-599-the-bloodsail-buccaneers",
            kind = "accept",
            priority = 1240,
            text = "Accept The Bloodsail Buccaneers from First Mate Crazz in Booty Bay.",
            complete = QuestState(599, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2811, 0.7613, "First Mate Crazz",
                    "Travel to First Mate Crazz."),
            },
        },
        {
            id = "turnin-607-return-to-mackinley",
            kind = "turnin",
            priority = 1250,
            text = "Turn in Return to MacKinley to \"Sea Wolf\" MacKinley in Booty Bay.",
            dependsOn = { "accept-607-return-to-mackinley" },
            complete = QuestState(607, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2776, 0.7712, "'Sea Wolf' MacKinley",
                    "Travel to 'Sea Wolf' MacKinley."),
            },
        },
        {
            id = "turnin-599-the-bloodsail-buccaneers",
            kind = "turnin",
            priority = 1260,
            text = "Turn in The Bloodsail Buccaneers to Fleet Master Seahorn in Booty Bay.",
            dependsOn = { "accept-599-the-bloodsail-buccaneers" },
            complete = QuestState(599, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2714, 0.7696, "Fleet Master Seahorn",
                    "Travel to Fleet Master Seahorn."),
            },
        },
        {
            id = "turnin-209-skullsplitter-tusks",
            kind = "turnin",
            priority = 1270,
            text = "Turn in Skullsplitter Tusks to Kebok in The Salty Sailor Tavern.",
            dependsOn = { "objective-209-skullsplitter-tusks" },
            complete = QuestState(209, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.2701, 0.7714, "Kebok",
                    "Travel to Kebok."),
            },
        },
        {
            id = "turnin-571-mok-thardin-s-enchantment",
            kind = "turnin",
            priority = 1290,
            text = "Turn in Mok'thardin's Enchantment to Far Seer Mok'thardin in Grom'gol Base Camp.",
            dependsOn = { "objective-571-mok-thardin-s-enchantment" },
            complete = QuestState(571, "completed"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2918, "Far Seer Mok'thardin",
                    "Travel to Far Seer Mok'thardin."),
            },
        },
        {
            id = "accept-573-mok-thardin-s-enchantment",
            kind = "accept",
            priority = 1300,
            text = "Accept Mok'thardin's Enchantment from Far Seer Mok'thardin in Grom'gol Base Camp.",
            complete = QuestState(573, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2918, "Far Seer Mok'thardin",
                    "Travel to Far Seer Mok'thardin."),
            },
        },
        {
            id = "accept-598-split-bone-necklace",
            kind = "accept",
            priority = 1310,
            text = "Accept Split Bone Necklace from Kin'weelay in Grom'gol Base Camp.",
            complete = QuestState(598, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3221, 0.2774, "Kin'weelay",
                    "Travel to Kin'weelay."),
            },
        },
        {
            id = "note-grom-gol-base-camp",
            kind = "note",
            priority = 1320,
            text = "Set your hearth in Grom'gol Base Camp with Innkeeper Thulbek.",
            route = {
                Point(MAP.STRANGLETHORN, 0.3150, 0.2970, "Innkeeper Thulbek",
                    "Travel to Innkeeper Thulbek."),
            },
        },
        {
            id = "accept-338-the-green-hills-of-stranglethorn",
            kind = "accept",
            priority = 1340,
            text = "Accept The Green Hills of Stranglethorn from Barnil Stonepot in Nesingwary's Expedition.",
            complete = QuestState(338, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1051, "Barnil Stonepot",
                    "Travel to Barnil Stonepot."),
            },
        },
        {
            id = "accept-339-chapter-i",
            kind = "accept",
            priority = 1350,
            text = "Accept Chapter I from Barnil Stonepot in Nesingwary's Expedition.",
            complete = QuestState(339, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1051, "Barnil Stonepot",
                    "Travel to Barnil Stonepot."),
            },
        },
        {
            id = "accept-340-chapter-ii",
            kind = "accept",
            priority = 1360,
            text = "Accept Chapter II from Barnil Stonepot in Nesingwary's Expedition.",
            complete = QuestState(340, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1051, "Barnil Stonepot",
                    "Travel to Barnil Stonepot."),
            },
        },
        {
            id = "accept-341-chapter-iii",
            kind = "accept",
            priority = 1370,
            text = "Accept Chapter III from Barnil Stonepot in Nesingwary's Expedition.",
            complete = QuestState(341, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1051, "Barnil Stonepot",
                    "Travel to Barnil Stonepot."),
            },
        },
        {
            id = "accept-342-chapter-iv",
            kind = "accept",
            priority = 1380,
            text = "Accept Chapter IV from Barnil Stonepot in Nesingwary's Expedition.",
            complete = QuestState(342, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3565, 0.1051, "Barnil Stonepot",
                    "Travel to Barnil Stonepot."),
            },
        },
    },
})
