local _, ns = ...

-- Horde Era leveling route for the Hinterlands, levels 47-47.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    HINTERLANDS = 1425,
    STRANGLETHORN = 1434,
    UNDERCITY = 1458,
    HILLSBRAD = 1424,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-47-47-hinterlands",
    title = "47-47 Hinterlands (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Horde" },
            { level = { min = 47 } },
        },
    },
    goals = {
        {
            id = "travel-grom-gol-base-camp",
            kind = "travel",
            priority = 10,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 2932, state = "activeOrCompleted" } } },
                },
            },
            text = "Travel to Grom'gol Base Camp.",
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2777, "Grom'gol Base Camp",
                    "Travel to Grom'gol Base Camp."),
            },
        },
        {
            id = "accept-2932-grim-message",
            kind = "accept",
            priority = 20,
            text = "Accept Grim Message from Nimboya in Grom'gol Base Camp.",
            complete = QuestState(2932, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN, 0.3216, 0.2777, "Nimboya",
                    "Travel to Nimboya."),
            },
        },
        {
            id = "travel-undercity",
            kind = "travel",
            priority = 30,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 2995, state = "activeOrCompleted" } } },
                },
            },
            text = "Travel to Magic Quarter in Undercity.",
            route = {
                Point(MAP.UNDERCITY, 0.7315, 0.3280, "Magic Quarter",
                    "Travel to Magic Quarter."),
            },
        },
        {
            id = "accept-2995-lines-of-communication",
            kind = "accept",
            priority = 40,
            text = "Accept Lines of Communication from Oran Snakewrithe in Magic Quarter.",
            complete = QuestState(2995, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.7315, 0.3280, "Oran Snakewrithe",
                    "Travel to Oran Snakewrithe."),
            },
        },
        {
            id = "travel-77-tarren-mill",
            kind = "travel",
            priority = 50,
            text = "Travel to Tarren Mill.",
            route = {
                Point(MAP.HILLSBRAD, 0.6276, 0.1904, "Tarren Mill",
                    "Travel to Tarren Mill."),
            },
        },
        {
            id = "note-77-tarren-mill",
            kind = "note",
            priority = 60,
            text = "Set your hearth in Tarren Mill with Innkeeper Shay.",
            route = {
                Point(MAP.HILLSBRAD, 0.6276, 0.1904, "Innkeeper Shay",
                    "Travel to Innkeeper Shay."),
            },
        },
        {
            id = "accept-77-a-sticky-situation",
            kind = "accept",
            priority = 70,
            text = "Accept A Sticky Situation from Gilveradin Sunchaser in Shindigger's Camp.",
            complete = QuestState(77, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.2670, 0.4852, "Gilveradin Sunchaser",
                    "Travel to Gilveradin Sunchaser."),
            },
        },
        {
            id = "travel-7844-revantusk-village",
            kind = "travel",
            priority = 80,
            text = "Travel to Revantusk Village.",
            route = {
                Point(MAP.HINTERLANDS, 0.5583, 0.5315, "Continue toward Revantusk Village",
                    "Continue toward Revantusk Village."),
                Point(MAP.HINTERLANDS, 0.7246, 0.6620, "Continue toward Revantusk Village",
                    "Continue toward Revantusk Village."),
                Point(MAP.HINTERLANDS, 0.7719, 0.7801, "Revantusk Village",
                    "Travel to Revantusk Village."),
            },
        },
        {
            id = "accept-7844-cannibalistic-cousins",
            kind = "accept",
            priority = 90,
            text = "Accept Cannibalistic Cousins from Mystic Yayo'jin in Revantusk Village.",
            complete = QuestState(7844, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.7881, 0.7902, "Mystic Yayo'jin",
                    "Travel to Mystic Yayo'jin."),
            },
        },
        {
            id = "accept-7841-message-to-the-wildhammer",
            kind = "accept",
            priority = 100,
            text = "Accept Message to the Wildhammer from Otho Moji'ko in Revantusk Village.",
            complete = QuestState(7841, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.7929, 0.7909, "Otho Moji'ko",
                    "Travel to Otho Moji'ko."),
            },
        },
        {
            id = "accept-7828-stalking-the-stalkers",
            kind = "accept",
            priority = 110,
            text = "Accept Stalking the Stalkers from Huntsman Markhor in Revantusk Village.",
            complete = QuestState(7828, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.7916, 0.7953, "Huntsman Markhor",
                    "Travel to Huntsman Markhor."),
            },
        },
        {
            id = "accept-7829-hunt-the-savages",
            kind = "accept",
            priority = 120,
            text = "Accept Hunt the Savages from Huntsman Markhor in Revantusk Village.",
            complete = QuestState(7829, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.7916, 0.7953, "Huntsman Markhor",
                    "Travel to Huntsman Markhor."),
            },
        },
        {
            id = "accept-7830-avenging-the-fallen",
            kind = "accept",
            priority = 130,
            text = "Accept Avenging the Fallen from Huntsman Markhor in Revantusk Village.",
            complete = QuestState(7830, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.7916, 0.7953, "Huntsman Markhor",
                    "Travel to Huntsman Markhor."),
            },
        },
        {
            id = "accept-7839-vilebranch-hooligans",
            kind = "accept",
            priority = 140,
            text = "Accept Vilebranch Hooligans from Smith Slagtree in Revantusk Village.",
            complete = QuestState(7839, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.7755, 0.8031, "Smith Slagtree",
                    "Travel to Smith Slagtree."),
            },
        },
        {
            id = "travel-7828-the-overlook-cliffs",
            kind = "travel",
            priority = 150,
            text = "Travel to The Overlook Cliffs.",
            route = {
                Point(MAP.HINTERLANDS, 0.7592, 0.6167, "The Overlook Cliffs",
                    "Travel to The Overlook Cliffs."),
            },
        },
        {
            id = "objective-7828-1-silvermane-stalker",
            kind = "objective",
            priority = 160,
            text = "Kill Silvermane Stalker in The Hinterlands, to complete this later.",
            dependsOn = { "accept-7828-stalking-the-stalkers" },
            complete = QuestObjective(7828, 1),
            route = {
                Point(MAP.HINTERLANDS, 0.6300, 0.4900, "Silvermane Stalker",
                    "Travel to Silvermane Stalker."),
            },
        },
        {
            id = "objective-7844-cannibalistic-cousins",
            kind = "objective",
            priority = 170,
            text = "Kill 15 Vilebranch Scalper and 10 Vilebranch Soothsayer in the troll camps.",
            dependsOn = { "accept-7844-cannibalistic-cousins" },
            complete = QuestState(7844, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.7306, 0.5188, "Continue toward Cannibalistic Cousins",
                    "Continue toward Cannibalistic Cousins."),
                Point(MAP.HINTERLANDS, 0.7067, 0.4834, "Continue toward Cannibalistic Cousins",
                    "Continue toward Cannibalistic Cousins."),
                Point(MAP.HINTERLANDS, 0.6554, 0.4457, "Vilebranch Scalper",
                    "Travel to Vilebranch Scalper."),
            },
        },
        {
            id = "travel-7839-skulk-rock",
            kind = "travel",
            priority = 180,
            text = "Travel to Skulk Rock.",
            route = {
                Point(MAP.HINTERLANDS, 0.5744, 0.4262, "Skulk Rock",
                    "Travel to Skulk Rock."),
            },
        },
        {
            id = "objective-7839-vilebranch-hooligans",
            kind = "objective",
            priority = 190,
            text = "Collect Slagtree's Lost Tools on top of the hill in Skulk Rock.",
            dependsOn = { "accept-7839-vilebranch-hooligans" },
            complete = QuestState(7839, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.5744, 0.4262, "Skulk Rock",
                    "Travel to Skulk Rock."),
            },
        },
        {
            id = "objective-77-a-sticky-situation",
            kind = "objective",
            priority = 200,
            text = "Collect 10 Hinterlands Honey Ripple from the Horde Supply Crate in Skulk Rock.",
            dependsOn = { "accept-77-a-sticky-situation" },
            complete = QuestState(77, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.5744, 0.3906, "Continue toward A Sticky Situation",
                    "Continue toward A Sticky Situation."),
                Point(MAP.HINTERLANDS, 0.5728, 0.4117, "Skulk Rock",
                    "Travel to Skulk Rock."),
            },
        },
        {
            id = "travel-7830-valorwind-lake",
            kind = "travel",
            priority = 210,
            text = "Travel to Valorwind Lake.",
            route = {
                Point(MAP.HINTERLANDS, 0.5417, 0.4939, "Valorwind Lake",
                    "Travel to Valorwind Lake."),
            },
        },
        {
            id = "objective-7830-avenging-the-fallen",
            kind = "objective",
            priority = 220,
            text = "Kill Razorbeak Skylord collect Skylord Plume.",
            dependsOn = { "accept-7830-avenging-the-fallen" },
            complete = QuestState(7830, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.5417, 0.4939, "Razorbeak Skylord",
                    "Travel to Razorbeak Skylord."),
            },
        },
        {
            id = "objective-3123-testing-the-vessel",
            kind = "objective",
            priority = 230,
            text = "Kill Primitive Owlbeast and use the Beast Muisek Vessel to collect 10 Beast Muisek in Valorwind Lake.",
            complete = QuestState(3123, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.4390, 0.5542, "Primitive Owlbeast",
                    "Travel to Primitive Owlbeast."),
            },
        },
        {
            id = "objective-7829-hunt-the-savages",
            kind = "objective",
            priority = 240,
            text = "Kill 20 Savage Owlbeast.",
            dependsOn = { "accept-7829-hunt-the-savages" },
            complete = QuestState(7829, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.6536, 0.5910, "Continue toward Hunt the Savages",
                    "Continue toward Hunt the Savages."),
                Point(MAP.HINTERLANDS, 0.5395, 0.5187, "Continue toward Hunt the Savages",
                    "Continue toward Hunt the Savages."),
                Point(MAP.HINTERLANDS, 0.5138, 0.4700, "Continue toward Hunt the Savages",
                    "Continue toward Hunt the Savages."),
                Point(MAP.HINTERLANDS, 0.6142, 0.4404, "Continue toward Hunt the Savages",
                    "Continue toward Hunt the Savages."),
                Point(MAP.HINTERLANDS, 0.6452, 0.5605, "Savage Owlbeast",
                    "Travel to Savage Owlbeast."),
            },
        },
        {
            id = "objective-7828-1-silvermane-howler",
            kind = "objective",
            priority = 250,
            text = "Kill Silvermane Howler in The Hinterlands, to complete this later.",
            dependsOn = { "accept-7828-stalking-the-stalkers" },
            complete = QuestObjective(7828, 1),
            route = {
                Point(MAP.HINTERLANDS, 0.4000, 0.5000, "Silvermane Howler",
                    "Travel to Silvermane Howler."),
            },
        },
        {
            id = "travel-81-shindigger-s-camp",
            kind = "travel",
            priority = 260,
            text = "Travel to Shindigger's Camp.",
            route = {
                Point(MAP.HINTERLANDS, 0.2071, 0.4824, "Continue toward Shindigger's Camp",
                    "Continue toward Shindigger's Camp."),
                Point(MAP.HINTERLANDS, 0.2672, 0.4860, "Shindigger's Camp",
                    "Travel to Shindigger's Camp."),
            },
        },
        {
            id = "turnin-77-a-sticky-situation",
            kind = "turnin",
            priority = 270,
            text = "Turn in A Sticky Situation to Gilveradin Sunchaser in Shindigger's Camp.",
            dependsOn = { "objective-77-a-sticky-situation" },
            complete = QuestState(77, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.2672, 0.4860, "Gilveradin Sunchaser",
                    "Travel to Gilveradin Sunchaser."),
            },
        },
        {
            id = "accept-81-ripple-delivery",
            kind = "accept",
            priority = 280,
            text = "Accept Ripple Delivery from Gilveradin Sunchaser in Shindigger's Camp.",
            complete = QuestState(81, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.2672, 0.4860, "Gilveradin Sunchaser",
                    "Travel to Gilveradin Sunchaser."),
            },
        },
        {
            id = "objective-2995-1-burn-the-highvale-records",
            kind = "objective",
            priority = 290,
            text = "Click on Highvale Records in Quel'Danil Lodge.",
            dependsOn = { "accept-2995-lines-of-communication" },
            complete = QuestObjective(2995, 1),
            route = {
                Point(MAP.HINTERLANDS, 0.3198, 0.4686, "Quel'Danil Lodge",
                    "Travel to Quel'Danil Lodge."),
            },
        },
        {
            id = "objective-2995-2-burn-the-highvale-notes",
            kind = "objective",
            priority = 300,
            text = "Click on Highvale Notes in Quel'Danil Lodge.",
            dependsOn = { "accept-2995-lines-of-communication" },
            complete = QuestObjective(2995, 2),
            route = {
                Point(MAP.HINTERLANDS, 0.2964, 0.4873, "Quel'Danil Lodge",
                    "Travel to Quel'Danil Lodge."),
            },
        },
        {
            id = "objective-2995-3-burn-the-highvale-report",
            kind = "objective",
            priority = 310,
            text = "Click on Highvale Report in Quel'Danil Lodge.",
            dependsOn = { "accept-2995-lines-of-communication" },
            complete = QuestObjective(2995, 3),
            route = {
                Point(MAP.HINTERLANDS, 0.2857, 0.4610, "Quel'Danil Lodge",
                    "Travel to Quel'Danil Lodge."),
            },
        },
        {
            id = "accept-2742-rin-ji-is-trapped",
            kind = "accept",
            priority = 320,
            text = "Accept Rin'ji is Trapped! from Rin'ji in Quel'Danil Lodge.",
            complete = QuestState(2742, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.3075, 0.4697, "Rin'ji",
                    "Travel to Rin'ji."),
            },
        },
        {
            id = "objective-2742-rin-ji-is-trapped",
            kind = "objective",
            priority = 330,
            text = "Escort Rin'ji to safety.",
            dependsOn = { "accept-2742-rin-ji-is-trapped" },
            complete = QuestState(2742, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.3486, 0.5678, "Rin'ji",
                    "Travel to Rin'ji."),
            },
        },
        {
            id = "objective-7841-message-to-the-wildhammer",
            kind = "objective",
            priority = 340,
            text = "Kill the required Highvale elfs Quel'Danil Lodge.",
            dependsOn = { "accept-7841-message-to-the-wildhammer" },
            complete = QuestState(7841, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.3177, 0.4940, "Highvale Ranger",
                    "Travel to Highvale Ranger."),
            },
        },
        {
            id = "travel-81-shindigger-s-camp-2",
            kind = "travel",
            priority = 350,
            text = "Travel to Shindigger's Camp.",
            route = {
                Point(MAP.HINTERLANDS, 0.2071, 0.4824, "Continue toward Shindigger's Camp",
                    "Continue toward Shindigger's Camp."),
                Point(MAP.HINTERLANDS, 0.2672, 0.4860, "Shindigger's Camp",
                    "Travel to Shindigger's Camp."),
            },
        },
        {
            id = "turnin-77-a-sticky-situation-2",
            kind = "turnin",
            priority = 360,
            text = "Turn in A Sticky Situation to Gilveradin Sunchaser in Shindigger's Camp.",
            dependsOn = { "objective-77-a-sticky-situation" },
            complete = QuestState(77, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.2672, 0.4861, "Gilveradin Sunchaser",
                    "Travel to Gilveradin Sunchaser."),
            },
        },
        {
            id = "accept-81-ripple-delivery-2",
            kind = "accept",
            priority = 370,
            text = "Accept Ripple Delivery from Gilveradin Sunchaser in Shindigger's Camp.",
            complete = QuestState(81, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.2672, 0.4861, "Gilveradin Sunchaser",
                    "Travel to Gilveradin Sunchaser."),
            },
        },
        {
            id = "travel-2933-hiri-watha",
            kind = "travel",
            priority = 380,
            text = "Travel to Zun'watha.",
            route = {
                Point(MAP.HINTERLANDS, 0.2352, 0.5891, "Zun'watha",
                    "Travel to Zun'watha."),
            },
        },
        {
            id = "accept-2933-venom-bottles",
            kind = "accept",
            priority = 390,
            text = "Accept Venom Bottles in Zun'watha.",
            complete = QuestState(2933, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.2352, 0.5891, "Zun'watha",
                    "Travel to Zun'watha."),
            },
        },
        {
            id = "objective-2932-nimboya-s-pike",
            kind = "objective",
            priority = 400,
            text = "Use Nimboya's Pike to create Nimboya's Laden Pike.",
            dependsOn = { "accept-2932-grim-message" },
            complete = QuestState(2932, "complete"),
        },
        {
            id = "objective-2932-1-grim-message",
            kind = "objective",
            priority = 410,
            text = "Use Nimboya's Laden Pike in Hiri'watha.",
            dependsOn = { "accept-2932-grim-message" },
            complete = QuestObjective(2932, 1),
            route = {
                Point(MAP.HINTERLANDS, 0.3182, 0.5781, "Hiri'watha",
                    "Travel to Hiri'watha."),
            },
        },
        {
            id = "objective-7842-trained-razorbeak",
            kind = "objective",
            priority = 420,
            text = "Kill Trained Razorbeak for 10 Long Elegant Feather, you will need this for a later quest.",
            dependsOn = { "accept-7842-another-message-to-the-wildhammer" },
            complete = QuestState(7842, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.2080, 0.5350, "Trained Razorbeak",
                    "Travel to Trained Razorbeak."),
            },
        },
        {
            id = "objective-7828-1-silvermane-howler-2",
            kind = "objective",
            priority = 430,
            text = "Kill Silvermane Howler in The Hinterlands.",
            dependsOn = { "accept-7828-stalking-the-stalkers" },
            complete = QuestObjective(7828, 1),
            route = {
                Point(MAP.HINTERLANDS, 0.4000, 0.5000, "Silvermane Howler",
                    "Travel to Silvermane Howler."),
            },
        },
        {
            id = "objective-7828-1-silvermane-stalker-2",
            kind = "objective",
            priority = 440,
            text = "Kill Silvermane Stalker in The Hinterlands.",
            dependsOn = { "accept-7828-stalking-the-stalkers" },
            complete = QuestObjective(7828, 1),
            route = {
                Point(MAP.HINTERLANDS, 0.6300, 0.4900, "Silvermane Stalker",
                    "Travel to Silvermane Stalker."),
            },
        },
        {
            id = "travel-2782-the-overlook-cliffs",
            kind = "travel",
            priority = 450,
            text = "Travel to The Overlook Cliffs.",
            route = {
                Point(MAP.HINTERLANDS, 0.8629, 0.5906, "The Overlook Cliffs",
                    "Travel to The Overlook Cliffs."),
            },
        },
        {
            id = "turnin-2742-rin-ji-is-trapped",
            kind = "turnin",
            priority = 460,
            text = "Turn in Rin'ji is Trapped! in The Overlook Cliffs.",
            dependsOn = { "objective-2742-rin-ji-is-trapped" },
            complete = QuestState(2742, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.8629, 0.5906, "The Overlook Cliffs",
                    "Travel to The Overlook Cliffs."),
            },
        },
        {
            id = "accept-2782-rin-ji-s-secret",
            kind = "accept",
            priority = 470,
            text = "Accept Rin'ji's Secret in The Overlook Cliffs.",
            complete = QuestState(2782, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.8625, 0.5921, "The Overlook Cliffs",
                    "Travel to The Overlook Cliffs."),
            },
        },
        {
            id = "travel-7842-revantusk-village",
            kind = "travel",
            priority = 480,
            text = "Travel to Revantusk Village.",
            route = {
                Point(MAP.HINTERLANDS, 0.7246, 0.6620, "Continue toward Revantusk Village",
                    "Continue toward Revantusk Village."),
                Point(MAP.HINTERLANDS, 0.7878, 0.7839, "Revantusk Village",
                    "Travel to Revantusk Village."),
            },
        },
        {
            id = "turnin-7844-cannibalistic-cousins",
            kind = "turnin",
            priority = 490,
            text = "Turn in Cannibalistic Cousins to Mystic Yayo'jin in Revantusk Village.",
            dependsOn = { "objective-7844-cannibalistic-cousins" },
            complete = QuestState(7844, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.7878, 0.7839, "Mystic Yayo'jin",
                    "Travel to Mystic Yayo'jin."),
            },
        },
        {
            id = "turnin-7828-stalking-the-stalkers",
            kind = "turnin",
            priority = 500,
            text = "Turn in Stalking the Stalkers to Huntsman Markhor in Revantusk Village.",
            dependsOn = { "objective-7828-1-silvermane-stalker", "objective-7828-1-silvermane-howler", "objective-7828-1-silvermane-howler-2", "objective-7828-1-silvermane-stalker-2" },
            complete = QuestState(7828, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.7917, 0.7951, "Huntsman Markhor",
                    "Travel to Huntsman Markhor."),
            },
        },
        {
            id = "turnin-7829-hunt-the-savages",
            kind = "turnin",
            priority = 510,
            text = "Turn in Hunt the Savages to Huntsman Markhor in Revantusk Village.",
            dependsOn = { "objective-7829-hunt-the-savages" },
            complete = QuestState(7829, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.7917, 0.7951, "Huntsman Markhor",
                    "Travel to Huntsman Markhor."),
            },
        },
        {
            id = "turnin-7830-avenging-the-fallen",
            kind = "turnin",
            priority = 520,
            text = "Turn in Avenging the Fallen to Huntsman Markhor in Revantusk Village.",
            dependsOn = { "objective-7830-avenging-the-fallen" },
            complete = QuestState(7830, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.7917, 0.7951, "Huntsman Markhor",
                    "Travel to Huntsman Markhor."),
            },
        },
        {
            id = "turnin-7841-message-to-the-wildhammer",
            kind = "turnin",
            priority = 530,
            text = "Turn in Message to the Wildhammer to Otho Moji'ko in Revantusk Village.",
            dependsOn = { "objective-7841-message-to-the-wildhammer" },
            complete = QuestState(7841, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.7934, 0.7909, "Otho Moji'ko",
                    "Travel to Otho Moji'ko."),
            },
        },
        {
            id = "accept-7842-another-message-to-the-wildhammer",
            kind = "accept",
            priority = 540,
            text = "Accept Another Message to the Wildhammer from Otho Moji'ko in Revantusk Village.",
            complete = QuestState(7842, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.7934, 0.7909, "Otho Moji'ko",
                    "Travel to Otho Moji'ko."),
            },
        },
        {
            id = "objective-7842-another-message-to-the-wildhammer",
            kind = "objective",
            priority = 550,
            text = "Kill Trained Razorbeak for 10 Long Elegant Feather in The Hinterlands.",
            dependsOn = { "accept-7842-another-message-to-the-wildhammer" },
            complete = QuestState(7842, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.2080, 0.5350, "Trained Razorbeak",
                    "Travel to Trained Razorbeak."),
            },
        },
        {
            id = "turnin-7842-another-message-to-the-wildhammer",
            kind = "turnin",
            priority = 560,
            text = "Turn in Another Message to the Wildhammer to Otho Moji'ko in Revantusk Village.",
            dependsOn = { "objective-7842-trained-razorbeak", "objective-7842-another-message-to-the-wildhammer" },
            complete = QuestState(7842, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.7934, 0.7909, "Otho Moji'ko",
                    "Travel to Otho Moji'ko."),
            },
        },
        {
            id = "turnin-7839-vilebranch-hooligans",
            kind = "turnin",
            priority = 570,
            text = "Turn in Vilebranch Hooligans to Smith Slagtree in Revantusk Village.",
            dependsOn = { "objective-7839-vilebranch-hooligans" },
            complete = QuestState(7839, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.7755, 0.8031, "Smith Slagtree",
                    "Travel to Smith Slagtree."),
            },
        },
        {
            id = "travel-2934-tarren-mill",
            kind = "travel",
            priority = 580,
            text = "Travel to Tarren Mill.",
            route = {
                Point(MAP.HILLSBRAD, 0.6146, 0.1915, "Tarren Mill",
                    "Travel to Tarren Mill."),
            },
        },
        {
            id = "turnin-2933-venom-bottles",
            kind = "turnin",
            priority = 590,
            text = "Turn in Venom Bottles to Apothecary Lydon in Tarren Mill.",
            dependsOn = { "accept-2933-venom-bottles" },
            complete = QuestState(2933, "completed"),
            route = {
                Point(MAP.HILLSBRAD, 0.6146, 0.1915, "Apothecary Lydon",
                    "Travel to Apothecary Lydon."),
            },
        },
        {
            id = "accept-2934-undamaged-venom-sac",
            kind = "accept",
            priority = 600,
            text = "Accept Undamaged Venom Sac from Apothecary Lydon in Tarren Mill.",
            complete = QuestState(2934, "activeOrCompleted"),
            route = {
                Point(MAP.HILLSBRAD, 0.6146, 0.1915, "Apothecary Lydon",
                    "Travel to Apothecary Lydon."),
            },
        },
        {
            id = "travel-2934-shadra-alor",
            kind = "travel",
            priority = 610,
            text = "Travel to Shadra'Alor.",
            route = {
                Point(MAP.HINTERLANDS, 0.1031, 0.5481, "Continue toward Shadra'Alor",
                    "Continue toward Shadra'Alor."),
                Point(MAP.HINTERLANDS, 0.2377, 0.5650, "Continue toward Shadra'Alor",
                    "Continue toward Shadra'Alor."),
                Point(MAP.HINTERLANDS, 0.3581, 0.6358, "Continue toward Shadra'Alor",
                    "Continue toward Shadra'Alor."),
                Point(MAP.HINTERLANDS, 0.3496, 0.6843, "Shadra'Alor",
                    "Travel to Shadra'Alor."),
            },
        },
        {
            id = "objective-2934-undamaged-venom-sac",
            kind = "objective",
            priority = 620,
            text = "Kill Witherbark Broodguard and collect Undamaged Venom Sac in Shadra'Alor.",
            dependsOn = { "accept-2934-undamaged-venom-sac" },
            complete = QuestState(2934, "complete"),
            route = {
                Point(MAP.HINTERLANDS, 0.3496, 0.6843, "Witherbark Broodguard",
                    "Travel to Witherbark Broodguard."),
            },
        },
        {
            id = "turnin-1429-the-atal-ai-exile",
            kind = "turnin",
            priority = 630,
            text = "Turn in The Atal'ai Exile to Atal'ai Exile in Shadra'Alor.",
            complete = QuestState(1429, "completed"),
            route = {
                Point(MAP.HINTERLANDS, 0.3374, 0.7516, "Atal'ai Exile",
                    "Travel to Atal'ai Exile."),
            },
        },
        {
            id = "accept-1444-return-to-fel-zerul",
            kind = "accept",
            priority = 640,
            text = "Accept Return to Fel'Zerul from Atal'ai Exile in Shadra'Alor.",
            complete = QuestState(1444, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.3374, 0.7516, "Atal'ai Exile",
                    "Travel to Atal'ai Exile."),
            },
        },
        {
            id = "accept-1446-jammal-an-the-prophet",
            kind = "accept",
            priority = 650,
            text = "Accept Jammal'an the Prophet from Atal'ai Exile in Shadra'Alor.",
            complete = QuestState(1446, "activeOrCompleted"),
            route = {
                Point(MAP.HINTERLANDS, 0.3374, 0.7516, "Atal'ai Exile",
                    "Travel to Atal'ai Exile."),
            },
        },
        {
            id = "travel-2934-tarren-mill-2",
            kind = "travel",
            priority = 660,
            text = "Travel to Tarren Mill.",
            route = {
                Point(MAP.HILLSBRAD, 0.6146, 0.1915, "Tarren Mill",
                    "Travel to Tarren Mill."),
            },
        },
        {
            id = "turnin-2934-undamaged-venom-sac",
            kind = "turnin",
            priority = 670,
            text = "Turn in Undamaged Venom Sac to Apothecary Lydon in Tarren Mill.",
            dependsOn = { "objective-2934-undamaged-venom-sac" },
            complete = QuestState(2934, "completed"),
            route = {
                Point(MAP.HILLSBRAD, 0.6147, 0.1910, "Apothecary Lydon",
                    "Travel to Apothecary Lydon."),
            },
        },
        {
            id = "travel-2782-undercity",
            kind = "travel",
            priority = 680,
            text = "Travel to Magic Quarter in Undercity.",
            route = {
                Point(MAP.UNDERCITY, 0.7309, 0.3277, "Magic Quarter",
                    "Travel to Magic Quarter."),
            },
        },
        {
            id = "turnin-2782-rin-ji-s-secret",
            kind = "turnin",
            priority = 690,
            text = "Turn in Rin'ji's Secret to Oran Snakewrithe in Magic Quarter.",
            dependsOn = { "accept-2782-rin-ji-s-secret" },
            complete = QuestState(2782, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.7309, 0.3277, "Oran Snakewrithe",
                    "Travel to Oran Snakewrithe."),
            },
        },
        {
            id = "turnin-2995-lines-of-communication",
            kind = "turnin",
            priority = 700,
            text = "Turn in Lines of Communication to Oran Snakewrithe in Magic Quarter.",
            dependsOn = { "objective-2995-1-burn-the-highvale-records", "objective-2995-2-burn-the-highvale-notes", "objective-2995-3-burn-the-highvale-report" },
            complete = QuestState(2995, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.7309, 0.3277, "Oran Snakewrithe",
                    "Travel to Oran Snakewrithe."),
            },
        },
        {
            id = "turnin-8273-oran-s-gratitude",
            kind = "turnin",
            priority = 710,
            text = "Turn in Oran's Gratitude to Oran Snakewrithe in Magic Quarter. This is an elite. Bring a group.",
            complete = QuestState(8273, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.7309, 0.3277, "Oran Snakewrithe",
                    "Travel to Oran Snakewrithe."),
            },
        },
    },
})
