local _, ns = ...

-- Horde Era leveling route for Un'Goro Crater, levels 51-53.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    UNGORO = 1449,
    ORGRIMMAR = 1454,
    UNDERCITY = 1458,
    BARRENS = 1413,
    TANARIS = 1446,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-51-53-ungoro-crater",
    title = "51-53 Un'Goro Crater (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Horde" },
            { level = { min = 51 } },
        },
    },
    goals = {
        {
            id = "objective-4244-mithril-casing",
            kind = "objective",
            priority = 10,
            text = "Buy Mithril Casing.",
            complete = QuestState(4244, "complete"),
        },
        {
            id = "accept-4300-bone-bladed-weapons",
            kind = "accept",
            priority = 30,
            text = "Accept Bone-Bladed Weapons from Jes'rimon in The Drag.",
            complete = QuestState(4300, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.5567, 0.3421, "Jes'rimon",
                    "Travel to Jes'rimon."),
            },
        },
        {
            id = "accept-4293-a-sample-of-slime",
            kind = "accept",
            priority = 50,
            text = "Accept A Sample of Slime... from Chemist Fuely in The Apothecarium.",
            complete = QuestState(4293, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.4746, 0.7330, "Chemist Fuely",
                    "Travel to Chemist Fuely."),
            },
        },
        {
            id = "accept-4294-and-a-batch-of-ooze",
            kind = "accept",
            priority = 60,
            text = "Accept ... and a Batch of Ooze from Chemist Fuely in The Apothecarium.",
            complete = QuestState(4294, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.4746, 0.7330, "Chemist Fuely",
                    "Travel to Chemist Fuely."),
            },
        },
        {
            id = "accept-4502-volcanic-activity",
            kind = "accept",
            priority = 80,
            text = "Accept Volcanic Activity from Liv Rizzlefix in Ratchet.",
            complete = QuestState(4502, "activeOrCompleted"),
            route = {
                Point(MAP.BARRENS, 0.6245, 0.3872, "Liv Rizzlefix",
                    "Travel to Liv Rizzlefix."),
            },
        },
        {
            id = "accept-2661-delivery-for-marin",
            kind = "accept",
            priority = 90,
            conditions = {
                all = {
                    { quest = { id = 2641, state = "completed" } },
                },
            },
            text = "Accept Delivery for Marin from Sprinkle in Gadgetzan.",
            complete = QuestState(2661, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.5105, 0.2687, "Sprinkle",
                    "Travel to Sprinkle."),
            },
        },
        {
            id = "accept-4496-bungle-in-the-jungle",
            kind = "accept",
            priority = 100,
            conditions = {
                all = {
                    { quest = { id = 4494, state = "completed" } },
                },
            },
            text = "Accept Bungle in the Jungle from Alchemist Pestlezugg in Gadgetzan.",
            complete = QuestState(4496, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.5090, 0.2698, "Alchemist Pestlezugg",
                    "Travel to Alchemist Pestlezugg."),
            },
        },
        {
            id = "turnin-2661-delivery-for-marin",
            kind = "turnin",
            priority = 110,
            conditions = {
                all = {
                    { quest = { id = 2641, state = "completed" } },
                },
            },
            text = "Turn in Delivery for Marin to Marin Noggenfogger in Gadgetzan.",
            dependsOn = { "accept-2661-delivery-for-marin" },
            complete = QuestState(2661, "completed"),
            route = {
                Point(MAP.TANARIS, 0.5180, 0.2866, "Marin Noggenfogger",
                    "Travel to Marin Noggenfogger."),
            },
        },
        {
            id = "accept-2662-noggenfogger-elixir",
            kind = "accept",
            priority = 120,
            conditions = {
                all = {
                    { quest = { id = 2641, state = "completed" } },
                },
            },
            text = "Accept Noggenfogger Elixir from Marin Noggenfogger in Gadgetzan.",
            complete = QuestState(2662, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.5180, 0.2866, "Marin Noggenfogger",
                    "Travel to Marin Noggenfogger."),
            },
        },
        {
            id = "turnin-2662-noggenfogger-elixir",
            kind = "turnin",
            priority = 130,
            conditions = {
                all = {
                    { quest = { id = 2641, state = "completed" } },
                },
            },
            text = "Turn in Noggenfogger Elixir to Marin Noggenfogger in Gadgetzan.",
            dependsOn = { "accept-2662-noggenfogger-elixir" },
            complete = QuestState(2662, "completed"),
            route = {
                Point(MAP.TANARIS, 0.5180, 0.2866, "Marin Noggenfogger",
                    "Travel to Marin Noggenfogger."),
            },
        },
        {
            id = "accept-4504-super-sticky",
            kind = "accept",
            priority = 140,
            text = "Accept Super Sticky from Tran'rek in Gadgetzan.",
            complete = QuestState(4504, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.5159, 0.2677, "Tran'rek",
                    "Travel to Tran'rek."),
            },
        },
        {
            id = "accept-4289-the-apes-of-un-goro",
            kind = "accept",
            priority = 160,
            text = "Accept The Apes of Un'Goro from Torwa Pathfinder in Un'Goro.",
            complete = QuestState(4289, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.7163, 0.7595, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "accept-4290-the-fare-of-lar-korwi",
            kind = "accept",
            priority = 170,
            text = "Accept The Fare of Lar'korwi from Torwa Pathfinder in Un'Goro.",
            complete = QuestState(4290, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.7163, 0.7595, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "objective-4290-the-fare-of-lar-korwi",
            kind = "objective",
            priority = 180,
            text = "Collect Piece of Threshadon Carcass from the Carcass in The Marshlands.",
            dependsOn = { "accept-4290-the-fare-of-lar-korwi" },
            complete = QuestState(4290, "complete"),
            route = {
                Point(MAP.UNGORO, 0.6864, 0.5657, "The Marshlands",
                    "Travel to The Marshlands."),
            },
        },
        {
            id = "accept-4243-chasing-a-me-01",
            kind = "accept",
            priority = 200,
            text = "Accept Chasing A-Me 01 from Karna Remtravel in Lakkari Tar Pits.",
            complete = QuestState(4243, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4639, 0.1343, "Karna Remtravel",
                    "Travel to Karna Remtravel."),
            },
        },
        {
            id = "accept-4503-shizzle-s-flyer",
            kind = "accept",
            priority = 210,
            text = "Accept Shizzle's Flyer from Shizzle in Marshal's Refuge.",
            complete = QuestState(4503, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4423, 0.1152, "Shizzle",
                    "Travel to Shizzle."),
            },
        },
        {
            id = "accept-4492-lost",
            kind = "accept",
            priority = 220,
            text = "Accept Lost! from Spraggle Frock in Marshal's Refuge.",
            complete = QuestState(4492, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4352, 0.0849, "Spraggle Frock",
                    "Travel to Spraggle Frock."),
            },
        },
        {
            id = "accept-4501-beware-of-pterrordax",
            kind = "accept",
            priority = 230,
            text = "Accept Beware of Pterrordax in Marshal's Refuge.",
            complete = QuestState(4501, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4359, 0.0831, "Marshal's Refuge",
                    "Travel to Marshal's Refuge."),
            },
        },
        {
            id = "accept-3881-expedition-salvation",
            kind = "accept",
            priority = 240,
            text = "Accept Expedition Salvation from Hol'anyee Marshal in Marshal's Refuge.",
            complete = QuestState(3881, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4390, 0.0722, "Hol'anyee Marshal",
                    "Travel to Hol'anyee Marshal."),
            },
        },
        {
            id = "accept-3883-alien-ecology",
            kind = "accept",
            priority = 250,
            text = "Accept Alien Ecology from Hol'anyee Marshal in Marshal's Refuge.",
            complete = QuestState(3883, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4390, 0.0726, "Hol'anyee Marshal",
                    "Travel to Hol'anyee Marshal."),
            },
        },
        {
            id = "accept-3882-roll-the-bones",
            kind = "accept",
            priority = 260,
            text = "Accept Roll the Bones from Spark Nilminer in Marshal's Refuge.",
            complete = QuestState(3882, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4340, 0.0782, "Spark Nilminer",
                    "Travel to Spark Nilminer."),
            },
        },
        {
            id = "accept-4145-larion-and-muigin",
            kind = "accept",
            priority = 270,
            text = "Accept Larion and Muigin from Larion in Marshal's Refuge.",
            complete = QuestState(4145, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4552, 0.0870, "Larion",
                    "Travel to Larion."),
            },
        },
        {
            id = "objective-4504-super-sticky",
            kind = "objective",
            priority = 280,
            text = "Kill Tar Beast or Tar Lord and collect 12 Super Sticky Tar in Lakkari Tar Pits.",
            dependsOn = { "accept-4504-super-sticky" },
            complete = QuestState(4504, "complete"),
            route = {
                Point(MAP.UNGORO, 0.4503, 0.1595, "Continue toward Super Sticky",
                    "Continue toward Super Sticky."),
                Point(MAP.UNGORO, 0.4305, 0.1795, "Continue toward Super Sticky",
                    "Continue toward Super Sticky."),
                Point(MAP.UNGORO, 0.4628, 0.1945, "Continue toward Super Sticky",
                    "Continue toward Super Sticky."),
                Point(MAP.UNGORO, 0.4893, 0.2046, "Continue toward Super Sticky",
                    "Continue toward Super Sticky."),
                Point(MAP.UNGORO, 0.5043, 0.2664, "Continue toward Super Sticky",
                    "Continue toward Super Sticky."),
                Point(MAP.UNGORO, 0.4758, 0.3175, "Tar Beast",
                    "Travel to Tar Beast."),
            },
        },
        {
            id = "objective-4145-2-bloodpetal-trapper",
            kind = "objective",
            priority = 290,
            text = "Kill 5 Bloodpetal Trapper near Lakkari Tar Pits.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 2),
            route = {
                Point(MAP.UNGORO, 0.3975, 0.2237, "Bloodpetal Trapper",
                    "Travel to Bloodpetal Trapper."),
            },
        },
        {
            id = "objective-4501-1-pterrordax",
            kind = "objective",
            priority = 310,
            text = "Make a start for killing 10 Pterrordax and also collect 10 Webbed Pterrordax Scale for quest 'Shizzle's Flyer' in Lakkari Tar Pits to complete it later.",
            dependsOn = { "accept-4501-beware-of-pterrordax" },
            complete = QuestObjective(4501, 1),
            route = {
                Point(MAP.UNGORO, 0.5691, 0.0994, "Pterrordax",
                    "Travel to Pterrordax."),
            },
        },
        {
            id = "objective-4145-3-bloodpetal-flayer",
            kind = "objective",
            priority = 320,
            text = "Kill 5 Bloodpetal Flayer near Lakkari Tar Pits.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 3),
            route = {
                Point(MAP.UNGORO, 0.5721, 0.1737, "Bloodpetal Flayer",
                    "Travel to Bloodpetal Flayer."),
            },
        },
        {
            id = "turnin-4243-chasing-a-me-01",
            kind = "turnin",
            priority = 340,
            text = "Turn in Chasing A-Me 01 to Williden Marshal in Fungal Rock.",
            dependsOn = { "accept-4243-chasing-a-me-01" },
            complete = QuestState(4243, "completed"),
            route = {
                Point(MAP.UNGORO, 0.6765, 0.1677, "Williden Marshal",
                    "Travel to Williden Marshal."),
            },
        },
        {
            id = "accept-4245-chasing-a-me-01",
            kind = "accept",
            priority = 350,
            conditions = {
                all = {
                    { quest = { id = 4244, state = "completed" } },
                },
            },
            text = "Accept Chasing A-Me 01 from A-Me 01 in Fungal Rock.",
            complete = QuestState(4245, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.6765, 0.1677, "A-Me 01",
                    "Travel to A-Me 01."),
            },
        },
        {
            id = "objective-4245-chasing-a-me-01",
            kind = "objective",
            priority = 360,
            conditions = {
                all = {
                    { quest = { id = 4244, state = "completed" } },
                },
            },
            text = "Escort A-Me 01 back to Marshal's Refuge.",
            dependsOn = { "accept-4245-chasing-a-me-01" },
            complete = QuestState(4245, "complete"),
            route = {
                Point(MAP.UNGORO, 0.6343, 0.1667, "Continue toward Chasing A-Me 01",
                    "Continue toward Chasing A-Me 01."),
                Point(MAP.UNGORO, 0.6124, 0.1700, "Continue toward Chasing A-Me 01",
                    "Continue toward Chasing A-Me 01."),
                Point(MAP.UNGORO, 0.6762, 0.1676, "A-Me 01",
                    "Travel to A-Me 01."),
            },
        },
        {
            id = "turnin-4245-chasing-a-me-01",
            kind = "turnin",
            priority = 370,
            conditions = {
                all = {
                    { quest = { id = 4244, state = "completed" } },
                },
            },
            text = "Turn in Chasing A-Me 01 to Karna Remtravel in Lakkari Tar Pits.",
            dependsOn = { "objective-4245-chasing-a-me-01" },
            complete = QuestState(4245, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4638, 0.1345, "Karna Remtravel",
                    "Travel to Karna Remtravel."),
            },
        },
        {
            id = "objective-4289-the-apes-of-un-goro",
            kind = "objective",
            priority = 380,
            text = "Kill Un'Goro Gorilla, Un'Goro Thunderer and Un'Goro Stomper for the quest items all of them found in Fungal Rock.",
            dependsOn = { "accept-4289-the-apes-of-un-goro" },
            complete = QuestState(4289, "complete"),
            route = {
                Point(MAP.UNGORO, 0.6386, 0.1644, "Un'Goro Gorilla",
                    "Travel to Un'Goro Gorilla."),
            },
        },
        {
            id = "objective-4501-1-pterrordax-2",
            kind = "objective",
            priority = 390,
            text = "Finish killing 10 Pterrordax in Lakkari Tar Pits.",
            dependsOn = { "accept-4501-beware-of-pterrordax" },
            complete = QuestObjective(4501, 1),
            route = {
                Point(MAP.UNGORO, 0.5851, 0.1674, "Continue toward Pterrordax",
                    "Continue toward Pterrordax."),
                Point(MAP.UNGORO, 0.5691, 0.0994, "Pterrordax",
                    "Travel to Pterrordax."),
            },
        },
        {
            id = "objective-3881-1-crate-of-foodstuffs",
            kind = "objective",
            priority = 410,
            text = "Collect Crate of Foodstuffs from the crate in The Marshlands.",
            dependsOn = { "accept-3881-expedition-salvation" },
            complete = QuestObjective(3881, 1),
            route = {
                Point(MAP.UNGORO, 0.6850, 0.3650, "The Marshlands",
                    "Travel to The Marshlands."),
            },
        },
        {
            id = "objective-4145-larion-and-muigin",
            kind = "objective",
            priority = 420,
            text = "Kill 5 Bloodpetal Lasher and 5 Bloodpetal Thresher in Un'Gorop.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestState(4145, "complete"),
            route = {
                Point(MAP.UNGORO, 0.6790, 0.3086, "Bloodpetal Lasher",
                    "Travel to Bloodpetal Lasher."),
            },
        },
        {
            id = "objective-4294-muculent-ooze",
            kind = "objective",
            priority = 430,
            text = "Kill Muculent Ooze and collect some Un'Goro Slime Sample, you will need about 35 of these for later quest.",
            dependsOn = { "accept-4294-and-a-batch-of-ooze" },
            complete = QuestState(4294, "complete"),
            route = {
                Point(MAP.UNGORO, 0.6790, 0.3086, "Muculent Ooze",
                    "Travel to Muculent Ooze."),
            },
        },
        {
            id = "objective-4503-1-diemetradon",
            kind = "objective",
            priority = 450,
            text = "Kill Diemetradon or Young Diemetradon and collect 8 Webbed Diemetradon Scale along the waypoint path in Un'Goro.",
            dependsOn = { "accept-4503-shizzle-s-flyer" },
            complete = QuestObjective(4503, 1),
            route = {
                Point(MAP.UNGORO, 0.5823, 0.5634, "Continue toward Diemetradon",
                    "Continue toward Diemetradon."),
                Point(MAP.UNGORO, 0.5808, 0.7059, "Continue toward Diemetradon",
                    "Continue toward Diemetradon."),
                Point(MAP.UNGORO, 0.5648, 0.6506, "Diemetradon",
                    "Travel to Diemetradon."),
            },
        },
        {
            id = "objective-3882-roll-the-bones",
            kind = "objective",
            priority = 460,
            text = "Collect 8 Dinosaur Bone dropped from Diemetradons in Un'Goro.",
            dependsOn = { "accept-3882-roll-the-bones" },
            complete = QuestState(3882, "complete"),
            route = {
                Point(MAP.UNGORO, 0.5818, 0.7182, "Diemetradon",
                    "Travel to Diemetradon."),
            },
        },
        {
            id = "objective-4294-primal-ooze",
            kind = "objective",
            priority = 470,
            text = "Kill Primal Ooze and collect some Un'Goro Slime Sample, you will need about 35 of these for later quest.",
            dependsOn = { "accept-4294-and-a-batch-of-ooze" },
            complete = QuestState(4294, "complete"),
            route = {
                Point(MAP.UNGORO, 0.5818, 0.7182, "Primal Ooze",
                    "Travel to Primal Ooze."),
            },
        },
        {
            id = "turnin-4289-the-apes-of-un-goro",
            kind = "turnin",
            priority = 480,
            text = "Turn in The Apes of Un'Goro to Torwa Pathfinder in Un'Goro.",
            dependsOn = { "objective-4289-the-apes-of-un-goro" },
            complete = QuestState(4289, "completed"),
            route = {
                Point(MAP.UNGORO, 0.7162, 0.7598, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "turnin-4290-the-fare-of-lar-korwi",
            kind = "turnin",
            priority = 490,
            text = "Turn in The Fare of Lar'korwi to Torwa Pathfinder in Un'Goro.",
            dependsOn = { "objective-4290-the-fare-of-lar-korwi" },
            complete = QuestState(4290, "completed"),
            route = {
                Point(MAP.UNGORO, 0.7162, 0.7598, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "accept-4291-the-scent-of-lar-korwi",
            kind = "accept",
            priority = 500,
            text = "Accept The Scent of Lar'korwi from Torwa Pathfinder in Un'Goro.",
            complete = QuestState(4291, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.7162, 0.7598, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "accept-4301-the-mighty-u-cha",
            kind = "accept",
            priority = 510,
            text = "Accept The Mighty U'cha from Torwa Pathfinder in Un'Goro.",
            complete = QuestState(4301, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.7162, 0.7598, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "objective-4291-the-scent-of-lar-korwi",
            kind = "objective",
            priority = 520,
            text = "Kill Lar'korwi Mate and collect 2 Ravasaur Pheromone Gland in The Marshlands.",
            dependsOn = { "accept-4291-the-scent-of-lar-korwi" },
            complete = QuestState(4291, "complete"),
            route = {
                Point(MAP.UNGORO, 0.6717, 0.7268, "Lar'korwi Mate",
                    "Travel to Lar'korwi Mate."),
            },
        },
        {
            id = "objective-4300-bone-bladed-weapons",
            kind = "objective",
            priority = 530,
            text = "Kill Ravasaurs and collect 8 White Ravasaur Claw in The Marshlands.",
            dependsOn = { "accept-4300-bone-bladed-weapons" },
            complete = QuestState(4300, "complete"),
            route = {
                Point(MAP.UNGORO, 0.6715, 0.5730, "Ravasaur Hunter",
                    "Travel to Ravasaur Hunter."),
            },
        },
        {
            id = "accept-3844-it-s-a-secret-to-everybody",
            kind = "accept",
            priority = 540,
            text = "Accept It's a Secret to Everybody in The Marshlands.",
            complete = QuestState(3844, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.6315, 0.6858, "The Marshlands",
                    "Travel to The Marshlands."),
            },
        },
        {
            id = "turnin-3844-it-s-a-secret-to-everybody",
            kind = "turnin",
            priority = 550,
            text = "Turn in It's a Secret to Everybody in The Marshlands.",
            dependsOn = { "accept-3844-it-s-a-secret-to-everybody" },
            complete = QuestState(3844, "completed"),
            route = {
                Point(MAP.UNGORO, 0.6313, 0.6895, "The Marshlands",
                    "Travel to The Marshlands."),
            },
        },
        {
            id = "accept-3845-it-s-a-secret-to-everybody",
            kind = "accept",
            priority = 560,
            text = "Accept It's a Secret to Everybody in The Marshlands.",
            complete = QuestState(3845, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.6313, 0.6895, "The Marshlands",
                    "Travel to The Marshlands."),
            },
        },
        {
            id = "turnin-4291-the-scent-of-lar-korwi",
            kind = "turnin",
            priority = 570,
            text = "Turn in The Scent of Lar'korwi to Torwa Pathfinder in Un'Goro.",
            dependsOn = { "objective-4291-the-scent-of-lar-korwi" },
            complete = QuestState(4291, "completed"),
            route = {
                Point(MAP.UNGORO, 0.7162, 0.7597, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "accept-4292-the-bait-for-lar-korwi",
            kind = "accept",
            priority = 580,
            text = "Accept The Bait for Lar'korwi from Torwa Pathfinder in Un'Goro.",
            complete = QuestState(4292, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.7162, 0.7597, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "objective-3883-alien-ecology",
            kind = "objective",
            priority = 600,
            text = "Use Unused Scraping Vial inside the hive to collect Hive Wall Sample in The Slithering Scar.",
            dependsOn = { "accept-3883-alien-ecology" },
            complete = QuestState(3883, "complete"),
            route = {
                Point(MAP.UNGORO, 0.5009, 0.8092, "Continue toward Alien Ecology",
                    "Continue toward Alien Ecology."),
                Point(MAP.UNGORO, 0.4947, 0.8318, "Continue toward Alien Ecology",
                    "Continue toward Alien Ecology."),
                Point(MAP.UNGORO, 0.4873, 0.8526, "The Slithering Scar",
                    "Travel to The Slithering Scar."),
            },
        },
        {
            id = "objective-3881-2-research-equipment",
            kind = "objective",
            priority = 630,
            text = "Collect Research Equipment from the ground in Terror Run.",
            dependsOn = { "accept-3881-expedition-salvation" },
            complete = QuestObjective(3881, 2),
            route = {
                Point(MAP.UNGORO, 0.3842, 0.6611, "Terror Run",
                    "Travel to Terror Run."),
            },
        },
        {
            id = "accept-974-finding-the-source",
            kind = "accept",
            priority = 640,
            text = "Accept Finding the Source from Krakle in Golakka Hot Springs.",
            complete = QuestState(974, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.3094, 0.5045, "Krakle",
                    "Travel to Krakle."),
            },
        },
        {
            id = "objective-4501-2-frenzied-pterrordax",
            kind = "objective",
            priority = 650,
            text = "Kill 15 Frenzied Pterrordax in found in Western side of Un'Goro.",
            dependsOn = { "accept-4501-beware-of-pterrordax" },
            complete = QuestObjective(4501, 2),
            route = {
                Point(MAP.UNGORO, 0.3240, 0.4390, "Frenzied Pterrordax",
                    "Travel to Frenzied Pterrordax."),
            },
        },
        {
            id = "objective-4503-2-webbed-pterrordax-scale",
            kind = "objective",
            priority = 660,
            text = "Collect 8 Webbed Pterrordax Scale from Pterrordax creatures in Un'Goro.",
            dependsOn = { "accept-4503-shizzle-s-flyer" },
            complete = QuestObjective(4503, 2),
            route = {
                Point(MAP.UNGORO, 0.3240, 0.4390, "Frenzied Pterrordax",
                    "Travel to Frenzied Pterrordax."),
            },
        },
        {
            id = "objective-4294-glutinous-ooze",
            kind = "objective",
            priority = 670,
            text = "Kill Glutinous Ooze and finish collecting 35 Un'Goro Slime Sample.",
            dependsOn = { "accept-4294-and-a-batch-of-ooze" },
            complete = QuestState(4294, "complete"),
            route = {
                Point(MAP.UNGORO, 0.3450, 0.3680, "Glutinous Ooze",
                    "Travel to Glutinous Ooze."),
            },
        },
        {
            id = "objective-974-finding-the-source",
            kind = "objective",
            priority = 690,
            text = "Use Krakle's Thermometer at the hottest area of Fire Plume Ridge.",
            dependsOn = { "accept-974-finding-the-source" },
            complete = QuestState(974, "complete"),
            route = {
                Point(MAP.UNGORO, 0.5277, 0.4224, "Continue toward Finding the Source",
                    "Continue toward Finding the Source."),
                Point(MAP.UNGORO, 0.5269, 0.4536, "Continue toward Finding the Source",
                    "Continue toward Finding the Source."),
                Point(MAP.UNGORO, 0.5143, 0.4731, "Continue toward Finding the Source",
                    "Continue toward Finding the Source."),
                Point(MAP.UNGORO, 0.5391, 0.4754, "Continue toward Finding the Source",
                    "Continue toward Finding the Source."),
                Point(MAP.UNGORO, 0.4970, 0.4580, "Fire Plume Ridge",
                    "Travel to Fire Plume Ridge."),
            },
        },
        {
            id = "objective-4502-volcanic-activity",
            kind = "objective",
            priority = 700,
            text = "Kill Living Blaze and collect 9 Un'Goro Ash in Fire Plume Ridge.",
            dependsOn = { "accept-4502-volcanic-activity" },
            complete = QuestState(4502, "complete"),
            route = {
                Point(MAP.UNGORO, 0.4949, 0.4755, "Living Blaze",
                    "Travel to Living Blaze."),
            },
        },
        {
            id = "turnin-4492-lost",
            kind = "turnin",
            priority = 710,
            text = "Turn in Lost! to Ringo in Fire Plume Ridge.",
            dependsOn = { "accept-4492-lost" },
            complete = QuestState(4492, "completed"),
            route = {
                Point(MAP.UNGORO, 0.5484, 0.5016, "Continue toward Lost!",
                    "Continue toward Lost!."),
                Point(MAP.UNGORO, 0.5261, 0.5118, "Continue toward Lost!",
                    "Continue toward Lost!."),
                Point(MAP.UNGORO, 0.5193, 0.4987, "Ringo",
                    "Travel to Ringo."),
            },
        },
        {
            id = "accept-4491-a-little-help-from-my-friends",
            kind = "accept",
            priority = 720,
            text = "Accept A Little Help From My Friends from Ringo in Fire Plume Ridge.",
            complete = QuestState(4491, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.5193, 0.4987, "Ringo",
                    "Travel to Ringo."),
            },
        },
        {
            id = "objective-4491-a-little-help-from-my-friends",
            kind = "objective",
            priority = 730,
            text = "Escort Ringo to Spraggle Frock at Marshal's Refuge in Marshal's Refuge.",
            dependsOn = { "accept-4491-a-little-help-from-my-friends" },
            complete = QuestState(4491, "complete"),
            route = {
                Point(MAP.UNGORO, 0.4373, 0.0759, "Ringo",
                    "Travel to Ringo."),
            },
        },
        {
            id = "turnin-4491-a-little-help-from-my-friends",
            kind = "turnin",
            priority = 740,
            text = "Turn in A Little Help From My Friends to Spraggle Frock in Marshal's Refuge.",
            dependsOn = { "objective-4491-a-little-help-from-my-friends" },
            complete = QuestState(4491, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4364, 0.0851, "Spraggle Frock",
                    "Travel to Spraggle Frock."),
            },
        },
        {
            id = "turnin-4501-beware-of-pterrordax",
            kind = "turnin",
            priority = 750,
            text = "Turn in Beware of Pterrordax to Spraggle Frock in Marshal's Refuge.",
            dependsOn = { "objective-4501-1-pterrordax", "objective-4501-1-pterrordax-2", "objective-4501-2-frenzied-pterrordax" },
            complete = QuestState(4501, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4364, 0.0851, "Spraggle Frock",
                    "Travel to Spraggle Frock."),
            },
        },
        {
            id = "turnin-4503-shizzle-s-flyer",
            kind = "turnin",
            priority = 760,
            text = "Turn in Shizzle's Flyer to Shizzle in Marshal's Refuge.",
            dependsOn = { "objective-4503-1-diemetradon", "objective-4503-2-webbed-pterrordax-scale" },
            complete = QuestState(4503, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4422, 0.1150, "Shizzle",
                    "Travel to Shizzle."),
            },
        },
        {
            id = "turnin-4145-larion-and-muigin",
            kind = "turnin",
            priority = 770,
            text = "Turn in Larion and Muigin to Larion in Marshal's Refuge.",
            dependsOn = { "objective-4145-2-bloodpetal-trapper", "objective-4145-3-bloodpetal-flayer", "objective-4145-larion-and-muigin" },
            complete = QuestState(4145, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4552, 0.0870, "Larion",
                    "Travel to Larion."),
            },
        },
        {
            id = "accept-4147-marvon-s-workshop",
            kind = "accept",
            priority = 780,
            text = "Accept Marvon's Workshop from Larion in Marshal's Refuge.",
            complete = QuestState(4147, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4552, 0.0870, "Larion",
                    "Travel to Larion."),
            },
        },
        {
            id = "turnin-3883-alien-ecology",
            kind = "turnin",
            priority = 790,
            text = "Turn in Alien Ecology to Hol'anyee Marshal in Marshal's Refuge.",
            dependsOn = { "objective-3883-alien-ecology" },
            complete = QuestState(3883, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4390, 0.0728, "Hol'anyee Marshal",
                    "Travel to Hol'anyee Marshal."),
            },
        },
        {
            id = "turnin-3881-expedition-salvation",
            kind = "turnin",
            priority = 800,
            text = "Turn in Expedition Salvation to Williden Marshal in Marshal's Refuge.",
            dependsOn = { "objective-3881-1-crate-of-foodstuffs", "objective-3881-2-research-equipment" },
            complete = QuestState(3881, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4396, 0.0712, "Williden Marshal",
                    "Travel to Williden Marshal."),
            },
        },
        {
            id = "turnin-3882-roll-the-bones",
            kind = "turnin",
            priority = 810,
            text = "Turn in Roll the Bones to Spark Nilminer in Marshal's Refuge.",
            dependsOn = { "objective-3882-roll-the-bones" },
            complete = QuestState(3882, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4348, 0.0744, "Spark Nilminer",
                    "Travel to Spark Nilminer."),
            },
        },
        {
            id = "objective-3845-it-s-a-secret-to-everybody",
            kind = "objective",
            priority = 820,
            text = "Open the A Small Pack to collect Large Compass, Curled Map Parchment and Lion-Headed Key in Marshal's Refuge.",
            dependsOn = { "accept-3845-it-s-a-secret-to-everybody" },
            complete = QuestState(3845, "complete"),
            route = {
                Point(MAP.UNGORO, 0.4361, 0.0736, "Marshal's Refuge",
                    "Travel to Marshal's Refuge."),
            },
        },
        {
            id = "turnin-3845-it-s-a-secret-to-everybody",
            kind = "turnin",
            priority = 830,
            text = "Turn in It's a Secret to Everybody to Linken in Marshal's Refuge.",
            dependsOn = { "objective-3845-it-s-a-secret-to-everybody" },
            complete = QuestState(3845, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4465, 0.0817, "Linken",
                    "Travel to Linken."),
            },
        },
        {
            id = "accept-3908-it-s-a-secret-to-everybody",
            kind = "accept",
            priority = 840,
            text = "Accept It's a Secret to Everybody from Linken in Marshal's Refuge.",
            complete = QuestState(3908, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4465, 0.0817, "Linken",
                    "Travel to Linken."),
            },
        },
        {
            id = "accept-4284-crystals-of-power",
            kind = "accept",
            priority = 850,
            text = "Accept Crystals of Power from J.D. Collie in Marshal's Refuge.",
            complete = QuestState(4284, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4353, 0.0700, "Continue toward Crystals of Power",
                    "Continue toward Crystals of Power."),
                Point(MAP.UNGORO, 0.4191, 0.0268, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
        {
            id = "objective-4284-crystals-of-power",
            kind = "objective",
            priority = 860,
            text = "Collect 7 Power Crystals of each color: red, blue, yellow, and green.",
            dependsOn = { "accept-4284-crystals-of-power" },
            complete = QuestState(4284, "complete"),
        },
        {
            id = "turnin-4284-crystals-of-power",
            kind = "turnin",
            priority = 870,
            text = "Turn in Crystals of Power to J.D. Collie in Marshal's Refuge.",
            dependsOn = { "objective-4284-crystals-of-power" },
            complete = QuestState(4284, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4191, 0.0268, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
        {
            id = "accept-4285-the-northern-pylon",
            kind = "accept",
            priority = 880,
            text = "Accept The Northern Pylon from J.D. Collie in Marshal's Refuge.",
            complete = QuestState(4285, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4191, 0.0268, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
        {
            id = "accept-4288-the-western-pylon",
            kind = "accept",
            priority = 890,
            text = "Accept The Western Pylon from J.D. Collie in Marshal's Refuge.",
            complete = QuestState(4288, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4191, 0.0268, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
        {
            id = "accept-4287-the-eastern-pylon",
            kind = "accept",
            priority = 900,
            text = "Accept The Eastern Pylon from J.D. Collie in Marshal's Refuge.",
            complete = QuestState(4287, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4191, 0.0268, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
        {
            id = "objective-4285-the-northern-pylon",
            kind = "objective",
            priority = 910,
            text = "Click on the Northern Crystal Pylon in Lakkari Tar Pits.",
            dependsOn = { "accept-4285-the-northern-pylon" },
            complete = QuestState(4285, "complete"),
            route = {
                Point(MAP.UNGORO, 0.5645, 0.1244, "Lakkari Tar Pits",
                    "Travel to Lakkari Tar Pits."),
            },
        },
        {
            id = "objective-4301-the-mighty-u-cha",
            kind = "objective",
            priority = 930,
            text = "Follow the left hand side path to find and kill U'cha in Fungal Rock.",
            dependsOn = { "accept-4301-the-mighty-u-cha" },
            complete = QuestState(4301, "complete"),
            route = {
                Point(MAP.UNGORO, 0.6577, 0.1524, "Continue toward The Mighty U'cha",
                    "Continue toward The Mighty U'cha."),
                Point(MAP.UNGORO, 0.6938, 0.1726, "Continue toward The Mighty U'cha",
                    "Continue toward The Mighty U'cha."),
                Point(MAP.UNGORO, 0.6833, 0.1290, "U'cha",
                    "Travel to U'cha."),
            },
        },
        {
            id = "objective-4287-the-eastern-pylon",
            kind = "objective",
            priority = 950,
            text = "Click on Eastern Crystal Pylon in The Marshlands.",
            dependsOn = { "accept-4287-the-eastern-pylon" },
            complete = QuestState(4287, "complete"),
            route = {
                Point(MAP.UNGORO, 0.7724, 0.5002, "The Marshlands",
                    "Travel to The Marshlands."),
            },
        },
        {
            id = "objective-4292-the-bait-for-lar-korwi",
            kind = "objective",
            priority = 970,
            text = "Use Preserved Threshadon Meat and Preserved Pheromone Mixture while standing near the flat rock to summon Lar'korwi, kill him and collect Lar'korwi's Head.",
            dependsOn = { "accept-4292-the-bait-for-lar-korwi" },
            complete = QuestState(4292, "complete"),
            route = {
                Point(MAP.UNGORO, 0.7999, 0.4984, "Lar'korwi",
                    "Travel to Lar'korwi."),
            },
        },
        {
            id = "turnin-4292-the-bait-for-lar-korwi",
            kind = "turnin",
            priority = 980,
            text = "Turn in The Bait for Lar'korwi to Torwa Pathfinder in Un'Goro.",
            dependsOn = { "objective-4292-the-bait-for-lar-korwi" },
            complete = QuestState(4292, "completed"),
            route = {
                Point(MAP.UNGORO, 0.7163, 0.7598, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "turnin-4301-the-mighty-u-cha",
            kind = "turnin",
            priority = 990,
            text = "Turn in The Mighty U'cha to Torwa Pathfinder in Un'Goro.",
            dependsOn = { "objective-4301-the-mighty-u-cha" },
            complete = QuestState(4301, "completed"),
            route = {
                Point(MAP.UNGORO, 0.7163, 0.7598, "Torwa Pathfinder",
                    "Travel to Torwa Pathfinder."),
            },
        },
        {
            id = "objective-4288-the-western-pylon",
            kind = "objective",
            priority = 1000,
            text = "Click on the Western Crystal Pylon in Golakka Hot Springs.",
            dependsOn = { "accept-4288-the-western-pylon" },
            complete = QuestState(4288, "complete"),
            route = {
                Point(MAP.UNGORO, 0.2377, 0.5904, "Golakka Hot Springs",
                    "Travel to Golakka Hot Springs."),
            },
        },
        {
            id = "turnin-974-finding-the-source",
            kind = "turnin",
            priority = 1010,
            text = "Turn in Finding the Source to Krakle in Golakka Hot Springs.",
            dependsOn = { "objective-974-finding-the-source" },
            complete = QuestState(974, "completed"),
            route = {
                Point(MAP.UNGORO, 0.3093, 0.5045, "Krakle",
                    "Travel to Krakle."),
            },
        },
        {
            id = "accept-980-the-new-springs",
            kind = "accept",
            priority = 1020,
            text = "Accept The New Springs from Krakle in Golakka Hot Springs.",
            complete = QuestState(980, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.3093, 0.5045, "Krakle",
                    "Travel to Krakle."),
            },
        },
        {
            id = "turnin-4285-the-northern-pylon",
            kind = "turnin",
            priority = 1040,
            text = "Turn in The Northern Pylon to J.D. Collie in Marshal's Refuge.",
            dependsOn = { "objective-4285-the-northern-pylon" },
            complete = QuestState(4285, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4350, 0.0697, "Continue toward The Northern Pylon",
                    "Continue toward The Northern Pylon."),
                Point(MAP.UNGORO, 0.4191, 0.0269, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
        {
            id = "turnin-4287-the-eastern-pylon",
            kind = "turnin",
            priority = 1050,
            text = "Turn in The Eastern Pylon to J.D. Collie in Marshal's Refuge.",
            dependsOn = { "objective-4287-the-eastern-pylon" },
            complete = QuestState(4287, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4191, 0.0269, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
        {
            id = "turnin-4288-the-western-pylon",
            kind = "turnin",
            priority = 1060,
            text = "Turn in The Western Pylon to J.D. Collie in Marshal's Refuge.",
            dependsOn = { "objective-4288-the-western-pylon" },
            complete = QuestState(4288, "completed"),
            route = {
                Point(MAP.UNGORO, 0.4191, 0.0269, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
        {
            id = "accept-4321-making-sense-of-it",
            kind = "accept",
            priority = 1070,
            text = "Accept Making Sense of It from J.D. Collie in Marshal's Refuge.",
            complete = QuestState(4321, "activeOrCompleted"),
            route = {
                Point(MAP.UNGORO, 0.4191, 0.0269, "J.D. Collie",
                    "Travel to J.D. Collie."),
            },
        },
    },
})
