local _, ns = ...

-- Horde Era leveling route for the Eastern Plaguelands, levels 56-57.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    EASTERN_PLAGUELANDS = 1423,
    WESTERN_PLAGUELANDS = 1422,
    UNDERCITY = 1458,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-56-57-eastern-plaguelands",
    title = "56-57 Eastern Plaguelands (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Horde" },
            { level = { min = 56 } },
        },
    },
    goals = {
        {
            id = "accept-5542-demon-dogs",
            kind = "accept",
            priority = 20,
            text = "Accept Demon Dogs from Tirion Fordring in Thondroril River.",
            complete = QuestState(5542, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0757, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5543-blood-tinged-skies",
            kind = "accept",
            priority = 30,
            text = "Accept Blood Tinged Skies from Tirion Fordring in Thondroril River.",
            complete = QuestState(5543, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0757, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5544-carrion-grubbage",
            kind = "accept",
            priority = 40,
            text = "Accept Carrion Grubbage from Tirion Fordring in Thondroril River.",
            complete = QuestState(5544, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0757, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-6022-to-kill-with-purpose",
            kind = "accept",
            priority = 60,
            text = "Accept To Kill With Purpose from Nathanos Blightcaller in The Marris Stead.",
            complete = QuestState(6022, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2657, 0.7476, "Nathanos Blightcaller",
                    "Travel to Nathanos Blightcaller."),
            },
        },
        {
            id = "accept-6042-un-life-s-little-annoyances",
            kind = "accept",
            priority = 70,
            text = "Accept Un-Life's Little Annoyances from Nathanos Blightcaller in The Marris Stead.",
            complete = QuestState(6042, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2657, 0.7476, "Nathanos Blightcaller",
                    "Travel to Nathanos Blightcaller."),
            },
        },
        {
            id = "accept-6133-the-ranger-lord-s-behest",
            kind = "accept",
            priority = 80,
            text = "Accept The Ranger Lord's Behest from Nathanos Blightcaller in The Marris Stead.",
            complete = QuestState(6133, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2657, 0.7476, "Nathanos Blightcaller",
                    "Travel to Nathanos Blightcaller."),
            },
        },
        {
            id = "accept-6024-hameya-s-plea",
            kind = "accept",
            priority = 100,
            text = "Accept Hameya's Plea in The Undercroft.",
            complete = QuestState(6024, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2791, 0.8546, "Continue toward Hameya's Plea",
                    "Continue toward Hameya's Plea."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2727, 0.8519, "The Undercroft",
                    "Travel to The Undercroft."),
            },
        },
        {
            id = "turnin-5601-sister-pamela",
            kind = "turnin",
            priority = 120,
            text = "Turn in Sister Pamela to Pamela Redpath in Darrowshire.",
            complete = QuestState(5601, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3646, 0.9078, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "accept-5149-pamela-s-doll",
            kind = "accept",
            priority = 130,
            text = "Accept Pamela's Doll from Pamela Redpath in Darrowshire.",
            complete = QuestState(5149, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3646, 0.9078, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "objective-5149-pamela-s-doll",
            kind = "objective",
            priority = 140,
            text = "Find Pamela's Doll's Left Side, Pamela's Doll's Head and Pamela's Doll's Right Side which randomly spawn in the locations of in the houses of Darrowshire. On the looting of these objects a mob may spawn which haunts the doll.",
            dependsOn = { "accept-5149-pamela-s-doll" },
            complete = QuestState(5149, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3859, 0.9197, "Pamela's Doll",
                    "Travel to Pamela's Doll."),
            },
        },
        {
            id = "objective-5149-pamela-s-doll-2",
            kind = "objective",
            priority = 150,
            text = "Find Pamela's Doll's Left Side, Pamela's Doll's Head and Pamela's Doll's Right Side which randomly spawn in the locations of in the houses of Darrowshire. On the looting of these objects a mob may spawn which haunts the doll.",
            dependsOn = { "accept-5149-pamela-s-doll" },
            complete = QuestState(5149, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3859, 0.9197, "Pamela's Doll",
                    "Travel to Pamela's Doll."),
            },
        },
        {
            id = "objective-5149-pamela-s-doll-3",
            kind = "objective",
            priority = 160,
            text = "Find Pamela's Doll's Left Side, Pamela's Doll's Head and Pamela's Doll's Right Side which randomly spawn in the locations of in the houses of Darrowshire. On the looting of these objects a mob may spawn which haunts the doll.",
            dependsOn = { "accept-5149-pamela-s-doll" },
            complete = QuestState(5149, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3859, 0.9197, "Pamela's Doll",
                    "Travel to Pamela's Doll."),
            },
        },
        {
            id = "objective-5149-pamela-s-doll-4",
            kind = "objective",
            priority = 170,
            text = "Use Pamela's Doll's Right Side to combine all the parts into Pamela's Doll.",
            dependsOn = { "accept-5149-pamela-s-doll" },
            complete = QuestState(5149, "complete"),
        },
        {
            id = "turnin-5149-pamela-s-doll",
            kind = "turnin",
            priority = 180,
            text = "Turn in Pamela's Doll to Pamela Redpath in Darrowshire.",
            dependsOn = { "objective-5149-pamela-s-doll", "objective-5149-pamela-s-doll-2", "objective-5149-pamela-s-doll-3", "objective-5149-pamela-s-doll-4" },
            complete = QuestState(5149, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3645, 0.9083, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "accept-5152-auntie-marlene",
            kind = "accept",
            priority = 190,
            text = "Accept Auntie Marlene from Pamela Redpath in Darrowshire.",
            complete = QuestState(5152, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3645, 0.9083, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "accept-5241-uncle-carlin",
            kind = "accept",
            priority = 200,
            text = "Accept Uncle Carlin from Pamela Redpath in Darrowshire.",
            complete = QuestState(5241, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3645, 0.9083, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "objective-5543-1-plaguebat",
            kind = "objective",
            priority = 210,
            text = "Kill 30 Plaguebat in Eastern Plaguelands.",
            dependsOn = { "accept-5543-blood-tinged-skies" },
            complete = QuestObjective(5543, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3577, 0.8188, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3457, 0.7346, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3281, 0.6777, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2460, 0.6822, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.1974, 0.7176, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.1829, 0.7741, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2262, 0.8033, "Plaguebat",
                    "Travel to Plaguebat."),
            },
        },
        {
            id = "objective-5542-1-plaguehound-runt",
            kind = "objective",
            priority = 220,
            text = "Kill 20 Plaguehound Runt in Eastern Plaguelands.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3577, 0.8188, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3457, 0.7346, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3281, 0.6777, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2460, 0.6822, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.1974, 0.7176, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.1829, 0.7741, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2262, 0.8033, "Plaguehound Runt",
                    "Travel to Plaguehound Runt."),
            },
        },
        {
            id = "accept-5281-the-restless-souls",
            kind = "accept",
            priority = 240,
            text = "Accept The Restless Souls from Caretaker Alen in Light's Hope Chapel.",
            complete = QuestState(5281, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7955, 0.6407, "Caretaker Alen",
                    "Travel to Caretaker Alen."),
            },
        },
        {
            id = "accept-6021-zaeldarr-the-outcast",
            kind = "accept",
            priority = 250,
            text = "Accept Zaeldarr the Outcast from Caretaker Alen in Light's Hope Chapel.",
            complete = QuestState(6021, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7961, 0.6322, "Caretaker Alen",
                    "Travel to Caretaker Alen."),
            },
        },
        {
            id = "turnin-5241-uncle-carlin",
            kind = "turnin",
            priority = 260,
            text = "Turn in Uncle Carlin to Carlin Redpath in Light's Hope Chapel.",
            dependsOn = { "accept-5241-uncle-carlin" },
            complete = QuestState(5241, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.8150, 0.5984, "Carlin Redpath",
                    "Travel to Carlin Redpath."),
            },
        },
        {
            id = "accept-5211-defenders-of-darrowshire",
            kind = "accept",
            priority = 270,
            text = "Accept Defenders of Darrowshire from Carlin Redpath in Light's Hope Chapel.",
            complete = QuestState(5211, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.8150, 0.5984, "Carlin Redpath",
                    "Travel to Carlin Redpath."),
            },
        },
        {
            id = "objective-6022-to-kill-with-purpose",
            kind = "objective",
            priority = 290,
            text = "Use the Mortar and Pestle to turn the meat into Coagulated Rot.",
            dependsOn = { "accept-6022-to-kill-with-purpose" },
            complete = QuestState(6022, "complete"),
        },
        {
            id = "objective-6042-1-noxious-plaguebat",
            kind = "objective",
            priority = 300,
            text = "Kill 20 Noxious Plaguebat in Eastern Plaguelands.",
            dependsOn = { "accept-6042-un-life-s-little-annoyances" },
            complete = QuestObjective(6042, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.5672, 0.6235, "Continue toward Noxious Plaguebat",
                    "Continue toward Noxious Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.5306, 0.5788, "Continue toward Noxious Plaguebat",
                    "Continue toward Noxious Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.5306, 0.5788, "Continue toward Noxious Plaguebat",
                    "Continue toward Noxious Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.5524, 0.5629, "Continue toward Noxious Plaguebat",
                    "Continue toward Noxious Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.5341, 0.5107, "Continue toward Noxious Plaguebat",
                    "Continue toward Noxious Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.5981, 0.5502, "Continue toward Noxious Plaguebat",
                    "Continue toward Noxious Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6489, 0.5686, "Continue toward Noxious Plaguebat",
                    "Continue toward Noxious Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7008, 0.5987, "Continue toward Noxious Plaguebat",
                    "Continue toward Noxious Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6951, 0.6725, "Noxious Plaguebat",
                    "Travel to Noxious Plaguebat."),
            },
        },
        {
            id = "objective-5542-2-plaguehound",
            kind = "objective",
            priority = 310,
            text = "Kill 5 Plaguehound in Eastern Plaguelands.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 2),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7918, 0.6876, "Continue toward Plaguehound",
                    "Continue toward Plaguehound."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7090, 0.7141, "Continue toward Plaguehound",
                    "Continue toward Plaguehound."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6497, 0.6250, "Continue toward Plaguehound",
                    "Continue toward Plaguehound."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7241, 0.5410, "Plaguehound",
                    "Travel to Plaguehound."),
            },
        },
        {
            id = "objective-5542-3-frenzied-plaguehound",
            kind = "objective",
            priority = 320,
            text = "Kill 5 Frenzied Plaguehound in Eastern Plaguelands.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 3),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7030, 0.4454, "Continue toward Frenzied Plaguehound",
                    "Continue toward Frenzied Plaguehound."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6890, 0.3651, "Frenzied Plaguehound",
                    "Travel to Frenzied Plaguehound."),
            },
        },
        {
            id = "objective-5544-carrion-grub",
            kind = "objective",
            priority = 330,
            text = "Kill Carrion Grub for 15 Slab of Carrion Worm Meat.",
            dependsOn = { "accept-5544-carrion-grubbage" },
            complete = QuestState(5544, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.6790, 0.6100, "Continue toward Carrion Grub",
                    "Continue toward Carrion Grub."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6640, 0.6760, "Continue toward Carrion Grub",
                    "Continue toward Carrion Grub."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7300, 0.7180, "Carrion Grub",
                    "Travel to Carrion Grub."),
            },
        },
        {
            id = "objective-5211-1-diseased-flayer",
            kind = "objective",
            priority = 350,
            text = "Kill Diseased Flayer, then speak to the Darrowshire Spirit that spawns to free the spirit. You can finish this later in Stratholme if this area is already cleared.",
            dependsOn = { "accept-5211-defenders-of-darrowshire" },
            complete = QuestObjective(5211, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.6596, 0.3986, "Diseased Flayer",
                    "Travel to Diseased Flayer."),
            },
        },
        {
            id = "objective-6024-1-infiltrator-hameya",
            kind = "objective",
            priority = 370,
            text = "Go around the graveyard and kill Infiltrator Hameya and collect Hameya's Key in Zul'Mashar.",
            dependsOn = { "accept-6024-hameya-s-plea" },
            complete = QuestObjective(6024, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.6686, 0.2145, "Continue toward Infiltrator Hameya",
                    "Continue toward Infiltrator Hameya."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6826, 0.2105, "Continue toward Infiltrator Hameya",
                    "Continue toward Infiltrator Hameya."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7077, 0.1607, "Infiltrator Hameya",
                    "Travel to Infiltrator Hameya."),
            },
        },
        {
            id = "objective-6042-monstrous-plaguebat",
            kind = "objective",
            priority = 390,
            text = "Kill 10 Monstrous Plaguebat near Eastwall Tower.",
            dependsOn = { "accept-6042-un-life-s-little-annoyances" },
            complete = QuestState(6042, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.6996, 0.4967, "Continue toward Monstrous Plaguebat",
                    "Continue toward Monstrous Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7040, 0.4184, "Continue toward Monstrous Plaguebat",
                    "Continue toward Monstrous Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6367, 0.4034, "Continue toward Monstrous Plaguebat",
                    "Continue toward Monstrous Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6052, 0.4908, "Monstrous Plaguebat",
                    "Travel to Monstrous Plaguebat."),
            },
        },
        {
            id = "objective-6133-4-quel-thalas-registry",
            kind = "objective",
            priority = 410,
            text = "Collect the Quel'Thalas Registry from the bench seat in Quel'Lithien Lodge. It is guarded by 2-3 blood elves. Try grabbing the book from the other side of the wall.",
            dependsOn = { "accept-6133-the-ranger-lord-s-behest" },
            complete = QuestObjective(6133, 4),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.5103, 0.1625, "Continue toward Quel'Thalas Registry",
                    "Continue toward Quel'Thalas Registry."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.5285, 0.1681, "Continue toward Quel'Thalas Registry",
                    "Continue toward Quel'Thalas Registry."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.5215, 0.1834, "Quel'Lithien Lodge",
                    "Travel to Quel'Lithien Lodge."),
            },
        },
        {
            id = "objective-6133-the-ranger-lord-s-behest",
            kind = "objective",
            priority = 420,
            text = "Kill the required Blood Elfs in Quel'Lithien Lodge.",
            dependsOn = { "accept-6133-the-ranger-lord-s-behest" },
            complete = QuestState(6133, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.5281, 0.1592, "Wretched Pathstrider",
                    "Travel to Wretched Pathstrider."),
            },
        },
        {
            id = "objective-5901-a-plague-upon-thee",
            kind = "objective",
            priority = 430,
            text = "Check each waypoint and click on Termite Mound to collect 100 Plagueland Termites in Stratholme.",
            complete = QuestState(5901, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.4583, 0.3401, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.4287, 0.3426, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.4217, 0.3829, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.4062, 0.3139, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.4128, 0.2540, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.4365, 0.2414, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3972, 0.2307, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3558, 0.2372, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3381, 0.2578, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3041, 0.2157, "Continue toward A Plague Upon Thee",
                    "Continue toward A Plague Upon Thee."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3000, 0.2295, "Stratholme",
                    "Travel to Stratholme."),
            },
        },
        {
            id = "objective-5211-defenders-of-darrowshire",
            kind = "objective",
            priority = 440,
            text = "Kill Cannibal Ghoul then speak to Darrowshire Spirit that will spawn after the kill to free 15 spirits in Stratholme.",
            dependsOn = { "accept-5211-defenders-of-darrowshire" },
            complete = QuestState(5211, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3558, 0.2372, "Continue toward Defenders of Darrowshire",
                    "Continue toward Defenders of Darrowshire."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3381, 0.2578, "Continue toward Defenders of Darrowshire",
                    "Continue toward Defenders of Darrowshire."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3041, 0.2157, "Continue toward Defenders of Darrowshire",
                    "Continue toward Defenders of Darrowshire."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3000, 0.2295, "Cannibal Ghoul",
                    "Travel to Cannibal Ghoul."),
            },
        },
        {
            id = "turnin-5281-the-restless-souls",
            kind = "turnin",
            priority = 460,
            text = "Turn in The Restless Souls to Egan in Terrordale.",
            dependsOn = { "accept-5281-the-restless-souls" },
            complete = QuestState(5281, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1446, 0.3375, "Egan",
                    "Travel to Egan."),
            },
        },
        {
            id = "accept-6164-augustus-receipt-book",
            kind = "accept",
            priority = 470,
            text = "Accept Augustus' Receipt Book from Augustus the Touched in Terrordale.",
            complete = QuestState(6164, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1446, 0.3351, "Augustus the Touched",
                    "Travel to Augustus the Touched."),
            },
        },
        {
            id = "objective-6164-augustus-receipt-book",
            kind = "objective",
            priority = 480,
            text = "Collect Augustus' Receipt Book inside the inn in Terrordale.",
            dependsOn = { "accept-6164-augustus-receipt-book" },
            complete = QuestState(6164, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1743, 0.3107, "Terrordale",
                    "Travel to Terrordale."),
            },
        },
        {
            id = "turnin-6164-augustus-receipt-book",
            kind = "turnin",
            priority = 490,
            text = "Turn in Augustus' Receipt Book to Augustus the Touched in Terrordale.",
            dependsOn = { "objective-6164-augustus-receipt-book" },
            complete = QuestState(6164, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1446, 0.3351, "Augustus the Touched",
                    "Travel to Augustus the Touched."),
            },
        },
        {
            id = "objective-9124-crypt-fiend-parts",
            kind = "objective",
            priority = 510,
            text = "Clear your way through Terrorweb Tunnel, kill all the spiders for 30 Crypt Fiend Parts for a later quest 'Cryptstalker Armor Doesn't Make Itself... '.",
            complete = QuestState(9124, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0706, 0.4139, "Crypt Stalker",
                    "Travel to Crypt Stalker."),
            },
        },
        {
            id = "turnin-5542-demon-dogs",
            kind = "turnin",
            priority = 520,
            text = "Turn in Demon Dogs to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5542-1-plaguehound-runt", "objective-5542-2-plaguehound", "objective-5542-3-frenzied-plaguehound" },
            complete = QuestState(5542, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0706, 0.4139, "Continue toward Demon Dogs",
                    "Continue toward Demon Dogs."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.0754, 0.4367, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-5544-carrion-grubbage",
            kind = "turnin",
            priority = 530,
            text = "Turn in Carrion Grubbage to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5544-carrion-grub" },
            complete = QuestState(5544, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0754, 0.4367, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-5543-blood-tinged-skies",
            kind = "turnin",
            priority = 540,
            text = "Turn in Blood Tinged Skies in Thondroril River.",
            dependsOn = { "objective-5543-1-plaguebat" },
            complete = QuestState(5543, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0754, 0.4367, "Thondroril River",
                    "Travel to Thondroril River."),
            },
        },
        {
            id = "accept-5742-redemption",
            kind = "accept",
            priority = 550,
            text = "Accept Redemption from Tirion Fordring in Thondroril River.",
            complete = QuestState(5742, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0754, 0.4367, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "objective-5742-redemption",
            kind = "objective",
            priority = 560,
            text = "Type /sit next to Tirion Fordring and speak to him to complete the quest in Thondroril River The speech option won't appear unless your character is a sitting position.",
            dependsOn = { "accept-5742-redemption" },
            complete = QuestState(5742, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0753, 0.4368, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-5742-redemption",
            kind = "turnin",
            priority = 570,
            text = "Turn in Redemption to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5742-redemption" },
            complete = QuestState(5742, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0753, 0.4368, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5781-of-forgotten-memories",
            kind = "accept",
            priority = 580,
            text = "Accept Of Forgotten Memories from Tirion Fordring in Thondroril River.",
            complete = QuestState(5781, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0753, 0.4368, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-6022-to-kill-with-purpose",
            kind = "turnin",
            priority = 600,
            text = "Turn in To Kill With Purpose to Nathanos Blightcaller in The Marris Stead.",
            dependsOn = { "objective-6022-to-kill-with-purpose" },
            complete = QuestState(6022, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2654, 0.7472, "Nathanos Blightcaller",
                    "Travel to Nathanos Blightcaller."),
            },
        },
        {
            id = "turnin-6042-un-life-s-little-annoyances",
            kind = "turnin",
            priority = 610,
            text = "Turn in Un-Life's Little Annoyances to Nathanos Blightcaller in The Marris Stead.",
            dependsOn = { "objective-6042-1-noxious-plaguebat", "objective-6042-monstrous-plaguebat" },
            complete = QuestState(6042, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2654, 0.7472, "Nathanos Blightcaller",
                    "Travel to Nathanos Blightcaller."),
            },
        },
        {
            id = "turnin-6133-the-ranger-lord-s-behest",
            kind = "turnin",
            priority = 620,
            text = "Turn in The Ranger Lord's Behest to Nathanos Blightcaller in The Marris Stead.",
            dependsOn = { "objective-6133-4-quel-thalas-registry", "objective-6133-the-ranger-lord-s-behest" },
            complete = QuestState(6133, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2654, 0.7472, "Nathanos Blightcaller",
                    "Travel to Nathanos Blightcaller."),
            },
        },
        {
            id = "objective-6021-zaeldarr-the-outcast",
            kind = "objective",
            priority = 640,
            text = "Kill Zaeldarr the Outcast in The Undercroft.",
            dependsOn = { "accept-6021-zaeldarr-the-outcast" },
            complete = QuestState(6021, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2747, 0.8493, "Zaeldarr the Outcast",
                    "Travel to Zaeldarr the Outcast."),
            },
        },
        {
            id = "turnin-6024-hameya-s-plea",
            kind = "turnin",
            priority = 650,
            text = "Turn in Hameya's Plea in The Undercroft.",
            dependsOn = { "objective-6024-1-infiltrator-hameya" },
            complete = QuestState(6024, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2784, 0.8536, "The Undercroft",
                    "Travel to The Undercroft."),
            },
        },
        {
            id = "objective-5781-of-forgotten-memories",
            kind = "objective",
            priority = 660,
            text = "Click the Loose Dirt Mound to summon Mercutio Filthgorger, kill him, and collect Taelan's Hammer. He spawns first, so you can pull him away from his bodyguards. This is an elite. Bring a group.",
            dependsOn = { "accept-5781-of-forgotten-memories" },
            complete = QuestState(5781, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2822, 0.8621, "Mercutio Filthgorger",
                    "Travel to Mercutio Filthgorger."),
            },
        },
        {
            id = "turnin-5781-of-forgotten-memories",
            kind = "turnin",
            priority = 680,
            text = "Turn in Of Forgotten Memories to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5781-of-forgotten-memories" },
            complete = QuestState(5781, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0756, 0.4369, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5845-of-lost-honor",
            kind = "accept",
            priority = 690,
            text = "Accept Of Lost Honor from Tirion Fordring in Thondroril River.",
            complete = QuestState(5845, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0756, 0.4369, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-6021-zaeldarr-the-outcast",
            kind = "turnin",
            priority = 710,
            text = "Turn in Zaeldarr the Outcast to Caretaker Alen in Light's Hope Chapel.",
            dependsOn = { "objective-6021-zaeldarr-the-outcast" },
            complete = QuestState(6021, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7966, 0.6362, "Caretaker Alen",
                    "Travel to Caretaker Alen."),
            },
        },
        {
            id = "turnin-5211-defenders-of-darrowshire",
            kind = "turnin",
            priority = 720,
            text = "Turn in Defenders of Darrowshire to Carlin Redpath in Light's Hope Chapel.",
            dependsOn = { "objective-5211-1-diseased-flayer", "objective-5211-defenders-of-darrowshire" },
            complete = QuestState(5211, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.8150, 0.5979, "Carlin Redpath",
                    "Travel to Carlin Redpath."),
            },
        },
        {
            id = "objective-5845-of-lost-honor",
            kind = "objective",
            priority = 740,
            text = "Collect Symbol of Lost Honor in the middle of the lake in Northdale.",
            dependsOn = { "accept-5845-of-lost-honor" },
            complete = QuestState(5845, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7128, 0.3397, "Northdale",
                    "Travel to Northdale."),
            },
        },
        {
            id = "turnin-5845-of-lost-honor",
            kind = "turnin",
            priority = 750,
            text = "Turn in Of Lost Honor to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5845-of-lost-honor" },
            complete = QuestState(5845, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0758, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5846-of-love-and-family",
            kind = "accept",
            priority = 760,
            text = "Accept Of Love and Family from Tirion Fordring in Thondroril River.",
            complete = QuestState(5846, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0758, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-5846-of-love-and-family",
            kind = "turnin",
            priority = 780,
            text = "Turn in Of Love and Family to Artist Renfray in Caer Darrow.",
            dependsOn = { "accept-5846-of-love-and-family" },
            complete = QuestState(5846, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.6576, 0.7536, "Artist Renfray",
                    "Travel to Artist Renfray."),
            },
        },
        {
            id = "accept-5049-the-jeremiah-blues",
            kind = "accept",
            priority = 790,
            conditions = {
                all = {
                    { quest = { id = 5023, state = "completed" } },
                },
            },
            text = "Accept The Jeremiah Blues from Royal Overseer Bauhaus in Trade Quarter.",
            complete = QuestState(5049, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.6981, 0.4323, "Royal Overseer Bauhaus",
                    "Travel to Royal Overseer Bauhaus."),
            },
        },
        {
            id = "turnin-5049-the-jeremiah-blues",
            kind = "turnin",
            priority = 800,
            conditions = {
                all = {
                    { quest = { id = 5023, state = "completed" } },
                },
            },
            text = "Turn in The Jeremiah Blues to Jeremiah Payson in Trade Quarter.",
            dependsOn = { "accept-5049-the-jeremiah-blues" },
            complete = QuestState(5049, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.6758, 0.4404, "Jeremiah Payson",
                    "Travel to Jeremiah Payson."),
            },
        },
        {
            id = "accept-5050-good-luck-charm",
            kind = "accept",
            priority = 810,
            conditions = {
                all = {
                    { quest = { id = 5023, state = "completed" } },
                },
            },
            text = "Accept Good Luck Charm from Jeremiah Payson in Trade Quarter.",
            complete = QuestState(5050, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.6758, 0.4404, "Jeremiah Payson",
                    "Travel to Jeremiah Payson."),
            },
        },
    },
})
