local _, ns = ...

-- Alliance Era leveling route for the Eastern Plaguelands, levels 57-58.
-- This follows the classic route and is not rewritten for Forever yet.
-- Grind stops and flight-point pickups are not part of this route.
-- Coordinates have not been validated in the Forever client.

local MAP = {
    EASTERN_PLAGUELANDS = 1423,
    WESTERN_PLAGUELANDS = 1422,
}

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index)
    return { questObjective = { id = questID, index = index } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "leveling-era-57-58-eastern-plaguelands",
    title = "57-58 Eastern Plaguelands (Era)",
    category = "Leveling Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Alliance" },
            { level = { min = 57 } },
        },
    },
    goals = {
        {
            id = "note-switch-guide",
            kind = "note",
            priority = 10,
            conditions = {
                all = {
                    { ["not"] = { quest = { id = 6185, state = "activeOrCompleted" } } },
                },
            },
            text = "Switch and complete #1422(56-57)#1422(56-57)\") before starting this guide.",
        },
        {
            id = "accept-5542-demon-dogs",
            kind = "accept",
            priority = 30,
            text = "Accept Demon Dogs from Tirion Fordring in Thondroril River.",
            complete = QuestState(5542, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0757, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5543-blood-tinged-skies",
            kind = "accept",
            priority = 40,
            text = "Accept Blood Tinged Skies from Tirion Fordring in Thondroril River.",
            complete = QuestState(5543, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0757, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5544-carrion-grubbage",
            kind = "accept",
            priority = 50,
            text = "Accept Carrion Grubbage from Tirion Fordring in Thondroril River.",
            complete = QuestState(5544, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0757, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-6024-hameya-s-plea",
            kind = "accept",
            priority = 70,
            text = "Accept Hameya's Plea in The Undercroft.",
            complete = QuestState(6024, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2791, 0.8546, "Continue toward Hameya's Plea",
                    "Continue toward Hameya's Plea."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2727, 0.8519, "The Undercroft",
                    "Travel to The Undercroft."),
            },
        },
        {
            id = "turnin-5601-sister-pamela",
            kind = "turnin",
            priority = 90,
            text = "Turn in Sister Pamela to Pamela Redpath in Darrowshire.",
            complete = QuestState(5601, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3646, 0.9078, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "accept-5149-pamela-s-doll",
            kind = "accept",
            priority = 100,
            text = "Accept Pamela's Doll from Pamela Redpath in Darrowshire.",
            complete = QuestState(5149, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3646, 0.9078, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "objective-5149-pamela-s-doll",
            kind = "objective",
            priority = 110,
            text = "Find Pamela's Doll's Left Side, Pamela's Doll's Head and Pamela's Doll's Right Side which randomly spawn in the locations of in the houses of Darrowshire. On the looting of these objects a mob may spawn which haunts the doll.",
            dependsOn = { "accept-5149-pamela-s-doll" },
            complete = QuestState(5149, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3859, 0.9197, "Pamela's Doll",
                    "Travel to Pamela's Doll."),
            },
        },
        {
            id = "objective-5149-pamela-s-doll-2",
            kind = "objective",
            priority = 120,
            text = "Find Pamela's Doll's Left Side, Pamela's Doll's Head and Pamela's Doll's Right Side which randomly spawn in the locations of in the houses of Darrowshire. On the looting of these objects a mob may spawn which haunts the doll.",
            dependsOn = { "accept-5149-pamela-s-doll" },
            complete = QuestState(5149, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3859, 0.9197, "Pamela's Doll",
                    "Travel to Pamela's Doll."),
            },
        },
        {
            id = "objective-5149-pamela-s-doll-3",
            kind = "objective",
            priority = 130,
            text = "Find Pamela's Doll's Left Side, Pamela's Doll's Head and Pamela's Doll's Right Side which randomly spawn in the locations of in the houses of Darrowshire. On the looting of these objects a mob may spawn which haunts the doll.",
            dependsOn = { "accept-5149-pamela-s-doll" },
            complete = QuestState(5149, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3859, 0.9197, "Pamela's Doll",
                    "Travel to Pamela's Doll."),
            },
        },
        {
            id = "objective-5149-pamela-s-doll-4",
            kind = "objective",
            priority = 140,
            text = "Use Pamela's Doll's Right Side to combine all the parts into Pamela's Doll.",
            dependsOn = { "accept-5149-pamela-s-doll" },
            complete = QuestState(5149, "complete"),
        },
        {
            id = "turnin-5149-pamela-s-doll",
            kind = "turnin",
            priority = 150,
            text = "Turn in Pamela's Doll to Pamela Redpath in Darrowshire.",
            dependsOn = { "objective-5149-pamela-s-doll", "objective-5149-pamela-s-doll-2", "objective-5149-pamela-s-doll-3", "objective-5149-pamela-s-doll-4" },
            complete = QuestState(5149, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3645, 0.9083, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "accept-5152-auntie-marlene",
            kind = "accept",
            priority = 160,
            text = "Accept Auntie Marlene from Pamela Redpath in Darrowshire.",
            complete = QuestState(5152, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3645, 0.9083, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "accept-5241-uncle-carlin",
            kind = "accept",
            priority = 170,
            text = "Accept Uncle Carlin from Pamela Redpath in Darrowshire.",
            complete = QuestState(5241, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3645, 0.9083, "Pamela Redpath",
                    "Travel to Pamela Redpath."),
            },
        },
        {
            id = "objective-5543-1-plaguebat",
            kind = "objective",
            priority = 180,
            text = "Kill 30 Plaguebat in Eastern Plaguelands.",
            dependsOn = { "accept-5543-blood-tinged-skies" },
            complete = QuestObjective(5543, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3577, 0.8188, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3457, 0.7346, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3281, 0.6777, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2460, 0.6822, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.1974, 0.7176, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.1829, 0.7741, "Continue toward Plaguebat",
                    "Continue toward Plaguebat."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2262, 0.8033, "Plaguebat",
                    "Travel to Plaguebat."),
            },
        },
        {
            id = "objective-5542-1-plaguehound-runt",
            kind = "objective",
            priority = 190,
            text = "Kill 20 Plaguehound Runt in Eastern Plaguelands.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3577, 0.8188, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3457, 0.7346, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3281, 0.6777, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2460, 0.6822, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.1974, 0.7176, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.1829, 0.7741, "Continue toward Plaguehound Runt",
                    "Continue toward Plaguehound Runt."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.2262, 0.8033, "Plaguehound Runt",
                    "Travel to Plaguehound Runt."),
            },
        },
        {
            id = "accept-5281-the-restless-souls",
            kind = "accept",
            priority = 210,
            text = "Accept The Restless Souls from Caretaker Alen in Light's Hope Chapel.",
            complete = QuestState(5281, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7955, 0.6407, "Caretaker Alen",
                    "Travel to Caretaker Alen."),
            },
        },
        {
            id = "accept-6021-zaeldarr-the-outcast",
            kind = "accept",
            priority = 220,
            text = "Accept Zaeldarr the Outcast from Caretaker Alen in Light's Hope Chapel.",
            complete = QuestState(6021, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7961, 0.6322, "Caretaker Alen",
                    "Travel to Caretaker Alen."),
            },
        },
        {
            id = "turnin-5241-uncle-carlin",
            kind = "turnin",
            priority = 230,
            text = "Turn in Uncle Carlin to Carlin Redpath in Light's Hope Chapel.",
            dependsOn = { "accept-5241-uncle-carlin" },
            complete = QuestState(5241, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.8150, 0.5984, "Carlin Redpath",
                    "Travel to Carlin Redpath."),
            },
        },
        {
            id = "accept-5211-defenders-of-darrowshire",
            kind = "accept",
            priority = 240,
            text = "Accept Defenders of Darrowshire from Carlin Redpath in Light's Hope Chapel.",
            complete = QuestState(5211, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.8150, 0.5984, "Carlin Redpath",
                    "Travel to Carlin Redpath."),
            },
        },
        {
            id = "objective-5542-2-plaguehound",
            kind = "objective",
            priority = 250,
            text = "Kill 5 Plaguehound in Eastern Plaguelands.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 2),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7918, 0.6876, "Continue toward Plaguehound",
                    "Continue toward Plaguehound."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7090, 0.7141, "Continue toward Plaguehound",
                    "Continue toward Plaguehound."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6497, 0.6250, "Continue toward Plaguehound",
                    "Continue toward Plaguehound."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7241, 0.5410, "Plaguehound",
                    "Travel to Plaguehound."),
            },
        },
        {
            id = "objective-5542-3-frenzied-plaguehound",
            kind = "objective",
            priority = 260,
            text = "Kill 5 Frenzied Plaguehound in Eastern Plaguelands.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 3),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7030, 0.4454, "Continue toward Frenzied Plaguehound",
                    "Continue toward Frenzied Plaguehound."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6890, 0.3651, "Frenzied Plaguehound",
                    "Travel to Frenzied Plaguehound."),
            },
        },
        {
            id = "objective-5544-carrion-grub",
            kind = "objective",
            priority = 270,
            text = "Kill Carrion Grub for 15 Slab of Carrion Worm Meat.",
            dependsOn = { "accept-5544-carrion-grubbage" },
            complete = QuestState(5544, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.6790, 0.6100, "Continue toward Carrion Grub",
                    "Continue toward Carrion Grub."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6640, 0.6760, "Continue toward Carrion Grub",
                    "Continue toward Carrion Grub."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7300, 0.7180, "Carrion Grub",
                    "Travel to Carrion Grub."),
            },
        },
        {
            id = "objective-5211-1-diseased-flayer",
            kind = "objective",
            priority = 290,
            text = "Kill Diseased Flayer, then speak to the Darrowshire Spirit that spawns to free the spirit. You can finish this later in Stratholme if this area is already cleared.",
            dependsOn = { "accept-5211-defenders-of-darrowshire" },
            complete = QuestObjective(5211, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.6596, 0.3986, "Diseased Flayer",
                    "Travel to Diseased Flayer."),
            },
        },
        {
            id = "objective-6024-1-infiltrator-hameya",
            kind = "objective",
            priority = 310,
            text = "Go around the graveyard and kill Infiltrator Hameya and collect Hameya's Key in Zul'Mashar.",
            dependsOn = { "accept-6024-hameya-s-plea" },
            complete = QuestObjective(6024, 1),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.6686, 0.2145, "Continue toward Infiltrator Hameya",
                    "Continue toward Infiltrator Hameya."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.6826, 0.2105, "Continue toward Infiltrator Hameya",
                    "Continue toward Infiltrator Hameya."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.7077, 0.1607, "Infiltrator Hameya",
                    "Travel to Infiltrator Hameya."),
            },
        },
        {
            id = "turnin-5245-troubled-spirits-of-kel-theril",
            kind = "turnin",
            priority = 330,
            text = "Turn in Troubled Spirits of Kel'Theril to Aurora Skycaller in Quel'Lithien Lodge.",
            complete = QuestState(5245, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.5354, 0.2204, "Aurora Skycaller",
                    "Travel to Aurora Skycaller."),
            },
        },
        {
            id = "accept-5246-fragments-of-the-past",
            kind = "accept",
            priority = 340,
            text = "Accept Fragments of the Past from Aurora Skycaller in Quel'Lithien Lodge.",
            complete = QuestState(5246, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.5354, 0.2204, "Aurora Skycaller",
                    "Travel to Aurora Skycaller."),
            },
        },
        {
            id = "objective-5211-defenders-of-darrowshire",
            kind = "objective",
            priority = 350,
            text = "Kill Cannibal Ghoul then speak to Darrowshire Spirit that will spawn after the kill to free 15 spirits in Stratholme.",
            dependsOn = { "accept-5211-defenders-of-darrowshire" },
            complete = QuestState(5211, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.3558, 0.2372, "Continue toward Defenders of Darrowshire",
                    "Continue toward Defenders of Darrowshire."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3381, 0.2578, "Continue toward Defenders of Darrowshire",
                    "Continue toward Defenders of Darrowshire."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3041, 0.2157, "Continue toward Defenders of Darrowshire",
                    "Continue toward Defenders of Darrowshire."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.3000, 0.2295, "Cannibal Ghoul",
                    "Travel to Cannibal Ghoul."),
            },
        },
        {
            id = "turnin-5281-the-restless-souls",
            kind = "turnin",
            priority = 370,
            text = "Turn in The Restless Souls to Egan in Terrordale.",
            dependsOn = { "accept-5281-the-restless-souls" },
            complete = QuestState(5281, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1446, 0.3375, "Egan",
                    "Travel to Egan."),
            },
        },
        {
            id = "accept-5282-the-restless-souls",
            kind = "accept",
            priority = 380,
            text = "Accept The Restless Souls from Egan in Terrordale.",
            complete = QuestState(5282, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1446, 0.3375, "Egan",
                    "Travel to Egan."),
            },
        },
        {
            id = "accept-6164-augustus-receipt-book",
            kind = "accept",
            priority = 390,
            text = "Accept Augustus' Receipt Book from Augustus the Touched in Terrordale.",
            complete = QuestState(6164, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1446, 0.3351, "Augustus the Touched",
                    "Travel to Augustus the Touched."),
            },
        },
        {
            id = "objective-6164-augustus-receipt-book",
            kind = "objective",
            priority = 400,
            text = "Collect Augustus' Receipt Book inside the inn in Terrordale.",
            dependsOn = { "accept-6164-augustus-receipt-book" },
            complete = QuestState(6164, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1743, 0.3107, "Terrordale",
                    "Travel to Terrordale."),
            },
        },
        {
            id = "turnin-6164-augustus-receipt-book",
            kind = "turnin",
            priority = 410,
            text = "Turn in Augustus' Receipt Book to Augustus the Touched in Terrordale.",
            dependsOn = { "objective-6164-augustus-receipt-book" },
            complete = QuestState(6164, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.1446, 0.3351, "Augustus the Touched",
                    "Travel to Augustus the Touched."),
            },
        },
        {
            id = "objective-9124-crypt-fiend-parts",
            kind = "objective",
            priority = 430,
            text = "Clear your way through Terrorweb Tunnel, kill all the spiders for 30 Crypt Fiend Parts for a later quest 'Cryptstalker Armor Doesn't Make Itself... '.",
            complete = QuestState(9124, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0706, 0.4139, "Crypt Stalker",
                    "Travel to Crypt Stalker."),
            },
        },
        {
            id = "turnin-5542-demon-dogs",
            kind = "turnin",
            priority = 440,
            text = "Turn in Demon Dogs to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5542-1-plaguehound-runt", "objective-5542-2-plaguehound", "objective-5542-3-frenzied-plaguehound" },
            complete = QuestState(5542, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0706, 0.4139, "Continue toward Demon Dogs",
                    "Continue toward Demon Dogs."),
                Point(MAP.EASTERN_PLAGUELANDS, 0.0754, 0.4367, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-5544-carrion-grubbage",
            kind = "turnin",
            priority = 450,
            text = "Turn in Carrion Grubbage to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5544-carrion-grub" },
            complete = QuestState(5544, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0754, 0.4367, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-5543-blood-tinged-skies",
            kind = "turnin",
            priority = 460,
            text = "Turn in Blood Tinged Skies in Thondroril River.",
            dependsOn = { "objective-5543-1-plaguebat" },
            complete = QuestState(5543, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0754, 0.4367, "Thondroril River",
                    "Travel to Thondroril River."),
            },
        },
        {
            id = "accept-5742-redemption",
            kind = "accept",
            priority = 470,
            text = "Accept Redemption from Tirion Fordring in Thondroril River.",
            complete = QuestState(5742, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0754, 0.4367, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "objective-5742-redemption",
            kind = "objective",
            priority = 480,
            text = "Type /sit next to Tirion Fordring and speak to him to complete the quest in Thondroril River The speech option won't appear unless your character is a sitting position.",
            dependsOn = { "accept-5742-redemption" },
            complete = QuestState(5742, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0753, 0.4368, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-5742-redemption",
            kind = "turnin",
            priority = 490,
            text = "Turn in Redemption to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5742-redemption" },
            complete = QuestState(5742, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0753, 0.4368, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5781-of-forgotten-memories",
            kind = "accept",
            priority = 500,
            text = "Accept Of Forgotten Memories from Tirion Fordring in Thondroril River.",
            complete = QuestState(5781, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0753, 0.4368, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "objective-6021-zaeldarr-the-outcast",
            kind = "objective",
            priority = 520,
            text = "Kill Zaeldarr the Outcast in The Undercroft.",
            dependsOn = { "accept-6021-zaeldarr-the-outcast" },
            complete = QuestState(6021, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2747, 0.8493, "Zaeldarr the Outcast",
                    "Travel to Zaeldarr the Outcast."),
            },
        },
        {
            id = "turnin-6024-hameya-s-plea",
            kind = "turnin",
            priority = 530,
            text = "Turn in Hameya's Plea in The Undercroft.",
            dependsOn = { "objective-6024-1-infiltrator-hameya" },
            complete = QuestState(6024, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2784, 0.8536, "The Undercroft",
                    "Travel to The Undercroft."),
            },
        },
        {
            id = "objective-5781-of-forgotten-memories",
            kind = "objective",
            priority = 540,
            text = "Click the Loose Dirt Mound to summon Mercutio Filthgorger, kill him, and collect Taelan's Hammer. He spawns first, so you can pull him away from his bodyguards. This is an elite. Bring a group.",
            dependsOn = { "accept-5781-of-forgotten-memories" },
            complete = QuestState(5781, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.2822, 0.8621, "Mercutio Filthgorger",
                    "Travel to Mercutio Filthgorger."),
            },
        },
        {
            id = "turnin-5781-of-forgotten-memories",
            kind = "turnin",
            priority = 560,
            text = "Turn in Of Forgotten Memories to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5781-of-forgotten-memories" },
            complete = QuestState(5781, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0756, 0.4369, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5845-of-lost-honor",
            kind = "accept",
            priority = 570,
            text = "Accept Of Lost Honor from Tirion Fordring in Thondroril River.",
            complete = QuestState(5845, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0756, 0.4369, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-6021-zaeldarr-the-outcast",
            kind = "turnin",
            priority = 590,
            text = "Turn in Zaeldarr the Outcast to Caretaker Alen in Light's Hope Chapel.",
            dependsOn = { "objective-6021-zaeldarr-the-outcast" },
            complete = QuestState(6021, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7966, 0.6362, "Caretaker Alen",
                    "Travel to Caretaker Alen."),
            },
        },
        {
            id = "turnin-5211-defenders-of-darrowshire",
            kind = "turnin",
            priority = 600,
            text = "Turn in Defenders of Darrowshire to Carlin Redpath in Light's Hope Chapel.",
            dependsOn = { "objective-5211-1-diseased-flayer", "objective-5211-defenders-of-darrowshire" },
            complete = QuestState(5211, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.8150, 0.5979, "Carlin Redpath",
                    "Travel to Carlin Redpath."),
            },
        },
        {
            id = "objective-5845-of-lost-honor",
            kind = "objective",
            priority = 620,
            text = "Collect Symbol of Lost Honor in the middle of the lake in Northdale.",
            dependsOn = { "accept-5845-of-lost-honor" },
            complete = QuestState(5845, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.7128, 0.3397, "Northdale",
                    "Travel to Northdale."),
            },
        },
        {
            id = "turnin-5845-of-lost-honor",
            kind = "turnin",
            priority = 630,
            text = "Turn in Of Lost Honor to Tirion Fordring in Thondroril River.",
            dependsOn = { "objective-5845-of-lost-honor" },
            complete = QuestState(5845, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0758, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "accept-5846-of-love-and-family",
            kind = "accept",
            priority = 640,
            text = "Accept Of Love and Family from Tirion Fordring in Thondroril River.",
            complete = QuestState(5846, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.0758, 0.4372, "Tirion Fordring",
                    "Travel to Tirion Fordring."),
            },
        },
        {
            id = "turnin-5846-of-love-and-family",
            kind = "turnin",
            priority = 660,
            text = "Turn in Of Love and Family to Artist Renfray in Caer Darrow.",
            dependsOn = { "accept-5846-of-love-and-family" },
            complete = QuestState(5846, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.6576, 0.7536, "Artist Renfray",
                    "Travel to Artist Renfray."),
            },
        },
    },
})
