local _, ns = ...

local MAP = {
    IRONFORGE = 1455,
    DARNASSUS = 1457,
    DARKSHORE = 1439,
    ASHENVALE = 1440,
    THUNDER_BLUFF = 1456,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-blackfathom-deeps-raid",
    title = "Blackfathom Deeps Raid",
    category = "Raid Quests",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 25 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-78923-knowledge-in-the-deeps",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Accept Knowledge in the Deeps from Gerrig Bonegrip.",
            complete = QuestState(78923, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.506, 0.062, "Gerrig Bonegrip", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-78925-twilight-falls",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Accept Twilight Falls from Argent Guard Manados.",
            complete = QuestState(78925, "activeOrCompleted"),
            route = {
                Point(MAP.DARNASSUS, 0.552, 0.236, "Argent Guard Manados", "Travel to Darnassus."),
            },
        },
        {
            id = "accept-78926-researching-the-corruption",
            kind = "accept",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Accept Researching the Corruption from Gershala Nightwhisper.",
            complete = QuestState(78926, "activeOrCompleted"),
            route = {
                Point(MAP.DARKSHORE, 0.384, 0.430, "Gershala Nightwhisper", "Travel to Darkshore."),
            },
        },
        {
            id = "boss-baron-aquanis",
            kind = "note",
            priority = 14,
            conditions = { level = { min = 25 } },
            text = "Kill Baron Aquanis. When afflicted by 'Depth Charge', move into the water. |grouprole EVERYONE. Return as soon as the debuff is gone. |grouprole EVERYONE. Move platforms to avoid taking damage from 'Thunderstorms'. |grouprole EVERYONE.",
        },
        {
            id = "note-click-pitted-iron-chest",
            kind = "note",
            priority = 16,
            conditions = { level = { min = 25 } },
            text = "Click Pitted Iron Chest.",
        },
        {
            id = "objective-78923-1-lorgalis-manuscript",
            kind = "objective",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Collect Lorgalis Manuscript.",
            dependsOn = { "accept-78923-knowledge-in-the-deeps" },
            complete = QuestState(78923, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-78921-blackfathom-villainy",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Accept Blackfathom Villainy from Argent Guard Thaelrid.",
            complete = QuestState(78921, "activeOrCompleted"),
        },
        {
            id = "boss-twilight-lord-kelris",
            kind = "note",
            priority = 19,
            conditions = { level = { min = 25 } },
            text = "Kill Twilight Lord Kelris. Avoid damage from 'Shadow Crash' by not standing in the purple areas. |grouprole EVERYONE. If you're afflicted by 'Sleep', kill the priestess quickly and click the portal to return to the fight. |grouprole EVERYONE. Interrupt both 'Mind Blast' and 'Shadowy Chains' as a priority. |grouprole DAMAGE.",
            dependsOn = { "boss-baron-aquanis" },
        },
        {
            id = "objective-78921-1-head-of-kelris",
            kind = "objective",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Collect Head of Kelris.",
            dependsOn = { "accept-78921-blackfathom-villainy" },
            complete = QuestState(78921, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-aku-mai",
            kind = "note",
            priority = 21,
            conditions = { level = { min = 25 } },
            text = "Kill Aku'mai. After 3 to 4 stacks of 'Corrosion' drag the boss to a Cleansing Pool and stand there. |grouprole TANK. Tank swap with Taunt if the current main tank has 3 to 4 stacks of 'Shadow Seep'. |grouprole TANK. Don't stand in front of the boss to avoid damage from 'Corrosive Blast'. |grouprole DAMAGE.",
            dependsOn = { "boss-twilight-lord-kelris" },
        },
        {
            id = "accept-78916-heart-of-the-void",
            kind = "accept",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Accept Heart of the Void.",
            complete = QuestState(78916, "activeOrCompleted"),
        },
        {
            id = "boss-twilight-enemies-around-this-area",
            kind = "note",
            priority = 23,
            conditions = { level = { min = 25 } },
            text = "Kill Twilight enemies around this area.",
            dependsOn = { "boss-aku-mai" },
        },
        {
            id = "objective-78925-1-twilight-pendant",
            kind = "objective",
            priority = 24,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Collect 10 Twilight Pendant.",
            dependsOn = { "accept-78925-twilight-falls" },
            complete = QuestState(78925, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-enemies-around-this-area",
            kind = "note",
            priority = 25,
            conditions = { level = { min = 25 } },
            text = "Kill enemies around this area. Both Fallenroot and Blackfathom enemies drop them. They look like Naga and Satyr.",
            dependsOn = { "boss-twilight-enemies-around-this-area" },
        },
        {
            id = "objective-78926-1-corrupted-brain-stem",
            kind = "objective",
            priority = 26,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Collect 8 Corrupted Brain Stem.",
            dependsOn = { "accept-78926-researching-the-corruption" },
            complete = QuestState(78926, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 27,
            conditions = { level = { min = 25 } },
            text = "Click Here to Continue.",
        },
        {
            id = "turnin-78916-heart-of-the-void",
            kind = "turnin",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Turn in Heart of the Void to Dawnwatcher Selgorm.",
            dependsOn = { "accept-78916-heart-of-the-void" },
            complete = QuestState(78916, "completed"),
            route = {
                Point(MAP.DARNASSUS, 0.560, 0.246, "Dawnwatcher Selgorm", "Travel to Darnassus."),
            },
        },
        {
            id = "turnin-78921-blackfathom-villainy",
            kind = "turnin",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Turn in Blackfathom Villainy to Dawnwatcher Selgorm.",
            dependsOn = { "objective-78921-1-head-of-kelris" },
            complete = QuestState(78921, "completed"),
            route = {
                Point(MAP.DARNASSUS, 0.560, 0.246, "Dawnwatcher Selgorm", "Travel to Darnassus."),
            },
        },
        {
            id = "turnin-78925-twilight-falls",
            kind = "turnin",
            priority = 30,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Turn in Twilight Falls to Argent Guard Manados.",
            dependsOn = { "objective-78925-1-twilight-pendant" },
            complete = QuestState(78925, "completed"),
            route = {
                Point(MAP.DARNASSUS, 0.552, 0.236, "Argent Guard Manados", "Travel to Darnassus."),
            },
        },
        {
            id = "turnin-78926-researching-the-corruption",
            kind = "turnin",
            priority = 32,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Turn in Researching the Corruption to Gershala Nightwhisper.",
            dependsOn = { "objective-78926-1-corrupted-brain-stem" },
            complete = QuestState(78926, "completed"),
            route = {
                Point(MAP.DARKSHORE, 0.384, 0.430, "Gershala Nightwhisper", "Travel to Darkshore."),
            },
        },
        {
            id = "turnin-78923-knowledge-in-the-deeps",
            kind = "turnin",
            priority = 33,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Turn in Knowledge in the Deeps to Gerrig Bonegrip.",
            dependsOn = { "objective-78923-1-lorgalis-manuscript" },
            complete = QuestState(78923, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.506, 0.062, "Gerrig Bonegrip", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-78927-allegiance-to-the-old-gods",
            kind = "accept",
            priority = 34,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Accept Allegiance to the Old Gods from Je'neu Sancrea.",
            complete = QuestState(78927, "activeOrCompleted"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.342, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "accept-78920-baron-aquanis",
            kind = "accept",
            priority = 35,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Accept Baron Aquanis.",
            complete = QuestState(78920, "activeOrCompleted"),
        },
        {
            id = "accept-78922-blackfathom-villainy",
            kind = "accept",
            priority = 36,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Accept Blackfathom Villainy from Argent Guard Thaelrid.",
            complete = QuestState(78922, "activeOrCompleted"),
        },
        {
            id = "objective-78927-1-lorgus-jett",
            kind = "objective",
            priority = 37,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Kill Lorgus Jett.",
            dependsOn = { "accept-78927-allegiance-to-the-old-gods" },
            complete = QuestState(78927, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-ghamoo-ra",
            kind = "note",
            priority = 38,
            conditions = { level = { min = 25 } },
            text = "Kill Ghamoo-Ra. Avoid bubbles that appear on the floor. |grouprole EVERYONE. Tank swap after two stacks of 'Crunch Armor'. |grouprole TANK. Top everyones health off when the shells are about to break. |grouprole HEALER.",
            dependsOn = { "boss-enemies-around-this-area" },
        },
        {
            id = "boss-lady-sarevess",
            kind = "note",
            priority = 39,
            conditions = { level = { min = 25 } },
            text = "Kill Lady Sarevess. Don't stand in frosted areas. |grouprole EVERYONE. The main tank should be on the boss. |grouprole TANK. The off-tank should move elite mobs away from the boss. |grouprole TANK.",
            dependsOn = { "boss-ghamoo-ra" },
        },
        {
            id = "boss-gelihast",
            kind = "note",
            priority = 40,
            conditions = { level = { min = 25 } },
            text = "Kill Gelihast. Avoid damage from 'Shadow Crash' by not standing in the purple areas. |grouprole EVERYONE. Avoid contact with the Shadow Murlocs that appear when Gelihast is at 10% health. |grouprole EVERYONE. The main tank should drag the boss to the center of the room. |grouprole TANK.",
            dependsOn = { "boss-lady-sarevess" },
        },
        {
            id = "boss-lorgus-jett",
            kind = "note",
            priority = 41,
            conditions = { level = { min = 25 } },
            text = "Kill Lorgus Jett. Focus down the waves of enemies to start the fight. |grouprole EVERYONE. Focus down elite enemies first. |grouprole DAMAGE. Interrupt the Priestess' healing abilities. |grouprole DAMAGE.",
            dependsOn = { "boss-gelihast" },
        },
        {
            id = "objective-78922-1-head-of-kelris",
            kind = "objective",
            priority = 42,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Collect Head of Kelris.",
            dependsOn = { "accept-78922-blackfathom-villainy" },
            complete = QuestState(78922, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-78917-heart-of-the-void",
            kind = "accept",
            priority = 43,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Accept Heart of the Void.",
            complete = QuestState(78917, "activeOrCompleted"),
        },
        {
            id = "turnin-78920-baron-aquanis",
            kind = "turnin",
            priority = 44,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Turn in Baron Aquanis to Je'neu Sancrea.",
            dependsOn = { "accept-78920-baron-aquanis" },
            complete = QuestState(78920, "completed"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.342, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "turnin-78927-allegiance-to-the-old-gods",
            kind = "turnin",
            priority = 45,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Turn in Allegiance to the Old Gods to Je'neu Sancrea.",
            dependsOn = { "objective-78927-1-lorgus-jett" },
            complete = QuestState(78927, "completed"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.342, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "turnin-78922-blackfathom-villainy",
            kind = "turnin",
            priority = 46,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Turn in Blackfathom Villainy to Bashana Runetotem.",
            dependsOn = { "objective-78922-1-head-of-kelris" },
            complete = QuestState(78922, "completed"),
            route = {
                Point(MAP.THUNDER_BLUFF, 0.708, 0.338, "Bashana Runetotem", "Travel to Thunder Bluff."),
            },
        },
        {
            id = "turnin-78917-heart-of-the-void",
            kind = "turnin",
            priority = 47,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Turn in Heart of the Void to Bashana Runetotem.",
            dependsOn = { "accept-78917-heart-of-the-void" },
            complete = QuestState(78917, "completed"),
            route = {
                Point(MAP.THUNDER_BLUFF, 0.708, 0.338, "Bashana Runetotem", "Travel to Thunder Bluff."),
            },
        },
    },
})
