local _, ns = ...

local MAP = {
    STORMWIND_CITY = 1453,
    IRONFORGE = 1455,
    DARKSHORE = 1439,
    DARNASSUS = 1457,
    ASHENVALE = 1440,
    THUNDER_BLUFF = 1456,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-blackfathom-deeps",
    title = "Blackfathom Deeps",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 20 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-3765-the-corruption-abroad",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Accept The Corruption Abroad from Argos Nightwhisper.",
            complete = QuestState(3765, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.214, 0.558, "Argos Nightwhisper", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-971-knowledge-in-the-deeps",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 10 } } } },
            text = "Accept Knowledge in the Deeps from Gerrig Bonegrip.",
            complete = QuestState(971, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.508, 0.056, "Gerrig Bonegrip", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-3765-the-corruption-abroad",
            kind = "turnin",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Turn in The Corruption Abroad to Gershala Nightwhisper.",
            dependsOn = { "accept-3765-the-corruption-abroad" },
            complete = QuestState(3765, "completed"),
            route = {
                Point(MAP.DARKSHORE, 0.383, 0.430, "Gershala Nightwhisper", "Travel to Darkshore."),
            },
        },
        {
            id = "accept-1275-researching-the-corruption",
            kind = "accept",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Accept Researching the Corruption from Gershala Nightwhisper.",
            dependsOn = { "turnin-3765-the-corruption-abroad" },
            complete = QuestState(1275, "activeOrCompleted"),
            route = {
                Point(MAP.DARKSHORE, 0.383, 0.430, "Gershala Nightwhisper", "Travel to Darkshore."),
            },
        },
        {
            id = "accept-1199-twilight-falls",
            kind = "accept",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Accept Twilight Falls from Argent Guard Manados.",
            complete = QuestState(1199, "activeOrCompleted"),
            route = {
                Point(MAP.DARNASSUS, 0.552, 0.240, "Argent Guard Manados", "Travel to Darnassus."),
            },
        },
        {
            id = "accept-1198-in-search-of-thaelrid",
            kind = "accept",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Accept In Search of Thaelrid from Dawnwatcher Shaedlass.",
            complete = QuestState(1198, "activeOrCompleted"),
            route = {
                Point(MAP.DARNASSUS, 0.554, 0.250, "Dawnwatcher Shaedlass", "Travel to Darnassus."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 16,
            conditions = { level = { min = 20 } },
            text = "Enter Blackfathom Deeps with your group.",
            dependsOn = { "accept-3765-the-corruption-abroad", "accept-971-knowledge-in-the-deeps", "accept-1275-researching-the-corruption", "accept-1199-twilight-falls", "accept-1198-in-search-of-thaelrid" },
            persistCompletion = true,
            complete = { instance = 48 },
        },
        {
            id = "note-click-pitted-iron-chest",
            kind = "note",
            priority = 17,
            conditions = { level = { min = 20 } },
            text = "Click Pitted Iron Chest.",
        },
        {
            id = "objective-971-1-lorgalis-manuscript",
            kind = "objective",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 10 } } } },
            text = "Collect Lorgalis Manuscript.",
            dependsOn = { "accept-971-knowledge-in-the-deeps" },
            complete = QuestState(971, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-1198-in-search-of-thaelrid",
            kind = "turnin",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Turn in In Search of Thaelrid to Argent Guard Thaelrid.",
            dependsOn = { "accept-1198-in-search-of-thaelrid" },
            complete = QuestState(1198, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-1200-blackfathom-villainy",
            kind = "accept",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Accept Blackfathom Villainy from Argent Guard Thaelrid.",
            dependsOn = { "turnin-1198-in-search-of-thaelrid" },
            complete = QuestState(1200, "activeOrCompleted"),
        },
        {
            id = "boss-twilight-lord-kelris",
            kind = "note",
            priority = 21,
            conditions = { level = { min = 20 } },
            text = "Kill Twilight Lord Kelris. The fourth boss of the dungeon. Leave the underwater cave and reenter the main room in The Pool of Ask'ar. Swim south and follow the path to the left to reach the Moonshrine Ruins. Kelris will cast the 'Sleep' ability on a random party member. The healer should keep the tank topped off in case they get slept. If there is a hybrid class in the group and the healer is slept, you may need to assist.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "objective-1200-1-head-of-kelris",
            kind = "objective",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Collect Head of Kelris.",
            dependsOn = { "accept-1200-blackfathom-villainy" },
            complete = QuestState(1200, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-twilight-enemies-around-this-area",
            kind = "note",
            priority = 23,
            conditions = { level = { min = 20 } },
            text = "Kill Twilight enemies around this area. They are found throughout the instance.",
            dependsOn = { "boss-twilight-lord-kelris" },
        },
        {
            id = "objective-1199-1-twilight-pendant",
            kind = "objective",
            priority = 24,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Collect 10 Twilight Pendant.",
            dependsOn = { "accept-1199-twilight-falls" },
            complete = QuestState(1199, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-blackfathom-and-fallenroot-enemies-around",
            kind = "note",
            priority = 25,
            conditions = { level = { min = 20 } },
            text = "Kill Blackfathom and Fallenroot enemies around this area. They are found throughout the instance.",
            dependsOn = { "boss-twilight-enemies-around-this-area" },
        },
        {
            id = "objective-1275-1-corrupted-brain-stem",
            kind = "objective",
            priority = 26,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Collect 8 Corrupted Brain Stem.",
            dependsOn = { "accept-1275-researching-the-corruption" },
            complete = QuestState(1275, "complete"),
            useClientPin = true,
        },
        {
            id = "note-leave-the-dungeon",
            kind = "note",
            priority = 27,
            conditions = { level = { min = 20 } },
            text = "Leave the dungeon.",
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 28,
            conditions = { level = { min = 20 } },
            text = "Click Here to Continue.",
        },
        {
            id = "turnin-1275-researching-the-corruption",
            kind = "turnin",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Turn in Researching the Corruption to Gershala Nightwhisper.",
            dependsOn = { "objective-1275-1-corrupted-brain-stem" },
            complete = QuestState(1275, "completed"),
            route = {
                Point(MAP.DARKSHORE, 0.383, 0.430, "Gershala Nightwhisper", "Travel to Darkshore."),
            },
        },
        {
            id = "turnin-1199-twilight-falls",
            kind = "turnin",
            priority = 30,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Turn in Twilight Falls to Argent Guard Manados.",
            dependsOn = { "objective-1199-1-twilight-pendant" },
            complete = QuestState(1199, "completed"),
            route = {
                Point(MAP.DARNASSUS, 0.552, 0.240, "Argent Guard Manados", "Travel to Darnassus."),
            },
        },
        {
            id = "turnin-1200-blackfathom-villainy",
            kind = "turnin",
            priority = 31,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 18 } } } },
            text = "Turn in Blackfathom Villainy to Dawnwatcher Selgorm.",
            dependsOn = { "objective-1200-1-head-of-kelris" },
            complete = QuestState(1200, "completed"),
            route = {
                Point(MAP.DARNASSUS, 0.562, 0.244, "Dawnwatcher Selgorm", "Travel to Darnassus."),
            },
        },
        {
            id = "turnin-971-knowledge-in-the-deeps",
            kind = "turnin",
            priority = 32,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 10 } } } },
            text = "Turn in Knowledge in the Deeps to Gerrig Bonegrip.",
            dependsOn = { "objective-971-1-lorgalis-manuscript" },
            complete = QuestState(971, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.508, 0.056, "Gerrig Bonegrip", "Travel to Ironforge."),
            },
        },
        {
            id = "reach-level-21",
            kind = "note",
            priority = 33,
            conditions = { level = { min = 21 } },
            text = "Reach level 21 before you continue.",
            dependsOn = { "turnin-971-knowledge-in-the-deeps" },
            complete = { level = { min = 21 } },
        },
        {
            id = "accept-6563-the-essence-of-aku-mai",
            kind = "accept",
            priority = 34,
            conditions = { all = { { faction = "Horde" }, { level = { min = 17 } } } },
            text = "Accept The Essence of Aku'Mai from Je'neu Sancrea.",
            complete = QuestState(6563, "activeOrCompleted"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.343, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "accept-6921-amongst-the-ruins",
            kind = "accept",
            priority = 35,
            conditions = { all = { { faction = "Horde" }, { level = { min = 21 } } } },
            text = "Accept Amongst the Ruins from Je'neu Sancrea.",
            complete = QuestState(6921, "activeOrCompleted"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.343, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "boss-blackfathom-tide-priestess",
            kind = "note",
            priority = 36,
            conditions = { level = { min = 21 } },
            text = "Kill Blackfathom Tide Priestess. You may need help with this. This has a low drop rate.",
            dependsOn = { "boss-blackfathom-and-fallenroot-enemies-around" },
        },
        {
            id = "accept-6564-allegience-to-the-old-gods",
            kind = "accept",
            priority = 37,
            conditions = { all = { { faction = "Horde" }, { level = { min = 17 } } } },
            text = "Accept Allegience to the Old Gods.",
            complete = QuestState(6564, "activeOrCompleted"),
        },
        {
            id = "turnin-6564-allegience-to-the-old-gods",
            kind = "turnin",
            priority = 38,
            conditions = { all = { { faction = "Horde" }, { level = { min = 17 } } } },
            text = "Turn in Allegience to the Old Gods to Je'neu Sancrea.",
            dependsOn = { "accept-6564-allegience-to-the-old-gods" },
            complete = QuestState(6564, "completed"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.343, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "accept-6565-allegiance-to-the-old-gods",
            kind = "accept",
            priority = 39,
            conditions = { all = { { faction = "Horde" }, { level = { min = 17 } } } },
            text = "Accept Allegiance to the Old Gods from Je'neu Sancrea.",
            dependsOn = { "turnin-6564-allegience-to-the-old-gods" },
            complete = QuestState(6565, "activeOrCompleted"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.343, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "note-click-sapphire-of-aku-mai",
            kind = "note",
            priority = 40,
            conditions = { level = { min = 21 } },
            text = "Click Sapphire of Aku'Mai+.",
        },
        {
            id = "objective-6563-1-sapphire-of-aku-mai",
            kind = "objective",
            priority = 41,
            conditions = { all = { { faction = "Horde" }, { level = { min = 17 } } } },
            text = "Collect 20 Sapphire of Aku'Mai.",
            dependsOn = { "accept-6563-the-essence-of-aku-mai" },
            complete = QuestState(6563, "complete"),
            route = {
                Point(MAP.ASHENVALE, 0.137, 0.094, "Ashenvale", "Travel to Ashenvale."),
            },
        },
        {
            id = "accept-6561-blackfathom-villainy",
            kind = "accept",
            priority = 42,
            conditions = { all = { { faction = "Horde" }, { level = { min = 18 } } } },
            text = "Accept Blackfathom Villainy from Argent Guard Thaelrid.",
            complete = QuestState(6561, "activeOrCompleted"),
        },
        {
            id = "objective-6565-1-lorgus-jett",
            kind = "objective",
            priority = 43,
            conditions = { all = { { faction = "Horde" }, { level = { min = 17 } } } },
            text = "Kill Lorgus Jett.",
            dependsOn = { "accept-6565-allegiance-to-the-old-gods" },
            complete = QuestState(6565, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-fathom-stone",
            kind = "note",
            priority = 44,
            conditions = { level = { min = 21 } },
            text = "Click Fathom Stone.",
        },
        {
            id = "boss-baron-aquanis",
            kind = "note",
            priority = 45,
            conditions = { level = { min = 21 } },
            text = "Kill Baron Aquanis. He is an optional boss in the dungeon. He spawns after clicking the Fathom Stone underwater in the Moonshrine Ruins.",
            dependsOn = { "boss-blackfathom-tide-priestess" },
        },
        {
            id = "accept-6922-baron-aquanis",
            kind = "accept",
            priority = 46,
            conditions = { all = { { faction = "Horde" }, { level = { min = 21 } } } },
            text = "Accept Baron Aquanis.",
            complete = QuestState(6922, "activeOrCompleted"),
        },
        {
            id = "boss-ghamoo-ra",
            kind = "note",
            priority = 47,
            conditions = { level = { min = 20 } },
            text = "Kill Ghamoo-ra. Ghamoo-ra has high armor so melee damage will be significantly reduced. Spread out as best as possible to avoid taking damage from 'Trample'.",
            dependsOn = { "boss-baron-aquanis" },
        },
        {
            id = "boss-lady-sarevess",
            kind = "note",
            priority = 48,
            conditions = { level = { min = 20 } },
            text = "Kill Lady Sarevess. Lady Sarevess will be patrolling a cave with 2 other Naga. It's recommended that you kill them before engaging her. Use CC abilities on her two bodyguards that accompany her.",
            dependsOn = { "boss-ghamoo-ra" },
        },
        {
            id = "boss-gelihast",
            kind = "note",
            priority = 49,
            conditions = { level = { min = 20 } },
            text = "Kill Gelihast. Before starting the encounter, clear the room of the Murlocs. Be careful not to pull them with the boss while clearing them out. Once the room is clear of adds, kill Gelihast.",
            dependsOn = { "boss-lady-sarevess" },
        },
        {
            id = "boss-old-serra-kis",
            kind = "note",
            priority = 50,
            conditions = { level = { min = 20 } },
            text = "Kill Old Serra'kis. To unlock the door, click each brazier one at a time and defeat the wave of enemies that spawn from them. This is an optional encounter. It takes place underwater.",
            dependsOn = { "boss-gelihast" },
        },
        {
            id = "boss-aku-mai",
            kind = "note",
            priority = 51,
            conditions = { level = { min = 20 } },
            text = "Kill Aku'mai. Aku'mai deals high damage to a single target during 'Frenzied Rage'. This ability lasts for 15 seconds. High healing will be required for these phases.",
            dependsOn = { "boss-old-serra-kis" },
        },
        {
            id = "objective-6561-1-head-of-kelris",
            kind = "objective",
            priority = 52,
            conditions = { all = { { faction = "Horde" }, { level = { min = 18 } } } },
            text = "Collect Head of Kelris.",
            dependsOn = { "accept-6561-blackfathom-villainy" },
            complete = QuestState(6561, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-6563-the-essence-of-aku-mai",
            kind = "turnin",
            priority = 53,
            conditions = { all = { { faction = "Horde" }, { level = { min = 17 } } } },
            text = "Turn in The Essence of Aku'Mai to Je'neu Sancrea.",
            dependsOn = { "objective-6563-1-sapphire-of-aku-mai" },
            complete = QuestState(6563, "completed"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.343, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "turnin-6565-allegiance-to-the-old-gods",
            kind = "turnin",
            priority = 54,
            conditions = { all = { { faction = "Horde" }, { level = { min = 17 } } } },
            text = "Turn in Allegiance to the Old Gods to Je'neu Sancrea.",
            dependsOn = { "objective-6565-1-lorgus-jett" },
            complete = QuestState(6565, "completed"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.343, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "turnin-6921-amongst-the-ruins",
            kind = "turnin",
            priority = 55,
            conditions = { all = { { faction = "Horde" }, { level = { min = 21 } } } },
            text = "Turn in Amongst the Ruins to Je'neu Sancrea.",
            dependsOn = { "accept-6921-amongst-the-ruins" },
            complete = QuestState(6921, "completed"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.343, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "turnin-6922-baron-aquanis",
            kind = "turnin",
            priority = 56,
            conditions = { all = { { faction = "Horde" }, { level = { min = 21 } } } },
            text = "Turn in Baron Aquanis to Je'neu Sancrea.",
            dependsOn = { "accept-6922-baron-aquanis" },
            complete = QuestState(6922, "completed"),
            route = {
                Point(MAP.ASHENVALE, 0.116, 0.343, "Je'neu Sancrea", "Travel to Ashenvale."),
            },
        },
        {
            id = "turnin-6561-blackfathom-villainy",
            kind = "turnin",
            priority = 57,
            conditions = { all = { { faction = "Horde" }, { level = { min = 18 } } } },
            text = "Turn in Blackfathom Villainy to Bashana Runetotem.",
            dependsOn = { "objective-6561-1-head-of-kelris" },
            complete = QuestState(6561, "completed"),
            route = {
                Point(MAP.THUNDER_BLUFF, 0.711, 0.342, "Bashana Runetotem", "Travel to Thunder Bluff."),
            },
        },
    },
})
