local _, ns = ...

local MAP = {
    TANARIS = 1446,
    IRONFORGE = 1455,
    BLASTED_LANDS = 1419,
    DUN_MOROGH = 1426,
    BURNING_STEPPES = 1428,
    REDRIDGE_MOUNTAINS = 1433,
    STORMWIND_CITY = 1453,
    SEARING_GORGE = 1427,
    AZSHARA = 1447,
    UN_GORO_CRATER = 1449,
    UNDERCITY = 1458,
    BADLANDS = 1418,
    ORGRIMMAR = 1454,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-blackrock-depths",
    title = "Blackrock Depths",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 52 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-4324-yuka-screwspigot",
            kind = "accept",
            priority = 10,
            conditions = { level = { min = 48 } },
            text = "Accept Yuka Screwspigot from Yorba Screwspigot.",
            complete = QuestState(4324, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.240, "Yorba Screwspigot", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3702-the-smoldering-ruins-of-thaurissan",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Smoldering Ruins of Thaurissan from Royal Historian Archesonus.",
            complete = QuestState(3702, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.384, 0.553, "Royal Historian Archesonus", "Travel to Ironforge."),
            },
        },
        {
            id = "objective-3702-1-hear-the-story-of-thauri",
            kind = "gossip",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Talk to Royal Historian Archesonus. 'I am ready to listen.' Hear the Story of Thaurissan.",
            dependsOn = { "accept-3702-the-smoldering-ruins-of-thaurissan" },
            complete = QuestState(3702, "complete"),
            route = {
                Point(MAP.IRONFORGE, 0.384, 0.553, "Ironforge", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-3702-the-smoldering-ruins-of-thaurissan",
            kind = "turnin",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Smoldering Ruins of Thaurissan to Royal Historian Archesonus.",
            dependsOn = { "objective-3702-1-hear-the-story-of-thauri" },
            complete = QuestState(3702, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.384, 0.553, "Royal Historian Archesonus", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-3701-the-smoldering-ruins-of-thaurissan",
            kind = "accept",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Smoldering Ruins of Thaurissan from Royal Historian Archesonus.",
            dependsOn = { "turnin-3702-the-smoldering-ruins-of-thaurissan" },
            complete = QuestState(3701, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.384, 0.553, "Royal Historian Archesonus", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-4128-ragnar-thunderbrew",
            kind = "accept",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Ragnar Thunderbrew from Enohar Thunderbrew.",
            complete = QuestState(4128, "activeOrCompleted"),
            route = {
                Point(MAP.BLASTED_LANDS, 0.636, 0.206, "Enohar Thunderbrew", "Travel to Blasted Lands."),
            },
        },
        {
            id = "turnin-4128-ragnar-thunderbrew",
            kind = "turnin",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Ragnar Thunderbrew to Ragnar Thunderbrew.",
            dependsOn = { "accept-4128-ragnar-thunderbrew" },
            complete = QuestState(4128, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.468, 0.524, "Ragnar Thunderbrew", "Travel to Dun Morogh."),
            },
        },
        {
            id = "accept-4126-hurley-blackbreath",
            kind = "accept",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Hurley Blackbreath from Ragnar Thunderbrew.",
            dependsOn = { "turnin-4128-ragnar-thunderbrew" },
            complete = QuestState(4126, "activeOrCompleted"),
            route = {
                Point(MAP.DUN_MOROGH, 0.468, 0.524, "Ragnar Thunderbrew", "Travel to Dun Morogh."),
            },
        },
        {
            id = "accept-4286-the-good-stuff",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Good Stuff from Oralius.",
            complete = QuestState(4286, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.846, 0.687, "Oralius", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4182-dragonkin-menace",
            kind = "accept",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Dragonkin Menace from Helendis Riverhorn.",
            complete = QuestState(4182, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.689, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4262-overmaster-pyron",
            kind = "accept",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Overmaster Pyron from Jalinda Sprig.",
            complete = QuestState(4262, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.854, 0.701, "Jalinda Sprig", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-3-black-drake",
            kind = "objective",
            priority = 21,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill Black Drake.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 3, "Black Drake"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.863, 0.307, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-4-black-wyrmkin",
            kind = "objective",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill 4 Black Wyrmkin.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 4, "Black Wyrmkin"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.843, 0.278, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-2-black-dragonspawn",
            kind = "objective",
            priority = 23,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill 10 Black Dragonspawn.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 2, "Black Dragonspawn"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.843, 0.278, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-1-black-broodling",
            kind = "objective",
            priority = 24,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill 15 Black Broodling.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 1, "Black Broodling"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.728, 0.284, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "note-click-thaurissan-relic",
            kind = "note",
            priority = 25,
            conditions = { level = { min = 52 } },
            text = "Click Thaurissan Relic+.",
        },
        {
            id = "objective-3701-1-pieces-of-information",
            kind = "objective",
            priority = 26,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Recover 12 Pieces of Information.",
            dependsOn = { "accept-3701-the-smoldering-ruins-of-thaurissan" },
            complete = QuestState(3701, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.672, 0.382, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4182-dragonkin-menace",
            kind = "turnin",
            priority = 27,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Dragonkin Menace to Helendis Riverhorn.",
            dependsOn = { "objective-4182-3-black-drake", "objective-4182-4-black-wyrmkin", "objective-4182-2-black-dragonspawn", "objective-4182-1-black-broodling" },
            complete = QuestState(4182, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.690, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4183-the-true-masters",
            kind = "accept",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Helendis Riverhorn.",
            dependsOn = { "turnin-4182-dragonkin-menace" },
            complete = QuestState(4183, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.690, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-3701-the-smoldering-ruins-of-thaurissan",
            kind = "turnin",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Smoldering Ruins of Thaurissan to Royal Historian Archesonus.",
            dependsOn = { "objective-3701-1-pieces-of-information" },
            complete = QuestState(3701, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.384, 0.553, "Royal Historian Archesonus", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-4341-kharan-mighthammer",
            kind = "accept",
            priority = 30,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Kharan Mighthammer from King Magni Bronzebeard.",
            complete = QuestState(4341, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.391, 0.562, "King Magni Bronzebeard", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-4183-the-true-masters",
            kind = "turnin",
            priority = 31,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Magistrate Solomon.",
            dependsOn = { "accept-4183-the-true-masters" },
            complete = QuestState(4183, "completed"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "accept-4184-the-true-masters",
            kind = "accept",
            priority = 32,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Magistrate Solomon.",
            dependsOn = { "turnin-4183-the-true-masters" },
            complete = QuestState(4184, "activeOrCompleted"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "turnin-4184-the-true-masters",
            kind = "turnin",
            priority = 33,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Highlord Bolvar Fordragon.",
            dependsOn = { "accept-4184-the-true-masters" },
            complete = QuestState(4184, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-4185-the-true-masters",
            kind = "accept",
            priority = 34,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Highlord Bolvar Fordragon.",
            dependsOn = { "turnin-4184-the-true-masters" },
            complete = QuestState(4185, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "objective-4185-1-seek-advice-from-lady-pr",
            kind = "gossip",
            priority = 35,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Talk to Lady Katrana Prestor. 'Pardon the intrusion, Lady Prestor, but Highlord Bolvar suggested that I seek your advice.' Seek Advice from Lady Prestor.",
            dependsOn = { "accept-4185-the-true-masters" },
            complete = QuestState(4185, "complete"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.781, 0.177, "Stormwind City", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4185-the-true-masters",
            kind = "turnin",
            priority = 36,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Highlord Bolvar Fordragon.",
            dependsOn = { "objective-4185-1-seek-advice-from-lady-pr" },
            complete = QuestState(4185, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-4186-the-true-masters",
            kind = "accept",
            priority = 37,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Highlord Bolvar Fordragon.",
            dependsOn = { "turnin-4185-the-true-masters" },
            complete = QuestState(4186, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4186-the-true-masters",
            kind = "turnin",
            priority = 38,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Magistrate Solomon.",
            dependsOn = { "accept-4186-the-true-masters" },
            complete = QuestState(4186, "completed"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "accept-4223-the-true-masters",
            kind = "accept",
            priority = 39,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Magistrate Solomon.",
            dependsOn = { "turnin-4186-the-true-masters" },
            complete = QuestState(4223, "activeOrCompleted"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "turnin-4223-the-true-masters",
            kind = "turnin",
            priority = 40,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Marshal Maxwell.",
            dependsOn = { "accept-4223-the-true-masters" },
            complete = QuestState(4223, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4224-the-true-masters",
            kind = "accept",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Marshal Maxwell.",
            dependsOn = { "turnin-4223-the-true-masters" },
            complete = QuestState(4224, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4224-1-listen-to-ragged-john-s",
            kind = "gossip",
            priority = 42,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Talk to Ragged John. 'Official business, John. I need some information about Marshal Windsor. Tell me about the last time you saw him.' Listen to Ragged John's Story.",
            dependsOn = { "accept-4224-the-true-masters" },
            complete = QuestState(4224, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4224-the-true-masters",
            kind = "turnin",
            priority = 43,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Marshal Maxwell.",
            dependsOn = { "objective-4224-1-listen-to-ragged-john-s" },
            complete = QuestState(4224, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.847, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4241-marshal-windsor",
            kind = "accept",
            priority = 44,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Marshal Windsor from Marshal Maxwell.",
            dependsOn = { "turnin-4224-the-true-masters" },
            complete = QuestState(4241, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.847, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-3441-divine-retribution",
            kind = "accept",
            priority = 45,
            conditions = { level = { min = 40 } },
            text = "Accept Divine Retribution from Kalaran Windblade.",
            complete = QuestState(3441, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "objective-3441-1-listen-to-kalaran-s-stor",
            kind = "gossip",
            priority = 46,
            conditions = { level = { min = 40 } },
            text = "Talk to Kalaran Windblade. 'Tell me what drives this vengeance?' Listen to Kalaran's Story.",
            dependsOn = { "accept-3441-divine-retribution" },
            complete = QuestState(3441, "complete"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-3441-divine-retribution",
            kind = "turnin",
            priority = 47,
            conditions = { level = { min = 40 } },
            text = "Turn in Divine Retribution to Kalaran Windblade.",
            dependsOn = { "objective-3441-1-listen-to-kalaran-s-stor" },
            complete = QuestState(3441, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "accept-3442-the-flawless-flame",
            kind = "accept",
            priority = 48,
            conditions = { level = { min = 40 } },
            text = "Accept The Flawless Flame from Kalaran Windblade.",
            dependsOn = { "turnin-3441-divine-retribution" },
            complete = QuestState(3442, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "boss-enemies-around-this-area",
            kind = "note",
            priority = 49,
            conditions = { level = { min = 52 } },
            text = "Kill enemies around this area. Only Tempered War Golems, Heavy War Golems, and Magma Elementals will drop this quest item.",
        },
        {
            id = "objective-3442-2-golem-oil",
            kind = "objective",
            priority = 50,
            conditions = { level = { min = 40 } },
            text = "Collect 4 Golem Oil.",
            dependsOn = { "accept-3442-the-flawless-flame" },
            complete = QuestObjective(3442, 2, "Golem Oil"),
            route = {
                Point(MAP.SEARING_GORGE, 0.486, 0.383, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "boss-elemental-enemies-around-this-area",
            kind = "note",
            priority = 51,
            conditions = { level = { min = 52 } },
            text = "Kill Elemental enemies around this area. Heavy War Golems will not drop this quest item.",
            dependsOn = { "boss-enemies-around-this-area" },
        },
        {
            id = "objective-3442-1-heart-of-flame",
            kind = "objective",
            priority = 52,
            conditions = { level = { min = 40 } },
            text = "Collect 4 Heart of Flame.",
            dependsOn = { "accept-3442-the-flawless-flame" },
            complete = QuestObjective(3442, 1, "Heart of Flame"),
            route = {
                Point(MAP.SEARING_GORGE, 0.426, 0.386, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-3442-the-flawless-flame",
            kind = "turnin",
            priority = 53,
            conditions = { level = { min = 40 } },
            text = "Turn in The Flawless Flame to Kalaran Windblade.",
            dependsOn = { "objective-3442-2-golem-oil", "objective-3442-1-heart-of-flame" },
            complete = QuestState(3442, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "accept-3443-forging-the-shaft",
            kind = "accept",
            priority = 54,
            conditions = { level = { min = 40 } },
            text = "Accept Forging the Shaft from Kalaran Windblade.",
            dependsOn = { "turnin-3442-the-flawless-flame" },
            complete = QuestState(3443, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "boss-dark-iron-enemies-around-this-area",
            kind = "note",
            priority = 55,
            conditions = { level = { min = 52 } },
            text = "Kill Dark Iron enemies around this area. Inside the cave, all throughout. You can also find some outside, near Thorium Point.",
            dependsOn = { "boss-elemental-enemies-around-this-area" },
        },
        {
            id = "objective-3443-1-thorium-plated-dagger",
            kind = "objective",
            priority = 56,
            conditions = { level = { min = 40 } },
            text = "Collect 8 Thorium Plated Dagger.",
            dependsOn = { "accept-3443-forging-the-shaft" },
            complete = QuestState(3443, "complete"),
            route = {
                Point(MAP.SEARING_GORGE, 0.434, 0.349, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-3443-forging-the-shaft",
            kind = "turnin",
            priority = 57,
            conditions = { level = { min = 40 } },
            text = "Turn in Forging the Shaft to Kalaran Windblade.",
            dependsOn = { "objective-3443-1-thorium-plated-dagger" },
            complete = QuestState(3443, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.391, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "accept-3452-the-flame-s-casing",
            kind = "accept",
            priority = 58,
            conditions = { level = { min = 40 } },
            text = "Accept The Flame's Casing from Kalaran Windblade.",
            dependsOn = { "turnin-3443-forging-the-shaft" },
            complete = QuestState(3452, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.391, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "boss-twilight-enemies-around-this-area",
            kind = "note",
            priority = 59,
            conditions = { level = { min = 52 } },
            text = "Kill Twilight enemies around this area. They are elite enemies, you will likely need help with this. Try to find someone to help you. Doing this quest unlocks more quests that give easy experience, so it's important to get it done.",
            dependsOn = { "boss-dark-iron-enemies-around-this-area" },
        },
        {
            id = "objective-3452-1-symbol-of-ragnaros",
            kind = "objective",
            priority = 60,
            conditions = { level = { min = 40 } },
            text = "Collect Symbol of Ragnaros.",
            dependsOn = { "accept-3452-the-flame-s-casing" },
            complete = QuestState(3452, "complete"),
            route = {
                Point(MAP.SEARING_GORGE, 0.246, 0.351, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-3452-the-flame-s-casing",
            kind = "turnin",
            priority = 61,
            conditions = { level = { min = 40 } },
            text = "Turn in The Flame's Casing to Kalaran Windblade.",
            dependsOn = { "objective-3452-1-symbol-of-ragnaros" },
            complete = QuestState(3452, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "accept-3453-the-torch-of-retribution",
            kind = "accept",
            priority = 62,
            conditions = { level = { min = 40 } },
            text = "Accept The Torch of Retribution from Kalaran Windblade.",
            dependsOn = { "turnin-3452-the-flame-s-casing" },
            complete = QuestState(3453, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "objective-3453-1-witness-the-creation-of",
            kind = "objective",
            priority = 63,
            conditions = { level = { min = 40 } },
            text = "Witness the Creation of the Torch.",
            dependsOn = { "accept-3453-the-torch-of-retribution" },
            complete = QuestState(3453, "complete"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-3453-the-torch-of-retribution",
            kind = "turnin",
            priority = 64,
            conditions = { level = { min = 40 } },
            text = "Turn in The Torch of Retribution to Kalaran Windblade.",
            dependsOn = { "objective-3453-1-witness-the-creation-of" },
            complete = QuestState(3453, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "accept-3454-the-torch-of-retribution",
            kind = "accept",
            priority = 65,
            conditions = { level = { min = 40 } },
            text = "Accept The Torch of Retribution from Kalaran Windblade.",
            dependsOn = { "turnin-3453-the-torch-of-retribution" },
            complete = QuestState(3454, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "note-click-torch-of-retribution",
            kind = "note",
            priority = 66,
            conditions = { level = { min = 52 } },
            text = "Click Torch of Retribution.",
        },
        {
            id = "turnin-3454-the-torch-of-retribution",
            kind = "turnin",
            priority = 67,
            conditions = { level = { min = 40 } },
            text = "Turn in The Torch of Retribution.",
            dependsOn = { "accept-3454-the-torch-of-retribution" },
            complete = QuestState(3454, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.391, 0.391, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "accept-3462-squire-maltrake",
            kind = "accept",
            priority = 68,
            conditions = { level = { min = 40 } },
            text = "Accept Squire Maltrake from Kalaran Windblade.",
            complete = QuestState(3462, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.390, 0.390, "Kalaran Windblade", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-3462-squire-maltrake",
            kind = "turnin",
            priority = 69,
            conditions = { level = { min = 40 } },
            text = "Turn in Squire Maltrake to Squire Maltrake.",
            dependsOn = { "accept-3462-squire-maltrake" },
            complete = QuestState(3462, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.392, 0.390, "Squire Maltrake", "Travel to Searing Gorge."),
            },
        },
        {
            id = "accept-3463-set-them-ablaze",
            kind = "accept",
            priority = 70,
            conditions = { level = { min = 40 } },
            text = "Accept Set Them Ablaze! from Squire Maltrake.",
            dependsOn = { "turnin-3462-squire-maltrake" },
            complete = QuestState(3463, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.392, 0.390, "Squire Maltrake", "Travel to Searing Gorge."),
            },
        },
        {
            id = "note-click-sentry-brazier",
            kind = "note",
            priority = 71,
            conditions = { level = { min = 52 } },
            text = "Click Sentry Brazier.",
        },
        {
            id = "objective-3463-4-set-the-northern-tower-a",
            kind = "objective",
            priority = 72,
            conditions = { level = { min = 40 } },
            text = "Set the Northern Tower Ablaze.",
            dependsOn = { "accept-3463-set-them-ablaze" },
            complete = QuestObjective(3463, 4, "Set the Northern Tower Ablaze"),
            route = {
                Point(MAP.SEARING_GORGE, 0.333, 0.545, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "objective-3463-1-set-the-western-tower-ab",
            kind = "objective",
            priority = 73,
            conditions = { level = { min = 40 } },
            text = "Set the Western Tower Ablaze.",
            dependsOn = { "accept-3463-set-them-ablaze" },
            complete = QuestObjective(3463, 1, "Set the Western Tower Ablaze"),
            route = {
                Point(MAP.SEARING_GORGE, 0.357, 0.607, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "objective-3463-2-set-the-southern-tower-a",
            kind = "objective",
            priority = 74,
            conditions = { level = { min = 40 } },
            text = "Set the Southern Tower Ablaze.",
            dependsOn = { "accept-3463-set-them-ablaze" },
            complete = QuestObjective(3463, 2, "Set the Southern Tower Ablaze"),
            route = {
                Point(MAP.SEARING_GORGE, 0.440, 0.609, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "objective-3463-3-set-the-eastern-tower-ab",
            kind = "objective",
            priority = 75,
            conditions = { level = { min = 40 } },
            text = "Set the Eastern Tower Ablaze.",
            dependsOn = { "accept-3463-set-them-ablaze" },
            complete = QuestObjective(3463, 3, "Set the Eastern Tower Ablaze"),
            route = {
                Point(MAP.SEARING_GORGE, 0.501, 0.547, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-3463-set-them-ablaze",
            kind = "turnin",
            priority = 76,
            conditions = { level = { min = 40 } },
            text = "Turn in Set Them Ablaze! to Squire Maltrake.",
            dependsOn = { "objective-3463-4-set-the-northern-tower-a", "objective-3463-1-set-the-western-tower-ab", "objective-3463-2-set-the-southern-tower-a", "objective-3463-3-set-the-eastern-tower-ab" },
            complete = QuestState(3463, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.392, 0.390, "Squire Maltrake", "Travel to Searing Gorge."),
            },
        },
        {
            id = "note-click-hoard-of-the-black-dragonflight",
            kind = "note",
            priority = 77,
            conditions = { level = { min = 52 } },
            text = "Click Hoard of the Black Dragonflight.",
        },
        {
            id = "accept-3481-trinkets",
            kind = "accept",
            priority = 78,
            conditions = { level = { min = 40 } },
            text = "Accept Trinkets.",
            complete = QuestState(3481, "activeOrCompleted"),
            route = {
                Point(MAP.SEARING_GORGE, 0.389, 0.390, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-3481-trinkets",
            kind = "turnin",
            priority = 79,
            conditions = { level = { min = 40 } },
            text = "Turn in Trinkets.",
            dependsOn = { "accept-3481-trinkets" },
            complete = QuestState(3481, "completed"),
            route = {
                Point(MAP.SEARING_GORGE, 0.389, 0.390, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "accept-4123-the-heart-of-the-mountain",
            kind = "accept",
            priority = 80,
            conditions = { level = { min = 50 } },
            text = "Accept The Heart of the Mountain from Maxwort Uberglint.",
            complete = QuestState(4123, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.239, "Maxwort Uberglint", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4324-yuka-screwspigot",
            kind = "turnin",
            priority = 81,
            conditions = { level = { min = 48 } },
            text = "Turn in Yuka Screwspigot to Yuka Screwspigot.",
            dependsOn = { "accept-4324-yuka-screwspigot" },
            complete = QuestState(4324, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.661, 0.220, "Yuka Screwspigot", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4136-ribbly-screwspigot",
            kind = "accept",
            priority = 82,
            conditions = { level = { min = 48 } },
            text = "Accept Ribbly Screwspigot from Yuka Screwspigot.",
            dependsOn = { "turnin-4324-yuka-screwspigot" },
            complete = QuestState(4136, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.661, 0.220, "Yuka Screwspigot", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4022-a-taste-of-flame",
            kind = "accept",
            priority = 83,
            conditions = { level = { min = 52 } },
            text = "Accept A Taste of Flame from Cyrus Therepentous.",
            complete = QuestState(4022, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.951, 0.316, "Cyrus Therepentous", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4022-1-black-dragonflight-molt",
            kind = "objective",
            priority = 84,
            conditions = { level = { min = 52 } },
            text = "Collect Black Dragonflight Molt.",
            dependsOn = { "accept-4022-a-taste-of-flame" },
            complete = QuestState(4022, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4022-a-taste-of-flame",
            kind = "turnin",
            priority = 85,
            conditions = { level = { min = 52 } },
            text = "Turn in A Taste of Flame to Cyrus Therepentous.",
            dependsOn = { "objective-4022-1-black-dragonflight-molt" },
            complete = QuestState(4022, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.951, 0.316, "Cyrus Therepentous", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4024-a-taste-of-flame",
            kind = "accept",
            priority = 86,
            conditions = { level = { min = 52 } },
            text = "Accept A Taste of Flame from Cyrus Therepentous.",
            dependsOn = { "turnin-4022-a-taste-of-flame" },
            complete = QuestState(4024, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.951, 0.316, "Cyrus Therepentous", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-3801-dark-iron-legacy",
            kind = "accept",
            priority = 87,
            conditions = { level = { min = 48 } },
            text = "Accept Dark Iron Legacy from Franclorn Forgewright.",
            complete = QuestState(3801, "activeOrCompleted"),
        },
        {
            id = "turnin-3801-dark-iron-legacy",
            kind = "turnin",
            priority = 88,
            conditions = { level = { min = 48 } },
            text = "Turn in Dark Iron Legacy to Franclorn Forgewright.",
            dependsOn = { "accept-3801-dark-iron-legacy" },
            complete = QuestState(3801, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-3802-dark-iron-legacy",
            kind = "accept",
            priority = 89,
            conditions = { level = { min = 48 } },
            text = "Accept Dark Iron Legacy from Franclorn Forgewright.",
            dependsOn = { "turnin-3801-dark-iron-legacy" },
            complete = QuestState(3802, "activeOrCompleted"),
        },
        {
            id = "objective-4262-1-overmaster-pyron",
            kind = "objective",
            priority = 90,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill Overmaster Pyron.",
            dependsOn = { "accept-4262-overmaster-pyron" },
            complete = QuestState(4262, "complete"),
            route = {
                Point(MAP.SEARING_GORGE, 0.264, 0.777, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 91,
            conditions = { level = { min = 52 } },
            text = "Enter Blackrock Depths with your group.",
            dependsOn = { "accept-4324-yuka-screwspigot", "accept-3702-the-smoldering-ruins-of-thaurissan", "accept-3701-the-smoldering-ruins-of-thaurissan", "accept-4128-ragnar-thunderbrew", "accept-4126-hurley-blackbreath", "accept-4286-the-good-stuff", "accept-4182-dragonkin-menace", "accept-4262-overmaster-pyron", "accept-4183-the-true-masters", "accept-4341-kharan-mighthammer", "accept-4184-the-true-masters", "accept-4185-the-true-masters", "accept-4186-the-true-masters", "accept-4223-the-true-masters", "accept-4224-the-true-masters", "accept-4241-marshal-windsor", "accept-3441-divine-retribution", "accept-3442-the-flawless-flame", "accept-3443-forging-the-shaft", "accept-3452-the-flame-s-casing", "accept-3453-the-torch-of-retribution", "accept-3454-the-torch-of-retribution", "accept-3462-squire-maltrake", "accept-3463-set-them-ablaze", "accept-3481-trinkets", "accept-4123-the-heart-of-the-mountain", "accept-4136-ribbly-screwspigot", "accept-4022-a-taste-of-flame", "accept-4024-a-taste-of-flame", "accept-3801-dark-iron-legacy", "accept-3802-dark-iron-legacy" },
            persistCompletion = true,
            complete = { instance = 230 },
            route = {
                Point(MAP.SEARING_GORGE, 0.372, 0.944, "Blackrock Depths entrance", "Travel to Searing Gorge."),
            },
        },
        {
            id = "boss-anvilrage-dwarves-at-the-beginning-of-the",
            kind = "note",
            priority = 92,
            conditions = { level = { min = 52 } },
            text = "Kill Anvilrage dwarves at the beginning of the dungeon. Just clear the first few rooms of the dungeon, killing all the Anvilrage dwarves and resetting the instance if needed, until you get the item drop.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "accept-4264-a-crumpled-up-note",
            kind = "accept",
            priority = 93,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept A Crumpled Up Note.",
            complete = QuestState(4264, "activeOrCompleted"),
        },
        {
            id = "boss-high-interrogator-gerstahn",
            kind = "note",
            priority = 94,
            conditions = { level = { min = 52 } },
            text = "Kill High Interrogator Gerstahn. After entering the dungeon, go straight into the Detention Block and then take the first right. Follow this path around until you can go left into a room at the back of this long hallway. Her most dangerous ability is 'Psychic Scream' which will fear the entire group, possibly leading to adds being pulled. 'Fear Ward' and 'Tremor Totem' will come in very handy during this encounter. Fight her in a corner of the room to try and control where your party runs during fear.",
            dependsOn = { "boss-anvilrage-dwarves-at-the-beginning-of-the" },
        },
        {
            id = "note-click-cell-door",
            kind = "note",
            priority = 95,
            conditions = { level = { min = 52 } },
            text = "Click Cell Door.",
        },
        {
            id = "turnin-4341-kharan-mighthammer",
            kind = "turnin",
            priority = 96,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Kharan Mighthammer to Kharan Mighthammer.",
            dependsOn = { "accept-4341-kharan-mighthammer" },
            complete = QuestState(4341, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4342-kharan-s-tale",
            kind = "accept",
            priority = 97,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Kharan's Tale from Kharan Mighthammer.",
            dependsOn = { "turnin-4341-kharan-mighthammer" },
            complete = QuestState(4342, "activeOrCompleted"),
        },
        {
            id = "objective-4342-1-hear-kharan-s-tale",
            kind = "gossip",
            priority = 98,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Talk to Kharan Mighthammer. 'All is not lost, Kharan!' Hear Kharan's Tale.",
            dependsOn = { "accept-4342-kharan-s-tale" },
            complete = QuestState(4342, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4342-kharan-s-tale",
            kind = "turnin",
            priority = 99,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Kharan's Tale to Kharan Mighthammer.",
            dependsOn = { "objective-4342-1-hear-kharan-s-tale" },
            complete = QuestState(4342, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4361-the-bearer-of-bad-news",
            kind = "accept",
            priority = 100,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Bearer of Bad News from Kharan Mighthammer.",
            dependsOn = { "turnin-4342-kharan-s-tale" },
            complete = QuestState(4361, "activeOrCompleted"),
        },
        {
            id = "turnin-4241-marshal-windsor",
            kind = "turnin",
            priority = 101,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Marshal Windsor to Marshal Windsor.",
            dependsOn = { "accept-4241-marshal-windsor" },
            complete = QuestState(4241, "completed"),
            useClientPin = true,
        },
        {
            id = "turnin-4264-a-crumpled-up-note",
            kind = "turnin",
            priority = 102,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in A Crumpled Up Note to Marshal Windsor.",
            dependsOn = { "accept-4264-a-crumpled-up-note" },
            complete = QuestState(4264, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4242-abandoned-hope",
            kind = "accept",
            priority = 103,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Abandoned Hope from Marshal Windsor.",
            dependsOn = { "turnin-4264-a-crumpled-up-note" },
            complete = QuestState(4242, "activeOrCompleted"),
        },
        {
            id = "accept-4282-a-shred-of-hope",
            kind = "accept",
            priority = 104,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept A Shred of Hope from Marshal Windsor.",
            complete = QuestState(4282, "activeOrCompleted"),
        },
        {
            id = "boss-fineous-darkvire",
            kind = "note",
            priority = 105,
            conditions = { level = { min = 52 } },
            text = "Kill Fineous Darkvire. Leave the tunnel and head east through the Detention Block and then turn left after reaching the Halls of the Law to start the Ring of the Law event. Complete the event and then exit through the west gate to enter the Eastern Garrison, immediately take a sharp right and go up the stairs to reach the upper. Follow the path around the arena and go down the ramp on the other side, go left and across the bridge to The Domicile. Clear all enemies along the path he patrols before engaging. This boss hits very hard, so extra healing may be required. Be sure to interrupt his 'Holy Light' as to not prolong the encounter.",
            dependsOn = { "boss-high-interrogator-gerstahn" },
        },
        {
            id = "objective-3802-1-ironfel",
            kind = "objective",
            priority = 106,
            conditions = { level = { min = 48 } },
            text = "Collect Ironfel.",
            dependsOn = { "accept-3802-dark-iron-legacy" },
            complete = QuestState(3802, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-monument-of-franclorn-forgewright",
            kind = "note",
            priority = 107,
            conditions = { level = { min = 52 } },
            text = "Click Monument of Franclorn Forgewright.",
        },
        {
            id = "turnin-3802-dark-iron-legacy",
            kind = "turnin",
            priority = 108,
            conditions = { level = { min = 48 } },
            text = "Turn in Dark Iron Legacy.",
            dependsOn = { "objective-3802-1-ironfel" },
            complete = QuestState(3802, "completed"),
            useClientPin = true,
        },
        {
            id = "boss-bael-gar",
            kind = "note",
            priority = 109,
            conditions = { level = { min = 52 } },
            text = "Kill Bael'Gar. Turn around and cross the bridge in Shadowforge City to once again reach The Domicile. Follow the same path as before to reach the Hall of Crafting where you killed Fineous Darkvire. Continue down through the Hall of Crafting's lower level to reach the boss Lord Incendius. This is an optional boss and may be skipped. He will spawn adds which need to be killed quickly. The tank will need to face him away from the group to prevent damage from 'Magma Splash'.",
            dependsOn = { "boss-fineous-darkvire" },
        },
        {
            id = "objective-4024-1-encased-fiery-essence",
            kind = "objective",
            priority = 110,
            conditions = { level = { min = 52 } },
            text = "Collect Encased Fiery Essence.",
            dependsOn = { "accept-4024-a-taste-of-flame" },
            complete = QuestState(4024, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-general-angerforge",
            kind = "note",
            priority = 111,
            conditions = { level = { min = 52 } },
            text = "Kill General Angerforge. Run back down the Dark Iron Highway, take the first right and unlock the gate on your left. Unlock the first door on your left to enter East Garrison. In the lower part of this room, click the Shadowforge Lock. run up the two sets of stairs and follow the hallway on the left just before the third set of. This boss is optional. During the encounter, he will summon adds which need to be AoE'd down. Aside from the tanks picking up adds, the fight is straight forward.",
            dependsOn = { "boss-bael-gar" },
        },
        {
            id = "objective-4282-1-marshal-windsor-s-lost-i",
            kind = "objective",
            priority = 112,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect Marshal Windsor's Lost Information.",
            dependsOn = { "accept-4282-a-shred-of-hope" },
            complete = QuestObjective(4282, 1, "Marshal Windsor's Lost Information"),
            useClientPin = true,
        },
        {
            id = "boss-golem-lord-argelmach",
            kind = "note",
            priority = 113,
            conditions = { level = { min = 52 } },
            text = "Kill Golem Lord Argelmach. Run back down the Dark Iron Highway, take the first right and unlock the gate on your left. Unlock the first door on your left to enter East Garrison. In the lower part of this room, click the Shadowforge Lock. run up the two sets of stairs and follow the hallway on the left just before the third set of.",
            dependsOn = { "boss-general-angerforge" },
        },
        {
            id = "objective-4282-2-marshal-windsor-s-lost-i",
            kind = "objective",
            priority = 114,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect Marshal Windsor's Lost Information.",
            dependsOn = { "accept-4282-a-shred-of-hope" },
            complete = QuestObjective(4282, 2, "Marshal Windsor's Lost Information"),
            useClientPin = true,
        },
        {
            id = "accept-4201-the-love-potion",
            kind = "accept",
            priority = 115,
            conditions = { level = { min = 50 } },
            text = "Accept The Love Potion from Mistress Nagmara.",
            complete = QuestState(4201, "activeOrCompleted"),
        },
        {
            id = "boss-ribbly-screwspigot",
            kind = "note",
            priority = 116,
            conditions = { level = { min = 52 } },
            text = "Kill Ribbly Screwspigot. He's at the bottom level of the Grim Guzzler.",
            dependsOn = { "boss-golem-lord-argelmach" },
        },
        {
            id = "objective-4136-1-ribbly-s-head",
            kind = "gossip",
            priority = 117,
            conditions = { level = { min = 48 } },
            text = "Talk to Ribbly Screwspigot. 'Your family says hello, Ribbly. And they want your head!' Collect Ribbly's Head.",
            dependsOn = { "accept-4136-ribbly-screwspigot" },
            complete = QuestState(4136, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-thunderbrew-lager-keg",
            kind = "note",
            priority = 118,
            conditions = { level = { min = 52 } },
            text = "Click Thunderbrew Lager Keg+.",
        },
        {
            id = "boss-hurley-blackbreath",
            kind = "note",
            priority = 119,
            conditions = { level = { min = 52 } },
            text = "Kill Hurley Blackbreath. They look like wooden kegs sitting in a side room in the lower section of The Grim Guzzler. Destroy all three kegs to spawn Hurley Blackbreath.",
            dependsOn = { "boss-ribbly-screwspigot" },
        },
        {
            id = "objective-4126-1-lost-thunderbrew-recipe",
            kind = "objective",
            priority = 120,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect Lost Thunderbrew Recipe.",
            dependsOn = { "accept-4126-hurley-blackbreath" },
            complete = QuestState(4126, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-relic-coffer-door",
            kind = "note",
            priority = 121,
            conditions = { level = { min = 52 } },
            text = "Click Relic Coffer Door.",
        },
        {
            id = "boss-watchman-doomgrip",
            kind = "note",
            priority = 122,
            conditions = { level = { min = 52 } },
            text = "Kill Watchman Doomgrip. Open all 12 of them inside of the Black Vault after clearing the room. Proceed back through The Domicile to reach the Shadowforge City. take the first door on the right to enter The Black Vault. He will spawn once all 12 Relic Coffer Doors have been opened.",
            dependsOn = { "boss-hurley-blackbreath" },
        },
        {
            id = "note-click-heart-of-the-mountain",
            kind = "note",
            priority = 123,
            conditions = { level = { min = 52 } },
            text = "Click Heart of the Mountain.",
        },
        {
            id = "objective-4123-1-the-heart-of-the-mountai",
            kind = "objective",
            priority = 124,
            conditions = { level = { min = 50 } },
            text = "Collect The Heart of the Mountain.",
            dependsOn = { "accept-4123-the-heart-of-the-mountain" },
            complete = QuestState(4123, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4282-a-shred-of-hope",
            kind = "turnin",
            priority = 125,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in A Shred of Hope to Marshal Windsor.",
            dependsOn = { "objective-4282-1-marshal-windsor-s-lost-i", "objective-4282-2-marshal-windsor-s-lost-i" },
            complete = QuestState(4282, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4322-jail-break",
            kind = "accept",
            priority = 126,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Jail Break! from Marshal Windsor.",
            dependsOn = { "turnin-4282-a-shred-of-hope" },
            complete = QuestState(4322, "activeOrCompleted"),
        },
        {
            id = "objective-4322-1-help-marshal-windsor-esc",
            kind = "objective",
            priority = 127,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Help Marshal Windsor Escape the Blackrock Depths.",
            dependsOn = { "accept-4322-jail-break" },
            complete = QuestState(4322, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4286-1-dark-iron-fanny-pack",
            kind = "objective",
            priority = 128,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect 20 Dark Iron Fanny Pack.",
            dependsOn = { "accept-4286-the-good-stuff" },
            complete = QuestState(4286, "complete"),
            useClientPin = true,
        },
        {
            id = "note-leave-the-dungeon",
            kind = "note",
            priority = 129,
            conditions = { level = { min = 52 } },
            text = "Leave the dungeon.",
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 130,
            conditions = { level = { min = 52 } },
            text = "Click Here to Continue.",
        },
        {
            id = "turnin-4322-jail-break",
            kind = "turnin",
            priority = 131,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Jail Break! to Marshal Maxwell.",
            dependsOn = { "objective-4322-1-help-marshal-windsor-esc" },
            complete = QuestState(4322, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4242-abandoned-hope",
            kind = "turnin",
            priority = 132,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Abandoned Hope to Marshal Maxwell.",
            dependsOn = { "accept-4242-abandoned-hope" },
            complete = QuestState(4242, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.847, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4286-the-good-stuff",
            kind = "turnin",
            priority = 133,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Good Stuff to Oralius.",
            dependsOn = { "objective-4286-1-dark-iron-fanny-pack" },
            complete = QuestState(4286, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.846, 0.687, "Oralius", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4262-overmaster-pyron",
            kind = "turnin",
            priority = 134,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Overmaster Pyron to Jalinda Sprig.",
            dependsOn = { "objective-4262-1-overmaster-pyron" },
            complete = QuestState(4262, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.854, 0.701, "Jalinda Sprig", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4263-incendius",
            kind = "accept",
            priority = 135,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Incendius! from Jalinda Sprig.",
            dependsOn = { "turnin-4262-overmaster-pyron" },
            complete = QuestState(4263, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.854, 0.701, "Jalinda Sprig", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4361-the-bearer-of-bad-news",
            kind = "turnin",
            priority = 136,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Bearer of Bad News to King Magni Bronzebeard.",
            dependsOn = { "accept-4361-the-bearer-of-bad-news" },
            complete = QuestState(4361, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.391, 0.562, "King Magni Bronzebeard", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-4362-the-fate-of-the-kingdom",
            kind = "accept",
            priority = 137,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Fate of the Kingdom from King Magni Bronzebeard.",
            dependsOn = { "turnin-4361-the-bearer-of-bad-news" },
            complete = QuestState(4362, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.391, 0.562, "King Magni Bronzebeard", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-4126-hurley-blackbreath",
            kind = "turnin",
            priority = 138,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Hurley Blackbreath to Ragnar Thunderbrew.",
            dependsOn = { "objective-4126-1-lost-thunderbrew-recipe" },
            complete = QuestState(4126, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.468, 0.524, "Ragnar Thunderbrew", "Travel to Dun Morogh."),
            },
        },
        {
            id = "turnin-4123-the-heart-of-the-mountain",
            kind = "turnin",
            priority = 139,
            conditions = { level = { min = 50 } },
            text = "Turn in The Heart of the Mountain to Maxwort Uberglint.",
            dependsOn = { "objective-4123-1-the-heart-of-the-mountai" },
            complete = QuestState(4123, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.239, "Maxwort Uberglint", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4136-ribbly-screwspigot",
            kind = "turnin",
            priority = 140,
            conditions = { level = { min = 48 } },
            text = "Turn in Ribbly Screwspigot to Yuka Screwspigot.",
            dependsOn = { "objective-4136-1-ribbly-s-head" },
            complete = QuestState(4136, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.661, 0.220, "Yuka Screwspigot", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4024-a-taste-of-flame",
            kind = "turnin",
            priority = 141,
            conditions = { level = { min = 52 } },
            text = "Turn in A Taste of Flame to Cyrus Therepentous.",
            dependsOn = { "objective-4024-1-encased-fiery-essence" },
            complete = QuestState(4024, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.951, 0.316, "Cyrus Therepentous", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4201-1-gromsblood",
            kind = "objective",
            priority = 142,
            conditions = { level = { min = 50 } },
            text = "Collect 4 Gromsblood.",
            dependsOn = { "accept-4201-the-love-potion" },
            complete = QuestObjective(4201, 1, "Gromsblood"),
            useClientPin = true,
        },
        {
            id = "boss-cliff-enemies-around-this-area",
            kind = "note",
            priority = 143,
            conditions = { level = { min = 52 } },
            text = "Kill Cliff enemies around this area. These are elite. You may need help with this.",
            dependsOn = { "boss-watchman-doomgrip" },
        },
        {
            id = "objective-4201-2-giant-silver-vein",
            kind = "objective",
            priority = 144,
            conditions = { level = { min = 50 } },
            text = "Collect 10 Giant Silver Vein.",
            dependsOn = { "accept-4201-the-love-potion" },
            complete = QuestObjective(4201, 2, "Giant Silver Vein"),
            route = {
                Point(MAP.AZSHARA, 0.448, 0.854, "Azshara", "Travel to Azshara."),
            },
        },
        {
            id = "objective-4201-3-nagmara-s-filled-vial",
            kind = "objective",
            priority = 145,
            conditions = { level = { min = 50 } },
            text = "Collect Nagmara's Filled Vial.",
            dependsOn = { "accept-4201-the-love-potion" },
            complete = QuestObjective(4201, 3, "Nagmara's Filled Vial"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.320, 0.500, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4263-1-lord-incendius",
            kind = "objective",
            priority = 146,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill Lord Incendius.",
            dependsOn = { "accept-4263-incendius" },
            complete = QuestState(4263, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4201-the-love-potion",
            kind = "turnin",
            priority = 147,
            conditions = { level = { min = 50 } },
            text = "Turn in The Love Potion to Mistress Nagmara.",
            dependsOn = { "objective-4201-1-gromsblood", "objective-4201-2-giant-silver-vein", "objective-4201-3-nagmara-s-filled-vial" },
            complete = QuestState(4201, "completed"),
            useClientPin = true,
        },
        {
            id = "boss-emperor-dagran-thaurissan",
            kind = "note",
            priority = 148,
            conditions = { level = { min = 52 } },
            text = "Kill Emperor Dagran Thaurissan. Don't kill Princess Moira Bronzebeard during the encounter. Interrupt her heals otherwise the encounter will be complicated. You will not be able to turn in the quest if you kill her. During the encounter, your group will need to decide what to do with Princess Moira Bronzebeard. Keep her CC'd if you chose to save her while keeping her away from AoE damage. If you fail to keep her controlled, have a group member dedicated to interrupting her healing abilities.",
            dependsOn = { "boss-cliff-enemies-around-this-area" },
        },
        {
            id = "objective-4362-1-emperor-dagran-thaurissa",
            kind = "objective",
            priority = 149,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Slay Emperor Dagran Thaurissan.",
            dependsOn = { "accept-4362-the-fate-of-the-kingdom" },
            complete = QuestState(4362, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4362-the-fate-of-the-kingdom",
            kind = "turnin",
            priority = 150,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Fate of the Kingdom to Princess Moira Bronzebeard.",
            dependsOn = { "objective-4362-1-emperor-dagran-thaurissa" },
            complete = QuestState(4362, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4363-the-princess-s-surprise",
            kind = "accept",
            priority = 151,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Princess's Surprise from Princess Moira Bronzebeard.",
            dependsOn = { "turnin-4362-the-fate-of-the-kingdom" },
            complete = QuestState(4363, "activeOrCompleted"),
        },
        {
            id = "turnin-4263-incendius",
            kind = "turnin",
            priority = 152,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Incendius! to Jalinda Sprig.",
            dependsOn = { "objective-4263-1-lord-incendius" },
            complete = QuestState(4263, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.854, 0.701, "Jalinda Sprig", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4363-the-princess-s-surprise",
            kind = "turnin",
            priority = 153,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Princess's Surprise to King Magni Bronzebeard.",
            dependsOn = { "accept-4363-the-princess-s-surprise" },
            complete = QuestState(4363, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.391, 0.562, "King Magni Bronzebeard", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-4133-vivian-lagrave",
            kind = "accept",
            priority = 154,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Accept Vivian Lagrave from Apothecary Zinge.",
            complete = QuestState(4133, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.501, 0.680, "Apothecary Zinge", "Travel to Undercity."),
            },
        },
        {
            id = "turnin-4133-vivian-lagrave",
            kind = "turnin",
            priority = 155,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Turn in Vivian Lagrave to Shadowmage Vivian Lagrave.",
            dependsOn = { "accept-4133-vivian-lagrave" },
            complete = QuestState(4133, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.029, 0.478, "Shadowmage Vivian Lagrave", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4134-lost-thunderbrew-recipe",
            kind = "accept",
            priority = 156,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Accept Lost Thunderbrew Recipe from Shadowmage Vivian Lagrave.",
            dependsOn = { "turnin-4133-vivian-lagrave" },
            complete = QuestState(4134, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.029, 0.478, "Shadowmage Vivian Lagrave", "Travel to Badlands."),
            },
        },
        {
            id = "accept-3906-disharmony-of-flame",
            kind = "accept",
            priority = 157,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept Disharmony of Flame from Thunderheart.",
            complete = QuestState(3906, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.033, 0.483, "Thunderheart", "Travel to Badlands."),
            },
        },
        {
            id = "note-click-wanted",
            kind = "note",
            priority = 158,
            conditions = { level = { min = 52 } },
            text = "Click WANTED.",
        },
        {
            id = "accept-4081-kill-on-sight-dark-iron-dwarves",
            kind = "accept",
            priority = 159,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept KILL ON SIGHT: Dark Iron Dwarves.",
            complete = QuestState(4081, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.038, 0.475, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4061-the-rise-of-the-machines",
            kind = "accept",
            priority = 160,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Accept The Rise of the Machines from Hierophant Theodora Mulvadania.",
            complete = QuestState(4061, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.030, 0.478, "Hierophant Theodora Mulvadania", "Travel to Badlands."),
            },
        },
        {
            id = "objective-4061-1-fractured-elemental-shar",
            kind = "objective",
            priority = 161,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Collect 10 Fractured Elemental Shard.",
            dependsOn = { "accept-4061-the-rise-of-the-machines" },
            complete = QuestState(4061, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.624, 0.405, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4061-the-rise-of-the-machines",
            kind = "turnin",
            priority = 162,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Turn in The Rise of the Machines to Hierophant Theodora Mulvadania.",
            dependsOn = { "objective-4061-1-fractured-elemental-shar" },
            complete = QuestState(4061, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.030, 0.478, "Hierophant Theodora Mulvadania", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4062-the-rise-of-the-machines",
            kind = "accept",
            priority = 163,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Accept The Rise of the Machines from Hierophant Theodora Mulvadania.",
            dependsOn = { "turnin-4061-the-rise-of-the-machines" },
            complete = QuestState(4062, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.030, 0.478, "Hierophant Theodora Mulvadania", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4062-the-rise-of-the-machines",
            kind = "turnin",
            priority = 164,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Turn in The Rise of the Machines to Lotwil Veriatus.",
            dependsOn = { "accept-4062-the-rise-of-the-machines" },
            complete = QuestState(4062, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.260, 0.449, "Lotwil Veriatus", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4063-the-rise-of-the-machines",
            kind = "accept",
            priority = 165,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Accept The Rise of the Machines from Lotwil Veriatus.",
            dependsOn = { "turnin-4062-the-rise-of-the-machines" },
            complete = QuestState(4063, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.260, 0.449, "Lotwil Veriatus", "Travel to Badlands."),
            },
        },
        {
            id = "objective-3906-1-overmaster-pyron",
            kind = "objective",
            priority = 166,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Kill Overmaster Pyron.",
            dependsOn = { "accept-3906-disharmony-of-flame" },
            complete = QuestState(3906, "complete"),
            route = {
                Point(MAP.SEARING_GORGE, 0.264, 0.777, "Searing Gorge", "Travel to Searing Gorge."),
            },
        },
        {
            id = "boss-lord-roccor",
            kind = "note",
            priority = 167,
            conditions = { level = { min = 52 } },
            text = "Kill Lord Roccor. This boss can use 'Earth Shock' which will interrupt any casters spells and prevent casting for 2 seconds. It also casts 'Flame Shock' which will leave a dot on a party member.",
            dependsOn = { "boss-emperor-dagran-thaurissan" },
        },
        {
            id = "boss-houndmaster-grebmar",
            kind = "note",
            priority = 168,
            conditions = { level = { min = 52 } },
            text = "Kill Houndmaster Grebmar. Before engaging him, pull and kill the two packs of hounds patrolling the room with him. Range should keep their distance to avoid being interrupted with 'Pummel'. Other than that, this is a pretty straight forward encounter.",
            dependsOn = { "boss-lord-roccor" },
        },
        {
            id = "boss-pyromancer-loregrain",
            kind = "note",
            priority = 169,
            conditions = { level = { min = 52 } },
            text = "Kill Pyromancer Loregrain. This is an optional boss and may be skipped. Destroy his totems when they are summoned.",
            dependsOn = { "boss-houndmaster-grebmar" },
        },
        {
            id = "objective-4063-1-head-of-argelmach",
            kind = "objective",
            priority = 170,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Collect Head of Argelmach.",
            dependsOn = { "accept-4063-the-rise-of-the-machines" },
            complete = QuestObjective(4063, 1, "Head of Argelmach"),
            useClientPin = true,
        },
        {
            id = "objective-4134-1-lost-thunderbrew-recipe",
            kind = "objective",
            priority = 171,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Collect Lost Thunderbrew Recipe.",
            dependsOn = { "accept-4134-lost-thunderbrew-recipe" },
            complete = QuestState(4134, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4063-2-intact-elemental-core",
            kind = "objective",
            priority = 172,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Collect 10 Intact Elemental Core.",
            dependsOn = { "accept-4063-the-rise-of-the-machines" },
            complete = QuestObjective(4063, 2, "Intact Elemental Core"),
            useClientPin = true,
        },
        {
            id = "objective-4081-1-anvilrage-guardsman",
            kind = "objective",
            priority = 173,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Kill 15 Anvilrage Guardsman.",
            dependsOn = { "accept-4081-kill-on-sight-dark-iron-dwarves" },
            complete = QuestObjective(4081, 1, "Anvilrage Guardsman"),
            useClientPin = true,
        },
        {
            id = "objective-4081-2-anvilrage-warden",
            kind = "objective",
            priority = 174,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Kill 10 Anvilrage Warden.",
            dependsOn = { "accept-4081-kill-on-sight-dark-iron-dwarves" },
            complete = QuestObjective(4081, 2, "Anvilrage Warden"),
            useClientPin = true,
        },
        {
            id = "objective-4081-3-anvilrage-footman",
            kind = "objective",
            priority = 175,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Kill 5 Anvilrage Footman.",
            dependsOn = { "accept-4081-kill-on-sight-dark-iron-dwarves" },
            complete = QuestObjective(4081, 3, "Anvilrage Footman"),
            useClientPin = true,
        },
        {
            id = "turnin-3906-disharmony-of-flame",
            kind = "turnin",
            priority = 176,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in Disharmony of Flame to Thunderheart.",
            dependsOn = { "objective-3906-1-overmaster-pyron" },
            complete = QuestState(3906, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.033, 0.483, "Thunderheart", "Travel to Badlands."),
            },
        },
        {
            id = "accept-3907-disharmony-of-fire",
            kind = "accept",
            priority = 177,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept Disharmony of Fire from Thunderheart.",
            dependsOn = { "turnin-3906-disharmony-of-flame" },
            complete = QuestState(3907, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.033, 0.483, "Thunderheart", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4134-lost-thunderbrew-recipe",
            kind = "turnin",
            priority = 178,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Turn in Lost Thunderbrew Recipe to Shadowmage Vivian Lagrave.",
            dependsOn = { "objective-4134-1-lost-thunderbrew-recipe" },
            complete = QuestState(4134, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.029, 0.478, "Shadowmage Vivian Lagrave", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4081-kill-on-sight-dark-iron-dwarves",
            kind = "turnin",
            priority = 179,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in KILL ON SIGHT: Dark Iron Dwarves to Warlord Goretooth.",
            dependsOn = { "objective-4081-1-anvilrage-guardsman", "objective-4081-2-anvilrage-warden", "objective-4081-3-anvilrage-footman" },
            complete = QuestState(4081, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "note-click-kill-on-sight",
            kind = "note",
            priority = 180,
            conditions = { level = { min = 52 } },
            text = "Click KILL ON SIGHT.",
        },
        {
            id = "accept-4082-kill-on-sight-high-ranking-dark-iron-offic",
            kind = "accept",
            priority = 181,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Accept KILL ON SIGHT: High Ranking Dark Iron Officials.",
            complete = QuestState(4082, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.040, 0.468, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4063-the-rise-of-the-machines",
            kind = "turnin",
            priority = 182,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Turn in The Rise of the Machines to Lotwil Veriatus.",
            dependsOn = { "objective-4063-1-head-of-argelmach", "objective-4063-2-intact-elemental-core" },
            complete = QuestState(4063, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.260, 0.449, "Lotwil Veriatus", "Travel to Badlands."),
            },
        },
        {
            id = "objective-3907-1-lord-incendius",
            kind = "objective",
            priority = 183,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Kill Lord Incendius.",
            dependsOn = { "accept-3907-disharmony-of-fire" },
            complete = QuestObjective(3907, 1, "Lord Incendius"),
            useClientPin = true,
        },
        {
            id = "boss-lord-incendius",
            kind = "note",
            priority = 184,
            conditions = { level = { min = 52 } },
            text = "Kill Lord Incendius. The most important thing for this encounter is to not get knocked off the platform. Avoid its 'Mighty Blow' ability to ensure that.",
            dependsOn = { "boss-pyromancer-loregrain" },
        },
        {
            id = "objective-3907-2-tablet-of-kurniya",
            kind = "objective",
            priority = 185,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Collect Tablet of Kurniya.",
            dependsOn = { "accept-3907-disharmony-of-fire" },
            complete = QuestObjective(3907, 2, "Tablet of Kurniya"),
            useClientPin = true,
        },
        {
            id = "objective-4082-1-anvilrage-medic",
            kind = "objective",
            priority = 186,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Kill 10 Anvilrage Medic.",
            dependsOn = { "accept-4082-kill-on-sight-high-ranking-dark-iron-offic" },
            complete = QuestObjective(4082, 1, "Anvilrage Medic"),
            useClientPin = true,
        },
        {
            id = "objective-4082-2-anvilrage-soldier",
            kind = "objective",
            priority = 187,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Kill 10 Anvilrage Soldier.",
            dependsOn = { "accept-4082-kill-on-sight-high-ranking-dark-iron-offic" },
            complete = QuestObjective(4082, 2, "Anvilrage Soldier"),
            useClientPin = true,
        },
        {
            id = "objective-4082-3-anvilrage-officer",
            kind = "objective",
            priority = 188,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Kill 10 Anvilrage Officer.",
            dependsOn = { "accept-4082-kill-on-sight-high-ranking-dark-iron-offic" },
            complete = QuestObjective(4082, 3, "Anvilrage Officer"),
            useClientPin = true,
        },
        {
            id = "turnin-3907-disharmony-of-fire",
            kind = "turnin",
            priority = 189,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in Disharmony of Fire to Thunderheart.",
            dependsOn = { "objective-3907-1-lord-incendius", "objective-3907-2-tablet-of-kurniya" },
            complete = QuestState(3907, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.033, 0.483, "Thunderheart", "Travel to Badlands."),
            },
        },
        {
            id = "accept-3981-commander-gor-shak",
            kind = "accept",
            priority = 190,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept Commander Gor'shak from Galamav the Marksman.",
            complete = QuestState(3981, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.060, 0.477, "Galamav the Marksman", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4082-kill-on-sight-high-ranking-dark-iron-offic",
            kind = "turnin",
            priority = 191,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Turn in KILL ON SIGHT: High Ranking Dark Iron Officials to Warlord Goretooth.",
            dependsOn = { "objective-4082-1-anvilrage-medic", "objective-4082-2-anvilrage-soldier", "objective-4082-3-anvilrage-officer" },
            complete = QuestState(4082, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-3981-commander-gor-shak",
            kind = "turnin",
            priority = 192,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in Commander Gor'shak to Commander Gor'shak.",
            dependsOn = { "accept-3981-commander-gor-shak" },
            complete = QuestState(3981, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-3982-what-is-going-on",
            kind = "accept",
            priority = 193,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept What Is Going On? from Commander Gor'shak.",
            dependsOn = { "turnin-3981-commander-gor-shak" },
            complete = QuestState(3982, "activeOrCompleted"),
        },
        {
            id = "boss-the-enemies-that-attack-in-waves",
            kind = "note",
            priority = 194,
            conditions = { level = { min = 52 } },
            text = "Kill the enemies that attack in waves. There will be two waves of enemies. Make sure Commander Gor'shak doesn't die.",
            dependsOn = { "boss-lord-incendius" },
        },
        {
            id = "objective-3982-1-survive-the-onslaught",
            kind = "objective",
            priority = 195,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Survive the Onslaught.",
            dependsOn = { "accept-3982-what-is-going-on" },
            complete = QuestState(3982, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-3982-what-is-going-on",
            kind = "turnin",
            priority = 196,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in What Is Going On? to Commander Gor'shak.",
            dependsOn = { "objective-3982-1-survive-the-onslaught" },
            complete = QuestState(3982, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4001-what-is-going-on",
            kind = "accept",
            priority = 197,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept What Is Going On? from Commander Gor'shak.",
            dependsOn = { "turnin-3982-what-is-going-on" },
            complete = QuestState(4001, "activeOrCompleted"),
        },
        {
            id = "objective-4001-1-information-from-kharan",
            kind = "gossip",
            priority = 198,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Talk to Kharan Mighthammer. 'I need to know where the princess are, Kharan!' Gather Information from Kharan.",
            dependsOn = { "accept-4001-what-is-going-on" },
            complete = QuestState(4001, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4001-what-is-going-on",
            kind = "turnin",
            priority = 199,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in What Is Going On? to Thrall.",
            dependsOn = { "objective-4001-1-information-from-kharan" },
            complete = QuestState(4001, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.318, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-4002-the-eastern-kingdom",
            kind = "accept",
            priority = 200,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept The Eastern Kingdom from Thrall.",
            dependsOn = { "turnin-4001-what-is-going-on" },
            complete = QuestState(4002, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.318, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-4002-the-eastern-kingdom",
            kind = "turnin",
            priority = 201,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in The Eastern Kingdom to Thrall.",
            dependsOn = { "accept-4002-the-eastern-kingdom" },
            complete = QuestState(4002, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.318, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-4003-the-royal-rescue",
            kind = "accept",
            priority = 202,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept The Royal Rescue from Thrall.",
            dependsOn = { "turnin-4002-the-eastern-kingdom" },
            complete = QuestState(4003, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.318, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "boss-phalanx",
            kind = "note",
            priority = 203,
            conditions = { level = { min = 52 } },
            text = "Kill Phalanx. Purchase 6 Dark Iron Ale Mugs from Plugger and give them to Private Rocknot. This will enrage him and cause Phalanx to burst through the door. The group should spread out as far as possible to avoid 'Thunderclap'.",
            dependsOn = { "boss-the-enemies-that-attack-in-waves" },
        },
        {
            id = "boss-ambassador-flamelash",
            kind = "note",
            priority = 204,
            conditions = { level = { min = 52 } },
            text = "Kill Ambassador Flamelash. During the encounter, adds will spawn. They will need to be killed before reaching Flamelash.",
            dependsOn = { "boss-phalanx" },
        },
        {
            id = "boss-panzor-the-invincible",
            kind = "note",
            priority = 205,
            conditions = { level = { min = 52 } },
            text = "Kill Panzor the Invincible if the rare is up. This is a rare mob that may not be available. Casters need to watch out for its 'Spell Reflection' ability.",
            dependsOn = { "boss-ambassador-flamelash" },
        },
        {
            id = "boss-magmus",
            kind = "note",
            priority = 206,
            conditions = { level = { min = 52 } },
            text = "Kill Magmus. To open the door, kill Shadowforge Flame Keepers and collect two Shadowforge Torches. Use them to light the braziers that open the door to Magmus. For this encounter, the tank will need to position Magmus properly.",
            dependsOn = { "boss-panzor-the-invincible" },
        },
        {
            id = "objective-4003-1-emperor-dagran-thaurissa",
            kind = "objective",
            priority = 207,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Slay Emperor Dagran Thaurissan.",
            dependsOn = { "accept-4003-the-royal-rescue" },
            complete = QuestState(4003, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4003-the-royal-rescue",
            kind = "turnin",
            priority = 208,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in The Royal Rescue to Princess Moira Bronzebeard.",
            dependsOn = { "objective-4003-1-emperor-dagran-thaurissa" },
            complete = QuestState(4003, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4004-the-princess-saved",
            kind = "accept",
            priority = 209,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept The Princess Saved? from Princess Moira Bronzebeard.",
            dependsOn = { "turnin-4003-the-royal-rescue" },
            complete = QuestState(4004, "activeOrCompleted"),
        },
        {
            id = "turnin-4004-the-princess-saved",
            kind = "turnin",
            priority = 210,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in The Princess Saved? to Thrall.",
            dependsOn = { "accept-4004-the-princess-saved" },
            complete = QuestState(4004, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.318, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
    },
})
