local _, ns = ...

local MAP = {
    FERALAS = 1444,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-dire-maul-north",
    title = "Dire Maul North",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 56 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-7482-elven-legends",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 54 } } } },
            text = "Accept Elven Legends from Scholar Runethorn.",
            complete = QuestState(7482, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.311, 0.441, "Scholar Runethorn", "Travel to Feralas."),
            },
        },
        {
            id = "boss-pusillin",
            kind = "note",
            priority = 11,
            conditions = { level = { min = 56 } },
            text = "Kill Pusillin. He is the first boss in the Dire Maul East dungeon. Use the Dire Maul East dungeon guide to accomplish this. This item is required to enter Dire Maul West.",
        },
        {
            id = "note-click-door",
            kind = "note",
            priority = 12,
            conditions = { level = { min = 56 } },
            text = "Click Door.",
            route = {
                Point(MAP.FERALAS, 0.625, 0.249, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 13,
            conditions = { level = { min = 56 } },
            text = "Enter Dire Maul - North with your group.",
            dependsOn = { "accept-7482-elven-legends" },
            persistCompletion = true,
            complete = { instance = 429 },
        },
        {
            id = "boss-guard-mol-dar",
            kind = "note",
            priority = 14,
            conditions = { level = { min = 56 } },
            text = "Kill Guard Mol'dar. Ranged should keep at a distance to avoid his 'Knock Away' and 'Shield Charge' abilities.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "boss-stomper-kreeg",
            kind = "note",
            priority = 15,
            conditions = { level = { min = 56 } },
            text = "Kill Stomper Kreeg. His main ability is 'Booze Spit' which will reduce the groups accuracy by 75%.",
            dependsOn = { "boss-guard-mol-dar" },
        },
        {
            id = "boss-guard-fengus",
            kind = "note",
            priority = 16,
            conditions = { level = { min = 56 } },
            text = "Kill Guard Fengus. Like Mol'dar, ranged should keep a distance to avoid being hit by 'Knock Away' and 'Shield Charge'.",
            dependsOn = { "boss-stomper-kreeg" },
        },
        {
            id = "boss-guard-slip-kik",
            kind = "note",
            priority = 17,
            conditions = { level = { min = 56 } },
            text = "Kill Guard Slip'kik. Like Mol'dar, ranged should keep a distance to avoid being hit by 'Knock Away' and 'Shield Charge'.",
            dependsOn = { "boss-guard-fengus" },
        },
        {
            id = "boss-captain-kromcrush",
            kind = "note",
            priority = 18,
            conditions = { level = { min = 56 } },
            text = "Kill Captain Kromcrush. He hits hard so the fight will be healing intensive. He uses the ability 'Intimidating Shout' which will fear your group, so clear the room. At 50% Health he summons 2 Gordok Reavers, which should be CC'd.",
            dependsOn = { "boss-guard-slip-kik" },
        },
        {
            id = "boss-cho-rush-the-observer",
            kind = "note",
            priority = 19,
            conditions = { level = { min = 56 } },
            text = "Kill Cho'Rush the Observer. DPS should focus on killing Cho'Rush first. Keep an eye out for King Gordok's 'Heal' ability and interrupt it when possible.",
            dependsOn = { "boss-captain-kromcrush" },
        },
        {
            id = "boss-king-gordok",
            kind = "note",
            priority = 20,
            conditions = { level = { min = 56 } },
            text = "Kill King Gordok. DPS should focus on killing Cho'Rush first. Keep an eye out for King Gordok's 'Heal' ability and interrupt it when possible.",
            dependsOn = { "boss-cho-rush-the-observer" },
        },
        {
            id = "note-click-conservatory-door",
            kind = "note",
            priority = 21,
            conditions = { level = { min = 56 } },
            text = "Click Conservatory Door.",
        },
        {
            id = "note-click-skeletal-remains-of-kariel-winthalus",
            kind = "note",
            priority = 22,
            conditions = { level = { min = 56 } },
            text = "Click Skeletal Remains of Kariel Winthalus.",
        },
        {
            id = "objective-7482-1-the-skeletal-remains-of",
            kind = "objective",
            priority = 23,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 54 } } } },
            text = "Find the Skeletal Remains of Master Kariel Winthalus.",
            dependsOn = { "accept-7482-elven-legends" },
            complete = QuestState(7482, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-fengus-s-chest",
            kind = "note",
            priority = 24,
            conditions = { level = { min = 56 } },
            text = "Click Fengus's Chest.",
        },
        {
            id = "note-click-gordok-courtyard-door",
            kind = "note",
            priority = 25,
            conditions = { level = { min = 56 } },
            text = "Click Gordok Courtyard Door.",
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 26,
            conditions = { level = { min = 56 } },
            text = "Click Here to Continue.",
        },
        {
            id = "accept-5518-the-gordok-ogre-suit",
            kind = "accept",
            priority = 27,
            conditions = { level = { min = 56 } },
            text = "Accept The Gordok Ogre Suit from Knot Thimblejack.",
            complete = QuestState(5518, "activeOrCompleted"),
        },
        {
            id = "note-click-ogre-tannin-basket",
            kind = "note",
            priority = 28,
            conditions = { level = { min = 56 } },
            text = "Click Ogre Tannin Basket.",
        },
        {
            id = "objective-5518-4-ogre-tannin",
            kind = "objective",
            priority = 29,
            conditions = { level = { min = 56 } },
            text = "Collect Ogre Tannin.",
            dependsOn = { "accept-5518-the-gordok-ogre-suit" },
            complete = QuestState(5518, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5518-the-gordok-ogre-suit",
            kind = "turnin",
            priority = 30,
            conditions = { level = { min = 56 } },
            text = "Turn in The Gordok Ogre Suit to Knot Thimblejack.",
            dependsOn = { "objective-5518-4-ogre-tannin" },
            complete = QuestState(5518, "completed"),
            useClientPin = true,
        },
        {
            id = "boss-guard-enemies-around-this-area",
            kind = "note",
            priority = 31,
            conditions = { level = { min = 56 } },
            text = "Kill Guard enemies around this area. Guard Mol'dar, Slip'kik, Fengus and Captain Kromcrush can drop the key. The guards can be found in the Halls of Destruction and in each of the large open rooms at the beginning of the dungeon. Captain Kromcrush is found in Gordok's Seat, which is reached by going through the upper level of the Halls of Destruction.",
            dependsOn = { "boss-king-gordok" },
        },
        {
            id = "turnin-7429-free-knot",
            kind = "turnin",
            priority = 32,
            conditions = { level = { min = 56 } },
            text = "Turn in Free Knot! to Knot Thimblejack.",
            complete = QuestState(7429, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-5528-the-gordok-taste-test",
            kind = "accept",
            priority = 33,
            conditions = { level = { min = 56 } },
            text = "Accept The Gordok Taste Test from Stomper Kreeg.",
            complete = QuestState(5528, "activeOrCompleted"),
        },
        {
            id = "accept-7703-unfinished-gordok-business",
            kind = "accept",
            priority = 34,
            conditions = { level = { min = 56 } },
            text = "Accept Unfinished Gordok Business from Captain Kromcrush.",
            complete = QuestState(7703, "activeOrCompleted"),
        },
        {
            id = "note-click-the-prince-s-chest",
            kind = "note",
            priority = 35,
            conditions = { level = { min = 56 } },
            text = "Click The Prince's Chest.",
        },
        {
            id = "objective-7703-1-gauntlet-of-gordok-might",
            kind = "objective",
            priority = 36,
            conditions = { level = { min = 56 } },
            text = "Collect Gauntlet of Gordok Might.",
            dependsOn = { "accept-7703-unfinished-gordok-business" },
            complete = QuestState(7703, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-7703-unfinished-gordok-business",
            kind = "turnin",
            priority = 37,
            conditions = { level = { min = 56 } },
            text = "Turn in Unfinished Gordok Business to Captain Kromcrush.",
            dependsOn = { "objective-7703-1-gauntlet-of-gordok-might" },
            complete = QuestState(7703, "completed"),
            useClientPin = true,
        },
        {
            id = "note-leave-the-dungeon",
            kind = "note",
            priority = 38,
            conditions = { level = { min = 56 } },
            text = "Leave the dungeon.",
        },
        {
            id = "turnin-7482-elven-legends",
            kind = "turnin",
            priority = 39,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 54 } } } },
            text = "Turn in Elven Legends to Scholar Runethorn.",
            dependsOn = { "objective-7482-1-the-skeletal-remains-of" },
            complete = QuestState(7482, "completed"),
            route = {
                Point(MAP.FERALAS, 0.311, 0.441, "Scholar Runethorn", "Travel to Feralas."),
            },
        },
        {
            id = "accept-7481-elven-legends",
            kind = "accept",
            priority = 40,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Accept Elven Legends from Sage Korolusk.",
            complete = QuestState(7481, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.755, 0.437, "Sage Korolusk", "Travel to Feralas."),
            },
        },
        {
            id = "objective-7481-1-the-skeletal-remains-of",
            kind = "objective",
            priority = 41,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Find the Skeletal Remains of Master Kariel Winthalus.",
            dependsOn = { "accept-7481-elven-legends" },
            complete = QuestState(7481, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-7481-elven-legends",
            kind = "turnin",
            priority = 42,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Turn in Elven Legends to Sage Korolusk.",
            dependsOn = { "objective-7481-1-the-skeletal-remains-of" },
            complete = QuestState(7481, "completed"),
            route = {
                Point(MAP.FERALAS, 0.755, 0.437, "Sage Korolusk", "Travel to Feralas."),
            },
        },
    },
})
