local _, ns = ...

local MAP = {
    DARNASSUS = 1457,
    STORMWIND_CITY = 1453,
    IRONFORGE = 1455,
    DUN_MOROGH = 1426,
    STRANGLETHORN_VALE = 1434,
    ORGRIMMAR = 1454,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-gnomeregan-raid",
    title = "Gnomeregan Raid",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 40 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-80135-klockmort-s-essentials",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Klockmort's Essentials from Mathiel.",
            complete = QuestState(80135, "activeOrCompleted"),
            route = {
                Point(MAP.DARNASSUS, 0.595, 0.454, "Mathiel", "Travel to Darnassus."),
            },
        },
        {
            id = "accept-80138-tinkmaster-overspark",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Tinkmaster Overspark from Brother Sarno.",
            complete = QuestState(80138, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.406, 0.310, "Brother Sarno", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-80181-gyrodrillmatic-excavationators",
            kind = "accept",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Gyrodrillmatic Excavationators from Shoni the Shilent.",
            complete = QuestState(80181, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.555, 0.125, "Shoni the Shilent", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-80135-klockmort-s-essentials",
            kind = "turnin",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Klockmort's Essentials to Klockmort Spannerspan.",
            dependsOn = { "accept-80135-klockmort-s-essentials" },
            complete = QuestState(80135, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.679, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-80136-essential-artificials",
            kind = "accept",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Essential Artificials from Klockmort Spannerspan.",
            dependsOn = { "turnin-80135-klockmort-s-essentials" },
            complete = QuestState(80136, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.679, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-80138-tinkmaster-overspark",
            kind = "turnin",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Tinkmaster Overspark to Tinkmaster Overspark.",
            dependsOn = { "accept-80138-tinkmaster-overspark" },
            complete = QuestState(80138, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.695, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-80137-save-techbot-s-brain",
            kind = "accept",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Save Techbot's Brain! from Tinkmaster Overspark.",
            dependsOn = { "turnin-80138-tinkmaster-overspark" },
            complete = QuestState(80137, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.695, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-80180-the-grand-betrayal",
            kind = "accept",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept The Grand Betrayal from High Tinker Mekkatorque.",
            complete = QuestState(80180, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.687, 0.490, "High Tinker Mekkatorque", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-80139-gnogaine",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Gnogaine from Ozzie Togglevolt.",
            complete = QuestState(80139, "activeOrCompleted"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "boss-iradiated-enemies-outside-the-gnomeregan-i",
            kind = "note",
            priority = 19,
            conditions = { level = { min = 40 } },
            text = "Kill Iradiated enemies outside the Gnomeregan Instance. They will be glowing bright green. You can use it on glowing green corpses or when their hands glow green and are casting on you.",
        },
        {
            id = "objective-80139-1-full-leaden-collection-p",
            kind = "objective",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Collect Full Leaden Collection Phial.",
            dependsOn = { "accept-80139-gnogaine" },
            complete = QuestState(80139, "complete"),
            route = {
                Point(MAP.DUN_MOROGH, 0.217, 0.343, "Dun Morogh", "Travel to Dun Morogh."),
            },
        },
        {
            id = "boss-techbot",
            kind = "note",
            priority = 21,
            conditions = { level = { min = 40 } },
            text = "Kill Techbot. In the area just before Gnomeregan. Instead of turning left, head straight to a circular platform. It has a potentially long respawn timer.",
            dependsOn = { "boss-iradiated-enemies-outside-the-gnomeregan-i" },
        },
        {
            id = "objective-80137-1-techbot-s-memory-core",
            kind = "objective",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Collect Techbot's Memory Core.",
            dependsOn = { "accept-80137-save-techbot-s-brain" },
            complete = QuestState(80137, "complete"),
            route = {
                Point(MAP.DUN_MOROGH, 0.218, 0.321, "Dun Morogh", "Travel to Dun Morogh."),
            },
        },
        {
            id = "turnin-80139-gnogaine",
            kind = "turnin",
            priority = 23,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Gnogaine to Ozzie Togglevolt.",
            dependsOn = { "objective-80139-1-full-leaden-collection-p" },
            complete = QuestState(80139, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "turnin-80137-save-techbot-s-brain",
            kind = "turnin",
            priority = 24,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Save Techbot's Brain! to Tinkmaster Overspark.",
            dependsOn = { "objective-80137-1-techbot-s-memory-core" },
            complete = QuestState(80137, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.695, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 25,
            conditions = { level = { min = 40 } },
            text = "Enter Gnomeregan with your group.",
            dependsOn = { "accept-80135-klockmort-s-essentials", "accept-80138-tinkmaster-overspark", "accept-80181-gyrodrillmatic-excavationators", "accept-80136-essential-artificials", "accept-80137-save-techbot-s-brain", "accept-80180-the-grand-betrayal", "accept-80139-gnogaine" },
            persistCompletion = true,
            complete = { instance = 90 },
        },
        {
            id = "note-click-artificial-extrapolator",
            kind = "note",
            priority = 26,
            conditions = { level = { min = 40 } },
            text = "Click Artificial Extrapolator+.",
        },
        {
            id = "objective-80136-1-essential-artificial",
            kind = "objective",
            priority = 27,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Collect 12 Essential Artificial.",
            dependsOn = { "accept-80136-essential-artificials" },
            complete = QuestState(80136, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-dark-iron-enemies-around-this-area",
            kind = "note",
            priority = 28,
            conditions = { level = { min = 40 } },
            text = "Kill Dark Iron Enemies around this area. They look like dwarves.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "accept-79986-grime-encrusted-ring",
            kind = "accept",
            priority = 29,
            conditions = { level = { min = 40 } },
            text = "Accept Grime-Encrusted Ring.",
            complete = QuestState(79986, "activeOrCompleted"),
        },
        {
            id = "note-click-the-sparklematic-5200",
            kind = "note",
            priority = 30,
            conditions = { level = { min = 40 } },
            text = "Click The Sparklematic 5200.",
        },
        {
            id = "turnin-79986-grime-encrusted-ring",
            kind = "turnin",
            priority = 31,
            conditions = { level = { min = 40 } },
            text = "Turn in Grime-Encrusted Ring.",
            dependsOn = { "accept-79986-grime-encrusted-ring" },
            complete = QuestState(79986, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-80153-the-sparklematic-5200",
            kind = "accept",
            priority = 32,
            conditions = { level = { min = 40 } },
            text = "Accept The Sparklematic 5200!.",
            complete = QuestState(80153, "activeOrCompleted"),
        },
        {
            id = "accept-80158-the-sparklematic-5200",
            kind = "accept",
            priority = 33,
            conditions = { level = { min = 40 } },
            text = "Accept The Sparklematic 5200!.",
            complete = QuestState(80158, "activeOrCompleted"),
        },
        {
            id = "accept-80157-the-sparklematic-5200",
            kind = "accept",
            priority = 34,
            conditions = { level = { min = 40 } },
            text = "Accept The Sparklematic 5200!.",
            complete = QuestState(80157, "activeOrCompleted"),
        },
        {
            id = "boss-stx-96-fr",
            kind = "note",
            priority = 35,
            conditions = { level = { min = 40 } },
            text = "Kill STX-96/FR. Jumps out after STX-96/FR is defeated and needs to be killed. Furnace Surge channels for 3 seconds causing 'Sprocketfire'. |grouprole TANK. This stacks on the main tank. |grouprole TANK.",
            dependsOn = { "boss-dark-iron-enemies-around-this-area" },
        },
        {
            id = "objective-80180-1-mekgineer-thermaplugg",
            kind = "objective",
            priority = 36,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Kill Mekgineer Thermaplugg.",
            dependsOn = { "accept-80180-the-grand-betrayal" },
            complete = QuestState(80180, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-80324-the-mad-king",
            kind = "accept",
            priority = 37,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept The Mad King.",
            complete = QuestState(80324, "activeOrCompleted"),
        },
        {
            id = "accept-79985-a-fine-mess",
            kind = "accept",
            priority = 38,
            conditions = { level = { min = 40 } },
            text = "Accept A Fine Mess from Kernobee.",
            complete = QuestState(79985, "activeOrCompleted"),
        },
        {
            id = "objective-79985-1-escort-kernobee-out-of-g",
            kind = "objective",
            priority = 39,
            conditions = { level = { min = 40 } },
            text = "Escort Kernobee out of Gnomeregan.",
            dependsOn = { "accept-79985-a-fine-mess" },
            complete = QuestState(79985, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-80136-essential-artificials",
            kind = "turnin",
            priority = 40,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Essential Artificials to Klockmort Spannerspan.",
            dependsOn = { "objective-80136-1-essential-artificial" },
            complete = QuestState(80136, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.679, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-80180-the-grand-betrayal",
            kind = "turnin",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in The Grand Betrayal to High Tinker Mekkatorque.",
            dependsOn = { "objective-80180-1-mekgineer-thermaplugg" },
            complete = QuestState(80180, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.687, 0.490, "High Tinker Mekkatorque", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-80324-the-mad-king",
            kind = "turnin",
            priority = 42,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in The Mad King to High Tinker Mekkatorque.",
            dependsOn = { "accept-80324-the-mad-king" },
            complete = QuestState(80324, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.687, 0.490, "High Tinker Mekkatorque", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-80181-gyrodrillmatic-excavationators",
            kind = "turnin",
            priority = 43,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Gyrodrillmatic Excavationators to Shoni the Shilent.",
            dependsOn = { "accept-80181-gyrodrillmatic-excavationators" },
            complete = QuestState(80181, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.555, 0.125, "Shoni the Shilent", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-79985-a-fine-mess",
            kind = "turnin",
            priority = 44,
            conditions = { level = { min = 40 } },
            text = "Turn in A Fine Mess to Scooty.",
            dependsOn = { "objective-79985-1-escort-kernobee-out-of-g" },
            complete = QuestState(79985, "completed"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "accept-80132-rig-wars",
            kind = "accept",
            priority = 45,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Accept Rig Wars from Nogg.",
            complete = QuestState(80132, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.760, 0.254, "Nogg", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-80133-chief-engineer-scooty",
            kind = "accept",
            priority = 46,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Accept Chief Engineer Scooty from Sovik.",
            complete = QuestState(80133, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.755, 0.254, "Sovik", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-80133-chief-engineer-scooty",
            kind = "turnin",
            priority = 47,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Turn in Chief Engineer Scooty to Scooty.",
            dependsOn = { "accept-80133-chief-engineer-scooty" },
            complete = QuestState(80133, "completed"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "accept-80134-gnomer-gooooone",
            kind = "accept",
            priority = 48,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Accept Gnomer-gooooone! from Scooty.",
            dependsOn = { "turnin-80133-chief-engineer-scooty" },
            complete = QuestState(80134, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "objective-80134-1-wait-for-scooty-to-calib",
            kind = "objective",
            priority = 49,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Wait for Scooty to Calibrate the Goblin Transponder.",
            dependsOn = { "accept-80134-gnomer-gooooone" },
            complete = QuestState(80134, "complete"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Stranglethorn Vale", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "turnin-80134-gnomer-gooooone",
            kind = "turnin",
            priority = 50,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Turn in Gnomer-gooooone! to Scooty.",
            dependsOn = { "objective-80134-1-wait-for-scooty-to-calib" },
            complete = QuestState(80134, "completed"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "boss-grubbis",
            kind = "note",
            priority = 51,
            conditions = { level = { min = 40 } },
            text = "Kill Grubbis. Stay out of the green gas clouds spawned by Grubbis. |grouprole EVERYONE. More gas clouds spawn the longer the battle goes on. |grouprole EVERYONE. Utilize Nature Protection Potions near the start of the fight and at 30% if available. |grouprole EVERYONE.",
            dependsOn = { "boss-stx-96-fr" },
        },
        {
            id = "boss-viscous-fallout",
            kind = "note",
            priority = 52,
            conditions = { level = { min = 40 } },
            text = "Kill Viscous Fallout. Avoid poison puddles left on the ground by the boss. |grouprole EVERYONE. Coordinate cooldowns with raid in safe spots |grouprole EVERYONE. Save damage mitigation skills for poison attacks. |grouprole TANK.",
            dependsOn = { "boss-grubbis" },
        },
        {
            id = "boss-electrocutioner-6000",
            kind = "note",
            priority = 53,
            conditions = { level = { min = 40 } },
            text = "Kill Electrocutioner 6000. 'Static Arc' targets the player furthest away from it. |grouprole EVERYONE. Afflicted player will take 500% extra damage and the affect will bounce to the two closest players to the target. |grouprole EVERYONE. Have 2 teams of 3 althernating positions for this. |grouprole EVERYONE.",
            dependsOn = { "boss-viscous-fallout" },
        },
        {
            id = "boss-crowd-pummeler-9-60",
            kind = "note",
            priority = 54,
            conditions = { level = { min = 40 } },
            text = "Kill Crowd Pummeler 9-60. For this encounter, place the groups back against the wall to avoid being knocked off the ledge. |grouprole EVERYONE. Soak damage from 'Crowd Pummel' and 'Arcing Smash' to mitigate group damage. |grouprole TANK. Don't stand in front of the boss to avoid damage from 'Arcing Smash'. |grouprole DAMAGE.",
            dependsOn = { "boss-electrocutioner-6000" },
        },
        {
            id = "boss-dark-iron-ambassador",
            kind = "note",
            priority = 55,
            conditions = { level = { min = 40 } },
            text = "Kill Dark Iron Ambassador. Resist the wave of Fireball and Knock Away, staying steady despite all odds. |grouprole TANK. Avoid dealing damage while 'Fire Shield II' is active. |grouprole DAMAGE. Heal through 'Fireball's' damage. |grouprole HEALER.",
            dependsOn = { "boss-crowd-pummeler-9-60" },
        },
        {
            id = "boss-mekgineer-thermaplugg",
            kind = "note",
            priority = 56,
            conditions = { level = { min = 40 } },
            text = "Kill Mekgineer Thermaplugg. Jumps out after STX-96/FR is defeated and needs to be killed. Furnace Surge channels for 3 seconds causing 'Sprocketfire'. |grouprole TANK. This stacks on the main tank. |grouprole TANK.",
            dependsOn = { "boss-dark-iron-ambassador" },
        },
        {
            id = "objective-80132-2-thermaplugg-s-safe-combi",
            kind = "objective",
            priority = 57,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Collect Thermaplugg's Safe Combination.",
            dependsOn = { "accept-80132-rig-wars" },
            complete = QuestObjective(80132, 2, "Thermaplugg's Safe Combination"),
            useClientPin = true,
        },
        {
            id = "accept-80325-the-mad-king",
            kind = "accept",
            priority = 58,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Accept The Mad King.",
            complete = QuestState(80325, "activeOrCompleted"),
        },
        {
            id = "note-click-thermaplugg-s-safe",
            kind = "note",
            priority = 59,
            conditions = { level = { min = 40 } },
            text = "Click Thermaplugg's Safe.",
        },
        {
            id = "objective-80132-1-rig-blueprints",
            kind = "objective",
            priority = 60,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Collect Rig Blueprints.",
            dependsOn = { "accept-80132-rig-wars" },
            complete = QuestObjective(80132, 1, "Rig Blueprints"),
            useClientPin = true,
        },
        {
            id = "turnin-80132-rig-wars",
            kind = "turnin",
            priority = 61,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Turn in Rig Wars to Nogg.",
            dependsOn = { "objective-80132-2-thermaplugg-s-safe-combi", "objective-80132-1-rig-blueprints" },
            complete = QuestState(80132, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.760, 0.254, "Nogg", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-80325-the-mad-king",
            kind = "turnin",
            priority = 62,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Turn in The Mad King to Nogg.",
            dependsOn = { "accept-80325-the-mad-king" },
            complete = QuestState(80325, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.760, 0.254, "Nogg", "Travel to Orgrimmar."),
            },
        },
    },
})
