local _, ns = ...

local MAP = {
    STORMWIND_CITY = 1453,
    DARNASSUS = 1457,
    IRONFORGE = 1455,
    DUN_MOROGH = 1426,
    ORGRIMMAR = 1454,
    STRANGLETHORN_VALE = 1434,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-gnomeregan",
    title = "Gnomeregan",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 25 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-2923-tinkmaster-overspark",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Accept Tinkmaster Overspark from Brother Sarno.",
            complete = QuestState(2923, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.406, 0.309, "Brother Sarno", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-2928-gyrodrillmatic-excavationators",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Accept Gyrodrillmatic Excavationators from Shoni the Shilent.",
            complete = QuestState(2928, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.555, 0.125, "Shoni the Shilent", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-2925-klockmort-s-essentials",
            kind = "accept",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 24 } } } },
            text = "Accept Klockmort's Essentials from Mathiel.",
            complete = QuestState(2925, "activeOrCompleted"),
            route = {
                Point(MAP.DARNASSUS, 0.595, 0.454, "Mathiel", "Travel to Darnassus."),
            },
        },
        {
            id = "turnin-2925-klockmort-s-essentials",
            kind = "turnin",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 24 } } } },
            text = "Turn in Klockmort's Essentials to Klockmort Spannerspan.",
            dependsOn = { "accept-2925-klockmort-s-essentials" },
            complete = QuestState(2925, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.680, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2924-essential-artificials",
            kind = "accept",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 24 } } } },
            text = "Accept Essential Artificials from Klockmort Spannerspan.",
            dependsOn = { "turnin-2925-klockmort-s-essentials" },
            complete = QuestState(2924, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.680, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2923-tinkmaster-overspark",
            kind = "turnin",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Turn in Tinkmaster Overspark to Tinkmaster Overspark.",
            dependsOn = { "accept-2923-tinkmaster-overspark" },
            complete = QuestState(2923, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.696, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2922-save-techbot-s-brain",
            kind = "accept",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Accept Save Techbot's Brain! from Tinkmaster Overspark.",
            dependsOn = { "turnin-2923-tinkmaster-overspark" },
            complete = QuestState(2922, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.696, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2927-the-day-after",
            kind = "accept",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Accept The Day After from Gnoarn.",
            complete = QuestState(2927, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.692, 0.506, "Gnoarn", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2930-data-rescue",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Accept Data Rescue from Master Mechanic Castpipe.",
            complete = QuestState(2930, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.698, 0.481, "Master Mechanic Castpipe", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2929-the-grand-betrayal",
            kind = "accept",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Accept The Grand Betrayal from High Tinker Mekkatorque.",
            complete = QuestState(2929, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.688, 0.490, "High Tinker Mekkatorque", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2927-the-day-after",
            kind = "turnin",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Turn in The Day After to Ozzie Togglevolt.",
            dependsOn = { "accept-2927-the-day-after" },
            complete = QuestState(2927, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "accept-2926-gnogaine",
            kind = "accept",
            priority = 21,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Accept Gnogaine from Ozzie Togglevolt.",
            dependsOn = { "turnin-2927-the-day-after" },
            complete = QuestState(2926, "activeOrCompleted"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 22,
            conditions = { level = { min = 25 } },
            text = "Enter Gnomeregan with your group.",
            dependsOn = { "accept-2923-tinkmaster-overspark", "accept-2928-gyrodrillmatic-excavationators", "accept-2925-klockmort-s-essentials", "accept-2924-essential-artificials", "accept-2922-save-techbot-s-brain", "accept-2927-the-day-after", "accept-2930-data-rescue", "accept-2929-the-grand-betrayal", "accept-2926-gnogaine" },
            persistCompletion = true,
            complete = { instance = 90 },
        },
        {
            id = "boss-addled-enemies-around-this-area",
            kind = "note",
            priority = 23,
            conditions = { level = { min = 25 } },
            text = "Kill Addled enemies around this area.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "boss-techbot",
            kind = "note",
            priority = 24,
            conditions = { level = { min = 25 } },
            text = "Kill Techbot. You may need help with this.",
            dependsOn = { "boss-addled-enemies-around-this-area" },
        },
        {
            id = "objective-2922-1-techbot-s-memory-core",
            kind = "objective",
            priority = 25,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Collect Techbot's Memory Core.",
            dependsOn = { "accept-2922-save-techbot-s-brain" },
            complete = QuestState(2922, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-matrix-punchograph-3005-a",
            kind = "note",
            priority = 26,
            conditions = { level = { min = 25 } },
            text = "Click Matrix Punchograph 3005-A.",
        },
        {
            id = "objective-2926-1-full-leaden-collection-p",
            kind = "objective",
            priority = 27,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Collect Full Leaden Collection Phial.",
            dependsOn = { "accept-2926-gnogaine" },
            complete = QuestState(2926, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-2926-gnogaine",
            kind = "turnin",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Turn in Gnogaine to Ozzie Togglevolt.",
            dependsOn = { "objective-2926-1-full-leaden-collection-p" },
            complete = QuestState(2926, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "accept-2962-the-only-cure-is-more-green-glow",
            kind = "accept",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Accept The Only Cure is More Green Glow from Ozzie Togglevolt.",
            dependsOn = { "turnin-2926-gnogaine" },
            complete = QuestState(2962, "activeOrCompleted"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "note-click-matrix-punchograph-3005-b",
            kind = "note",
            priority = 30,
            conditions = { level = { min = 25 } },
            text = "Click Matrix Punchograph 3005-B.",
        },
        {
            id = "boss-grubbis",
            kind = "note",
            priority = 31,
            conditions = { level = { min = 25 } },
            text = "Kill Grubbis. This boss spawns from an event started by 'Blastmaster Emi Shortfuse'. She will trigger an explosive tha twill cause mobs to spawn from a cave. Grubbis will eventually spawn.",
            dependsOn = { "boss-techbot" },
        },
        {
            id = "boss-viscous-fallout",
            kind = "note",
            priority = 32,
            conditions = { level = { min = 25 } },
            text = "Kill Viscous Fallout. It is the first boss of the dungeon. It is in the lower level of the Hall of Gears. Leave The Dormitory and reenter The Hall of Gears and then jump down to the lower level. Before engaging in this encounter, it is recommended that you clear the trash in the room. After that, the fight itself is simple.",
            dependsOn = { "boss-grubbis" },
        },
        {
            id = "objective-2962-1-high-potency-radioactive",
            kind = "objective",
            priority = 33,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Collect High Potency Radioactive Fallout.",
            dependsOn = { "accept-2962-the-only-cure-is-more-green-glow" },
            complete = QuestState(2962, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-electrocutioner-6000",
            kind = "note",
            priority = 34,
            conditions = { level = { min = 25 } },
            text = "Kill Electrocutioner 6000. He is the third boss of the dungeon. He is in the center of the upper level of the Launch Bay. Follow the west path from The Hall of Gears to enter the Launch Bay. This encounter is standard. DPS the boss down and move on.",
            dependsOn = { "boss-viscous-fallout" },
        },
        {
            id = "note-click-matrix-punchograph-3005-c",
            kind = "note",
            priority = 35,
            conditions = { level = { min = 25 } },
            text = "Click Matrix Punchograph 3005-C.",
        },
        {
            id = "note-click-miatrix-punchograph-3005-d",
            kind = "note",
            priority = 36,
            conditions = { level = { min = 25 } },
            text = "Click Miatrix Punchograph 3005-D.",
        },
        {
            id = "objective-2930-1-prismatic-punch-card",
            kind = "objective",
            priority = 37,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Collect Prismatic Punch Card.",
            dependsOn = { "accept-2930-data-rescue" },
            complete = QuestState(2930, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-enemies-around-this-area",
            kind = "note",
            priority = 38,
            conditions = { level = { min = 25 } },
            text = "Kill enemies around this area.",
            dependsOn = { "boss-electrocutioner-6000" },
        },
        {
            id = "objective-2928-1-robo-mechanical-guts",
            kind = "objective",
            priority = 39,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Collect 24 Robo-mechanical Guts.",
            dependsOn = { "accept-2928-gyrodrillmatic-excavationators" },
            complete = QuestState(2928, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-artificial-extrapolator",
            kind = "note",
            priority = 40,
            conditions = { level = { min = 25 } },
            text = "Click Artificial Extrapolator+.",
        },
        {
            id = "objective-2924-1-essential-artificial",
            kind = "objective",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 24 } } } },
            text = "Collect 12 Essential Artificial.",
            dependsOn = { "accept-2924-essential-artificials" },
            complete = QuestState(2924, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2929-1-mekgineer-thermaplugg",
            kind = "objective",
            priority = 42,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Kill Mekgineer Thermaplugg.",
            dependsOn = { "accept-2929-the-grand-betrayal" },
            complete = QuestState(2929, "complete"),
            useClientPin = true,
        },
        {
            id = "note-leave-the-dungeon",
            kind = "note",
            priority = 43,
            conditions = { level = { min = 25 } },
            text = "Leave the dungeon.",
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 44,
            conditions = { level = { min = 25 } },
            text = "Click Here to Continue.",
        },
        {
            id = "turnin-2924-essential-artificials",
            kind = "turnin",
            priority = 45,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 24 } } } },
            text = "Turn in Essential Artificials to Klockmort Spannerspan.",
            dependsOn = { "objective-2924-1-essential-artificial" },
            complete = QuestState(2924, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.680, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2922-save-techbot-s-brain",
            kind = "turnin",
            priority = 46,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Turn in Save Techbot's Brain! to Tinkmaster Overspark.",
            dependsOn = { "objective-2922-1-techbot-s-memory-core" },
            complete = QuestState(2922, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.696, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2930-data-rescue",
            kind = "turnin",
            priority = 47,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Turn in Data Rescue to Master Mechanic Castpipe.",
            dependsOn = { "objective-2930-1-prismatic-punch-card" },
            complete = QuestState(2930, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.698, 0.481, "Master Mechanic Castpipe", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2929-the-grand-betrayal",
            kind = "turnin",
            priority = 48,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 25 } } } },
            text = "Turn in The Grand Betrayal to High Tinker Mekkatorque.",
            dependsOn = { "objective-2929-1-mekgineer-thermaplugg" },
            complete = QuestState(2929, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.688, 0.490, "High Tinker Mekkatorque", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2962-the-only-cure-is-more-green-glow",
            kind = "turnin",
            priority = 49,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Turn in The Only Cure is More Green Glow to Ozzie Togglevolt.",
            dependsOn = { "objective-2962-1-high-potency-radioactive" },
            complete = QuestState(2962, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "turnin-2928-gyrodrillmatic-excavationators",
            kind = "turnin",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Turn in Gyrodrillmatic Excavationators to Shoni the Shilent.",
            dependsOn = { "objective-2928-1-robo-mechanical-guts" },
            complete = QuestState(2928, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.555, 0.125, "Shoni the Shilent", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-2841-rig-wars",
            kind = "accept",
            priority = 51,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Accept Rig Wars from Nogg.",
            complete = QuestState(2841, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.760, 0.254, "Nogg", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-2842-chief-engineer-scooty",
            kind = "accept",
            priority = 52,
            conditions = { all = { { faction = "Horde" }, { level = { min = 20 } } } },
            text = "Accept Chief Engineer Scooty from Sovik.",
            complete = QuestState(2842, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.755, 0.254, "Sovik", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-2842-chief-engineer-scooty",
            kind = "turnin",
            priority = 53,
            conditions = { all = { { faction = "Horde" }, { level = { min = 20 } } } },
            text = "Turn in Chief Engineer Scooty to Scooty.",
            dependsOn = { "accept-2842-chief-engineer-scooty" },
            complete = QuestState(2842, "completed"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "accept-2843-gnomer-gooooone",
            kind = "accept",
            priority = 54,
            conditions = { all = { { faction = "Horde" }, { level = { min = 20 } } } },
            text = "Accept Gnomer-gooooone! from Scooty.",
            dependsOn = { "turnin-2842-chief-engineer-scooty" },
            complete = QuestState(2843, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "objective-2843-1-wait-for-scooty-to-calib",
            kind = "objective",
            priority = 55,
            conditions = { all = { { faction = "Horde" }, { level = { min = 20 } } } },
            text = "Wait for Scooty to Calibrate the Goblin Transponder.",
            dependsOn = { "accept-2843-gnomer-gooooone" },
            complete = QuestState(2843, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-2843-gnomer-gooooone",
            kind = "turnin",
            priority = 56,
            conditions = { all = { { faction = "Horde" }, { level = { min = 20 } } } },
            text = "Turn in Gnomer-gooooone! to Scooty.",
            dependsOn = { "objective-2843-1-wait-for-scooty-to-calib" },
            complete = QuestState(2843, "completed"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "boss-crowd-pummeler-9-60",
            kind = "note",
            priority = 57,
            conditions = { level = { min = 25 } },
            text = "Kill Crowd Pummeler 9-60. For this encounter, place the groups back against the wall to avoid being knocked off the ledge.",
            dependsOn = { "boss-enemies-around-this-area" },
        },
        {
            id = "boss-dark-iron-ambassador",
            kind = "note",
            priority = 58,
            conditions = { level = { min = 25 } },
            text = "Kill Dark Iron Ambassador if the rare is up. This is a rare mob that may not be available. Click the line below to continue.",
            dependsOn = { "boss-crowd-pummeler-9-60" },
        },
        {
            id = "boss-mekgineer-thermaplugg",
            kind = "note",
            priority = 59,
            conditions = { level = { min = 25 } },
            text = "Kill Mekgineer Thermaplugg. He is the last boss of the dungeon. Follow the path west through The Hall of Gears to enter the Launch Bay. Continue southwest through the Launch Bay and follow the path to reach Tinkers' Court. For this encounter, the DPS in the group should focus down 'Walking Bombs' as they close in on the group. Other than that, kill Thermaplugg in between them.",
            dependsOn = { "boss-dark-iron-ambassador" },
        },
        {
            id = "objective-2841-2-thermaplugg-s-safe-combi",
            kind = "objective",
            priority = 60,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Collect Thermaplugg's Safe Combination.",
            dependsOn = { "accept-2841-rig-wars" },
            complete = QuestObjective(2841, 2, "Thermaplugg's Safe Combination"),
            useClientPin = true,
        },
        {
            id = "note-click-thermaplugg-s-safe",
            kind = "note",
            priority = 61,
            conditions = { level = { min = 25 } },
            text = "Click Thermaplugg's Safe.",
        },
        {
            id = "objective-2841-1-rig-blueprints",
            kind = "objective",
            priority = 62,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Collect Rig Blueprints.",
            dependsOn = { "accept-2841-rig-wars" },
            complete = QuestObjective(2841, 1, "Rig Blueprints"),
            useClientPin = true,
        },
        {
            id = "turnin-2841-rig-wars",
            kind = "turnin",
            priority = 63,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Turn in Rig Wars to Nogg.",
            dependsOn = { "objective-2841-2-thermaplugg-s-safe-combi", "objective-2841-1-rig-blueprints" },
            complete = QuestState(2841, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.760, 0.254, "Nogg", "Travel to Orgrimmar."),
            },
        },
    },
})
