local _, ns = ...

local MAP = {
    STORMWIND_CITY = 1453,
    DARNASSUS = 1457,
    IRONFORGE = 1455,
    DUN_MOROGH = 1426,
    ORGRIMMAR = 1454,
    STRANGLETHORN_VALE = 1434,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-gnomeregan",
    title = "Gnomeregan",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 25 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-2923-tinkmaster-overspark",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Accept Tinkmaster Overspark from Brother Sarno.",
            complete = QuestState(2923, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.406, 0.309, "Brother Sarno", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-2928-gyrodrillmatic-excavationators",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Accept Gyrodrillmatic Excavationators from Shoni the Shilent.",
            complete = QuestState(2928, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.555, 0.125, "Shoni the Shilent", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-2925-klockmort-s-essentials",
            kind = "accept",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 24 } } } },
            text = "Accept Klockmort's Essentials from Mathiel.",
            complete = QuestState(2925, "activeOrCompleted"),
            route = {
                Point(MAP.DARNASSUS, 0.595, 0.454, "Mathiel", "Travel to Darnassus."),
            },
        },
        {
            id = "turnin-2925-klockmort-s-essentials",
            kind = "turnin",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 24 } } } },
            text = "Turn in Klockmort's Essentials to Klockmort Spannerspan.",
            dependsOn = { "accept-2925-klockmort-s-essentials" },
            complete = QuestState(2925, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.680, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2924-essential-artificials",
            kind = "accept",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Accept Essential Artificials from Klockmort Spannerspan.",
            dependsOn = { "turnin-2925-klockmort-s-essentials" },
            complete = QuestState(2924, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.680, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2923-tinkmaster-overspark",
            kind = "turnin",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Turn in Tinkmaster Overspark to Tinkmaster Overspark.",
            dependsOn = { "accept-2923-tinkmaster-overspark" },
            complete = QuestState(2923, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.696, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2922-save-techbot-s-brain",
            kind = "accept",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Accept Save Techbot's Brain! from Tinkmaster Overspark.",
            dependsOn = { "turnin-2923-tinkmaster-overspark" },
            complete = QuestState(2922, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.696, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2927-the-day-after",
            kind = "accept",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Accept The Day After from Gnoarn.",
            complete = QuestState(2927, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.692, 0.506, "Gnoarn", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2930-data-rescue",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Accept Data Rescue from Master Mechanic Castpipe.",
            complete = QuestState(2930, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.698, 0.481, "Master Mechanic Castpipe", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2929-the-grand-betrayal",
            kind = "accept",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Accept The Grand Betrayal from High Tinker Mekkatorque.",
            complete = QuestState(2929, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.688, 0.490, "High Tinker Mekkatorque", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2927-the-day-after",
            kind = "turnin",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Turn in The Day After to Ozzie Togglevolt.",
            dependsOn = { "accept-2927-the-day-after" },
            complete = QuestState(2927, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "accept-2926-gnogaine",
            kind = "accept",
            priority = 21,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Accept Gnogaine from Ozzie Togglevolt.",
            dependsOn = { "turnin-2927-the-day-after" },
            complete = QuestState(2926, "activeOrCompleted"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 22,
            conditions = { level = { min = 25 } },
            text = "Enter Gnomeregan with your group.",
            dependsOn = { "accept-2923-tinkmaster-overspark", "accept-2928-gyrodrillmatic-excavationators", "accept-2925-klockmort-s-essentials", "accept-2924-essential-artificials", "accept-2922-save-techbot-s-brain", "accept-2927-the-day-after", "accept-2930-data-rescue", "accept-2929-the-grand-betrayal", "accept-2926-gnogaine" },
            persistCompletion = true,
            complete = { instance = 90 },
        },
        {
            id = "objective-2922-1-techbot-s-memory-core",
            kind = "objective",
            priority = 25,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Kill Techbot in the Workshop and loot Techbot's Memory Core.",
            dependsOn = { "accept-2922-save-techbot-s-brain" },
            complete = QuestState(2922, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2926-1-full-leaden-collection-p",
            kind = "objective",
            priority = 27,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Use the Empty Leaden Collection Phial on Irradiated Slimes or Horrors in Gnomeregan until it fills.",
            dependsOn = { "accept-2926-gnogaine" },
            complete = QuestState(2926, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-2926-gnogaine",
            kind = "turnin",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Turn in Gnogaine to Ozzie Togglevolt.",
            dependsOn = { "objective-2926-1-full-leaden-collection-p" },
            complete = QuestState(2926, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "accept-2962-the-only-cure-is-more-green-glow",
            kind = "accept",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Accept The Only Cure is More Green Glow from Ozzie Togglevolt.",
            dependsOn = { "turnin-2926-gnogaine" },
            complete = QuestState(2962, "activeOrCompleted"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "objective-2962-1-high-potency-radioactive",
            kind = "objective",
            priority = 33,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Use the Leaden Collection Phial on high-level irradiated slimes in the irradiated rooms until you collect High Potency Radioactive Fallout.",
            dependsOn = { "accept-2962-the-only-cure-is-more-green-glow" },
            complete = QuestState(2962, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2930-1-prismatic-punch-card",
            kind = "objective",
            priority = 37,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Loot the Prismatic Punch Card from the Dimensional Vault terminal in Gnomeregan.",
            dependsOn = { "accept-2930-data-rescue" },
            complete = QuestState(2930, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2928-1-robo-mechanical-guts",
            kind = "objective",
            priority = 39,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Kill leper gnomes and mechanized guards in Gnomeregan until you loot 24 Robo-mechanical Guts.",
            dependsOn = { "accept-2928-gyrodrillmatic-excavationators" },
            complete = QuestState(2928, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2924-1-essential-artificial",
            kind = "objective",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Kill mechanized units in Gnomeregan until you loot 12 Essential Artificial.",
            dependsOn = { "accept-2924-essential-artificials" },
            complete = QuestState(2924, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2929-1-mekgineer-thermaplugg",
            kind = "objective",
            priority = 42,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Kill Mekgineer Thermaplugg in the final chamber and loot proof of the betrayal for The Grand Betrayal.",
            dependsOn = { "accept-2929-the-grand-betrayal" },
            complete = QuestState(2929, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-2924-essential-artificials",
            kind = "turnin",
            priority = 45,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Turn in Essential Artificials to Klockmort Spannerspan.",
            dependsOn = { "objective-2924-1-essential-artificial" },
            complete = QuestState(2924, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.680, 0.461, "Klockmort Spannerspan", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2922-save-techbot-s-brain",
            kind = "turnin",
            priority = 46,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Turn in Save Techbot's Brain! to Tinkmaster Overspark.",
            dependsOn = { "objective-2922-1-techbot-s-memory-core" },
            complete = QuestState(2922, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.696, 0.503, "Tinkmaster Overspark", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2930-data-rescue",
            kind = "turnin",
            priority = 47,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Turn in Data Rescue to Master Mechanic Castpipe.",
            dependsOn = { "objective-2930-1-prismatic-punch-card" },
            complete = QuestState(2930, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.698, 0.481, "Master Mechanic Castpipe", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2929-the-grand-betrayal",
            kind = "turnin",
            priority = 48,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Turn in The Grand Betrayal to High Tinker Mekkatorque.",
            dependsOn = { "objective-2929-1-mekgineer-thermaplugg" },
            complete = QuestState(2929, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.688, 0.490, "High Tinker Mekkatorque", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2962-the-only-cure-is-more-green-glow",
            kind = "turnin",
            priority = 49,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 20 } } } },
            text = "Turn in The Only Cure is More Green Glow to Ozzie Togglevolt.",
            dependsOn = { "objective-2962-1-high-potency-radioactive" },
            complete = QuestState(2962, "completed"),
            route = {
                Point(MAP.DUN_MOROGH, 0.459, 0.494, "Ozzie Togglevolt", "Travel to Dun Morogh."),
            },
        },
        {
            id = "turnin-2928-gyrodrillmatic-excavationators",
            kind = "turnin",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 29 } } } },
            text = "Turn in Gyrodrillmatic Excavationators to Shoni the Shilent.",
            dependsOn = { "objective-2928-1-robo-mechanical-guts" },
            complete = QuestState(2928, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.555, 0.125, "Shoni the Shilent", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-2841-rig-wars",
            kind = "accept",
            priority = 51,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Accept Rig Wars from Nogg.",
            complete = QuestState(2841, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.760, 0.254, "Nogg", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-2842-chief-engineer-scooty",
            kind = "accept",
            priority = 52,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Accept Chief Engineer Scooty from Sovik.",
            complete = QuestState(2842, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.755, 0.254, "Sovik", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-2842-chief-engineer-scooty",
            kind = "turnin",
            priority = 53,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Turn in Chief Engineer Scooty to Scooty.",
            dependsOn = { "accept-2842-chief-engineer-scooty" },
            complete = QuestState(2842, "completed"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "accept-2843-gnomer-gooooone",
            kind = "accept",
            priority = 54,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Accept Gnomer-gooooone! from Scooty.",
            dependsOn = { "turnin-2842-chief-engineer-scooty" },
            complete = QuestState(2843, "activeOrCompleted"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "objective-2843-1-wait-for-scooty-to-calib",
            kind = "objective",
            priority = 55,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Wait for Scooty to Calibrate the Goblin Transponder.",
            dependsOn = { "accept-2843-gnomer-gooooone" },
            complete = QuestState(2843, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-2843-gnomer-gooooone",
            kind = "turnin",
            priority = 56,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Turn in Gnomer-gooooone! to Scooty.",
            dependsOn = { "objective-2843-1-wait-for-scooty-to-calib" },
            complete = QuestState(2843, "completed"),
            route = {
                Point(MAP.STRANGLETHORN_VALE, 0.276, 0.775, "Scooty", "Travel to Stranglethorn Vale."),
            },
        },
        {
            id = "objective-2841-2-thermaplugg-s-safe-combi",
            kind = "objective",
            priority = 60,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Kill Mekgineer Thermaplugg and loot Thermaplugg's Safe Combination.",
            dependsOn = { "accept-2841-rig-wars" },
            complete = QuestObjective(2841, 2, "Thermaplugg's Safe Combination"),
            useClientPin = true,
        },
        {
            id = "objective-2841-1-rig-blueprints",
            kind = "objective",
            priority = 62,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Loot the Rig Blueprints from the plans in Gnomeregan's upper halls.",
            dependsOn = { "accept-2841-rig-wars" },
            complete = QuestObjective(2841, 1, "Rig Blueprints"),
            useClientPin = true,
        },
        {
            id = "turnin-2841-rig-wars",
            kind = "turnin",
            priority = 63,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Turn in Rig Wars to Nogg.",
            dependsOn = { "objective-2841-2-thermaplugg-s-safe-combi", "objective-2841-1-rig-blueprints" },
            complete = QuestState(2841, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.760, 0.254, "Nogg", "Travel to Orgrimmar."),
            },
        },
    },
})
