local _, ns = ...

local MAP = {
    TANARIS = 1446,
    FERALAS = 1444,
    THE_HINTERLANDS = 1425,
    EASTERN_PLAGUELANDS = 1423,
    BURNING_STEPPES = 1428,
    BADLANDS = 1418,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-lower-blackrock-spire",
    title = "Lower Blackrock Spire",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 57 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-3520-screecher-spirits",
            kind = "accept",
            priority = 10,
            conditions = { level = { min = 49 } },
            text = "Accept Screecher Spirits from Yeh'kinya.",
            complete = QuestState(3520, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-3520-1-screecher-spirits",
            kind = "objective",
            priority = 12,
            conditions = { level = { min = 49 } },
            text = "Collect 3 Screecher Spirits.",
            dependsOn = { "accept-3520-screecher-spirits" },
            complete = QuestState(3520, "complete"),
            route = {
                Point(MAP.FERALAS, 0.583, 0.577, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-3520-screecher-spirits",
            kind = "turnin",
            priority = 13,
            conditions = { level = { min = 49 } },
            text = "Turn in Screecher Spirits to Yeh'kinya.",
            dependsOn = { "objective-3520-1-screecher-spirits" },
            complete = QuestState(3520, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3527-the-prophecy-of-mosh-aru",
            kind = "accept",
            priority = 14,
            conditions = { level = { min = 46 } },
            text = "Accept The Prophecy of Mosh'aru from Yeh'kinya.",
            dependsOn = { "turnin-3520-screecher-spirits" },
            complete = QuestState(3527, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 15,
            conditions = { level = { min = 57 } },
            text = "Enter Temple Of Atal'Hakkar with your group.",
            dependsOn = { "accept-3520-screecher-spirits", "accept-3527-the-prophecy-of-mosh-aru" },
            persistCompletion = true,
            complete = { instance = 229 },
        },
        {
            id = "objective-3527-1-first-mosh-aru-tablet",
            kind = "objective",
            priority = 17,
            conditions = { level = { min = 46 } },
            text = "Collect First Mosh'aru Tablet.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 1, "First Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-3527-2-second-mosh-aru-tablet",
            kind = "objective",
            priority = 19,
            conditions = { level = { min = 46 } },
            text = "Collect Second Mosh'aru Tablet.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 2, "Second Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "turnin-3527-the-prophecy-of-mosh-aru",
            kind = "turnin",
            priority = 22,
            conditions = { level = { min = 46 } },
            text = "Turn in The Prophecy of Mosh'aru to Yeh'kinya.",
            dependsOn = { "objective-3527-1-first-mosh-aru-tablet", "objective-3527-2-second-mosh-aru-tablet" },
            complete = QuestState(3527, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4787-the-ancient-egg",
            kind = "accept",
            priority = 23,
            conditions = { level = { min = 40 } },
            text = "Accept The Ancient Egg from Yeh'kinya.",
            dependsOn = { "turnin-3527-the-prophecy-of-mosh-aru" },
            complete = QuestState(4787, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-4787-1-ancient-egg",
            kind = "objective",
            priority = 25,
            conditions = { level = { min = 40 } },
            text = "Collect Ancient Egg.",
            dependsOn = { "accept-4787-the-ancient-egg" },
            complete = QuestState(4787, "complete"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.575, 0.868, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-4787-the-ancient-egg",
            kind = "turnin",
            priority = 26,
            conditions = { level = { min = 40 } },
            text = "Turn in The Ancient Egg to Yeh'kinya.",
            dependsOn = { "objective-4787-1-ancient-egg" },
            complete = QuestState(4787, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3528-the-god-hakkar",
            kind = "accept",
            priority = 27,
            conditions = { level = { min = 40 } },
            text = "Accept The God Hakkar from Yeh'kinya.",
            dependsOn = { "turnin-4787-the-ancient-egg" },
            complete = QuestState(3528, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-3528-1-fill-the-egg-of-hakkar",
            kind = "objective",
            priority = 32,
            conditions = { level = { min = 40 } },
            text = "Fill the Egg of Hakkar.",
            dependsOn = { "accept-3528-the-god-hakkar" },
            complete = QuestState(3528, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-3528-the-god-hakkar",
            kind = "turnin",
            priority = 33,
            conditions = { level = { min = 40 } },
            text = "Turn in The God Hakkar to Yeh'kinya.",
            dependsOn = { "objective-3528-1-fill-the-egg-of-hakkar" },
            complete = QuestState(3528, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-5065-the-lost-tablets-of-mosh-aru",
            kind = "accept",
            priority = 34,
            conditions = { level = { min = 40 } },
            text = "Accept The Lost Tablets of Mosh'aru from Prospector Ironboot.",
            complete = QuestState(5065, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.669, 0.240, "Prospector Ironboot", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-5065-2-fourth-mosh-aru-tablet",
            kind = "objective",
            priority = 36,
            conditions = { level = { min = 40 } },
            text = "Collect Fourth Mosh'aru Tablet.",
            dependsOn = { "accept-5065-the-lost-tablets-of-mosh-aru" },
            complete = QuestObjective(5065, 2, "Fourth Mosh'aru Tablet"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.727, 0.156, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5065-1-third-mosh-aru-tablet",
            kind = "objective",
            priority = 38,
            conditions = { level = { min = 40 } },
            text = "Collect Third Mosh'aru Tablet.",
            dependsOn = { "accept-5065-the-lost-tablets-of-mosh-aru" },
            complete = QuestObjective(5065, 1, "Third Mosh'aru Tablet"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.723, 0.129, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5065-the-lost-tablets-of-mosh-aru",
            kind = "turnin",
            priority = 39,
            conditions = { level = { min = 40 } },
            text = "Turn in The Lost Tablets of Mosh'aru to Prospector Ironboot.",
            dependsOn = { "objective-5065-2-fourth-mosh-aru-tablet", "objective-5065-1-third-mosh-aru-tablet" },
            complete = QuestState(5065, "completed"),
            route = {
                Point(MAP.TANARIS, 0.669, 0.240, "Prospector Ironboot", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4788-the-final-tablets",
            kind = "accept",
            priority = 40,
            conditions = { level = { min = 40 } },
            text = "Accept The Final Tablets from Prospector Ironboot.",
            dependsOn = { "turnin-5065-the-lost-tablets-of-mosh-aru" },
            complete = QuestState(4788, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.669, 0.240, "Prospector Ironboot", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4701-put-her-down",
            kind = "accept",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Put Her Down from Helendis Riverhorn.",
            complete = QuestState(4701, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.689, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4866-mother-s-milk",
            kind = "accept",
            priority = 42,
            conditions = { level = { min = 55 } },
            text = "Accept Mother's Milk from Ragged John.",
            complete = QuestState(4866, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Ragged John", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4729-kibler-s-exotic-pets",
            kind = "accept",
            priority = 43,
            conditions = { level = { min = 55 } },
            text = "Accept Kibler's Exotic Pets from Kibler.",
            complete = QuestState(4729, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.659, 0.219, "Kibler", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4862-en-ay-es-tee-why",
            kind = "accept",
            priority = 44,
            conditions = { level = { min = 55 } },
            text = "Accept En-Ay-Es-Tee-Why from Kibler.",
            complete = QuestState(4862, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.659, 0.219, "Kibler", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4867-urok-doomhowl",
            kind = "accept",
            priority = 45,
            conditions = { level = { min = 55 } },
            text = "Accept Urok Doomhowl from Warosh.",
            complete = QuestState(4867, "activeOrCompleted"),
        },
        {
            id = "accept-5001-bijou-s-belongings",
            kind = "accept",
            priority = 47,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Bijou's Belongings from Bijou.",
            complete = QuestState(5001, "activeOrCompleted"),
        },
        {
            id = "objective-5001-1-bijou-s-belongings",
            kind = "objective",
            priority = 49,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Collect Bijou's Belongings.",
            dependsOn = { "accept-5001-bijou-s-belongings" },
            complete = QuestState(5001, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5001-bijou-s-belongings",
            kind = "turnin",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Bijou's Belongings to Bijou.",
            dependsOn = { "objective-5001-1-bijou-s-belongings" },
            complete = QuestState(5001, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-5002-message-to-maxwell",
            kind = "accept",
            priority = 51,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Message to Maxwell from Bijou.",
            dependsOn = { "turnin-5001-bijou-s-belongings" },
            complete = QuestState(5002, "activeOrCompleted"),
        },
        {
            id = "turnin-5002-message-to-maxwell",
            kind = "turnin",
            priority = 52,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Message to Maxwell to Marshal Maxwell.",
            dependsOn = { "accept-5002-message-to-maxwell" },
            complete = QuestState(5002, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-5081-maxwell-s-mission",
            kind = "accept",
            priority = 53,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Maxwell's Mission from Marshal Maxwell.",
            dependsOn = { "turnin-5002-message-to-maxwell" },
            complete = QuestState(5081, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4742-seal-of-ascension",
            kind = "accept",
            priority = 55,
            conditions = { level = { min = 57 } },
            text = "Accept Seal of Ascension from Vaelan. 'As you wish, Vaelan.'.",
            complete = QuestState(4742, "activeOrCompleted"),
        },
        {
            id = "objective-4788-1-fifth-mosh-aru-tablet",
            kind = "objective",
            priority = 57,
            conditions = { level = { min = 40 } },
            text = "Collect Fifth Mosh'aru Tablet.",
            dependsOn = { "accept-4788-the-final-tablets" },
            complete = QuestObjective(4788, 1, "Fifth Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-5081-1-war-master-voone",
            kind = "objective",
            priority = 58,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Kill War Master Voone.",
            dependsOn = { "accept-5081-maxwell-s-mission" },
            complete = QuestObjective(5081, 1, "War Master Voone"),
            useClientPin = true,
        },
        {
            id = "objective-4742-2-gemstone-of-smolderthorn",
            kind = "objective",
            priority = 60,
            conditions = { level = { min = 57 } },
            text = "Collect Gemstone of Smolderthorn.",
            dependsOn = { "accept-4742-seal-of-ascension" },
            complete = QuestObjective(4742, 2, "Gemstone of Smolderthorn"),
            useClientPin = true,
        },
        {
            id = "objective-4788-2-sixth-mosh-aru-tablet",
            kind = "objective",
            priority = 62,
            conditions = { level = { min = 40 } },
            text = "Collect Sixth Mosh'aru Tablet.",
            dependsOn = { "accept-4788-the-final-tablets" },
            complete = QuestObjective(4788, 2, "Sixth Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-5081-2-highlord-omokk",
            kind = "objective",
            priority = 63,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Kill Highlord Omokk.",
            dependsOn = { "accept-5081-maxwell-s-mission" },
            complete = QuestObjective(5081, 2, "Highlord Omokk"),
            useClientPin = true,
        },
        {
            id = "objective-4742-1-gemstone-of-spirestone",
            kind = "objective",
            priority = 65,
            conditions = { level = { min = 57 } },
            text = "Collect Gemstone of Spirestone.",
            dependsOn = { "accept-4742-seal-of-ascension" },
            complete = QuestObjective(4742, 1, "Gemstone of Spirestone"),
            useClientPin = true,
        },
        {
            id = "objective-4862-1-spire-spider-egg",
            kind = "objective",
            priority = 68,
            conditions = { level = { min = 55 } },
            text = "Collect 15 Spire Spider Egg.",
            dependsOn = { "accept-4862-en-ay-es-tee-why" },
            complete = QuestState(4862, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4867-1-warosh-s-mojo",
            kind = "objective",
            priority = 70,
            conditions = { level = { min = 55 } },
            text = "Collect Warosh's Mojo.",
            dependsOn = { "accept-4867-urok-doomhowl" },
            complete = QuestState(4867, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4729-1-capture-a-caged-worg-pup",
            kind = "objective",
            priority = 71,
            conditions = { level = { min = 55 } },
            text = "Capture a Caged Worg Pup.",
            dependsOn = { "accept-4729-kibler-s-exotic-pets" },
            complete = QuestState(4729, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4701-1-halycon",
            kind = "objective",
            priority = 72,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Kill Halycon.",
            dependsOn = { "accept-4701-put-her-down" },
            complete = QuestState(4701, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-5081-3-overlord-wyrmthalak",
            kind = "objective",
            priority = 73,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Kill Overlord Wyrmthalak.",
            dependsOn = { "accept-5081-maxwell-s-mission" },
            complete = QuestObjective(5081, 3, "Overlord Wyrmthalak"),
            useClientPin = true,
        },
        {
            id = "objective-4742-3-gemstone-of-bloodaxe",
            kind = "objective",
            priority = 75,
            conditions = { level = { min = 57 } },
            text = "Collect Gemstone of Bloodaxe.",
            dependsOn = { "accept-4742-seal-of-ascension" },
            complete = QuestObjective(4742, 3, "Gemstone of Bloodaxe"),
            useClientPin = true,
        },
        {
            id = "turnin-4867-urok-doomhowl",
            kind = "turnin",
            priority = 76,
            conditions = { level = { min = 55 } },
            text = "Turn in Urok Doomhowl to Warosh.",
            dependsOn = { "objective-4867-1-warosh-s-mojo" },
            complete = QuestState(4867, "completed"),
            useClientPin = true,
        },
        {
            id = "turnin-4742-seal-of-ascension",
            kind = "turnin",
            priority = 77,
            conditions = { level = { min = 57 } },
            text = "Turn in Seal of Ascension to Vaelan.",
            dependsOn = { "objective-4742-2-gemstone-of-smolderthorn", "objective-4742-1-gemstone-of-spirestone", "objective-4742-3-gemstone-of-bloodaxe" },
            complete = QuestState(4742, "completed"),
            useClientPin = true,
        },
        {
            id = "turnin-5081-maxwell-s-mission",
            kind = "turnin",
            priority = 78,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Maxwell's Mission to Marshal Maxwell.",
            dependsOn = { "objective-5081-1-war-master-voone", "objective-5081-2-highlord-omokk", "objective-5081-3-overlord-wyrmthalak" },
            complete = QuestState(5081, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4701-put-her-down",
            kind = "turnin",
            priority = 79,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Put Her Down to Helendis Riverhorn.",
            dependsOn = { "objective-4701-1-halycon" },
            complete = QuestState(4701, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.689, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4866-1-return-to-ragged-john",
            kind = "objective",
            priority = 80,
            conditions = { level = { min = 55 } },
            text = "Return to Ragged John.",
            dependsOn = { "accept-4866-mother-s-milk" },
            complete = QuestState(4866, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4866-mother-s-milk",
            kind = "turnin",
            priority = 81,
            conditions = { level = { min = 55 } },
            text = "Turn in Mother's Milk to Ragged John.",
            dependsOn = { "objective-4866-1-return-to-ragged-john" },
            complete = QuestState(4866, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Ragged John", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4729-kibler-s-exotic-pets",
            kind = "turnin",
            priority = 82,
            conditions = { level = { min = 55 } },
            text = "Turn in Kibler's Exotic Pets to Kibler.",
            dependsOn = { "objective-4729-1-capture-a-caged-worg-pup" },
            complete = QuestState(4729, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.659, 0.219, "Kibler", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4862-en-ay-es-tee-why",
            kind = "turnin",
            priority = 83,
            conditions = { level = { min = 55 } },
            text = "Turn in En-Ay-Es-Tee-Why to Kibler.",
            dependsOn = { "objective-4862-1-spire-spider-egg" },
            complete = QuestState(4862, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.659, 0.219, "Kibler", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4788-the-final-tablets",
            kind = "turnin",
            priority = 84,
            conditions = { level = { min = 40 } },
            text = "Turn in The Final Tablets to Prospector Ironboot.",
            dependsOn = { "objective-4788-1-fifth-mosh-aru-tablet", "objective-4788-2-sixth-mosh-aru-tablet" },
            complete = QuestState(4788, "completed"),
            route = {
                Point(MAP.TANARIS, 0.669, 0.240, "Prospector Ironboot", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4903-warlord-s-command",
            kind = "accept",
            priority = 85,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Warlord's Command.",
            complete = QuestState(4903, "activeOrCompleted"),
        },
        {
            id = "accept-4981-operative-bijou",
            kind = "accept",
            priority = 86,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Operative Bijou from Lexlort.",
            complete = QuestState(4981, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.059, 0.476, "Lexlort", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4724-the-pack-mistress",
            kind = "accept",
            priority = 87,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Pack Mistress from Galamav the Marksman.",
            complete = QuestState(4724, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.060, 0.477, "Galamav the Marksman", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4981-operative-bijou",
            kind = "turnin",
            priority = 88,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Operative Bijou to Bijou.",
            dependsOn = { "accept-4981-operative-bijou" },
            complete = QuestState(4981, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4982-bijou-s-belongings",
            kind = "accept",
            priority = 89,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Bijou's Belongings from Bijou.",
            dependsOn = { "turnin-4981-operative-bijou" },
            complete = QuestState(4982, "activeOrCompleted"),
        },
        {
            id = "objective-4982-1-bijou-s-belongings",
            kind = "objective",
            priority = 90,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Bijou's Belongings.",
            dependsOn = { "accept-4982-bijou-s-belongings" },
            complete = QuestState(4982, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4982-bijou-s-belongings",
            kind = "turnin",
            priority = 91,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Bijou's Belongings to Bijou.",
            dependsOn = { "objective-4982-1-bijou-s-belongings" },
            complete = QuestState(4982, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4983-bijou-s-reconnaissance-report",
            kind = "accept",
            priority = 92,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Bijou's Reconnaissance Report from Bijou.",
            dependsOn = { "turnin-4982-bijou-s-belongings" },
            complete = QuestState(4983, "activeOrCompleted"),
        },
        {
            id = "objective-4903-3-war-master-voone",
            kind = "objective",
            priority = 93,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill War Master Voone.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 3, "War Master Voone"),
            useClientPin = true,
        },
        {
            id = "objective-4903-2-highlord-omokk",
            kind = "objective",
            priority = 95,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Highlord Omokk.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 2, "Highlord Omokk"),
            useClientPin = true,
        },
        {
            id = "objective-4724-1-halycon",
            kind = "objective",
            priority = 100,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Halycon.",
            dependsOn = { "accept-4724-the-pack-mistress" },
            complete = QuestState(4724, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4903-1-overlord-wyrmthalak",
            kind = "objective",
            priority = 101,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Overlord Wyrmthalak.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 1, "Overlord Wyrmthalak"),
            useClientPin = true,
        },
        {
            id = "objective-4903-4-important-blackrock-docu",
            kind = "objective",
            priority = 106,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Important Blackrock Documents.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 4, "Important Blackrock Documents"),
            useClientPin = true,
        },
        {
            id = "turnin-4903-warlord-s-command",
            kind = "turnin",
            priority = 107,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Warlord's Command to Warlord Goretooth.",
            dependsOn = { "objective-4903-3-war-master-voone", "objective-4903-2-highlord-omokk", "objective-4903-1-overlord-wyrmthalak", "objective-4903-4-important-blackrock-docu" },
            complete = QuestState(4903, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4983-bijou-s-reconnaissance-report",
            kind = "turnin",
            priority = 108,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Bijou's Reconnaissance Report to Lexlort.",
            dependsOn = { "accept-4983-bijou-s-reconnaissance-report" },
            complete = QuestState(4983, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.059, 0.476, "Lexlort", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4724-the-pack-mistress",
            kind = "turnin",
            priority = 109,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Pack Mistress to Galamav the Marksman.",
            dependsOn = { "objective-4724-1-halycon" },
            complete = QuestState(4724, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.060, 0.477, "Galamav the Marksman", "Travel to Badlands."),
            },
        },
    },
})
