local _, ns = ...

local MAP = {
    TANARIS = 1446,
    FERALAS = 1444,
    THE_HINTERLANDS = 1425,
    EASTERN_PLAGUELANDS = 1423,
    BURNING_STEPPES = 1428,
    BADLANDS = 1418,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-lower-blackrock-spire",
    title = "Lower Blackrock Spire",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 57 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-3520-screecher-spirits",
            kind = "accept",
            priority = 10,
            conditions = { level = { min = 40 } },
            text = "Accept Screecher Spirits from Yeh'kinya.",
            complete = QuestState(3520, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "boss-vale-screecher",
            kind = "note",
            priority = 11,
            conditions = { level = { min = 57 } },
            text = "Kill Vale Screecher. These have a low spawn rate. Use it on their corpse.",
        },
        {
            id = "objective-3520-1-screecher-spirits",
            kind = "objective",
            priority = 12,
            conditions = { level = { min = 40 } },
            text = "Collect 3 Screecher Spirits.",
            dependsOn = { "accept-3520-screecher-spirits" },
            complete = QuestState(3520, "complete"),
            route = {
                Point(MAP.FERALAS, 0.583, 0.577, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-3520-screecher-spirits",
            kind = "turnin",
            priority = 13,
            conditions = { level = { min = 40 } },
            text = "Turn in Screecher Spirits to Yeh'kinya.",
            dependsOn = { "objective-3520-1-screecher-spirits" },
            complete = QuestState(3520, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3527-the-prophecy-of-mosh-aru",
            kind = "accept",
            priority = 14,
            conditions = { level = { min = 40 } },
            text = "Accept The Prophecy of Mosh'aru from Yeh'kinya.",
            dependsOn = { "turnin-3520-screecher-spirits" },
            complete = QuestState(3527, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 15,
            conditions = { level = { min = 57 } },
            text = "Enter Temple Of Atal'Hakkar with your group.",
            dependsOn = { "accept-3520-screecher-spirits", "accept-3527-the-prophecy-of-mosh-aru" },
            persistCompletion = true,
            complete = { instance = 229 },
        },
        {
            id = "boss-theka-the-martyr",
            kind = "note",
            priority = 16,
            conditions = { level = { min = 57 } },
            text = "Kill Theka the Martyr. He is the second boss of the dungeon. Follow the path north and then go right when the path splits. Quickly go left afterwards and then north.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "objective-3527-1-first-mosh-aru-tablet",
            kind = "objective",
            priority = 17,
            conditions = { level = { min = 40 } },
            text = "Collect First Mosh'aru Tablet.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 1, "First Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "boss-hydromancer-velratha",
            kind = "note",
            priority = 18,
            conditions = { level = { min = 57 } },
            text = "Kill Hydromancer Velratha. Continue following the path west to reach the room with a large pyramid on the western side. Follow the path southeast to reach the large room with a pool in the center. She walks around this area.",
            dependsOn = { "boss-theka-the-martyr" },
        },
        {
            id = "objective-3527-2-second-mosh-aru-tablet",
            kind = "objective",
            priority = 19,
            conditions = { level = { min = 40 } },
            text = "Collect Second Mosh'aru Tablet.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 2, "Second Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "note-leave-the-dungeon",
            kind = "note",
            priority = 20,
            conditions = { level = { min = 57 } },
            text = "Leave the dungeon.",
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 21,
            conditions = { level = { min = 57 } },
            text = "Click Here to Continue.",
        },
        {
            id = "turnin-3527-the-prophecy-of-mosh-aru",
            kind = "turnin",
            priority = 22,
            conditions = { level = { min = 40 } },
            text = "Turn in The Prophecy of Mosh'aru to Yeh'kinya.",
            dependsOn = { "objective-3527-1-first-mosh-aru-tablet", "objective-3527-2-second-mosh-aru-tablet" },
            complete = QuestState(3527, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4787-the-ancient-egg",
            kind = "accept",
            priority = 23,
            conditions = { level = { min = 40 } },
            text = "Accept The Ancient Egg from Yeh'kinya.",
            dependsOn = { "turnin-3527-the-prophecy-of-mosh-aru" },
            complete = QuestState(4787, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "note-click-ancient-egg",
            kind = "note",
            priority = 24,
            conditions = { level = { min = 57 } },
            text = "Click Ancient Egg.",
            route = {
                Point(MAP.THE_HINTERLANDS, 0.622, 0.714, "The Hinterlands", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.600, 0.702, "The Hinterlands", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.587, 0.703, "The Hinterlands", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.592, 0.743, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "objective-4787-1-ancient-egg",
            kind = "objective",
            priority = 25,
            conditions = { level = { min = 40 } },
            text = "Collect Ancient Egg.",
            dependsOn = { "accept-4787-the-ancient-egg" },
            complete = QuestState(4787, "complete"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.575, 0.868, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-4787-the-ancient-egg",
            kind = "turnin",
            priority = 26,
            conditions = { level = { min = 40 } },
            text = "Turn in The Ancient Egg to Yeh'kinya.",
            dependsOn = { "objective-4787-1-ancient-egg" },
            complete = QuestState(4787, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3528-the-god-hakkar",
            kind = "accept",
            priority = 27,
            conditions = { level = { min = 40 } },
            text = "Accept The God Hakkar from Yeh'kinya.",
            dependsOn = { "turnin-4787-the-ancient-egg" },
            complete = QuestState(3528, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "boss-the-enemies-that-spawn-in-waves",
            kind = "note",
            priority = 28,
            conditions = { level = { min = 57 } },
            text = "Kill the enemies that spawn in waves. Use it next to the skeleton laying on the ground in the Sanctum of the Fallen God. After entering the dungeon, follow the left path and go up three large sets of stairs, immediately go right to follow a short hallway to reach the upper level. Follow the southwestern path to reach the Sanctum of the Fallen God.",
            dependsOn = { "boss-hydromancer-velratha" },
        },
        {
            id = "boss-hakkari-bloodkeeper",
            kind = "note",
            priority = 29,
            conditions = { level = { min = 57 } },
            text = "Kill Hakkari Bloodkeeper+. Use it next to the skeleton laying on the ground in the Sanctum of the Fallen God. After entering the dungeon, follow the left path and go up three large sets of stairs, immediately go right to follow a short hallway to reach the upper level. Follow the southwestern path to reach the Sanctum of the Fallen God.",
            dependsOn = { "boss-the-enemies-that-spawn-in-waves" },
        },
        {
            id = "note-click-eternal-flame",
            kind = "note",
            priority = 30,
            conditions = { level = { min = 57 } },
            text = "Click Eternal Flame+.",
        },
        {
            id = "boss-avatar-of-hakkar",
            kind = "note",
            priority = 31,
            conditions = { level = { min = 57 } },
            text = "Kill Avatar of Hakkar. Use it next to the skeleton laying on the ground in the Sanctum of the Fallen God. After entering the dungeon, follow the left path and go up three large sets of stairs, immediately go right to follow a short hallway to reach the upper level. Follow the southwestern path to reach the Sanctum of the Fallen God.",
            dependsOn = { "boss-hakkari-bloodkeeper" },
        },
        {
            id = "objective-3528-1-fill-the-egg-of-hakkar",
            kind = "objective",
            priority = 32,
            conditions = { level = { min = 40 } },
            text = "Fill the Egg of Hakkar.",
            dependsOn = { "accept-3528-the-god-hakkar" },
            complete = QuestState(3528, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-3528-the-god-hakkar",
            kind = "turnin",
            priority = 33,
            conditions = { level = { min = 40 } },
            text = "Turn in The God Hakkar to Yeh'kinya.",
            dependsOn = { "objective-3528-1-fill-the-egg-of-hakkar" },
            complete = QuestState(3528, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-5065-the-lost-tablets-of-mosh-aru",
            kind = "accept",
            priority = 34,
            conditions = { level = { min = 40 } },
            text = "Accept The Lost Tablets of Mosh'aru from Prospector Ironboot.",
            complete = QuestState(5065, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.669, 0.240, "Prospector Ironboot", "Travel to Tanaris."),
            },
        },
        {
            id = "note-click-fourth-mosh-aru-tablet",
            kind = "note",
            priority = 35,
            conditions = { level = { min = 57 } },
            text = "Click Fourth Mosh'aru Tablet.",
        },
        {
            id = "objective-5065-2-fourth-mosh-aru-tablet",
            kind = "objective",
            priority = 36,
            conditions = { level = { min = 40 } },
            text = "Collect Fourth Mosh'aru Tablet.",
            dependsOn = { "accept-5065-the-lost-tablets-of-mosh-aru" },
            complete = QuestObjective(5065, 2, "Fourth Mosh'aru Tablet"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.727, 0.156, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "note-click-third-mosh-aru-tablet",
            kind = "note",
            priority = 37,
            conditions = { level = { min = 57 } },
            text = "Click Third Mosh'aru Tablet.",
        },
        {
            id = "objective-5065-1-third-mosh-aru-tablet",
            kind = "objective",
            priority = 38,
            conditions = { level = { min = 40 } },
            text = "Collect Third Mosh'aru Tablet.",
            dependsOn = { "accept-5065-the-lost-tablets-of-mosh-aru" },
            complete = QuestObjective(5065, 1, "Third Mosh'aru Tablet"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.723, 0.129, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5065-the-lost-tablets-of-mosh-aru",
            kind = "turnin",
            priority = 39,
            conditions = { level = { min = 40 } },
            text = "Turn in The Lost Tablets of Mosh'aru to Prospector Ironboot.",
            dependsOn = { "objective-5065-2-fourth-mosh-aru-tablet", "objective-5065-1-third-mosh-aru-tablet" },
            complete = QuestState(5065, "completed"),
            route = {
                Point(MAP.TANARIS, 0.669, 0.240, "Prospector Ironboot", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4788-the-final-tablets",
            kind = "accept",
            priority = 40,
            conditions = { level = { min = 40 } },
            text = "Accept The Final Tablets from Prospector Ironboot.",
            dependsOn = { "turnin-5065-the-lost-tablets-of-mosh-aru" },
            complete = QuestState(4788, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.669, 0.240, "Prospector Ironboot", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4701-put-her-down",
            kind = "accept",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Put Her Down from Helendis Riverhorn.",
            complete = QuestState(4701, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.689, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4866-mother-s-milk",
            kind = "accept",
            priority = 42,
            conditions = { level = { min = 55 } },
            text = "Accept Mother's Milk from Ragged John.",
            complete = QuestState(4866, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Ragged John", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4729-kibler-s-exotic-pets",
            kind = "accept",
            priority = 43,
            conditions = { level = { min = 55 } },
            text = "Accept Kibler's Exotic Pets from Kibler.",
            complete = QuestState(4729, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.659, 0.219, "Kibler", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4862-en-ay-es-tee-why",
            kind = "accept",
            priority = 44,
            conditions = { level = { min = 55 } },
            text = "Accept En-Ay-Es-Tee-Why from Kibler.",
            complete = QuestState(4862, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.659, 0.219, "Kibler", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4867-urok-doomhowl",
            kind = "accept",
            priority = 45,
            conditions = { level = { min = 55 } },
            text = "Accept Urok Doomhowl from Warosh.",
            complete = QuestState(4867, "activeOrCompleted"),
        },
        {
            id = "note-click-roughshod-pike",
            kind = "note",
            priority = 46,
            conditions = { level = { min = 57 } },
            text = "Click Roughshod Pike.",
        },
        {
            id = "accept-5001-bijou-s-belongings",
            kind = "accept",
            priority = 47,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Bijou's Belongings from Bijou.",
            complete = QuestState(5001, "activeOrCompleted"),
        },
        {
            id = "note-click-bijou-s-belongings",
            kind = "note",
            priority = 48,
            conditions = { level = { min = 57 } },
            text = "Click Bijou's Belongings.",
        },
        {
            id = "objective-5001-1-bijou-s-belongings",
            kind = "objective",
            priority = 49,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Collect Bijou's Belongings.",
            dependsOn = { "accept-5001-bijou-s-belongings" },
            complete = QuestState(5001, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5001-bijou-s-belongings",
            kind = "turnin",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Bijou's Belongings to Bijou.",
            dependsOn = { "objective-5001-1-bijou-s-belongings" },
            complete = QuestState(5001, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-5002-message-to-maxwell",
            kind = "accept",
            priority = 51,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Message to Maxwell from Bijou.",
            dependsOn = { "turnin-5001-bijou-s-belongings" },
            complete = QuestState(5002, "activeOrCompleted"),
        },
        {
            id = "turnin-5002-message-to-maxwell",
            kind = "turnin",
            priority = 52,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Message to Maxwell to Marshal Maxwell.",
            dependsOn = { "accept-5002-message-to-maxwell" },
            complete = QuestState(5002, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-5081-maxwell-s-mission",
            kind = "accept",
            priority = 53,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Maxwell's Mission from Marshal Maxwell.",
            dependsOn = { "turnin-5002-message-to-maxwell" },
            complete = QuestState(5081, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "boss-enemies-around-this-area",
            kind = "note",
            priority = 54,
            conditions = { level = { min = 57 } },
            text = "Kill enemies around this area.",
            dependsOn = { "boss-avatar-of-hakkar" },
        },
        {
            id = "accept-4742-seal-of-ascension",
            kind = "accept",
            priority = 55,
            conditions = { level = { min = 57 } },
            text = "Accept Seal of Ascension from Vaelan. 'As you wish, Vaelan.'.",
            complete = QuestState(4742, "activeOrCompleted"),
        },
        {
            id = "note-click-fifth-mosh-aru-tablet",
            kind = "note",
            priority = 56,
            conditions = { level = { min = 57 } },
            text = "Click Fifth Mosh'aru Tablet.",
        },
        {
            id = "objective-4788-1-fifth-mosh-aru-tablet",
            kind = "objective",
            priority = 57,
            conditions = { level = { min = 40 } },
            text = "Collect Fifth Mosh'aru Tablet.",
            dependsOn = { "accept-4788-the-final-tablets" },
            complete = QuestObjective(4788, 1, "Fifth Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-5081-1-war-master-voone",
            kind = "objective",
            priority = 58,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Kill War Master Voone.",
            dependsOn = { "accept-5081-maxwell-s-mission" },
            complete = QuestObjective(5081, 1, "War Master Voone"),
            useClientPin = true,
        },
        {
            id = "boss-war-master-voone",
            kind = "note",
            priority = 59,
            conditions = { level = { min = 57 } },
            text = "Kill War Master Voone. Follow the ramps back down to the lowest level of Tazz'Alaor. Follow the path in the southwestern corner of the room. This isn't a 100% drop rate. Clear the rooms leading up to him before engaging. War master Voone hits hard, so this will be a healing intensive fight. Wait for the tank to establish aggro before DPS jumps in.",
            dependsOn = { "boss-enemies-around-this-area" },
        },
        {
            id = "objective-4742-2-gemstone-of-smolderthorn",
            kind = "objective",
            priority = 60,
            conditions = { level = { min = 57 } },
            text = "Collect Gemstone of Smolderthorn.",
            dependsOn = { "accept-4742-seal-of-ascension" },
            complete = QuestObjective(4742, 2, "Gemstone of Smolderthorn"),
            useClientPin = true,
        },
        {
            id = "note-click-sixth-mosh-aru-tablet",
            kind = "note",
            priority = 61,
            conditions = { level = { min = 57 } },
            text = "Click Sixth Mosh'aru Tablet.",
        },
        {
            id = "objective-4788-2-sixth-mosh-aru-tablet",
            kind = "objective",
            priority = 62,
            conditions = { level = { min = 40 } },
            text = "Collect Sixth Mosh'aru Tablet.",
            dependsOn = { "accept-4788-the-final-tablets" },
            complete = QuestObjective(4788, 2, "Sixth Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-5081-2-highlord-omokk",
            kind = "objective",
            priority = 63,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Kill Highlord Omokk.",
            dependsOn = { "accept-5081-maxwell-s-mission" },
            complete = QuestObjective(5081, 2, "Highlord Omokk"),
            useClientPin = true,
        },
        {
            id = "boss-highlord-omokk",
            kind = "note",
            priority = 64,
            conditions = { level = { min = 57 } },
            text = "Kill Highlord Omokk. Return to the upper level of the dungeon again and proceed through Hordemar City. Continue past the groove in the ground where Bijou is and go west with all of the ogres to reach Mok'Doom. He is in the back of the room along the north side. CC one of the two adds that accompany him. The tank should stand away from the group after picking up Highlord Omokk. Ranged should stand with their backs to a wall.",
            dependsOn = { "boss-war-master-voone" },
        },
        {
            id = "objective-4742-1-gemstone-of-spirestone",
            kind = "objective",
            priority = 65,
            conditions = { level = { min = 57 } },
            text = "Collect Gemstone of Spirestone.",
            dependsOn = { "accept-4742-seal-of-ascension" },
            complete = QuestObjective(4742, 1, "Gemstone of Spirestone"),
            useClientPin = true,
        },
        {
            id = "boss-mother-smolderweb",
            kind = "note",
            priority = 66,
            conditions = { level = { min = 57 } },
            text = "Kill Mother Smolderweb. In the lower part of the dungeon, in the upper level of the Skitterweb Tunnels. If you are able to dispel the poison, make sure you don't. On the way to her, Druids can use the 'Hibernate' ability to CC them if one is available. When you reach her, the tank should face her away from the group to avoid her 'Crystallize' ability. Her 'Mother's Milk' ability will temporarily stun party members.",
            dependsOn = { "boss-highlord-omokk" },
        },
        {
            id = "note-click-spire-spider-egg",
            kind = "note",
            priority = 67,
            conditions = { level = { min = 57 } },
            text = "Click Spire Spider Egg+.",
        },
        {
            id = "objective-4862-1-spire-spider-egg",
            kind = "objective",
            priority = 68,
            conditions = { level = { min = 55 } },
            text = "Collect 15 Spire Spider Egg.",
            dependsOn = { "accept-4862-en-ay-es-tee-why" },
            complete = QuestState(4862, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-urok-doomhowl",
            kind = "note",
            priority = 69,
            conditions = { level = { min = 57 } },
            text = "Kill Urok Doomhowl. Use it near the pile of bones up the ramp past Mother Smolderweb. It looks like a large pile of skulls in Hordemar City. He will appear after a wave of ogres. Collect the Pike on the ledge just after Mother Smolderweb. Whoever picked up Omokk's Head should do this. Clear the room of ogres then combine the two to summon Urok Doomhowl.",
            dependsOn = { "boss-mother-smolderweb" },
        },
        {
            id = "objective-4867-1-warosh-s-mojo",
            kind = "objective",
            priority = 70,
            conditions = { level = { min = 55 } },
            text = "Collect Warosh's Mojo.",
            dependsOn = { "accept-4867-urok-doomhowl" },
            complete = QuestState(4867, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4729-1-capture-a-caged-worg-pup",
            kind = "objective",
            priority = 71,
            conditions = { level = { min = 55 } },
            text = "Capture a Caged Worg Pup.",
            dependsOn = { "accept-4729-kibler-s-exotic-pets" },
            complete = QuestState(4729, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4701-1-halycon",
            kind = "objective",
            priority = 72,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Kill Halycon.",
            dependsOn = { "accept-4701-put-her-down" },
            complete = QuestState(4701, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-5081-3-overlord-wyrmthalak",
            kind = "objective",
            priority = 73,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Kill Overlord Wyrmthalak.",
            dependsOn = { "accept-5081-maxwell-s-mission" },
            complete = QuestObjective(5081, 3, "Overlord Wyrmthalak"),
            useClientPin = true,
        },
        {
            id = "boss-overlord-wyrmthalak",
            kind = "note",
            priority = 74,
            conditions = { level = { min = 57 } },
            text = "Kill Overlord Wyrmthalak. Final boss of Lower Blackrock Spire, inside the Chamber of Battle. After killing Halycon, go up the first small set of stairs on your left in the hallway room before Halycon's Lair. Cross this room and continue up the small set of stairs on the opposite side, continue forward to reach the Chamber of Battle. The tank needs to face Wyrmthalak away from the group. Melee be sure to stand behind him to avoid its 'Cleave' ability. CC adds as the spawn and DPS Overlord Wyrmthalak as fast as possible, moving to the adds after he is dealth with.",
            dependsOn = { "boss-urok-doomhowl" },
        },
        {
            id = "objective-4742-3-gemstone-of-bloodaxe",
            kind = "objective",
            priority = 75,
            conditions = { level = { min = 57 } },
            text = "Collect Gemstone of Bloodaxe.",
            dependsOn = { "accept-4742-seal-of-ascension" },
            complete = QuestObjective(4742, 3, "Gemstone of Bloodaxe"),
            useClientPin = true,
        },
        {
            id = "turnin-4867-urok-doomhowl",
            kind = "turnin",
            priority = 76,
            conditions = { level = { min = 55 } },
            text = "Turn in Urok Doomhowl to Warosh.",
            dependsOn = { "objective-4867-1-warosh-s-mojo" },
            complete = QuestState(4867, "completed"),
            useClientPin = true,
        },
        {
            id = "turnin-4742-seal-of-ascension",
            kind = "turnin",
            priority = 77,
            conditions = { level = { min = 57 } },
            text = "Turn in Seal of Ascension to Vaelan.",
            dependsOn = { "objective-4742-2-gemstone-of-smolderthorn", "objective-4742-1-gemstone-of-spirestone", "objective-4742-3-gemstone-of-bloodaxe" },
            complete = QuestState(4742, "completed"),
            useClientPin = true,
        },
        {
            id = "turnin-5081-maxwell-s-mission",
            kind = "turnin",
            priority = 78,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Maxwell's Mission to Marshal Maxwell.",
            dependsOn = { "objective-5081-1-war-master-voone", "objective-5081-2-highlord-omokk", "objective-5081-3-overlord-wyrmthalak" },
            complete = QuestState(5081, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4701-put-her-down",
            kind = "turnin",
            priority = 79,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Put Her Down to Helendis Riverhorn.",
            dependsOn = { "objective-4701-1-halycon" },
            complete = QuestState(4701, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.689, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4866-1-return-to-ragged-john",
            kind = "objective",
            priority = 80,
            conditions = { level = { min = 55 } },
            text = "Return to Ragged John.",
            dependsOn = { "accept-4866-mother-s-milk" },
            complete = QuestState(4866, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4866-mother-s-milk",
            kind = "turnin",
            priority = 81,
            conditions = { level = { min = 55 } },
            text = "Turn in Mother's Milk to Ragged John.",
            dependsOn = { "objective-4866-1-return-to-ragged-john" },
            complete = QuestState(4866, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Ragged John", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4729-kibler-s-exotic-pets",
            kind = "turnin",
            priority = 82,
            conditions = { level = { min = 55 } },
            text = "Turn in Kibler's Exotic Pets to Kibler.",
            dependsOn = { "objective-4729-1-capture-a-caged-worg-pup" },
            complete = QuestState(4729, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.659, 0.219, "Kibler", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4862-en-ay-es-tee-why",
            kind = "turnin",
            priority = 83,
            conditions = { level = { min = 55 } },
            text = "Turn in En-Ay-Es-Tee-Why to Kibler.",
            dependsOn = { "objective-4862-1-spire-spider-egg" },
            complete = QuestState(4862, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.659, 0.219, "Kibler", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4788-the-final-tablets",
            kind = "turnin",
            priority = 84,
            conditions = { level = { min = 40 } },
            text = "Turn in The Final Tablets to Prospector Ironboot.",
            dependsOn = { "objective-4788-1-fifth-mosh-aru-tablet", "objective-4788-2-sixth-mosh-aru-tablet" },
            complete = QuestState(4788, "completed"),
            route = {
                Point(MAP.TANARIS, 0.669, 0.240, "Prospector Ironboot", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4903-warlord-s-command",
            kind = "accept",
            priority = 85,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Warlord's Command.",
            complete = QuestState(4903, "activeOrCompleted"),
        },
        {
            id = "accept-4981-operative-bijou",
            kind = "accept",
            priority = 86,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Operative Bijou from Lexlort.",
            complete = QuestState(4981, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.059, 0.476, "Lexlort", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4724-the-pack-mistress",
            kind = "accept",
            priority = 87,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Pack Mistress from Galamav the Marksman.",
            complete = QuestState(4724, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.060, 0.477, "Galamav the Marksman", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4981-operative-bijou",
            kind = "turnin",
            priority = 88,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Operative Bijou to Bijou.",
            dependsOn = { "accept-4981-operative-bijou" },
            complete = QuestState(4981, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4982-bijou-s-belongings",
            kind = "accept",
            priority = 89,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Bijou's Belongings from Bijou.",
            dependsOn = { "turnin-4981-operative-bijou" },
            complete = QuestState(4982, "activeOrCompleted"),
        },
        {
            id = "objective-4982-1-bijou-s-belongings",
            kind = "objective",
            priority = 90,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Bijou's Belongings.",
            dependsOn = { "accept-4982-bijou-s-belongings" },
            complete = QuestState(4982, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4982-bijou-s-belongings",
            kind = "turnin",
            priority = 91,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Bijou's Belongings to Bijou.",
            dependsOn = { "objective-4982-1-bijou-s-belongings" },
            complete = QuestState(4982, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4983-bijou-s-reconnaissance-report",
            kind = "accept",
            priority = 92,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Bijou's Reconnaissance Report from Bijou.",
            dependsOn = { "turnin-4982-bijou-s-belongings" },
            complete = QuestState(4983, "activeOrCompleted"),
        },
        {
            id = "objective-4903-3-war-master-voone",
            kind = "objective",
            priority = 93,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill War Master Voone.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 3, "War Master Voone"),
            useClientPin = true,
        },
        {
            id = "boss-shadow-hunter-vosh-gajin",
            kind = "note",
            priority = 94,
            conditions = { level = { min = 57 } },
            text = "Kill Shadow Hunter Vosh'gajin. She will be accompanied by 2 'Smolderthorn Shadow Priests'. CC one of them. The tank should take Shadow Hunter Vosh'gajin away from the group.",
            dependsOn = { "boss-overlord-wyrmthalak" },
        },
        {
            id = "objective-4903-2-highlord-omokk",
            kind = "objective",
            priority = 95,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Highlord Omokk.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 2, "Highlord Omokk"),
            useClientPin = true,
        },
        {
            id = "boss-spirestone-butcher",
            kind = "note",
            priority = 96,
            conditions = { level = { min = 57 } },
            text = "Kill Spirestone Butcher if the rare is up. This is a rare mob that may not be available.",
            dependsOn = { "boss-shadow-hunter-vosh-gajin" },
        },
        {
            id = "boss-spirestone-battle-lord",
            kind = "note",
            priority = 97,
            conditions = { level = { min = 57 } },
            text = "Kill Spirestone Battle Lord if the rare is up. This is a rare mob that may not be available.",
            dependsOn = { "boss-spirestone-butcher" },
        },
        {
            id = "boss-bannok-grimaxe",
            kind = "note",
            priority = 98,
            conditions = { level = { min = 57 } },
            text = "Kill Bannok Grimaxe if the rare is up. This is a rare mob that may not be available. He can spawn in any of the packs of mobs around tents, and sometimes patrols.",
            dependsOn = { "boss-spirestone-battle-lord" },
        },
        {
            id = "boss-crystal-fang",
            kind = "note",
            priority = 99,
            conditions = { level = { min = 57 } },
            text = "Kill Crystal Fang if the rare is up. This is a rare mob that may not be available.",
            dependsOn = { "boss-bannok-grimaxe" },
        },
        {
            id = "objective-4724-1-halycon",
            kind = "objective",
            priority = 100,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Halycon.",
            dependsOn = { "accept-4724-the-pack-mistress" },
            complete = QuestState(4724, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4903-1-overlord-wyrmthalak",
            kind = "objective",
            priority = 101,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Overlord Wyrmthalak.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 1, "Overlord Wyrmthalak"),
            useClientPin = true,
        },
        {
            id = "boss-quartermaster-zigris",
            kind = "note",
            priority = 102,
            conditions = { level = { min = 57 } },
            text = "Kill Quartermaster Zigris. Clear the entire room that he patrols before engaging him. Avoid him when possible, until the room is clear by waiting for him to patrol past the group.",
            dependsOn = { "boss-crystal-fang" },
        },
        {
            id = "boss-halycon",
            kind = "note",
            priority = 103,
            conditions = { level = { min = 57 } },
            text = "Kill Halycon. Halycon will be accompanied by 'Worg Pups' which will need to be AoE'd down. The tank should pick up Halycon while this is happening, establishing aggro. Once the adds are taken care of, DPS should move to Halycon.",
            dependsOn = { "boss-quartermaster-zigris" },
        },
        {
            id = "boss-gizrul-the-slavener",
            kind = "note",
            priority = 104,
            conditions = { level = { min = 57 } },
            text = "Kill Gizrul the Slavener. This boss hits hard, so it will be a healing intensive fight. It heals with each use of 'Fatal Bite', dealing out massive damage to the tank. It will also use the 'Infected Bite' ability on your tank.",
            dependsOn = { "boss-halycon" },
        },
        {
            id = "note-click-inconspicuous-documents",
            kind = "note",
            priority = 105,
            conditions = { level = { min = 57 } },
            text = "Click Inconspicuous Documents.",
        },
        {
            id = "objective-4903-4-important-blackrock-docu",
            kind = "objective",
            priority = 106,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Important Blackrock Documents.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 4, "Important Blackrock Documents"),
            useClientPin = true,
        },
        {
            id = "turnin-4903-warlord-s-command",
            kind = "turnin",
            priority = 107,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Warlord's Command to Warlord Goretooth.",
            dependsOn = { "objective-4903-3-war-master-voone", "objective-4903-2-highlord-omokk", "objective-4903-1-overlord-wyrmthalak", "objective-4903-4-important-blackrock-docu" },
            complete = QuestState(4903, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4983-bijou-s-reconnaissance-report",
            kind = "turnin",
            priority = 108,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Bijou's Reconnaissance Report to Lexlort.",
            dependsOn = { "accept-4983-bijou-s-reconnaissance-report" },
            complete = QuestState(4983, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.059, 0.476, "Lexlort", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-4724-the-pack-mistress",
            kind = "turnin",
            priority = 109,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Pack Mistress to Galamav the Marksman.",
            dependsOn = { "objective-4724-1-halycon" },
            complete = QuestState(4724, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.060, 0.477, "Galamav the Marksman", "Travel to Badlands."),
            },
        },
    },
})
