local _, ns = ...

local MAP = {
    DUSTWALLOW_MARSH = 1445,
    DESOLACE = 1443,
    MOONGLADE = 1450,
    ORGRIMMAR = 1454,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-maraudon",
    title = "Maraudon",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 45 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-7070-shadowshard-fragments",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 39 } } } },
            text = "Accept Shadowshard Fragments from Archmage Tervosh.",
            complete = QuestState(7070, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.664, 0.493, "Archmage Tervosh", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-7041-vyletongue-corruption",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Accept Vyletongue Corruption from Talendria.",
            complete = QuestState(7041, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.685, 0.089, "Talendria", "Travel to Desolace."),
            },
        },
        {
            id = "accept-7065-corruption-of-earth-and-seed",
            kind = "accept",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 45 } } } },
            text = "Accept Corruption of Earth and Seed from Keeper Marandis.",
            complete = QuestState(7065, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.638, 0.107, "Keeper Marandis", "Travel to Desolace."),
            },
        },
        {
            id = "accept-7028-twisted-evils",
            kind = "accept",
            priority = 13,
            conditions = { level = { min = 41 } },
            text = "Accept Twisted Evils from Willow.",
            complete = QuestState(7028, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.622, 0.396, "Willow", "Travel to Desolace."),
            },
        },
        {
            id = "accept-7067-the-pariah-s-instructions",
            kind = "accept",
            priority = 14,
            conditions = { level = { min = 39 } },
            text = "Accept The Pariah's Instructions from Centuar Pariah.",
            complete = QuestState(7067, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.515, 0.874, "Centuar Pariah", "Travel to Desolace."),
            },
        },
        {
            id = "note-click-stone-door",
            kind = "note",
            priority = 15,
            conditions = { level = { min = 45 } },
            text = "Click Stone Door.",
        },
        {
            id = "boss-the-nameless-prophet",
            kind = "note",
            priority = 16,
            conditions = { level = { min = 45 } },
            text = "Kill The Nameless Prophet. He spawns in multiple locations outside of the Maraudon dungeon. You may need help with this.",
        },
        {
            id = "boss-gelk",
            kind = "note",
            priority = 17,
            conditions = { level = { min = 45 } },
            text = "Kill Gelk. Use it on the Spirit of Gelk. He walks around this area.",
            dependsOn = { "boss-the-nameless-prophet" },
        },
        {
            id = "boss-shadowshard-enemies-around-this-area",
            kind = "note",
            priority = 18,
            conditions = { level = { min = 45 } },
            text = "Kill Shadowshard enemies around this area.",
            dependsOn = { "boss-gelk" },
        },
        {
            id = "objective-7070-1-shadowshard-fragment",
            kind = "objective",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 39 } } } },
            text = "Collect 10 Shadowshard Fragment.",
            dependsOn = { "accept-7070-shadowshard-fragments" },
            complete = QuestState(7070, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.283, 0.545, "Desolace", "Travel to Desolace."),
            },
        },
        {
            id = "boss-kolk",
            kind = "note",
            priority = 20,
            conditions = { level = { min = 45 } },
            text = "Kill Kolk. Use it on the Spirit of Kolk.",
            dependsOn = { "boss-shadowshard-enemies-around-this-area" },
        },
        {
            id = "accept-7044-legend-of-maraudon-goto-desolace-38-76-58",
            kind = "accept",
            priority = 21,
            conditions = { level = { min = 41 } },
            text = "Accept Legend of Maraudon |goto Desolace 38.76,58.13 from CavindraCavindra.",
            complete = QuestState(7044, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.386, 0.580, "CavindraCavindra", "Travel to Desolace."),
                Point(MAP.DESOLACE, 0.384, 0.581, "CavindraCavindra", "Travel to Desolace."),
                Point(MAP.DESOLACE, 0.385, 0.582, "CavindraCavindra", "Travel to Desolace."),
            },
        },
        {
            id = "objective-7041-2-filled-cerulean-vial",
            kind = "objective",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Collect Filled Cerulean Vial.",
            dependsOn = { "accept-7041-vyletongue-corruption" },
            complete = QuestObjective(7041, 2, "Filled Cerulean Vial"),
            route = {
                Point(MAP.DESOLACE, 0.389, 0.584, "Desolace", "Travel to Desolace."),
            },
        },
        {
            id = "boss-magra",
            kind = "note",
            priority = 23,
            conditions = { level = { min = 45 } },
            text = "Kill Magra. Use it on the Spirit of Magra. He walks around this area.",
            dependsOn = { "boss-kolk" },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 24,
            conditions = { level = { min = 45 } },
            text = "Enter Maraudon (Foulspore Cavern - Orange) with your group.",
            dependsOn = { "accept-7070-shadowshard-fragments", "accept-7041-vyletongue-corruption", "accept-7065-corruption-of-earth-and-seed", "accept-7028-twisted-evils", "accept-7067-the-pariah-s-instructions", "accept-7044-legend-of-maraudon-goto-desolace-38-76-58" },
            persistCompletion = true,
            complete = { instance = 349 },
            route = {
                Point(MAP.DESOLACE, 0.296, 0.647, "Maraudon entrance", "Travel to Desolace."),
            },
        },
        {
            id = "boss-noxxion",
            kind = "note",
            priority = 25,
            conditions = { level = { min = 45 } },
            text = "Kill Noxxion. It is the first boss on the Orange side of Maraudon. After entering the dungeon, run up the stairs and follow the path to the right whenever possible.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "objective-7044-2-celebrian-rod",
            kind = "objective",
            priority = 26,
            conditions = { level = { min = 41 } },
            text = "Collect Celebrian Rod.",
            dependsOn = { "accept-7044-legend-of-maraudon-goto-desolace-38-76-58" },
            complete = QuestObjective(7044, 2, "Celebrian Rod"),
            useClientPin = true,
        },
        {
            id = "boss-veng",
            kind = "note",
            priority = 27,
            conditions = { level = { min = 45 } },
            text = "Kill Veng. Use it on the Spirit of Veng. He walks around the Orange side of Maraudon.",
            dependsOn = { "boss-noxxion" },
        },
        {
            id = "boss-noxxious-scion",
            kind = "note",
            priority = 28,
            conditions = { level = { min = 45 } },
            text = "Kill Noxxious Scion+. While in the Foulspore Cavern, or Orange side of Maraudon, there will be tree stumps with a red top. You won't be able to target them. They have five leaves growing out of them.",
            dependsOn = { "boss-veng" },
        },
        {
            id = "objective-7041-1-heal-8-vylestem-vines",
            kind = "objective",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Heal 8 Vylestem Vines.",
            dependsOn = { "accept-7041-vyletongue-corruption" },
            complete = QuestObjective(7041, 1, "Heal 8 Vylestem Vines"),
            useClientPin = true,
        },
        {
            id = "note-leave-the-dungeon",
            kind = "note",
            priority = 30,
            conditions = { level = { min = 45 } },
            text = "Leave the dungeon.",
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 31,
            conditions = { level = { min = 45 } },
            text = "Click Here to Continue.",
        },
        {
            id = "boss-maraudos",
            kind = "note",
            priority = 32,
            conditions = { level = { min = 45 } },
            text = "Kill Maraudos. Use it on the Spirit of Maraudos. He walks around The Wicked Grotto in the Purple side of Maraudon.",
            dependsOn = { "boss-noxxious-scion" },
        },
        {
            id = "objective-7067-1-amulet-of-union",
            kind = "objective",
            priority = 33,
            conditions = { level = { min = 39 } },
            text = "Collect Amulet of Union.",
            dependsOn = { "accept-7067-the-pariah-s-instructions" },
            complete = QuestState(7067, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-lord-vyletongue",
            kind = "note",
            priority = 34,
            conditions = { level = { min = 45 } },
            text = "Kill Lord Vyletongue. He is Purple side of Maraudon. Proceed through The Wicked Grotto and enter the Vyletongue Seat. He is in a small room on the northern side.",
            dependsOn = { "boss-maraudos" },
        },
        {
            id = "objective-7044-1-celebrian-diamond",
            kind = "objective",
            priority = 35,
            conditions = { level = { min = 41 } },
            text = "Collect Celebrian Diamond.",
            dependsOn = { "accept-7044-legend-of-maraudon-goto-desolace-38-76-58" },
            complete = QuestObjective(7044, 1, "Celebrian Diamond"),
            useClientPin = true,
        },
        {
            id = "boss-celebras-the-cursed",
            kind = "note",
            priority = 36,
            conditions = { level = { min = 45 } },
            text = "Kill Celebras the Cursed. He is Purple side of Maraudon. Continue through the Vyletongue Seat and into the Poison Falls. Once you reach the Poison Falls, continue working your way west and then south, where he will be on a small island.",
            dependsOn = { "boss-lord-vyletongue" },
        },
        {
            id = "turnin-7044-legend-of-maraudon",
            kind = "turnin",
            priority = 37,
            conditions = { level = { min = 41 } },
            text = "Turn in Legend of Maraudon to Celebras the Redeemed.",
            dependsOn = { "objective-7044-2-celebrian-rod", "objective-7044-1-celebrian-diamond" },
            complete = QuestState(7044, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-7046-the-scepter-of-celebras",
            kind = "accept",
            priority = 38,
            conditions = { level = { min = 41 } },
            text = "Accept The Scepter of Celebras from Celebras the Redeemed.",
            dependsOn = { "turnin-7044-legend-of-maraudon" },
            complete = QuestState(7046, "activeOrCompleted"),
        },
        {
            id = "note-click-incantations-of-celebras",
            kind = "note",
            priority = 39,
            conditions = { level = { min = 45 } },
            text = "Click Incantations of Celebras.",
        },
        {
            id = "objective-7046-1-create-the-scepter-of-ce",
            kind = "objective",
            priority = 40,
            conditions = { level = { min = 41 } },
            text = "Create the Scepter of Celebras.",
            dependsOn = { "accept-7046-the-scepter-of-celebras" },
            complete = QuestState(7046, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-7046-the-scepter-of-celebras",
            kind = "turnin",
            priority = 41,
            conditions = { level = { min = 41 } },
            text = "Turn in The Scepter of Celebras to Celebras the Redeemed.",
            dependsOn = { "objective-7046-1-create-the-scepter-of-ce" },
            complete = QuestState(7046, "completed"),
            useClientPin = true,
        },
        {
            id = "objective-7065-1-princess-theradras",
            kind = "objective",
            priority = 42,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 45 } } } },
            text = "Kill Princess Theradras.",
            dependsOn = { "accept-7065-corruption-of-earth-and-seed" },
            complete = QuestState(7065, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-7066-seed-of-life",
            kind = "accept",
            priority = 43,
            conditions = { level = { min = 39 } },
            text = "Accept Seed of Life from Zaetar's Spirit.",
            complete = QuestState(7066, "activeOrCompleted"),
        },
        {
            id = "boss-enemies-around-this-area",
            kind = "note",
            priority = 44,
            conditions = { level = { min = 45 } },
            text = "Kill enemies around this area. These drop from enemies inside of Maraudon.",
            dependsOn = { "boss-celebras-the-cursed" },
        },
        {
            id = "objective-7028-1-theradric-crystal-carvin",
            kind = "objective",
            priority = 45,
            conditions = { level = { min = 41 } },
            text = "Collect 15 Theradric Crystal Carving.",
            dependsOn = { "accept-7028-twisted-evils" },
            complete = QuestState(7028, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-7067-the-pariah-s-instructions",
            kind = "turnin",
            priority = 46,
            conditions = { level = { min = 39 } },
            text = "Turn in The Pariah's Instructions to Centuar Pariah.",
            dependsOn = { "objective-7067-1-amulet-of-union" },
            complete = QuestState(7067, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.515, 0.874, "Centuar Pariah", "Travel to Desolace."),
            },
        },
        {
            id = "turnin-7028-twisted-evils",
            kind = "turnin",
            priority = 47,
            conditions = { level = { min = 41 } },
            text = "Turn in Twisted Evils to Willow.",
            dependsOn = { "objective-7028-1-theradric-crystal-carvin" },
            complete = QuestState(7028, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.622, 0.396, "Willow", "Travel to Desolace."),
            },
        },
        {
            id = "turnin-7041-vyletongue-corruption",
            kind = "turnin",
            priority = 48,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Turn in Vyletongue Corruption to Talendria.",
            dependsOn = { "objective-7041-2-filled-cerulean-vial", "objective-7041-1-heal-8-vylestem-vines" },
            complete = QuestState(7041, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.685, 0.089, "Talendria", "Travel to Desolace."),
            },
        },
        {
            id = "turnin-7065-corruption-of-earth-and-seed",
            kind = "turnin",
            priority = 49,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 45 } } } },
            text = "Turn in Corruption of Earth and Seed to Keeper Marandis.",
            dependsOn = { "objective-7065-1-princess-theradras" },
            complete = QuestState(7065, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.638, 0.107, "Keeper Marandis", "Travel to Desolace."),
            },
        },
        {
            id = "turnin-7070-shadowshard-fragments",
            kind = "turnin",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 39 } } } },
            text = "Turn in Shadowshard Fragments to Archmage Tervosh.",
            dependsOn = { "objective-7070-1-shadowshard-fragment" },
            complete = QuestState(7070, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.664, 0.493, "Archmage Tervosh", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "turnin-7066-seed-of-life",
            kind = "turnin",
            priority = 51,
            conditions = { level = { min = 39 } },
            text = "Turn in Seed of Life to Keeper Remulos.",
            dependsOn = { "accept-7066-seed-of-life" },
            complete = QuestState(7066, "completed"),
            route = {
                Point(MAP.MOONGLADE, 0.362, 0.418, "Keeper Remulos", "Travel to Moonglade."),
            },
        },
        {
            id = "accept-7068-shadowshard-fragments",
            kind = "accept",
            priority = 52,
            conditions = { all = { { faction = "Horde" }, { level = { min = 39 } } } },
            text = "Accept Shadowshard Fragments from Uthel'nay.",
            complete = QuestState(7068, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.392, 0.863, "Uthel'nay", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-7029-vyletongue-corruption",
            kind = "accept",
            priority = 53,
            conditions = { all = { { faction = "Horde" }, { level = { min = 41 } } } },
            text = "Accept Vyletongue Corruption from Vark Battlescar.",
            complete = QuestState(7029, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.232, 0.703, "Vark Battlescar", "Travel to Desolace."),
            },
        },
        {
            id = "accept-7064-corruption-of-earth-and-seed",
            kind = "accept",
            priority = 54,
            conditions = { all = { { faction = "Horde" }, { level = { min = 45 } } } },
            text = "Accept Corruption of Earth and Seed from Selendra.",
            complete = QuestState(7064, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.269, 0.777, "Selendra", "Travel to Desolace."),
            },
        },
        {
            id = "objective-7068-1-shadowshard-fragment",
            kind = "objective",
            priority = 55,
            conditions = { all = { { faction = "Horde" }, { level = { min = 39 } } } },
            text = "Collect 10 Shadowshard Fragment.",
            dependsOn = { "accept-7068-shadowshard-fragments" },
            complete = QuestState(7068, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.283, 0.545, "Desolace", "Travel to Desolace."),
            },
        },
        {
            id = "objective-7029-2-filled-cerulean-vial",
            kind = "objective",
            priority = 56,
            conditions = { all = { { faction = "Horde" }, { level = { min = 41 } } } },
            text = "Collect Filled Cerulean Vial.",
            dependsOn = { "accept-7029-vyletongue-corruption" },
            complete = QuestObjective(7029, 2, "Filled Cerulean Vial"),
            route = {
                Point(MAP.DESOLACE, 0.389, 0.584, "Desolace", "Travel to Desolace."),
            },
        },
        {
            id = "objective-7029-1-heal-8-vylestem-vines",
            kind = "objective",
            priority = 57,
            conditions = { all = { { faction = "Horde" }, { level = { min = 41 } } } },
            text = "Heal 8 Vylestem Vines.",
            dependsOn = { "accept-7029-vyletongue-corruption" },
            complete = QuestObjective(7029, 1, "Heal 8 Vylestem Vines"),
            useClientPin = true,
        },
        {
            id = "objective-7064-1-princess-theradras",
            kind = "objective",
            priority = 58,
            conditions = { all = { { faction = "Horde" }, { level = { min = 45 } } } },
            text = "Kill Princess Theradras.",
            dependsOn = { "accept-7064-corruption-of-earth-and-seed" },
            complete = QuestState(7064, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-7068-shadowshard-fragments",
            kind = "turnin",
            priority = 59,
            conditions = { all = { { faction = "Horde" }, { level = { min = 39 } } } },
            text = "Turn in Shadowshard Fragments to Uthel'nay.",
            dependsOn = { "objective-7068-1-shadowshard-fragment" },
            complete = QuestState(7068, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.392, 0.863, "Uthel'nay", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-7029-vyletongue-corruption",
            kind = "turnin",
            priority = 60,
            conditions = { all = { { faction = "Horde" }, { level = { min = 41 } } } },
            text = "Turn in Vyletongue Corruption to Vark Battlescar.",
            dependsOn = { "objective-7029-2-filled-cerulean-vial", "objective-7029-1-heal-8-vylestem-vines" },
            complete = QuestState(7029, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.232, 0.703, "Vark Battlescar", "Travel to Desolace."),
            },
        },
        {
            id = "turnin-7064-corruption-of-earth-and-seed",
            kind = "turnin",
            priority = 61,
            conditions = { all = { { faction = "Horde" }, { level = { min = 45 } } } },
            text = "Turn in Corruption of Earth and Seed to Selendra.",
            dependsOn = { "objective-7064-1-princess-theradras" },
            complete = QuestState(7064, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.269, 0.777, "Selendra", "Travel to Desolace."),
            },
        },
    },
})
