local _, ns = ...

local MAP = {
    BURNING_STEPPES = 1428,
    REDRIDGE_MOUNTAINS = 1433,
    STORMWIND_CITY = 1453,
    SEARING_GORGE = 1427,
    WINTERSPRING = 1452,
    BADLANDS = 1418,
    ORGRIMMAR = 1454,
    WESTERN_PLAGUELANDS = 1422,
    DUSTWALLOW_MARSH = 1445,
    TANARIS = 1446,
    SWAMP_OF_SORROWS = 1435,
    WETLANDS = 1437,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-onyxia-s-lair-attunement",
    title = "Onyxia's Lair Attunement",
    category = "Raid Quests",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 48 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-4182-dragonkin-menace",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Accept Dragonkin Menace from Helendis Riverhorn.",
            complete = QuestState(4182, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.690, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-1-black-broodling",
            kind = "objective",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Kill 15 Black Broodling.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 1, "Black Broodling"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.892, 0.538, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-2-black-dragonspawn",
            kind = "objective",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Kill 10 Black Dragonspawn.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 2, "Black Dragonspawn"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.920, 0.538, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-3-black-drake",
            kind = "objective",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Kill 1 Black Drake.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 3, "Black Drake"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.892, 0.538, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-4-black-wyrmkin",
            kind = "objective",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Kill 4 Black Wyrmkin.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 4, "Black Wyrmkin"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.920, 0.538, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4182-dragonkin-menace",
            kind = "turnin",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Turn in Dragonkin Menace to Helendis Riverhorn.",
            dependsOn = { "objective-4182-1-black-broodling", "objective-4182-2-black-dragonspawn", "objective-4182-3-black-drake", "objective-4182-4-black-wyrmkin" },
            complete = QuestState(4182, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.690, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4183-the-true-masters",
            kind = "accept",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Accept The True Masters from Helendis Riverhorn.",
            dependsOn = { "turnin-4182-dragonkin-menace" },
            complete = QuestState(4183, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.690, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4183-the-true-masters",
            kind = "turnin",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Turn in The True Masters to Magistrate Solomon.",
            dependsOn = { "accept-4183-the-true-masters" },
            complete = QuestState(4183, "completed"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "accept-4184-the-true-masters",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Accept The True Masters from Magistrate Solomon.",
            dependsOn = { "turnin-4183-the-true-masters" },
            complete = QuestState(4184, "activeOrCompleted"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "turnin-4184-the-true-masters",
            kind = "turnin",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Turn in The True Masters to Highlord Bolvar Fordragon.",
            dependsOn = { "accept-4184-the-true-masters" },
            complete = QuestState(4184, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-4185-the-true-masters",
            kind = "accept",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Accept The True Masters from Highlord Bolvar Fordragon.",
            dependsOn = { "turnin-4184-the-true-masters" },
            complete = QuestState(4185, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "objective-4185-1-receive-advice-from-lady",
            kind = "gossip",
            priority = 21,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Talk to Lady Katrana Prestor. 'Pardon the intrusion, Lady Prestor, but Highlord Bolvar suggested that I seek your advice.' Receive Advice From Lady Prestor.",
            dependsOn = { "accept-4185-the-true-masters" },
            complete = QuestState(4185, "complete"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.781, 0.177, "Stormwind City", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4185-the-true-masters",
            kind = "turnin",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Turn in The True Masters to Highlord Bolvar Fordragon.",
            dependsOn = { "objective-4185-1-receive-advice-from-lady" },
            complete = QuestState(4185, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-4186-the-true-masters",
            kind = "accept",
            priority = 23,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Accept The True Masters from Highlord Bolvar Fordragon.",
            dependsOn = { "turnin-4185-the-true-masters" },
            complete = QuestState(4186, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4186-the-true-masters",
            kind = "turnin",
            priority = 24,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Turn in The True Masters to Magistrate Solomon.",
            dependsOn = { "accept-4186-the-true-masters" },
            complete = QuestState(4186, "completed"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "accept-4223-the-true-masters",
            kind = "accept",
            priority = 25,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Accept The True Masters from Magistrate Solomon.",
            dependsOn = { "turnin-4186-the-true-masters" },
            complete = QuestState(4223, "activeOrCompleted"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "turnin-4223-the-true-masters",
            kind = "turnin",
            priority = 26,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Turn in The True Masters to Marshal Maxwell.",
            dependsOn = { "accept-4223-the-true-masters" },
            complete = QuestState(4223, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4224-the-true-masters",
            kind = "accept",
            priority = 27,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Accept The True Masters from Marshal Maxwell.",
            dependsOn = { "turnin-4223-the-true-masters" },
            complete = QuestState(4224, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4224-1-hear-ragged-john-s-story",
            kind = "gossip",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Talk to Ragged John. 'Official business, John. I need some information about Marshal Windsor. Tell me about the last time you saw him.' Hear Ragged John's Story.",
            dependsOn = { "accept-4224-the-true-masters" },
            complete = QuestState(4224, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4224-the-true-masters",
            kind = "turnin",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 56 } } } },
            text = "Turn in The True Masters to Marshal Maxwell.",
            dependsOn = { "objective-4224-1-hear-ragged-john-s-story" },
            complete = QuestState(4224, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4241-marshal-windsor",
            kind = "accept",
            priority = 30,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Marshal Windsor from Marshal Maxwell.",
            dependsOn = { "turnin-4224-the-true-masters" },
            complete = QuestState(4241, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 31,
            conditions = { level = { min = 48 } },
            text = "Enter Blackrock Depths with your group.",
            dependsOn = { "accept-4182-dragonkin-menace", "accept-4183-the-true-masters", "accept-4184-the-true-masters", "accept-4185-the-true-masters", "accept-4186-the-true-masters", "accept-4223-the-true-masters", "accept-4224-the-true-masters", "accept-4241-marshal-windsor" },
            route = {
                Point(MAP.SEARING_GORGE, 0.372, 0.944, "Onyxia's Lair Attunement entrance", "Travel to Searing Gorge."),
            },
        },
        {
            id = "turnin-4241-marshal-windsor",
            kind = "turnin",
            priority = 33,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Marshal Windsor to Marshal Windsor.",
            dependsOn = { "accept-4241-marshal-windsor" },
            complete = QuestState(4241, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4242-abandoned-hope",
            kind = "accept",
            priority = 34,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Abandoned Hope from Marshal Windsor.",
            dependsOn = { "turnin-4241-marshal-windsor" },
            complete = QuestState(4242, "activeOrCompleted"),
        },
        {
            id = "turnin-4242-abandoned-hope",
            kind = "turnin",
            priority = 35,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Abandoned Hope to Marshal Maxwell.",
            dependsOn = { "accept-4242-abandoned-hope" },
            complete = QuestState(4242, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4264-a-crumpled-up-note",
            kind = "accept",
            priority = 38,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept A Crumpled Up Note.",
            complete = QuestState(4264, "activeOrCompleted"),
        },
        {
            id = "turnin-4264-a-crumpled-up-note",
            kind = "turnin",
            priority = 39,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in A Crumpled Up Note to Marshal Windsor.",
            dependsOn = { "accept-4264-a-crumpled-up-note" },
            complete = QuestState(4264, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4282-a-shred-of-hope",
            kind = "accept",
            priority = 40,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept A Shred of Hope from Marshal Windsor.",
            dependsOn = { "turnin-4264-a-crumpled-up-note" },
            complete = QuestState(4282, "activeOrCompleted"),
        },
        {
            id = "objective-4282-1-marshal-windsor-s-lost-i",
            kind = "objective",
            priority = 42,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect Marshal Windsor's Lost Information.",
            dependsOn = { "accept-4282-a-shred-of-hope" },
            complete = QuestObjective(4282, 1, "Marshal Windsor's Lost Information"),
            useClientPin = true,
        },
        {
            id = "objective-4282-2-marshal-windsor-s-lost-i",
            kind = "objective",
            priority = 44,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect Marshal Windsor's Lost Information.",
            dependsOn = { "accept-4282-a-shred-of-hope" },
            complete = QuestObjective(4282, 2, "Marshal Windsor's Lost Information"),
            useClientPin = true,
        },
        {
            id = "turnin-4282-a-shred-of-hope",
            kind = "turnin",
            priority = 45,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in A Shred of Hope to Marshal Windsor.",
            dependsOn = { "objective-4282-1-marshal-windsor-s-lost-i", "objective-4282-2-marshal-windsor-s-lost-i" },
            complete = QuestState(4282, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4322-jail-break",
            kind = "accept",
            priority = 46,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Jail Break! from Marshal Windsor.",
            dependsOn = { "turnin-4282-a-shred-of-hope" },
            complete = QuestState(4322, "activeOrCompleted"),
        },
        {
            id = "objective-4322-1-jail-break",
            kind = "objective",
            priority = 47,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Jail Break!",
            dependsOn = { "accept-4322-jail-break" },
            complete = QuestState(4322, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4322-jail-break",
            kind = "turnin",
            priority = 48,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Jail Break! to Marshal Maxwell.",
            dependsOn = { "objective-4322-1-jail-break" },
            complete = QuestState(4322, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-6402-stormwind-rendezvous",
            kind = "accept",
            priority = 49,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Stormwind Rendezvous from Marshal Maxwell.",
            dependsOn = { "turnin-4322-jail-break" },
            complete = QuestState(6402, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-6402-stormwind-rendezvous",
            kind = "turnin",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Stormwind Rendezvous to Reginald Windsor.",
            dependsOn = { "accept-6402-stormwind-rendezvous" },
            complete = QuestState(6402, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.705, 0.851, "Reginald Windsor", "Travel to Stormwind City."),
                Point(MAP.STORMWIND_CITY, 0.697, 0.861, "Reginald Windsor", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-6403-the-great-masquerade",
            kind = "accept",
            priority = 51,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Great Masquerade from Reginald Windsor.",
            dependsOn = { "turnin-6402-stormwind-rendezvous" },
            complete = QuestState(6403, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.697, 0.861, "Reginald Windsor", "Travel to Stormwind City."),
            },
        },
        {
            id = "objective-6403-1-complete-reginald-windso",
            kind = "objective",
            priority = 53,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Complete Reginald Windsor's March.",
            dependsOn = { "accept-6403-the-great-masquerade" },
            complete = QuestState(6403, "complete"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.781, 0.179, "Stormwind City", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-6403-the-great-masquerade",
            kind = "turnin",
            priority = 54,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Great Masquerade to Highlord Bolvar Fordragon.",
            dependsOn = { "objective-6403-1-complete-reginald-windso" },
            complete = QuestState(6403, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-6501-the-dragon-s-eye",
            kind = "accept",
            priority = 55,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Dragon's Eye from Highlord Bolvar Fordragon.",
            dependsOn = { "turnin-6403-the-great-masquerade" },
            complete = QuestState(6501, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-6501-the-dragon-s-eye",
            kind = "turnin",
            priority = 56,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Dragon's Eye to Haleh.",
            dependsOn = { "accept-6501-the-dragon-s-eye" },
            complete = QuestState(6501, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-6502-drakefire-amulet",
            kind = "accept",
            priority = 57,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Drakefire Amulet from Haleh.",
            dependsOn = { "turnin-6501-the-dragon-s-eye" },
            complete = QuestState(6502, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "objective-6502-1-blood-of-the-black-drago",
            kind = "objective",
            priority = 59,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect Blood of the Black Dragon Champion.",
            dependsOn = { "accept-6502-drakefire-amulet" },
            complete = QuestState(6502, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-6502-drakefire-amulet",
            kind = "turnin",
            priority = 60,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Drakefire Amulet to Haleh.",
            dependsOn = { "objective-6502-1-blood-of-the-black-drago" },
            complete = QuestState(6502, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-4903-warlord-s-command",
            kind = "accept",
            priority = 62,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Warlord's Command.",
            complete = QuestState(4903, "activeOrCompleted"),
        },
        {
            id = "objective-4903-2-highlord-omokk",
            kind = "objective",
            priority = 63,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Highlord Omokk.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 2, "Highlord Omokk"),
            useClientPin = true,
        },
        {
            id = "objective-4903-3-war-master-voone",
            kind = "objective",
            priority = 64,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill War Master Voone.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 3, "War Master Voone"),
            useClientPin = true,
        },
        {
            id = "objective-4903-1-overlord-wyrmthalak",
            kind = "objective",
            priority = 65,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Overlord Wyrmthalak.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 1, "Overlord Wyrmthalak"),
            useClientPin = true,
        },
        {
            id = "objective-4903-4-important-blackrock-docu",
            kind = "objective",
            priority = 67,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Important Blackrock Documents.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 4, "Important Blackrock Documents"),
            useClientPin = true,
        },
        {
            id = "turnin-4903-warlord-s-command",
            kind = "turnin",
            priority = 68,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Warlord's Command to Warlord Goretooth.",
            dependsOn = { "objective-4903-2-highlord-omokk", "objective-4903-3-war-master-voone", "objective-4903-1-overlord-wyrmthalak", "objective-4903-4-important-blackrock-docu" },
            complete = QuestState(4903, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4941-eitrigg-s-wisdom",
            kind = "accept",
            priority = 69,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Eitrigg's Wisdom from Warlord Goretooth.",
            dependsOn = { "turnin-4903-warlord-s-command" },
            complete = QuestState(4941, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "objective-4941-1-council-with-eitrigg",
            kind = "gossip",
            priority = 70,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Talk to Eitrigg. 'Hello, Eitrigg. I bring news back from Blackrock Spire.' Council with Eitrigg.",
            dependsOn = { "accept-4941-eitrigg-s-wisdom" },
            complete = QuestState(4941, "complete"),
            route = {
                Point(MAP.ORGRIMMAR, 0.343, 0.394, "Orgrimmar", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-4941-eitrigg-s-wisdom",
            kind = "turnin",
            priority = 71,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Eitrigg's Wisdom to Thrall.",
            dependsOn = { "objective-4941-1-council-with-eitrigg" },
            complete = QuestState(4941, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-4974-for-the-horde",
            kind = "accept",
            priority = 72,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept For The Horde! from Thrall.",
            dependsOn = { "turnin-4941-eitrigg-s-wisdom" },
            complete = QuestState(4974, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "objective-4974-1-head-of-rend-blackhand",
            kind = "objective",
            priority = 74,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Head of Rend Blackhand.",
            dependsOn = { "accept-4974-for-the-horde" },
            complete = QuestState(4974, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4974-for-the-horde",
            kind = "turnin",
            priority = 75,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in For The Horde! to Thrall.",
            dependsOn = { "objective-4974-1-head-of-rend-blackhand" },
            complete = QuestState(4974, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-6566-what-the-wind-carries",
            kind = "accept",
            priority = 76,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept What the Wind Carries from Thrall.",
            dependsOn = { "turnin-4974-for-the-horde" },
            complete = QuestState(6566, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "objective-6566-1-listen-to-thrall-s-tale",
            kind = "gossip",
            priority = 77,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Talk to Thrall. 'Please share your wisdom with me, Warchief.' Listen to Thrall's Tale.",
            dependsOn = { "accept-6566-what-the-wind-carries" },
            complete = QuestState(6566, "complete"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Orgrimmar", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-6566-what-the-wind-carries",
            kind = "turnin",
            priority = 78,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in What the Wind Carries to Thrall.",
            dependsOn = { "objective-6566-1-listen-to-thrall-s-tale" },
            complete = QuestState(6566, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-6567-the-champion-of-the-horde",
            kind = "accept",
            priority = 79,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Champion of the Horde from Thrall.",
            dependsOn = { "turnin-6566-what-the-wind-carries" },
            complete = QuestState(6567, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-6567-the-champion-of-the-horde",
            kind = "turnin",
            priority = 80,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Champion of the Horde to Rexxar.",
            dependsOn = { "accept-6567-the-champion-of-the-horde" },
            complete = QuestState(6567, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-6568-the-testament-of-rexxar",
            kind = "accept",
            priority = 81,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Testament of Rexxar from Rexxar.",
            complete = QuestState(6568, "activeOrCompleted"),
        },
        {
            id = "turnin-6568-the-testament-of-rexxar",
            kind = "turnin",
            priority = 82,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Testament of Rexxar to Myranda the Hag.",
            dependsOn = { "accept-6568-the-testament-of-rexxar" },
            complete = QuestState(6568, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.508, 0.778, "Myranda the Hag", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-6569-oculus-illusions",
            kind = "accept",
            priority = 83,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Oculus Illusions from Myranda the Hag.",
            dependsOn = { "turnin-6568-the-testament-of-rexxar" },
            complete = QuestState(6569, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.508, 0.778, "Myranda the Hag", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-6569-1-black-dragonspawn-eye",
            kind = "objective",
            priority = 85,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect 20 Black Dragonspawn Eye.",
            dependsOn = { "accept-6569-oculus-illusions" },
            complete = QuestState(6569, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-6569-oculus-illusions",
            kind = "turnin",
            priority = 86,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Oculus Illusions to Myranda the Hag.",
            dependsOn = { "objective-6569-1-black-dragonspawn-eye" },
            complete = QuestState(6569, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.508, 0.778, "Myranda the Hag", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-6570-emberstrife",
            kind = "accept",
            priority = 87,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Emberstrife from Myranda the Hag.",
            dependsOn = { "turnin-6569-oculus-illusions" },
            complete = QuestState(6570, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.508, 0.778, "Myranda the Hag", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-6570-emberstrife",
            kind = "turnin",
            priority = 88,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Emberstrife to Emberstrife.",
            dependsOn = { "accept-6570-emberstrife" },
            complete = QuestState(6570, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6582-the-test-of-skulls-scryer",
            kind = "accept",
            priority = 89,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Test of Skulls, Scryer from Emberstrife.",
            dependsOn = { "turnin-6570-emberstrife" },
            complete = QuestState(6582, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6583-the-test-of-skulls-somnus",
            kind = "accept",
            priority = 90,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Test of Skulls, Somnus from Emberstrife.",
            complete = QuestState(6583, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6584-the-test-of-skulls-chronalis",
            kind = "accept",
            priority = 91,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Test of Skulls, Chronalis from Emberstrife.",
            complete = QuestState(6584, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "objective-6584-1-the-skull-of-chronalis",
            kind = "objective",
            priority = 93,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect The Skull of Chronalis.",
            dependsOn = { "accept-6584-the-test-of-skulls-chronalis" },
            complete = QuestState(6584, "complete"),
            route = {
                Point(MAP.TANARIS, 0.641, 0.487, "Tanaris", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-6582-1-the-skull-of-scryer",
            kind = "objective",
            priority = 95,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect The Skull of Scryer.",
            dependsOn = { "accept-6582-the-test-of-skulls-scryer" },
            complete = QuestState(6582, "complete"),
            route = {
                Point(MAP.WINTERSPRING, 0.529, 0.561, "Winterspring", "Travel to Winterspring."),
            },
        },
        {
            id = "objective-6583-1-the-skull-of-somnus",
            kind = "objective",
            priority = 97,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect The Skull of Somnus.",
            dependsOn = { "accept-6583-the-test-of-skulls-somnus" },
            complete = QuestState(6583, "complete"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.804, 0.684, "Swamp of Sorrows", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-6582-the-test-of-skulls-scryer",
            kind = "turnin",
            priority = 98,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Test of Skulls, Scryer to Emberstrife.",
            dependsOn = { "objective-6582-1-the-skull-of-scryer" },
            complete = QuestState(6582, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "turnin-6583-the-test-of-skulls-somnus",
            kind = "turnin",
            priority = 99,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Test of Skulls, Somnus to Emberstrife.",
            dependsOn = { "objective-6583-1-the-skull-of-somnus" },
            complete = QuestState(6583, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "turnin-6584-the-test-of-skulls-chronalis",
            kind = "turnin",
            priority = 100,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Test of Skulls, Chronalis to Emberstrife.",
            dependsOn = { "objective-6584-1-the-skull-of-chronalis" },
            complete = QuestState(6584, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6585-the-test-of-skulls-axtroz",
            kind = "accept",
            priority = 101,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Test of Skulls, Axtroz from Emberstrife.",
            dependsOn = { "turnin-6584-the-test-of-skulls-chronalis" },
            complete = QuestState(6585, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "objective-6585-1-the-skull-of-axtroz",
            kind = "objective",
            priority = 103,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect The Skull of Axtroz.",
            dependsOn = { "accept-6585-the-test-of-skulls-axtroz" },
            complete = QuestState(6585, "complete"),
            route = {
                Point(MAP.WETLANDS, 0.828, 0.489, "Wetlands", "Travel to Wetlands."),
            },
        },
        {
            id = "turnin-6585-the-test-of-skulls-axtroz",
            kind = "turnin",
            priority = 104,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Test of Skulls, Axtroz to Emberstrife.",
            dependsOn = { "objective-6585-1-the-skull-of-axtroz" },
            complete = QuestState(6585, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6601-ascension",
            kind = "accept",
            priority = 105,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Ascension from Emberstrife.",
            dependsOn = { "turnin-6585-the-test-of-skulls-axtroz" },
            complete = QuestState(6601, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "turnin-6601-ascension",
            kind = "turnin",
            priority = 106,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Ascension to Rexxar.",
            dependsOn = { "accept-6601-ascension" },
            complete = QuestState(6601, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-6602-blood-of-the-black-dragon-champion",
            kind = "accept",
            priority = 107,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Blood of the Black Dragon Champion from Rexxar.",
            complete = QuestState(6602, "activeOrCompleted"),
        },
        {
            id = "objective-6602-1-blood-of-the-black-drago",
            kind = "objective",
            priority = 108,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Blood of the Black Dragon Champion.",
            dependsOn = { "accept-6602-blood-of-the-black-dragon-champion" },
            complete = QuestState(6602, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-6602-blood-of-the-black-dragon-champion",
            kind = "turnin",
            priority = 109,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Blood of the Black Dragon Champion to Rexxar.",
            dependsOn = { "objective-6602-1-blood-of-the-black-drago" },
            complete = QuestState(6602, "completed"),
            useClientPin = true,
        },
    },
})
