local _, ns = ...

local MAP = {
    STORMWIND_CITY = 1453,
    DESOLACE = 1443,
    HILLSBRAD_FOOTHILLS = 1424,
    IRONFORGE = 1455,
    THUNDER_BLUFF = 1456,
    THOUSAND_NEEDLES = 1441,
    STONETALON_MOUNTAINS = 1442,
    ASHENVALE = 1440,
    UNDERCITY = 1458,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-scarlet-monastery-library",
    title = "Scarlet Monastery (Library)",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 28 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-6141-brother-anton",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 34 } } } },
            text = "Accept Brother Anton from Brother Crowley.",
            complete = QuestState(6141, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.426, 0.242, "Brother Crowley", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-6141-brother-anton",
            kind = "turnin",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 34 } } } },
            text = "Turn in Brother Anton to Brother Anton.",
            dependsOn = { "accept-6141-brother-anton" },
            complete = QuestState(6141, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.665, 0.079, "Brother Anton", "Travel to Desolace."),
            },
        },
        {
            id = "accept-261-down-the-scarlet-path",
            kind = "accept",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Down the Scarlet Path from Brother Anton.",
            dependsOn = { "turnin-6141-brother-anton" },
            complete = QuestState(261, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.665, 0.079, "Brother Anton", "Travel to Desolace."),
            },
        },
        {
            id = "objective-261-1-undead-ravager",
            kind = "objective",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Kill 30 Undead Ravager.",
            dependsOn = { "accept-261-down-the-scarlet-path" },
            complete = QuestState(261, "complete"),
            route = {
                Point(MAP.DESOLACE, 0.641, 0.916, "Desolace", "Travel to Desolace."),
            },
        },
        {
            id = "turnin-261-down-the-scarlet-path",
            kind = "turnin",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Down the Scarlet Path to Brother Anton.",
            dependsOn = { "objective-261-1-undead-ravager" },
            complete = QuestState(261, "completed"),
            route = {
                Point(MAP.DESOLACE, 0.665, 0.079, "Brother Anton", "Travel to Desolace."),
            },
        },
        {
            id = "accept-1052-down-the-scarlet-path",
            kind = "accept",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Down the Scarlet Path from Brother Anton.",
            dependsOn = { "turnin-261-down-the-scarlet-path" },
            complete = QuestState(1052, "activeOrCompleted"),
            route = {
                Point(MAP.DESOLACE, 0.665, 0.079, "Brother Anton", "Travel to Desolace."),
            },
        },
        {
            id = "turnin-1052-down-the-scarlet-path",
            kind = "turnin",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Down the Scarlet Path to Raleigh the Devout.",
            dependsOn = { "accept-1052-down-the-scarlet-path" },
            complete = QuestState(1052, "completed"),
            route = {
                Point(MAP.HILLSBRAD_FOOTHILLS, 0.515, 0.584, "Raleigh the Devout", "Travel to Hillsbrad Foothills."),
            },
        },
        {
            id = "accept-1053-in-the-name-of-the-light",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept In the Name of the Light from Raleigh the Devout.",
            dependsOn = { "turnin-1052-down-the-scarlet-path" },
            complete = QuestState(1053, "activeOrCompleted"),
            route = {
                Point(MAP.HILLSBRAD_FOOTHILLS, 0.515, 0.584, "Raleigh the Devout", "Travel to Hillsbrad Foothills."),
            },
        },
        {
            id = "accept-1050-mythology-of-the-titans",
            kind = "accept",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Mythology of the Titans from Librarian Mae Paledust.",
            complete = QuestState(1050, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.750, 0.125, "Librarian Mae Paledust", "Travel to Ironforge."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 20,
            conditions = { level = { min = 34 } },
            text = "Enter Scarlet Monastery - Library with your group.",
            dependsOn = { "accept-6141-brother-anton", "accept-261-down-the-scarlet-path", "accept-1052-down-the-scarlet-path", "accept-1053-in-the-name-of-the-light", "accept-1050-mythology-of-the-titans" },
            persistCompletion = true,
            complete = { instance = 189 },
        },
        {
            id = "objective-1053-4-houndmaster-loksey",
            kind = "objective",
            priority = 23,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Kill Houndmaster Loksey in the Library wing and loot proof for In the Name of the Light.",
            dependsOn = { "accept-1053-in-the-name-of-the-light" },
            complete = QuestState(1053, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-1050-1-mythology-of-the-titans",
            kind = "objective",
            priority = 25,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Loot Mythology of the Titans from a bookshelf in the Scarlet Monastery Library.",
            dependsOn = { "accept-1050-mythology-of-the-titans" },
            complete = QuestState(1050, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-1053-in-the-name-of-the-light",
            kind = "turnin",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in In the Name of the Light to Raleigh the Devout.",
            dependsOn = { "objective-1053-4-houndmaster-loksey" },
            complete = QuestState(1053, "completed"),
            route = {
                Point(MAP.HILLSBRAD_FOOTHILLS, 0.515, 0.584, "Raleigh the Devout", "Travel to Hillsbrad Foothills."),
            },
        },
        {
            id = "turnin-1050-mythology-of-the-titans",
            kind = "turnin",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Mythology of the Titans to Librarian Mae Paledust.",
            dependsOn = { "objective-1050-1-mythology-of-the-titans" },
            complete = QuestState(1050, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.750, 0.125, "Librarian Mae Paledust", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-1049-compendium-of-the-fallen",
            kind = "accept",
            priority = 30,
            conditions = { all = { { faction = "Horde" }, { race = { 2, 6, 8 } }, { level = { min = 39 } } } },
            text = "Accept Compendium of the Fallen from Sage Truthseeker.",
            complete = QuestState(1049, "activeOrCompleted"),
            route = {
                Point(MAP.THUNDER_BLUFF, 0.344, 0.469, "Sage Truthseeker", "Travel to Thunder Bluff."),
            },
        },
        {
            id = "accept-1149-test-of-faith",
            kind = "accept",
            priority = 31,
            conditions = { all = { { faction = "Horde" }, { level = { min = 28 } } } },
            text = "Accept Test of Faith from Dorn Plainstalker.",
            complete = QuestState(1149, "activeOrCompleted"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.539, 0.415, "Dorn Plainstalker", "Travel to Thousand Needles."),
            },
        },
        {
            id = "turnin-1149-test-of-faith",
            kind = "turnin",
            priority = 32,
            conditions = { all = { { faction = "Horde" }, { level = { min = 28 } } } },
            text = "Turn in Test of Faith to Dorn Plainstalker.",
            dependsOn = { "accept-1149-test-of-faith" },
            complete = QuestState(1149, "completed"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.539, 0.415, "Dorn Plainstalker", "Travel to Thousand Needles."),
            },
        },
        {
            id = "accept-1150-test-of-endurance",
            kind = "accept",
            priority = 33,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Accept Test of Endurance from Dorn Plainstalker.",
            dependsOn = { "turnin-1149-test-of-faith" },
            complete = QuestState(1150, "activeOrCompleted"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.539, 0.415, "Dorn Plainstalker", "Travel to Thousand Needles."),
            },
        },
        {
            id = "objective-1150-1-grenka-s-claw",
            kind = "objective",
            priority = 37,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Kill Grenka Bloodscreech in Thousand Needles and loot Grenka's Claw.",
            dependsOn = { "accept-1150-test-of-endurance" },
            complete = QuestState(1150, "complete"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.258, 0.548, "Thousand Needles", "Travel to Thousand Needles."),
            },
        },
        {
            id = "turnin-1150-test-of-endurance",
            kind = "turnin",
            priority = 38,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Turn in Test of Endurance to Dorn Plainstalker.",
            dependsOn = { "objective-1150-1-grenka-s-claw" },
            complete = QuestState(1150, "completed"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.539, 0.415, "Dorn Plainstalker", "Travel to Thousand Needles."),
            },
        },
        {
            id = "accept-1151-test-of-strength",
            kind = "accept",
            priority = 39,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Accept Test of Strength from Dorn Plainstalker.",
            dependsOn = { "turnin-1150-test-of-endurance" },
            complete = QuestState(1151, "activeOrCompleted"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.539, 0.415, "Dorn Plainstalker", "Travel to Thousand Needles."),
            },
        },
        {
            id = "objective-1151-1-fragments-of-rok-alim",
            kind = "objective",
            priority = 41,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Collect Fragments of Rok'Alim.",
            dependsOn = { "accept-1151-test-of-strength" },
            complete = QuestState(1151, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-1151-test-of-strength",
            kind = "turnin",
            priority = 42,
            conditions = { all = { { faction = "Horde" }, { level = { min = 25 } } } },
            text = "Turn in Test of Strength to Dorn Plainstalker.",
            dependsOn = { "objective-1151-1-fragments-of-rok-alim" },
            complete = QuestState(1151, "completed"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.539, 0.415, "Dorn Plainstalker", "Travel to Thousand Needles."),
            },
        },
        {
            id = "accept-1152-test-of-lore",
            kind = "accept",
            priority = 43,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Accept Test of Lore from Dorn Plainstalker.",
            dependsOn = { "turnin-1151-test-of-strength" },
            complete = QuestState(1152, "activeOrCompleted"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.539, 0.415, "Dorn Plainstalker", "Travel to Thousand Needles."),
            },
        },
        {
            id = "turnin-1152-test-of-lore",
            kind = "turnin",
            priority = 44,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Turn in Test of Lore to Braug Dimspirit.",
            dependsOn = { "accept-1152-test-of-lore" },
            complete = QuestState(1152, "completed"),
            route = {
                Point(MAP.STONETALON_MOUNTAINS, 0.788, 0.457, "Braug Dimspirit", "Travel to Stonetalon Mountains."),
            },
        },
        {
            id = "accept-1154-test-of-lore",
            kind = "accept",
            priority = 45,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Accept Test of Lore from Braug Dimspirit.",
            dependsOn = { "turnin-1152-test-of-lore" },
            complete = QuestState(1154, "activeOrCompleted"),
            route = {
                Point(MAP.STONETALON_MOUNTAINS, 0.788, 0.457, "Braug Dimspirit", "Travel to Stonetalon Mountains."),
            },
        },
        {
            id = "objective-1154-1-legacy-of-the-aspects",
            kind = "objective",
            priority = 47,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Loot Legacy of the Aspects from the tome in the Temple of Zul in Ashenvale.",
            dependsOn = { "accept-1154-test-of-lore" },
            complete = QuestState(1154, "complete"),
            route = {
                Point(MAP.ASHENVALE, 0.756, 0.744, "Ashenvale", "Travel to Ashenvale."),
            },
        },
        {
            id = "turnin-1154-test-of-lore",
            kind = "turnin",
            priority = 48,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Turn in Test of Lore to Braug Dimspirit.",
            dependsOn = { "objective-1154-1-legacy-of-the-aspects" },
            complete = QuestState(1154, "completed"),
            route = {
                Point(MAP.STONETALON_MOUNTAINS, 0.788, 0.457, "Braug Dimspirit", "Travel to Stonetalon Mountains."),
            },
        },
        {
            id = "accept-6627-test-of-lore",
            kind = "accept",
            priority = 49,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Accept Test of Lore from Braug Dimspirit.",
            dependsOn = { "turnin-1154-test-of-lore" },
            complete = QuestState(6627, "activeOrCompleted"),
            route = {
                Point(MAP.STONETALON_MOUNTAINS, 0.788, 0.457, "Braug Dimspirit", "Travel to Stonetalon Mountains."),
            },
        },
        {
            id = "objective-6627-1-answer-braug-dimspirit-s",
            kind = "gossip",
            priority = 50,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Talk to Braug Dimspirit. 'Neltharion is my answer.' Answer Braug Dimspirit's Question Correctly.",
            dependsOn = { "accept-6627-test-of-lore" },
            complete = QuestState(6627, "complete"),
            route = {
                Point(MAP.STONETALON_MOUNTAINS, 0.788, 0.457, "Stonetalon Mountains", "Travel to Stonetalon Mountains."),
            },
        },
        {
            id = "turnin-6627-test-of-lore",
            kind = "turnin",
            priority = 51,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Turn in Test of Lore to Braug Dimspirit.",
            dependsOn = { "objective-6627-1-answer-braug-dimspirit-s" },
            complete = QuestState(6627, "completed"),
            route = {
                Point(MAP.STONETALON_MOUNTAINS, 0.788, 0.457, "Braug Dimspirit", "Travel to Stonetalon Mountains."),
            },
        },
        {
            id = "accept-1159-test-of-lore",
            kind = "accept",
            priority = 52,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Accept Test of Lore from Braug Dimspirit.",
            dependsOn = { "turnin-6627-test-of-lore" },
            complete = QuestState(1159, "activeOrCompleted"),
            route = {
                Point(MAP.STONETALON_MOUNTAINS, 0.788, 0.457, "Braug Dimspirit", "Travel to Stonetalon Mountains."),
            },
        },
        {
            id = "turnin-1159-test-of-lore",
            kind = "turnin",
            priority = 53,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Turn in Test of Lore to Parqual Fintallas.",
            dependsOn = { "accept-1159-test-of-lore" },
            complete = QuestState(1159, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.578, 0.654, "Parqual Fintallas", "Travel to Undercity."),
            },
        },
        {
            id = "accept-1160-test-of-lore",
            kind = "accept",
            priority = 54,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Accept Test of Lore from Parqual Fintallas.",
            dependsOn = { "turnin-1159-test-of-lore" },
            complete = QuestState(1160, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.578, 0.654, "Parqual Fintallas", "Travel to Undercity."),
            },
        },
        {
            id = "accept-1048-into-the-scarlet-monastery",
            kind = "accept",
            priority = 55,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Accept Into The Scarlet Monastery from Varimathras.",
            complete = QuestState(1048, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.563, 0.922, "Varimathras", "Travel to Undercity."),
            },
        },
        {
            id = "objective-1048-4-houndmaster-loksey",
            kind = "objective",
            priority = 56,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Kill Houndmaster Loksey in the Library wing for Into the Scarlet Monastery.",
            dependsOn = { "accept-1048-into-the-scarlet-monastery" },
            complete = QuestState(1048, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-1160-1-beginnings-of-the-undead",
            kind = "objective",
            priority = 58,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Loot Beginnings of the Undead Threat from a bookshelf in the Scarlet Monastery Library.",
            dependsOn = { "accept-1160-test-of-lore" },
            complete = QuestState(1160, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-1049-1-compendium-of-the-fallen",
            kind = "objective",
            priority = 60,
            conditions = { all = { { faction = "Horde" }, { race = { 2, 6, 8 } }, { level = { min = 39 } } } },
            text = "Loot the Compendium of the Fallen from a bookshelf in the Scarlet Monastery Library.",
            dependsOn = { "accept-1049-compendium-of-the-fallen" },
            complete = QuestState(1049, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-1160-test-of-lore",
            kind = "turnin",
            priority = 62,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Turn in Test of Lore to Parqual Fintallas.",
            dependsOn = { "objective-1160-1-beginnings-of-the-undead" },
            complete = QuestState(1160, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.578, 0.654, "Parqual Fintallas", "Travel to Undercity."),
            },
        },
        {
            id = "accept-6628-test-of-lore",
            kind = "accept",
            priority = 63,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Accept Test of Lore from Parqual Fintallas.",
            dependsOn = { "turnin-1160-test-of-lore" },
            complete = QuestState(6628, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.578, 0.654, "Parqual Fintallas", "Travel to Undercity."),
            },
        },
        {
            id = "objective-6628-1-answer-parqual-fintallas",
            kind = "objective",
            priority = 64,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Answer Parqual Fintallas' Question Correctly.",
            dependsOn = { "accept-6628-test-of-lore" },
            complete = QuestState(6628, "complete"),
            route = {
                Point(MAP.UNDERCITY, 0.578, 0.654, "Undercity", "Travel to Undercity."),
            },
        },
        {
            id = "turnin-6628-test-of-lore",
            kind = "turnin",
            priority = 65,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Turn in Test of Lore to Parqual Fintallas.",
            dependsOn = { "objective-6628-1-answer-parqual-fintallas" },
            complete = QuestState(6628, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.578, 0.654, "Parqual Fintallas", "Travel to Undercity."),
            },
        },
        {
            id = "accept-1394-final-passage",
            kind = "accept",
            priority = 66,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Accept Final Passage from Parqual Fintallas.",
            dependsOn = { "turnin-6628-test-of-lore" },
            complete = QuestState(1394, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.578, 0.654, "Parqual Fintallas", "Travel to Undercity."),
            },
        },
        {
            id = "turnin-1048-into-the-scarlet-monastery",
            kind = "turnin",
            priority = 67,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Turn in Into The Scarlet Monastery to Varimathras.",
            dependsOn = { "objective-1048-4-houndmaster-loksey" },
            complete = QuestState(1048, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.563, 0.922, "Varimathras", "Travel to Undercity."),
            },
        },
        {
            id = "turnin-1049-compendium-of-the-fallen",
            kind = "turnin",
            priority = 68,
            conditions = { all = { { faction = "Horde" }, { race = { 2, 6, 8 } }, { level = { min = 39 } } } },
            text = "Turn in Compendium of the Fallen to Sage Truthseeker.",
            dependsOn = { "objective-1049-1-compendium-of-the-fallen" },
            complete = QuestState(1049, "completed"),
            route = {
                Point(MAP.THUNDER_BLUFF, 0.344, 0.469, "Sage Truthseeker", "Travel to Thunder Bluff."),
            },
        },
        {
            id = "turnin-1394-final-passage",
            kind = "turnin",
            priority = 69,
            conditions = { all = { { faction = "Horde" }, { level = { min = 26 } } } },
            text = "Turn in Final Passage to Dorn Plainstalker.",
            dependsOn = { "accept-1394-final-passage" },
            complete = QuestState(1394, "completed"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.539, 0.415, "Dorn Plainstalker", "Travel to Thousand Needles."),
            },
        },
    },
})
