local _, ns = ...

local MAP = {
    BURNING_STEPPES = 1428,
    WINTERSPRING = 1452,
    EASTERN_PLAGUELANDS = 1423,
    WESTERN_PLAGUELANDS = 1422,
    TANARIS = 1446,
    UN_GORO_CRATER = 1449,
    ARATHI_HIGHLANDS = 1417,
    UNDERCITY = 1458,
    TIRISFAL_GLADES = 1420,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-scholomance",
    title = "Scholomance",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 50 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-5091-a-call-to-arms-the-plaguelands",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Accept A Call to Arms: The Plaguelands! from Crier Goodman.",
            complete = QuestState(5091, "activeOrCompleted"),
        },
        {
            id = "accept-4726-broodling-essence",
            kind = "accept",
            priority = 11,
            conditions = { level = { min = 56 } },
            text = "Accept Broodling Essence from Tinkee Steamboil.",
            complete = QuestState(4726, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4726-1-broodling-essence",
            kind = "objective",
            priority = 14,
            conditions = { level = { min = 56 } },
            text = "Collect 8 Broodling Essence.",
            dependsOn = { "accept-4726-broodling-essence" },
            complete = QuestState(4726, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.593, 0.325, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4726-broodling-essence",
            kind = "turnin",
            priority = 15,
            conditions = { level = { min = 56 } },
            text = "Turn in Broodling Essence to Tinkee Steamboil.",
            dependsOn = { "objective-4726-1-broodling-essence" },
            complete = QuestState(4726, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4808-felnok-steelspring",
            kind = "accept",
            priority = 16,
            conditions = { level = { min = 58 } },
            text = "Accept Felnok Steelspring from Tinkee Steamboil.",
            dependsOn = { "turnin-4726-broodling-essence" },
            complete = QuestState(4808, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4808-felnok-steelspring",
            kind = "turnin",
            priority = 17,
            conditions = { level = { min = 58 } },
            text = "Turn in Felnok Steelspring to Felnok Steelspring.",
            dependsOn = { "accept-4808-felnok-steelspring" },
            complete = QuestState(4808, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-4809-chillwind-horns",
            kind = "accept",
            priority = 18,
            conditions = { level = { min = 58 } },
            text = "Accept Chillwind Horns from Felnok Steelspring.",
            dependsOn = { "turnin-4808-felnok-steelspring" },
            complete = QuestState(4809, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "objective-4809-1-uncracked-chillwind-horn",
            kind = "objective",
            priority = 20,
            conditions = { level = { min = 58 } },
            text = "Collect 8 Uncracked Chillwind Horn.",
            dependsOn = { "accept-4809-chillwind-horns" },
            complete = QuestState(4809, "complete"),
            route = {
                Point(MAP.WINTERSPRING, 0.600, 0.215, "Winterspring", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-4809-chillwind-horns",
            kind = "turnin",
            priority = 21,
            conditions = { level = { min = 58 } },
            text = "Turn in Chillwind Horns to Felnok Steelspring.",
            dependsOn = { "objective-4809-1-uncracked-chillwind-horn" },
            complete = QuestState(4809, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-4810-return-to-tinkee",
            kind = "accept",
            priority = 22,
            conditions = { level = { min = 50 } },
            text = "Accept Return to Tinkee from Felnok Steelspring.",
            dependsOn = { "turnin-4809-chillwind-horns" },
            complete = QuestState(4810, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-4810-return-to-tinkee",
            kind = "turnin",
            priority = 23,
            conditions = { level = { min = 50 } },
            text = "Turn in Return to Tinkee to Tinkee Steamboil.",
            dependsOn = { "accept-4810-return-to-tinkee" },
            complete = QuestState(4810, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4907-tinkee-steamboil",
            kind = "accept",
            priority = 24,
            conditions = { level = { min = 57 } },
            text = "Accept Tinkee Steamboil from Felnok Steelspring.",
            complete = QuestState(4907, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-4907-tinkee-steamboil",
            kind = "turnin",
            priority = 25,
            conditions = { level = { min = 57 } },
            text = "Turn in Tinkee Steamboil to Tinkee Steamboil.",
            dependsOn = { "accept-4907-tinkee-steamboil" },
            complete = QuestState(4907, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4734-egg-freezing",
            kind = "accept",
            priority = 26,
            conditions = { level = { min = 57 } },
            text = "Accept Egg Freezing from Tinkee Steamboil.",
            dependsOn = { "turnin-4907-tinkee-steamboil" },
            complete = QuestState(4734, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 27,
            conditions = { level = { min = 50 } },
            text = "Enter Stratholme - Undead with your group.",
            dependsOn = { "accept-5091-a-call-to-arms-the-plaguelands", "accept-4726-broodling-essence", "accept-4808-felnok-steelspring", "accept-4809-chillwind-horns", "accept-4810-return-to-tinkee", "accept-4907-tinkee-steamboil", "accept-4734-egg-freezing" },
            persistCompletion = true,
            complete = { instance = 289 },
        },
        {
            id = "objective-4734-1-test-the-eggscilloscope",
            kind = "objective",
            priority = 28,
            conditions = { level = { min = 57 } },
            text = "Test the Eggscilloscope Prototype.",
            dependsOn = { "accept-4734-egg-freezing" },
            complete = QuestState(4734, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4734-egg-freezing",
            kind = "turnin",
            priority = 31,
            conditions = { level = { min = 57 } },
            text = "Turn in Egg Freezing to Tinkee Steamboil.",
            dependsOn = { "objective-4734-1-test-the-eggscilloscope" },
            complete = QuestState(4734, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4735-egg-collection",
            kind = "accept",
            priority = 32,
            conditions = { level = { min = 57 } },
            text = "Accept Egg Collection from Tinkee Steamboil.",
            dependsOn = { "turnin-4734-egg-freezing" },
            complete = QuestState(4735, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4735-1-collected-dragon-egg",
            kind = "objective",
            priority = 33,
            conditions = { level = { min = 57 } },
            text = "Collect 8 Collected Dragon Egg.",
            dependsOn = { "accept-4735-egg-collection" },
            complete = QuestState(4735, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4735-egg-collection",
            kind = "turnin",
            priority = 34,
            conditions = { level = { min = 57 } },
            text = "Turn in Egg Collection to Tinkee Steamboil.",
            dependsOn = { "objective-4735-1-collected-dragon-egg" },
            complete = QuestState(4735, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-5522-leonid-barthalomew",
            kind = "accept",
            priority = 35,
            conditions = { level = { min = 57 } },
            text = "Accept Leonid Barthalomew from Tinkee Steamboil.",
            dependsOn = { "turnin-4735-egg-collection" },
            complete = QuestState(5522, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-5522-leonid-barthalomew",
            kind = "turnin",
            priority = 36,
            conditions = { level = { min = 57 } },
            text = "Turn in Leonid Barthalomew to Leonid Barthalomew the Revered.",
            dependsOn = { "accept-5522-leonid-barthalomew" },
            complete = QuestState(5522, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5531-betina-bigglezink",
            kind = "accept",
            priority = 37,
            conditions = { level = { min = 57 } },
            text = "Accept Betina Bigglezink from Leonid Barthalomew the Revered.",
            dependsOn = { "turnin-5522-leonid-barthalomew" },
            complete = QuestState(5531, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5531-betina-bigglezink",
            kind = "turnin",
            priority = 38,
            conditions = { level = { min = 57 } },
            text = "Turn in Betina Bigglezink to Betina Bigglezink.",
            dependsOn = { "accept-5531-betina-bigglezink" },
            complete = QuestState(5531, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5529-plagued-hatchlings",
            kind = "accept",
            priority = 39,
            conditions = { level = { min = 55 } },
            text = "Accept Plagued Hatchlings from Betina Bigglezink.",
            dependsOn = { "turnin-5531-betina-bigglezink" },
            complete = QuestState(5529, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-4771-dawn-s-gambit",
            kind = "accept",
            priority = 40,
            conditions = { level = { min = 57 } },
            text = "Accept Dawn's Gambit from Betina Bigglezink.",
            complete = QuestState(4771, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5091-a-call-to-arms-the-plaguelands",
            kind = "turnin",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Turn in A Call to Arms: The Plaguelands! to Commander Ashlam Valorfist.",
            dependsOn = { "accept-5091-a-call-to-arms-the-plaguelands" },
            complete = QuestState(5091, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5092-clear-the-way",
            kind = "accept",
            priority = 42,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Accept Clear the Way from Commander Ashlam Valorfist.",
            dependsOn = { "turnin-5091-a-call-to-arms-the-plaguelands" },
            complete = QuestState(5092, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5092-1-skeletal-flayer",
            kind = "objective",
            priority = 43,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Kill 10 Skeletal Flayer.",
            dependsOn = { "accept-5092-clear-the-way" },
            complete = QuestObjective(5092, 1, "Skeletal Flayer"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.485, 0.811, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5092-2-slavering-ghoul",
            kind = "objective",
            priority = 44,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Kill 10 Slavering Ghoul.",
            dependsOn = { "accept-5092-clear-the-way" },
            complete = QuestObjective(5092, 2, "Slavering Ghoul"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.485, 0.811, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5092-clear-the-way",
            kind = "turnin",
            priority = 45,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Turn in Clear the Way to Commander Ashlam Valorfist.",
            dependsOn = { "objective-5092-1-skeletal-flayer", "objective-5092-2-slavering-ghoul" },
            complete = QuestState(5092, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5097-all-along-the-watchtowers",
            kind = "accept",
            priority = 46,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Accept All Along the Watchtowers from Commander Ashlam Valorfist.",
            dependsOn = { "turnin-5092-clear-the-way" },
            complete = QuestState(5097, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5097-4-mark-tower-four",
            kind = "objective",
            priority = 47,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Mark Tower Four.",
            dependsOn = { "accept-5097-all-along-the-watchtowers" },
            complete = QuestObjective(5097, 4, "Mark Tower Four"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.467, 0.711, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5097-1-mark-tower-one",
            kind = "objective",
            priority = 48,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Mark Tower One.",
            dependsOn = { "accept-5097-all-along-the-watchtowers" },
            complete = QuestObjective(5097, 1, "Mark Tower One"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.401, 0.715, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5097-2-mark-tower-two",
            kind = "objective",
            priority = 49,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Mark Tower Two.",
            dependsOn = { "accept-5097-all-along-the-watchtowers" },
            complete = QuestObjective(5097, 2, "Mark Tower Two"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.424, 0.663, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5097-3-mark-tower-three",
            kind = "objective",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Mark Tower Three.",
            dependsOn = { "accept-5097-all-along-the-watchtowers" },
            complete = QuestObjective(5097, 3, "Mark Tower Three"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.442, 0.634, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5097-all-along-the-watchtowers",
            kind = "turnin",
            priority = 51,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Turn in All Along the Watchtowers to Commander Ashlam Valorfist.",
            dependsOn = { "objective-5097-4-mark-tower-four", "objective-5097-1-mark-tower-one", "objective-5097-2-mark-tower-two", "objective-5097-3-mark-tower-three" },
            complete = QuestState(5097, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5533-scholomance",
            kind = "accept",
            priority = 53,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Accept Scholomance from Commander Ashlam Valorfist.",
            complete = QuestState(5533, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5533-scholomance",
            kind = "turnin",
            priority = 54,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Turn in Scholomance to Alchemist Arbington.",
            dependsOn = { "accept-5533-scholomance" },
            complete = QuestState(5533, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.838, "Alchemist Arbington", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5537-skeletal-fragments",
            kind = "accept",
            priority = 55,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Accept Skeletal Fragments from Alchemist Arbington.",
            dependsOn = { "turnin-5533-scholomance" },
            complete = QuestState(5537, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.838, "Alchemist Arbington", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5537-1-skeletal-fragments",
            kind = "objective",
            priority = 57,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Collect 15 Skeletal Fragments.",
            dependsOn = { "accept-5537-skeletal-fragments" },
            complete = QuestState(5537, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.504, 0.786, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5537-skeletal-fragments",
            kind = "turnin",
            priority = 58,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Turn in Skeletal Fragments to Alchemist Arbington.",
            dependsOn = { "objective-5537-1-skeletal-fragments" },
            complete = QuestState(5537, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.838, "Alchemist Arbington", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5538-mold-rhymes-with",
            kind = "accept",
            priority = 59,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Mold Rhymes With from Alchemist Arbington.",
            dependsOn = { "turnin-5537-skeletal-fragments" },
            complete = QuestState(5538, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.838, "Alchemist Arbington", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5538-mold-rhymes-with",
            kind = "turnin",
            priority = 60,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Mold Rhymes With to Krinkle Goodsteel.",
            dependsOn = { "accept-5538-mold-rhymes-with" },
            complete = QuestState(5538, "completed"),
            route = {
                Point(MAP.TANARIS, 0.515, 0.288, "Krinkle Goodsteel", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-5801-fire-plume-forged",
            kind = "accept",
            priority = 61,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept Fire Plume Forged from Krinkle Goodsteel.",
            dependsOn = { "turnin-5538-mold-rhymes-with" },
            complete = QuestState(5801, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.515, 0.288, "Krinkle Goodsteel", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-5801-1-unfinished-skeleton-key",
            kind = "objective",
            priority = 62,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Collect Unfinished Skeleton Key.",
            dependsOn = { "accept-5801-fire-plume-forged" },
            complete = QuestState(5801, "complete"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.488, 0.472, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-5801-fire-plume-forged",
            kind = "turnin",
            priority = 63,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in Fire Plume Forged to Alchemist Arbington.",
            dependsOn = { "objective-5801-1-unfinished-skeleton-key" },
            complete = QuestState(5801, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.838, "Alchemist Arbington", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5803-araj-s-scarab",
            kind = "accept",
            priority = 64,
            conditions = { level = { min = 55 } },
            text = "Accept Araj's Scarab from Alchemist Arbington.",
            dependsOn = { "turnin-5801-fire-plume-forged" },
            complete = QuestState(5803, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.838, "Alchemist Arbington", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5803-1-araj-s-scarab",
            kind = "objective",
            priority = 67,
            conditions = { level = { min = 55 } },
            text = "Collect Araj's Scarab.",
            dependsOn = { "accept-5803-araj-s-scarab" },
            complete = QuestState(5803, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.453, 0.692, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5803-araj-s-scarab",
            kind = "turnin",
            priority = 68,
            conditions = { level = { min = 55 } },
            text = "Turn in Araj's Scarab to talk Alchemist Arbington.",
            dependsOn = { "objective-5803-1-araj-s-scarab" },
            complete = QuestState(5803, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.838, "talk Alchemist Arbington", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5505-the-key-to-scholomance",
            kind = "accept",
            priority = 69,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept The Key to Scholomance from Commander Ashlam Valorfist.",
            complete = QuestState(5505, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5343-barov-family-fortune",
            kind = "accept",
            priority = 70,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 52 } } } },
            text = "Accept Barov Family Fortune from Weldon Barov.",
            complete = QuestState(5343, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.435, 0.837, "Weldon Barov", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5382-doctor-theolen-krastinov-the-butcher",
            kind = "accept",
            priority = 71,
            conditions = { level = { min = 55 } },
            text = "Accept Doctor Theolen Krastinov, the Butcher from Eva Sarkhoff. 'The pleasure is mine madam. Might I ask what it is that you are doing here?'.",
            complete = QuestState(5382, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5343-3-the-deed-to-southshore",
            kind = "objective",
            priority = 73,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 52 } } } },
            text = "Collect The Deed to Southshore.",
            dependsOn = { "accept-5343-barov-family-fortune" },
            complete = QuestObjective(5343, 3, "The Deed to Southshore"),
            useClientPin = true,
        },
        {
            id = "objective-5343-4-the-deed-to-tarren-mill",
            kind = "objective",
            priority = 75,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 52 } } } },
            text = "Collect The Deed to Tarren Mill.",
            dependsOn = { "accept-5343-barov-family-fortune" },
            complete = QuestObjective(5343, 4, "The Deed to Tarren Mill"),
            useClientPin = true,
        },
        {
            id = "objective-5529-1-plagued-hatchling",
            kind = "objective",
            priority = 76,
            conditions = { level = { min = 55 } },
            text = "Kill 20 Plagued Hatchling.",
            dependsOn = { "accept-5529-plagued-hatchlings" },
            complete = QuestState(5529, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4771-1-place-the-dawn-s-gmabit",
            kind = "objective",
            priority = 78,
            conditions = { level = { min = 57 } },
            text = "Place the Dawn's Gmabit.",
            dependsOn = { "accept-4771-dawn-s-gambit" },
            complete = QuestObjective(4771, 1, "Place the Dawn's Gmabit"),
            useClientPin = true,
        },
        {
            id = "objective-4771-2-vectus",
            kind = "objective",
            priority = 80,
            conditions = { level = { min = 57 } },
            text = "Slay Vectus.",
            dependsOn = { "accept-4771-dawn-s-gambit" },
            complete = QuestObjective(4771, 2, "Vectus"),
            useClientPin = true,
        },
        {
            id = "objective-5343-1-the-deed-to-brill",
            kind = "objective",
            priority = 82,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 52 } } } },
            text = "Collect The Deed to Brill.",
            dependsOn = { "accept-5343-barov-family-fortune" },
            complete = QuestObjective(5343, 1, "The Deed to Brill"),
            useClientPin = true,
        },
        {
            id = "objective-5382-2-burn-the-remains-of-eva",
            kind = "objective",
            priority = 84,
            conditions = { level = { min = 55 } },
            text = "Burn the Remains of Eva Sarkhoff.",
            dependsOn = { "accept-5382-doctor-theolen-krastinov-the-butcher" },
            complete = QuestObjective(5382, 2, "Burn the Remains of Eva Sarkhoff"),
            useClientPin = true,
        },
        {
            id = "objective-5382-3-burn-the-remains-of-luci",
            kind = "objective",
            priority = 86,
            conditions = { level = { min = 55 } },
            text = "Burn the Remains of Lucien Sarkhoff.",
            dependsOn = { "accept-5382-doctor-theolen-krastinov-the-butcher" },
            complete = QuestObjective(5382, 3, "Burn the Remains of Lucien Sarkhoff"),
            useClientPin = true,
        },
        {
            id = "objective-5382-1-doctor-theolen-krastinov",
            kind = "objective",
            priority = 87,
            conditions = { level = { min = 55 } },
            text = "Kill Doctor Theolen Krastinov.",
            dependsOn = { "accept-5382-doctor-theolen-krastinov-the-butcher" },
            complete = QuestObjective(5382, 1, "Doctor Theolen Krastinov"),
            useClientPin = true,
        },
        {
            id = "objective-5343-2-the-deed-to-caer-darrow",
            kind = "objective",
            priority = 89,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 52 } } } },
            text = "Collect The Deed to Caer Darrow.",
            dependsOn = { "accept-5343-barov-family-fortune" },
            complete = QuestObjective(5343, 2, "The Deed to Caer Darrow"),
            useClientPin = true,
        },
        {
            id = "turnin-5382-doctor-theolen-krastinov-the-butcher",
            kind = "turnin",
            priority = 90,
            conditions = { level = { min = 55 } },
            text = "Turn in Doctor Theolen Krastinov, the Butcher to Eva Sarkhoff.",
            dependsOn = { "objective-5382-2-burn-the-remains-of-eva", "objective-5382-3-burn-the-remains-of-luci", "objective-5382-1-doctor-theolen-krastinov" },
            complete = QuestState(5382, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5515-krastinov-s-bag-of-horrors",
            kind = "accept",
            priority = 91,
            conditions = { level = { min = 55 } },
            text = "Accept Krastinov's Bag of Horrors from Eva Sarkhoff.",
            dependsOn = { "turnin-5382-doctor-theolen-krastinov-the-butcher" },
            complete = QuestState(5515, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5343-barov-family-fortune",
            kind = "turnin",
            priority = 92,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 52 } } } },
            text = "Turn in Barov Family Fortune to Weldon Barov.",
            dependsOn = { "objective-5343-3-the-deed-to-southshore", "objective-5343-4-the-deed-to-tarren-mill", "objective-5343-1-the-deed-to-brill", "objective-5343-2-the-deed-to-caer-darrow" },
            complete = QuestState(5343, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.435, 0.837, "Weldon Barov", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5529-plagued-hatchlings",
            kind = "turnin",
            priority = 93,
            conditions = { level = { min = 55 } },
            text = "Turn in Plagued Hatchlings to Betina Bigglezink.",
            dependsOn = { "objective-5529-1-plagued-hatchling" },
            complete = QuestState(5529, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-4771-dawn-s-gambit",
            kind = "turnin",
            priority = 94,
            conditions = { level = { min = 57 } },
            text = "Turn in Dawn's Gambit to Betina Bigglezink.",
            dependsOn = { "objective-4771-1-place-the-dawn-s-gmabit", "objective-4771-2-vectus" },
            complete = QuestState(4771, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5515-1-krastinov-s-bag-of-horro",
            kind = "objective",
            priority = 96,
            conditions = { level = { min = 55 } },
            text = "Collect Krastinov's Bag of Horrors.",
            dependsOn = { "accept-5515-krastinov-s-bag-of-horrors" },
            complete = QuestState(5515, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-5582-healthy-dragon-scale",
            kind = "accept",
            priority = 98,
            conditions = { level = { min = 55 } },
            text = "Accept Healthy Dragon Scale.",
            complete = QuestState(5582, "activeOrCompleted"),
        },
        {
            id = "turnin-5515-krastinov-s-bag-of-horrors",
            kind = "turnin",
            priority = 99,
            conditions = { level = { min = 55 } },
            text = "Turn in Krastinov's Bag of Horrors to Eva Sarkhoff.",
            dependsOn = { "objective-5515-1-krastinov-s-bag-of-horro" },
            complete = QuestState(5515, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5384-kirtonos-the-herald",
            kind = "accept",
            priority = 100,
            conditions = { level = { min = 55 } },
            text = "Accept Kirtonos the Herald from Eva Sarkhoff.",
            dependsOn = { "turnin-5515-krastinov-s-bag-of-horrors" },
            complete = QuestState(5384, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5582-healthy-dragon-scale",
            kind = "turnin",
            priority = 101,
            conditions = { level = { min = 55 } },
            text = "Turn in Healthy Dragon Scale to Betina Bigglezink.",
            dependsOn = { "accept-5582-healthy-dragon-scale" },
            complete = QuestState(5582, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5384-1-kirtonos-the-herald",
            kind = "objective",
            priority = 103,
            conditions = { level = { min = 55 } },
            text = "Kill Kirtonos the Herald.",
            dependsOn = { "accept-5384-kirtonos-the-herald" },
            complete = QuestState(5384, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5384-kirtonos-the-herald",
            kind = "turnin",
            priority = 104,
            conditions = { level = { min = 55 } },
            text = "Turn in Kirtonos the Herald to Eva Sarkhoff.",
            dependsOn = { "objective-5384-1-kirtonos-the-herald" },
            complete = QuestState(5384, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5461-the-human-ras-frostwhisper",
            kind = "accept",
            priority = 106,
            conditions = { level = { min = 57 } },
            text = "Accept The Human, Ras Frostwhisper from Magistrate Marduke.",
            complete = QuestState(5461, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5461-1-keepsake-of-remembrance",
            kind = "objective",
            priority = 108,
            conditions = { level = { min = 57 } },
            text = "Collect Keepsake of Remembrance.",
            dependsOn = { "accept-5461-the-human-ras-frostwhisper" },
            complete = QuestState(5461, "complete"),
            route = {
                Point(MAP.ARATHI_HIGHLANDS, 0.179, 0.694, "Arathi Highlands", "Travel to Arathi Highlands."),
            },
        },
        {
            id = "turnin-5461-the-human-ras-frostwhisper",
            kind = "turnin",
            priority = 109,
            conditions = { level = { min = 57 } },
            text = "Turn in The Human, Ras Frostwhisper to Magistrate Marduke.",
            dependsOn = { "objective-5461-1-keepsake-of-remembrance" },
            complete = QuestState(5461, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5462-the-dying-ras-frostwhisper",
            kind = "accept",
            priority = 110,
            conditions = { level = { min = 57 } },
            text = "Accept The Dying, Ras Frostwhisper from Magistrate Marduke.",
            dependsOn = { "turnin-5461-the-human-ras-frostwhisper" },
            complete = QuestState(5462, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5462-the-dying-ras-frostwhisper",
            kind = "turnin",
            priority = 111,
            conditions = { level = { min = 57 } },
            text = "Turn in The Dying, Ras Frostwhisper to Leonid Barthalomew the Revered.",
            dependsOn = { "accept-5462-the-dying-ras-frostwhisper" },
            complete = QuestState(5462, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5463-menethil-s-gift",
            kind = "accept",
            priority = 112,
            conditions = { level = { min = 57 } },
            text = "Accept Menethil's Gift from Leonid Barthalomew the Revered.",
            dependsOn = { "turnin-5462-the-dying-ras-frostwhisper" },
            complete = QuestState(5463, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5463-menethil-s-gift",
            kind = "turnin",
            priority = 115,
            conditions = { level = { min = 57 } },
            text = "Turn in Menethil's Gift to Leonid Barthalomew the Revered.",
            dependsOn = { "accept-5463-menethil-s-gift" },
            complete = QuestState(5463, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5464-menethil-s-gift",
            kind = "accept",
            priority = 116,
            conditions = { level = { min = 57 } },
            text = "Accept Menethil's Gift.",
            dependsOn = { "turnin-5463-menethil-s-gift" },
            complete = QuestState(5464, "activeOrCompleted"),
        },
        {
            id = "accept-5465-soulbound-keepsake",
            kind = "accept",
            priority = 117,
            conditions = { level = { min = 57 } },
            text = "Accept Soulbound Keepsake from Leonid Barthalomew the Revered.",
            dependsOn = { "turnin-5463-menethil-s-gift" },
            complete = QuestState(5465, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5465-soulbound-keepsake",
            kind = "turnin",
            priority = 118,
            conditions = { level = { min = 57 } },
            text = "Turn in Soulbound Keepsake to Magistrate Marduke.",
            dependsOn = { "accept-5465-soulbound-keepsake" },
            complete = QuestState(5465, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5466-the-lich-ras-frostwhisper",
            kind = "accept",
            priority = 119,
            conditions = { level = { min = 57 } },
            text = "Accept The Lich, Ras Frostwhisper from Magistrate Marduke.",
            dependsOn = { "turnin-5465-soulbound-keepsake" },
            complete = QuestState(5466, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5466-1-human-head-of-ras-frostw",
            kind = "objective",
            priority = 121,
            conditions = { level = { min = 57 } },
            text = "Collect Human Head of Ras Frostwhisper.",
            dependsOn = { "accept-5466-the-lich-ras-frostwhisper" },
            complete = QuestState(5466, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5466-the-lich-ras-frostwhisper",
            kind = "turnin",
            priority = 122,
            conditions = { level = { min = 57 } },
            text = "Turn in The Lich, Ras Frostwhisper to Magistrate Marduke.",
            dependsOn = { "objective-5466-1-human-head-of-ras-frostw" },
            complete = QuestState(5466, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5094-a-call-to-arms-the-plaguelands",
            kind = "accept",
            priority = 123,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept A Call to Arms: The Plaguelands! from Harbinger Balthazad.",
            complete = QuestState(5094, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.638, 0.441, "Harbinger Balthazad", "Travel to Undercity."),
            },
        },
        {
            id = "turnin-5094-a-call-to-arms-the-plaguelands",
            kind = "turnin",
            priority = 124,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in A Call to Arms: The Plaguelands! to High Executor Derrington.",
            dependsOn = { "accept-5094-a-call-to-arms-the-plaguelands" },
            complete = QuestState(5094, "completed"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.689, "High Executor Derrington", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "accept-5096-scarlet-diversions",
            kind = "accept",
            priority = 125,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept Scarlet Diversions from High Executor Derrington.",
            dependsOn = { "turnin-5094-a-call-to-arms-the-plaguelands" },
            complete = QuestState(5096, "activeOrCompleted"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.689, "High Executor Derrington", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "objective-5096-1-destroy-the-command-tent",
            kind = "objective",
            priority = 128,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Destroy the Command Tent and Plant the Scourge Banner in the Camp.",
            dependsOn = { "accept-5096-scarlet-diversions" },
            complete = QuestState(5096, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.407, 0.520, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5096-scarlet-diversions",
            kind = "turnin",
            priority = 129,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in Scarlet Diversions to High Executor Derrington.",
            dependsOn = { "objective-5096-1-destroy-the-command-tent" },
            complete = QuestState(5096, "completed"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.689, "High Executor Derrington", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "accept-5098-all-along-the-watchtowers",
            kind = "accept",
            priority = 130,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept All Along the Watchtowers from High Executor Derrington.",
            dependsOn = { "turnin-5096-scarlet-diversions" },
            complete = QuestState(5098, "activeOrCompleted"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.689, "High Executor Derrington", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "objective-5098-4-mark-tower-four",
            kind = "objective",
            priority = 131,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Mark Tower Four.",
            dependsOn = { "accept-5098-all-along-the-watchtowers" },
            complete = QuestObjective(5098, 4, "Mark Tower Four"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.467, 0.711, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5098-1-mark-tower-one",
            kind = "objective",
            priority = 132,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Mark Tower One.",
            dependsOn = { "accept-5098-all-along-the-watchtowers" },
            complete = QuestObjective(5098, 1, "Mark Tower One"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.401, 0.715, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5098-2-mark-tower-two",
            kind = "objective",
            priority = 133,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Mark Tower Two.",
            dependsOn = { "accept-5098-all-along-the-watchtowers" },
            complete = QuestObjective(5098, 2, "Mark Tower Two"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.424, 0.663, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5098-3-mark-tower-three",
            kind = "objective",
            priority = 134,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Mark Tower Three.",
            dependsOn = { "accept-5098-all-along-the-watchtowers" },
            complete = QuestObjective(5098, 3, "Mark Tower Three"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.442, 0.634, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5098-all-along-the-watchtowers",
            kind = "turnin",
            priority = 135,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in All Along the Watchtowers to High Executor Derrington.",
            dependsOn = { "objective-5098-4-mark-tower-four", "objective-5098-1-mark-tower-one", "objective-5098-2-mark-tower-two", "objective-5098-3-mark-tower-three" },
            complete = QuestState(5098, "completed"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.689, "High Executor Derrington", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "accept-838-scholomance",
            kind = "accept",
            priority = 136,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept Scholomance from High Executor Derrington.",
            complete = QuestState(838, "activeOrCompleted"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.689, "High Executor Derrington", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "turnin-838-scholomance",
            kind = "turnin",
            priority = 137,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in Scholomance to Apothecary Dithers.",
            dependsOn = { "accept-838-scholomance" },
            complete = QuestState(838, "completed"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.833, 0.692, "Apothecary Dithers", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "accept-964-skeletal-fragments",
            kind = "accept",
            priority = 138,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept Skeletal Fragments from Apothecary Dithers.",
            dependsOn = { "turnin-838-scholomance" },
            complete = QuestState(964, "activeOrCompleted"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.833, 0.692, "Apothecary Dithers", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "objective-964-1-skeletal-fragments",
            kind = "objective",
            priority = 139,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Collect 15 Skeletal Fragments.",
            dependsOn = { "accept-964-skeletal-fragments" },
            complete = QuestState(964, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.366, 0.577, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-964-skeletal-fragments",
            kind = "turnin",
            priority = 140,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in Skeletal Fragments to Apothecary Dithers.",
            dependsOn = { "objective-964-1-skeletal-fragments" },
            complete = QuestState(964, "completed"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.833, 0.692, "Apothecary Dithers", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "accept-5514-mold-rhymes-with",
            kind = "accept",
            priority = 141,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Mold Rhymes With from Apothecary Dithers.",
            dependsOn = { "turnin-964-skeletal-fragments" },
            complete = QuestState(5514, "activeOrCompleted"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.833, 0.692, "Apothecary Dithers", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "turnin-5514-mold-rhymes-with",
            kind = "turnin",
            priority = 142,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Mold Rhymes With to Krinkle Goodsteel.",
            dependsOn = { "accept-5514-mold-rhymes-with" },
            complete = QuestState(5514, "completed"),
            route = {
                Point(MAP.TANARIS, 0.515, 0.288, "Krinkle Goodsteel", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-5802-fire-plume-forged",
            kind = "accept",
            priority = 143,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Fire Plume Forged from Krinkle Goodsteel.",
            dependsOn = { "turnin-5514-mold-rhymes-with" },
            complete = QuestState(5802, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.515, 0.288, "Krinkle Goodsteel", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-5802-1-unfinished-skeleton-key",
            kind = "objective",
            priority = 144,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Unfinished Skeleton Key.",
            dependsOn = { "accept-5802-fire-plume-forged" },
            complete = QuestState(5802, "complete"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.488, 0.472, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "accept-5511-the-key-to-scholomance",
            kind = "accept",
            priority = 145,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Key to Scholomance from High Executor Derrington.",
            complete = QuestState(5511, "activeOrCompleted"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.689, "High Executor Derrington", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "accept-5341-barov-family-fortune",
            kind = "accept",
            priority = 146,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Accept Barov Family Fortune from Alexi Barov.",
            complete = QuestState(5341, "activeOrCompleted"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.716, "Alexi Barov", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "objective-5341-3-the-deed-to-southshore",
            kind = "objective",
            priority = 147,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Collect The Deed to Southshore.",
            dependsOn = { "accept-5341-barov-family-fortune" },
            complete = QuestObjective(5341, 3, "The Deed to Southshore"),
            useClientPin = true,
        },
        {
            id = "objective-5341-4-the-deed-to-tarren-mill",
            kind = "objective",
            priority = 148,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Collect The Deed to Tarren Mill.",
            dependsOn = { "accept-5341-barov-family-fortune" },
            complete = QuestObjective(5341, 4, "The Deed to Tarren Mill"),
            useClientPin = true,
        },
        {
            id = "objective-5341-1-the-deed-to-brill",
            kind = "objective",
            priority = 150,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Collect The Deed to Brill.",
            dependsOn = { "accept-5341-barov-family-fortune" },
            complete = QuestObjective(5341, 1, "The Deed to Brill"),
            useClientPin = true,
        },
        {
            id = "objective-5341-2-the-deed-to-caer-darrow",
            kind = "objective",
            priority = 151,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Collect The Deed to Caer Darrow.",
            dependsOn = { "accept-5341-barov-family-fortune" },
            complete = QuestObjective(5341, 2, "The Deed to Caer Darrow"),
            useClientPin = true,
        },
        {
            id = "turnin-5341-barov-family-fortune",
            kind = "turnin",
            priority = 152,
            conditions = { all = { { faction = "Horde" }, { level = { min = 52 } } } },
            text = "Turn in Barov Family Fortune to Alexi Barov.",
            dependsOn = { "objective-5341-3-the-deed-to-southshore", "objective-5341-4-the-deed-to-tarren-mill", "objective-5341-1-the-deed-to-brill", "objective-5341-2-the-deed-to-caer-darrow" },
            complete = QuestState(5341, "completed"),
            route = {
                Point(MAP.TIRISFAL_GLADES, 0.831, 0.716, "Alexi Barov", "Travel to Tirisfal Glades."),
            },
        },
        {
            id = "turnin-5464-menethil-s-gift",
            kind = "turnin",
            priority = 155,
            conditions = { level = { min = 57 } },
            text = "Turn in Menethil's Gift to Leonid Barthalomew the Revered.",
            dependsOn = { "accept-5464-menethil-s-gift" },
            complete = QuestState(5464, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
    },
})
