local _, ns = ...

local MAP = {
    EASTERN_PLAGUELANDS = 1423,
    WESTERN_PLAGUELANDS = 1422,
}

local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-stratholme-live",
    title = "Stratholme - Live",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 55 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-5214-the-great-fras-siabi",
            kind = "accept",
            priority = 10,
            conditions = { level = { min = 55 } },
            text = "Accept The Great Fras Siabi from Smokey LaRue.",
            complete = QuestState(5214, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.806, 0.580, "Smokey LaRue", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5251-the-archivist",
            kind = "accept",
            priority = 11,
            conditions = { level = { min = 55 } },
            text = "Accept The Archivist from Duke Nicholas Zverenhoff.",
            complete = QuestState(5251, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.814, 0.598, "Duke Nicholas Zverenhoff", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5281-the-restless-souls",
            kind = "accept",
            priority = 12,
            conditions = { level = { min = 55 } },
            text = "Accept The Restless Souls from Caretaker Alen.",
            complete = QuestState(5281, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.797, 0.637, "Caretaker Alen", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5281-the-restless-souls",
            kind = "turnin",
            priority = 13,
            conditions = { level = { min = 55 } },
            text = "Turn in The Restless Souls to Egan.",
            dependsOn = { "accept-5281-the-restless-souls" },
            complete = QuestState(5281, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.144, 0.337, "Egan", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5282-the-restless-souls",
            kind = "accept",
            priority = 14,
            conditions = { level = { min = 55 } },
            text = "Accept The Restless Souls from Egan.",
            dependsOn = { "turnin-5281-the-restless-souls" },
            complete = QuestState(5282, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.144, 0.337, "Egan", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5542-demon-dogs",
            kind = "accept",
            priority = 15,
            conditions = { level = { min = 52 } },
            text = "Accept Demon Dogs from Tirion Fordring.",
            complete = QuestState(5542, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5543-blood-tinged-skies",
            kind = "accept",
            priority = 16,
            conditions = { level = { min = 52 } },
            text = "Accept Blood Tinged Skies from Tirion Fordring.",
            complete = QuestState(5543, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5544-carrion-grubbage",
            kind = "accept",
            priority = 17,
            conditions = { level = { min = 52 } },
            text = "Accept Carrion Grubbage from Tirion Fordring.",
            complete = QuestState(5544, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5543-1-plaguebat",
            kind = "objective",
            priority = 18,
            conditions = { level = { min = 52 } },
            text = "Kill 30 Plaguebat.",
            dependsOn = { "accept-5543-blood-tinged-skies" },
            complete = QuestState(5543, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.432, 0.830, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5542-1-plaguehound-runt",
            kind = "objective",
            priority = 19,
            conditions = { level = { min = 52 } },
            text = "Kill 20 Plaguehound Runt.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 1, "Plaguehound Runt"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.432, 0.830, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "boss-carrion-grub",
            kind = "note",
            priority = 20,
            conditions = { level = { min = 55 } },
            text = "Kill Carrion Grub+.",
        },
        {
            id = "objective-5544-1-slab-of-carrion-worm-mea",
            kind = "objective",
            priority = 21,
            conditions = { level = { min = 52 } },
            text = "Collect 15 Slab of Carrion Worm Meat.",
            dependsOn = { "accept-5544-carrion-grubbage" },
            complete = QuestState(5544, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.432, 0.830, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5542-2-plaguehound",
            kind = "objective",
            priority = 22,
            conditions = { level = { min = 52 } },
            text = "Kill 5 Plaguehound.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 2, "Plaguehound"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.700, 0.684, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5542-3-frenzied-plaguehound",
            kind = "objective",
            priority = 23,
            conditions = { level = { min = 52 } },
            text = "Kill 5 Frenzied Plaguehound.",
            dependsOn = { "accept-5542-demon-dogs" },
            complete = QuestObjective(5542, 3, "Frenzied Plaguehound"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.626, 0.480, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5542-demon-dogs",
            kind = "turnin",
            priority = 24,
            conditions = { level = { min = 52 } },
            text = "Turn in Demon Dogs to Tirion Fordring.",
            dependsOn = { "objective-5542-1-plaguehound-runt", "objective-5542-2-plaguehound", "objective-5542-3-frenzied-plaguehound" },
            complete = QuestState(5542, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5543-blood-tinged-skies",
            kind = "turnin",
            priority = 25,
            conditions = { level = { min = 52 } },
            text = "Turn in Blood Tinged Skies to Tirion Fordring.",
            dependsOn = { "objective-5543-1-plaguebat" },
            complete = QuestState(5543, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5544-carrion-grubbage",
            kind = "turnin",
            priority = 26,
            conditions = { level = { min = 52 } },
            text = "Turn in Carrion Grubbage to Tirion Fordring.",
            dependsOn = { "objective-5544-1-slab-of-carrion-worm-mea" },
            complete = QuestState(5544, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5742-redemption",
            kind = "accept",
            priority = 27,
            conditions = { level = { min = 52 } },
            text = "Accept Redemption from Tirion Fordring.",
            dependsOn = { "turnin-5544-carrion-grubbage" },
            complete = QuestState(5742, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5742-1-listen-to-tirion-s-tale",
            kind = "gossip",
            priority = 28,
            conditions = { level = { min = 52 } },
            text = "Talk to Tirion Fordring. 'I am ready to hear your tale, Tirion.' Listen to Tirion's Tale.",
            dependsOn = { "accept-5742-redemption" },
            complete = QuestState(5742, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5742-redemption",
            kind = "turnin",
            priority = 29,
            conditions = { level = { min = 52 } },
            text = "Turn in Redemption to Tirion Fordring.",
            dependsOn = { "objective-5742-1-listen-to-tirion-s-tale" },
            complete = QuestState(5742, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5781-of-forgotten-memories",
            kind = "accept",
            priority = 30,
            conditions = { level = { min = 52 } },
            text = "Accept Of Forgotten Memories from Tirion Fordring.",
            dependsOn = { "turnin-5742-redemption" },
            complete = QuestState(5781, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "note-click-loose-dirt-mound",
            kind = "note",
            priority = 31,
            conditions = { level = { min = 55 } },
            text = "Click Loose Dirt Mound.",
        },
        {
            id = "boss-mercutio-filthgorger",
            kind = "note",
            priority = 32,
            conditions = { level = { min = 55 } },
            text = "Kill Mercutio Filthgorger. Mercutio Filthgorger appears with a group of 3 guards with him. Try to kite Mercutio Filthgorger away from his guards, so you can fight him by himself. If you have trouble, try to find someone to help you.",
            dependsOn = { "boss-carrion-grub" },
        },
        {
            id = "objective-5781-1-taelan-s-hammer",
            kind = "objective",
            priority = 33,
            conditions = { level = { min = 52 } },
            text = "Collect Taelan's Hammer.",
            dependsOn = { "accept-5781-of-forgotten-memories" },
            complete = QuestState(5781, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.283, 0.869, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5781-of-forgotten-memories",
            kind = "turnin",
            priority = 34,
            conditions = { level = { min = 52 } },
            text = "Turn in Of Forgotten Memories to Tirion Fordring.",
            dependsOn = { "objective-5781-1-taelan-s-hammer" },
            complete = QuestState(5781, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5845-of-lost-honor",
            kind = "accept",
            priority = 35,
            conditions = { level = { min = 52 } },
            text = "Accept Of Lost Honor from Tirion Fordring.",
            dependsOn = { "turnin-5781-of-forgotten-memories" },
            complete = QuestState(5845, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "note-click-symbol-of-lost-honor",
            kind = "note",
            priority = 36,
            conditions = { level = { min = 55 } },
            text = "Click Symbol of Lost Honor.",
        },
        {
            id = "objective-5845-1-symbol-of-lost-honor",
            kind = "objective",
            priority = 37,
            conditions = { level = { min = 52 } },
            text = "Collect Symbol of Lost Honor.",
            dependsOn = { "accept-5845-of-lost-honor" },
            complete = QuestState(5845, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.713, 0.340, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5845-of-lost-honor",
            kind = "turnin",
            priority = 38,
            conditions = { level = { min = 52 } },
            text = "Turn in Of Lost Honor to Tirion Fordring.",
            dependsOn = { "objective-5845-1-symbol-of-lost-honor" },
            complete = QuestState(5845, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5846-of-love-and-family",
            kind = "accept",
            priority = 39,
            conditions = { level = { min = 52 } },
            text = "Accept Of Love and Family from Tirion Fordring.",
            dependsOn = { "turnin-5845-of-lost-honor" },
            complete = QuestState(5846, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5846-of-love-and-family",
            kind = "turnin",
            priority = 40,
            conditions = { level = { min = 52 } },
            text = "Turn in Of Love and Family to Artist Renfray.",
            dependsOn = { "accept-5846-of-love-and-family" },
            complete = QuestState(5846, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.658, 0.754, "Artist Renfray", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5848-of-love-and-family",
            kind = "accept",
            priority = 41,
            conditions = { level = { min = 52 } },
            text = "Accept Of Love and Family from Artist Renfray.",
            dependsOn = { "turnin-5846-of-love-and-family" },
            complete = QuestState(5848, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.658, 0.754, "Artist Renfray", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 42,
            conditions = { level = { min = 55 } },
            text = "Enter Stratholme - Undead with your group.",
            dependsOn = { "accept-5214-the-great-fras-siabi", "accept-5251-the-archivist", "accept-5281-the-restless-souls", "accept-5282-the-restless-souls", "accept-5542-demon-dogs", "accept-5543-blood-tinged-skies", "accept-5544-carrion-grubbage", "accept-5742-redemption", "accept-5781-of-forgotten-memories", "accept-5845-of-lost-honor", "accept-5846-of-love-and-family", "accept-5848-of-love-and-family" },
            persistCompletion = true,
            complete = { instance = 329 },
        },
        {
            id = "note-click-premius-siabi-tobacco",
            kind = "note",
            priority = 43,
            conditions = { level = { min = 55 } },
            text = "Click Premius Siabi Tobacco.",
        },
        {
            id = "boss-fras-siabi",
            kind = "note",
            priority = 44,
            conditions = { level = { min = 55 } },
            text = "Kill Fras Siabi. It looks like a small wooden crate on the ground. Turn left twice into King's Square. It's a small wooden box on the ground. Spread out as best you can to avoid being hit by 'Flame Breath'. He will use 'Smoke Bomb' which will stun anybody caught by it.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "objective-5214-1-siabi-s-premium-tobacco",
            kind = "objective",
            priority = 45,
            conditions = { level = { min = 55 } },
            text = "Collect Siabi's Premium Tobacco.",
            dependsOn = { "accept-5214-the-great-fras-siabi" },
            complete = QuestState(5214, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-the-bastion-door",
            kind = "note",
            priority = 46,
            conditions = { level = { min = 55 } },
            text = "Click The Bastion Door.",
        },
        {
            id = "note-click-malor-s-strongbox",
            kind = "note",
            priority = 47,
            conditions = { level = { min = 55 } },
            text = "Click Malor's Strongbox.",
        },
        {
            id = "note-click-hall-of-high-command",
            kind = "note",
            priority = 48,
            conditions = { level = { min = 55 } },
            text = "Click Hall of High Command.",
        },
        {
            id = "boss-archivist-galford",
            kind = "note",
            priority = 49,
            conditions = { level = { min = 55 } },
            text = "Kill Archivist Galford. This requires The Scarlet Key from the Scarlet Monastery dungeon or a Rogue with leveled lockpicking to open. Go across the hall from The Hall of Lights to enter The Scarlet Bastion. He is near the end of The Scarlet Bastion across from Grand Crusader Dathrohan. His ability 'Burning Winds' is a high damage DoT that will make this fight healing intensive. If the tank is hit with the ability, the Galford may swap targets.",
            dependsOn = { "boss-fras-siabi" },
        },
        {
            id = "objective-5251-1-archivist-galford",
            kind = "objective",
            priority = 50,
            conditions = { level = { min = 55 } },
            text = "Slay Archivist Galford.",
            dependsOn = { "accept-5251-the-archivist" },
            complete = QuestObjective(5251, 1, "Archivist Galford"),
            useClientPin = true,
        },
        {
            id = "note-click-unfinished-painting",
            kind = "note",
            priority = 51,
            conditions = { level = { min = 55 } },
            text = "Click Unfinished Painting.",
        },
        {
            id = "objective-5848-1-of-love-and-family",
            kind = "objective",
            priority = 52,
            conditions = { level = { min = 52 } },
            text = "Collect Of Love and Family.",
            dependsOn = { "accept-5848-of-love-and-family" },
            complete = QuestState(5848, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-scarlet-archive",
            kind = "note",
            priority = 53,
            conditions = { level = { min = 55 } },
            text = "Click Scarlet Archive.",
        },
        {
            id = "objective-5251-2-burn-the-archive",
            kind = "objective",
            priority = 54,
            conditions = { level = { min = 55 } },
            text = "Burn the Archive.",
            dependsOn = { "accept-5251-the-archivist" },
            complete = QuestObjective(5251, 2, "Burn the Archive"),
            useClientPin = true,
        },
        {
            id = "objective-5282-1-free-15-souls",
            kind = "objective",
            priority = 55,
            conditions = { level = { min = 55 } },
            text = "Free 15 Souls.",
            dependsOn = { "accept-5282-the-restless-souls" },
            complete = QuestState(5282, "complete"),
            useClientPin = true,
        },
        {
            id = "note-leave-the-dungeon",
            kind = "note",
            priority = 56,
            conditions = { level = { min = 55 } },
            text = "Leave the dungeon.",
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 57,
            conditions = { level = { min = 55 } },
            text = "Click Here to Continue.",
        },
        {
            id = "note-click-elders-square-service-gate",
            kind = "note",
            priority = 58,
            conditions = { level = { min = 55 } },
            text = "Click Elders' Square Service Gate.",
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.479, 0.239, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "note-click-service-entrance-gate",
            kind = "note",
            priority = 59,
            conditions = { level = { min = 55 } },
            text = "Click Service Entrance Gate.",
        },
        {
            id = "accept-5122-the-medallion-of-faith",
            kind = "accept",
            priority = 60,
            conditions = { level = { min = 55 } },
            text = "Accept The Medallion of Faith from Aurius.",
            complete = QuestState(5122, "activeOrCompleted"),
        },
        {
            id = "turnin-5282-the-restless-souls",
            kind = "turnin",
            priority = 61,
            conditions = { level = { min = 55 } },
            text = "Turn in The Restless Souls to Egan.",
            dependsOn = { "objective-5282-1-free-15-souls" },
            complete = QuestState(5282, "completed"),
            useClientPin = true,
        },
        {
            id = "turnin-5848-of-love-and-family",
            kind = "turnin",
            priority = 62,
            conditions = { level = { min = 52 } },
            text = "Turn in Of Love and Family to Tirion Fordring.",
            dependsOn = { "objective-5848-1-of-love-and-family" },
            complete = QuestState(5848, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.076, 0.437, "Tirion Fordring", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5214-the-great-fras-siabi",
            kind = "turnin",
            priority = 63,
            conditions = { level = { min = 55 } },
            text = "Turn in The Great Fras Siabi to Smokey LaRue.",
            dependsOn = { "objective-5214-1-siabi-s-premium-tobacco" },
            complete = QuestState(5214, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.806, 0.580, "Smokey LaRue", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5251-the-archivist",
            kind = "turnin",
            priority = 64,
            conditions = { level = { min = 55 } },
            text = "Turn in The Archivist to Duke Nicholas Zverenhoff.",
            dependsOn = { "objective-5251-1-archivist-galford", "objective-5251-2-burn-the-archive" },
            complete = QuestState(5251, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.814, 0.598, "Duke Nicholas Zverenhoff", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "boss-balnazzar",
            kind = "note",
            priority = 65,
            conditions = { level = { min = 55 } },
            text = "Kill Balnazzar. He is the last boss of the Live Side of Stratholme. He is at the very end of The Scarlet Bastion, across from where Archivist Galford was. He uses the 'Domination' ability on random players in the group. Use CC on them to mitigate any damage they might do to the part. Casters should stand at max range to avoid being feared.",
            dependsOn = { "boss-archivist-galford" },
        },
        {
            id = "accept-5262-the-truth-comes-crashing-down",
            kind = "accept",
            priority = 66,
            conditions = { level = { min = 55 } },
            text = "Accept The Truth Comes Crashing Down.",
            complete = QuestState(5262, "activeOrCompleted"),
        },
        {
            id = "turnin-5262-the-truth-comes-crashing-down",
            kind = "turnin",
            priority = 67,
            conditions = { level = { min = 55 } },
            text = "Turn in The Truth Comes Crashing Down to Duke Nicholas Zverenhoff.",
            dependsOn = { "accept-5262-the-truth-comes-crashing-down" },
            complete = QuestState(5262, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.814, 0.598, "Duke Nicholas Zverenhoff", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "boss-skul",
            kind = "note",
            priority = 68,
            conditions = { level = { min = 55 } },
            text = "Kill Skul if the rare is up. This is a rare mob that may not be available. There are two spots he can spawn; Just before Fras Siabi and on the east portion of the map. Interrup its spells when possible.",
            dependsOn = { "boss-balnazzar" },
        },
        {
            id = "boss-hearthsinger-forresten",
            kind = "note",
            priority = 69,
            conditions = { level = { min = 55 } },
            text = "Kill Hearthsinger Forresten if the rare is up. This is a rare mob that may not be available. He can spawn after the rat gate. Spread out a little to avoid being hit with 'Multi-Shot'.",
            dependsOn = { "boss-skul" },
        },
        {
            id = "boss-the-unforgiven",
            kind = "note",
            priority = 70,
            conditions = { level = { min = 55 } },
            text = "Kill The Unforgiven. This boss spawns as you walk through the gate at the opposite end to where Timmy the Cruel is. Be sure your health and mana are healed up before passing through the gate. He will have non elite adds along with him.",
            dependsOn = { "boss-hearthsinger-forresten" },
        },
        {
            id = "boss-postmaster-malown",
            kind = "note",
            priority = 71,
            conditions = { level = { min = 55 } },
            text = "Kill Postmaster Malown. To summon this boss, kill 'Stratholme Couriers' found throughout the instance. Collect the 'Market Row Postbox Keys'. Next, find and open 3 of the locked Mailboxes.",
            dependsOn = { "boss-the-unforgiven" },
        },
        {
            id = "boss-timmy-the-cruel",
            kind = "note",
            priority = 72,
            conditions = { level = { min = 55 } },
            text = "Kill Timmy the Cruel. He will heal while using 'Ravenous Claw', but other than that the fight is straight forward.",
            dependsOn = { "boss-postmaster-malown" },
        },
        {
            id = "boss-malor-the-zealous",
            kind = "note",
            priority = 73,
            conditions = { level = { min = 55 } },
            text = "Kill Malor the Zealous. During the fight, he will use the 'Lay on Hands' ability which will heal him significantly. The chest behind him contains the 'Medallion of Faith' for the quest The Medallion of Faith.",
            dependsOn = { "boss-timmy-the-cruel" },
        },
        {
            id = "boss-crimson-hammersmith",
            kind = "note",
            priority = 74,
            conditions = { level = { min = 55 } },
            text = "Kill Crimson Hammersmith. They are on the floor near boxes in the room. This mob can be skipped if no one in the group needs the 'Bottom Half of Advanced Armorsmithing: Volume II' for Blacksmithing.",
            dependsOn = { "boss-malor-the-zealous" },
        },
        {
            id = "boss-cannon-master-willey",
            kind = "note",
            priority = 75,
            conditions = { level = { min = 55 } },
            text = "Kill Cannon Master Willey. He has no special abilities to account for.",
            dependsOn = { "boss-crimson-hammersmith" },
        },
    },
})
