local _, ns = ...

local MAP = {
    WESTERN_PLAGUELANDS = 1422,
    ARATHI_HIGHLANDS = 1417,
    EASTERN_PLAGUELANDS = 1423,
}

local HORDE = { faction = "Horde" }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-stratholme-undead",
    title = "Stratholme - Undead",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { faction = "Horde" },
            { level = { min = 55 } },
        },
    },
    goals = {
        {
            id = "accept-5382-doctor-theolen-krastinov-the-butcher",
            kind = "accept",
            priority = 10,
            conditions = { level = { min = 55 } },
            text = "Accept Doctor Theolen Krastinov, the Butcher from Eva Sarkhoff. 'The pleasure is mine madam. Might I ask what it is that you are doing here?'.",
            complete = QuestState(5382, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 11,
            conditions = { level = { min = 55 } },
            text = "Enter Stratholme - Undead with your group.",
            dependsOn = { "accept-5382-doctor-theolen-krastinov-the-butcher" },
            persistCompletion = true,
            complete = { instance = 329 },
        },
        {
            id = "objective-5382-2-burn-the-remains-of-eva",
            kind = "objective",
            priority = 14,
            conditions = { level = { min = 55 } },
            text = "Burn the Remains of Eva Sarkhoff.",
            dependsOn = { "accept-5382-doctor-theolen-krastinov-the-butcher" },
            complete = QuestObjective(5382, 2, "Burn the Remains of Eva Sarkhoff"),
            useClientPin = true,
        },
        {
            id = "objective-5382-3-burn-the-remains-of-luci",
            kind = "objective",
            priority = 16,
            conditions = { level = { min = 55 } },
            text = "Burn the Remains of Lucien Sarkhoff.",
            dependsOn = { "accept-5382-doctor-theolen-krastinov-the-butcher" },
            complete = QuestObjective(5382, 3, "Burn the Remains of Lucien Sarkhoff"),
            useClientPin = true,
        },
        {
            id = "objective-5382-1-doctor-theolen-krastinov",
            kind = "objective",
            priority = 17,
            conditions = { level = { min = 55 } },
            text = "Kill Doctor Theolen Krastinov.",
            dependsOn = { "accept-5382-doctor-theolen-krastinov-the-butcher" },
            complete = QuestObjective(5382, 1, "Doctor Theolen Krastinov"),
            useClientPin = true,
        },
        {
            id = "turnin-5382-doctor-theolen-krastinov-the-butcher",
            kind = "turnin",
            priority = 20,
            conditions = { level = { min = 55 } },
            text = "Turn in Doctor Theolen Krastinov, the Butcher to Eva Sarkhoff.",
            dependsOn = { "objective-5382-2-burn-the-remains-of-eva", "objective-5382-3-burn-the-remains-of-luci", "objective-5382-1-doctor-theolen-krastinov" },
            complete = QuestState(5382, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5515-krastinov-s-bag-of-horrors",
            kind = "accept",
            priority = 21,
            conditions = { level = { min = 55 } },
            text = "Accept Krastinov's Bag of Horrors from Eva Sarkhoff.",
            dependsOn = { "turnin-5382-doctor-theolen-krastinov-the-butcher" },
            complete = QuestState(5515, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5515-1-krastinov-s-bag-of-horro",
            kind = "objective",
            priority = 23,
            conditions = { level = { min = 55 } },
            text = "Collect Krastinov's Bag of Horrors.",
            dependsOn = { "accept-5515-krastinov-s-bag-of-horrors" },
            complete = QuestState(5515, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5515-krastinov-s-bag-of-horrors",
            kind = "turnin",
            priority = 24,
            conditions = { level = { min = 55 } },
            text = "Turn in Krastinov's Bag of Horrors to Eva Sarkhoff.",
            dependsOn = { "objective-5515-1-krastinov-s-bag-of-horro" },
            complete = QuestState(5515, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5384-kirtonos-the-herald",
            kind = "accept",
            priority = 25,
            conditions = { level = { min = 55 } },
            text = "Accept Kirtonos the Herald from Eva Sarkhoff.",
            dependsOn = { "turnin-5515-krastinov-s-bag-of-horrors" },
            complete = QuestState(5384, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5384-1-kirtonos-the-herald",
            kind = "objective",
            priority = 27,
            conditions = { level = { min = 55 } },
            text = "Kill Kirtonos the Herald.",
            dependsOn = { "accept-5384-kirtonos-the-herald" },
            complete = QuestState(5384, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5384-kirtonos-the-herald",
            kind = "turnin",
            priority = 28,
            conditions = { level = { min = 55 } },
            text = "Turn in Kirtonos the Herald to Eva Sarkhoff.",
            dependsOn = { "objective-5384-1-kirtonos-the-herald" },
            complete = QuestState(5384, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.702, 0.737, "Eva Sarkhoff", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5461-the-human-ras-frostwhisper",
            kind = "accept",
            priority = 30,
            conditions = { level = { min = 57 } },
            text = "Accept The Human, Ras Frostwhisper from Magistrate Marduke.",
            complete = QuestState(5461, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-5461-1-keepsake-of-remembrance",
            kind = "objective",
            priority = 32,
            conditions = { level = { min = 57 } },
            text = "Collect Keepsake of Remembrance.",
            dependsOn = { "accept-5461-the-human-ras-frostwhisper" },
            complete = QuestState(5461, "complete"),
            route = {
                Point(MAP.ARATHI_HIGHLANDS, 0.179, 0.694, "Arathi Highlands", "Travel to Arathi Highlands."),
            },
        },
        {
            id = "turnin-5461-the-human-ras-frostwhisper",
            kind = "turnin",
            priority = 33,
            conditions = { level = { min = 57 } },
            text = "Turn in The Human, Ras Frostwhisper to Magistrate Marduke.",
            dependsOn = { "objective-5461-1-keepsake-of-remembrance" },
            complete = QuestState(5461, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5462-the-dying-ras-frostwhisper",
            kind = "accept",
            priority = 34,
            conditions = { level = { min = 57 } },
            text = "Accept The Dying, Ras Frostwhisper from Magistrate Marduke.",
            dependsOn = { "turnin-5461-the-human-ras-frostwhisper" },
            complete = QuestState(5462, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.706, 0.741, "Magistrate Marduke", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-5462-the-dying-ras-frostwhisper",
            kind = "turnin",
            priority = 35,
            conditions = { level = { min = 57 } },
            text = "Turn in The Dying, Ras Frostwhisper to Leonid Barthalomew the Revered.",
            dependsOn = { "accept-5462-the-dying-ras-frostwhisper" },
            complete = QuestState(5462, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5463-menethil-s-gift",
            kind = "accept",
            priority = 36,
            conditions = { level = { min = 57 } },
            text = "Accept Menethil's Gift from Leonid Barthalomew the Revered.",
            dependsOn = { "turnin-5462-the-dying-ras-frostwhisper" },
            complete = QuestState(5463, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5251-the-archivist",
            kind = "accept",
            priority = 37,
            conditions = { level = { min = 55 } },
            text = "Accept The Archivist from Duke Nicholas Zverenhoff.",
            complete = QuestState(5251, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.814, 0.598, "Duke Nicholas Zverenhoff", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5251-1-archivist-galford",
            kind = "objective",
            priority = 42,
            conditions = { level = { min = 55 } },
            text = "Slay Archivist Galford.",
            dependsOn = { "accept-5251-the-archivist" },
            complete = QuestObjective(5251, 1, "Archivist Galford"),
            useClientPin = true,
        },
        {
            id = "objective-5251-2-burn-the-archive",
            kind = "objective",
            priority = 44,
            conditions = { level = { min = 55 } },
            text = "Burn the Archive.",
            dependsOn = { "accept-5251-the-archivist" },
            complete = QuestObjective(5251, 2, "Burn the Archive"),
            useClientPin = true,
        },
        {
            id = "turnin-5251-the-archivist",
            kind = "turnin",
            priority = 45,
            conditions = { level = { min = 55 } },
            text = "Turn in The Archivist to Duke Nicholas Zverenhoff.",
            dependsOn = { "objective-5251-1-archivist-galford", "objective-5251-2-burn-the-archive" },
            complete = QuestState(5251, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.814, 0.598, "Duke Nicholas Zverenhoff", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5262-the-truth-comes-crashing-down",
            kind = "accept",
            priority = 47,
            conditions = { level = { min = 55 } },
            text = "Accept The Truth Comes Crashing Down.",
            complete = QuestState(5262, "activeOrCompleted"),
        },
        {
            id = "turnin-5262-the-truth-comes-crashing-down",
            kind = "turnin",
            priority = 48,
            conditions = { level = { min = 55 } },
            text = "Turn in The Truth Comes Crashing Down to Duke Nicholas Zverenhoff.",
            dependsOn = { "accept-5262-the-truth-comes-crashing-down" },
            complete = QuestState(5262, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.814, 0.598, "Duke Nicholas Zverenhoff", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5263-above-and-beyond",
            kind = "accept",
            priority = 49,
            conditions = { level = { min = 55 } },
            text = "Accept Above and Beyond from Duke Nicholas Zverenhoff.",
            dependsOn = { "turnin-5262-the-truth-comes-crashing-down" },
            complete = QuestState(5263, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.814, 0.598, "Duke Nicholas Zverenhoff", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5212-the-flesh-does-not-lie",
            kind = "accept",
            priority = 50,
            conditions = { level = { min = 55 } },
            text = "Accept The Flesh Does Not Lie from Betina Bigglezink.",
            complete = QuestState(5212, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5243-houses-of-the-holy",
            kind = "accept",
            priority = 51,
            conditions = { level = { min = 55 } },
            text = "Accept Houses of the Holy from Leonid Barthalomew the Revered.",
            complete = QuestState(5243, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5122-the-medallion-of-faith",
            kind = "accept",
            priority = 54,
            conditions = { level = { min = 55 } },
            text = "Accept The Medallion of Faith from Aurius.",
            complete = QuestState(5122, "activeOrCompleted"),
        },
        {
            id = "objective-5263-1-head-of-baron-rivendare",
            kind = "objective",
            priority = 56,
            conditions = { level = { min = 55 } },
            text = "Collect Head of Baron Rivendare.",
            dependsOn = { "accept-5263-above-and-beyond" },
            complete = QuestState(5263, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-5125-aurius-reckoning",
            kind = "accept",
            priority = 57,
            conditions = { level = { min = 55 } },
            text = "Accept Aurius' Reckoning from Aurius.",
            complete = QuestState(5125, "activeOrCompleted"),
        },
        {
            id = "turnin-5463-menethil-s-gift",
            kind = "turnin",
            priority = 59,
            conditions = { level = { min = 57 } },
            text = "Turn in Menethil's Gift.",
            dependsOn = { "accept-5463-menethil-s-gift" },
            complete = QuestState(5463, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-5464-menethil-s-gift",
            kind = "accept",
            priority = 60,
            conditions = { level = { min = 57 } },
            text = "Accept Menethil's Gift.",
            dependsOn = { "turnin-5463-menethil-s-gift" },
            complete = QuestState(5464, "activeOrCompleted"),
        },
        {
            id = "objective-5212-1-plagued-flesh-sample",
            kind = "objective",
            priority = 62,
            conditions = { level = { min = 55 } },
            text = "Collect 20 Plagued Flesh Sample.",
            dependsOn = { "accept-5212-the-flesh-does-not-lie" },
            complete = QuestState(5212, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-5243-1-stratholme-holy-water",
            kind = "objective",
            priority = 64,
            conditions = { level = { min = 55 } },
            text = "Collect 5 Stratholme Holy Water.",
            dependsOn = { "accept-5243-houses-of-the-holy" },
            complete = QuestState(5243, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5263-above-and-beyond",
            kind = "turnin",
            priority = 65,
            conditions = { level = { min = 55 } },
            text = "Turn in Above and Beyond to Duke Nicholas Zverenhoff.",
            dependsOn = { "objective-5263-1-head-of-baron-rivendare" },
            complete = QuestState(5263, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.814, 0.598, "Duke Nicholas Zverenhoff", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5212-the-flesh-does-not-lie",
            kind = "turnin",
            priority = 66,
            conditions = { level = { min = 55 } },
            text = "Turn in The Flesh Does Not Lie to Betina Bigglezink.",
            dependsOn = { "objective-5212-1-plagued-flesh-sample" },
            complete = QuestState(5212, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-5213-the-active-agent",
            kind = "accept",
            priority = 67,
            conditions = { level = { min = 55 } },
            text = "Accept The Active Agent from Betina Bigglezink.",
            dependsOn = { "turnin-5212-the-flesh-does-not-lie" },
            complete = QuestState(5213, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5464-menethil-s-gift",
            kind = "turnin",
            priority = 68,
            conditions = { level = { min = 57 } },
            text = "Turn in Menethil's Gift to Leonid Barthalomew the Revered.",
            dependsOn = { "accept-5464-menethil-s-gift" },
            complete = QuestState(5464, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-5243-houses-of-the-holy",
            kind = "turnin",
            priority = 69,
            conditions = { level = { min = 55 } },
            text = "Turn in Houses of the Holy to Leonid Barthalomew the Revered.",
            dependsOn = { "objective-5243-1-stratholme-holy-water" },
            complete = QuestState(5243, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.817, 0.578, "Leonid Barthalomew the Revered", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-5213-1-scourge-data",
            kind = "objective",
            priority = 71,
            conditions = { level = { min = 55 } },
            text = "Collect Scourge Data.",
            dependsOn = { "accept-5213-the-active-agent" },
            complete = QuestState(5213, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-5213-the-active-agent",
            kind = "turnin",
            priority = 72,
            conditions = { level = { min = 55 } },
            text = "Turn in The Active Agent to Betina Bigglezink.",
            dependsOn = { "objective-5213-1-scourge-data" },
            complete = QuestState(5213, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.815, 0.597, "Betina Bigglezink", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-6022-to-kill-with-purpose",
            kind = "accept",
            priority = 73,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept To Kill With Purpose from Nathanos Blightcaller.",
            complete = QuestState(6022, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-6133-the-ranger-lord-s-behest",
            kind = "accept",
            priority = 74,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Accept The Ranger Lord's Behest from Nathanos Blightcaller.",
            complete = QuestState(6133, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-6042-un-life-s-little-annoyances",
            kind = "accept",
            priority = 75,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept Un-Life's Little Annoyances from Nathanos Blightcaller.",
            complete = QuestState(6042, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6042-1-noxious-plaguebat",
            kind = "objective",
            priority = 76,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Kill 20 Noxious Plaguebat.",
            dependsOn = { "accept-6042-un-life-s-little-annoyances" },
            complete = QuestObjective(6042, 1, "Noxious Plaguebat"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.620, 0.612, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6022-1-coagulated-rot",
            kind = "objective",
            priority = 77,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Collect Coagulated Rot.",
            dependsOn = { "accept-6022-to-kill-with-purpose" },
            complete = QuestState(6022, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.600, 0.683, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6042-2-monstrous-plaguebat",
            kind = "objective",
            priority = 78,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Kill 10 Monstrous Plaguebat.",
            dependsOn = { "accept-6042-un-life-s-little-annoyances" },
            complete = QuestObjective(6042, 2, "Monstrous Plaguebat"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.609, 0.488, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6133-4-quel-thalas-registry",
            kind = "objective",
            priority = 80,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Collect Quel'Thalas Registry.",
            dependsOn = { "accept-6133-the-ranger-lord-s-behest" },
            complete = QuestObjective(6133, 4, "Quel'Thalas Registry"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.521, 0.183, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6133-1-pathstrider",
            kind = "objective",
            priority = 81,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Kill Pathstrider.",
            dependsOn = { "accept-6133-the-ranger-lord-s-behest" },
            complete = QuestObjective(6133, 1, "Pathstrider"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.528, 0.187, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6133-2-ranger",
            kind = "objective",
            priority = 82,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Kill Ranger.",
            dependsOn = { "accept-6133-the-ranger-lord-s-behest" },
            complete = QuestObjective(6133, 2, "Ranger"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.528, 0.187, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6133-3-woodsman",
            kind = "objective",
            priority = 83,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Kill Woodsman.",
            dependsOn = { "accept-6133-the-ranger-lord-s-behest" },
            complete = QuestObjective(6133, 3, "Woodsman"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.528, 0.187, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-6022-to-kill-with-purpose",
            kind = "turnin",
            priority = 84,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in To Kill With Purpose to Nathanos Blightcaller.",
            dependsOn = { "objective-6022-1-coagulated-rot" },
            complete = QuestState(6022, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-6133-the-ranger-lord-s-behest",
            kind = "turnin",
            priority = 85,
            conditions = { all = { { faction = "Horde" }, { level = { min = 54 } } } },
            text = "Turn in The Ranger Lord's Behest to Nathanos Blightcaller.",
            dependsOn = { "objective-6133-4-quel-thalas-registry", "objective-6133-1-pathstrider", "objective-6133-2-ranger", "objective-6133-3-woodsman" },
            complete = QuestState(6133, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-6042-un-life-s-little-annoyances",
            kind = "turnin",
            priority = 86,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in Un-Life's Little Annoyances to Nathanos Blightcaller.",
            dependsOn = { "objective-6042-1-noxious-plaguebat", "objective-6042-2-monstrous-plaguebat" },
            complete = QuestState(6042, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-6135-duskwing-oh-how-i-hate-thee",
            kind = "accept",
            priority = 87,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept Duskwing, Oh How I Hate Thee from Nathanos Blightcaller.",
            dependsOn = { "turnin-6042-un-life-s-little-annoyances" },
            complete = QuestState(6135, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-6136-the-corpulent-one",
            kind = "accept",
            priority = 88,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept The Corpulent One from Nathanos Blightcaller.",
            complete = QuestState(6136, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6135-1-patch-of-duskwing-s-fur",
            kind = "objective",
            priority = 90,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Collect Patch of Duskwing's Fur.",
            dependsOn = { "accept-6135-duskwing-oh-how-i-hate-thee" },
            complete = QuestState(6135, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.312, 0.723, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6136-1-borelgore",
            kind = "objective",
            priority = 91,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Kill Borelgore.",
            dependsOn = { "accept-6136-the-corpulent-one" },
            complete = QuestState(6136, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-6135-duskwing-oh-how-i-hate-thee",
            kind = "turnin",
            priority = 92,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in Duskwing, Oh How I Hate Thee to Nathanos Blightcaller.",
            dependsOn = { "objective-6135-1-patch-of-duskwing-s-fur" },
            complete = QuestState(6135, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-6136-the-corpulent-one",
            kind = "turnin",
            priority = 93,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in The Corpulent One to Nathanos Blightcaller.",
            dependsOn = { "objective-6136-1-borelgore" },
            complete = QuestState(6136, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "accept-6163-ramstein",
            kind = "accept",
            priority = 94,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Accept Ramstein from Nathanos Blightcaller.",
            dependsOn = { "turnin-6136-the-corpulent-one" },
            complete = QuestState(6163, "activeOrCompleted"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "objective-6163-1-head-of-ramstein-the-gor",
            kind = "objective",
            priority = 102,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Collect Head of Ramstein the Gorger.",
            dependsOn = { "accept-6163-ramstein" },
            complete = QuestState(6163, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-6163-ramstein",
            kind = "turnin",
            priority = 103,
            conditions = { all = { { faction = "Horde" }, { level = { min = 56 } } } },
            text = "Turn in Ramstein to Nathanos Blightcaller.",
            dependsOn = { "objective-6163-1-head-of-ramstein-the-gor" },
            complete = QuestState(6163, "completed"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.265, 0.747, "Nathanos Blightcaller", "Travel to Eastern Plaguelands."),
            },
        },
    },
})
