-- TODO: Convert this guide to Forever before loading it.
-- Not shipped. Onyxia's Lair is the only raid content confirmed in Forever.

local _, ns = ...

local MAP = {
    STORMWIND_CITY = 1453,
    THUNDER_BLUFF = 1456,
    DARNASSUS = 1457,
    UN_GORO_CRATER = 1449,
    AZSHARA = 1447,
    WESTERN_PLAGUELANDS = 1422,
    WINTERSPRING = 1452,
    ALTERAC_MOUNTAINS = 1416,
    FELWOOD = 1448,
    SWAMP_OF_SORROWS = 1435,
    BLASTED_LANDS = 1419,
    THE_HINTERLANDS = 1425,
    TANARIS = 1446,
    FERALAS = 1444,
    THE_BARRENS = 1413,
    STRANGLETHORN_VALE = 1434,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-sunken-temple-raid",
    title = "Sunken Temple Raid",
    category = "Raid Quests",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 25 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-8250-magecraft",
            kind = "accept",
            priority = 10,
            conditions = { level = { min = 50 } },
            text = "Accept Magecraft from Maginor Dumas.",
            complete = QuestState(8250, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.382, 0.819, "Maginor Dumas", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-8415-chillwind-point",
            kind = "accept",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Chillwind Point from Lord Grayson Shadowbreaker.",
            complete = QuestState(8415, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.371, 0.333, "Lord Grayson Shadowbreaker", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-8254-cenarion-aid",
            kind = "accept",
            priority = 12,
            conditions = { level = { min = 50 } },
            text = "Accept Cenarion Aid from Brother Joshua.",
            complete = QuestState(8254, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.388, 0.264, "Brother Joshua", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-8233-a-simple-request",
            kind = "accept",
            priority = 13,
            conditions = { level = { min = 50 } },
            text = "Accept A Simple Request from Lord Tony Romano.",
            complete = QuestState(8233, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.783, 0.570, "Lord Tony Romano", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-8419-an-imp-s-request",
            kind = "accept",
            priority = 14,
            conditions = { level = { min = 50 } },
            text = "Accept An Imp's Request from Demisette Cloyce.",
            complete = QuestState(8419, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.253, 0.782, "Demisette Cloyce", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-8417-a-troubled-spirit",
            kind = "accept",
            priority = 15,
            conditions = { level = { min = 50 } },
            text = "Accept A Troubled Spirit from Wu Shen.",
            complete = QuestState(8417, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.787, 0.458, "Wu Shen", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-9063-torwa-pathfinder-goto-darnassus-35-38-8-41",
            kind = "accept",
            priority = 16,
            conditions = { level = { min = 50 } },
            text = "Accept Torwa Pathfinder|goto Darnassus 35.38,8.41 from Mathrengyl Bearwalker.",
            complete = QuestState(9063, "activeOrCompleted"),
            route = {
                Point(MAP.THUNDER_BLUFF, 0.766, 0.276, "Mathrengyl Bearwalker", "Travel to Thunder Bluff."),
            },
        },
        {
            id = "accept-8151-the-hunter-s-charm",
            kind = "accept",
            priority = 17,
            conditions = { level = { min = 50 } },
            text = "Accept The Hunter's Charm from Ormak Grimshot.",
            complete = QuestState(8151, "activeOrCompleted"),
            route = {
                Point(MAP.DARNASSUS, 0.422, 0.073, "Dorion", "Travel to Darnassus."),
            },
        },
        {
            id = "turnin-9063-torwa-pathfinder",
            kind = "turnin",
            priority = 18,
            conditions = { level = { min = 50 } },
            text = "Turn in Torwa Pathfinder to Torwa Pathfinder.",
            dependsOn = { "accept-9063-torwa-pathfinder-goto-darnassus-35-38-8-41" },
            complete = QuestState(9063, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.716, 0.760, "Torwa Pathfinder", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "accept-9052-bloodpetal-poison",
            kind = "accept",
            priority = 19,
            conditions = { level = { min = 50 } },
            text = "Accept Bloodpetal Poison from Torwa Pathfinder.",
            dependsOn = { "turnin-9063-torwa-pathfinder" },
            complete = QuestState(9052, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.716, 0.760, "Torwa Pathfinder", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-9052-1-gorishi-sting",
            kind = "objective",
            priority = 21,
            conditions = { level = { min = 50 } },
            text = "Collect 8 Gorishi Sting.",
            dependsOn = { "accept-9052-bloodpetal-poison" },
            complete = QuestObjective(9052, 1, "Gorishi Sting"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.504, 0.786, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-9052-2-bloodcap",
            kind = "objective",
            priority = 23,
            conditions = { level = { min = 50 } },
            text = "Collect 8 Bloodcap.",
            dependsOn = { "accept-9052-bloodpetal-poison" },
            complete = QuestObjective(9052, 2, "Bloodcap"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.719, 0.574, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-9052-bloodpetal-poison",
            kind = "turnin",
            priority = 24,
            conditions = { level = { min = 50 } },
            text = "Turn in Bloodpetal Poison to Torwa Pathfinder.",
            dependsOn = { "objective-9052-1-gorishi-sting", "objective-9052-2-bloodcap" },
            complete = QuestState(9052, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.716, 0.760, "Torwa Pathfinder", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "accept-9051-toxic-test",
            kind = "accept",
            priority = 25,
            conditions = { level = { min = 50 } },
            text = "Accept Toxic Test from Torwa Pathfinder.",
            dependsOn = { "turnin-9052-bloodpetal-poison" },
            complete = QuestState(9051, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.716, 0.760, "Torwa Pathfinder", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-9051-1-stab-a-devilsaur-with-th",
            kind = "objective",
            priority = 26,
            conditions = { level = { min = 50 } },
            text = "Stab a Devilsaur with the Barb.",
            dependsOn = { "accept-9051-toxic-test" },
            complete = QuestState(9051, "complete"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.673, 0.339, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-9051-toxic-test",
            kind = "turnin",
            priority = 27,
            conditions = { level = { min = 50 } },
            text = "Turn in Toxic Test to Torwa Pathfinder.",
            dependsOn = { "objective-9051-1-stab-a-devilsaur-with-th" },
            complete = QuestState(9051, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.716, 0.760, "Torwa Pathfinder", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "accept-9053-a-better-ingredient",
            kind = "accept",
            priority = 28,
            conditions = { all = { { race = 4 }, { class = 11 }, { level = { min = 50 } } } },
            text = "Accept A Better Ingredient from Torwa Pathfinder.",
            dependsOn = { "turnin-9051-toxic-test" },
            complete = QuestState(9053, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.716, 0.760, "Torwa Pathfinder", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-8151-the-hunter-s-charm",
            kind = "turnin",
            priority = 29,
            conditions = { level = { min = 50 } },
            text = "Turn in The Hunter's Charm to Ogtinc.",
            dependsOn = { "accept-8151-the-hunter-s-charm" },
            complete = QuestState(8151, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8153-courser-antlers",
            kind = "accept",
            priority = 30,
            conditions = { level = { min = 50 } },
            text = "Accept Courser Antlers from Ogtinc.",
            dependsOn = { "turnin-8151-the-hunter-s-charm" },
            complete = QuestState(8153, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "objective-8153-1-perfect-courser-antler",
            kind = "objective",
            priority = 32,
            conditions = { level = { min = 50 } },
            text = "Collect 2 Perfect Courser Antler.",
            dependsOn = { "accept-8153-courser-antlers" },
            complete = QuestState(8153, "complete"),
            route = {
                Point(MAP.AZSHARA, 0.495, 0.176, "Azshara", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8153-courser-antlers",
            kind = "turnin",
            priority = 33,
            conditions = { level = { min = 50 } },
            text = "Turn in Courser Antlers to Ogtinc.",
            dependsOn = { "objective-8153-1-perfect-courser-antler" },
            complete = QuestState(8153, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8231-wavethrashing",
            kind = "accept",
            priority = 34,
            conditions = { level = { min = 50 } },
            text = "Accept Wavethrashing from Ogtinc.",
            dependsOn = { "turnin-8153-courser-antlers" },
            complete = QuestState(8231, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "objective-8231-1-wavethrasher-scale",
            kind = "objective",
            priority = 36,
            conditions = { level = { min = 50 } },
            text = "Collect 6 Wavethrasher Scale.",
            dependsOn = { "accept-8231-wavethrashing" },
            complete = QuestState(8231, "complete"),
            route = {
                Point(MAP.AZSHARA, 0.526, 0.419, "Azshara", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8231-wavethrashing",
            kind = "turnin",
            priority = 37,
            conditions = { level = { min = 50 } },
            text = "Turn in Wavethrashing to Ogtinc.",
            dependsOn = { "objective-8231-1-wavethrasher-scale" },
            complete = QuestState(8231, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8232-the-green-drake",
            kind = "accept",
            priority = 38,
            conditions = { all = { { class = 3 }, { level = { min = 50 } } } },
            text = "Accept The Green Drake from Ogtinc.",
            dependsOn = { "turnin-8231-wavethrashing" },
            complete = QuestState(8232, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8250-magecraft",
            kind = "turnin",
            priority = 39,
            conditions = { level = { min = 50 } },
            text = "Turn in Magecraft to Sanath Lim-yo.",
            dependsOn = { "accept-8250-magecraft" },
            complete = QuestState(8250, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.281, 0.501, "Sanath Lim-yo", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8251-magic-dust",
            kind = "accept",
            priority = 40,
            conditions = { level = { min = 50 } },
            text = "Accept Magic Dust from Archmage Xylem.",
            complete = QuestState(8251, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.281, 0.501, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "objective-8251-1-glittering-dust",
            kind = "objective",
            priority = 42,
            conditions = { level = { min = 50 } },
            text = "Collect 10 Glittering Dust.",
            dependsOn = { "accept-8251-magic-dust" },
            complete = QuestState(8251, "complete"),
            route = {
                Point(MAP.AZSHARA, 0.569, 0.293, "Azshara", "Travel to Azshara."),
            },
        },
        {
            id = "accept-3503-meeting-with-the-master",
            kind = "accept",
            priority = 43,
            conditions = { level = { min = 45 } },
            text = "Accept Meeting with the Master from Sanath Lim-yo.",
            complete = QuestState(3503, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.281, 0.501, "Sanath Lim-yo", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8251-magic-dust",
            kind = "turnin",
            priority = 44,
            conditions = { level = { min = 50 } },
            text = "Turn in Magic Dust to Archmage Xylem.",
            dependsOn = { "objective-8251-1-glittering-dust" },
            complete = QuestState(8251, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.281, 0.501, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8252-the-siren-s-coral",
            kind = "accept",
            priority = 45,
            conditions = { level = { min = 50 } },
            text = "Accept The Siren's Coral from Archmage Xylem.",
            dependsOn = { "turnin-8251-magic-dust" },
            complete = QuestState(8252, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.281, 0.501, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "objective-8252-1-enchanted-coral",
            kind = "objective",
            priority = 47,
            conditions = { level = { min = 50 } },
            text = "Collect 6 Enchanted Coral.",
            dependsOn = { "accept-8252-the-siren-s-coral" },
            complete = QuestState(8252, "complete"),
            route = {
                Point(MAP.AZSHARA, 0.476, 0.439, "Azshara", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8252-the-siren-s-coral",
            kind = "turnin",
            priority = 48,
            conditions = { level = { min = 50 } },
            text = "Turn in The Siren's Coral to Archmage Xylem.",
            dependsOn = { "objective-8252-1-enchanted-coral" },
            complete = QuestState(8252, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.281, 0.501, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8253-destroy-morphaz",
            kind = "accept",
            priority = 49,
            conditions = { all = { { class = 8 }, { level = { min = 50 } } } },
            text = "Accept Destroy Morphaz from Archmage Xylem.",
            dependsOn = { "turnin-8252-the-siren-s-coral" },
            complete = QuestState(8253, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.281, 0.501, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8415-chillwind-point",
            kind = "turnin",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Chillwind Point to Commander Ashlam Valorfist.",
            dependsOn = { "accept-8415-chillwind-point" },
            complete = QuestState(8415, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-8414-dispelling-evil",
            kind = "accept",
            priority = 51,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Dispelling Evil from Commander Ashlam Valorfist.",
            dependsOn = { "turnin-8415-chillwind-point" },
            complete = QuestState(8414, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-8414-1-minion-s-scourgestone",
            kind = "objective",
            priority = 53,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect 20 Minion's Scourgestone.",
            dependsOn = { "accept-8414-dispelling-evil" },
            complete = QuestState(8414, "complete"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.406, 0.703, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-8414-dispelling-evil",
            kind = "turnin",
            priority = 54,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Dispelling Evil to High Priest Thel'danis.",
            dependsOn = { "objective-8414-1-minion-s-scourgestone" },
            complete = QuestState(8414, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.521, 0.833, "High Priest Thel'danis", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-8416-inert-scourgestones",
            kind = "accept",
            priority = 55,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Inert Scourgestones from High Priest Thel'danis.",
            dependsOn = { "turnin-8414-dispelling-evil" },
            complete = QuestState(8416, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.521, 0.833, "High Priest Thel'danis", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-8416-inert-scourgestones",
            kind = "turnin",
            priority = 56,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Inert Scourgestones to Commander Ashlam Valorfist.",
            dependsOn = { "accept-8416-inert-scourgestones" },
            complete = QuestState(8416, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-8418-forging-the-mightstone",
            kind = "accept",
            priority = 57,
            conditions = { all = { { faction = "Alliance" }, { class = 2 }, { level = { min = 50 } } } },
            text = "Accept Forging the Mightstone from Commander Ashlam Valorfist.",
            dependsOn = { "turnin-8416-inert-scourgestones" },
            complete = QuestState(8418, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-8254-cenarion-aid",
            kind = "turnin",
            priority = 58,
            conditions = { level = { min = 50 } },
            text = "Turn in Cenarion Aid to Ogtinc.",
            dependsOn = { "accept-8254-cenarion-aid" },
            complete = QuestState(8254, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8255-of-coursers-we-know",
            kind = "accept",
            priority = 59,
            conditions = { level = { min = 50 } },
            text = "Accept Of Coursers We know from Ogtinc.",
            dependsOn = { "turnin-8254-cenarion-aid" },
            complete = QuestState(8255, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "objective-8255-1-healthy-courser-gland",
            kind = "objective",
            priority = 60,
            conditions = { level = { min = 50 } },
            text = "Collect 4 Healthy Courser Gland.",
            dependsOn = { "accept-8255-of-coursers-we-know" },
            complete = QuestState(8255, "complete"),
            route = {
                Point(MAP.AZSHARA, 0.495, 0.176, "Azshara", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8255-of-coursers-we-know",
            kind = "turnin",
            priority = 61,
            conditions = { level = { min = 50 } },
            text = "Turn in Of Coursers We know to Ogtinc.",
            dependsOn = { "objective-8255-1-healthy-courser-gland" },
            complete = QuestState(8255, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8256-the-ichor-of-undeath",
            kind = "accept",
            priority = 62,
            conditions = { level = { min = 50 } },
            text = "Accept The Ichor of Undeath from Ogtinc.",
            dependsOn = { "turnin-8255-of-coursers-we-know" },
            complete = QuestState(8256, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "objective-8256-1-ichor-of-undeath",
            kind = "objective",
            priority = 64,
            conditions = { level = { min = 50 } },
            text = "Collect Ichor of Undeath.",
            dependsOn = { "accept-8256-the-ichor-of-undeath" },
            complete = QuestState(8256, "complete"),
            route = {
                Point(MAP.WINTERSPRING, 0.526, 0.407, "Winterspring", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-8256-the-ichor-of-undeath",
            kind = "turnin",
            priority = 65,
            conditions = { level = { min = 50 } },
            text = "Turn in The Ichor of Undeath to Ogtinc.",
            dependsOn = { "objective-8256-1-ichor-of-undeath" },
            complete = QuestState(8256, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8257-blood-of-morphaz",
            kind = "accept",
            priority = 66,
            conditions = { all = { { class = 5 }, { level = { min = 50 } } } },
            text = "Accept Blood of Morphaz from Ogtinc.",
            dependsOn = { "turnin-8256-the-ichor-of-undeath" },
            complete = QuestState(8257, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8233-a-simple-request",
            kind = "turnin",
            priority = 67,
            conditions = { level = { min = 50 } },
            text = "Turn in A Simple Request to Lord Jorach Ravenholdt.",
            dependsOn = { "accept-8233-a-simple-request" },
            complete = QuestState(8233, "completed"),
            route = {
                Point(MAP.ALTERAC_MOUNTAINS, 0.860, 0.789, "Lord Jorach Ravenholdt", "Travel to Alterac Mountains."),
            },
        },
        {
            id = "accept-8234-sealed-azure-bag",
            kind = "accept",
            priority = 68,
            conditions = { level = { min = 50 } },
            text = "Accept Sealed Azure Bag from Lord Jorach Ravenholdt.",
            dependsOn = { "turnin-8233-a-simple-request" },
            complete = QuestState(8234, "activeOrCompleted"),
            route = {
                Point(MAP.ALTERAC_MOUNTAINS, 0.860, 0.789, "Lord Jorach Ravenholdt", "Travel to Alterac Mountains."),
            },
        },
        {
            id = "objective-8234-1-sealed-azure-bag",
            kind = "objective",
            priority = 70,
            conditions = { level = { min = 50 } },
            text = "Collect Sealed Azure Bag.",
            dependsOn = { "accept-8234-sealed-azure-bag" },
            complete = QuestState(8234, "complete"),
            route = {
                Point(MAP.AZSHARA, 0.438, 0.256, "Azshara", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8234-sealed-azure-bag",
            kind = "turnin",
            priority = 71,
            conditions = { level = { min = 50 } },
            text = "Turn in Sealed Azure Bag to Archmage Xylem.",
            dependsOn = { "objective-8234-1-sealed-azure-bag" },
            complete = QuestState(8234, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.297, 0.405, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8235-encoded-fragments",
            kind = "accept",
            priority = 72,
            conditions = { level = { min = 50 } },
            text = "Accept Encoded Fragments from Archmage Xylem.",
            dependsOn = { "turnin-8234-sealed-azure-bag" },
            complete = QuestState(8235, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.297, 0.405, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "accept-3421-return-trip",
            kind = "accept",
            priority = 73,
            conditions = { level = { min = 45 } },
            text = "Accept Return Trip from Nyrill.",
            complete = QuestState(3421, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.361, 0.678, "Nyrill", "Travel to Azshara."),
            },
        },
        {
            id = "objective-8235-1-encoded-fragment",
            kind = "objective",
            priority = 75,
            conditions = { level = { min = 50 } },
            text = "Collect 10 Encoded Fragment.",
            dependsOn = { "accept-8235-encoded-fragments" },
            complete = QuestState(8235, "complete"),
            route = {
                Point(MAP.AZSHARA, 0.734, 0.252, "Azshara", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8235-encoded-fragments",
            kind = "turnin",
            priority = 76,
            conditions = { level = { min = 50 } },
            text = "Turn in Encoded Fragments to Archmage Xylem.",
            dependsOn = { "objective-8235-1-encoded-fragment" },
            complete = QuestState(8235, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.297, 0.405, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "accept-8236-the-azure-key",
            kind = "accept",
            priority = 77,
            conditions = { all = { { class = 4 }, { level = { min = 50 } } } },
            text = "Accept The Azure Key from Archmage Xylem.",
            dependsOn = { "turnin-8235-encoded-fragments" },
            complete = QuestState(8236, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.297, 0.405, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8419-an-imp-s-request",
            kind = "turnin",
            priority = 78,
            conditions = { level = { min = 50 } },
            text = "Turn in An Imp's Request to Impsy.",
            dependsOn = { "accept-8419-an-imp-s-request" },
            complete = QuestState(8419, "completed"),
            route = {
                Point(MAP.FELWOOD, 0.414, 0.450, "Impsy", "Travel to Felwood."),
            },
        },
        {
            id = "accept-8421-the-wrong-stuff",
            kind = "accept",
            priority = 79,
            conditions = { level = { min = 50 } },
            text = "Accept The Wrong Stuff from Impsy.",
            dependsOn = { "turnin-8419-an-imp-s-request" },
            complete = QuestState(8421, "activeOrCompleted"),
            route = {
                Point(MAP.FELWOOD, 0.414, 0.450, "Impsy", "Travel to Felwood."),
            },
        },
        {
            id = "objective-8421-2-bloodvenom-essence",
            kind = "objective",
            priority = 81,
            conditions = { level = { min = 50 } },
            text = "Collect 4 Bloodvenom Essence.",
            dependsOn = { "accept-8421-the-wrong-stuff" },
            complete = QuestObjective(8421, 2, "Bloodvenom Essence"),
            route = {
                Point(MAP.FELWOOD, 0.409, 0.468, "Felwood", "Travel to Felwood."),
            },
        },
        {
            id = "objective-8421-1-rotting-wood",
            kind = "objective",
            priority = 82,
            conditions = { level = { min = 50 } },
            text = "Collect 10 Rotting Wood.",
            dependsOn = { "accept-8421-the-wrong-stuff" },
            complete = QuestObjective(8421, 1, "Rotting Wood"),
            route = {
                Point(MAP.FELWOOD, 0.469, 0.242, "Felwood", "Travel to Felwood."),
            },
        },
        {
            id = "turnin-8421-the-wrong-stuff",
            kind = "turnin",
            priority = 83,
            conditions = { level = { min = 50 } },
            text = "Turn in The Wrong Stuff to Impsy.",
            dependsOn = { "objective-8421-2-bloodvenom-essence", "objective-8421-1-rotting-wood" },
            complete = QuestState(8421, "completed"),
            route = {
                Point(MAP.FELWOOD, 0.414, 0.450, "Impsy", "Travel to Felwood."),
            },
        },
        {
            id = "accept-8422-trolls-of-a-feather",
            kind = "accept",
            priority = 84,
            conditions = { all = { { class = 9 }, { level = { min = 50 } } } },
            text = "Accept Trolls of a Feather from Impsy.",
            dependsOn = { "turnin-8421-the-wrong-stuff" },
            complete = QuestState(8422, "activeOrCompleted"),
            route = {
                Point(MAP.FELWOOD, 0.414, 0.450, "Impsy", "Travel to Felwood."),
            },
        },
        {
            id = "turnin-8417-a-troubled-spirit",
            kind = "turnin",
            priority = 85,
            conditions = { level = { min = 50 } },
            text = "Turn in A Troubled Spirit to Fallen Hero of the Horde.",
            dependsOn = { "accept-8417-a-troubled-spirit" },
            complete = QuestState(8417, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.343, 0.662, "Fallen Hero of the Horde", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-8423-warrior-kinship",
            kind = "accept",
            priority = 86,
            conditions = { level = { min = 50 } },
            text = "Accept Warrior Kinship from Fallen Hero of the Horde.",
            dependsOn = { "turnin-8417-a-troubled-spirit" },
            complete = QuestState(8423, "activeOrCompleted"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.343, 0.662, "Fallen Hero of the Horde", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "objective-8423-1-helboar",
            kind = "objective",
            priority = 87,
            conditions = { level = { min = 50 } },
            text = "Kill 7 Helboar.",
            dependsOn = { "accept-8423-warrior-kinship" },
            complete = QuestState(8423, "complete"),
            route = {
                Point(MAP.BLASTED_LANDS, 0.513, 0.534, "Blasted Lands", "Travel to Blasted Lands."),
            },
        },
        {
            id = "turnin-8423-warrior-kinship",
            kind = "turnin",
            priority = 88,
            conditions = { level = { min = 50 } },
            text = "Turn in Warrior Kinship to Fallen Hero of the Horde.",
            dependsOn = { "objective-8423-1-helboar" },
            complete = QuestState(8423, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.343, 0.662, "Fallen Hero of the Horde", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-8424-war-on-the-shadowsworn",
            kind = "accept",
            priority = 89,
            conditions = { level = { min = 50 } },
            text = "Accept War on the Shadowsworn from Fallen Hero of the Horde.",
            dependsOn = { "turnin-8423-warrior-kinship" },
            complete = QuestState(8424, "activeOrCompleted"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.343, 0.662, "Fallen Hero of the Horde", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "objective-8424-1-shadowsworn-adept",
            kind = "objective",
            priority = 90,
            conditions = { level = { min = 50 } },
            text = "Kill 20 Shadowsworn Adept.",
            dependsOn = { "accept-8424-war-on-the-shadowsworn" },
            complete = QuestObjective(8424, 1, "Shadowsworn Adept"),
            route = {
                Point(MAP.BLASTED_LANDS, 0.652, 0.328, "Blasted Lands", "Travel to Blasted Lands."),
            },
        },
        {
            id = "objective-8424-2-shadowsworn-cultist",
            kind = "objective",
            priority = 91,
            conditions = { level = { min = 50 } },
            text = "Kill 10 Shadowsworn Cultist.",
            dependsOn = { "accept-8424-war-on-the-shadowsworn" },
            complete = QuestObjective(8424, 2, "Shadowsworn Cultist"),
            route = {
                Point(MAP.BLASTED_LANDS, 0.652, 0.328, "Blasted Lands", "Travel to Blasted Lands."),
            },
        },
        {
            id = "objective-8424-3-shadowsworn-thug",
            kind = "objective",
            priority = 92,
            conditions = { level = { min = 50 } },
            text = "Kill 20 Shadowsworn Thug.",
            dependsOn = { "accept-8424-war-on-the-shadowsworn" },
            complete = QuestObjective(8424, 3, "Shadowsworn Thug"),
            route = {
                Point(MAP.BLASTED_LANDS, 0.652, 0.328, "Blasted Lands", "Travel to Blasted Lands."),
            },
        },
        {
            id = "turnin-8424-war-on-the-shadowsworn",
            kind = "turnin",
            priority = 93,
            conditions = { level = { min = 50 } },
            text = "Turn in War on the Shadowsworn to Fallen Hero of the Horde.",
            dependsOn = { "objective-8424-1-shadowsworn-adept", "objective-8424-2-shadowsworn-cultist", "objective-8424-3-shadowsworn-thug" },
            complete = QuestState(8424, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.343, 0.662, "Fallen Hero of the Horde", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-8425-voodoo-feathers",
            kind = "accept",
            priority = 94,
            conditions = { all = { { class = 1 }, { level = { min = 50 } } } },
            text = "Accept Voodoo Feathers from Fallen Hero of the Horde.",
            dependsOn = { "turnin-8424-war-on-the-shadowsworn" },
            complete = QuestState(8425, "activeOrCompleted"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.343, 0.662, "Fallen Hero of the Horde", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-1448-in-search-of-the-temple",
            kind = "accept",
            priority = 95,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept In Search of The Temple from Brohann Caskbelly.",
            complete = QuestState(1448, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.207, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "objective-1448-1-search-for-the-temple-of",
            kind = "objective",
            priority = 96,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Search for the Temple of Atal'Hakkar.",
            dependsOn = { "accept-1448-in-search-of-the-temple" },
            complete = QuestState(1448, "complete"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.668, 0.594, "Swamp of Sorrows", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-1448-in-search-of-the-temple",
            kind = "turnin",
            priority = 97,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in In Search of The Temple to Brohann Caskbelly.",
            dependsOn = { "objective-1448-1-search-for-the-temple-of" },
            complete = QuestState(1448, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.207, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-1449-to-the-hinterlands",
            kind = "accept",
            priority = 98,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept To The Hinterlands from Brohann Caskbelly.",
            dependsOn = { "turnin-1448-in-search-of-the-temple" },
            complete = QuestState(1449, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.207, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-1449-to-the-hinterlands",
            kind = "turnin",
            priority = 99,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in To The Hinterlands to Falstad Wildhammer.",
            dependsOn = { "accept-1449-to-the-hinterlands" },
            complete = QuestState(1449, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.118, 0.468, "Falstad Wildhammer", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1450-gryphon-master-talonaxe",
            kind = "accept",
            priority = 100,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Gryphon Master Talonaxe from Falstad Wildhammer.",
            dependsOn = { "turnin-1449-to-the-hinterlands" },
            complete = QuestState(1450, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.118, 0.468, "Falstad Wildhammer", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-1450-gryphon-master-talonaxe",
            kind = "turnin",
            priority = 101,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Gryphon Master Talonaxe to Gryphon Master Talonaxe.",
            dependsOn = { "accept-1450-gryphon-master-talonaxe" },
            complete = QuestState(1450, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1451-rhapsody-shindigger",
            kind = "accept",
            priority = 102,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Rhapsody Shindigger from Gryphon Master Talonaxe.",
            dependsOn = { "turnin-1450-gryphon-master-talonaxe" },
            complete = QuestState(1451, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-1451-rhapsody-shindigger",
            kind = "turnin",
            priority = 103,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Rhapsody Shindigger to Rhapsody Shindigger.",
            dependsOn = { "accept-1451-rhapsody-shindigger" },
            complete = QuestState(1451, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.269, 0.486, "Rhapsody Shindigger", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1452-rhapsody-s-kalimdor-kocktail",
            kind = "accept",
            priority = 104,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Rhapsody's Kalimdor Kocktail from Rhapsody Shindigger.",
            dependsOn = { "turnin-1451-rhapsody-shindigger" },
            complete = QuestState(1452, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.269, 0.486, "Rhapsody Shindigger", "Travel to The Hinterlands."),
            },
        },
        {
            id = "objective-1452-1-roc-gizzard",
            kind = "objective",
            priority = 106,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Collect 3 Roc Gizzard.",
            dependsOn = { "accept-1452-rhapsody-s-kalimdor-kocktail" },
            complete = QuestObjective(1452, 1, "Roc Gizzard"),
            route = {
                Point(MAP.TANARIS, 0.435, 0.404, "Tanaris", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3445-the-sunken-temple",
            kind = "accept",
            priority = 107,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 46 } } } },
            text = "Accept The Sunken Temple from Angelas Moonbreeze.",
            complete = QuestState(3445, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.318, 0.456, "Angelas Moonbreeze", "Travel to Feralas."),
            },
        },
        {
            id = "objective-1452-2-ironfur-liver",
            kind = "objective",
            priority = 109,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Collect 3 Ironfur Liver.",
            dependsOn = { "accept-1452-rhapsody-s-kalimdor-kocktail" },
            complete = QuestObjective(1452, 2, "Ironfur Liver"),
            route = {
                Point(MAP.FERALAS, 0.499, 0.304, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "objective-1452-3-groddoc-liver",
            kind = "objective",
            priority = 111,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Collect 3 Groddoc Liver.",
            dependsOn = { "accept-1452-rhapsody-s-kalimdor-kocktail" },
            complete = QuestObjective(1452, 3, "Groddoc Liver"),
            route = {
                Point(MAP.FERALAS, 0.499, 0.304, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-1452-rhapsody-s-kalimdor-kocktail",
            kind = "turnin",
            priority = 112,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Rhapsody's Kalimdor Kocktail to Rhapsody Shindigger.",
            dependsOn = { "objective-1452-1-roc-gizzard", "objective-1452-2-ironfur-liver", "objective-1452-3-groddoc-liver" },
            complete = QuestState(1452, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.269, 0.486, "Rhapsody Shindigger", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1469-rhapsody-s-tale",
            kind = "accept",
            priority = 113,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Rhapsody's Tale from Rhapsody Shindigger.",
            dependsOn = { "turnin-1452-rhapsody-s-kalimdor-kocktail" },
            complete = QuestState(1469, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.269, 0.486, "Rhapsody Shindigger", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-1469-rhapsody-s-tale",
            kind = "turnin",
            priority = 114,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Rhapsody's Tale to Brohann Caskbelly.",
            dependsOn = { "accept-1469-rhapsody-s-tale" },
            complete = QuestState(1469, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.206, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-3445-the-sunken-temple",
            kind = "turnin",
            priority = 116,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 46 } } } },
            text = "Turn in The Sunken Temple to Marvon Rivetseeker.",
            dependsOn = { "accept-3445-the-sunken-temple" },
            complete = QuestState(3445, "completed"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3444-the-stone-circle",
            kind = "accept",
            priority = 117,
            conditions = { level = { min = 46 } },
            text = "Accept The Stone Circle from Marvon Rivetseeker.",
            dependsOn = { "turnin-3445-the-sunken-temple" },
            complete = QuestState(3444, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-3444-1-stone-circle",
            kind = "objective",
            priority = 119,
            conditions = { level = { min = 46 } },
            text = "Collect Stone Circle.",
            dependsOn = { "accept-3444-the-stone-circle" },
            complete = QuestState(3444, "complete"),
            route = {
                Point(MAP.THE_BARRENS, 0.625, 0.385, "The Barrens", "Travel to The Barrens."),
            },
        },
        {
            id = "turnin-3444-the-stone-circle",
            kind = "turnin",
            priority = 120,
            conditions = { level = { min = 46 } },
            text = "Turn in The Stone Circle to Marvon Rivetseeker.",
            dependsOn = { "objective-3444-1-stone-circle" },
            complete = QuestState(3444, "completed"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3446-into-the-depths",
            kind = "accept",
            priority = 121,
            conditions = { level = { min = 46 } },
            text = "Accept Into the Depths from Marvon Rivetseeker.",
            dependsOn = { "turnin-3444-the-stone-circle" },
            complete = QuestState(3446, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3520-screecher-spirits",
            kind = "accept",
            priority = 122,
            conditions = { level = { min = 40 } },
            text = "Accept Screecher Spirits from Yeh'kinya.",
            complete = QuestState(3520, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-3520-1-screecher-spirits",
            kind = "objective",
            priority = 124,
            conditions = { level = { min = 40 } },
            text = "Collect 3 Screecher Spirits.",
            dependsOn = { "accept-3520-screecher-spirits" },
            complete = QuestState(3520, "complete"),
            route = {
                Point(MAP.FERALAS, 0.583, 0.577, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-3520-screecher-spirits",
            kind = "turnin",
            priority = 125,
            conditions = { level = { min = 40 } },
            text = "Turn in Screecher Spirits to Yeh'kinya.",
            dependsOn = { "objective-3520-1-screecher-spirits" },
            complete = QuestState(3520, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3527-the-prophecy-of-mosh-aru",
            kind = "accept",
            priority = 126,
            conditions = { level = { min = 40 } },
            text = "Accept The Prophecy of Mosh'aru from Yeh'kinya.",
            dependsOn = { "turnin-3520-screecher-spirits" },
            complete = QuestState(3527, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 127,
            conditions = { level = { min = 25 } },
            text = "Enter Zul'Farrak with your group.",
            dependsOn = { "accept-8250-magecraft", "accept-8415-chillwind-point", "accept-8254-cenarion-aid", "accept-8233-a-simple-request", "accept-8419-an-imp-s-request", "accept-8417-a-troubled-spirit", "accept-9063-torwa-pathfinder-goto-darnassus-35-38-8-41", "accept-8151-the-hunter-s-charm", "accept-9052-bloodpetal-poison", "accept-9051-toxic-test", "accept-9053-a-better-ingredient", "accept-8153-courser-antlers", "accept-8231-wavethrashing", "accept-8232-the-green-drake", "accept-8251-magic-dust", "accept-3503-meeting-with-the-master", "accept-8252-the-siren-s-coral", "accept-8253-destroy-morphaz", "accept-8414-dispelling-evil", "accept-8416-inert-scourgestones", "accept-8418-forging-the-mightstone", "accept-8255-of-coursers-we-know", "accept-8256-the-ichor-of-undeath", "accept-8257-blood-of-morphaz", "accept-8234-sealed-azure-bag", "accept-8235-encoded-fragments", "accept-3421-return-trip", "accept-8236-the-azure-key", "accept-8421-the-wrong-stuff", "accept-8422-trolls-of-a-feather", "accept-8423-warrior-kinship", "accept-8424-war-on-the-shadowsworn", "accept-8425-voodoo-feathers", "accept-1448-in-search-of-the-temple", "accept-1449-to-the-hinterlands", "accept-1450-gryphon-master-talonaxe", "accept-1451-rhapsody-shindigger", "accept-1452-rhapsody-s-kalimdor-kocktail", "accept-3445-the-sunken-temple", "accept-1469-rhapsody-s-tale", "accept-3444-the-stone-circle", "accept-3446-into-the-depths", "accept-3520-screecher-spirits", "accept-3527-the-prophecy-of-mosh-aru" },
            persistCompletion = true,
            complete = { instance = 109 },
        },
        {
            id = "objective-3527-1-first-mosh-aru-tablet",
            kind = "objective",
            priority = 129,
            conditions = { level = { min = 40 } },
            text = "Collect First Mosh'aru Tablet.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 1, "First Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-3527-2-second-mosh-aru-tablet",
            kind = "objective",
            priority = 131,
            conditions = { level = { min = 40 } },
            text = "Collect Second Mosh'aru Tablet.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 2, "Second Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "turnin-3527-the-prophecy-of-mosh-aru",
            kind = "turnin",
            priority = 134,
            conditions = { level = { min = 40 } },
            text = "Turn in The Prophecy of Mosh'aru to Yeh'kinya.",
            dependsOn = { "objective-3527-1-first-mosh-aru-tablet", "objective-3527-2-second-mosh-aru-tablet" },
            complete = QuestState(3527, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4787-the-ancient-egg",
            kind = "accept",
            priority = 135,
            conditions = { level = { min = 40 } },
            text = "Accept The Ancient Egg from Yeh'kinya.",
            dependsOn = { "turnin-3527-the-prophecy-of-mosh-aru" },
            complete = QuestState(4787, "activeOrCompleted"),
        },
        {
            id = "objective-4787-1-ancient-egg",
            kind = "objective",
            priority = 138,
            conditions = { level = { min = 40 } },
            text = "Collect Ancient Egg.",
            dependsOn = { "accept-4787-the-ancient-egg" },
            complete = QuestState(4787, "complete"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.575, 0.868, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-4787-the-ancient-egg",
            kind = "turnin",
            priority = 139,
            conditions = { level = { min = 40 } },
            text = "Turn in The Ancient Egg to Yeh'kinya.",
            dependsOn = { "objective-4787-1-ancient-egg" },
            complete = QuestState(4787, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4141-muigin-and-larion",
            kind = "accept",
            priority = 141,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Accept Muigin and Larion from Muigin.",
            complete = QuestState(4141, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.429, 0.097, "Muigin", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4141-1-bloodpetal",
            kind = "objective",
            priority = 143,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Collect 15 Bloodpetal.",
            dependsOn = { "accept-4141-muigin-and-larion" },
            complete = QuestState(4141, "complete"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.715, 0.387, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-4141-muigin-and-larion",
            kind = "turnin",
            priority = 144,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Turn in Muigin and Larion to Muigin.",
            dependsOn = { "objective-4141-1-bloodpetal" },
            complete = QuestState(4141, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.429, 0.097, "Muigin", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "accept-4142-a-visit-to-gregan",
            kind = "accept",
            priority = 145,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Accept A Visit to Gregan from Muigin.",
            dependsOn = { "turnin-4141-muigin-and-larion" },
            complete = QuestState(4142, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.429, 0.097, "Muigin", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-4142-a-visit-to-gregan",
            kind = "turnin",
            priority = 146,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Turn in A Visit to Gregan to Gregan Brewspewer.",
            dependsOn = { "accept-4142-a-visit-to-gregan" },
            complete = QuestState(4142, "completed"),
            route = {
                Point(MAP.FERALAS, 0.451, 0.256, "Gregan Brewspewer", "Travel to Feralas."),
            },
        },
        {
            id = "objective-9053-1-putrid-vine",
            kind = "objective",
            priority = 152,
            conditions = { all = { { race = 4 }, { class = 11 }, { level = { min = 50 } } } },
            text = "Collect Putrid Vine.",
            dependsOn = { "accept-9053-a-better-ingredient" },
            complete = QuestState(9053, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-3446-into-the-depths",
            kind = "turnin",
            priority = 154,
            conditions = { level = { min = 46 } },
            text = "Turn in Into the Depths.",
            dependsOn = { "accept-3446-into-the-depths" },
            complete = QuestState(3446, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-3447-secret-of-the-circle",
            kind = "accept",
            priority = 155,
            conditions = { level = { min = 46 } },
            text = "Accept Secret of the Circle.",
            dependsOn = { "turnin-3446-into-the-depths" },
            complete = QuestState(3447, "activeOrCompleted"),
        },
        {
            id = "turnin-3447-secret-of-the-circle",
            kind = "turnin",
            priority = 157,
            conditions = { level = { min = 46 } },
            text = "Turn in Secret of the Circle.",
            dependsOn = { "accept-3447-secret-of-the-circle" },
            complete = QuestState(3447, "completed"),
            useClientPin = true,
        },
        {
            id = "objective-8418-1-amber-voodoo-feather",
            kind = "objective",
            priority = 159,
            conditions = { all = { { faction = "Alliance" }, { class = 2 }, { level = { min = 50 } } } },
            text = "Collect 2 Amber Voodoo Feather.",
            dependsOn = { "accept-8418-forging-the-mightstone" },
            complete = QuestObjective(8418, 1, "Amber Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8422-1-amber-voodoo-feather",
            kind = "objective",
            priority = 160,
            conditions = { all = { { class = 9 }, { level = { min = 50 } } } },
            text = "Collect 2 Amber Voodoo Feather.",
            dependsOn = { "accept-8422-trolls-of-a-feather" },
            complete = QuestObjective(8422, 1, "Amber Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8425-1-amber-voodoo-feather",
            kind = "objective",
            priority = 161,
            conditions = { all = { { class = 1 }, { level = { min = 50 } } } },
            text = "Collect 2 Amber Voodoo Feather.",
            dependsOn = { "accept-8425-voodoo-feathers" },
            complete = QuestObjective(8425, 1, "Amber Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8418-2-blue-voodoo-feather",
            kind = "objective",
            priority = 162,
            conditions = { all = { { faction = "Alliance" }, { class = 2 }, { level = { min = 50 } } } },
            text = "Collect 2 Blue Voodoo Feather.",
            dependsOn = { "accept-8418-forging-the-mightstone" },
            complete = QuestObjective(8418, 2, "Blue Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8422-2-blue-voodoo-feather",
            kind = "objective",
            priority = 163,
            conditions = { all = { { class = 9 }, { level = { min = 50 } } } },
            text = "Collect 2 Blue Voodoo Feather.",
            dependsOn = { "accept-8422-trolls-of-a-feather" },
            complete = QuestObjective(8422, 2, "Blue Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8425-2-blue-voodoo-feather",
            kind = "objective",
            priority = 164,
            conditions = { all = { { class = 1 }, { level = { min = 50 } } } },
            text = "Collect 2 Blue Voodoo Feather.",
            dependsOn = { "accept-8425-voodoo-feathers" },
            complete = QuestObjective(8425, 2, "Blue Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8418-3-green-voodoo-feather",
            kind = "objective",
            priority = 165,
            conditions = { all = { { faction = "Alliance" }, { class = 2 }, { level = { min = 50 } } } },
            text = "Collect 2 Green Voodoo Feather.",
            dependsOn = { "accept-8418-forging-the-mightstone" },
            complete = QuestObjective(8418, 3, "Green Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8422-3-green-voodoo-feather",
            kind = "objective",
            priority = 166,
            conditions = { all = { { class = 9 }, { level = { min = 50 } } } },
            text = "Collect 2 Green Voodoo Feather.",
            dependsOn = { "accept-8422-trolls-of-a-feather" },
            complete = QuestObjective(8422, 3, "Green Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8425-3-green-voodoo-feather",
            kind = "objective",
            priority = 167,
            conditions = { all = { { class = 1 }, { level = { min = 50 } } } },
            text = "Collect 2 Green Voodoo Feather.",
            dependsOn = { "accept-8425-voodoo-feathers" },
            complete = QuestObjective(8425, 3, "Green Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8232-1-tooth-of-morphaz",
            kind = "objective",
            priority = 171,
            conditions = { all = { { class = 3 }, { level = { min = 50 } } } },
            text = "Collect Tooth of Morphaz.",
            dependsOn = { "accept-8232-the-green-drake" },
            complete = QuestState(8232, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-8253-1-arcane-shard",
            kind = "objective",
            priority = 172,
            conditions = { all = { { class = 8 }, { level = { min = 50 } } } },
            text = "Collect Arcane Shard.",
            dependsOn = { "accept-8253-destroy-morphaz" },
            complete = QuestState(8253, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-8257-1-blood-of-morphaz",
            kind = "objective",
            priority = 173,
            conditions = { all = { { class = 5 }, { level = { min = 50 } } } },
            text = "Collect Blood of Morphaz.",
            dependsOn = { "accept-8257-blood-of-morphaz" },
            complete = QuestState(8257, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-8236-1-azure-key",
            kind = "objective",
            priority = 174,
            conditions = { all = { { class = 4 }, { level = { min = 50 } } } },
            text = "Collect Azure Key.",
            dependsOn = { "accept-8236-the-azure-key" },
            complete = QuestState(8236, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-1445-1-fetish-of-hakkar",
            kind = "objective",
            priority = 183,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Collect 20 Fetish of Hakkar.",
            complete = QuestState(1445, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-9053-a-better-ingredient",
            kind = "turnin",
            priority = 191,
            conditions = { all = { { race = 4 }, { class = 11 }, { level = { min = 50 } } } },
            text = "Turn in A Better Ingredient to Torwa Pathfinder.",
            dependsOn = { "objective-9053-1-putrid-vine", "objective-9053-1-putrid-vine-2" },
            complete = QuestState(9053, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.716, 0.760, "Torwa Pathfinder", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-8232-the-green-drake",
            kind = "turnin",
            priority = 192,
            conditions = { all = { { class = 3 }, { level = { min = 50 } } } },
            text = "Turn in The Green Drake to Ogtinc.",
            dependsOn = { "objective-8232-1-tooth-of-morphaz" },
            complete = QuestState(8232, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.424, 0.426, "Ogtinc", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8253-destroy-morphaz",
            kind = "turnin",
            priority = 193,
            conditions = { all = { { class = 8 }, { level = { min = 50 } } } },
            text = "Turn in Destroy Morphaz to Archmage Xylem.",
            dependsOn = { "objective-8253-1-arcane-shard" },
            complete = QuestState(8253, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.281, 0.501, "Archmage Xylem", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-8418-forging-the-mightstone",
            kind = "turnin",
            priority = 194,
            conditions = { all = { { faction = "Alliance" }, { class = 2 }, { level = { min = 50 } } } },
            text = "Turn in Forging the Mightstone to Commander Ashlam Valorfist.",
            dependsOn = { "objective-8418-1-amber-voodoo-feather", "objective-8418-2-blue-voodoo-feather", "objective-8418-3-green-voodoo-feather" },
            complete = QuestState(8418, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.427, 0.840, "Commander Ashlam Valorfist", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-8257-blood-of-morphaz",
            kind = "turnin",
            priority = 195,
            conditions = { all = { { class = 5 }, { level = { min = 50 } } } },
            text = "Turn in Blood of Morphaz to Greta Mosshoof.",
            dependsOn = { "objective-8257-1-blood-of-morphaz" },
            complete = QuestState(8257, "completed"),
            route = {
                Point(MAP.FELWOOD, 0.512, 0.822, "Greta Mosshoof", "Travel to Felwood."),
            },
        },
        {
            id = "turnin-8236-the-azure-key-goto-alterac-mountains-86-03",
            kind = "turnin",
            priority = 196,
            conditions = { all = { { class = 4 }, { level = { min = 50 } } } },
            text = "Turn in The Azure Key|goto Alterac Mountains 86.03,78.88 to Lord Jorach Ravenholdt.",
            dependsOn = { "objective-8236-1-azure-key" },
            complete = QuestState(8236, "completed"),
            useClientPin = true,
        },
        {
            id = "turnin-8422-trolls-of-a-feather",
            kind = "turnin",
            priority = 197,
            conditions = { all = { { class = 9 }, { level = { min = 50 } } } },
            text = "Turn in Trolls of a Feather to Impsy.",
            dependsOn = { "objective-8422-1-amber-voodoo-feather", "objective-8422-2-blue-voodoo-feather", "objective-8422-3-green-voodoo-feather" },
            complete = QuestState(8422, "completed"),
            route = {
                Point(MAP.ALTERAC_MOUNTAINS, 0.414, 0.450, "Impsy", "Travel to Alterac Mountains."),
            },
        },
        {
            id = "turnin-8425-voodoo-feathers",
            kind = "turnin",
            priority = 198,
            conditions = { all = { { class = 1 }, { level = { min = 50 } } } },
            text = "Turn in Voodoo Feathers to Fallen Hero of the Horde.",
            dependsOn = { "objective-8425-1-amber-voodoo-feather", "objective-8425-2-blue-voodoo-feather", "objective-8425-3-green-voodoo-feather" },
            complete = QuestState(8425, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.343, 0.662, "Fallen Hero of the Horde", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-8410-elemental-mastery",
            kind = "accept",
            priority = 199,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Accept Elemental Mastery from Beram Skychaser.",
            complete = QuestState(8410, "activeOrCompleted"),
            route = {
                Point(MAP.THUNDER_BLUFF, 0.228, 0.194, "Beram Skychaser", "Travel to Thunder Bluff."),
            },
        },
        {
            id = "turnin-8410-elemental-mastery",
            kind = "turnin",
            priority = 201,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Turn in Elemental Mastery to Bath'rah the Windwatcher.",
            dependsOn = { "accept-8410-elemental-mastery" },
            complete = QuestState(8410, "completed"),
            route = {
                Point(MAP.ALTERAC_MOUNTAINS, 0.805, 0.669, "Bath'rah the Windwatcher", "Travel to Alterac Mountains."),
            },
        },
        {
            id = "accept-8412-spirit-totem",
            kind = "accept",
            priority = 202,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Accept Spirit Totem from Bath'rah the Windwatcher.",
            dependsOn = { "turnin-8410-elemental-mastery" },
            complete = QuestState(8412, "activeOrCompleted"),
            route = {
                Point(MAP.ALTERAC_MOUNTAINS, 0.805, 0.669, "Bath'rah the Windwatcher", "Travel to Alterac Mountains."),
            },
        },
        {
            id = "objective-8412-1-bloodshot-spider-eye",
            kind = "objective",
            priority = 203,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Collect 8 Bloodshot Spider Eye.",
            dependsOn = { "accept-8412-spirit-totem" },
            complete = QuestObjective(8412, 1, "Bloodshot Spider Eye"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.336, 0.604, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "objective-8412-2-thick-black-claw",
            kind = "objective",
            priority = 204,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Collect 8 Thick Black Claw.",
            dependsOn = { "accept-8412-spirit-totem" },
            complete = QuestObjective(8412, 2, "Thick Black Claw"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.336, 0.604, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-8412-spirit-totem",
            kind = "turnin",
            priority = 205,
            conditions = { all = { { faction = "Horde" }, { level = { min = 50 } } } },
            text = "Turn in Spirit Totem to Bath'rah the Windwatcher.",
            dependsOn = { "objective-8412-1-bloodshot-spider-eye", "objective-8412-2-thick-black-claw" },
            complete = QuestState(8412, "completed"),
            route = {
                Point(MAP.ALTERAC_MOUNTAINS, 0.805, 0.669, "Bath'rah the Windwatcher", "Travel to Alterac Mountains."),
            },
        },
        {
            id = "accept-8413-da-voodoo",
            kind = "accept",
            priority = 206,
            conditions = { all = { { faction = "Horde" }, { class = 7 }, { level = { min = 50 } } } },
            text = "Accept Da Voodoo from Bath'rah the Windwatcher.",
            dependsOn = { "turnin-8412-spirit-totem" },
            complete = QuestState(8413, "activeOrCompleted"),
            route = {
                Point(MAP.ALTERAC_MOUNTAINS, 0.805, 0.669, "Bath'rah the Windwatcher", "Travel to Alterac Mountains."),
            },
        },
        {
            id = "accept-3380-the-sunken-temple",
            kind = "accept",
            priority = 207,
            conditions = { all = { { faction = "Horde" }, { level = { min = 46 } } } },
            text = "Accept The Sunken Temple from Witch Doctor Uzer'i.",
            complete = QuestState(3380, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.744, 0.434, "Witch Doctor Uzer'i", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-3380-the-sunken-temple",
            kind = "turnin",
            priority = 208,
            conditions = { all = { { faction = "Horde" }, { level = { min = 46 } } } },
            text = "Turn in The Sunken Temple to Marvon Rivetseeker.",
            dependsOn = { "accept-3380-the-sunken-temple" },
            complete = QuestState(3380, "completed"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-1424-pool-of-tears",
            kind = "accept",
            priority = 209,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Accept Pool of Tears from Fel'zerul.",
            complete = QuestState(1424, "activeOrCompleted"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "objective-1424-1-atal-ai-artifact",
            kind = "objective",
            priority = 211,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Collect 10 Atal'ai Artifact.",
            dependsOn = { "accept-1424-pool-of-tears" },
            complete = QuestState(1424, "complete"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.671, 0.587, "Swamp of Sorrows", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-1424-pool-of-tears",
            kind = "turnin",
            priority = 212,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Turn in Pool of Tears to Fel'zerul.",
            dependsOn = { "objective-1424-1-atal-ai-artifact" },
            complete = QuestState(1424, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-1429-the-atal-ai-exile",
            kind = "accept",
            priority = 213,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Accept The Atal'ai Exile from Fel'zerul.",
            dependsOn = { "turnin-1424-pool-of-tears" },
            complete = QuestState(1429, "activeOrCompleted"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-1429-the-atal-ai-exile",
            kind = "turnin",
            priority = 214,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Turn in The Atal'ai Exile to Atal'ai Exile.",
            dependsOn = { "accept-1429-the-atal-ai-exile" },
            complete = QuestState(1429, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.338, 0.752, "Atal'ai Exile", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1444-return-to-fel-zerul",
            kind = "accept",
            priority = 215,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Accept Return to Fel'Zerul from Atal'ai Exile.",
            dependsOn = { "turnin-1429-the-atal-ai-exile" },
            complete = QuestState(1444, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.338, 0.752, "Atal'ai Exile", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-1444-return-to-fel-zerul",
            kind = "turnin",
            priority = 216,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Turn in Return to Fel'Zerul to Fel'zerul.",
            dependsOn = { "accept-1444-return-to-fel-zerul" },
            complete = QuestState(1444, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-4145-larion-and-muigin",
            kind = "accept",
            priority = 218,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Accept Larion and Muigin from Larion.",
            complete = QuestState(4145, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.455, 0.087, "Larion", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4145-3-bloodpetal-flayer",
            kind = "objective",
            priority = 219,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Kill 5 Bloodpetal Flayer.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 3, "Bloodpetal Flayer"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.571, 0.164, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4145-4-bloodpetal-thresher",
            kind = "objective",
            priority = 220,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Kill 5 Bloodpetal Thresher.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 4, "Bloodpetal Thresher"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.566, 0.345, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4145-1-bloodpetal-lasher",
            kind = "objective",
            priority = 221,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Kill 5 Bloodpetal Lasher.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 1, "Bloodpetal Lasher"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.698, 0.298, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4145-2-bloodpetal-trapper",
            kind = "objective",
            priority = 222,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Kill 5 Bloodpetal Trapper.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 2, "Bloodpetal Trapper"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.399, 0.535, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-4145-larion-and-muigin",
            kind = "turnin",
            priority = 223,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Turn in Larion and Muigin to Larion.",
            dependsOn = { "objective-4145-3-bloodpetal-flayer", "objective-4145-4-bloodpetal-thresher", "objective-4145-1-bloodpetal-lasher", "objective-4145-2-bloodpetal-trapper" },
            complete = QuestState(4145, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.455, 0.087, "Larion", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "accept-4147-marvon-s-workshop",
            kind = "accept",
            priority = 224,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Accept Marvon's Workshop from Larion.",
            dependsOn = { "turnin-4145-larion-and-muigin" },
            complete = QuestState(4147, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.455, 0.087, "Larion", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-4147-marvon-s-workshop",
            kind = "turnin",
            priority = 225,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Turn in Marvon's Workshop to Liv Rizzlefix.",
            dependsOn = { "accept-4147-marvon-s-workshop" },
            complete = QuestState(4147, "completed"),
            route = {
                Point(MAP.THE_BARRENS, 0.625, 0.387, "Liv Rizzlefix", "Travel to The Barrens."),
            },
        },
        {
            id = "objective-9053-1-putrid-vine-2",
            kind = "objective",
            priority = 227,
            conditions = { all = { { race = 4 }, { class = 11 }, { level = { min = 50 } } } },
            text = "Collect Putrid Vine.",
            dependsOn = { "accept-9053-a-better-ingredient" },
            complete = QuestState(9053, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-8413-1-amber-voodoo-feather",
            kind = "objective",
            priority = 229,
            conditions = { all = { { faction = "Horde" }, { class = 7 }, { level = { min = 50 } } } },
            text = "Collect 2 Amber Voodoo Feather.",
            dependsOn = { "accept-8413-da-voodoo" },
            complete = QuestObjective(8413, 1, "Amber Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8413-2-blue-voodoo-feather",
            kind = "objective",
            priority = 230,
            conditions = { all = { { faction = "Horde" }, { class = 7 }, { level = { min = 50 } } } },
            text = "Collect 2 Blue Voodoo Feather.",
            dependsOn = { "accept-8413-da-voodoo" },
            complete = QuestObjective(8413, 2, "Blue Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "objective-8413-3-green-voodoo-feather",
            kind = "objective",
            priority = 231,
            conditions = { all = { { faction = "Horde" }, { class = 7 }, { level = { min = 50 } } } },
            text = "Collect 2 Green Voodoo Feather.",
            dependsOn = { "accept-8413-da-voodoo" },
            complete = QuestObjective(8413, 3, "Green Voodoo Feather"),
            useClientPin = true,
        },
        {
            id = "turnin-8413-da-voodoo",
            kind = "turnin",
            priority = 238,
            conditions = { all = { { faction = "Horde" }, { class = 7 }, { level = { min = 50 } } } },
            text = "Turn in Da Voodoo to Bath'rah the Windwatcher.",
            dependsOn = { "objective-8413-1-amber-voodoo-feather", "objective-8413-2-blue-voodoo-feather", "objective-8413-3-green-voodoo-feather" },
            complete = QuestState(8413, "completed"),
            route = {
                Point(MAP.ALTERAC_MOUNTAINS, 0.805, 0.669, "Bath'rah the Windwatcher", "Travel to Alterac Mountains."),
            },
        },
    },
})
