local _, ns = ...

local MAP = {
    STORMWIND_CITY = 1453,
    SWAMP_OF_SORROWS = 1435,
    THE_HINTERLANDS = 1425,
    TANARIS = 1446,
    FERALAS = 1444,
    THE_BARRENS = 1413,
    UN_GORO_CRATER = 1449,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-temple-of-atal-hakkar",
    title = "Temple of Atal'Hakkar",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 47 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-1448-in-search-of-the-temple",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept In Search of The Temple from Brohann Caskbelly.",
            complete = QuestState(1448, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.207, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "objective-1448-1-search-for-the-temple-of",
            kind = "objective",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Search for the Temple of Atal'Hakkar.",
            dependsOn = { "accept-1448-in-search-of-the-temple" },
            complete = QuestState(1448, "complete"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.668, 0.594, "Swamp of Sorrows", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-1448-in-search-of-the-temple",
            kind = "turnin",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in In Search of The Temple to Brohann Caskbelly.",
            dependsOn = { "objective-1448-1-search-for-the-temple-of" },
            complete = QuestState(1448, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.207, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-1449-to-the-hinterlands",
            kind = "accept",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept To The Hinterlands from Brohann Caskbelly.",
            dependsOn = { "turnin-1448-in-search-of-the-temple" },
            complete = QuestState(1449, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.207, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-1449-to-the-hinterlands",
            kind = "turnin",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in To The Hinterlands to Falstad Wildhammer.",
            dependsOn = { "accept-1449-to-the-hinterlands" },
            complete = QuestState(1449, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.118, 0.468, "Falstad Wildhammer", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1450-gryphon-master-talonaxe",
            kind = "accept",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Gryphon Master Talonaxe from Falstad Wildhammer.",
            dependsOn = { "turnin-1449-to-the-hinterlands" },
            complete = QuestState(1450, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.118, 0.468, "Falstad Wildhammer", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-1450-gryphon-master-talonaxe",
            kind = "turnin",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Gryphon Master Talonaxe to Gryphon Master Talonaxe.",
            dependsOn = { "accept-1450-gryphon-master-talonaxe" },
            complete = QuestState(1450, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1451-rhapsody-shindigger",
            kind = "accept",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Rhapsody Shindigger from Gryphon Master Talonaxe.",
            dependsOn = { "turnin-1450-gryphon-master-talonaxe" },
            complete = QuestState(1451, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-1451-rhapsody-shindigger",
            kind = "turnin",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Rhapsody Shindigger to Rhapsody Shindigger.",
            dependsOn = { "accept-1451-rhapsody-shindigger" },
            complete = QuestState(1451, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.269, 0.486, "Rhapsody Shindigger", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1452-rhapsody-s-kalimdor-kocktail",
            kind = "accept",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Rhapsody's Kalimdor Kocktail from Rhapsody Shindigger.",
            dependsOn = { "turnin-1451-rhapsody-shindigger" },
            complete = QuestState(1452, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.269, 0.486, "Rhapsody Shindigger", "Travel to The Hinterlands."),
            },
        },
        {
            id = "objective-1452-1-roc-gizzard",
            kind = "objective",
            priority = 21,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Collect 3 Roc Gizzard.",
            dependsOn = { "accept-1452-rhapsody-s-kalimdor-kocktail" },
            complete = QuestObjective(1452, 1, "Roc Gizzard"),
            route = {
                Point(MAP.TANARIS, 0.435, 0.404, "Tanaris", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3445-the-sunken-temple",
            kind = "accept",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 46 } } } },
            text = "Accept The Sunken Temple from Angelas Moonbreeze.",
            complete = QuestState(3445, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.318, 0.456, "Angelas Moonbreeze", "Travel to Feralas."),
            },
        },
        {
            id = "objective-1452-2-ironfur-liver",
            kind = "objective",
            priority = 24,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Collect 3 Ironfur Liver.",
            dependsOn = { "accept-1452-rhapsody-s-kalimdor-kocktail" },
            complete = QuestObjective(1452, 2, "Ironfur Liver"),
            route = {
                Point(MAP.FERALAS, 0.499, 0.304, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "objective-1452-3-groddoc-liver",
            kind = "objective",
            priority = 26,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Collect 3 Groddoc Liver.",
            dependsOn = { "accept-1452-rhapsody-s-kalimdor-kocktail" },
            complete = QuestObjective(1452, 3, "Groddoc Liver"),
            route = {
                Point(MAP.FERALAS, 0.499, 0.304, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-1452-rhapsody-s-kalimdor-kocktail",
            kind = "turnin",
            priority = 27,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Rhapsody's Kalimdor Kocktail to Rhapsody Shindigger.",
            dependsOn = { "objective-1452-1-roc-gizzard", "objective-1452-2-ironfur-liver", "objective-1452-3-groddoc-liver" },
            complete = QuestState(1452, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.269, 0.486, "Rhapsody Shindigger", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1469-rhapsody-s-tale",
            kind = "accept",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Rhapsody's Tale from Rhapsody Shindigger.",
            dependsOn = { "turnin-1452-rhapsody-s-kalimdor-kocktail" },
            complete = QuestState(1469, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.269, 0.486, "Rhapsody Shindigger", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-1469-rhapsody-s-tale",
            kind = "turnin",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Rhapsody's Tale to Brohann Caskbelly.",
            dependsOn = { "accept-1469-rhapsody-s-tale" },
            complete = QuestState(1469, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.206, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-1475-into-the-temple-of-atal-hakkar",
            kind = "accept",
            priority = 30,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Into The Temple of Atal'Hakkar from Brohann Caskbelly.",
            dependsOn = { "turnin-1469-rhapsody-s-tale" },
            complete = QuestState(1475, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.206, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-3445-the-sunken-temple",
            kind = "turnin",
            priority = 31,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 46 } } } },
            text = "Turn in The Sunken Temple to Marvon Rivetseeker.",
            dependsOn = { "accept-3445-the-sunken-temple" },
            complete = QuestState(3445, "completed"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3444-the-stone-circle",
            kind = "accept",
            priority = 32,
            conditions = { level = { min = 46 } },
            text = "Accept The Stone Circle from Marvon Rivetseeker.",
            dependsOn = { "turnin-3445-the-sunken-temple" },
            complete = QuestState(3444, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-3444-1-stone-circle",
            kind = "objective",
            priority = 34,
            conditions = { level = { min = 46 } },
            text = "Collect Stone Circle.",
            dependsOn = { "accept-3444-the-stone-circle" },
            complete = QuestState(3444, "complete"),
            route = {
                Point(MAP.THE_BARRENS, 0.625, 0.385, "The Barrens", "Travel to The Barrens."),
            },
        },
        {
            id = "turnin-3444-the-stone-circle",
            kind = "turnin",
            priority = 35,
            conditions = { level = { min = 46 } },
            text = "Turn in The Stone Circle to Marvon Rivetseeker.",
            dependsOn = { "objective-3444-1-stone-circle" },
            complete = QuestState(3444, "completed"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3446-into-the-depths",
            kind = "accept",
            priority = 36,
            conditions = { level = { min = 46 } },
            text = "Accept Into the Depths from Marvon Rivetseeker.",
            dependsOn = { "turnin-3444-the-stone-circle" },
            complete = QuestState(3446, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3520-screecher-spirits",
            kind = "accept",
            priority = 37,
            conditions = { level = { min = 40 } },
            text = "Accept Screecher Spirits from Yeh'kinya.",
            complete = QuestState(3520, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-3520-1-screecher-spirits",
            kind = "objective",
            priority = 39,
            conditions = { level = { min = 40 } },
            text = "Collect 3 Screecher Spirits.",
            dependsOn = { "accept-3520-screecher-spirits" },
            complete = QuestState(3520, "complete"),
            route = {
                Point(MAP.FERALAS, 0.583, 0.577, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-3520-screecher-spirits",
            kind = "turnin",
            priority = 40,
            conditions = { level = { min = 40 } },
            text = "Turn in Screecher Spirits to Yeh'kinya.",
            dependsOn = { "objective-3520-1-screecher-spirits" },
            complete = QuestState(3520, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3527-the-prophecy-of-mosh-aru",
            kind = "accept",
            priority = 41,
            conditions = { level = { min = 40 } },
            text = "Accept The Prophecy of Mosh'aru from Yeh'kinya.",
            dependsOn = { "turnin-3520-screecher-spirits" },
            complete = QuestState(3527, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 42,
            conditions = { level = { min = 47 } },
            text = "Enter Temple Of Atal'Hakkar with your group.",
            dependsOn = { "accept-1448-in-search-of-the-temple", "accept-1449-to-the-hinterlands", "accept-1450-gryphon-master-talonaxe", "accept-1451-rhapsody-shindigger", "accept-1452-rhapsody-s-kalimdor-kocktail", "accept-3445-the-sunken-temple", "accept-1469-rhapsody-s-tale", "accept-1475-into-the-temple-of-atal-hakkar", "accept-3444-the-stone-circle", "accept-3446-into-the-depths", "accept-3520-screecher-spirits", "accept-3527-the-prophecy-of-mosh-aru" },
            persistCompletion = true,
            complete = { instance = 109 },
        },
        {
            id = "objective-3527-1-first-mosh-aru-tablet",
            kind = "objective",
            priority = 44,
            conditions = { level = { min = 40 } },
            text = "Collect First Mosh'aru Tablet.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 1, "First Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-3527-2-second-mosh-aru-tablet",
            kind = "objective",
            priority = 46,
            conditions = { level = { min = 40 } },
            text = "Collect Second Mosh'aru Tablet.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 2, "Second Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "turnin-3527-the-prophecy-of-mosh-aru",
            kind = "turnin",
            priority = 49,
            conditions = { level = { min = 40 } },
            text = "Turn in The Prophecy of Mosh'aru to Yeh'kinya.",
            dependsOn = { "objective-3527-1-first-mosh-aru-tablet", "objective-3527-2-second-mosh-aru-tablet" },
            complete = QuestState(3527, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4787-the-ancient-egg",
            kind = "accept",
            priority = 50,
            conditions = { level = { min = 40 } },
            text = "Accept The Ancient Egg from Yeh'kinya.",
            dependsOn = { "turnin-3527-the-prophecy-of-mosh-aru" },
            complete = QuestState(4787, "activeOrCompleted"),
        },
        {
            id = "accept-1446-jammal-an-the-prophet",
            kind = "accept",
            priority = 51,
            conditions = { level = { min = 38 } },
            text = "Accept Jammal'an the Prophet from Atal'ai Exile.",
            complete = QuestState(1446, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.338, 0.752, "Atal'ai Exile", "Travel to The Hinterlands."),
            },
        },
        {
            id = "objective-4787-1-ancient-egg",
            kind = "objective",
            priority = 53,
            conditions = { level = { min = 40 } },
            text = "Collect Ancient Egg.",
            dependsOn = { "accept-4787-the-ancient-egg" },
            complete = QuestState(4787, "complete"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.575, 0.868, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-4787-the-ancient-egg",
            kind = "turnin",
            priority = 54,
            conditions = { level = { min = 40 } },
            text = "Turn in The Ancient Egg to Yeh'kinya.",
            dependsOn = { "objective-4787-1-ancient-egg" },
            complete = QuestState(4787, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3528-the-god-hakkar",
            kind = "accept",
            priority = 55,
            conditions = { level = { min = 40 } },
            text = "Accept The God Hakkar from Yeh'kinya.",
            dependsOn = { "turnin-4787-the-ancient-egg" },
            complete = QuestState(3528, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-4141-muigin-and-larion",
            kind = "accept",
            priority = 56,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Accept Muigin and Larion from Muigin.",
            complete = QuestState(4141, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.429, 0.097, "Muigin", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4141-1-bloodpetal",
            kind = "objective",
            priority = 58,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Collect 15 Bloodpetal.",
            dependsOn = { "accept-4141-muigin-and-larion" },
            complete = QuestState(4141, "complete"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.715, 0.387, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-4141-muigin-and-larion",
            kind = "turnin",
            priority = 59,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Turn in Muigin and Larion to Muigin.",
            dependsOn = { "objective-4141-1-bloodpetal" },
            complete = QuestState(4141, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.429, 0.097, "Muigin", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "accept-4142-a-visit-to-gregan",
            kind = "accept",
            priority = 60,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Accept A Visit to Gregan from Muigin.",
            dependsOn = { "turnin-4141-muigin-and-larion" },
            complete = QuestState(4142, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.429, 0.097, "Muigin", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-4142-a-visit-to-gregan",
            kind = "turnin",
            priority = 61,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Turn in A Visit to Gregan to Gregan Brewspewer.",
            dependsOn = { "accept-4142-a-visit-to-gregan" },
            complete = QuestState(4142, "completed"),
            route = {
                Point(MAP.FERALAS, 0.451, 0.256, "Gregan Brewspewer", "Travel to Feralas."),
            },
        },
        {
            id = "accept-4143-haze-of-evil",
            kind = "accept",
            priority = 62,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Accept Haze of Evil from Gregan Brewspewer.",
            dependsOn = { "turnin-4142-a-visit-to-gregan" },
            complete = QuestState(4143, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.451, 0.256, "Gregan Brewspewer", "Travel to Feralas."),
            },
        },
        {
            id = "objective-1475-1-atal-ai-tablet",
            kind = "objective",
            priority = 64,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Collect 10 Atal'ai Tablet.",
            dependsOn = { "accept-1475-into-the-temple-of-atal-hakkar" },
            complete = QuestState(1475, "complete"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.568, 0.760, "Swamp of Sorrows", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-3446-into-the-depths",
            kind = "turnin",
            priority = 68,
            conditions = { level = { min = 46 } },
            text = "Turn in Into the Depths.",
            dependsOn = { "accept-3446-into-the-depths" },
            complete = QuestState(3446, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-3447-secret-of-the-circle",
            kind = "accept",
            priority = 69,
            conditions = { level = { min = 46 } },
            text = "Accept Secret of the Circle.",
            dependsOn = { "turnin-3446-into-the-depths" },
            complete = QuestState(3447, "activeOrCompleted"),
        },
        {
            id = "turnin-3447-secret-of-the-circle",
            kind = "turnin",
            priority = 71,
            conditions = { level = { min = 46 } },
            text = "Turn in Secret of the Circle.",
            dependsOn = { "accept-3447-secret-of-the-circle" },
            complete = QuestState(3447, "completed"),
            useClientPin = true,
        },
        {
            id = "objective-1446-1-head-of-jammal-an",
            kind = "objective",
            priority = 73,
            conditions = { level = { min = 38 } },
            text = "Collect Head of Jammal'an.",
            dependsOn = { "accept-1446-jammal-an-the-prophet" },
            complete = QuestState(1446, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-3373-the-essence-of-eranikus",
            kind = "accept",
            priority = 75,
            conditions = { level = { min = 48 } },
            text = "Accept The Essence of Eranikus.",
            complete = QuestState(3373, "activeOrCompleted"),
        },
        {
            id = "turnin-3373-the-essence-of-eranikus",
            kind = "turnin",
            priority = 77,
            conditions = { level = { min = 48 } },
            text = "Turn in The Essence of Eranikus.",
            dependsOn = { "accept-3373-the-essence-of-eranikus" },
            complete = QuestState(3373, "completed"),
            useClientPin = true,
        },
        {
            id = "objective-3528-1-fill-the-egg-of-hakkar",
            kind = "objective",
            priority = 82,
            conditions = { level = { min = 40 } },
            text = "Fill the Egg of Hakkar.",
            dependsOn = { "accept-3528-the-god-hakkar" },
            complete = QuestState(3528, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-1445-1-fetish-of-hakkar",
            kind = "objective",
            priority = 84,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Collect 20 Fetish of Hakkar.",
            dependsOn = { "accept-1445-the-temple-of-atal-hakkar" },
            complete = QuestState(1445, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4143-1-atal-ai-haze",
            kind = "objective",
            priority = 86,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Collect 5 Atal'ai Haze.",
            dependsOn = { "accept-4143-haze-of-evil" },
            complete = QuestState(4143, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-1475-into-the-temple-of-atal-hakkar",
            kind = "turnin",
            priority = 87,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Into The Temple of Atal'Hakkar to Brohann Caskbelly.",
            dependsOn = { "objective-1475-1-atal-ai-tablet" },
            complete = QuestState(1475, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.643, 0.206, "Brohann Caskbelly", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-1446-jammal-an-the-prophet",
            kind = "turnin",
            priority = 88,
            conditions = { level = { min = 38 } },
            text = "Turn in Jammal'an the Prophet to Atal'ai Exile.",
            dependsOn = { "objective-1446-1-head-of-jammal-an" },
            complete = QuestState(1446, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.338, 0.752, "Atal'ai Exile", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-4143-haze-of-evil",
            kind = "turnin",
            priority = 89,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 47 } } } },
            text = "Turn in Haze of Evil to Muigin.",
            dependsOn = { "objective-4143-1-atal-ai-haze" },
            complete = QuestState(4143, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.429, 0.097, "Muigin", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-3528-the-god-hakkar",
            kind = "turnin",
            priority = 90,
            conditions = { level = { min = 40 } },
            text = "Turn in The God Hakkar to Yeh'kinya.",
            dependsOn = { "objective-3528-1-fill-the-egg-of-hakkar" },
            complete = QuestState(3528, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3380-the-sunken-temple",
            kind = "accept",
            priority = 91,
            conditions = { all = { { faction = "Horde" }, { level = { min = 46 } } } },
            text = "Accept The Sunken Temple from Witch Doctor Uzer'i.",
            complete = QuestState(3380, "activeOrCompleted"),
            route = {
                Point(MAP.FERALAS, 0.744, 0.434, "Witch Doctor Uzer'i", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-3380-the-sunken-temple",
            kind = "turnin",
            priority = 92,
            conditions = { all = { { faction = "Horde" }, { level = { min = 46 } } } },
            text = "Turn in The Sunken Temple to Marvon Rivetseeker.",
            dependsOn = { "accept-3380-the-sunken-temple" },
            complete = QuestState(3380, "completed"),
            route = {
                Point(MAP.TANARIS, 0.527, 0.459, "Marvon Rivetseeker", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-1424-pool-of-tears",
            kind = "accept",
            priority = 93,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Accept Pool of Tears from Fel'zerul.",
            complete = QuestState(1424, "activeOrCompleted"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "objective-1424-1-atal-ai-artifact",
            kind = "objective",
            priority = 95,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Collect 10 Atal'ai Artifact.",
            dependsOn = { "accept-1424-pool-of-tears" },
            complete = QuestState(1424, "complete"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.671, 0.587, "Swamp of Sorrows", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-1424-pool-of-tears",
            kind = "turnin",
            priority = 96,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Turn in Pool of Tears to Fel'zerul.",
            dependsOn = { "objective-1424-1-atal-ai-artifact" },
            complete = QuestState(1424, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-1429-the-atal-ai-exile",
            kind = "accept",
            priority = 97,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Accept The Atal'ai Exile from Fel'zerul.",
            dependsOn = { "turnin-1424-pool-of-tears" },
            complete = QuestState(1429, "activeOrCompleted"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-1429-the-atal-ai-exile",
            kind = "turnin",
            priority = 98,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Turn in The Atal'ai Exile to Atal'ai Exile.",
            dependsOn = { "accept-1429-the-atal-ai-exile" },
            complete = QuestState(1429, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.338, 0.752, "Atal'ai Exile", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-1444-return-to-fel-zerul",
            kind = "accept",
            priority = 99,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Accept Return to Fel'Zerul from Atal'ai Exile.",
            dependsOn = { "turnin-1429-the-atal-ai-exile" },
            complete = QuestState(1444, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.338, 0.752, "Atal'ai Exile", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-1444-return-to-fel-zerul",
            kind = "turnin",
            priority = 100,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Turn in Return to Fel'Zerul to Fel'zerul.",
            dependsOn = { "accept-1444-return-to-fel-zerul" },
            complete = QuestState(1444, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-1445-the-temple-of-atal-hakkar",
            kind = "accept",
            priority = 101,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Accept The Temple of Atal'Hakkar from Fel'zerul.",
            dependsOn = { "turnin-1444-return-to-fel-zerul" },
            complete = QuestState(1445, "activeOrCompleted"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "accept-4145-larion-and-muigin",
            kind = "accept",
            priority = 102,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Accept Larion and Muigin from Larion.",
            complete = QuestState(4145, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.455, 0.087, "Larion", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4145-3-bloodpetal-flayer",
            kind = "objective",
            priority = 103,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Kill 5 Bloodpetal Flayer.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 3, "Bloodpetal Flayer"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.571, 0.164, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4145-4-bloodpetal-thresher",
            kind = "objective",
            priority = 104,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Kill 5 Bloodpetal Thresher.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 4, "Bloodpetal Thresher"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.566, 0.345, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4145-1-bloodpetal-lasher",
            kind = "objective",
            priority = 105,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Kill 5 Bloodpetal Lasher.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 1, "Bloodpetal Lasher"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.698, 0.298, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "objective-4145-2-bloodpetal-trapper",
            kind = "objective",
            priority = 106,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Kill 5 Bloodpetal Trapper.",
            dependsOn = { "accept-4145-larion-and-muigin" },
            complete = QuestObjective(4145, 2, "Bloodpetal Trapper"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.399, 0.535, "Un'Goro Crater", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-4145-larion-and-muigin",
            kind = "turnin",
            priority = 107,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Turn in Larion and Muigin to Larion.",
            dependsOn = { "objective-4145-3-bloodpetal-flayer", "objective-4145-4-bloodpetal-thresher", "objective-4145-1-bloodpetal-lasher", "objective-4145-2-bloodpetal-trapper" },
            complete = QuestState(4145, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.455, 0.087, "Larion", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "accept-4147-marvon-s-workshop",
            kind = "accept",
            priority = 108,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Accept Marvon's Workshop from Larion.",
            dependsOn = { "turnin-4145-larion-and-muigin" },
            complete = QuestState(4147, "activeOrCompleted"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.455, 0.087, "Larion", "Travel to Un'Goro Crater."),
            },
        },
        {
            id = "turnin-4147-marvon-s-workshop",
            kind = "turnin",
            priority = 109,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Turn in Marvon's Workshop to Liv Rizzlefix.",
            dependsOn = { "accept-4147-marvon-s-workshop" },
            complete = QuestState(4147, "completed"),
            route = {
                Point(MAP.THE_BARRENS, 0.625, 0.387, "Liv Rizzlefix", "Travel to The Barrens."),
            },
        },
        {
            id = "accept-4146-zapper-fuel",
            kind = "accept",
            priority = 110,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Accept Zapper Fuel from Liv Rizzlefix.",
            dependsOn = { "turnin-4147-marvon-s-workshop" },
            complete = QuestState(4146, "activeOrCompleted"),
            route = {
                Point(MAP.THE_BARRENS, 0.625, 0.387, "Liv Rizzlefix", "Travel to The Barrens."),
            },
        },
        {
            id = "objective-4146-1-atal-ai-haze",
            kind = "objective",
            priority = 117,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Collect 5 Atal'ai Haze.",
            dependsOn = { "accept-4146-zapper-fuel" },
            complete = QuestState(4146, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-1445-the-temple-of-atal-hakkar",
            kind = "turnin",
            priority = 118,
            conditions = { all = { { faction = "Horde" }, { level = { min = 38 } } } },
            text = "Turn in The Temple of Atal'Hakkar to Fel'zerul.",
            dependsOn = { "objective-1445-1-fetish-of-hakkar" },
            complete = QuestState(1445, "completed"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.479, 0.548, "Fel'zerul", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-4146-zapper-fuel",
            kind = "turnin",
            priority = 119,
            conditions = { all = { { faction = "Horde" }, { level = { min = 47 } } } },
            text = "Turn in Zapper Fuel to Larion.",
            dependsOn = { "objective-4146-1-atal-ai-haze" },
            complete = QuestState(4146, "completed"),
            route = {
                Point(MAP.UN_GORO_CRATER, 0.455, 0.087, "Larion", "Travel to Un'Goro Crater."),
            },
        },
    },
})
