local _, ns = ...

local MAP = {
    IRONFORGE = 1455,
    BADLANDS = 1418,
    LOCH_MODAN = 1432,
    UNDERCITY = 1458,
    ORGRIMMAR = 1454,
    THUNDER_BLUFF = 1456,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-uldaman",
    title = "Uldaman",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 37 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-2198-the-shattered-necklace",
            kind = "accept",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Kill Shadowforge dwarves in the Badlands until a Shattered Necklace drops. " ..
                "Use the necklace to accept The Shattered Necklace.",
            complete = QuestState(2198, "activeOrCompleted"),
        },
        {
            id = "turnin-2198-the-shattered-necklace",
            kind = "turnin",
            priority = 13,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Turn in The Shattered Necklace to Talvash del Kissel.",
            dependsOn = { "accept-2198-the-shattered-necklace" },
            complete = QuestState(2198, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.364, 0.036, "Talvash del Kissel", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2199-lore-for-a-price",
            kind = "accept",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Accept Lore for a Price from Talvash del Kissel.",
            dependsOn = { "turnin-2198-the-shattered-necklace" },
            complete = QuestState(2199, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.364, 0.036, "Talvash del Kissel", "Travel to Ironforge."),
            },
        },
        {
            id = "objective-2199-1-silver-bar",
            kind = "objective",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Collect 5 Silver Bar.",
            dependsOn = { "accept-2199-lore-for-a-price" },
            complete = QuestState(2199, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-2199-lore-for-a-price",
            kind = "turnin",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Turn in Lore for a Price to Talvash del Kissel.",
            dependsOn = { "objective-2199-1-silver-bar" },
            complete = QuestState(2199, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.364, 0.036, "Talvash del Kissel", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2200-back-to-uldaman",
            kind = "accept",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Accept Back to Uldaman from Talvash del Kissel.",
            dependsOn = { "turnin-2199-lore-for-a-price" },
            complete = QuestState(2200, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.364, 0.036, "Talvash del Kissel", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2398-the-lost-dwarves",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept The Lost Dwarves from Prospector Stormpike.",
            complete = QuestState(2398, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.746, 0.118, "Prospector Stormpike", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-720-a-sign-of-hope",
            kind = "accept",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Accept A Sign of Hope.",
            complete = QuestState(720, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.530, 0.339, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-720-a-sign-of-hope",
            kind = "turnin",
            priority = 21,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Turn in A Sign of Hope to Prospector Ryedol.",
            dependsOn = { "accept-720-a-sign-of-hope" },
            complete = QuestState(720, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.534, 0.434, "Prospector Ryedol", "Travel to Badlands."),
            },
        },
        {
            id = "accept-721-a-sign-of-hope",
            kind = "accept",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept A Sign of Hope from Prospector Ryedol.",
            dependsOn = { "turnin-720-a-sign-of-hope" },
            complete = QuestState(721, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.534, 0.434, "Prospector Ryedol", "Travel to Badlands."),
            },
        },
        {
            id = "objective-721-1-hammertoe-grez-in-uldama",
            kind = "objective",
            priority = 23,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Find Hammertoe Grez in Uldaman.",
            dependsOn = { "accept-721-a-sign-of-hope" },
            complete = QuestState(721, "complete"),
            route = {
                Point(MAP.BADLANDS, 0.540, 0.577, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-721-a-sign-of-hope",
            kind = "turnin",
            priority = 24,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in A Sign of Hope to Hammertoe Grez.",
            dependsOn = { "objective-721-1-hammertoe-grez-in-uldama" },
            complete = QuestState(721, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.540, 0.577, "Hammertoe Grez", "Travel to Badlands."),
            },
        },
        {
            id = "accept-722-amulet-of-secrets",
            kind = "accept",
            priority = 25,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept Amulet of Secrets from Hammertoe Grez.",
            dependsOn = { "turnin-721-a-sign-of-hope" },
            complete = QuestState(722, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.540, 0.577, "Hammertoe Grez", "Travel to Badlands."),
            },
        },
        {
            id = "objective-722-1-hammertoe-s-amulet",
            kind = "objective",
            priority = 27,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Loot Hammertoe's Amulet from Hammertoe Grez's corpse in Uldaman.",
            dependsOn = { "accept-722-amulet-of-secrets" },
            complete = QuestState(722, "complete"),
            route = {
                Point(MAP.BADLANDS, 0.538, 0.580, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-722-amulet-of-secrets",
            kind = "turnin",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in Amulet of Secrets to Hammertoe Grez.",
            dependsOn = { "objective-722-1-hammertoe-s-amulet" },
            complete = QuestState(722, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.540, 0.577, "Hammertoe Grez", "Travel to Badlands."),
            },
        },
        {
            id = "accept-723-prospect-of-faith",
            kind = "accept",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept Prospect of Faith from Hammertoe Grez.",
            dependsOn = { "turnin-722-amulet-of-secrets" },
            complete = QuestState(723, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.540, 0.577, "Hammertoe Grez", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-723-prospect-of-faith",
            kind = "turnin",
            priority = 30,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in Prospect of Faith to Prospector Ryedol.",
            dependsOn = { "accept-723-prospect-of-faith" },
            complete = QuestState(723, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.534, 0.434, "Prospector Ryedol", "Travel to Badlands."),
            },
        },
        {
            id = "accept-724-prospect-of-faith",
            kind = "accept",
            priority = 31,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept Prospect of Faith from Prospector Ryedol.",
            dependsOn = { "turnin-723-prospect-of-faith" },
            complete = QuestState(724, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.534, 0.434, "Prospector Ryedol", "Travel to Badlands."),
            },
        },
        {
            id = "accept-707-ironband-wants-you",
            kind = "accept",
            priority = 32,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Accept Ironband Wants You! from Prospector Stormpike.",
            complete = QuestState(707, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.747, 0.117, "Prospector Stormpike", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-724-prospect-of-faith",
            kind = "turnin",
            priority = 33,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in Prospect of Faith to Historian Karnik.",
            dependsOn = { "accept-724-prospect-of-faith" },
            complete = QuestState(724, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.776, 0.118, "Historian Karnik", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-725-passing-word-of-a-threat",
            kind = "accept",
            priority = 34,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept Passing Word of a Threat from Historian Karnik.",
            dependsOn = { "turnin-724-prospect-of-faith" },
            complete = QuestState(725, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.776, 0.118, "Historian Karnik", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-725-passing-word-of-a-threat",
            kind = "turnin",
            priority = 35,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in Passing Word of a Threat to Advisor Belgrum.",
            dependsOn = { "accept-725-passing-word-of-a-threat" },
            complete = QuestState(725, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.773, 0.098, "Advisor Belgrum", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-726-passing-word-of-a-threat",
            kind = "accept",
            priority = 36,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept Passing Word of a Threat from Advisor Belgrum.",
            dependsOn = { "turnin-725-passing-word-of-a-threat" },
            complete = QuestState(726, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.773, 0.098, "Advisor Belgrum", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-726-passing-word-of-a-threat",
            kind = "turnin",
            priority = 37,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in Passing Word of a Threat to Historian Karnik.",
            dependsOn = { "accept-726-passing-word-of-a-threat" },
            complete = QuestState(726, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.776, 0.118, "Historian Karnik", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-762-an-ambassador-of-evil",
            kind = "accept",
            priority = 38,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept An Ambassador of Evil from Historian Karnik.",
            dependsOn = { "turnin-726-passing-word-of-a-threat" },
            complete = QuestState(762, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.776, 0.118, "Historian Karnik", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2500-badlands-reagent-run",
            kind = "accept",
            priority = 39,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Accept Badlands Reagent Run from Ghak Healtouch.",
            complete = QuestState(2500, "activeOrCompleted"),
            route = {
                Point(MAP.LOCH_MODAN, 0.371, 0.494, "Ghak Healtouch", "Travel to Loch Modan."),
            },
        },
        {
            id = "turnin-707-ironband-wants-you",
            kind = "turnin",
            priority = 40,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Turn in Ironband Wants You! to Prospector Ironband.",
            dependsOn = { "accept-707-ironband-wants-you" },
            complete = QuestState(707, "completed"),
            route = {
                Point(MAP.LOCH_MODAN, 0.659, 0.656, "Prospector Ironband", "Travel to Loch Modan."),
            },
        },
        {
            id = "accept-738-find-agmond",
            kind = "accept",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Accept Find Agmond from Prospector Ironband.",
            dependsOn = { "turnin-707-ironband-wants-you" },
            complete = QuestState(738, "activeOrCompleted"),
            route = {
                Point(MAP.LOCH_MODAN, 0.659, 0.656, "Prospector Ironband", "Travel to Loch Modan."),
            },
        },
        {
            id = "turnin-738-find-agmond",
            kind = "turnin",
            priority = 43,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Turn in Find Agmond to Prospector Ironband.",
            dependsOn = { "accept-738-find-agmond" },
            complete = QuestState(738, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.509, 0.624, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "accept-739-murdaloc",
            kind = "accept",
            priority = 44,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Accept Murdaloc.",
            dependsOn = { "turnin-738-find-agmond" },
            complete = QuestState(739, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.509, 0.624, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-739-1-murdaloc",
            kind = "objective",
            priority = 45,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Kill Murdaloc.",
            dependsOn = { "accept-739-murdaloc" },
            complete = QuestObjective(739, 1, "Murdaloc"),
            route = {
                Point(MAP.BADLANDS, 0.496, 0.663, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-739-2-stonevault-bonesnapper",
            kind = "objective",
            priority = 46,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Kill 12 Stonevault Bonesnapper.",
            dependsOn = { "accept-739-murdaloc" },
            complete = QuestObjective(739, 2, "Stonevault Bonesnapper"),
            route = {
                Point(MAP.BADLANDS, 0.512, 0.683, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-762-1-ambassador-infernus-brac",
            kind = "objective",
            priority = 48,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Collect Ambassador Infernus' Bracer.",
            dependsOn = { "accept-762-an-ambassador-of-evil" },
            complete = QuestState(762, "complete"),
            route = {
                Point(MAP.BADLANDS, 0.421, 0.289, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-2500-3-rock-elemental-shard",
            kind = "objective",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Collect 5 Rock Elemental Shard.",
            dependsOn = { "accept-2500-badlands-reagent-run" },
            complete = QuestObjective(2500, 3, "Rock Elemental Shard"),
            route = {
                Point(MAP.BADLANDS, 0.195, 0.430, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-2500-1-buzzard-gizzard",
            kind = "objective",
            priority = 52,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Collect 5 Buzzard Gizzard.",
            dependsOn = { "accept-2500-badlands-reagent-run" },
            complete = QuestObjective(2500, 1, "Buzzard Gizzard"),
            route = {
                Point(MAP.BADLANDS, 0.168, 0.598, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-2500-2-crag-coyote-fang",
            kind = "objective",
            priority = 54,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Collect 10 Crag Coyote Fang.",
            dependsOn = { "accept-2500-badlands-reagent-run" },
            complete = QuestObjective(2500, 2, "Crag Coyote Fang"),
            route = {
                Point(MAP.BADLANDS, 0.237, 0.551, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "accept-704-agmond-s-fate",
            kind = "accept",
            priority = 55,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 30 } } } },
            text = "Accept Agmond's Fate from Prospector Ironband.",
            dependsOn = { "turnin-738-find-agmond" },
            complete = QuestState(704, "activeOrCompleted"),
            route = {
                Point(MAP.LOCH_MODAN, 0.659, 0.656, "Prospector Ironband", "Travel to Loch Modan."),
            },
        },
        {
            id = "turnin-2500-badlands-reagent-run",
            kind = "turnin",
            priority = 56,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 41 } } } },
            text = "Turn in Badlands Reagent Run to Ghak Healtouch.",
            dependsOn = { "objective-2500-3-rock-elemental-shard", "objective-2500-1-buzzard-gizzard", "objective-2500-2-crag-coyote-fang" },
            complete = QuestState(2500, "completed"),
            route = {
                Point(MAP.LOCH_MODAN, 0.371, 0.494, "Ghak Healtouch", "Travel to Loch Modan."),
            },
        },
        {
            id = "accept-17-uldaman-reagent-run",
            kind = "accept",
            priority = 57,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Accept Uldaman Reagent Run from Ghak Healtouch.",
            dependsOn = { "turnin-2500-badlands-reagent-run" },
            complete = QuestState(17, "activeOrCompleted"),
            route = {
                Point(MAP.LOCH_MODAN, 0.371, 0.494, "Ghak Healtouch", "Travel to Loch Modan."),
            },
        },
        {
            id = "turnin-762-an-ambassador-of-evil",
            kind = "turnin",
            priority = 58,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in An Ambassador of Evil to Advisor Belgrum.",
            dependsOn = { "objective-762-1-ambassador-infernus-brac" },
            complete = QuestState(762, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.773, 0.098, "Advisor Belgrum", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-1139-the-lost-tablets-of-will",
            kind = "accept",
            priority = 59,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept The Lost Tablets of Will from Advisor Belgrum.",
            dependsOn = { "turnin-762-an-ambassador-of-evil" },
            complete = QuestState(1139, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.773, 0.098, "Advisor Belgrum", "Travel to Ironforge."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 60,
            conditions = { level = { min = 38 } },
            text = "Enter Uldaman with your group.",
            dependsOn = { "accept-2198-the-shattered-necklace", "accept-2199-lore-for-a-price", "accept-2200-back-to-uldaman", "accept-2398-the-lost-dwarves", "accept-720-a-sign-of-hope", "accept-721-a-sign-of-hope", "accept-722-amulet-of-secrets", "accept-723-prospect-of-faith", "accept-724-prospect-of-faith", "accept-707-ironband-wants-you", "accept-725-passing-word-of-a-threat", "accept-726-passing-word-of-a-threat", "accept-762-an-ambassador-of-evil", "accept-2500-badlands-reagent-run", "accept-738-find-agmond", "accept-739-murdaloc", "accept-704-agmond-s-fate", "accept-17-uldaman-reagent-run", "accept-1139-the-lost-tablets-of-will" },
            persistCompletion = true,
            complete = { instance = 70 },
        },
        {
            id = "turnin-2200-back-to-uldaman",
            kind = "turnin",
            priority = 61,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Turn in Back to Uldaman to Remains of a Paladin.",
            dependsOn = { "accept-2200-back-to-uldaman" },
            complete = QuestState(2200, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-2201-find-the-gems",
            kind = "accept",
            priority = 62,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Accept Find the Gems from Remains of a Paladin.",
            dependsOn = { "turnin-2200-back-to-uldaman" },
            complete = QuestState(2201, "activeOrCompleted"),
        },
        {
            id = "turnin-2398-the-lost-dwarves",
            kind = "turnin",
            priority = 63,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in The Lost Dwarves to Baelog.",
            dependsOn = { "accept-2398-the-lost-dwarves" },
            complete = QuestState(2398, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-2240-the-hidden-chamber",
            kind = "accept",
            priority = 64,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Accept The Hidden Chamber from Baelog.",
            dependsOn = { "turnin-2398-the-lost-dwarves" },
            complete = QuestState(2240, "activeOrCompleted"),
        },
        {
            id = "objective-2201-3-shattered-necklace-topaz",
            kind = "objective",
            priority = 67,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Kill Grimlok and loot the Shattered Necklace Topaz.",
            dependsOn = { "accept-2201-find-the-gems" },
            complete = QuestObjective(2201, 3, "Shattered Necklace Topaz"),
            useClientPin = true,
        },
        {
            id = "objective-2240-1-explore-the-hidden-chamb",
            kind = "objective",
            priority = 70,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Explore the Hidden Chamber.",
            dependsOn = { "accept-2240-the-hidden-chamber" },
            complete = QuestState(2240, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2201-1-shattered-necklace-ruby",
            kind = "objective",
            priority = 72,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Kill Galgann Firehammer and loot the Shattered Necklace Ruby.",
            dependsOn = { "accept-2201-find-the-gems" },
            complete = QuestObjective(2201, 1, "Shattered Necklace Ruby"),
            useClientPin = true,
        },
        {
            id = "objective-1139-1-tablet-of-will",
            kind = "objective",
            priority = 74,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Loot the Tablet of Will from the stone tablet in Uldaman.",
            dependsOn = { "accept-1139-the-lost-tablets-of-will" },
            complete = QuestState(1139, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2201-2-shattered-necklace-sapph",
            kind = "objective",
            priority = 76,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Kill the Ancient Stone Keeper and loot the Shattered Necklace Sapphire.",
            dependsOn = { "accept-2201-find-the-gems" },
            complete = QuestObjective(2201, 2, "Shattered Necklace Sapphire"),
            useClientPin = true,
        },
        {
            id = "turnin-2201-find-the-gems",
            kind = "turnin",
            priority = 78,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Turn in Find the Gems.",
            dependsOn = { "objective-2201-3-shattered-necklace-topaz", "objective-2201-1-shattered-necklace-ruby", "objective-2201-2-shattered-necklace-sapph" },
            complete = QuestState(2201, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-2204-restoring-the-necklace",
            kind = "accept",
            priority = 79,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Accept Restoring the Necklace.",
            dependsOn = { "turnin-2201-find-the-gems" },
            complete = QuestState(2204, "activeOrCompleted"),
        },
        {
            id = "objective-2204-1-shattered-necklace-power",
            kind = "objective",
            priority = 82,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Loot the Shattered Necklace Power Source from the altar in Uldaman.",
            dependsOn = { "accept-2204-restoring-the-necklace" },
            complete = QuestState(2204, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-2278-the-platinum-discs",
            kind = "accept",
            priority = 84,
            conditions = { level = { min = 40 } },
            text = "Accept The Platinum Discs.",
            complete = QuestState(2278, "activeOrCompleted"),
        },
        {
            id = "objective-2278-1-learn-what-lore-that-the",
            kind = "gossip",
            priority = 85,
            conditions = { level = { min = 40 } },
            text = "Talk to Lore Keeper of Norgannon. 'Who are the Earthen?' Learn What Lore That the Stone Watcher Has to Offer.",
            dependsOn = { "accept-2278-the-platinum-discs" },
            complete = QuestState(2278, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-2278-the-platinum-discs",
            kind = "turnin",
            priority = 86,
            conditions = { level = { min = 40 } },
            text = "Turn in The Platinum Discs.",
            dependsOn = { "objective-2278-1-learn-what-lore-that-the" },
            complete = QuestState(2278, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-2279-the-platinum-discs",
            kind = "accept",
            priority = 87,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept The Platinum Discs.",
            dependsOn = { "turnin-2278-the-platinum-discs" },
            complete = QuestState(2279, "activeOrCompleted"),
        },
        {
            id = "objective-704-1-carved-stone-urn",
            kind = "objective",
            priority = 89,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 30 } } } },
            text = "Collect 4 Carved Stone Urn.",
            dependsOn = { "accept-704-agmond-s-fate" },
            complete = QuestState(704, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2202-1-magenta-cap-cluster",
            kind = "objective",
            priority = 91,
            conditions = { all = { { faction = "Horde" }, { level = { min = 36 } } } },
            text = "Collect 12 Magenta Cap Cluster.",
            dependsOn = { "accept-2202-uldaman-reagent-run" },
            complete = QuestState(2202, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-704-agmond-s-fate",
            kind = "turnin",
            priority = 94,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 30 } } } },
            text = "Turn in Agmond's Fate to Prospector Ironband.",
            dependsOn = { "objective-704-1-carved-stone-urn" },
            complete = QuestState(704, "completed"),
            route = {
                Point(MAP.LOCH_MODAN, 0.659, 0.656, "Prospector Ironband", "Travel to Loch Modan."),
            },
        },
        {
            id = "turnin-17-uldaman-reagent-run",
            kind = "turnin",
            priority = 95,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 38 } } } },
            text = "Turn in Uldaman Reagent Run to Ghak Healtouch.",
            dependsOn = { "accept-17-uldaman-reagent-run" },
            complete = QuestState(17, "completed"),
            route = {
                Point(MAP.LOCH_MODAN, 0.371, 0.494, "Ghak Healtouch", "Travel to Loch Modan."),
            },
        },
        {
            id = "turnin-3448-passing-the-burden",
            kind = "turnin",
            priority = 96,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Turn in Passing the Burden to Tymor.",
            complete = QuestState(3448, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.310, 0.048, "Tymor", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2279-the-platinum-discs",
            kind = "turnin",
            priority = 97,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in The Platinum Discs to High Explorer Magellas.",
            dependsOn = { "accept-2279-the-platinum-discs" },
            complete = QuestState(2279, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.699, 0.185, "High Explorer Magellas", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2439-the-platinum-discs",
            kind = "accept",
            priority = 98,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept The Platinum Discs from High Explorer Magellas.",
            dependsOn = { "turnin-2279-the-platinum-discs" },
            complete = QuestState(2439, "activeOrCompleted"),
            route = {
                Point(MAP.IRONFORGE, 0.699, 0.185, "High Explorer Magellas", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2439-the-platinum-discs",
            kind = "turnin",
            priority = 99,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in The Platinum Discs to Dinita Stonemantle.",
            dependsOn = { "accept-2439-the-platinum-discs" },
            complete = QuestState(2439, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.335, 0.602, "Dinita Stonemantle", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-2204-restoring-the-necklace-goto-ironforge-36-3",
            kind = "turnin",
            priority = 100,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 37 } } } },
            text = "Turn in Restoring the Necklace|goto Ironforge 36.36,3.62 to Talvash del Kissel.",
            dependsOn = { "objective-2204-1-shattered-necklace-power" },
            complete = QuestState(2204, "completed"),
            useClientPin = true,
        },
        {
            id = "turnin-2240-the-hidden-chamber",
            kind = "turnin",
            priority = 101,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in The Hidden Chamber to Prospector Stormpike.",
            dependsOn = { "objective-2240-1-explore-the-hidden-chamb" },
            complete = QuestState(2240, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.747, 0.117, "Prospector Stormpike", "Travel to Ironforge."),
            },
        },
        {
            id = "turnin-1139-the-lost-tablets-of-will",
            kind = "turnin",
            priority = 102,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 35 } } } },
            text = "Turn in The Lost Tablets of Will to Advisor Belgrum.",
            dependsOn = { "objective-1139-1-tablet-of-will" },
            complete = QuestState(1139, "completed"),
            route = {
                Point(MAP.IRONFORGE, 0.773, 0.098, "Advisor Belgrum", "Travel to Ironforge."),
            },
        },
        {
            id = "accept-2342-reclaimed-treasure",
            kind = "accept",
            priority = 103,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Accept Reclaimed Treasure from Patrick Garrett.",
            complete = QuestState(2342, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.623, 0.486, "Patrick Garrett", "Travel to Undercity."),
            },
        },
        {
            id = "accept-2418-power-stones",
            kind = "accept",
            priority = 104,
            conditions = { all = { { faction = "Horde" }, { level = { min = 30 } } } },
            text = "Accept Power Stones from Rigglefuzz.",
            complete = QuestState(2418, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.424, 0.530, "Rigglefuzz", "Travel to Badlands."),
            },
        },
        {
            id = "accept-709-solution-to-doom",
            kind = "accept",
            priority = 105,
            conditions = { all = { { faction = "Horde" }, { level = { min = 30 } } } },
            text = "Accept Solution to Doom from Theldurin the Lost.",
            complete = QuestState(709, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.514, 0.769, "Theldurin the Lost", "Travel to Badlands."),
            },
        },
        {
            id = "accept-2258-badlands-reagent-run",
            kind = "accept",
            priority = 106,
            conditions = { all = { { faction = "Horde" }, { level = { min = 39 } } } },
            text = "Accept Badlands Reagent Run from Jarkal Mossmeld.",
            complete = QuestState(2258, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "objective-2258-3-rock-elemental-shard",
            kind = "objective",
            priority = 107,
            conditions = { all = { { faction = "Horde" }, { level = { min = 39 } } } },
            text = "Collect 5 Rock Elemental Shard.",
            dependsOn = { "accept-2258-badlands-reagent-run" },
            complete = QuestObjective(2258, 3, "Rock Elemental Shard"),
            route = {
                Point(MAP.BADLANDS, 0.195, 0.430, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-2258-1-buzzard-gizzard",
            kind = "objective",
            priority = 108,
            conditions = { all = { { faction = "Horde" }, { level = { min = 39 } } } },
            text = "Collect 5 Buzzard Gizzard.",
            dependsOn = { "accept-2258-badlands-reagent-run" },
            complete = QuestObjective(2258, 1, "Buzzard Gizzard"),
            route = {
                Point(MAP.BADLANDS, 0.168, 0.598, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-2258-2-crag-coyote-fang",
            kind = "objective",
            priority = 109,
            conditions = { all = { { faction = "Horde" }, { level = { min = 39 } } } },
            text = "Collect 10 Crag Coyote Fang.",
            dependsOn = { "accept-2258-badlands-reagent-run" },
            complete = QuestObjective(2258, 2, "Crag Coyote Fang"),
            route = {
                Point(MAP.BADLANDS, 0.237, 0.551, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-2258-badlands-reagent-run",
            kind = "turnin",
            priority = 110,
            conditions = { all = { { faction = "Horde" }, { level = { min = 39 } } } },
            text = "Turn in Badlands Reagent Run to Jarkal Mossmeld.",
            dependsOn = { "objective-2258-3-rock-elemental-shard", "objective-2258-1-buzzard-gizzard", "objective-2258-2-crag-coyote-fang" },
            complete = QuestState(2258, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "accept-2202-uldaman-reagent-run",
            kind = "accept",
            priority = 111,
            conditions = { all = { { faction = "Horde" }, { level = { min = 36 } } } },
            text = "Accept Uldaman Reagent Run from Jarkal Mossmeld.",
            dependsOn = { "turnin-2258-badlands-reagent-run" },
            complete = QuestState(2202, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "accept-2283-necklace-recovery",
            kind = "accept",
            priority = 112,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Accept Necklace Recovery from Dran Droffers.",
            complete = QuestState(2283, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.595, 0.366, "Dran Droffers", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-2283-necklace-recovery",
            kind = "turnin",
            priority = 113,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Turn in Necklace Recovery to Dran Droffers.",
            dependsOn = { "accept-2283-necklace-recovery" },
            complete = QuestState(2283, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.595, 0.366, "Dran Droffers", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-2284-necklace-recovery-take-2",
            kind = "accept",
            priority = 114,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Accept Necklace Recovery, Take 2 from Dran Droffers.",
            dependsOn = { "turnin-2283-necklace-recovery" },
            complete = QuestState(2284, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.595, 0.366, "Dran Droffers", "Travel to Orgrimmar."),
            },
        },
        {
            id = "objective-709-1-tablet-of-ryun-eh",
            kind = "objective",
            priority = 116,
            conditions = { all = { { faction = "Horde" }, { level = { min = 30 } } } },
            text = "Collect Tablet of Ryun'eh.",
            dependsOn = { "accept-709-solution-to-doom" },
            complete = QuestState(709, "complete"),
            route = {
                Point(MAP.BADLANDS, 0.541, 0.582, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "objective-2342-1-garrett-family-treasure",
            kind = "objective",
            priority = 118,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Collect Garrett Family Treasure.",
            dependsOn = { "accept-2342-reclaimed-treasure" },
            complete = QuestState(2342, "complete"),
            route = {
                Point(MAP.BADLANDS, 0.538, 0.582, "Badlands", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-2284-necklace-recovery-take-2",
            kind = "turnin",
            priority = 119,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Turn in Necklace Recovery, Take 2 to Remains of a Paladin.",
            dependsOn = { "accept-2284-necklace-recovery-take-2" },
            complete = QuestState(2284, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-2318-translating-the-journal",
            kind = "accept",
            priority = 120,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Accept Translating the Journal from Remains of a Paladin.",
            dependsOn = { "turnin-2284-necklace-recovery-take-2" },
            complete = QuestState(2318, "activeOrCompleted"),
        },
        {
            id = "turnin-2318-translating-the-journal",
            kind = "turnin",
            priority = 121,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Turn in Translating the Journal to Jarkal Mossmeld.",
            dependsOn = { "accept-2318-translating-the-journal" },
            complete = QuestState(2318, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "accept-2338-translating-the-journal",
            kind = "accept",
            priority = 122,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Accept Translating the Journal from Jarkal Mossmeld.",
            dependsOn = { "turnin-2318-translating-the-journal" },
            complete = QuestState(2338, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-2338-translating-the-journal",
            kind = "turnin",
            priority = 123,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Turn in Translating the Journal to Jarkal Mossmeld.",
            dependsOn = { "accept-2338-translating-the-journal" },
            complete = QuestState(2338, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-2339-find-the-gems-and-power-source",
            kind = "accept",
            priority = 124,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Accept Find the Gems and Power Source from Jarkal Mossmeld.",
            dependsOn = { "turnin-2338-translating-the-journal" },
            complete = QuestState(2339, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "objective-2339-3-shattered-necklace-topaz",
            kind = "objective",
            priority = 125,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Collect Shattered Necklace Topaz.",
            dependsOn = { "accept-2339-find-the-gems-and-power-source" },
            complete = QuestObjective(2339, 3, "Shattered Necklace Topaz"),
            useClientPin = true,
        },
        {
            id = "objective-2339-1-shattered-necklace-ruby",
            kind = "objective",
            priority = 126,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Collect Shattered Necklace Ruby.",
            dependsOn = { "accept-2339-find-the-gems-and-power-source" },
            complete = QuestObjective(2339, 1, "Shattered Necklace Ruby"),
            useClientPin = true,
        },
        {
            id = "objective-2339-2-shattered-necklace-sapph",
            kind = "objective",
            priority = 131,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Collect Shattered Necklace Sapphire.",
            dependsOn = { "accept-2339-find-the-gems-and-power-source" },
            complete = QuestObjective(2339, 2, "Shattered Necklace Sapphire"),
            useClientPin = true,
        },
        {
            id = "objective-2339-4-shattered-necklace-power",
            kind = "objective",
            priority = 133,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Collect Shattered Necklace Power Source.",
            dependsOn = { "accept-2339-find-the-gems-and-power-source" },
            complete = QuestObjective(2339, 4, "Shattered Necklace Power Source"),
            useClientPin = true,
        },
        {
            id = "accept-2280-the-platinum-discs",
            kind = "accept",
            priority = 134,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Accept The Platinum Discs.",
            dependsOn = { "turnin-2338-translating-the-journal", "turnin-2278-the-platinum-discs" },
            complete = QuestState(2280, "activeOrCompleted"),
        },
        {
            id = "objective-2418-1-dentrium-power-stone",
            kind = "objective",
            priority = 136,
            conditions = { all = { { faction = "Horde" }, { level = { min = 30 } } } },
            text = "Collect 8 Dentrium Power Stone.",
            dependsOn = { "accept-2418-power-stones" },
            complete = QuestObjective(2418, 1, "Dentrium Power Stone"),
            useClientPin = true,
        },
        {
            id = "objective-2418-2-an-alleum-power-stone",
            kind = "objective",
            priority = 137,
            conditions = { all = { { faction = "Horde" }, { level = { min = 30 } } } },
            text = "Collect 8 An'Alleum Power Stone.",
            dependsOn = { "accept-2418-power-stones" },
            complete = QuestObjective(2418, 2, "An'Alleum Power Stone"),
            useClientPin = true,
        },
        {
            id = "turnin-2202-uldaman-reagent-run",
            kind = "turnin",
            priority = 138,
            conditions = { all = { { faction = "Horde" }, { level = { min = 36 } } } },
            text = "Turn in Uldaman Reagent Run to Jarkal Mossmeld.",
            dependsOn = { "objective-2202-1-magenta-cap-cluster" },
            complete = QuestState(2202, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-2339-find-the-gems-and-power-source",
            kind = "turnin",
            priority = 139,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Turn in Find the Gems and Power Source to Jarkal Mossmeld.",
            dependsOn = { "objective-2339-3-shattered-necklace-topaz", "objective-2339-1-shattered-necklace-ruby", "objective-2339-2-shattered-necklace-sapph", "objective-2339-4-shattered-necklace-power" },
            complete = QuestState(2339, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "accept-2340-deliver-the-gems",
            kind = "accept",
            priority = 140,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Accept Deliver the Gems from Jarkal Mossmeld.",
            dependsOn = { "turnin-2339-find-the-gems-and-power-source" },
            complete = QuestState(2340, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-2418-power-stones",
            kind = "turnin",
            priority = 141,
            conditions = { all = { { faction = "Horde" }, { level = { min = 30 } } } },
            text = "Turn in Power Stones to Rigglefuzz.",
            dependsOn = { "objective-2418-1-dentrium-power-stone", "objective-2418-2-an-alleum-power-stone" },
            complete = QuestState(2418, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.424, 0.530, "Rigglefuzz", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-709-solution-to-doom",
            kind = "turnin",
            priority = 142,
            conditions = { all = { { faction = "Horde" }, { level = { min = 30 } } } },
            text = "Turn in Solution to Doom to Theldurin the Lost.",
            dependsOn = { "objective-709-1-tablet-of-ryun-eh" },
            complete = QuestState(709, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.514, 0.769, "Theldurin the Lost", "Travel to Badlands."),
            },
        },
        {
            id = "turnin-2342-reclaimed-treasure",
            kind = "turnin",
            priority = 143,
            conditions = { all = { { faction = "Horde" }, { level = { min = 33 } } } },
            text = "Turn in Reclaimed Treasure to Patrick Garrett.",
            dependsOn = { "objective-2342-1-garrett-family-treasure" },
            complete = QuestState(2342, "completed"),
            route = {
                Point(MAP.UNDERCITY, 0.623, 0.486, "Patrick Garrett", "Travel to Undercity."),
            },
        },
        {
            id = "turnin-2340-deliver-the-gems",
            kind = "turnin",
            priority = 144,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Turn in Deliver the Gems to Dran Droffers.",
            dependsOn = { "accept-2340-deliver-the-gems" },
            complete = QuestState(2340, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.595, 0.366, "Dran Droffers", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-2341-necklace-recovery-take-3",
            kind = "accept",
            priority = 145,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Accept Necklace Recovery, Take 3 from Dran Droffers.",
            dependsOn = { "turnin-2340-deliver-the-gems" },
            complete = QuestState(2341, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.595, 0.366, "Dran Droffers", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-2280-the-platinum-discs",
            kind = "turnin",
            priority = 146,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Turn in The Platinum Discs to Sage Truthseeker.",
            dependsOn = { "accept-2280-the-platinum-discs" },
            complete = QuestState(2280, "completed"),
            route = {
                Point(MAP.THUNDER_BLUFF, 0.344, 0.469, "Sage Truthseeker", "Travel to Thunder Bluff."),
            },
        },
        {
            id = "turnin-2341-necklace-recovery-take-3",
            kind = "turnin",
            priority = 147,
            conditions = { all = { { faction = "Horde" }, { level = { min = 37 } } } },
            text = "Turn in Necklace Recovery, Take 3 to Jarkal Mossmeld.",
            dependsOn = { "accept-2341-necklace-recovery-take-3" },
            complete = QuestState(2341, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.024, 0.461, "Jarkal Mossmeld", "Travel to Badlands."),
            },
        },
    },
})
