local _, ns = ...

local MAP = {
    STORMWIND_CITY = 1453,
    BURNING_STEPPES = 1428,
    REDRIDGE_MOUNTAINS = 1433,
    SEARING_GORGE = 1427,
    WINTERSPRING = 1452,
    AZSHARA = 1447,
    SILITHUS = 1451,
    EASTERN_PLAGUELANDS = 1423,
    WESTERN_PLAGUELANDS = 1422,
    UNDERCITY = 1458,
    BADLANDS = 1418,
    ORGRIMMAR = 1454,
    DUSTWALLOW_MARSH = 1445,
    TANARIS = 1446,
    SWAMP_OF_SORROWS = 1435,
    WETLANDS = 1437,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-upper-blackrock-spire",
    title = "Upper Blackrock Spire",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 57 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-4766-mayara-brightwing",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Accept Mayara Brightwing from Count Remington Ridgewell.",
            complete = QuestState(4766, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.740, 0.302, "Count Remington Ridgewell", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4766-mayara-brightwing",
            kind = "turnin",
            priority = 11,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Turn in Mayara Brightwing to Mayara Brightwing.",
            dependsOn = { "accept-4766-mayara-brightwing" },
            complete = QuestState(4766, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.691, "Mayara Brightwing", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4764-doomrigger-s-clasp",
            kind = "accept",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Accept Doomrigger's Clasp from Mayara Brightwing.",
            dependsOn = { "turnin-4766-mayara-brightwing" },
            complete = QuestState(4764, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.691, "Mayara Brightwing", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4726-broodling-essence",
            kind = "accept",
            priority = 13,
            conditions = { level = { min = 50 } },
            text = "Accept Broodling Essence from Tinkee Steamboil.",
            complete = QuestState(4726, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4182-dragonkin-menace",
            kind = "accept",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Dragonkin Menace from Helendis Riverhorn.",
            complete = QuestState(4182, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.690, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-1-black-broodling",
            kind = "objective",
            priority = 15,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill 15 Black Broodling.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 1, "Black Broodling"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.892, 0.538, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-2-black-dragonspawn",
            kind = "objective",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill 10 Black Dragonspawn.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 2, "Black Dragonspawn"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.920, 0.538, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-3-black-drake",
            kind = "objective",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill 1 Black Drake.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 3, "Black Drake"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.892, 0.538, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4182-4-black-wyrmkin",
            kind = "objective",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Kill 4 Black Wyrmkin.",
            dependsOn = { "accept-4182-dragonkin-menace" },
            complete = QuestObjective(4182, 4, "Black Wyrmkin"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.920, 0.538, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "boss-broodling-enemies-around-this-area",
            kind = "note",
            priority = 19,
            conditions = { level = { min = 57 } },
            text = "Kill Broodling enemies around this area. Use it on Broodling enemies around this area. They look like small flying dragons. They look like red floating crystals that appear above their corpses after you kill them.",
        },
        {
            id = "note-click-broodling-essence",
            kind = "note",
            priority = 20,
            conditions = { level = { min = 57 } },
            text = "Click Broodling Essence+.",
        },
        {
            id = "objective-4726-1-broodling-essence",
            kind = "objective",
            priority = 21,
            conditions = { level = { min = 50 } },
            text = "Collect 8 Broodling Essence.",
            dependsOn = { "accept-4726-broodling-essence" },
            complete = QuestState(4726, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.593, 0.325, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4182-dragonkin-menace",
            kind = "turnin",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Dragonkin Menace to Helendis Riverhorn.",
            dependsOn = { "objective-4182-1-black-broodling", "objective-4182-2-black-dragonspawn", "objective-4182-3-black-drake", "objective-4182-4-black-wyrmkin" },
            complete = QuestState(4182, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.690, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4183-the-true-masters",
            kind = "accept",
            priority = 23,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Helendis Riverhorn.",
            dependsOn = { "turnin-4182-dragonkin-menace" },
            complete = QuestState(4183, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.858, 0.690, "Helendis Riverhorn", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4183-the-true-masters",
            kind = "turnin",
            priority = 24,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Magistrate Solomon.",
            dependsOn = { "accept-4183-the-true-masters" },
            complete = QuestState(4183, "completed"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "accept-4184-the-true-masters",
            kind = "accept",
            priority = 25,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Magistrate Solomon.",
            dependsOn = { "turnin-4183-the-true-masters" },
            complete = QuestState(4184, "activeOrCompleted"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "turnin-4184-the-true-masters",
            kind = "turnin",
            priority = 26,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Highlord Bolvar Fordragon.",
            dependsOn = { "accept-4184-the-true-masters" },
            complete = QuestState(4184, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-4185-the-true-masters",
            kind = "accept",
            priority = 27,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Highlord Bolvar Fordragon.",
            dependsOn = { "turnin-4184-the-true-masters" },
            complete = QuestState(4185, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "objective-4185-1-receive-advice-from-lady",
            kind = "gossip",
            priority = 28,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Talk to Lady Katrana Prestor. 'Pardon the intrusion, Lady Prestor, but Highlord Bolvar suggested that I seek your advice.' Receive Advice From Lady Prestor.",
            dependsOn = { "accept-4185-the-true-masters" },
            complete = QuestState(4185, "complete"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.781, 0.177, "Stormwind City", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4185-the-true-masters",
            kind = "turnin",
            priority = 29,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Highlord Bolvar Fordragon.",
            dependsOn = { "objective-4185-1-receive-advice-from-lady" },
            complete = QuestState(4185, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-4186-the-true-masters",
            kind = "accept",
            priority = 30,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Highlord Bolvar Fordragon.",
            dependsOn = { "turnin-4185-the-true-masters" },
            complete = QuestState(4186, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4186-the-true-masters",
            kind = "turnin",
            priority = 31,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Magistrate Solomon.",
            dependsOn = { "accept-4186-the-true-masters" },
            complete = QuestState(4186, "completed"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "accept-4223-the-true-masters",
            kind = "accept",
            priority = 32,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Magistrate Solomon.",
            dependsOn = { "turnin-4186-the-true-masters" },
            complete = QuestState(4223, "activeOrCompleted"),
            route = {
                Point(MAP.REDRIDGE_MOUNTAINS, 0.300, 0.445, "Magistrate Solomon", "Travel to Redridge Mountains."),
            },
        },
        {
            id = "turnin-4223-the-true-masters",
            kind = "turnin",
            priority = 33,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Marshal Maxwell.",
            dependsOn = { "accept-4223-the-true-masters" },
            complete = QuestState(4223, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4224-the-true-masters",
            kind = "accept",
            priority = 34,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept The True Masters from Marshal Maxwell.",
            dependsOn = { "turnin-4223-the-true-masters" },
            complete = QuestState(4224, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "objective-4224-1-hear-ragged-john-s-story",
            kind = "gossip",
            priority = 35,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Talk to Ragged John. 'Official business, John. I need some information about Marshal Windsor. Tell me about the last time you saw him.' Hear Ragged John's Story.",
            dependsOn = { "accept-4224-the-true-masters" },
            complete = QuestState(4224, "complete"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.650, 0.238, "Burning Steppes", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4224-the-true-masters",
            kind = "turnin",
            priority = 36,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in The True Masters to Marshal Maxwell.",
            dependsOn = { "objective-4224-1-hear-ragged-john-s-story" },
            complete = QuestState(4224, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4241-marshal-windsor",
            kind = "accept",
            priority = 37,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Marshal Windsor from Marshal Maxwell.",
            dependsOn = { "turnin-4224-the-true-masters" },
            complete = QuestState(4241, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 38,
            conditions = { level = { min = 57 } },
            text = "Enter Blackrock Depths with your group.",
            dependsOn = { "accept-4766-mayara-brightwing", "accept-4764-doomrigger-s-clasp", "accept-4726-broodling-essence", "accept-4182-dragonkin-menace", "accept-4183-the-true-masters", "accept-4184-the-true-masters", "accept-4185-the-true-masters", "accept-4186-the-true-masters", "accept-4223-the-true-masters", "accept-4224-the-true-masters", "accept-4241-marshal-windsor" },
            persistCompletion = true,
            complete = { instance = 229 },
            route = {
                Point(MAP.SEARING_GORGE, 0.372, 0.944, "Upper Blackrock Spire entrance", "Travel to Searing Gorge."),
            },
        },
        {
            id = "boss-high-interrogator-gerstahn",
            kind = "note",
            priority = 39,
            conditions = { level = { min = 57 } },
            text = "Kill High Interrogator Gerstahn. After entering the dungeon, go straight into the Detention Block and then take the first right. Follow this path around until you can go left into a room at the back of this long hallway. You need this key to unlock Marshal Windsor's cell door.",
            dependsOn = { "enter-dungeon" },
        },
        {
            id = "turnin-4241-marshal-windsor",
            kind = "turnin",
            priority = 40,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Marshal Windsor to Marshal Windsor.",
            dependsOn = { "accept-4241-marshal-windsor" },
            complete = QuestState(4241, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4242-abandoned-hope",
            kind = "accept",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Abandoned Hope from Marshal Windsor.",
            dependsOn = { "turnin-4241-marshal-windsor" },
            complete = QuestState(4242, "activeOrCompleted"),
        },
        {
            id = "note-leave-the-dungeon",
            kind = "note",
            priority = 42,
            conditions = { level = { min = 57 } },
            text = "Leave the dungeon.",
        },
        {
            id = "note-click-here-to-continue",
            kind = "note",
            priority = 43,
            conditions = { level = { min = 57 } },
            text = "Click Here to Continue.",
        },
        {
            id = "turnin-4242-abandoned-hope",
            kind = "turnin",
            priority = 44,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Abandoned Hope to Marshal Maxwell.",
            dependsOn = { "accept-4242-abandoned-hope" },
            complete = QuestState(4242, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "boss-anvilrage-dwarves-at-the-beginning-of-the",
            kind = "note",
            priority = 45,
            conditions = { level = { min = 57 } },
            text = "Kill Anvilrage dwarves at the beginning of the dungeon. Just clear the first few rooms of the dungeon, killing all the Anvilrage dwarves and resetting the instance if needed, until you get the item drop.",
            dependsOn = { "boss-high-interrogator-gerstahn" },
        },
        {
            id = "accept-4264-a-crumpled-up-note",
            kind = "accept",
            priority = 46,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept A Crumpled Up Note.",
            complete = QuestState(4264, "activeOrCompleted"),
        },
        {
            id = "turnin-4264-a-crumpled-up-note",
            kind = "turnin",
            priority = 47,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in A Crumpled Up Note to Marshal Windsor.",
            dependsOn = { "accept-4264-a-crumpled-up-note" },
            complete = QuestState(4264, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4282-a-shred-of-hope",
            kind = "accept",
            priority = 48,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept A Shred of Hope from Marshal Windsor.",
            dependsOn = { "turnin-4264-a-crumpled-up-note" },
            complete = QuestState(4282, "activeOrCompleted"),
        },
        {
            id = "boss-general-angerforge",
            kind = "note",
            priority = 49,
            conditions = { level = { min = 57 } },
            text = "Kill General Angerforge. Run north through the Detention Block and unlock the East Garrison Door to enter the East Garrison. In the lower part of this room, click the Shadowforge Lock. run up the two sets of stairs and follow the hallway on the left just before the third set of. Follow the path through the hallway to reach the West Garrison.",
            dependsOn = { "boss-anvilrage-dwarves-at-the-beginning-of-the" },
        },
        {
            id = "objective-4282-1-marshal-windsor-s-lost-i",
            kind = "objective",
            priority = 50,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect Marshal Windsor's Lost Information.",
            dependsOn = { "accept-4282-a-shred-of-hope" },
            complete = QuestObjective(4282, 1, "Marshal Windsor's Lost Information"),
            useClientPin = true,
        },
        {
            id = "boss-golem-lord-argelmach",
            kind = "note",
            priority = 51,
            conditions = { level = { min = 57 } },
            text = "Kill Golem Lord Argelmach. Go back up the stairs next to General Angerforge and continue north to reach The Manufactory and Golem Lord Argelmach.",
            dependsOn = { "boss-general-angerforge" },
        },
        {
            id = "objective-4282-2-marshal-windsor-s-lost-i",
            kind = "objective",
            priority = 52,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Collect Marshal Windsor's Lost Information.",
            dependsOn = { "accept-4282-a-shred-of-hope" },
            complete = QuestObjective(4282, 2, "Marshal Windsor's Lost Information"),
            useClientPin = true,
        },
        {
            id = "turnin-4282-a-shred-of-hope",
            kind = "turnin",
            priority = 53,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in A Shred of Hope to Marshal Windsor.",
            dependsOn = { "objective-4282-1-marshal-windsor-s-lost-i", "objective-4282-2-marshal-windsor-s-lost-i" },
            complete = QuestState(4282, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-4322-jail-break",
            kind = "accept",
            priority = 54,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Jail Break! from Marshal Windsor.",
            dependsOn = { "turnin-4282-a-shred-of-hope" },
            complete = QuestState(4322, "activeOrCompleted"),
        },
        {
            id = "objective-4322-1-protect-marshal-windor-d",
            kind = "objective",
            priority = 55,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Protect Marshal Windor During your Escape.",
            dependsOn = { "accept-4322-jail-break" },
            complete = QuestState(4322, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4322-jail-break",
            kind = "turnin",
            priority = 56,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Jail Break! to Marshal Maxwell.",
            dependsOn = { "objective-4322-1-protect-marshal-windor-d" },
            complete = QuestState(4322, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-6402-stormwind-rendezvous",
            kind = "accept",
            priority = 57,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Stormwind Rendezvous from Marshal Maxwell.",
            dependsOn = { "turnin-4322-jail-break" },
            complete = QuestState(6402, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-6402-stormwind-rendezvous",
            kind = "turnin",
            priority = 58,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Stormwind Rendezvous to Reginald Windsor.",
            dependsOn = { "accept-6402-stormwind-rendezvous" },
            complete = QuestState(6402, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.705, 0.851, "Reginald Windsor", "Travel to Stormwind City."),
                Point(MAP.STORMWIND_CITY, 0.697, 0.861, "Reginald Windsor", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-6403-the-great-masquerade",
            kind = "accept",
            priority = 59,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Great Masquerade from Reginald Windsor.",
            dependsOn = { "turnin-6402-stormwind-rendezvous" },
            complete = QuestState(6403, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.697, 0.861, "Reginald Windsor", "Travel to Stormwind City."),
            },
        },
        {
            id = "boss-onyxia-s-elite-guard",
            kind = "note",
            priority = 60,
            conditions = { level = { min = 57 } },
            text = "Kill Onyxia's Elite Guard+. Inside the building.",
            dependsOn = { "boss-golem-lord-argelmach" },
        },
        {
            id = "objective-6403-1-complete-reginald-windso",
            kind = "objective",
            priority = 61,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Complete Reginald Windsor's March.",
            dependsOn = { "accept-6403-the-great-masquerade" },
            complete = QuestState(6403, "complete"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.781, 0.179, "Stormwind City", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-6403-the-great-masquerade",
            kind = "turnin",
            priority = 62,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Great Masquerade to Highlord Bolvar Fordragon.",
            dependsOn = { "objective-6403-1-complete-reginald-windso" },
            complete = QuestState(6403, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-6501-the-dragon-s-eye",
            kind = "accept",
            priority = 63,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept The Dragon's Eye from Highlord Bolvar Fordragon.",
            dependsOn = { "turnin-6403-the-great-masquerade" },
            complete = QuestState(6501, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.782, 0.180, "Highlord Bolvar Fordragon", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4726-broodling-essence",
            kind = "turnin",
            priority = 64,
            conditions = { level = { min = 50 } },
            text = "Turn in Broodling Essence to Tinkee Steamboil.",
            dependsOn = { "objective-4726-1-broodling-essence" },
            complete = QuestState(4726, "completed"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.652, 0.240, "Tinkee Steamboil", "Travel to Stormwind City."),
            },
        },
        {
            id = "accept-4808-felnok-steelspring",
            kind = "accept",
            priority = 65,
            conditions = { level = { min = 50 } },
            text = "Accept Felnok Steelspring from Tinkee Steamboil.",
            dependsOn = { "turnin-4726-broodling-essence" },
            complete = QuestState(4808, "activeOrCompleted"),
            route = {
                Point(MAP.STORMWIND_CITY, 0.652, 0.240, "Tinkee Steamboil", "Travel to Stormwind City."),
            },
        },
        {
            id = "turnin-4808-felnok-steelspring",
            kind = "turnin",
            priority = 66,
            conditions = { level = { min = 50 } },
            text = "Turn in Felnok Steelspring to Felnok Steelspring.",
            dependsOn = { "accept-4808-felnok-steelspring" },
            complete = QuestState(4808, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-4809-chillwind-horns",
            kind = "accept",
            priority = 67,
            conditions = { level = { min = 50 } },
            text = "Accept Chillwind Horns from Felnok Steelspring.",
            dependsOn = { "turnin-4808-felnok-steelspring" },
            complete = QuestState(4809, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "boss-chillwind-ravager",
            kind = "note",
            priority = 68,
            conditions = { level = { min = 57 } },
            text = "Kill Chillwind Ravager+. They look like chimeras. They share spawn points with the bears, so kill them too.",
            dependsOn = { "boss-onyxia-s-elite-guard" },
        },
        {
            id = "objective-4809-1-uncracked-chillwind-horn",
            kind = "objective",
            priority = 69,
            conditions = { level = { min = 50 } },
            text = "Collect 8 Uncracked Chillwind Horn.",
            dependsOn = { "accept-4809-chillwind-horns" },
            complete = QuestState(4809, "complete"),
            route = {
                Point(MAP.WINTERSPRING, 0.600, 0.215, "Winterspring", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-4809-chillwind-horns",
            kind = "turnin",
            priority = 70,
            conditions = { level = { min = 50 } },
            text = "Turn in Chillwind Horns to Felnok Steelspring.",
            dependsOn = { "objective-4809-1-uncracked-chillwind-horn" },
            complete = QuestState(4809, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-4810-return-to-tinkee",
            kind = "accept",
            priority = 71,
            conditions = { level = { min = 50 } },
            text = "Accept Return to Tinkee from Felnok Steelspring.",
            dependsOn = { "turnin-4809-chillwind-horns" },
            complete = QuestState(4810, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-6501-the-dragon-s-eye",
            kind = "turnin",
            priority = 72,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in The Dragon's Eye to Haleh.",
            dependsOn = { "accept-6501-the-dragon-s-eye" },
            complete = QuestState(6501, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-6502-drakefire-amulet",
            kind = "accept",
            priority = 73,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Accept Drakefire Amulet from Haleh.",
            dependsOn = { "turnin-6501-the-dragon-s-eye" },
            complete = QuestState(6502, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-4810-return-to-tinkee",
            kind = "turnin",
            priority = 74,
            conditions = { level = { min = 50 } },
            text = "Turn in Return to Tinkee to Tinkee Steamboil.",
            dependsOn = { "accept-4810-return-to-tinkee" },
            complete = QuestState(4810, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4907-tinkee-steamboil",
            kind = "accept",
            priority = 75,
            conditions = { level = { min = 57 } },
            text = "Accept Tinkee Steamboil from Felnok Steelspring.",
            complete = QuestState(4907, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.616, 0.386, "Felnok Steelspring", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-4907-tinkee-steamboil",
            kind = "turnin",
            priority = 76,
            conditions = { level = { min = 57 } },
            text = "Turn in Tinkee Steamboil to Tinkee Steamboil.",
            dependsOn = { "accept-4907-tinkee-steamboil" },
            complete = QuestState(4907, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4734-egg-freezing",
            kind = "accept",
            priority = 77,
            conditions = { level = { min = 57 } },
            text = "Accept Egg Freezing from Tinkee Steamboil.",
            dependsOn = { "turnin-4907-tinkee-steamboil" },
            complete = QuestState(4734, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-6804-poisoned-water",
            kind = "accept",
            priority = 78,
            conditions = { level = { min = 55 } },
            text = "Accept Poisoned Water from Duke Hydraxis.",
            complete = QuestState(6804, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.793, 0.737, "Duke Hydraxis", "Travel to Azshara."),
            },
        },
        {
            id = "accept-6805-stormers-and-rumblers",
            kind = "accept",
            priority = 79,
            conditions = { level = { min = 55 } },
            text = "Accept Stormers and Rumblers from Duke Hydraxis.",
            complete = QuestState(6805, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.793, 0.737, "Duke Hydraxis", "Travel to Azshara."),
            },
        },
        {
            id = "objective-6805-1-dust-stormer",
            kind = "objective",
            priority = 80,
            conditions = { level = { min = 55 } },
            text = "Kill 15 Dust Stormer.",
            dependsOn = { "accept-6805-stormers-and-rumblers" },
            complete = QuestObjective(6805, 1, "Dust Stormer"),
            route = {
                Point(MAP.SILITHUS, 0.198, 0.222, "Silithus", "Travel to Silithus."),
            },
        },
        {
            id = "objective-6805-2-desert-rumbler",
            kind = "objective",
            priority = 81,
            conditions = { level = { min = 55 } },
            text = "Kill 15 Desert Rumbler.",
            dependsOn = { "accept-6805-stormers-and-rumblers" },
            complete = QuestObjective(6805, 2, "Desert Rumbler"),
            route = {
                Point(MAP.SILITHUS, 0.198, 0.222, "Silithus", "Travel to Silithus."),
            },
        },
        {
            id = "boss-discordant-surge",
            kind = "note",
            priority = 82,
            conditions = { level = { min = 57 } },
            text = "Kill Discordant Surge+. Use it on Plague Ravagers and Blighted Surge around this area.",
            dependsOn = { "boss-chillwind-ravager" },
        },
        {
            id = "objective-6804-1-discordant-bracers",
            kind = "objective",
            priority = 83,
            conditions = { level = { min = 55 } },
            text = "Collect 12 Discordant Bracers.",
            dependsOn = { "accept-6804-poisoned-water" },
            complete = QuestState(6804, "complete"),
            route = {
                Point(MAP.EASTERN_PLAGUELANDS, 0.626, 0.794, "Eastern Plaguelands", "Travel to Eastern Plaguelands."),
            },
        },
        {
            id = "turnin-6804-poisoned-water",
            kind = "turnin",
            priority = 84,
            conditions = { level = { min = 55 } },
            text = "Turn in Poisoned Water to Duke Hydraxis.",
            dependsOn = { "objective-6804-1-discordant-bracers" },
            complete = QuestState(6804, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.793, 0.737, "Duke Hydraxis", "Travel to Azshara."),
            },
        },
        {
            id = "turnin-6805-stormers-and-rumblers",
            kind = "turnin",
            priority = 85,
            conditions = { level = { min = 55 } },
            text = "Turn in Stormers and Rumblers to Duke Hydraxis.",
            dependsOn = { "objective-6805-1-dust-stormer", "objective-6805-2-desert-rumbler" },
            complete = QuestState(6805, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.793, 0.737, "Duke Hydraxis", "Travel to Azshara."),
            },
        },
        {
            id = "accept-6821-eye-of-the-emberseer",
            kind = "accept",
            priority = 86,
            conditions = { level = { min = 55 } },
            text = "Accept Eye of the Emberseer from Duke Hydraxis.",
            dependsOn = { "turnin-6805-stormers-and-rumblers" },
            complete = QuestState(6821, "activeOrCompleted"),
            route = {
                Point(MAP.AZSHARA, 0.793, 0.737, "Duke Hydraxis", "Travel to Azshara."),
            },
        },
        {
            id = "boss-overlord-wyrmthalak",
            kind = "note",
            priority = 87,
            conditions = { level = { min = 57 } },
            text = "Kill Overlord Wyrmthalak. After entering the dungeon, follow the path right in the Hall of Blackhand to reach Hordemar City. Proceed across the bridges through Hordemar City and jump down into the groove in the ground where Bijou is. Jump down to the west from Bijou and follow the path west around Hordemar City, eventually heading south to reach the Skitterweb Tunnels.",
            dependsOn = { "boss-discordant-surge" },
        },
        {
            id = "accept-5089-general-drakkisath-s-command",
            kind = "accept",
            priority = 88,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept General Drakkisath's Command.",
            complete = QuestState(5089, "activeOrCompleted"),
        },
        {
            id = "turnin-5089-general-drakkisath-s-command",
            kind = "turnin",
            priority = 89,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in General Drakkisath's Command to Marshal Maxwell.",
            dependsOn = { "accept-5089-general-drakkisath-s-command" },
            complete = QuestState(5089, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-5102-general-drakkisath-s-demise",
            kind = "accept",
            priority = 90,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Accept General Drakkisath's Demise from Marshal Maxwell.",
            dependsOn = { "turnin-5089-general-drakkisath-s-command" },
            complete = QuestState(5102, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "boss-pyroguard-emberseer",
            kind = "note",
            priority = 91,
            conditions = { level = { min = 57 } },
            text = "Kill Pyroguard Emberseer. After entering the dungeon, follow the path to the left to enter the Upper Blackrock Spire. Someone in your group must have the Seal of Ascension in order to open the door. Clear the enemies in the first room to unlock the door to the next room. This will start the fight. The Tank should keep him away from the group. Melee will need extra heals during the encounter from its AoE attacks.",
            dependsOn = { "boss-overlord-wyrmthalak" },
        },
        {
            id = "objective-6821-1-eye-of-the-emberseer",
            kind = "objective",
            priority = 92,
            conditions = { level = { min = 55 } },
            text = "Collect Eye of the Emberseer.",
            dependsOn = { "accept-6821-eye-of-the-emberseer" },
            complete = QuestState(6821, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-4734-1-test-the-eggscilloscope",
            kind = "objective",
            priority = 93,
            conditions = { level = { min = 57 } },
            text = "Test the Eggscilloscope Prototype.",
            dependsOn = { "accept-4734-egg-freezing" },
            complete = QuestState(4734, "complete"),
            useClientPin = true,
        },
        {
            id = "note-click-doomrigger-s-coffer",
            kind = "note",
            priority = 94,
            conditions = { level = { min = 57 } },
            text = "Click Doomrigger's Coffer.",
        },
        {
            id = "objective-4764-1-doomrigger-s-clasp",
            kind = "objective",
            priority = 95,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Collect Doomrigger's Clasp.",
            dependsOn = { "accept-4764-doomrigger-s-clasp" },
            complete = QuestState(4764, "complete"),
            useClientPin = true,
        },
        {
            id = "accept-5160-the-matron-protectorate",
            kind = "accept",
            priority = 96,
            conditions = { level = { min = 57 } },
            text = "Accept The Matron Protectorate from Awbee.",
            complete = QuestState(5160, "activeOrCompleted"),
        },
        {
            id = "boss-the-beast",
            kind = "note",
            priority = 97,
            conditions = { level = { min = 57 } },
            text = "Kill The Beast if the rare is up. Head east up the stairs from Awbee and go right into The Furnace, followed by a left to reach The Beast. This is a rare drop and may take multiple attempts to get. If you don't have Skinning or you don't want to do this you can skip this step but you will have to skip the next quest. It's 'Berserker Charge' ability targets the player with the most aggro. The tanks must ensure that they have the highest aggro at all times. All ranged should stand at max range to avoid its 'Fear' ability.",
            dependsOn = { "boss-pyroguard-emberseer" },
        },
        {
            id = "accept-5047-finkle-einhorn-at-your-service",
            kind = "accept",
            priority = 98,
            conditions = { level = { min = 57 } },
            text = "Accept Finkle Einhorn, At Your Service! from Finkle Einhorn. 'How the hell did you get in there to begin with?'.",
            complete = QuestState(5047, "activeOrCompleted"),
        },
        {
            id = "turnin-4734-egg-freezing",
            kind = "turnin",
            priority = 99,
            conditions = { level = { min = 57 } },
            text = "Turn in Egg Freezing to Tinkee Steamboil.",
            dependsOn = { "objective-4734-1-test-the-eggscilloscope" },
            complete = QuestState(4734, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4735-egg-collection",
            kind = "accept",
            priority = 100,
            conditions = { level = { min = 57 } },
            text = "Accept Egg Collection from Tinkee Steamboil.",
            dependsOn = { "turnin-4734-egg-freezing" },
            complete = QuestState(4735, "activeOrCompleted"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-4764-doomrigger-s-clasp",
            kind = "turnin",
            priority = 101,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 57 } } } },
            text = "Turn in Doomrigger's Clasp to Mayara Brightwing.",
            dependsOn = { "objective-4764-1-doomrigger-s-clasp" },
            complete = QuestState(4764, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.691, "Mayara Brightwing", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-5102-general-drakkisath-s-demise",
            kind = "turnin",
            priority = 102,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 55 } } } },
            text = "Turn in General Drakkisath's Demise to Marshal Maxwell.",
            dependsOn = { "accept-5102-general-drakkisath-s-demise" },
            complete = QuestState(5102, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.848, 0.690, "Marshal Maxwell", "Travel to Burning Steppes."),
            },
        },
        {
            id = "turnin-5047-finkle-einhorn-at-your-service",
            kind = "turnin",
            priority = 103,
            conditions = { level = { min = 57 } },
            text = "Turn in Finkle Einhorn, At Your Service! to Malyfous Darkhammer.",
            dependsOn = { "accept-5047-finkle-einhorn-at-your-service" },
            complete = QuestState(5047, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.610, 0.388, "Malyfous Darkhammer", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-6502-drakefire-amulet",
            kind = "turnin",
            priority = 104,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 50 } } } },
            text = "Turn in Drakefire Amulet to Haleh.",
            dependsOn = { "accept-6502-drakefire-amulet" },
            complete = QuestState(6502, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-5162-wrath-of-the-blue-flight",
            kind = "turnin",
            priority = 105,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Turn in Wrath of the Blue Flight to Jeziba.",
            dependsOn = { "accept-5162-wrath-of-the-blue-flight" },
            complete = QuestState(5162, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.394, 0.668, "Jeziba", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-5164-catalogue-of-the-wayward",
            kind = "accept",
            priority = 106,
            conditions = { level = { min = 57 } },
            text = "Accept Catalogue of the Wayward from Jeziba.",
            dependsOn = { "turnin-5162-wrath-of-the-blue-flight" },
            complete = QuestState(5164, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.394, 0.668, "Jeziba", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "note-click-catalogue-of-the-wayward",
            kind = "note",
            priority = 107,
            conditions = { level = { min = 57 } },
            text = "Click Catalogue of the Wayward.",
        },
        {
            id = "turnin-5164-catalogue-of-the-wayward",
            kind = "turnin",
            priority = 108,
            conditions = { level = { min = 57 } },
            text = "Turn in Catalogue of the Wayward.",
            dependsOn = { "accept-5164-catalogue-of-the-wayward" },
            complete = QuestState(5164, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.394, 0.666, "Western Plaguelands", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-6821-eye-of-the-emberseer",
            kind = "turnin",
            priority = 109,
            conditions = { level = { min = 55 } },
            text = "Turn in Eye of the Emberseer to Duke Hydraxis.",
            dependsOn = { "objective-6821-1-eye-of-the-emberseer" },
            complete = QuestState(6821, "completed"),
            route = {
                Point(MAP.AZSHARA, 0.793, 0.737, "Duke Hydraxis", "Travel to Azshara."),
            },
        },
        {
            id = "objective-4735-1-collected-dragon-egg",
            kind = "objective",
            priority = 110,
            conditions = { level = { min = 57 } },
            text = "Collect 8 Collected Dragon Egg.",
            dependsOn = { "accept-4735-egg-collection" },
            complete = QuestState(4735, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4735-egg-collection",
            kind = "turnin",
            priority = 111,
            conditions = { level = { min = 57 } },
            text = "Turn in Egg Collection to Tinkee Steamboil.",
            dependsOn = { "objective-4735-1-collected-dragon-egg" },
            complete = QuestState(4735, "completed"),
            route = {
                Point(MAP.BURNING_STEPPES, 0.652, 0.240, "Tinkee Steamboil", "Travel to Burning Steppes."),
            },
        },
        {
            id = "accept-4769-vivian-lagrave-and-the-darkstone-tablet",
            kind = "accept",
            priority = 112,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Accept Vivian Lagrave and the Darkstone Tablet from Apothecary Zinge.",
            complete = QuestState(4769, "activeOrCompleted"),
            route = {
                Point(MAP.UNDERCITY, 0.501, 0.680, "Apothecary Zinge", "Travel to Undercity."),
            },
        },
        {
            id = "turnin-4769-vivian-lagrave-and-the-darkstone-tablet",
            kind = "turnin",
            priority = 113,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Turn in Vivian Lagrave and the Darkstone Tablet to Shadowmage Vivian Lagrave.",
            dependsOn = { "accept-4769-vivian-lagrave-and-the-darkstone-tablet" },
            complete = QuestState(4769, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.029, 0.477, "Shadowmage Vivian Lagrave", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4768-the-darkstone-tablet",
            kind = "accept",
            priority = 114,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Accept The Darkstone Tablet from Shadowmage Vivian Lagrave.",
            dependsOn = { "turnin-4769-vivian-lagrave-and-the-darkstone-tablet" },
            complete = QuestState(4768, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.029, 0.477, "Shadowmage Vivian Lagrave", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4903-warlord-s-command",
            kind = "accept",
            priority = 115,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Warlord's Command from Warlord Goretooth.",
            complete = QuestState(4903, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "objective-4903-2-highlord-omokk",
            kind = "objective",
            priority = 116,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Highlord Omokk.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 2, "Highlord Omokk"),
            useClientPin = true,
        },
        {
            id = "objective-4903-3-war-master-voone",
            kind = "objective",
            priority = 117,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill War Master Voone.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 3, "War Master Voone"),
            useClientPin = true,
        },
        {
            id = "objective-4903-1-overlord-wyrmthalak",
            kind = "objective",
            priority = 118,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Kill Overlord Wyrmthalak.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 1, "Overlord Wyrmthalak"),
            useClientPin = true,
        },
        {
            id = "note-click-inconspicuous-documents",
            kind = "note",
            priority = 119,
            conditions = { level = { min = 57 } },
            text = "Click Inconspicuous Documents.",
        },
        {
            id = "objective-4903-4-important-blackrock-docu",
            kind = "objective",
            priority = 120,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Important Blackrock Documents.",
            dependsOn = { "accept-4903-warlord-s-command" },
            complete = QuestObjective(4903, 4, "Important Blackrock Documents"),
            useClientPin = true,
        },
        {
            id = "turnin-4903-warlord-s-command",
            kind = "turnin",
            priority = 121,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Warlord's Command to Warlord Goretooth.",
            dependsOn = { "objective-4903-2-highlord-omokk", "objective-4903-3-war-master-voone", "objective-4903-1-overlord-wyrmthalak", "objective-4903-4-important-blackrock-docu" },
            complete = QuestState(4903, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "accept-4941-eitrigg-s-wisdom",
            kind = "accept",
            priority = 122,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Eitrigg's Wisdom from Warlord Goretooth.",
            dependsOn = { "turnin-4903-warlord-s-command" },
            complete = QuestState(4941, "activeOrCompleted"),
            route = {
                Point(MAP.BADLANDS, 0.058, 0.475, "Warlord Goretooth", "Travel to Badlands."),
            },
        },
        {
            id = "note-click-darkstone-tablet",
            kind = "note",
            priority = 123,
            conditions = { level = { min = 57 } },
            text = "Click Darkstone Tablet.",
        },
        {
            id = "objective-4768-1-darkstone-tablet",
            kind = "objective",
            priority = 124,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Collect Darkstone Tablet.",
            dependsOn = { "accept-4768-the-darkstone-tablet" },
            complete = QuestState(4768, "complete"),
            useClientPin = true,
        },
        {
            id = "boss-gyth",
            kind = "note",
            priority = 125,
            conditions = { level = { min = 57 } },
            text = "Kill Gyth. They will spawn after clearing the gauntlet of orcs and dragon spawn. Focus on Flame Tongues, Dragonguard, Dragon Spawn, Chromatic Dragonspawn, Chromatic Whelps then Blackhand Orcs in that order. When Gyth appears, the tank should face it away from the group.",
            dependsOn = { "boss-the-beast" },
        },
        {
            id = "turnin-4768-the-darkstone-tablet",
            kind = "turnin",
            priority = 126,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Turn in The Darkstone Tablet to Shadowmage Vivian Lagrave.",
            dependsOn = { "objective-4768-1-darkstone-tablet" },
            complete = QuestState(4768, "completed"),
            route = {
                Point(MAP.BADLANDS, 0.029, 0.477, "Shadowmage Vivian Lagrave", "Travel to Badlands."),
            },
        },
        {
            id = "objective-4941-1-council-with-eitrigg",
            kind = "gossip",
            priority = 127,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Talk to Eitrigg. 'Hello, Eitrigg. I bring news back from Blackrock Spire.' Council with Eitrigg.",
            dependsOn = { "accept-4941-eitrigg-s-wisdom" },
            complete = QuestState(4941, "complete"),
            route = {
                Point(MAP.ORGRIMMAR, 0.343, 0.394, "Orgrimmar", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-4941-eitrigg-s-wisdom",
            kind = "turnin",
            priority = 128,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Eitrigg's Wisdom to Thrall.",
            dependsOn = { "objective-4941-1-council-with-eitrigg" },
            complete = QuestState(4941, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-4974-for-the-horde",
            kind = "accept",
            priority = 129,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept For The Horde! from Thrall.",
            dependsOn = { "turnin-4941-eitrigg-s-wisdom" },
            complete = QuestState(4974, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-5160-the-matron-protectorate",
            kind = "turnin",
            priority = 130,
            conditions = { level = { min = 57 } },
            text = "Turn in The Matron Protectorate to Haleh.",
            dependsOn = { "accept-5160-the-matron-protectorate" },
            complete = QuestState(5160, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-5161-wrath-of-the-blue-flight",
            kind = "accept",
            priority = 131,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Accept Wrath of the Blue Flight from Haleh.",
            dependsOn = { "turnin-5160-the-matron-protectorate" },
            complete = QuestState(5161, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "turnin-5161-wrath-of-the-blue-flight",
            kind = "turnin",
            priority = 132,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Turn in Wrath of the Blue Flight to Haleh.",
            dependsOn = { "accept-5161-wrath-of-the-blue-flight" },
            complete = QuestState(5161, "completed"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "accept-5162-wrath-of-the-blue-flight",
            kind = "accept",
            priority = 133,
            conditions = { all = { { faction = "Horde" }, { level = { min = 57 } } } },
            text = "Accept Wrath of the Blue Flight from Haleh.",
            dependsOn = { "turnin-5161-wrath-of-the-blue-flight" },
            complete = QuestState(5162, "activeOrCompleted"),
            route = {
                Point(MAP.WINTERSPRING, 0.545, 0.512, "Haleh", "Travel to Winterspring."),
            },
        },
        {
            id = "boss-solakar-flamewreath",
            kind = "note",
            priority = 134,
            conditions = { level = { min = 57 } },
            text = "Kill Solakar Flamewreath. Clear all dragon spawn before starting the event. Click on father flame and take the item to start the event. DPS need to focus down 'Rookery Hatchers' as quickly as possible.",
            dependsOn = { "boss-gyth" },
        },
        {
            id = "boss-jed-runewatcher",
            kind = "note",
            priority = 135,
            conditions = { level = { min = 57 } },
            text = "Kill Jed Runewatcher if the rare is up. This is a rare mob that may not be available. The tank should have their back to the wall. All ranged should be at max distance as well.",
            dependsOn = { "boss-solakar-flamewreath" },
        },
        {
            id = "boss-goraluk-anvilcrack",
            kind = "note",
            priority = 136,
            conditions = { level = { min = 57 } },
            text = "Kill Goraluk Anvilcrack. The tank should have their back to the wall. All ranged should be at max distance as well.",
            dependsOn = { "boss-jed-runewatcher" },
        },
        {
            id = "boss-warchief-rend-blackhand",
            kind = "note",
            priority = 137,
            conditions = { level = { min = 57 } },
            text = "Kill Warchief Rend Blackhand. Proceed through the upper level of The Rookery to reach the Hall of Blackhand. Go east in the Hall of Blackhand and jump down into the Blackrock Stadium to start the encounter. Kill the enemies that attack. finally Gyth and Warchief Rend Blackhand. They will spawn after clearing the gauntlet of orcs and dragon spawn. Focus on Flame Tongues, Dragonguard, Dragon Spawn, Chromatic Dragonspawn, Chromatic Whelps then Blackhand Orcs in that order. When Gyth appears, the tank should face it away from the group.",
            dependsOn = { "boss-goraluk-anvilcrack" },
        },
        {
            id = "objective-4974-1-head-of-rend-blackhand",
            kind = "objective",
            priority = 138,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Head of Rend Blackhand.",
            dependsOn = { "accept-4974-for-the-horde" },
            complete = QuestState(4974, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-4974-for-the-horde",
            kind = "turnin",
            priority = 139,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in For The Horde! to Thrall.",
            dependsOn = { "objective-4974-1-head-of-rend-blackhand" },
            complete = QuestState(4974, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-6566-what-the-wind-carries",
            kind = "accept",
            priority = 140,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept What the Wind Carries from Thrall.",
            dependsOn = { "turnin-4974-for-the-horde" },
            complete = QuestState(6566, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "objective-6566-1-listen-to-thrall-s-tale",
            kind = "gossip",
            priority = 141,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Talk to Thrall. 'Please share your wisdom with me, Warchief.' Listen to Thrall's Tale.",
            dependsOn = { "accept-6566-what-the-wind-carries" },
            complete = QuestState(6566, "complete"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Orgrimmar", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-6566-what-the-wind-carries",
            kind = "turnin",
            priority = 142,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in What the Wind Carries to Thrall.",
            dependsOn = { "objective-6566-1-listen-to-thrall-s-tale" },
            complete = QuestState(6566, "completed"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "accept-6567-the-champion-of-the-horde",
            kind = "accept",
            priority = 143,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Champion of the Horde from Thrall.",
            dependsOn = { "turnin-6566-what-the-wind-carries" },
            complete = QuestState(6567, "activeOrCompleted"),
            route = {
                Point(MAP.ORGRIMMAR, 0.317, 0.378, "Thrall", "Travel to Orgrimmar."),
            },
        },
        {
            id = "turnin-6567-the-champion-of-the-horde",
            kind = "turnin",
            priority = 144,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Champion of the Horde to Rexxar.",
            dependsOn = { "accept-6567-the-champion-of-the-horde" },
            complete = QuestState(6567, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-6568-the-testament-of-rexxar",
            kind = "accept",
            priority = 145,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Testament of Rexxar from Rexxar.",
            complete = QuestState(6568, "activeOrCompleted"),
        },
        {
            id = "turnin-6568-the-testament-of-rexxar",
            kind = "turnin",
            priority = 146,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Testament of Rexxar to Myranda the Hag.",
            dependsOn = { "accept-6568-the-testament-of-rexxar" },
            complete = QuestState(6568, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.508, 0.778, "Myranda the Hag", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-6569-oculus-illusions",
            kind = "accept",
            priority = 147,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Oculus Illusions from Myranda the Hag.",
            dependsOn = { "turnin-6568-the-testament-of-rexxar" },
            complete = QuestState(6569, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.508, 0.778, "Myranda the Hag", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "boss-rage-talon-enemies-throughout-the-dungeon",
            kind = "note",
            priority = 148,
            conditions = { level = { min = 57 } },
            text = "Kill Rage Talon enemies throughout the dungeon. There's a few at the very beginning of the dungeon and a lot more in The Rookery.",
            dependsOn = { "boss-warchief-rend-blackhand" },
        },
        {
            id = "objective-6569-1-black-dragonspawn-eye",
            kind = "objective",
            priority = 149,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect 20 Black Dragonspawn Eye.",
            dependsOn = { "accept-6569-oculus-illusions" },
            complete = QuestState(6569, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-6569-oculus-illusions",
            kind = "turnin",
            priority = 150,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Oculus Illusions to Myranda the Hag.",
            dependsOn = { "objective-6569-1-black-dragonspawn-eye" },
            complete = QuestState(6569, "completed"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.508, 0.778, "Myranda the Hag", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "accept-6570-emberstrife",
            kind = "accept",
            priority = 151,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Emberstrife from Myranda the Hag.",
            dependsOn = { "turnin-6569-oculus-illusions" },
            complete = QuestState(6570, "activeOrCompleted"),
            route = {
                Point(MAP.WESTERN_PLAGUELANDS, 0.508, 0.778, "Myranda the Hag", "Travel to Western Plaguelands."),
            },
        },
        {
            id = "turnin-6570-emberstrife",
            kind = "turnin",
            priority = 152,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Emberstrife to Emberstrife.",
            dependsOn = { "accept-6570-emberstrife" },
            complete = QuestState(6570, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6582-the-test-of-skulls-scryer",
            kind = "accept",
            priority = 153,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Test of Skulls, Scryer from Emberstrife.",
            dependsOn = { "turnin-6570-emberstrife" },
            complete = QuestState(6582, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6583-the-test-of-skulls-somnus",
            kind = "accept",
            priority = 154,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Test of Skulls, Somnus from Emberstrife.",
            complete = QuestState(6583, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6584-the-test-of-skulls-chronalis",
            kind = "accept",
            priority = 155,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Test of Skulls, Chronalis from Emberstrife.",
            complete = QuestState(6584, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "boss-chronalis",
            kind = "note",
            priority = 156,
            conditions = { level = { min = 57 } },
            text = "Kill Chronalis. It flies around this area. Killing it will require a full group.",
            dependsOn = { "boss-rage-talon-enemies-throughout-the-dungeon" },
        },
        {
            id = "objective-6584-1-the-skull-of-chronalis",
            kind = "objective",
            priority = 157,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect The Skull of Chronalis.",
            dependsOn = { "accept-6584-the-test-of-skulls-chronalis" },
            complete = QuestState(6584, "complete"),
            route = {
                Point(MAP.TANARIS, 0.641, 0.487, "Tanaris", "Travel to Tanaris."),
            },
        },
        {
            id = "boss-scryer",
            kind = "note",
            priority = 158,
            conditions = { level = { min = 57 } },
            text = "Kill Scryer. Inside the cave. It flies around this area. Killing it will require a full group.",
            dependsOn = { "boss-chronalis" },
        },
        {
            id = "objective-6582-1-the-skull-of-scryer",
            kind = "objective",
            priority = 159,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect The Skull of Scryer.",
            dependsOn = { "accept-6582-the-test-of-skulls-scryer" },
            complete = QuestState(6582, "complete"),
            route = {
                Point(MAP.WINTERSPRING, 0.529, 0.561, "Winterspring", "Travel to Winterspring."),
            },
        },
        {
            id = "boss-somnus",
            kind = "note",
            priority = 160,
            conditions = { level = { min = 57 } },
            text = "Kill Somnus. It flies around this area, between these two spots. Killing it will require a full group.",
            dependsOn = { "boss-scryer" },
        },
        {
            id = "objective-6583-1-the-skull-of-somnus",
            kind = "objective",
            priority = 161,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect The Skull of Somnus.",
            dependsOn = { "accept-6583-the-test-of-skulls-somnus" },
            complete = QuestState(6583, "complete"),
            route = {
                Point(MAP.SWAMP_OF_SORROWS, 0.804, 0.684, "Swamp of Sorrows", "Travel to Swamp of Sorrows."),
            },
        },
        {
            id = "turnin-6582-the-test-of-skulls-scryer",
            kind = "turnin",
            priority = 162,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Test of Skulls, Scryer to Emberstrife.",
            dependsOn = { "objective-6582-1-the-skull-of-scryer" },
            complete = QuestState(6582, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "turnin-6583-the-test-of-skulls-somnus",
            kind = "turnin",
            priority = 163,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Test of Skulls, Somnus to Emberstrife.",
            dependsOn = { "objective-6583-1-the-skull-of-somnus" },
            complete = QuestState(6583, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "turnin-6584-the-test-of-skulls-chronalis",
            kind = "turnin",
            priority = 164,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Test of Skulls, Chronalis to Emberstrife.",
            dependsOn = { "objective-6584-1-the-skull-of-chronalis" },
            complete = QuestState(6584, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6585-the-test-of-skulls-axtroz",
            kind = "accept",
            priority = 165,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept The Test of Skulls, Axtroz from Emberstrife.",
            dependsOn = { "turnin-6584-the-test-of-skulls-chronalis" },
            complete = QuestState(6585, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "boss-axtroz",
            kind = "note",
            priority = 166,
            conditions = { level = { min = 57 } },
            text = "Kill Axtroz. It flies back and forth between these two gates. Killing it will require a full group.",
            dependsOn = { "boss-somnus" },
        },
        {
            id = "objective-6585-1-the-skull-of-axtroz",
            kind = "objective",
            priority = 167,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect The Skull of Axtroz.",
            dependsOn = { "accept-6585-the-test-of-skulls-axtroz" },
            complete = QuestState(6585, "complete"),
            route = {
                Point(MAP.WETLANDS, 0.828, 0.489, "Wetlands", "Travel to Wetlands."),
            },
        },
        {
            id = "turnin-6585-the-test-of-skulls-axtroz",
            kind = "turnin",
            priority = 168,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in The Test of Skulls, Axtroz to Emberstrife.",
            dependsOn = { "objective-6585-1-the-skull-of-axtroz" },
            complete = QuestState(6585, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-6601-ascension",
            kind = "accept",
            priority = 169,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Ascension from Emberstrife.",
            dependsOn = { "turnin-6585-the-test-of-skulls-axtroz" },
            complete = QuestState(6601, "activeOrCompleted"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.567, 0.877, "Emberstrife", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "turnin-6601-ascension",
            kind = "turnin",
            priority = 170,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Ascension to Rexxar.",
            dependsOn = { "accept-6601-ascension" },
            complete = QuestState(6601, "completed"),
            useClientPin = true,
        },
        {
            id = "accept-6602-blood-of-the-black-dragon-champion",
            kind = "accept",
            priority = 171,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Accept Blood of the Black Dragon Champion from Rexxar.",
            complete = QuestState(6602, "activeOrCompleted"),
        },
        {
            id = "boss-general-drakkisath",
            kind = "note",
            priority = 172,
            conditions = { level = { min = 57 } },
            text = "Kill General Drakkisath. After entering the dungeon, follow the path to the left to enter the Upper Blackrock Spire. Someone in your group must have the Seal of Ascension in order to open the door. Follow the path in the dungeon to reach The Rookery. To start, if you have a hunter, you can have them kite General Drakkisath into The Beasts room and feign death while the group burns down the 'Chromatic Elite. You can also tank all 3 where they stand, AoEing down the Elite Guards as quickly as possible. Melee should stand behind Drakkisath at all times.",
            dependsOn = { "boss-axtroz" },
        },
        {
            id = "objective-6602-1-blood-of-the-black-drago",
            kind = "objective",
            priority = 173,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Collect Blood of the Black Dragon Champion.",
            dependsOn = { "accept-6602-blood-of-the-black-dragon-champion" },
            complete = QuestState(6602, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-6602-blood-of-the-black-dragon-champion",
            kind = "turnin",
            priority = 174,
            conditions = { all = { { faction = "Horde" }, { level = { min = 55 } } } },
            text = "Turn in Blood of the Black Dragon Champion to Rexxar.",
            dependsOn = { "objective-6602-1-blood-of-the-black-drago" },
            complete = QuestState(6602, "completed"),
            useClientPin = true,
        },
    },
})
