local _, ns = ...

local MAP = {
    THE_HINTERLANDS = 1425,
    BLASTED_LANDS = 1419,
    DUSTWALLOW_MARSH = 1445,
    THOUSAND_NEEDLES = 1441,
    TANARIS = 1446,
    FERALAS = 1444,
    HILLSBRAD_FOOTHILLS = 1424,
    DUROTAR = 1411,
}

local ALLIANCE = { faction = "Alliance" }
local HORDE = { faction = "Horde" }
local BOTH_FACTIONS = { any = { { faction = "Alliance" }, { faction = "Horde" } } }

local function QuestState(questID, state)
    return { quest = { id = questID, state = state } }
end

local function QuestObjective(questID, index, text)
    return { questObjective = { id = questID, index = index, text = text } }
end

local function Point(mapID, x, y, label, offMapText)
    return {
        mapID = mapID,
        x = x,
        y = y,
        label = label,
        offMapText = offMapText,
    }
end

ns:RegisterGuide({
    id = "dungeons-zul-farrak",
    title = "Zul'Farrak",
    category = "Dungeon Quest Guides",
    revision = 1,
    conditions = {
        all = {
            { level = { min = 40 } },
            BOTH_FACTIONS,
        },
    },
    goals = {
        {
            id = "accept-2988-witherbark-cages",
            kind = "accept",
            priority = 10,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Accept Witherbark Cages from Gryphon Master Talonaxe.",
            complete = QuestState(2988, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "objective-2988-1-check-the-first-cage",
            kind = "objective",
            priority = 12,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Check the First Witherbark Cage east of the Altar of Zul in the Hinterlands.",
            dependsOn = { "accept-2988-witherbark-cages" },
            complete = QuestObjective(2988, 1, "Check the First Cage"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.233, 0.588, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "objective-2988-2-check-the-second-cage",
            kind = "objective",
            priority = 14,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Check the Second Witherbark Cage by the river in the Hinterlands.",
            dependsOn = { "accept-2988-witherbark-cages" },
            complete = QuestObjective(2988, 2, "Check the Second Cage"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.231, 0.588, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "objective-2988-3-check-the-third-cage",
            kind = "objective",
            priority = 16,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Check the Third Witherbark Cage at the Quel'Danil Lodge in the Hinterlands.",
            dependsOn = { "accept-2988-witherbark-cages" },
            complete = QuestObjective(2988, 3, "Check the Third Cage"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.320, 0.574, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-2988-witherbark-cages",
            kind = "turnin",
            priority = 17,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 48 } } } },
            text = "Turn in Witherbark Cages to Gryphon Master Talonaxe.",
            dependsOn = { "objective-2988-1-check-the-first-cage", "objective-2988-2-check-the-second-cage", "objective-2988-3-check-the-third-cage" },
            complete = QuestState(2988, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-2989-the-altar-of-zul",
            kind = "accept",
            priority = 18,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Accept The Altar of Zul from Gryphon Master Talonaxe.",
            dependsOn = { "turnin-2988-witherbark-cages" },
            complete = QuestState(2989, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "objective-2989-1-search-the-altar-of-zul",
            kind = "objective",
            priority = 19,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Search the Altar of Zul in the Hinterlands for clues to the missing trolls.",
            dependsOn = { "accept-2989-the-altar-of-zul" },
            complete = QuestState(2989, "complete"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.488, 0.684, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-2989-the-altar-of-zul",
            kind = "turnin",
            priority = 20,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 51 } } } },
            text = "Turn in The Altar of Zul to Gryphon Master Talonaxe.",
            dependsOn = { "objective-2989-1-search-the-altar-of-zul" },
            complete = QuestState(2989, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "accept-2990-thadius-grimshade",
            kind = "accept",
            priority = 21,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Thadius Grimshade from Gryphon Master Talonaxe.",
            dependsOn = { "turnin-2989-the-altar-of-zul" },
            complete = QuestState(2990, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.098, 0.445, "Gryphon Master Talonaxe", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-2990-thadius-grimshade",
            kind = "turnin",
            priority = 22,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Thadius Grimshade to Thadius Grimshade.",
            dependsOn = { "accept-2990-thadius-grimshade" },
            complete = QuestState(2990, "completed"),
            route = {
                Point(MAP.BLASTED_LANDS, 0.669, 0.195, "Thadius Grimshade", "Travel to Blasted Lands."),
            },
        },
        {
            id = "accept-2991-nekrum-s-medallion",
            kind = "accept",
            priority = 23,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Accept Nekrum's Medallion from Thadius Grimshade.",
            dependsOn = { "turnin-2990-thadius-grimshade" },
            complete = QuestState(2991, "activeOrCompleted"),
            route = {
                Point(MAP.BLASTED_LANDS, 0.669, 0.195, "Thadius Grimshade", "Travel to Blasted Lands."),
            },
        },
        {
            id = "accept-2846-tiara-of-the-deep",
            kind = "accept",
            priority = 25,
            conditions = { level = { min = 46 } },
            text = "Accept Tiara of the Deep from Tabetha.",
            complete = QuestState(2846, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.672, 0.733, "Tabetha", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.645, 0.750, "Tabetha", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.622, 0.714, "Tabetha", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.599, 0.702, "Tabetha", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.592, 0.741, "Tabetha", "Travel to The Hinterlands."),
                Point(MAP.DUSTWALLOW_MARSH, 0.461, 0.571, "Tabetha", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "accept-2770-gahz-rilla",
            kind = "accept",
            priority = 26,
            conditions = { level = { min = 40 } },
            text = "Accept Gahz'rilla from Wizzle Brassbolts.",
            complete = QuestState(2770, "activeOrCompleted"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.781, 0.771, "Wizzle Brassbolts", "Travel to Thousand Needles."),
            },
        },
        {
            id = "accept-3520-screecher-spirits",
            kind = "accept",
            priority = 27,
            conditions = { level = { min = 49 } },
            text = "Accept Screecher Spirits from Yeh'kinya.",
            complete = QuestState(3520, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "objective-3520-1-screecher-spirits",
            kind = "objective",
            priority = 29,
            conditions = { level = { min = 49 } },
            text = "Use Yeh'kinya's Bramble on 3 Screecher spirits in Feralas when they die to capture their spirits.",
            dependsOn = { "accept-3520-screecher-spirits" },
            complete = QuestState(3520, "complete"),
            route = {
                Point(MAP.FERALAS, 0.583, 0.577, "Feralas", "Travel to Feralas."),
            },
        },
        {
            id = "turnin-3520-screecher-spirits",
            kind = "turnin",
            priority = 30,
            conditions = { level = { min = 49 } },
            text = "Turn in Screecher Spirits to Yeh'kinya.",
            dependsOn = { "objective-3520-1-screecher-spirits" },
            complete = QuestState(3520, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3527-the-prophecy-of-mosh-aru",
            kind = "accept",
            priority = 31,
            conditions = { level = { min = 46 } },
            text = "Accept The Prophecy of Mosh'aru from Yeh'kinya.",
            dependsOn = { "turnin-3520-screecher-spirits" },
            complete = QuestState(3527, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-2768-divino-matic-rod",
            kind = "accept",
            priority = 32,
            conditions = { level = { min = 46 } },
            text = "Accept Divino-matic Rod from Chief Engineer Bilgewhizzle.",
            complete = QuestState(2768, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.525, 0.285, "Chief Engineer Bilgewhizzle", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-2865-scarab-shells",
            kind = "accept",
            priority = 33,
            conditions = { level = { min = 46 } },
            text = "Accept Scarab Shells from Tran'rek.",
            complete = QuestState(2865, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.516, 0.268, "Tran'rek", "Travel to Tanaris."),
            },
        },
        {
            id = "accept-3042-troll-temper",
            kind = "accept",
            priority = 34,
            conditions = { level = { min = 46 } },
            text = "Accept Troll Temper from Trenton Lighthammer.",
            complete = QuestState(3042, "activeOrCompleted"),
            route = {
                Point(MAP.TANARIS, 0.514, 0.287, "Trenton Lighthammer", "Travel to Tanaris."),
            },
        },
        {
            id = "enter-dungeon",
            kind = "travel",
            priority = 35,
            conditions = { level = { min = 40 } },
            text = "Enter Zul'Farrak with your group.",
            dependsOn = { "accept-2988-witherbark-cages", "accept-2989-the-altar-of-zul", "accept-2990-thadius-grimshade", "accept-2991-nekrum-s-medallion", "accept-2846-tiara-of-the-deep", "accept-2770-gahz-rilla", "accept-3520-screecher-spirits", "accept-3527-the-prophecy-of-mosh-aru", "accept-2768-divino-matic-rod", "accept-2865-scarab-shells", "accept-3042-troll-temper" },
            persistCompletion = true,
            complete = { instance = 209 },
        },
        {
            id = "objective-3527-1-first-mosh-aru-tablet",
            kind = "objective",
            priority = 37,
            conditions = { level = { min = 46 } },
            text = "Loot the First Mosh'aru Tablet from Theka the Martyr's pit in Zul'Farrak.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 1, "First Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-2991-1-nekrum-s-medallion",
            kind = "objective",
            priority = 41,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Kill Nekrum Gutchewer and loot Nekrum's Medallion.",
            dependsOn = { "accept-2991-nekrum-s-medallion" },
            complete = QuestState(2991, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2768-1-divino-matic-rod",
            kind = "objective",
            priority = 43,
            conditions = { level = { min = 46 } },
            text = "Kill Sergeant Bly and loot the Divino-matic Rod.",
            dependsOn = { "accept-2768-divino-matic-rod" },
            complete = QuestState(2768, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2846-1-tiara-of-the-deep",
            kind = "objective",
            priority = 45,
            conditions = { level = { min = 46 } },
            text = "Kill Hydromancer Velratha and loot the Tiara of the Deep.",
            dependsOn = { "accept-2846-tiara-of-the-deep" },
            complete = QuestState(2846, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-3527-2-second-mosh-aru-tablet",
            kind = "objective",
            priority = 46,
            conditions = { level = { min = 46 } },
            text = "Loot the Second Mosh'aru Tablet from the troll altar near Antu'sul in Zul'Farrak.",
            dependsOn = { "accept-3527-the-prophecy-of-mosh-aru" },
            complete = QuestObjective(3527, 2, "Second Mosh'aru Tablet"),
            useClientPin = true,
        },
        {
            id = "objective-2770-1-gahz-rilla-s-electrified",
            kind = "objective",
            priority = 48,
            conditions = { level = { min = 40 } },
            text = "Use the Mallet of Zul'Farrak on the Gong, then kill Gahz'rilla and loot Gahz'rilla's Electrified Scale.",
            dependsOn = { "accept-2770-gahz-rilla" },
            complete = QuestState(2770, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-2865-1-uncracked-scarab-shell",
            kind = "objective",
            priority = 50,
            conditions = { level = { min = 46 } },
            text = "Kill Scarabs in Zul'Farrak until you loot 5 Uncracked Scarab Shell.",
            dependsOn = { "accept-2865-scarab-shells" },
            complete = QuestState(2865, "complete"),
            useClientPin = true,
        },
        {
            id = "objective-3042-1-troll-temper",
            kind = "objective",
            priority = 52,
            conditions = { level = { min = 46 } },
            text = "Kill trolls in Zul'Farrak until you loot 20 Troll Temper.",
            dependsOn = { "accept-3042-troll-temper" },
            complete = QuestState(3042, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-3527-the-prophecy-of-mosh-aru",
            kind = "turnin",
            priority = 55,
            conditions = { level = { min = 46 } },
            text = "Turn in The Prophecy of Mosh'aru to Yeh'kinya.",
            dependsOn = { "objective-3527-1-first-mosh-aru-tablet", "objective-3527-2-second-mosh-aru-tablet" },
            complete = QuestState(3527, "completed"),
            route = {
                Point(MAP.TANARIS, 0.670, 0.224, "Yeh'kinya", "Travel to Tanaris."),
            },
        },
        {
            id = "turnin-2768-divino-matic-rod",
            kind = "turnin",
            priority = 56,
            conditions = { level = { min = 46 } },
            text = "Turn in Divino-matic Rod to Chief Engineer Bilgewhizzle.",
            dependsOn = { "objective-2768-1-divino-matic-rod" },
            complete = QuestState(2768, "completed"),
            route = {
                Point(MAP.TANARIS, 0.525, 0.285, "Chief Engineer Bilgewhizzle", "Travel to Tanaris."),
            },
        },
        {
            id = "turnin-2865-scarab-shells",
            kind = "turnin",
            priority = 57,
            conditions = { level = { min = 46 } },
            text = "Turn in Scarab Shells to Tran'rek.",
            dependsOn = { "objective-2865-1-uncracked-scarab-shell" },
            complete = QuestState(2865, "completed"),
            route = {
                Point(MAP.TANARIS, 0.516, 0.268, "Tran'rek", "Travel to Tanaris."),
            },
        },
        {
            id = "turnin-3042-troll-temper",
            kind = "turnin",
            priority = 58,
            conditions = { level = { min = 46 } },
            text = "Turn in Troll Temper to Trenton Lighthammer.",
            dependsOn = { "objective-3042-1-troll-temper" },
            complete = QuestState(3042, "completed"),
            route = {
                Point(MAP.TANARIS, 0.514, 0.287, "Trenton Lighthammer", "Travel to Tanaris."),
            },
        },
        {
            id = "turnin-2770-gahz-rilla",
            kind = "turnin",
            priority = 59,
            conditions = { level = { min = 40 } },
            text = "Turn in Gahz'rilla to Wizzle Brassbolts.",
            dependsOn = { "objective-2770-1-gahz-rilla-s-electrified" },
            complete = QuestState(2770, "completed"),
            route = {
                Point(MAP.THOUSAND_NEEDLES, 0.781, 0.771, "Wizzle Brassbolts", "Travel to Thousand Needles."),
            },
        },
        {
            id = "turnin-2846-tiara-of-the-deep",
            kind = "turnin",
            priority = 60,
            conditions = { level = { min = 46 } },
            text = "Turn in Tiara of the Deep to Tabetha.",
            dependsOn = { "objective-2846-1-tiara-of-the-deep" },
            complete = QuestState(2846, "completed"),
            route = {
                Point(MAP.DUSTWALLOW_MARSH, 0.461, 0.571, "Tabetha", "Travel to Dustwallow Marsh."),
            },
        },
        {
            id = "turnin-2991-nekrum-s-medallion",
            kind = "turnin",
            priority = 61,
            conditions = { all = { { faction = "Alliance" }, { level = { min = 40 } } } },
            text = "Turn in Nekrum's Medallion to Thadius Grimshade.",
            dependsOn = { "objective-2991-1-nekrum-s-medallion" },
            complete = QuestState(2991, "completed"),
            route = {
                Point(MAP.BLASTED_LANDS, 0.669, 0.195, "Thadius Grimshade", "Travel to Blasted Lands."),
            },
        },
        {
            id = "accept-2933-venom-bottles",
            kind = "accept",
            priority = 63,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Loot Venom Bottles from the Revantusk troll camp in the Hinterlands. " ..
                "Use them to accept Venom Bottles.",
            complete = QuestState(2933, "activeOrCompleted"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.235, 0.588, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-2933-venom-bottles",
            kind = "turnin",
            priority = 64,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in Venom Bottles to Apothecary Lydon.",
            dependsOn = { "accept-2933-venom-bottles" },
            complete = QuestState(2933, "completed"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.672, 0.733, "Apothecary Lydon", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.645, 0.750, "Apothecary Lydon", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.622, 0.714, "Apothecary Lydon", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.599, 0.702, "Apothecary Lydon", "Travel to The Hinterlands."),
                Point(MAP.THE_HINTERLANDS, 0.592, 0.741, "Apothecary Lydon", "Travel to The Hinterlands."),
                Point(MAP.HILLSBRAD_FOOTHILLS, 0.614, 0.191, "Apothecary Lydon", "Travel to Hillsbrad Foothills."),
            },
        },
        {
            id = "accept-2934-undamaged-venom-sac",
            kind = "accept",
            priority = 65,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Accept Undamaged Venom Sac from Apothecary Lydon.",
            dependsOn = { "turnin-2933-venom-bottles" },
            complete = QuestState(2934, "activeOrCompleted"),
            route = {
                Point(MAP.HILLSBRAD_FOOTHILLS, 0.614, 0.191, "Apothecary Lydon", "Travel to Hillsbrad Foothills."),
            },
        },
        {
            id = "objective-2934-1-undamaged-venom-sac",
            kind = "objective",
            priority = 67,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Kill Venomtip Scorpids in the Hinterlands until you loot an Undamaged Venom Sac.",
            dependsOn = { "accept-2934-undamaged-venom-sac" },
            complete = QuestState(2934, "complete"),
            route = {
                Point(MAP.THE_HINTERLANDS, 0.348, 0.695, "The Hinterlands", "Travel to The Hinterlands."),
            },
        },
        {
            id = "turnin-2934-undamaged-venom-sac",
            kind = "turnin",
            priority = 68,
            conditions = { all = { { faction = "Horde" }, { level = { min = 48 } } } },
            text = "Turn in Undamaged Venom Sac to Apothecary Lydon.",
            dependsOn = { "objective-2934-1-undamaged-venom-sac" },
            complete = QuestState(2934, "completed"),
            route = {
                Point(MAP.HILLSBRAD_FOOTHILLS, 0.614, 0.191, "Apothecary Lydon", "Travel to Hillsbrad Foothills."),
            },
        },
        {
            id = "accept-2935-consult-master-gadrin",
            kind = "accept",
            priority = 69,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Accept Consult Master Gadrin from Apothecary Lydon.",
            dependsOn = { "turnin-2934-undamaged-venom-sac" },
            complete = QuestState(2935, "activeOrCompleted"),
            route = {
                Point(MAP.HILLSBRAD_FOOTHILLS, 0.614, 0.191, "Apothecary Lydon", "Travel to Hillsbrad Foothills."),
            },
        },
        {
            id = "turnin-2935-consult-master-gadrin",
            kind = "turnin",
            priority = 70,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Turn in Consult Master Gadrin to Master Gadrin.",
            dependsOn = { "accept-2935-consult-master-gadrin" },
            complete = QuestState(2935, "completed"),
            route = {
                Point(MAP.DUROTAR, 0.559, 0.747, "Master Gadrin", "Travel to Durotar."),
            },
        },
        {
            id = "accept-2936-the-spider-god",
            kind = "accept",
            priority = 71,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Accept The Spider God from Master Gadrin.",
            dependsOn = { "turnin-2935-consult-master-gadrin" },
            complete = QuestState(2936, "activeOrCompleted"),
            route = {
                Point(MAP.DUROTAR, 0.559, 0.747, "Master Gadrin", "Travel to Durotar."),
            },
        },
        {
            id = "objective-2936-1-the-spider-god-s-name",
            kind = "objective",
            priority = 74,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Inside Zul'Farrak, read the Spider God tablet at the troll altar to learn the Spider God's name.",
            dependsOn = { "accept-2936-the-spider-god" },
            complete = QuestState(2936, "complete"),
            useClientPin = true,
        },
        {
            id = "turnin-2936-the-spider-god",
            kind = "turnin",
            priority = 79,
            conditions = { all = { { faction = "Horde" }, { level = { min = 40 } } } },
            text = "Turn in The Spider God to Master Gadrin.",
            dependsOn = { "objective-2936-1-the-spider-god-s-name" },
            complete = QuestState(2936, "completed"),
            route = {
                Point(MAP.DUROTAR, 0.559, 0.747, "Master Gadrin", "Travel to Durotar."),
            },
        },
    },
})
